### ISSUE TITLE
Favorites as a Geonode Plugin

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1001]
Contribute Favorites feature back to GeoNode as an optional module.

---

As an authenticated user I would like to mark layers, documents and maps as favorites in Geonode so that I can quickly revisit them at a later date.

Acceptance Criteria:

Favorites button is available on Layers, Maps, and Documents
User profile page list favorite layers, maps, and documents in the appropriate tab under the resources group.
Any model that extends Resourcebase will be eligible to use the Favorites plugin
The plugin is available under the contrib directory
The favorite activity is logged to the activity stream"

**Comment by jwood106** [comment]
Contributed Favorites back to GeoNode as an optional contrib module.
Submitted it as a pull request https://github.com/GeoNode/geonode/pull/2165 and revised the submission per GeoNode developer feedback.

**Comment by jwood106** [comment]
The GeoNode pull request referenced in previous comment has now been reviewed and merged.

**Comment by jonpmarino** [comment]
@jwood106 great! pulled into beta?

**Comment by jwood106** [comment]
@jonpmarino This issue was to contribute it to GeoNode.
I created issue https://github.com/MapStory/mapstory/issues/1105 this morning to add Favorites to MapStory v2.
