### ISSUE TITLE
Contribute Intraplatform Messaging to GeoNode

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1005]
Implement interplatform messaging on MapStory v2
Modularize MapStory Messaging
Ensure Proper Test Coverage
Submit Pull Request to GeoNode

**Comment by jonpmarino** [comment]
Not sure where we ended up with this.

**Comment by jonpmarino** [comment]
@jwood106 see live implementation of this on v1 production site. Goal is to basically inherit the same functionality on production

**Comment by garnertb** [comment]
Intraplatform messaging is coming from https://github.com/GeoNode/geonode-user-messages, which is already implemented in GeoNode.  Closing.
