### ISSUE TITLE
Implement threaded comments. Potentially contribute to GeoNode

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1006]
Implement django-threaded comments tool.

Evaluate Threaded Comments as a possible contrib module to be submitted to GeoNode.

Ensure Proper Test Coverage
Submit Pull Request to GeoNode

**Comment by jwood106** [comment]
At this time (Friday 5/29 standup mtg), we (Clarence and I) recommended that we not contribute this back to GeoNode as a contrib module.

Note: we do still need to add threaded comments to MapStory v2.
