### ISSUE TITLE
Story Pins Editor

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1013]
Create/edit pins
![image](https://cloud.githubusercontent.com/assets/11614809/7616956/ccd8e90a-f96d-11e4-9396-97562b956015.png)

**Comment by bartvde** [comment]
except for the media part this is done

**Comment by davisc** [comment]
I've been able to integrate storytools into the mapstory-geonode project and add the media buttons to the StoryPins form. Final task is to wire up the buttons to the backend functionality.
