### ISSUE TITLE
Story Pins Bulk Upload

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1014]
upload .shp file with pins
![image](https://cloud.githubusercontent.com/assets/11614809/7616611/5a9022c0-f96b-11e4-89e8-a22542be71bc.png)

**Comment by jonpmarino** [comment]
@zrouse-Boundless Currently we support bulk upload of annotations as CSV as well. Will want to maintain that in new build

**Comment by ischneider** [comment]
shapefile would be an addition - currently only CSV supported though technically the API endpoint accepts geojson so it wouldn't be hard to add that, too

**Comment by ischneider** [comment]
depends on #1011 - either in geonode or mapstory-geonode
