### ISSUE TITLE
wps classify branch

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#1019]
get jdeolive's wps classification into geoserver, currently resides on a branch here:
https://github.com/boundlessgeo/geoserver/tree/wps_classify-2.6.x

this _should_ work but didn't get a chance to test on 2.6.x - testing had been done with the last 4 commits on master/2.7.x at the time of this writing

**Comment by jonpmarino** [comment]
a holdover for Ian. Assigning to @davisc to determine if still relevant

**Comment by davisc** [comment]
@emerkle826 pushed changes made to get these to compile.

GeoTools (based on version 12.x) - https://github.com/emerkle826/geotools/tree/wps_classify_revive2
GeoServer (based on the boundlessgeo/wps_classify-2.6.x branch) - https://github.com/emerkle826/geoserver/tree/wps_classify_revive2

For this to work, you have to compile 3 modules in GeoTools and then the WPS-core extension in GeoServer. The 3 GeoTools modules are:
- process
- process-feature
- process-raster

The compile wps-core in GeoServer src/extensions/wps

**Comment by davisc** [comment]
The compiled jars are available here:
https://s3-us-west-2.amazonaws.com/mapstory-resources/geoserver/2.6/libs/wps/classify.zip

**Comment by davisc** [comment]
An Ansible task has been added to the provision scripts to download and deploy the .jar files.
