### ISSUE TITLE
Need a longer character limit for Journal entry titles

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1022]
Current set way too short.

**Comment by travislbrundage** [comment]
What's a reasonable character limit for this?

**Comment by jonpmarino** [comment]
Does there have to be a limit? If so, a good marker is the longest title of the essays on current mapstory.org

**Comment by travislbrundage** [comment]
Technically I think there doesn't need to be, but I'll ask others if it's unwise for some reason.

**Comment by garnertb** [comment]
@travislbrundage, I suggest trying to find a reasonable limit of characters or at least use the truncatechars template tag (https://docs.djangoproject.com/en/1.8/ref/templates/builtins/#truncatechars) to reduce the length on the client-side, just to be safe.

**Comment by jonpmarino** [comment]
Agreed. Not huge so don't get hung up. Make sure this fits, beyond-pushpin-mapping-the-power-of-crisis-mapstorytelling. How's that?

**Comment by garnertb** [comment]
Thats 58 characters, I'd start with 255 just to see how it goes.

**Comment by travislbrundage** [comment]
I was incorrect, it requires a max character limit. I've set it to 128 characters, which is about this long. Closed by [Pull Request #36](https://github.com/MapStory/mapstory-geonode/pull/36).

**Comment by travislbrundage** [comment]
Closed by [Pull Request #36](https://github.com/MapStory/mapstory-geonode/pull/36)

**Comment by jonpmarino** [comment]
;)
