### ISSUE TITLE
layer time dimension can not be enabled in upload

### ISSUE THREAD

**Issue by jwood106** [MapStory/mapstory-meta#1023]
On MapStory dev, when user uploads a layer with time dimension, time dimension does not get enabled.

We(Zach, Travis, Tyler, Clarence, Jeff) saw this while looking into time issue Travis was having while working on viewer time slider.  When user uploads layer, can check a time checkbox, then sees an input screen to configure some time vars.  Get error msg when attempt to save.
Workaround (only available to GeoServer admin) is to enable the layer's time dimension through the GeoServer admin UI.  Then layer performed as expected in viewer time slider.

**Comment by ischneider** [comment]
The uploader has been a source of many problems so it's quite possible this has broken.

In V1, this was configured during ingest using the GeoServer REST API. I think using this code: https://github.com/boundlessgeo/geonode/blob/52b59f7e19f7a18dabbee6af4a4e29a19c136d1a/src/gsuploader/src/gsuploader/api.py#L266
My guess is something similar is in use in GeoNode master.

Ideally, a user would be able to modify this configuration _after_ the upload as well.

cc @jonpmarino

**Comment by garnertb** [comment]
This is fixed.
