### ISSUE TITLE
Update: In Profile, should be "create a new MapStory" or "Upload StoryLayers"

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1027]
Need to keep this terminology consistent throughout.

**Comment by jwood106** [comment]
i see two left nav 'user actions'  for layer and map.  will replace their wording per wording on Rey's profile page mockup:
upload new layers -> upload storylayer
create a new map -> create a mapstory

**Comment by reynalddizon** [comment]
Thanks @jwood106

**Comment by jwood106** [comment]
done.
https://github.com/MapStory/mapstory-geonode/commit/98e61dd67c5d63dbc9d91bb663d5f6a2e75fb82e

**Comment by jonpmarino** [comment]
Can we do no space between story and layer....storylayer. Need consistency

**Comment by jonpmarino** [comment]
Nice! My mistake

**Comment by jwood106** [comment]
@jonpmarino 
yes, my original comment had the errant space.  noticed my mistake while implementing.  thx for looking it over.
