### ISSUE TITLE
Creating a new user on Beta hangs and fails

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1030]

**Comment by jwood106** [comment]
To set up new account, user is asked for first name, last name, email, password.  I filled out the info, checked the terms, pressed submit.  Received no error msg. 
Then i went to log in and it asks for username and password.  not sure what it is thinking the username is, that was not one of the input field labels. (just noticed this has its own issue, #1031.) 
Tyler went through the UI and 'created' three users.  He looked at the back end and saw none of them were created.

**Comment by garnertb** [comment]
Fixed in https://github.com/MapStory/mapstory-geonode/commit/e2579c97d1a46854f2347605989e33a6560b8311.

**Comment by davisc** [comment]
These changes are now available on the dev site.

**Comment by garnertb** [comment]
Awesome, thanks!
