### ISSUE TITLE
Featured MapStories on the homepage

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1032]
We need to add Featured MapStories after the first homepage section. See attachment. Needs design refinement. The list should be pull from site admin's favorites. Also, "Biology" should be "Biography"

![screen shot 2015-06-18 at 3 20 55 pm](https://cloud.githubusercontent.com/assets/4611843/8240037/e9edf964-15cd-11e5-957f-b3ad1f531fa0.png)

**Comment by travislbrundage** [comment]
Related to Issue #1073. For now, getting it to display just any featured MapStories, then later when the correct categories are worked in, will add those queries.

**Comment by jonpmarino** [comment]
Correct. Sorry for duplicate

**Comment by travislbrundage** [comment]
Closed by [Pull Request #56](https://github.com/MapStory/mapstory-geonode/pull/56)
