### ISSUE TITLE
Navigation Bar design refinement

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1038]
The drop down button looks a bit weird. The How-To drop down menu should behave the same way as the "admin" menu (the last item.) Remove the shadow effect whenever we click on the How-To menu and the border surrounding the words "How-to". Align the admin avatar with the other elements of the navbar.

**Comment by garnertb** [comment]
I think I got all of these.  

![screen shot 2015-06-18 at 11 02 30 pm](https://cloud.githubusercontent.com/assets/1141646/8246547/3d3158d8-160e-11e5-9708-b7e684a3e636.png)
