### ISSUE TITLE
Explore page design refinements

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1040]
1. Remove the bullet points on the items under What's Hot
2. Uniform typography on the items under Refine Search.
3. On the Topics filter, replace the number badge on the right hand side with a checkmark (if the item is selected) and if unselected, leave the right hand side blank.
4. Fix the height of the vertical divider. (Currently, it depends on the height of the content of the right hand panel.)

**Comment by travislbrundage** [comment]
I think 2. was already addressed when Jon updated the wording to What, When, and Where. Please let me know if it still looks wrong, because it looks uniform to me right now.

**Comment by travislbrundage** [comment]
Fixed 1 and 3. I'm sorry, but I'm not sure I understand what is desired differently for 4? Maybe we can talk about this tomorrow? Or maybe a visual would help me understand... the way I see it the vertical divider is above both, not just dependent on the right hand panel, but maybe I'm looking at something wrong.

**Comment by reynalddizon** [comment]
The vertical divider is dependent on the height of the content of the search results the more search results shown, the longer the vertical divider, see screen cap. The vertical divider here is the border-left style attribute of the class "col-lg-9". 

![screen shot 2015-06-26 at 8 10 02 am](https://cloud.githubusercontent.com/assets/4611843/8376968/e87bb716-1bda-11e5-80da-cca2a3bd9401.png)

My idea is to fix the height of this divider by setting a fixed height for the right hand side panel (col-lg-9), no matter how many search results there are.

**Comment by travislbrundage** [comment]
Ah okay, I understand now. Thanks for the further clarification and picture Rey, that helped a lot!

**Comment by reynalddizon** [comment]
@travislbrundage since you're working on refining the explore page already, might be good to address Issues #1065 and #1066 too.

**Comment by travislbrundage** [comment]
Closed by [Pull Request #64](https://github.com/MapStory/mapstory-geonode/pull/64)
