### ISSUE TITLE
Sign up modal design refinement

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1041]
-Align the elements (textboxes and label)
-Make the Login button more prominent (Maybe a gray fill?)
-Remove the Twitter and Yahoo sign up options.
-Link the terms and conditions text to http://wiki.mapstory.org/wiki/Terms_of_Service

**Comment by garnertb** [comment]
Fixed in https://github.com/MapStory/mapstory-geonode/commit/1e47d0427d5575499a87fd4b09301379dfdbd1d6.
