### ISSUE TITLE
Need to ensure get page model enables video embed - YouTube or Vimeo

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1044]
On each of the get pages (get skills, get started, get resources) we need to be able to add a video embed. Need to make sure that is reflected in the django module.

**Comment by travislbrundage** [comment]
This is basically done, but there are some compatibility concerns. According to caniuse.com/#feat=video it looks like the video format with the most compatibility is .mp4. However, even with that, older versions of Firefox won't support it. I'm just wondering how much of a concern this should be? What are the plans for uploading videos? Will they always be .mp4?

**Comment by reynalddizon** [comment]
We're pretty flexible on video formats, just do whats the most practical and we'll convert the videos accordingly.

**Comment by travislbrundage** [comment]
@jonpmarino You just changed it to a YouTube or Vimeo embed? So you want to embed a link to a different hosting site then? Maybe I misunderstood, I thought the desire was to upload a video file (such as .mp4) to the django model and have it appear on the page.

**Comment by jonpmarino** [comment]
I think embed of external link would be easier long run

**Comment by travislbrundage** [comment]
It'll allow us to ignore compatibility issues, so I agree, I think that will be easier. I already finished it the one way though so I'll keep the branch existing in case it's desired at any point. Can always do both, as well.

**Comment by travislbrundage** [comment]
Closed by [Pull Request #65](https://github.com/MapStory/mapstory-geonode/pull/65)
