### ISSUE TITLE
Footer links

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1048]
Contact: http://wiki.mapstory.org/wiki/The_MapStory_Foundation
Developers: http://wiki.mapstory.org/wiki/Developers
Press: http://wiki.mapstory.org/wiki/The_MapStory_Foundation#News_Coverage
Disclaimers: http://wiki.mapstory.org/wiki/Terms_of_Service
Values: http://wiki.mapstory.org/wiki/Community_Ethics
--Add link in footer to wiki.mapstory.org

**Comment by garnertb** [comment]
And leave About, Blog, Mobile View blank?

**Comment by garnertb** [comment]
Closed in https://github.com/MapStory/mapstory-geonode/pull/39.

**Comment by jonpmarino** [comment]
About goes to get started. The first get started section will be a meta about video. Blog goes to blog.mapstory.org

**Comment by davisc** [comment]
These changes have been deployed to mapstory.dev.opengeo.org
