### ISSUE TITLE
"MapStory Wiki" on Get Skills section of MapStory homepage goes to wiki.mapstory.org

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1050]

**Comment by garnertb** [comment]
Sorry, its not clear to me what you're getting at with this issue.    Are you saying that the MapStory Wiki text should be turned into a link?

**Comment by reynalddizon** [comment]
Yeah, i think that's what Jon meant.

**Comment by travislbrundage** [comment]
Closed by [Pull Request #38](https://github.com/MapStory/mapstory-geonode/pull/38)
