### ISSUE TITLE
Get Involved homepage section change

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1052]
Change circles for Get Involved to a single picture of the community (see attached). May the word "join" a hyperlink to Get Involved.
![123456](https://cloud.githubusercontent.com/assets/2573761/8257542/560f4acc-167c-11e5-991b-a6a0a0f2cdb9.jpg)

**Comment by garnertb** [comment]
@jonpmarino, can you add the link to the picture you want to use to this issue?  (I've seen it before but I don't remember where).

**Comment by jonpmarino** [comment]
sent by email

**Comment by travislbrundage** [comment]
Closed by [Pull Request #53](https://github.com/MapStory/mapstory-geonode/pull/53)
