### ISSUE TITLE
Change Topics, Time Periods, Places to What, When, Where on Explore

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1054]

**Comment by garnertb** [comment]
![screen shot 2015-06-19 at 7 51 43 pm](https://cloud.githubusercontent.com/assets/1141646/8265008/172fb7f6-16bd-11e5-97b5-1c4885d27eb3.png)

**Comment by reynalddizon** [comment]
Yes, Topics (What), Places (Where) and Time Period (When), Keywords will remain the same.

**Comment by jwood106** [comment]
done.
https://github.com/MapStory/mapstory-geonode/commit/be41a90ac08eef5da62c332f69627a312fbd2c11
Also, in screenshot above, Topics and Places are darker than Time Periods and Keywords.  Revised the html to make all four Refine Search choices consistent.

**Comment by jonpmarino** [comment]
Nice!
