### ISSUE TITLE
Apply Rey's designs for "update profile" form

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1057]
And, we need a create profile form for Organization Pages. The current "update profile" form we have for individual accounts actually looks like it could basically work for Org Page create with mods. The trick here is that we don't want anyone to create Org Pages. You'll see that in the "create account" module there is a  link for "Signing Up as an Organization? Click here"...This will link to a wiki with some details and contact.

**Comment by reynalddizon** [comment]
![screen shot 2015-06-21 at 10 58 02 am](https://cloud.githubusercontent.com/assets/4611843/8272100/79f2caf2-1804-11e5-9cf7-063e64bc3a71.png)

**Comment by reynalddizon** [comment]
Add "Join Volunteer Technical Community?" checkbox after the Help emails checkbox. Checking this will add an attribute to the user: volunteer.
