### ISSUE TITLE
Update graphics and links in Donate Now page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1058]
http://mapstory.dev.boundlessgeo.com/donate.

See current mapstory.org implementation for example - http://mapstory.org/mapstory/donate/

Need Paypal link on Donate Now, https://www.paypal.com/us/cgi-bin/webscr?cmd=_flow&SESSION=JOgiHBBWV826YcB69U-SRSJ62GjPO0VK4YrDF0THHw_yVyLhK9YoVspcHY0&dispatch=5885d80a13c0db1f8e263663d3faee8de6030e9239419d79c3f52f70a3ed57ec.

Buy an Organization Page will go to a Get Involved section...TBD.

Eliminate "Sponsor". Graphics for both are here -
![unnamed](https://cloud.githubusercontent.com/assets/2573761/8297918/f371da0e-192f-11e5-8fae-05163ffd26e3.jpg)
![unnamed-1](https://cloud.githubusercontent.com/assets/2573761/8297919/f8c968f0-192f-11e5-8e31-0a333cd528b1.jpg)

**Comment by davisc** [comment]
Is the paypal link configured with mapstory.org as the allowed referrer? If so, this link will not be authorized from another domain.
