### ISSUE TITLE
Have graphics on Get Started on home click to approach sections on Get Started page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1059]
The logic is that clicking on one of the graphics (i.e. Journalists) on Get Started home will take you to the jump on the Get Started page for that paragraph

**Comment by reynalddizon** [comment]
Is there a way to update the get started graphics thru the get page django admin model?

**Comment by travislbrundage** [comment]
@reynalddizon I don't think there is right now... Right now the images are being grabbed through mapstory-assets.

Closed by [Pull Request #46](https://github.com/MapStory/mapstory-geonode/pull/46)
