### ISSUE TITLE
Change default masking text for "external link" in get page contents

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1063]
Currently the word "more" defaults for the link (see http://mapstory.dev.boundlessgeo.com/getstarted). It would be nice to be a bit more precise and say "More resources for students" (change depending on Get content title)

**Comment by garnertb** [comment]
Closed in: https://github.com/MapStory/mapstory-geonode/commit/228d9c2bd310365237d95a944b794a1dfe169801

Note: this requires a migration to deploy:

```
sudo -u postgres psql -c 'alter table mapstory_getpagecontent add column "external_link_title" varchar(64);' -d mapstory
```
