### ISSUE TITLE
Search results card update

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1065]
On the Explore page, Search result cards must be aligned correctly and must contain the following information:

![screen shot 2015-07-02 at 2 28 10 pm](https://cloud.githubusercontent.com/assets/4611843/8484634/a88b319a-20c6-11e5-8a9e-d8958bf2924e.png)

**Comment by reynalddizon** [comment]
Abstract (summary) of story layers should be truncated to 70 characters. I'm guessing this would solve the misalignment of the search cards? Please confirm. Add a "Read more." link at the end of it and link it to the StoryLayer page.

**Comment by reynalddizon** [comment]
On the StoryLayer card, the view button, should be "use" and that would launch the composer preloaded with that storylayer

**Comment by travislbrundage** [comment]
Looking at the misalignment of search cards, I'm assuming you're talking about situations like this: http://i.imgur.com/alkWuQD.png

In this case, limiting it to 70 characters is not going to do anything. The problem indeed is the difference in length of the abstracts, though. So I'm going to guess we want a standard amount of area for the abstract. Do you still want a 70 character limit even with that established?

I also just want to confirm some of the functionality.

If I hit "play" will it just take me straight to the viewer for this map?
If I hit "edit" I assume it's the same as going to the Layer page itself and clicking "edit".
What does "share" do?

**Comment by jonpmarino** [comment]
Sounds right for play and edit. Share I would say would bring you to the viewer page with the iframe window open to make it easy for user to grab embed code
