### ISSUE TITLE
Need to address UI behaviors on Mobile View

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1068]
We need to test the UI on Mobile. We don't expect to support editing or composing on mobile at this Stage. But users should be able to see the Homepage with coherence, explore and hit play on mapstories without too much difficulty.

**Comment by jonpmarino** [comment]
Also there is no header menu on mobile view

**Comment by travislbrundage** [comment]
Issue #1075 is the header stuff, noted on the animated GIFs (I assume you're referring to the parallax images changing size and repeating). Is there anything else? If so, can you please expand upon the weird behaviour on mobile so we know what to look out for?
