### ISSUE TITLE
Home Page Search and Quick Search

### ISSUE THREAD

**Issue by travislbrundage** [MapStory/mapstory-meta#1071]

**Comment by travislbrundage** [comment]
Closed by [Pull Request #47](https://github.com/MapStory/mapstory-geonode/pull/47)

**Comment by jonpmarino** [comment]
needs to be right sized

**Comment by travislbrundage** [comment]
Closed by [Pull Request #55](https://github.com/MapStory/mapstory-geonode/pull/55)
