### ISSUE TITLE
Replace current composer StoryLayer and Style tab w/ Rey's stylesheets

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1072]

**Comment by reynalddizon** [comment]
Since there are some major differences between the Composer tabs in the mockup and the one in the beta, I'm going to revise my mockup a little bit to address these differences. Will let you know @davisc as soon as I finish it.

**Comment by reynalddizon** [comment]
![screen shot 2015-06-29 at 7 46 32 am](https://cloud.githubusercontent.com/assets/4611843/8408278/9ac79bf2-1e3c-11e5-9c45-8c5eb5fe5896.png)
