### ISSUE TITLE
Current topics in Explore should be replaced with our topics -

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1073]
Same as home page -

Crisis, Geopolitics, Science & Industry, Human Settlement, Culture & Ideas, Nature & Environment, Health, Biography

**Comment by jwood106** [comment]
When I choose any of the current topics on home page on beta, none of them return any results except the 'All'.  So looks like we have either no MapStories in any of those topics, or we have an application issue that needs to be resolved.  For this story, I will change the list of Explore topics (labelled 'What') to match the main page's list.  I will write up a separate issue https://github.com/MapStory/mapstory/issues/1088 to make sure the search actually is working for both the main page and the Explore page topics.

**Comment by jonpmarino** [comment]
Correct, Jeff. Thanks for getting on this! The application hasn't been set up for those topics. The current mapstory.org implementation has. You may want to review that. Also, *note...beta.mapstory.org topics have one error. The one that reads Biology should read Biography.

**Comment by jwood106** [comment]
Thanks for the confirmation Jon.  And for the info on the existing beta error, I will correct the Biology topic label to Biography.

Side note: Isn't there a song 'don't know much about biology...', this change will put us in line with that.

**Comment by jwood106** [comment]
done.
https://github.com/MapStory/mapstory-geonode/commit/1f2ce2ab363826bc416afeb0522db8f501ddf2fa
