### ISSUE TITLE
Thinkers and Thoughts section

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1077]
Thumbnails must display the users avatar (with circle mask -- not rounded square),and the thumbnails should link to a specific journal entry specified by the admin. Caption of the thumbnails must contain:

Title of the Journal Post
Name

**Comment by jwood106** [comment]
Status: i have the diary info available on the template (as demonstrated in the template change, generating comments with diary info).  Was not able to successfully format the html correctly from static to dynamic.  So I backed out some of my work, committed what is correct to a feature branch(https://github.com/MapStory/mapstory-geonode/tree/diary_entries_to_main_page).

This change involves a model field change (add a boolean column), here is the necessary SQL:
mapstory=> alter table mapstory_diaryentry add column show_on_main boolean default false;

I ran this SQL on my local vm with psql and then could use the django admin to choose to show diary entries on main, you will see a new check box labelled show_on_main.  Once you add a few and mark them show_on_main, you can view source of the main page and see their info in comments right above the static diary entry slice section.

Also, note that Rey wants the images to be circular, the css class to use is img-circle.

**Comment by jwood106** [comment]
Status:
Made it past the dynamic problems I reported 3 days ago.  The diary entries now being dynamically populated, and each of them correctly links to its corresponding detail page.
Still have some formatting and presentation work to do.  Once get that done, will create pull request from the feature branch.

**Comment by jonpmarino** [comment]
Awesome!

**Comment by jwood106** [comment]
changes are ready to go in pull request: https://github.com/MapStory/mapstory-geonode/pull/66

**Comment by jwood106** [comment]
done.
Clarence reviewed the pull request, merged and pushed to beta.

**Comment by jwood106** [comment]
Received feedback from Jon and Rey after their review of beta.
Reopen issue to make these changes from Rey:
The title of the essay should be bold, maybe two lines. and the name of the storyteller on the third line, not bold.

**Comment by jwood106** [comment]
format changes done.
https://github.com/MapStory/mapstory-geonode/pull/67
