### ISSUE TITLE
Play button doesn't toggle at end of playback

### ISSUE THREAD

**Issue by mpriour** [MapStory/mapstory-meta#108]
Playback button should toggle to the 'paused/stopped' state when the time slider reaches the end. As it is now, user must double click the play button after resetting the slider or adjusting it to a play-able point.

**Comment by mpriour** [comment]
fixed in https://github.com/opengeo/gxp/commit/42b1a353a9eadbfb18843ff1c5866b00062eccba

**Comment by ischneider** [comment]
Have not extensively tested this, but does not work on http://mapstory.dev.opengeo.org/maps/14

**Comment by mpriour** [comment]
I just tested with that example on the dev server and the play button toggled from "pause" to "play" style at the end of playback just as you would expect. How did you make it fail? That way I can determine why it was not working when you tested it.

**Comment by ischneider** [comment]
I thought I had made this happen while looking at the playback speed issue that Chris reported, but I cannot duplicate it now. Sorry, I'll close it again for now.
