### ISSUE TITLE
Cache dimensions data in the GeoNode db to allow lazy loading.

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1081]
In order to get https://github.com/MapStory/mapstory/issues/1055 working I had to disable the GeoEXT lazy loading functionality from: https://github.com/MapStory/geonode/commit/82c30829a734388796f6e4587d5b92906604cb43.  This requires GeoEXT to make a GetCapabilties request when the user visits a layer detail page.  The GetCapbilties request will time out when a large number of layers are present.  

It should be possible to cache the dimensional data when saving a Layer (somewhere in here https://github.com/GeoNode/geonode/blob/master/geonode/geoserver/signals.py#L38) which would allow us to load the map without the getcapabilties.

**Comment by garnertb** [comment]
Alternatively we may be able to filter the getcapabilties to a single layer: `geoserver/geonode/Solo_Americas1/wms?service=wms&version=1.3.0&request=GetCapabilities`

**Comment by jonpmarino** [comment]
@garnertb still open? If so, defer to you on level of priority.

**Comment by garnertb** [comment]
This is still open, but its a performance enhancement and therefore should probably be low priority until the current implementation causes problems.

**Comment by jonpmarino** [comment]
Table it

**Comment by glynnis** [comment]
Closing this. If this is still relevant, please create a new issue with more detail at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.
