### ISSUE TITLE
Update the mapstory-v2 branch.

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1083]
The submodules with explicit commits is becoming burdensome to keep up to date and adding confusion to the developer experience.  I recommend we make the following changes to improve this:
- [ ] Update the geonode to use the fork https://github.com/MapStory/geonode.
- [ ] Set the geonode submodule ref to master vs an explicit commit.
- [ ] Set the mapstory-geonode submodule ref to master vs an explicit commit.

As the codebase becomes more stable we can switch back to explicit commits (or use a deploy branch).

**Comment by meilinger** [comment]
For the life of me, I couldn't figure out how to track the tip of master automatically for submodules.
