### ISSUE TITLE
Layer Preview can use a layer specific getcap

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1085]
http://mapstory.beta.boundlessgeo.com/geoserver/geonode/Solo_Americas1/wms?service=wms&version=1.3.0&request=GetCapabilities

update the layer url in the context_dict of this view: https://github.com/MapStory/geonode/blob/82c30829a734388796f6e4587d5b92906604cb43/geonode/layers/views.py#L284.

**Comment by garnertb** [comment]
Fixed with https://github.com/MapStory/geonode/commit/deb8504eea63e5582e5ea5aa4970d8ca6c83fa01.

I still think implementing https://github.com/MapStory/mapstory/issues/1081, which would avoid the get capabilities request all together, is the right long-term solution for MapStory.
