### ISSUE TITLE
Implement MapStory Topic search

### ISSUE THREAD

**Issue by jwood106** [MapStory/mapstory-meta#1088]
When I choose any of the current topics on home page on beta, none of them return any results except the 'All'.  After talking to Jon and looking at code, can see we have not implemented these MapStory specific categories in MapStory v2.  Implement these and apply to the home page topic search and the Explore 'What' section so that topic search works in both places.

**Comment by travislbrundage** [comment]
Hi @jwood106 - has there been any work you've done towards this?

**Comment by jonpmarino** [comment]
Should begin by reviewing implementation on production. This is already implemented there. Users assign storylayers to topics when completing metadata

**Comment by jwood106** [comment]
@travislbrundage No, I have not done any work to implement this.  When I wrote this story, I did quickly look at the object hierarchy on production.  The existing 'topics' hierarchy I see there are model objects named section, and a section has topic(s), and a topic has layer(s) and map(s).  I think this is one more level than provided in GeoNode.  Iirc, Ian mentioned MapStory had changes from GeoNode to drive MapStory's 'related' concept.  I think this additional piece in topics may be how MapStory does that.  If you look into this one, would be fine to discuss further, bounce ideas off me, etc.

**Comment by travislbrundage** [comment]
Closed by [Pull Request #72](https://github.com/MapStory/mapstory-geonode/pull/72) in mapstory-geonode, and [Pull Request #6](https://github.com/MapStory/geonode/pull/6) in geonode. To note, this requires changing the fixtures in the geonode project, but it is not something that will be contributed back to geonode. It's a mapstory specific change.

Further, this change will require a database update for topic categories. The old entries have to be removed and replaced with the new one. I think this will require entirely dumping the old tables and remaking them.
