### ISSUE TITLE
Time.ftl for kml sharing

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1089]
create a time.ftl for layers that specify time attributes.  google earth will pick up the time and make a slider

**Comment by jonpmarino** [comment]
@zrouse-Boundless this is interesting. would love some google earth integration. But is this a big effort given time/money remaining? Try to prioritize for @garnertb

**Comment by garnertb** [comment]
@jonpmarino: I'd say this is at least 40 hours of work.

**Comment by jonpmarino** [comment]
Table it
