### ISSUE TITLE
Change URL standard string for Journal articles to /journal not /diary

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1090]
Current journal entry string looks something like this, http://mapstory.beta.boundlessgeo.com/diary/5. We want to have it default to /journal/# not  /diary/#

**Comment by jwood106** [comment]
done.
https://github.com/MapStory/mapstory-geonode/commit/74d55bda0bd71ff9236b106b4ecee30ad079dd14
