### ISSUE TITLE
Add arrows and carrousel effect to featured mapstories on homepage if there is more than 4

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1091]
Update of same behavior we have on Home right now.

**Comment by reynalddizon** [comment]
Well, sort of similar to what the current mapstory has. Carousel movement should follow the direction of the arrow. (the one in the current mapstory has that behavior reversed.)

**Comment by travislbrundage** [comment]
Closed by [Pull Request #79](https://github.com/MapStory/mapstory-geonode/pull/79)
