### ISSUE TITLE
Profile page style refinement

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1093]
I tweaked the mockup for profile page just a little bit, removed unnecessary features, etc.

Two modes of the profile page:
(1.) Other users viewing one's profile page:
![screen shot 2015-07-01 at 3 52 48 pm](https://cloud.githubusercontent.com/assets/4611843/8463556/49963da0-2009-11e5-9d28-928c033ce6d7.png)

(2.) User viewing his own profile page.
![screen shot 2015-07-01 at 1 54 25 pm](https://cloud.githubusercontent.com/assets/4611843/8461183/bad8f040-1ff8-11e5-97a2-6ab60a88b158.png)

**Comment by jonpmarino** [comment]
Make sure it's journal entries on both views

**Comment by jonpmarino** [comment]
@davisc @travislbrundage @reynalddizon on beta "Journal entries" tab still says "Diary entries"

**Comment by garnertb** [comment]
@travislbrundage, I added the messaging context to the profile page which should help when you need to get that working on the client-side.  Here is the commit: https://github.com/MapStory/mapstory-geonode/commit/3ad14958e39a6bc9e5e077c223938c6f5d696143
