### ISSUE TITLE
Search bar & auto-complete style refinements

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1094]
(1.) Autocomplete box should be placed immediately below the text input box to avoid obstruction. It should also inherit the width of the text input box.

![autocomplete](https://cloud.githubusercontent.com/assets/4611843/8461434/79b1633e-1ffa-11e5-995d-359f9b8f159f.png)

(2.) Align the quick search bar with the other elements on the navbar.

![screen shot 2015-07-01 at 2 09 13 pm](https://cloud.githubusercontent.com/assets/4611843/8461482/f0ff2cfa-1ffa-11e5-85c6-7480ffc364e7.png)

**Comment by jonpmarino** [comment]
closing since were canning auto-complete except when searching keywords in explore or creating new keywords.
