### ISSUE TITLE
Journal pages style refinement

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1097]
I have updated the page layout for Journal page and Get pages to make them look uniform. Check them out in my mockup repo: github.com/reynalddizon/mapstoryorg

![screen shot 2015-07-01 at 4 50 16 pm](https://cloud.githubusercontent.com/assets/4611843/8464579/477f0c38-2011-11e5-8040-9ea72641e5d9.png)

Changes include layout of the headers and the position of the "write a new entry" because it really looked weird on the previous version. And this version looks consistent with the profile page.

**Comment by jonpmarino** [comment]
thanks @reynalddizon. Related to this in journal we are hoping for #1025 #1024 and #1037
