### ISSUE TITLE
Add a StoryLayer refinement

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1099]
(1) All the buttons in the Add a StoryLayer accordion element should trigger the StoryLayerModal. The names of the buttons correspond to the tabs in the modal.

![screen shot 2015-07-02 at 2 14 15 pm](https://cloud.githubusercontent.com/assets/4611843/8484274/b6f4518c-20c4-11e5-8ce4-76ece998f0f4.png)

![screen shot 2015-07-02 at 2 36 37 pm](https://cloud.githubusercontent.com/assets/4611843/8484832/c9d96334-20c7-11e5-911f-c52f9ae64f03.png)

![screen shot 2015-07-02 at 2 32 50 pm](https://cloud.githubusercontent.com/assets/4611843/8484727/40dc9588-20c7-11e5-8fb5-a82b4c8e9247.png)

(2) StoryLayers card should look like this:
![screen shot 2015-07-02 at 1 13 32 pm](https://cloud.githubusercontent.com/assets/4611843/8483103/3aad9c3a-20bc-11e5-8f0f-c4362fc1b723.png)

These updates are in the mockup: github.com/reynalddizon/mapstoryorg
Composer mockups are in the composer folder.

**Comment by reynalddizon** [comment]
@davisc @jonpmarino I just noticed that if you click on panels other than "Explore All", it still directs you to the "Explore All" tab of the modal. It should be that clicking on Common StoryLayers panel with direct you to the same modal but the "Common" tab is active and not the "Explore All" tab, same for other panels.

**Comment by jonpmarino** [comment]
@reynalddizon and @davisc the Explore All tab in the mini-explore modul inside composer should also enable the user to refine in the same ways they can refine in the normal Explore...What, Where, When. @reynalddizon need designs for this

**Comment by jonpmarino** [comment]
@davisc "selecting" a layer from the mini-explore module in composer should add that layer into the map composer. Realize this is a function you've prob yet to implement

**Comment by davisc** [comment]
@jonpmarino "selecting" a layer from the mini-explore module in composer will add each layer the map once you press the "use selected" button. Currently, the oil_deepwater9 and oil_deepwater10 layers work because they were newly uploaded. Most of the layers in the search result fail to load on the map because the underlying data does not exist in geoserver.

**Comment by reynalddizon** [comment]
In the Explore StoryLayers Modal, clicking on the title of a storylayer should launch a new tab showing the storylayer info page. Currently the storylayer info page loads up in the same tab where the composer is.
