### ISSUE TITLE
Upload a StoryLayer in the Composer update

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1100]
Add the uploader feature in the Add a StoryLayer panel.

<img width="1280" alt="screen shot 2015-07-06 at 3 34 43 pm" src="https://cloud.githubusercontent.com/assets/4611843/8531337/9d62f600-23f4-11e5-9866-1e49353a219f.png">

The upload modal doesnt have any UI features inside it but it has a summary of what the tabs should contain. Panels Upload CSV and Upload SHP panels could be unified as both have the same function.

Step 1 Tab: Add a File.

> Includes drag and drop box or the classic locate file button.

Step 2 Tab: Time and Geospatial Parameters

> Includes options for identifying which columns contain geographic and temporal attributes of the features. Also includes options on how geographic information should be projected and the time format the temporal attribute is encoded.

Step 3 Tab: StoryLayer Metadata

> Includes form fields and options for specifying storylayer level metadata like author, topic(categories), data quality statement etc.

Step 4 Tab: StoryLayer Permissions and Privacy

> Includes options for specifying what the author and other users can do with the storylayers. Also includes privacy and visibility options.

Step 5 Tab: Finish Upload

> Other options not specified in previous tabs.

There should be a way for users to navigating thru the tabs by having "Previous/Back" to "Next" buttons.

**Comment by jonpmarino** [comment]
@reynalddizon do we have direction on exactly what the Upload page will look like when someone goes from Home > Upload StoryLayers? Currently, the page is stock GeoNode, which is not what we want - 

http://mapstory.beta.boundlessgeo.com/layers/upload

**Comment by reynalddizon** [comment]
it should be just the page version of this modal. It just that their points of entry are different. . there's no reason that the page version and the modal version should look different.

**Comment by jonpmarino** [comment]
@garnertb not sure if you were working composer at all, but FYI - need to get the uploader page and workflow in mapstory beta ready for everyday users...
