### ISSUE TITLE
Implement Organization page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1102]
We need to implement the Organization profile page, as opposed to Individual Profile page. Basic idea is that Org pages let an admin build a place at a single URL where storylayers, storytellers and mapstories exist together. Admin can pull storylayers, storytellers and mapstories into their Org page by favoriting those contents on the site. This is the same workflow for Org page that exists on Prod (see http://mapstory.org/theresolve/). We are just updating the UI with some small feature mods.

**Comment by reynalddizon** [comment]
(1) Logged in as Admin:
<img width="1280" alt="screen shot 2015-07-09 at 3 05 59 pm" src="https://cloud.githubusercontent.com/assets/4611843/8604355/2084449a-264c-11e5-9bdf-3f7bdd34389a.png">

(2) Viewing page as non-admin:
<img width="1280" alt="screen shot 2015-07-09 at 3 05 44 pm" src="https://cloud.githubusercontent.com/assets/4611843/8604354/2081d9e4-264c-11e5-8e3d-7d070cb8a580.png">

**Comment by jonpmarino** [comment]
Should blogs be journal entries? And did we define forum?

**Comment by reynalddizon** [comment]
I'll update the mockup

**Comment by reynalddizon** [comment]
To the one assigned to do this task: Let Jon and I know if you're about to start working on this one, lets discuss the details of this concept first on hangout.

**Comment by jj0hns0n** [comment]
@simod is working on this.

**Comment by jonpmarino** [comment]
@jj0hns0n has changes to roll in for @davisc. On Thursday after standup @travislbrundage @jj0hns0n and I will work through getting front-end UI going.

**Comment by jj0hns0n** [comment]
Deployed to demo. http://demo.mapstory.org/api/collections/1/
@travislbrundage is going to pick up the front end of this.

**Comment by travislbrundage** [comment]
Closed by https://github.com/MapStory/mapstory-geonode/pull/187
