### ISSUE TITLE
Implement Community Initiative page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1103]
The community initiative page is basically the same as the Org Page, with a few feature differences. Creation workflow is the same - created on Admin backend, with management credentials provided to an admin user

**Comment by reynalddizon** [comment]
<img width="1280" alt="screen shot 2015-07-08 at 10 40 15 am" src="https://cloud.githubusercontent.com/assets/4611843/8573080/c7349848-255d-11e5-8f5d-c61d4e4fc29b.png">

**Comment by reynalddizon** [comment]
To the one assigned to do this task: Let Jon and I know if you're about to start working on this one, lets discuss the details of this concept first on hangout.

**Comment by jonpmarino** [comment]
Closing. @travislbrundage created. Comments on remaining work is in #1135
