### ISSUE TITLE
Search for storytellers doesn't seem to work

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1107]
![1010](https://cloud.githubusercontent.com/assets/2573761/8585694/c262c9b0-25b3-11e5-8994-c4dbd814a1c1.jpg)

entering a name should begin an autocomplete and filter users

**Comment by travislbrundage** [comment]
This should be closed [Pull Request #74](https://github.com/MapStory/mapstory-geonode/pull/74)
