### ISSUE TITLE
Migrate StoryLayer Topics/Categories

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1108]
- [ ] Sections from mapstroy production need to be mapped to the "Metadata Topic Categories" in beta.
- [ ] Topics (which are sub-sections) will become tags.
- [ ] Need re-implement the related layers/maps.

**Comment by jonpmarino** [comment]
@travislbrundage created topics. there are issues with assigning topics to content but this is separate fro topics creator
