### ISSUE TITLE
MapStory viewer page update

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1113]
<img width="1280" alt="screen shot 2015-07-13 at 11 12 25 am" src="https://cloud.githubusercontent.com/assets/4611843/8653009/197bf4a2-2950-11e5-8c4a-4b74d0074319.png">

This update should include the following features:
Left column:
1. MapStory Mini viewer with time and playback controls.
2. StoryTeller name. Skip the social media links for now.
3. Comments

Right column:
1. Basic MapStory information (Title, Region, Category, Tags and Rating)
2. Options (play fullscreen, favorite and flag, and "edit" if the user is viewing his own mapstory). Don't include "download".
3. Tabs (Summary and Metadata). Skip the Related Tabs for now.

**Comment by jonpmarino** [comment]
@travislbrundage @reynalddizon Need to add a tab next to related for "StoryLayers" that shows the layers that the mapstory is based on so user can go directly to the StoryLayers that the mapstory is based on
