### ISSUE TITLE
On Home, make sure "Sign Up" call to action goes to the MapStory sign-up modal, not stock GeoNode

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1127]
Currently the icon at top-right has one sign up (ours) and clicking "Sign Up" on the calls to action goes another. Needs to be the same.

**Comment by garnertb** [comment]
Fixed in https://github.com/MapStory/mapstory-geonode/commit/f568ceadd7b859138d2304912a5fdefdc4b28d09.
