### ISSUE TITLE
errors when removing a layer from the map when the layer is being animated

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#113]

**Comment by awright** [comment]
what sort of errors?  does this stop the animation from showing?

perhaps a simple way to resolve is to only allow deletion of layers when a map is paused/stopped.

**Comment by bartvde** [comment]
You get a continuous loop of javascript errors:

this.currentTime["getUTC" + b] is not a function
http://mapstory.dev.opengeo.org/static/static/script/TimeManager.js
Line 15

The best way is for the TimeManager to listen to events on the layer store and when a layer is removed, then unbind.

**Comment by bartvde** [comment]
And yes this stops the animation from showing, but this is to be expected IMHO since the layer which is being animated is removed by the user. However the TimeManager should deal with this more gracefully.

**Comment by mpriour** [comment]
dealt with in 
https://github.com/mpriour/TimeManager_OpenLayers-Addin/commit/60bffc51dc00baca1274524ec23ec21ec3805654
