### ISSUE TITLE
Update URL paths for profile pages

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1134]
1. For individual profile pages: mapstory.org/storyteller/username.
2. For initiative pages: mapstory.org/initiative/initiativename
3. For org pages: mapstory.org/organization_name

**Comment by travislbrundage** [comment]
For the individual profile page it is not as trivial because we are taking it from geonode, so I need to figure out how to override that properly. Got 2 and 3 though.

**Comment by jwood106** [comment]
Travis changed the mapstory-geonode project urls.py to match these three in https://github.com/MapStory/mapstory-geonode/commit/304f2f243c0a0e4888a108844392a52a561df213.
As Travis mentioned, we needed to do a little more work for the first one.
The change broke the user profile links in the header, and I made changes to fix them. (there are two - composer has its own.)  Searched the mapstory-geonode project for any more uses of the geonode project's Profile.get_absolute_url method, no others. https://github.com/MapStory/mapstory-geonode/commit/4a178c12c0f17e7984cbf1c4ddd009fe81262beb

**Comment by jwood106** [comment]
@travislbrundage  are you aware of anything else we need to do to complete the work for this issue?  I fixed the issue I reported in today's standup(see comment above).

**Comment by travislbrundage** [comment]
The 3rd one I've set temporarily to be /organization/[slug] because it seems to screw up other links otherwise. I'm not sure how to get around that immediately. The problem is because there are other pages, like the admin panel itself, which would match the pattern /[organization_name], since it is /admin.
