### ISSUE TITLE
Give user more graceful notice that they can't view a layer if they aren't logged on

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1138]
Currently in composer when I am not logged on, I try to click on a layer in the mini-explore and I get a 403 error. Instead we should say something to the user "Sorry, you can't access this unless you are logged on. Please log on."

![4133](https://cloud.githubusercontent.com/assets/2573761/8942370/fa4b6d66-3542-11e5-8627-c30888c5b77b.jpg)

**Comment by davisc** [comment]
Should you be able to access composer if you are not logged in?

**Comment by jonpmarino** [comment]
Good point. I'd say nope. So if a user clicks the composer link on header at all and isn't logged on it should either go to login modal or give an indication of "this area is only available to registered users. Please log in or create an account"
