### ISSUE TITLE
speed up create_layer endpoint

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#116]
see if we can speed this up, currently takes anywhere between 5 and 20 seconds on my MacBook Pro.

**Comment by ischneider** [comment]
Can't do much about this at the moment since all geonode layers have to exist in geonode, geoserver, and geonetwork. The latter takes the bulk of the time for this operation.

**Comment by awright** [comment]
this may be resolved with the CSW work for ANZSM.  we'll review the status of this at a later date.

**Comment by bartvde** [comment]
@ischneider Is the slow GeoNetwork step still necessary here since we don't want annotation layers to be found through search?

**Comment by ischneider** [comment]
@bartvde I think geonode will get grumpy if the layer is not in geonetwork and as it is now, creating a layer automatically adds it to geonetwork.

**Comment by bartvde** [comment]
Okay let's safely close this one now then :-) Nothing to be done about it.
