### ISSUE TITLE
StoryLayer Errors [Case Studies] 

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1171]
_Writing this issue still in progress_

Case 1: No features on Beta. Features show up on production.
- [ ] http://mapstory.beta.boundlessgeo.com/layers/geonode:pula_streets_2014 (beta)
  http://mapstory.org/data/geonode:pula_streets_2014 (prod)

Case 2: Temporal playback failed on Beta. Layer plays fine on prod.
- [ ] http://mapstory.org/data/geonode:MLK_speeches (beta)
  http://mapstory.beta.boundlessgeo.com/layers/geonode:MLK_speeches (prod)

Case 3: Pink Tiles on beta. These layers don't exist on prod.
- [ ] http://mapstory.beta.boundlessgeo.com/layers/geonode%3ADC_murals1
- [ ] http://mapstory.beta.boundlessgeo.com/layers/geonode%3AUS_Shootings

Case 4: Pink Tiles on beta. Pink tiles on prod.
- [ ] http://mapstory.beta.boundlessgeo.com/layers/geonode:sa_anthrome?limit=100&offset=0 (beta)
  http://mapstory.org/data/geonode:sa_anthrome (prod)

**Comment by jonpmarino** [comment]
closing. links are to beta.
