### ISSUE TITLE
Technical Debt Brainstorm

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1179]
- [ ] Geowebcache
- [ ] Dev-ops deploy
- [ ] vm snapshot
- [ ] Git Repo organization
- [ ] payload diet
- [ ] ensure no phantom dependancies on old version
- [x] learn syntax for checkbox
- [ ] HA (check out Dan Berry's GVS work)

**Comment by garnertb** [comment]
- [ ] minify/uglify/compress static assets
- [ ] move static assets to a CDN
- [ ] load test
- [ ] separate web app from db server?
- [ ] add a load balancer?
- [ ] use statsd/graphite or new relic for monitoring
- [x] use celery to run expensive tasks outside of the request/response cycle
- [ ] integration tests
- [ ] start deploying with ansible

**Comment by davisc** [comment]
- [ ] Repo Branching strategy
- [ ] Document architecture
- [ ] DB and Data Dir backups
- [ ] Use south/django migrations within mapstory
- [ ] Get storytools mapstory wip from the storytools repo via bower dependency

**Comment by travislbrundage** [comment]
- [ ] [geoserver-marlin](http://www.geo-solutions.it/blog/developerss-corner-achieving-extreme-geoserver-scalability-with-the-new-marlin-vector-rasterizer/)?
- [ ] Fix the parallax images taking up too much space?
- [ ] Fix geonode commits?
