### ISSUE TITLE
Uploader seems to choke on shapefiles with mixed case names

### ISSUE THREAD

**Issue by mpriour** [MapStory/mapstory-meta#119]
Sam Pepple & I were trying to upload MexicoMurdersJoined and consistently getting an "expected to find geonode:MexicanMurdersJoined layer" error in the second step of the upload process. I tried with a known, good shapefile which I also changed to a mixed case name and got the same kind of error.
Everything went through just fine once the name case was all lowercase (we didn't try all upper case)

**Comment by ischneider** [comment]
Verified and fixed in importer (creation of index on time attribute was failing due to missing quotes on table name) - will hopefully be deploying this evening to dev server.
