### ISSUE TITLE
Profiles and Community

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1191]
#### Profile Page
- [ ] Add Education, Skills, Interests (tags) on the left sidebar.
- [ ] Favorites tab should display Cards instead of a list, for consistency.
- [ ] Send notification emails to users for: recent edits, recent comments, recent flags, new mapstories created using the user's storylayers.

**Comment by jonpmarino** [comment]
Closing since now duplicate of #1302
