### ISSUE TITLE
Explore (Large collection of stories)

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1194]
_This issue contains tasks related to the back-end and front-search aspects of content and user exploration._
#### Explore content
- [x] Add "Who" to the Content Search. Have it be an auto-complete / drop down of storytellers. Should filter StoryLayers/MapStories by that user
- [x] Make "Search for Content" or "Search for Storytellers" stay gray when clicked.
- [x] New items are always displayed from right to left, it's counter-intuitive.
- [x] Remove the map search box or make it work. Configure place search
- [x] Install a date-picker UI for the when filter.
- [x] The Explore page tries to load http://mapstory.org/static/lib/js/bootstrap-datepicker.js, but it gives a 404
- [x] Add most used tags like from UI
- [x] Add bootstrap tokenization for tags
- [x] [“No Image” placeholder](http://mapstory.org/static/geonode/img/missing_thumb.png) could be improved. Maybe a light grayscale map?
  Test URL: http://mapstory.org/static/geonode/img/missing_thumb.png
  Test URL: http://mapstory.org/search/?limit=100&offset=0&is_published
- [x] Keyword option on the Explore page is unclear and does not seem to function.
  Image:
  <img width="359" alt="screen shot 2015-10-16 at 2 13 11 pm" src="https://cloud.githubusercontent.com/assets/1622331/10699861/78f06a7e-797f-11e5-86b2-5affb38e76fa.png">
- [x] The “Where” option under the “Refine Search” section on the Explore page does not have any effect Test URL: http://mapstory.org/search/?limit=100&offset=0&is_published&q=&extent=-126.21093749999999,49.95121990866204,-104.0625,64.09140752262307
- [x] Update styling
#### Tags
- [x] Implement the ability to load a search page preloaded with the clicked tag fro a viewer page. This will require making the Tags clickable on the StoryLayer and MapStory viewer pages (clicking a tag should launch a search in Explore based on that tag
#### StoryTellers
- [x] implement StoryTeller filters on left-side like called for in mockup: filters = By VTC members, By city, By country, By Interests

**Comment by jj0hns0n** [comment]
datepicker fixed with https://github.com/MapStory/mapstory-geonode/commit/03ccdb3f0caa3bc06c0224bff20c446b09dbe419

**Comment by travislbrundage** [comment]
Just putting it out here as a random note, but the `search.js` file really needs a clean up. There's a lot of old, outdated code that's not even being used. It's making the file cluttered and more confusing than necessary. https://github.com/MapStory/mapstory-geonode/blob/master/mapstory/static/mapstory/js/search.js

**Comment by travislbrundage** [comment]
"Add most used tags like from UI" - I've added the Trending Tags, however, it should be noted that tags are the same on the backend for keywords (on MapStories and StoryLayers) and interests (on StoryTellers). So, it's going to show the 8 most popular alphabetically ordered, but this includes both keywords and interests.

**Comment by jonpmarino** [comment]
@travislbrundage I think that's fine. We can think about it as an integrated "Most popular on mapstory" type feature.

**Comment by travislbrundage** [comment]
Yeah, that's fine, just wanted to make sure it was known that was the behaviour.

"Implement the ability to load a search page preloaded with the clicked tag fro a viewer page. This will require making the Tags clickable on the StoryLayer and MapStory viewer pages (clicking a tag should launch a search in Explore based on that tag" - this is partway there. It's implemented, however, when you are taken to the search page with that tag filtered already, there is no obvious way to remove it. You can do so manually by adjusting the URL but that's not the right way to interact with the page as a user. Thinking it should probably show up under the Keywords search pre-populated with the tag you clicked on. Kind of related to #1356

**Comment by jonpmarino** [comment]
1. fix Who so the drop-down doesn't cover text 2. Fix Trending tags so it pulls from tags.

**Comment by travislbrundage** [comment]
"Explore page shows "page 1 of NaN” before loading is complete Test URL:" - I think I fixed this, but let me know if it still appears after this PR is merged: https://github.com/MapStory/mapstory-geonode/pull/181

**Comment by travislbrundage** [comment]
Separated this out into multiple issues.
