### ISSUE TITLE
GeoNode mapstory branch clean up

### ISSUE THREAD

**Issue by travislbrundage** [MapStory/mapstory-meta#1209]
Go through mapstory branch of geonode and clean up any extraneous commits.

Mapstory specific commits in the GeoNode fork should be on the mapstory branch and continuously refactored on top of latest GeoNode. Requires addressing [issue #1208](https://github.com/MapStory/mapstory/issues/1208).

**Comment by jonpmarino** [comment]
@travislbrundage is this still an active issue?

**Comment by travislbrundage** [comment]
This is still open and I worked some towards this issue recently, but there are still bugs and conflicts with GeoNode.
