### ISSUE TITLE
Local layers should be saved as 'lazy' layers

### ISSUE THREAD

**Issue by mpriour** [MapStory/mapstory-meta#121]
This will avoid broken capabilities issues and will significantly speed up the map load.

**Comment by mpriour** [comment]
Committed to a new lazy-load branch on gxp as saved maps don't contain the layer's dimension data and thus break when this change is made.
Newly saved maps after this change is applied work fine.

**Comment by mpriour** [comment]
See https://github.com/opengeo/gxp/commit/7f63d013d96235d490bf5b88026ec2839917182a

**Comment by awright** [comment]
what's keeping this from being closed?

**Comment by bartvde** [comment]
@mpriour Can this be closed?

**Comment by mpriour** [comment]
yep
