### ISSUE TITLE
Get GeoTools postgis-xdate branch upstream

### ISSUE THREAD

**Issue by travislbrundage** [MapStory/mapstory-meta#1210]
Need to get the [postgis-xdate](https://github.com/ROGUE-JCTD/geotools) branch of GeoTools into upstream to make our lives easier and avoid future rebase failures.

**Comment by travislbrundage** [comment]
I'm coming back to this issue once I get confirmation that repo.boundlessgeo.com is up again. It's not completely a blocker, but will make solving the issue much easier because I can test it on my local VM. Will be carrying to next sprint.

**Comment by jonpmarino** [comment]
@travislbrundage is this still an active issue?

**Comment by travislbrundage** [comment]
This is still open, although I am not currently working on this issue.
