### ISSUE TITLE
List of broken basemap services

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1212]

**Comment by davisc** [comment]
[maps-broken-basemap.txt](https://github.com/MapStory/mapstory/files/16196/maps-broken-basemap.txt)
300 records in the database using this layer configuration.

```
"{"selected": false, "title": "Naked Earth", "args": ["Naked Earth", "http://maps.opengeo.org/geowebcache/service/wms", {"layers": ["Wayne"], "tiled": true, "tilesOrigin": [-20037508.34, -20037508.34], "format": "image/png"}, {"buffer": 0}], "type": "OpenLa (...)"
```

**Comment by davisc** [comment]
Updated all records listed in the maps-broken-basemap.txt and set the basemap to OpenstreetMap.
