### ISSUE TITLE
mapstory.org/getskills has no content.

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1216]
@jonpmarino, is there supposed to be content on this page?

http://mapstory.org/getskills

**Comment by davisc** [comment]
@garnertb looks like there was content but is not complete.

**Comment by jonpmarino** [comment]
@garnertb yes. Videos. Just like get started. Still making the videos. Need to be based on finished version of things

**Comment by garnertb** [comment]
@jonpmarino So you're OK with the current status of the page and this can be closed?

**Comment by garnertb** [comment]
Closing, per @jonpmarino.
