### ISSUE TITLE
Checkboxes on the sign up form have no effect.

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1218]
While writing some tests I realized that these checkboxes don't actually do anything: 

<img width="492" alt="screen shot 2015-10-12 at 10 40 30 am" src="https://cloud.githubusercontent.com/assets/1141646/10430557/dad945b8-70cd-11e5-8847-b633ee3f4255.png">
- [x] Monthly digest
- [x] Terms and Conditoins
- [x] Password length

**Comment by jonpmarino** [comment]
For the "receive the monthly digest of projects and updates", the idea solution would probably be to have a way to filter users in django-admin by clicked yes. As admins, we can then bulk download a .csv of these accounts and add the emails to our mailchimp

For "I agree with Terms and Conditions", the "Join MapStory" button should not work unless that is checked.

**Comment by travislbrundage** [comment]
As a side note, password length also doesn't seem to actually enforce the requirements it says (which is simply 8 character minimum).

**Comment by travislbrundage** [comment]
Terms and Conditions and Password length closed by [PR#213](https://github.com/MapStory/mapstory-geonode/pull/213)

**Comment by travislbrundage** [comment]
Resolved by [PR#34](https://github.com/MapStory/geonode/pull/34) and [PR#217](https://github.com/MapStory/mapstory-geonode/pull/217)
