### ISSUE TITLE
Site no longer sending the "Welcome to Mapstory" email.

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1219]
I assume this email was triggered when the user signed up, but based on my tests no emails are triggered in the current app.

**Note**: I haven't actually tried signing up on the new site to confirm this.

@jonpmarino please close if this functionality is no longer required.

```
FAIL: Ensure the signup works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/git/mapstory/mapstory-geonode/mapstory/tests.py", line 252, in test_sign_up
    self.assertEqual(len(mail.outbox), 1)
AssertionError: 0 != 1
    '0 != 1' = '%s != %s' % (safe_repr(0), safe_repr(1))
    '0 != 1' = self._formatMessage('0 != 1', '0 != 1')
>>  raise self.failureException('0 != 1')
```

**Comment by travislbrundage** [comment]
I didn't see such a test case in what's currently in the repo, I assume you made that test on your local copy? Either way, I believe I should have addressed this with this PR: https://github.com/MapStory/mapstory-geonode/pull/139

Includes my own version of testing it, but please let me know if I can test it better (kind of new to it).

**Comment by garnertb** [comment]
Fixed, closing.
