### ISSUE TITLE
Fix urls for maps and layers

### ISSUE THREAD

**Issue by davisc** [MapStory/mapstory-meta#1220]
- [X] mapstories should hold their URL - mapstory.org/maps/1234 
- [ ] storylayers should hold their URL - mapstory.org//layers/1234

**Comment by garnertb** [comment]
A quick hack for #1 may just be stripping the trailing "/" in an nginx directive.

Something along the lines of 
`rewrite ^\/maps\/(\d+)(\/+)$ /maps/$1 last;`

**Comment by garnertb** [comment]
Actually, scratch that, it seems like the JS is failing here so the nginx rewrite probably won't be helpful.

**Comment by jj0hns0n** [comment]
Fixed with https://github.com/MapStory/mapstory-geonode/commit/28d88e2ca7c63bfce0139b15a6c54b138ae615b6 and https://github.com/MapStory/mapstory-geonode/commit/dcd30c7084dfb86fbe6f2cd1d2e64b8fb43b98a7
