### ISSUE TITLE
Create an error template.

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1222]
The user currently sees the nginx error page, we should have a custom Mapstory one instead.
<img width="777" alt="screen shot 2015-10-18 at 11 05 18 am" src="https://cloud.githubusercontent.com/assets/1141646/10564610/6cda5c40-7588-11e5-93fc-ca8b587eb194.png">

**Comment by jonpmarino** [comment]
Rey has a .jpeg to use for this when we can implement

**Comment by Coop56** [comment]
@reynalddizon Can you post the .jpeg you want used here?

**Comment by jonpmarino** [comment]
![error_720](https://cloud.githubusercontent.com/assets/2573761/14859917/41865944-0c74-11e6-8208-0073f9300c07.jpg)

**Comment by Coop56** [comment]
This commit - https://github.com/MapStory/mapstory-geonode/commit/68cd56f3e567db15e3cdc45e764b713266713763 - should handle this.
