### ISSUE TITLE
OAuth Google/Facebook

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1226]
I want to be able to log in to mapstory using my google or facebook account linked to my profile.  Users from retro that used google/facebook to log in can do it on the current version.
#### Integrated Sign In
- [x]  Wiki, Help and Warper
#### Social Sign In
- [x] Google
- [x] Facebook

**Comment by davisc** [comment]
Pull request submitted. https://github.com/MapStory/mapstory-geonode/pull/130

**Comment by davisc** [comment]
A couple of issues encountered during testing:
- [ ] Redirect from auth provider goes to invalid url '/accounts/profile'
- [ ] Template doesn't honor ENABLE_SOCIAL_AUTH setting
- [ ] Layout of social buttons needs alignment

**Comment by zrouse-Boundless** [comment]
Creating new issue for above
