### ISSUE TITLE
Annotations layers are always assigned to Geonode Admin as owner and are read-only to other users

### ISSUE THREAD

**Issue by mbertrand** [MapStory/mapstory-meta#123]
When adding notes to a map, the annotations layer is always created with the Geonode Admin as the owner (even if created while logged in as another user) and is read-only to everyone else.  This prevents other users from adding any notes.   Should annotations layer permissions be set to editable by all registered users?

**Comment by ischneider** [comment]
Does it make sense that the annotations layer inherit the same permissions as the layer instead?

**Comment by mbertrand** [comment]
Do you mean inheriting the same permissions as the map?  If annotation layers are associated with maps, then I think it makes sense for them to inherit the same permissions as the map, and maybe gray out or hide the Add/Edit Note buttons from the menu if a user does not have edit permission.

From: Ian Schneider <reply@reply.github.com<mailto:reply@reply.github.com>>
Date: Fri, 13 Jan 2012 15:08:06 -0500
To: Matt Bertrand <mbertrand@cga.harvard.edu<mailto:mbertrand@cga.harvard.edu>>
Subject: Re: [mapstory] Annotations layers are always assigned to Geonode Admin as owner and are read-only to other users (#123)

Does it make sense that the annotations layer inherit the same permissions as the layer instead?

---

**Comment by awright** [comment]
not sure if the js configures the permission or django.  initially assigning to bart. please reassign to ian if more appropriate.

**Comment by bartvde** [comment]
The create_layer endpoint does not allow me to specify this, so reassigning to Ian.

**Comment by ischneider** [comment]
The creator of the map is given ownership of the annotations layer. That user may later change the permissions as they see fit.
