### ISSUE TITLE
MapLoom interface changes

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1231]
#### Editing StoryLayers
- [ ] Change "Layer Info" to "StoryLayer Metadata" and show layer metadata modal
- [ ] Change "Edit History" to be the default first thing an editor sees
- [ ] Hide "Delete" layer button
- [ ] Add a "Base Map" header above the basemap layers so there is division between the 2
- [x] Users should be able to see their editing-enabled StoryLayers on MapLoom (with geometries and timeline displayed correctly.)
- [x] Users should be able to add features on the map and consequently update the database.
- [x] Users should be able to click on features and see the feature info.
- [X] Users should be able to delete an existing feature.
- [x] Users should be able to access the table and see and navigate thru all the information. Users should be able to close the table as well.
- [x] Users should be able to change the basemap.
- [x] Add a link/button to enable the users to compose a mapstory using the edited layer
  <img width="1280" alt="save" src="https://cloud.githubusercontent.com/assets/4611843/9179395/3aeffb76-3f6a-11e5-930b-9d5cb919df87.png">
- [ ] In Table View, editing attributes is okay, but cannot sort a column, which makes things very hard when there are more than a few pages.
- [ ] Would eventually be very helpful to not have pagination. I know that there is an application online that does allow scrolling very large datasets, where it dynamically updates. In the meantime, perhaps would be good to be able to type page number and jump to page. 
- [ ] Cannot add cumulative layers...or do cumulative playback -Needed to refresh screen to see features we added rather than having them appear right away 
- [ ] Got the following error when hitting **"zoom to data" button**: "The following script error has occurred: "TypeError: json.BoundingBox is undefined". It is recommended that you reload the web page to resolve any potential complications." Appears to be two issues: 1) The request results in an exception and 2) the exception is not handled gracefully.

Request:

```
http://mapstory.org/geoserver/geonode/bear/wps?version=1.0.0
```

Payload:

```
<?xml version="1.0" encoding="UTF-8"?><wps:Execute version="1.0.0" service="WPS" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.opengis.net/wps/1.0.0" xmlns:wfs="http://www.opengis.net/wfs" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:gml="http://www.opengis.net/gml" xmlns:ogc="http://www.opengis.net/ogc" xmlns:wcs="http://www.opengis.net/wcs/1.1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsAll.xsd"><ows:Identifier>gs:Bounds</ows:Identifier><wps:DataInputs><wps:Input><ows:Identifier>features</ows:Identifier><wps:Reference mimeType="text/xml" xlink:href="http://geoserver/wfs" method="POST"><wps:Body><wfs:GetFeature service="WFS" version="1.1.0" outputFormat="GML2" xmlns:="http://geonode.org/"><wfs:Query typeName="bear"/></wfs:GetFeature></wps:Body></wps:Reference></wps:Input></wps:DataInputs><wps:ResponseForm><wps:RawDataOutput><ows:Identifier>bounds</ows:Identifier></wps:RawDataOutput></wps:ResponseForm></wps:Execute>
```

Response:

```
<ows:ExceptionReport xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.1.0" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://mapstory.org:80/geoserver/schemas/ows/1.1.0/owsAll.xsd">
<ows:Exception exceptionCode="NoApplicableCode">…</ows:Exception>
</ows:ExceptionReport>
```

I created a layer (see screenshot). One thing I notice is even though I did it under my account it shows that it is by "Administrator". When I click to "edit" the layer in maploom I get an error (see screenshot below). If I X that error our and just try to add features anyway the Add form looks good with my fields, but I get an error message when saving (screenshot)
![3333](https://cloud.githubusercontent.com/assets/2573761/10919698/3f59f636-823a-11e5-973f-d50fa9294471.jpg)
![3311](https://cloud.githubusercontent.com/assets/2573761/10919705/45a8fa32-823a-11e5-8da1-d29729c84c75.jpg)
![88888](https://cloud.githubusercontent.com/assets/2573761/10919708/4b9a1750-823a-11e5-86b2-a657d869f5b6.jpg)

**Comment by jonpmarino** [comment]
Closing, as this is based on old maploom, unless someone seems utility in leaving it open.
