### ISSUE TITLE
Help.Mapstory cleanup

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1232]
- [x] Get application up and running again
- [x] Delete all posts
- [x] Test authentication with mapstory.org

**Comment by davisc** [comment]
The following error prevented the askbot application from running correctly after start up. This was due to the memcache service not running. Starting the memcache service resolved the issue and the application is now up and running.

```
File "/usr/local/lib/python2.7/dist-packages/askbot-0.7.48-py2.7.egg/askbot/context.py", line 35, in application_settings
    my_settings['LANGUAGE_CODE'] = getattr(request, 'LANGUAGE_CODE', settings.LANGUAGE_CODE)
TypeError: 'NoneType' object does not support item assignment

```

**Comment by davisc** [comment]
The oauth integration between mapstory.org and help.mapstory.org is enabled and working as designed.

**Comment by ChristopherTucker** [comment]
HELZ YEAH!

Chris
703-981-9373
