### ISSUE TITLE
ERROR: Invalid HTTP_HOST header: 

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1240]
To avoid spamming the admins, hosts that are not in the ALLOWED_HOSTS list should be blocked by nginx.  

Adding this to the nginx config should do the trick, but needs to be tested.

```
    {% if django_allowed_hosts is defined %}
    ## Deny illegal Host headers
    if ($host !~* ^({{django_allowed_hosts|join('|')}})$ ) {
        return 444;
    }
    {% endif %}
```

**Comment by davisc** [comment]
@garnertb: I’ve tested the change to deny illegal host headers and will prepare a change-set to commit to the repo.

**Comment by davisc** [comment]
This change is included in the following commit - https://github.com/MapStory/mapstory-geonode/commit/f5bf8647175f20d246224f9a4a0df660f3d8a870
