### ISSUE TITLE
Social Oath login wrapup

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1243]
A couple of issues encountered during testing:
- [x] Redirect from auth provider goes to invalid url '/accounts/profile'
- [x] Template doesn't honor ENABLE_SOCIAL_AUTH setting
- [x] Layout of social buttons needs alignment

**Comment by davisc** [comment]
I've implemented a temporary fix for the first checkbox item https://github.com/MapStory/mapstory-geonode/commit/2774f9a7cb393573e01c1807829a6cc8bdfd2a6f#diff-9facdb61078fa65d34de1af84a3c9f7dR49

I've added ENABLE_SOCIAL_AUTH to the context processor

I've updated the modal layout based on Rey's input
