### ISSUE TITLE
Search errors: /api/base/search/

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1246]
This needs to be investigated, as the errors are happening quite a bit.

```
ERROR (EXTERNAL IP): Internal Server Error: /api/base/search/
Internal Server Error: /api/base/search/

TypeError at /api/base/search/
int() argument must be a string or a number, not 'NoneType'

Request Method: GET
Request URL: http://mapstory.org/api/base/search/?owner__username__in=abhisindal70
```

**Comment by davisc** [comment]
The error message is the result of missing request parameters; limit and offset. Chances are that this request is being made outside of the expected application flow and possibly by a link harvesting bot.

```
/site-packages/django/core/paginator.py", line 24, in __init__
self.per_page = int(per_page)
TypeError: int() argument must be a string or a number, not 'NoneType'
```

```
site-packages/tastypie/resources.py", line 195, in wrapper
 int(request.GET.get('offset')) /
TypeError: int() argument must be a string or a number, not 'NoneType'
```

Here is a valid http request:

```
http://mapstory.org/api/base/search/?owner__username__in=abhisindal70&limit=10&offset=0
```

A safe approach would be to modify https://github.com/MapStory/geonode/blob/master/geonode/api/resourcebase_api.py#L366 to return a default value if the GET request parameter is not found.

**Comment by davisc** [comment]
Fixed
