### ISSUE TITLE
Threaded Comments

### ISSUE THREAD

**Issue by travislbrundage** [MapStory/mapstory-meta#1248]
Implement threaded comments in MapStory

**Comment by travislbrundage** [comment]
Addressed here: https://github.com/MapStory/mapstory-geonode/pull/140

**Comment by jonpmarino** [comment]
comments is working, but no user confirmation currently.

**Comment by travislbrundage** [comment]
Two issues remaining with threaded comments, both of which I have posted on the owner of the app we're using's github issues and I am currently awaiting a response. I will circle back to work on this issue more after knocking out my others for this sprint.
- [ ] Posting a comment redirects you rather than updating within the page. Would be a nicer user experience to just have the form disappear and tell you your comment is posted without changing the page.
- [ ] Currently no limit on number of comments shown. Implementing pagination of some sort will be necessary at some point in the future.

**Comment by jonpmarino** [comment]
These are minor issues. Will move this off to MVP for now.
