### ISSUE TITLE
created annotations layer does not support null geometries

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#125]
This prevents "note" annotations. This means a change to gsconfig.py to support nullability in the schema.

**Comment by ischneider** [comment]
I've made the changes to the backend to support this. The client code needs to be adjusted to add nullability to the geometry. For example, instead of:

```
title:java.lang.String,the_geom:com.vividsolutions.jts.geom.Geometry,timestamp:java.util.Date
```

The posted attributes data should be:

```
title:java.lang.String,the_geom:com.vividsolutions.jts.geom.Geometry:true,timestamp:java.util.Date
```

The true specifies that the the_geom is created nillable.

**Comment by bartvde** [comment]
Thanks Ian, fixed in geonode-client with https://github.com/opengeo/geonode-client/commit/40c0f6172623f2f2b13a8f87f11cc177ec4260d8
