### ISSUE TITLE
Fix default storybox

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1253]
get time slider events firing again

**Comment by jonpmarino** [comment]
fixed. should be pushed by 12/14

**Comment by davisc** [comment]
The default storybox fix has been been applied and is functioning properly, however, it appears as though the slider is not sending the correct time step to the timeline for existing stories due to the default value for the interval.

**Comment by davisc** [comment]
The default behavior is as follows:
- If no storybox, calculate the range and interval from the time dimension on the layer(s).
