### ISSUE TITLE
Add client-side "Upload" to icons commons modal

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1254]
Should support users uploading a single .svg or a zipped file with several. Upload modal should tell the user they confirm that they have permission to share their icons, and that they are willing to license them into the Creative Commons (CC0).

**Comment by jonpmarino** [comment]
Basic work is done. Needs to be integrated into composer/styling UI

**Comment by jonpmarino** [comment]
client side support

**Comment by Coop56** [comment]
Commenting here for myself - doing some research throughout the Git repo to find all of the issues and conversations related to icons commons for reference.

https://github.com/MapStory/mapstory/issues/1017
https://github.com/MapStory/mapstory/issues/1460
