### ISSUE TITLE
Support raster uploads in the new uploader.

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1264]
First, simple raster upload (geotiff?)

Second, temporal sequence, http://geoserver.geo-solutions.it/multidim/en/mosaic_config/temperature_mosaic.html

Third, integrate warper.mapstory.org to enable users to more simply "publish to mapstory" their georeferenced maps without a separate download>desktop>upload process

**Comment by jonpmarino** [comment]
From @bitner - dependent on work being done to get feature parity on upload styles and metadata.

**Comment by glynnis** [comment]
Closing this. If this is still relevant, please create a new issue with more detail at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.
