### ISSUE TITLE
osgeo_importer should gracefully handle non-UTF8 encoded characters

### ISSUE THREAD

**Issue by garnertb** [MapStory/mapstory-meta#1273]
`invalid byte sequence for encoding "UTF8": 0x89`

**Comment by jj0hns0n** [comment]
Basic upload with a shapefile with chinese characters worked. Do we have an example of one that didnt work? @reynalddizon 

Note the characters dont actually display properly in the front end, see below.

<img width="1271" alt="screen shot 2016-02-26 at 11 31 57" src="https://cloud.githubusercontent.com/assets/506078/13363200/05491f1a-dc7d-11e5-8971-f28635d13749.png">

**Comment by ChristopherTucker** [comment]
It did not display mandarin in the attributes.

**Comment by jj0hns0n** [comment]
@ChristopherTucker thats what it says there above (Note the characters dont actually display properly in the front end, see below). Looking into it.

**Comment by jj0hns0n** [comment]
This test case is now working with https://github.com/ProminentEdge/django-osgeo-importer/commit/4a974114336bc765115b14f88ce2060ee90ce853 for me locally with the additions to the `__init__.py` ... but now we see "Invalid Byte Sequence" in travis. https://travis-ci.org/ProminentEdge/django-osgeo-importer/jobs/112158903 ... Im investigating.

**Comment by jj0hns0n** [comment]
UTF-8 encoding errors are now caught (but not acted on) after https://github.com/ProminentEdge/django-osgeo-importer/commit/b9848634c0e07ddc1d3d006779c376b543386692 and https://github.com/ProminentEdge/django-osgeo-importer/commit/0df8f531feffdd2feca475f7f7841d84d7c542b5 ... We need to decide how to act on them now. @garnertb grab me on slack to discuss.

**Comment by jj0hns0n** [comment]
@garnertb I think we can close this now that the tests are all passing right?

**Comment by garnertb** [comment]
@jj0hns0n yep.  Closed.
