### ISSUE TITLE
Add fields for mapstory metadata in new importer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1279]
For MapStory, we expect users to add these fields with new storylayers they generate:

StoryLayer name, Summary Abstract, Language, Data Source, Data Quality Statement, Purpose. See StoryLayer viewer page Metadata tab for existing fields that users need to be able to populate

**Comment by garnertb** [comment]
Are these fields required?  If so, we need to come up with a workflow that enforces it.

**Comment by jonpmarino** [comment]
Only one I would require is "data source". The rest the user is free to not complete and just be crappy. An ideal future feature would be a indicator to show the viewer that the story is X % complete...like we used to have for Profile based on number of fields complete. But these are low priorities. For now just need metadata fields in the modal at a basic level so the user has a place to input.

**Comment by jonpmarino** [comment]
i think we are just pointing people to metadata edit modal as the last point in upload process instead of a separate workflow.

**Comment by rob-metalinkage** [comment]
Can we make this extensible - i.e. dont assume a fixed metadata schema - but allow a profile to select the mandatory elements - and maybe allow users to choose profile - perhaps something like
- "test" - your data wont be visible to others
- "undocumented" - you can publish but no one will find your data
- "basic (abstract, language)" - stories will be discovered by search
- "CommunityX" - compliant with the metadata requirements of CommunityX (e,g, US gov)

Each profile would specify mandatory elements, and have a means to specify the controlled vocabulary to use, and perhaps define static tags. 

This then gives us an extensibility mechanism - and opportunity to offer customised MapStory hosting for specific communities.

The "featured" functions could then highlight stories tagged according to the profiles relevant to the user (or prioritised by MapStory)

**Comment by rob-metalinkage** [comment]
where will this work take place? Will this require fork of https://github.com/ProminentEdge/django-osgeo-importer
