### ISSUE TITLE
slider on timeline doesn't change scale

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#129]
It's doesn't look like changing the scale slider on the left side of the timeline does anything to change the range of dates.

**Comment by awright** [comment]
said another way -- i can't seem to figure out how to "move into" the timeline.  i am working with the mexican murder map on the dev site.

**Comment by bartvde** [comment]
The slider controls the percentage of the time range that is used in the timeline (the WFS queries behind the timeline actually). Initially it's at 25%. As in my example from e-mail, if the time range is 1900-2000, it would initially get data for 1900-1925. If you move the slider down to 5%, it will get data for 1900-1905 etc.
So the slider does not control the time scale of the timeline, it controls the date range used in the WFS request.

**Comment by awright** [comment]
So, the user gets no visibile feedback from moving the slider?  Doesn't it
make sense to change what's in the scale of the timeline?  (I'm not sure I
understand why the two are mutually exclusive....)

**Comment by bartvde** [comment]
Hey Alyssa, are you looking for something like this demo:

http://ec2-50-19-52-89.compute-1.amazonaws.com/AlsTimelines.html

**Comment by awright** [comment]
Yes.  Exactly.

On Fri, Jan 20, 2012 at 10:44 AM, Bart van den Eijnden <
reply@reply.github.com

**Comment by bartvde** [comment]
URL gives a 404 now, so use http://ec2-50-19-52-89.compute-1.amazonaws.com/AlsTimemaps.html instead

**Comment by bartvde** [comment]
This should have been improved with https://github.com/opengeo/gxp/commit/b0d2153c3bcb10ffa6eb10bcb69dc4bd1e17debd

**Comment by scrollie** [comment]
Agreed that it should work like that example.
