### ISSUE TITLE
celerybeat-schedule file causes ansible provision to fail on TASK: [web | mapstory update]

### ISSUE THREAD

**Issue by davisc** [MapStory/mapstory-meta#1290]

**Comment by garnertb** [comment]
.gitignore?

**Comment by davisc** [comment]
Yeah that's what I was going to try.

**Comment by garnertb** [comment]
celerybeat-schedule was added to the .gitignore in https://github.com/MapStory/mapstory-geonode/commit/10ba816998ed07022d75acf1d6e440ffffd77f9b.  Closing.

Re-open if future provisions fail.
