### ISSUE TITLE
Synchronize Django and Tomcat cookie domains

### ISSUE THREAD

**Issue by davisc** [MapStory/mapstory-meta#1294]
The default cookie domain for Django and applications running in tomcat is 'mapstory.org'. Changing the Django session_cookie_domain to '.mapstory.org' to handle wildcard sub-domains and share a session cookie (login session) across multiple subdomains requires a corresponding change to Tomcat for the Geoserver Geonode Auth Plugin to find the cookie collection and honor the GeoNode session.

**Comment by garnertb** [comment]
This was fixed in https://github.com/MapStory/mapstory-geonode/commit/0e47844ae58e5bd74ba8601cb4a6a89e92336c29.  Closing.
