### ISSUE TITLE
non admin user accounts unable to edit layers

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1297]
StoryLayer setting options > Public or Private? Only I can edit or the Community can edit?

MapStory setting options > Public or Private? (no editing of mapstories)

Styles of StoryLayers > base style for all storylayers. Users create a custom style when composing mapstory that persists on playback..

Styles of MapStories > just owners can change

Deleting or changing StoryLayer settings > just owners or admins

Deleting or changing MapStory settings > just owners or admins

Any visitor to MapStory.org can = explore and view storylayers, mapstories, user profiles

Any registered user of mapstory can = download/upload data, create StoryLayers, make edits to community edited layers, compose MapStories, create and tend to their profile, conduct peer review and social activities (messaging, flagging, tagging, commenting)

Admins can = delete StoryLayers, MapStories and users, change settings of StoryLayers and MapStories, freeze editing of storylayers if something goes wrong.

**Comment by davisc** [comment]
As a newly registered user account, I am not able to edit layers that I do not own within the map viewer. Comparing the permissions within django guardian to the results of the authorize_url db function for the auth plugin, reveals a potential bug.

Below is the list of layers the user account  `demo` has `read/write` access to.

<img width="948" alt="screen shot 2016-04-18 at 8 47 30 am" src="https://cloud.githubusercontent.com/assets/947403/14606416/c50a4688-0542-11e6-95c1-d6f8c7961f81.png">

Below is the query and results for the authorize_url db function for the same user and the `geonode:walmart` layer.

Query: `SELECT geonode_authorize_layer('demo', 'geonode:walmart');`

Result: `ur-ro`

Looks like the code responsible for the permissions list in django checks for `change_layer_data`

https://github.com/MapStory/geonode/blob/master/geonode/geoserver/views.py#L485

where as the authorize_layers function checks for the `change_resourcebase` and based on the results, only the owner of the layer has the `change_resourcebase` permission.

https://github.com/MapStory/mapstory-geonode/blob/master/scripts/provision/roles/db/files/geonode_authorize_layer.sql#L53

It appears that changing the function to check for the `change_layer_data` permission resolves the issue.

**Comment by ingenieroariel** [comment]
I think it is a good idea. That permission is only applied to layers and you would be changing authorized_layers.

I think the confusion started because there is `edit_perm` (only for layers) and `change_perm` (for all resourcebases).

-a
