### ISSUE TITLE
Change "Distribution URL" in metadata modal to "Data Source"

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1298]
this way what we have on front-end "metadata" tab mirrors title of fields in metadata modal
![meta](https://cloud.githubusercontent.com/assets/2573761/12218043/169460b6-b6e1-11e5-887c-63c53026311d.jpg)

**Comment by garnertb** [comment]
Fixed in https://github.com/MapStory/mapstory-geonode/commit/53ef8d05d453e5bb7bd0e19e3bc18bf0102d98a4.
