### ISSUE TITLE
Faceted search

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#13]
Search various "facets" of data with selectable values - for example we might let the user choose a data topic in which to search. http://en.wikipedia.org/wiki/Faceted_search

**Comment by scrollie** [comment]
What sort of facets do we have available? Type (map, data, user, group)? Date (uploaded, modified)? User (handle, real name)? Geography (extent)? Social (average rating, # of comments)? Text (title, abstract, keywords)? 

Anyone else want to throw in some useful/available parameters for search?

**Comment by dwins** [comment]
I don't think dynamic facets are going to be tenable in the near term - so our facets will effectively be preset search parameters. Also, we don't have some of the potential facets you mentioned (groups, comments.)

How about these facets:
- **type** can be map/layer
- **data time extent** is a free selection (start and end date, both optional.)
- **data spatial extent** is a free selection (draw a bbox on a map)

I don't think most users are going to care about whether a keyword appears in the title vs. abstract, but some folks seem to put a lot of weight in keywords.  Keywords may not make sense until we can do dynamic updating of the facet options (ie, only once you've narrowed down the candidate layers a bit does it offer you the top 10 keywords for that subset of the geonode.)

**Comment by bartvde** [comment]
AFAICT this was done. Closing. Please reopen if something is missing.
