### ISSUE TITLE
confusing filter behavior

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#130]
1. opened the mexican murder map
2. zoomed in to scale 1:1091958 over Aguililla (see https://skitch.com/alyssawright/g33r5/map-viewer-geonode for reference)
3. set filter to deaths > 5.  

expected: saw one item on the timeline displayed
1. set filter to deaths = 5.  

unexpected: no info on timeline
1. changed filter to deaths <> 0

expected to see multiple points on timeline removed (0E-10)
unexpected result: no change in timeline display

**Comment by bartvde** [comment]
Hey Alyssa, I am getting a different behavior, which is more consistent. See:

http://imageshack.us/photo/my-images/862/screenshot20120123at357.png/
http://imageshack.us/photo/my-images/825/screenshot20120123at357.png/

Please note one thing that might not be very intuitive, the filter is only applied when the value field blurs, i.e. loses its focus.

**Comment by bartvde** [comment]
I cannot reproduce this anymore on the dev server, so closing this one. Please reopen if it occurs again.
