### ISSUE TITLE
Enable admin editing of front-end parralax images

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1300]
The homepage and header of profile pages have parralax images (animated gifs). Need admin to be able to upload and change these images.

**Comment by travislbrundage** [comment]
You should already be able to edit these, although it's a bit strange to do. Basically each one has a "name" and you have to modify the already existing ones to change what shows up on the page.

The header one is called "Africa" right now. On the home page, they're just called Parallax1, Parallax2, and Parallax3.

http://mapstory.org/admin/mapstory/parallaximage/

Noting to myself for future clean up: adjusting the names will probably make it far more intuitive.
