### ISSUE TITLE
Multi-language support

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1301]
- [x] Translate mapstory website texts to different languages
- [x] Enable language toggle tool

**Comment by jj0hns0n** [comment]
Working with https://github.com/MapStory/mapstory-geonode/pull/173 ... @jonpmarino and I have access to transifex, others can be added as necessary.

**Comment by jj0hns0n** [comment]
@jonpmarino can we close this one?

**Comment by jonpmarino** [comment]
Yes. confirmed live on beta. Need to remember to push to production though, @davisc
