### ISSUE TITLE
fixes to "edit profile"

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1302]
- [x] Interests > change help text to "separate each interest with a comma"
- [ ] Interests > make sure each interest is separate by comma, not word
- [x] Make interests a clickable item that generates a Search>Storytellers filtered by that interest
- [x] Join the Volunteer Technical Community > add the text "What's this? Learn more here" (link to http://wiki.mapstory.org/wiki/Volunteer_Technical_Community)
- [x] City > change help text to say "What city do you spend most of your time in?"
- [x] Country > change help text to say "What country do you spend most of your time in?"
- [x] Profile > change help text to say "Introduce yourself in under 200 characters"
- [x] Under "user action", change "create mapstory" to "compose a mapstory"
- [x] Add space to let users link to Twitter, Facebook, linkedin, github profiles
- [x] Add Education, Skills, Interests (tags) on the left sidebar.
- [ ] Favorites tab in Profile should display Cards instead of a list, for consistency.
- [x] Give user ability to set notification preferences: Options are: Notify me immediately | Send me a Daily  Summary | Send Me a Weekly Summary (choices = When my StoryLayer is edited, When someone comments on my work, when someone flags my work, when someone favorites my work.

**Comment by jj0hns0n** [comment]
<img width="1229" alt="screen shot 2016-02-22 at 15 04 14" src="https://cloud.githubusercontent.com/assets/506078/13235953/125a5bb0-d976-11e5-83cc-355fee061c12.png">

**Comment by jonpmarino** [comment]
looks good @jj0hns0n

**Comment by jj0hns0n** [comment]
@jonpmarino can you give me some clarity on "Add space to let users link to Twitter, Facebook, linkedin, github profiles". Should we just add a profile field for each of these 4 or something more extensible/generic?

**Comment by jj0hns0n** [comment]
@jonpmarino also not clear on this one "Add Education, Skills, Interests (tags) on the left sidebar."

**Comment by jonpmarino** [comment]
@jj0hns0n on old mapstory.org site (retro.mapstory.org) we had place in "edit profile" to add the slug for those social media accounts. When the user saved, on their profile the icon/logo of each social media entity would appear, and it would be hyperlinked to the user's social media account. So what you described probably works.

**Comment by jonpmarino** [comment]
@jj0hns0n on the "Add Education, Skills" question: Its an issue of migrating that user account data from retro.mapstory.org and having a field for it to live on current mapstory.org profile. We had space for people to input their Education History and skills in the old account. Don't have place for it in new. So its 1) Creating place in new profile for it to appear and 2) migrating data from old user accounts.

**Comment by jj0hns0n** [comment]
@travislbrundage can you help with the 2 remaining issues here
- Interests > make sure each interest is separate by comma, not word (This should use a bootstrap tokenfield of some sort)
- Favorites tab in Profile should display Cards instead of a list, for consistency.

**Comment by jj0hns0n** [comment]
@jonpmarino can you file 2 new issues for the last 2 things I mentioned in the last comment to @travislbrundage and close this issue once verified in production.

**Comment by jonpmarino** [comment]
will do

**Comment by jonpmarino** [comment]
Closing this issue. All checked items test. Creating new issue for Interests, #1358. Lets forget about the favorites as card for now. List looks pretty good actually.
