### ISSUE TITLE
legend performance and design

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1306]
- [x] Legend needs to condense to height when longer than youtube/embed height. Currently it extends beyond the screen height without a scroll bar for the user to see content.

**Comment by jonpmarino** [comment]
Legend covers time controls in viewer page

http://mapstory.org/maps/475

![legend](https://cloud.githubusercontent.com/assets/2573761/13502973/2fff3470-e13b-11e5-8efc-f2b6fdf17029.jpg)

**Comment by zrouse-Boundless** [comment]
Legend might have to be scrolable
