### ISSUE TITLE
timeline filtering

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#131]
would be nice -- by default -- to have the timeline styling derived from the SLD.  i would like to investigate whether this would clarify timeline behavior.  if the effort involved in implementing this is minimal, we should look to address by the feb demo.

**Comment by awright** [comment]
related to #24

**Comment by bartvde** [comment]
Unfortunately the styling of timeline events in SImile is very limited. You can only specify a basic hard-coded URL to an image, which is what I did for annotations.

**Comment by bartvde** [comment]
The timeline now takes the filter from the SLD, but this does not seem testing. So let's see if this improves things.

**Comment by awright** [comment]
"but this does not seem testing"

do you mean, this needs testing?

On Tue, Feb 7, 2012 at 8:32 AM, Bart van den Eijnden <
reply@reply.github.com

**Comment by bartvde** [comment]
Yeah sorry that's what I meant :-)
