### ISSUE TITLE
Add embed code for StoryLayers as well as mapstories

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1316]
Not sure if this is possible, but to consider:

Can a user embed a StoryLayer on an external site, like they can a MapStory? This would enable an organization managing a "crowd-editing" campaign to feature a layer on their website by embedding it.

**Comment by travislbrundage** [comment]
Doing some research into this, it does not exist by default. GeoNode provided an embed option for maps, but not for layers. I may be able to recreate the functionality for layers, but it doesn't currently exist. I'm not sure if there's some technical reason that makes this impossible, but assuming it's just a new functionality that needs to be implemented, that would make this a medium pick in my eyes. It's not trivial, but shouldn't be an immense amount of work provided there's not too many technical "gotchas" hiding in this issue.

**Comment by travislbrundage** [comment]
I have a lot more notes on this issue, but they're on physical paper... the WIP branch for this is here: https://github.com/travislbrundage/geonode/tree/layer-embed

**Comment by travislbrundage** [comment]
MapStory embedding resolved by [PR#214](https://github.com/MapStory/mapstory-geonode/pull/214) and [PR#32](https://github.com/MapStory/geonode/pull/32).
