### ISSUE TITLE
Composer UI

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1318]
## Mile 2: Adding a New StoryLayer
- [ ] My Favorites tab should show all the story layers the user has favorited (in card form) (Mila)
## Mile 4: Adding a new StoryPin
- [ ]  Pin Location button should capture the coordinates of the pin: Lat and Long
- [ ]  A working pair of text input boxes for the time frame. An error message/alert should be displayed if the end time occurs before the start time.
- [ ]  A working save button to update the Storybox details.
- [ ] List down the added StoryPins on Level2-StoryPin
## Mile 5: Implementing MapLoom Editing Features (See [Composer-Editing Documentation])(https://github.com/reynalddizon/MapStoryOrg/raw/master/composer-editing.doc.pdf))
- [x] “Edit an existing feature” button should trigger sidebar collapse and display a help text on the map panel.
- [ ] Layer Metadata form must have a save button for updating metadata fields.
- [ ]  View history
## Mile 7: Basemap, Timeline and Layout
- [ ] Implement UI for rearranging the list items (Chapters List, StoryLayers List, StoryPins list, StoryBoxes list) (Drag and drop)

**Comment by travislbrundage** [comment]
Implement the collapsible sidebar behavior. - Done, not pushed yet.
Basemap (on the right) should resize depending on the behavior of the sidebar (active or inactive) - Not done, should be done in less than an hour.
Title bar should contain the title of the MapStory - Done, not pushed yet.
 Title bar should contain a working Properties button which will call the MapStory Properties modal - Not done, should be done by the end of the day/tomorrow morning.
Title bar should contain a working Save button which will call the Save MapStory modal - Not done, should be done by the end of the day/tomorrow morning.
Title bar should contain a working Preview button which will launch the MapStory preview mode - Not done, should be done by the end of the day/tomorrow morning.
Help should be able to launch a new tab containing the Get Skills page - Done, not pushed yet

**Comment by travislbrundage** [comment]
"Title bar should contain a working Save button which will call the Save MapStory modal."

This is partially working, the only thing not working is publishing directly - it saves the map, but currently you still have to go to your profile to publish your draft map.

**Comment by travislbrundage** [comment]
"Title bar should contain a working Summary button which will call the MapStory Summary modal. Include the Title, Summary, Category Tags, and Location fields."

This exists on the front end and properly sends the JSON when saving the MapStory. The JSON needs to be received by the backend to save it correctly though. Also, the javascript will be reworked to support Maps comprised of chapters.

**Comment by Coop56** [comment]
The PDF says to have a Start Editing button that calls the editor and collapses the menu which is what I have just added.  Would you rather split that into two buttons Add a New Feature and Edit an existing Feature like the other doc above says?  @reynalddizon

**Comment by Coop56** [comment]
@reynalddizon I pulled the old  Layer Metadata form and modified it so it works with the new composer.  It was never built to be editable though - so is this something that needs added?  I'm referencing the below list item.

Layer Metadata form must have a save button for updating metadata fields.

**Comment by reynalddizon** [comment]
@Coop56 for the first question , yes. please split it into two. Ignore the one in the composer2.0 doc and follow the one shown in composer-editing doc. and as for the metadata, yes, we need that to be editable.

**Comment by zrouse-Boundless** [comment]
@reynalddizon  can you spit this into separate issues?

**Comment by reynalddizon** [comment]
@zrouse-Boundless done. closing this one now. Split this issue into Issues #1377 #1378 #1379 #1380 #1381 #1382
