### ISSUE TITLE
Add bit of user-feedback to indicate Upload is done

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1319]
Currently uploader has a nice progress bar that shows percent complete of an upload. When it gets to 100% the user infers the upload is done but isn't sure.

Lets have some bit of notification confirming that upload is complete so the user knows to hit "Continue". Perhaps the words "upload complete" could appear to the right of the Progress bar once 100% is hit.

**Comment by garnertb** [comment]
Can we just hide the progress bar?

**Comment by jonpmarino** [comment]
After 100% is reached? Yeah, that seems like a great solution. Just something to indicate completion

**Comment by garnertb** [comment]
Sounds good, @JWileczek can you do this?

**Comment by JWileczek** [comment]
Can do
