### ISSUE TITLE
about this map dialog interferes viewing map

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#132]
when viewing a map -- if one leaves or refreshes a map view -- the  "About this Map" dialog pops up.  at minimal this should be removed. panning a map should not be considered an edit -- and therefore a user wouldn't be prompted to add about info.

**Comment by mpriour** [comment]
Yes, this the most annoying thing. Glad to hear that we can remove it

On Wed, Jan 18, 2012 at 10:16 AM, alyssa wright <
reply@reply.github.com

> wrote:
> 
> when viewing a map -- if one leaves or refreshes a map view -- the  "About
> this Map" dialog pops up.  at minimal this should be removed. panning a map
> should not be considered an edit -- and therefore a user wouldn't be
> prompted to add about info.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/opengeo/mapstory/issues/132

## 

Matt Priour
OpenGeo - http://opengeo.org/
Expert service straight from the developers

**Comment by bartvde** [comment]
This has been removed already. Closing.
