### ISSUE TITLE
Change Upload StoryLayers link to new uploader modal

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1320]
![home_720](https://cloud.githubusercontent.com/assets/2573761/12682752/2b89d288-c683-11e5-942d-26e3778e0518.png)

currently goes to dead uploader link

**Comment by garnertb** [comment]
Fixed here: https://github.com/MapStory/mapstory-geonode/commit/decf3687f5fed647b2521652ce21e7bfab598e44.  Will deploy soon.
