### ISSUE TITLE
Update Create Layer modal text

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1322]
- [ ] GEOMETRY (see image below). We need to find a good example of each type and hyperlink. 
  ![5555_720](https://cloud.githubusercontent.com/assets/2573761/12683371/dd55813a-c686-11e5-9ba0-0bef0287c0f5.png)
- [ ] ATTRIBUTES: "Next you'll need to define the attributes you have for the features in your StoryLayer. Attributes are just the pieces of information you have for features. For example, if you are mapping the spread of libraries in the world, your attributes might be "Library Name" and "Date Built". The "Location" attribute will be added when you create your features later, so don't work about that now. But note that after you set your attributes here now you won't be able to change them later. So think hard!

**Comment by Coop56** [comment]
No longer relevant, this modal has been rebuilt.  Closing.
