### ISSUE TITLE
Download Schema Link Pointing Back at Itself

### ISSUE THREAD

**Issue by nittyjee** [MapStory/mapstory-meta#1327]
I am trying to use "append", and all it does when I click on  "Download Shape-file schema" is go back to the same page I was already on. For example - when I go here:
http://mapstory.org/layers/geonode:final_florida_20
and click "Append", and then click "Download Shape-file schema", it goes back to that same page.

John says he believes at the moment it has something to do with the users permissions to download, will take care of it soon,

**Comment by jonpmarino** [comment]
addressed as a comment in another issue
