### ISSUE TITLE
Add Timestamp to Storylayers Upon Creation

### ISSUE THREAD

**Issue by nittyjee** [MapStory/mapstory-meta#1328]
Storylayers don't have the date they were created, small and probably low priority now, but super important.
Uploaded this one yesterday, not seeing a date anywhere (same for any other storylayer):
http://mapstory.org/layers/geonode:permitstotakewater%20testing%20uploader

**Comment by travislbrundage** [comment]
There's a timestamp on created StoryLayers and MapStories already. I can add it to the detail page on the front end. What do we want for this?

**Comment by davisc** [comment]
Take a look at the resourcebase model, there is an existing date field that I believe is being used as the created date, can you confirm? Although I agree your change is more explicit.

**Comment by travislbrundage** [comment]
Yeah, I edited my comment when I realized that was reflecting that. Although it appears as though you can change it.

I'm guessing we just want to add a "Created on [date]" on the detail page?

**Comment by davisc** [comment]
@travislbrundage  and the search cards

**Comment by jonpmarino** [comment]
I don't know if we need it on the card itself. @reynalddizon ? Judging from the original mockup, having the date will be great for enabling the "date" filter, but not sure we need to expose the date itself on card. Yes to layer detail page
![explore](https://cloud.githubusercontent.com/assets/2573761/13883352/5b99c526-ecff-11e5-937d-ab1c232d430b.jpg)

**Comment by reynalddizon** [comment]
i would only agree to put it in the cards if we find a way to make the date attribute human readable, not the one that looks like 1999-12-12'T'01:01:01.

**Comment by travislbrundage** [comment]
Converting it to human readable shouldn't be an issue. So on both the detail and card, I'll put something like:

Created Jan 1st, 2015
