### ISSUE TITLE
Support data uploads that extend to geologic time (4.5 billion years)

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1329]
Many StoryLayers will want to express B.C. time periods. Should include geologic time (-300m BCE), just as was supported on retro.  Later we need to get back to 4.5billion years.

**Comment by zrouse-Boundless** [comment]
Assumption: Geotools, PostGIS, and Geoserver are set for this.  This is just making sure the python can handle the -Time

**Comment by bitner** [comment]
it looks like currently the date parsing behavior when given just a year is to return the current date in that year (ie parse('2000') returns 2000-02-17). I'm assuming that behavior should be to return 2000-01-01?

**Comment by garnertb** [comment]
That seems sane to me.

On Wed, Feb 17, 2016 at 4:00 PM, David Bitner notifications@github.com
wrote:

> it looks like currently the date parsing behavior when given just a year
> is to return the current date in that year (ie parse('2000') returns
> 2000-02-17). I'm assuming that behavior should be to return 2000-01-01?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MapStory/mapstory/issues/1329#issuecomment-185401050.

## 

-Tyler Garner

**Comment by jonpmarino** [comment]
agreed.

**Comment by bitner** [comment]
Slight issue. PostgreSQL timestamptz data type can only store dates between 4713 BC and 294276 AD (http://www.postgresql.org/docs/9.4/static/datatype-datetime.html). I've got the tweek so Python will read and set the negative or "BC/BCE" times correctly in the ogr.OFTDateTime field, but we are outside the limits of PostgreSQL storage if we go into geologic time.

One possible option would be to add a second year column that just contains the year. As most use cases that would go prior to human history would not have anything at a higher resolution than the year, it might work to at a certain scale switch the time slider code from using the full timestamp to just the year column.

**Comment by jonpmarino** [comment]
this sounds reasonable to me. Can't imagine any data that we might deal with that has deeper than annual further back than 4713 years. In terms of geologic time is there a limit on how far back that goes? Internally we've used 4.5 billion as a marker

**Comment by jonpmarino** [comment]
Work is done. Waiting on @garnertb to pull in with other changes this week.

**Comment by jonpmarino** [comment]
Created layer with BC dates -  In our time controls on playback, BC dates appear to march from small number to larger, rather than counting down to year 0. http://mapstory.org/layers/geonode:polling_no_az_messed_up_dates_negative_time

**Comment by jonpmarino** [comment]
In Jira. Closing, but there is important discussion here to track.
