### ISSUE TITLE
indicate animation frame and timeline relationship

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#133]
currently it's difficult to determine how the timeline relates to the current view of the map.  i suggest we place a visible red line that indicates the date of the current frame.  for reference:

https://skitch.com/alyssawright/g33c3/map-viewer-geonode

**Comment by bartvde** [comment]
You really want the red line to go through the text? Should we run this by Rollie first?

**Comment by awright** [comment]
Yes. Let's discuss with Rollie et al next week.  (Though if he has the
chance, I'll ask him to review beforehand.)

**Comment by scrollie** [comment]
I think it makes sense to have a "present time" indicator, though I don't think Alyssa is literally advocating for a thick red line over the text.

The "zoomed out" timeline showing decades beneath the main "yearly" one establishes a similar effect with a slightly different shade of grey. What sort of options do we have for adding stuff to the background (ie, beneath the text) of the SIMILE timeline widget?

**Comment by bartvde** [comment]
I haven't seen any possibility to add something like this in the Simile demos, but I might have missed something.

**Comment by bartvde** [comment]
Okay, I had overlooked something, Simile decorators can be used to do this. I've implemented this in https://github.com/opengeo/gxp/commit/362b9eebec3ee5fd5a49e36a142c9a4fb0f823d4
