### ISSUE TITLE
Journal entries don't work

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1331]
Go to http://mapstory.org/journal, click "write an entry". Enter content. Journals don't publish.

**Comment by travislbrundage** [comment]
Should be fixed with commit https://github.com/MapStory/mapstory-geonode/commit/35211e3630b279e150726c81b1dc6bd26951f3a6

**Comment by jonpmarino** [comment]
@travislbrundage any way to get newest posts showing up top rather than at the end?

**Comment by travislbrundage** [comment]
I didn't realize they were still appearing at the bottom. Yeah, I will look into that.

**Comment by jonpmarino** [comment]
cool. thanks!

**Comment by jonpmarino** [comment]
@travislbrundage adding a couple of other picks on journals. If you think they are quick wins, feel free to knock out.
- [x] make username and thumbnail picture under journal entry title link to that users profile
- [ ] add ability to add keywords/tags to journal entries, and to sort by keyword/tag on left-hand column of journal page
- [x] Make most recently published entries appear at top/beginning of journal page
- [x] Allow comments to be made on journals

**Comment by travislbrundage** [comment]
Only that second one isn't a really quick pick, the rest will be fairly simple picks.

**Comment by jonpmarino** [comment]
@travislbrundage taking out the one on tags and making a separate issue for later...and closing.
