### ISSUE TITLE
BUG- Download schema links for append data fails for old stories

### ISSUE THREAD

**Issue by zrouse-Boundless** [MapStory/mapstory-meta#1332]
"it looks like some backend data issue for those layers in particular, somehow the links didn’t get generated correctly. I haven’t found another case of download schema links not working for any newly uploaded or recently created layers"

Example = http://mapstory.org/layers/geonode:Breweries0

@nittyjee has a list of layers too

**Comment by davisc** [comment]
`Before`
<img width="988" alt="before" src="https://cloud.githubusercontent.com/assets/947403/13192899/7c3fa40a-d736-11e5-8991-18ed2bdd7cdb.png">

`After`

<img width="1003" alt="after" src="https://cloud.githubusercontent.com/assets/947403/13192900/7c4ccef0-d736-11e5-883c-417abf756124.png">
