### ISSUE TITLE
Append Schema download changes

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1338]

**Comment by JWileczek** [comment]
Currently schema download adds columns that are automatically created upon import. Mainly date_xd, date_parsed for Big Date. GeoServer allows you to specify certain attributes to download with a GetFeature request as a whitelist, but doesn't allow you to Blacklist certain attributes. I've tried to include all attributes except the auto-generated ones and it works on layers with a small number of attributes, but times out on layers will a lot of attributes.
- [ ] Determine better way to exclude certain attributes on schema download.
- [ ] CSV schema may require additional columns to be excluded vs the shapefile format.
