### ISSUE TITLE
Legend and InfoBox masking

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1340]
In composer, user should have the ability to "mask" default text and create custom text for Chapter Legend and StoryLayer InfoBox.

(Chapter "Legend" is the drop-down of all Layers in a Chapter and their style summaries. "InfoBox" is the information that should pop-up when a user clicks a feature on the map)

Right now the Legend text and InfoBox text are direct transcripts of the text that is in the StoryLayer at the point of original upload. This text may not be appropriate for ever MapStory that uses the layer, and the storyteller should have the ability to customize.

Legend masking should happen at the Select Chapter level of multi-level push menu.

InfoBox Masking should happen at the level of style editing inside a single layer

**Comment by jonpmarino** [comment]
moving to March 4 milestone as part of #1318 - composer work

**Comment by milafrerichs** [comment]
Is it correct that the attributes for a layer can be found in `layer.get('metadata').schema`

I found it here: https://github.com/MapStory/MapLoom/blob/master/src/common/layers/LayersDirective.js#L136

can someone confirm? 
@davisc @Coop56 @JWileczek

**Comment by jonpmarino** [comment]
Confirmed basic functions work. A few clean-up tasks:
- [x] Masked Layer name does change legend, but it looks like original layer name still appears at the header of the InfoBox. Easiest solutions seems to be to remove appears of layer name in infobox altogether.
- [ ] on sidebar, resize functions so they fit properly
- [x] remove old "masking" options that aren't operable.
  ![grabmorning](https://cloud.githubusercontent.com/assets/2573761/14430413/865afd10-ffcf-11e5-9648-afceb63547ab.jpg)

**Comment by reynalddizon** [comment]
comment on Jon's first item. I think we should not remove the layer name from the infobox. The layer name is especially important if you have multiple layers loaded on the map and if you click on a stack of features, you would know from which layer the information is pulled from.

**Comment by jonpmarino** [comment]
@reynalddizon fine. Good point. @milafrerichs if making the StoryLayer name also update on the Infobox is a huge effort, then eliminate. If you can quickly make it happen, then follow Rey's lead. Either way, the most important thing is consistency. Can't have the old layer name appearing if the storyteller has masked it for the legend.

**Comment by jonpmarino** [comment]
@milafrerichs latest cleanup looks good. @reynalddizon probably need to figure out a css solution for getting the masking stuff to fit in that sidebar. Maybe the mask text box goes under the original Attribute title, and the check box next to it?
![grab12345](https://cloud.githubusercontent.com/assets/2573761/14447718/3e2af638-0030-11e6-83a4-b6d79c56ff7f.jpg)

**Comment by jonpmarino** [comment]
Closing this. the remainder of masing is addressed by #1447
