### ISSUE TITLE
User Notification Preferences

### ISSUE THREAD

**Issue by jj0hns0n** [MapStory/mapstory-meta#1344]
Give user ability to set notification preferences: Options are: Notify me immediately | Send me a Daily Summary | Send Me a Weekly Summary (choices = When my StoryLayer is edited, When someone comments on my work, when someone flags my work, when someone favorites my work.

(migrated from #1302)

**Comment by jj0hns0n** [comment]
@davis guess we can open other tickets for specific requirements on notifications. At this point, notifications are basically enabled, but we need to still do work to meet the requirements as specified here. I prefer small discrete tickets, so happy to just file new ones after discussing with @jonpmarino

**Comment by davisc** [comment]
@jj0hns0n yes opened #1404
