### ISSUE TITLE
Upload and Create StoryLayer modals should not show up unless user is logged in

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1345]
If a user is not logged in and clicks Upload StoryLayer from the homepage or header, or Create StoryLayer from the header, they should be brought to the login modal. This behavior is correctly implemented for the "Compose MapStory" links.

**Comment by davisc** [comment]
Since a modal pops up rather than a page redirect, I opted to hide the links if the user is not authenticated.

**Comment by Coop56** [comment]
I've solved this issue with this PR - https://github.com/MapStory/mapstory-geonode/pull/208

**Comment by Coop56** [comment]
@jonpmarino This is now fixed and on demo.  Please confirm and close when you have a moment, or let me know if you have any questions.

**Comment by jonpmarino** [comment]
Looks good! Closing...

**Comment by jonpmarino** [comment]
Only thing I notice is that the Upload StoryLayers link on homepage is now disabled if a user is logged.

**Comment by Coop56** [comment]
@jonpmarino That's fixed in this PR - https://github.com/MapStory/mapstory-geonode/pull/210

**Comment by jonpmarino** [comment]
Confirmed and closing.
