### ISSUE TITLE
City and Country not showing up on profile when added in "Edit Profile"

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1350]

**Comment by jj0hns0n** [comment]
Added at https://github.com/MapStory/mapstory-geonode/commit/5966bd99564053df9c5a943f084901717b543e0e ... Note that these are not clickable or searchable currently. This can be added later.

@jonpmarino please close when this is live and verified

**Comment by jonpmarino** [comment]
Confirmed on prod. "Clickable" location issue documented for later as #1357
