### ISSUE TITLE
add "write a message" to user actions section in Profile

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1352]
there is no place to launch a new message on Profile page right now. Easiest place seems to add "send a message" with link to message creator under the "user actions" section.

There is a send message link in the "Inbox" accessible on the top-right drop down. So this link just needs to be enabled on the profile itself.

![9999](https://cloud.githubusercontent.com/assets/2573761/13367495/0ceec7ae-dcb1-11e5-8e53-981538561e27.jpg)

**Comment by jj0hns0n** [comment]
Added with https://github.com/MapStory/mapstory-geonode/commit/84af075054adf5ce0d1df166170561d397d08242 ... @jonpmarino please close once verified

**Comment by jonpmarino** [comment]
tested and confirmed on prod
