### ISSUE TITLE
The first edit in a new geogig enabled layer should refer to the user's real name, not anonymous

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1354]
If Real Name is complete, user username.

On the Edit History on the layer detail page, the first edit should refer to User Real Name, not "unknown".

**Comment by Coop56** [comment]
We're currently unable to do this, as the initial upload is created by the server itself and not by a specific Author.  In a future version of Geogig, the ability to pass the Author as a username exists.  The geoserver geogig extension most likely won't be updated until the Geogig 1.0 release, which according to JD is most likely a month or so out.  We should be able to do this then.  @jonpmarino @davisc @reynalddizon
