### ISSUE TITLE
Names on edit history in a geogig enabled layer should link to the users' profiles

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1355]

**Comment by jonpmarino** [comment]
Related to general user interface issues listed in #1231

**Comment by Coop56** [comment]
Still not something we can do at this point - as we don't have access to their username during a commit which we need to link to their profile.

**Comment by jonpmarino** [comment]
understood. moving out of this milestone.

**Comment by emilyashley** [comment]
closed https://github.com/MapStory/mapstory-geonode/commit/4393d9e5c443150a068097b678cdfc3e99052dcd
