### ISSUE TITLE
Reset clean search when a selected field (tag, category) is de-selected

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1356]
When a filter item is deseleted, it should repopulate the content (StoryLayers and MapStories) that were eliminated by the previous filter.

**Comment by travislbrundage** [comment]
This is kind of intertwined with the explore issue #1194. It'll make more sense implementing Bootstrap tokenization, and then this functionality will fall into place more obviously. So, I'll be hitting two birds with one stone.
