### ISSUE TITLE
MapStory Viewer & Playback

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1359]
![viewer 001](https://cloud.githubusercontent.com/assets/4611843/13579452/a6eef498-e46b-11e5-8629-125549219ac2.jpeg)

(based on http://beta.mapstory.org/story/5842)
- [x] Clicking Title should link back to MapStory viewer page
- [x] Clicking author should link back to storyteller profile page
- [x] Add infinite scrolling to Chapter Info if it extends beyond the map height
- [x] Change vertical "chapter info" pop up to a collapsable sidebar (to mimic function in composer)
- [x] Add the MapStory title,  author, chapter number, chapter title and chapter summary in the collapsible sidebar.
- [x] We need an icon to exit the viewer (and return to the mapstory detail page), maybe place fa-sign-out on the left of the sidebar collapse button. 
- [x] Skip the part where it shows a featured image on the sidebar, chapter info doesnt include photos yet.
- [x] The circles at the bottom of the sidebar correspond to the number of chapters, for now, replace them with numbers instead of dots. 
- [x] not sure if you’re going to work on the playback toolbar and timeline as well, but for now, keep it as is. This is a completely different issue.

**Comment by jonpmarino** [comment]
@reynalddizon @milafrerichs what about changing the "By MapStoryteller_Name" to "A MapStory, by MapStoryteller_Name". Right now we don't indicate MapStory branding anywhere on playback. Making this small convention change to the byline would be a way to make it clear that the viewer is looking at a MapStory from MapStory.org.

**Comment by Coop56** [comment]
@milafrerichs How much work did you do to this?  Do you have it somewhere?  Or am I starting from scratch?

**Comment by Coop56** [comment]
This is done now and live on demo - @reynalddizon let me know if you want any styling changed.

**Comment by jonpmarino** [comment]
@Coop56 looks really good. Just tested with http://demo.mapstory.org/story/1046#/chapter/2. Realize you'll probably want to open a new issue with @reynalddizon to deal with final styling issues. Question - should this affect anything with the embed? Tried embedding into a journal article and am getting errors. Could be unrelated, http://demo.mapstory.org/journal.

**Comment by reynalddizon** [comment]
<img width="548" alt="screen shot 2016-05-31 at 2 28 14 pm" src="https://cloud.githubusercontent.com/assets/4611843/15685939/0417317c-273c-11e6-91fc-f14b27c08a36.png">
