### ISSUE TITLE
Profiles API queries are timing out (/api/profiles) on production

### ISSUE THREAD

**Issue by travislbrundage** [MapStory/mapstory-meta#1361]
For me I'm seeing my queries to the profiles API time out on production. (www.mapstory.org/api/profiles)

For others it seems to just take a long time, so I am guessing my connection is slightly worse and it is crossing a threshold for which it times out. I think with the sheer volume of users, a request has become somewhat expensive.

Is there a way to give a longer amount of time to process it before timing out, or is there something genuinely broken here? I haven't experienced the problem with any other parts of the api, even querying resourcebase objects.

**Comment by travislbrundage** [comment]
Might be fixed by changing to /api/owners instead of /api/profiles

Might also work to just use a lower value for `limit` when using /api/profiles/ in the search page (results in more pages to scroll through)

**Comment by jonpmarino** [comment]
fixed by @simod and @travislbrundage . confirmed storyteller search performance improvements on beta.
