### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1365]
- [x] Make sure user can open and minimize Legend.
- [x] Move the timestamp from the tooltip to the toolbar and make it more human-readable.
- [x] Playback Speed options in the toolbar (0.5x, normal, 2x, 4x, 8x)

**Comment by davisc** [comment]
@reynalddizon or @jonpmarino what is meant by 'more human readable'?

**Comment by reynalddizon** [comment]
timestamps like 2015-01-01'T'12:12:12 should be more like 01/01/2015 12:12:12 or Jan 01, 2015 12:12:12

**Comment by jonpmarino** [comment]
thanks rey. and, ideally time is always visible rather than scroll over on timeline. If possible, we could move it to the right, so it doesn't cover up the chapter info

**Comment by davisc** [comment]
![Uploading Screen Shot 2016-05-10 at 7.20.18 AM.png…]()
