### ISSUE TITLE
Chapters

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1366]
- [x] Add more lines for the chapter info summary.
- [x] Remove the Info word
- [x] Handle chapter transition gracefully.
- [x] Save chapter info should call "Save Draft" function. No need to display the "Save MapStory" modal.

**Comment by reynalddizon** [comment]
Question: What happens to the basemap display when the sidebar shows the Chapters list? What does it display?

**Comment by Coop56** [comment]
@reynalddizon Can you explain a bit more about what you're looking for when you say Handle chapter transition gracefully?

**Comment by Coop56** [comment]
@reynalddizon I'm not sure what you mean by handle chapter transition gracefully as clicking between chapters is instantaneous for me.  The other two items are complete as per my latest push @jonpmarino @davisc.  https://github.com/MapStory/MapLoom/commit/4e2fd936463a12e6691fc0f3f492399e63296442

**Comment by jonpmarino** [comment]
Maybe what is referred to in #1412?

**Comment by reynalddizon** [comment]
@Coop56 it's basically making sure that the right elements are being displayed depending on what chapter is active on the sidebar. I just tested beta and it looks like this one is okay now. so I'm checking this one off the list.

**Comment by Coop56** [comment]
@reynalddizon Great.  @jonpmarino @davisc Please review and close this issue.
