### ISSUE TITLE
Styling a StoryLayer

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1368]
- [x] Update the carousel with more comprehensive images (Rey)
- [x] Update the map features' style gracefully when moving from one style to another in the carousel.
- [x] Apply CSS rules for the styling interface shown in MapStoryOrg mockup
- [x] Add a color picker UI for color selection (in addition to hex text box)

**Comment by Coop56** [comment]
Styles don't work on new Composer right now, @davisc is working on a fix that should make them start working.  Once that's taken care of I'll handle these additional tasks.

**Comment by Coop56** [comment]
I added a dependency that should fix the edit layer styles color picker with my latest commit - https://github.com/MapStory/MapLoom/commit/d1e3175c8c38c40e64eb7e4a099ae63ccf8e50e7.  Once demo builds I'll see if it's working, in the meantime I'm moving onto a different issue.

**Comment by Coop56** [comment]
@reynalddizon Can you tell me a bit more about what you want for transitioning styles gracefully please?  I'm not 100% sure what you're looking for there.

**Comment by reynalddizon** [comment]
@Coop56 basically it's just a simple message on top of the basemap that says "Loading style..." which will appear when loading map tiles when a user chooses a new style, and will disappear when the loading is finished. This is very helpful when loading really big datasets. But with small datasets we can simply hide this feature.
<img width="856" alt="screen shot 2016-03-15 at 1 57 04 pm" src="https://cloud.githubusercontent.com/assets/4611843/13788442/26f8eef0-eab6-11e5-8d4a-618c3ef36eb8.png">
