### ISSUE TITLE
StoryBoxes

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1369]
- [x] Delete StoryBox description. No need for that.
- [x] Add a "Delete StoryBox" button in the StoryBox info sidebar panel.
- [x] Fix the error where you hit "Save StoryBox" in the edit StoryBox form, it generates a new storybox item on the list. (See example below, I tired updating the "hello" storybox 3 times by clicking Save 3 times, the list shows 3 extra list items between "hello" and "hello2" storyboxes.)
  <img width="318" alt="screen shot 2016-03-10 at 12 25 36 pm" src="https://cloud.githubusercontent.com/assets/4611843/13678161/4e049f48-e6bb-11e5-9a78-bfe9beb11a60.png">

**Comment by JWileczek** [comment]
Time picker improvements moved to separate issue.
#1413
