### ISSUE TITLE
Add save icon and call save function at any step in composer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1370]
- [x] Add save icon to the top of all menu sections.
- [x] Notify user when the Mapstory has been saved successfully.
- [x] Notify user when the Mapstory has failed to save.

**Comment by Coop56** [comment]
We want to add a Save button to the top of Composer as well on all sections of the Menu next to the collapse icon.  @reynalddizon Which icon would you like to use?

**Comment by Coop56** [comment]
@reynalddizon @jonpmarino What sort of notification would you like to see in Composer to let the user know that the Mapstory has been successfully saved?

**Comment by Coop56** [comment]
Added the save icon to all menu sections.  https://github.com/MapStory/MapLoom/commit/55309598fa51f482b5dd10e6394abc12bb0a9fdf

**Comment by reynalddizon** [comment]
@Coop56 Just a simple dismissible modal:
<img width="547" alt="screen shot 2016-03-15 at 10 48 03 am" src="https://cloud.githubusercontent.com/assets/4611843/13781940/7ae4dcb0-ea9b-11e5-9406-2cf3ee39c0e7.png">

**Comment by Coop56** [comment]
I just sent in a commit - https://github.com/MapStory/MapLoom/commit/afd3cc06e3ad758890a6983947423ee72ceba557 - that handles the success and failure notifications for users.  That should close this issue.  @jonpmarino @reynalddizon Feel free to take a look when this goes live on demo.  @davisc When you get a chance please check and close this issue.

**Comment by milafrerichs** [comment]
what about a message when a layer is added via search? right now it does all the stuff in the background and nothing is happening and suddenly the layer is there.

**Comment by Coop56** [comment]
@milafrerichs This issue is about saving specifically but yes we should have some notifications and loading bars for adding layers.  @reynalddizon @jonpmarino or @davisc if you want to set that up in another issue I can take care of that.

**Comment by jonpmarino** [comment]
@milafrerichs good observation. I believe this is what #1373 is trying to speak to. On the old maploom, when a layer was added, the title immediately appeared in the side bar, and there was a spinning circle to indicate processes were occuring to get the layer added. Something similar for our composer seems vital. @reynalddizon @davisc @Coop56

**Comment by Coop56** [comment]
I can use the same alert setup I used for the save success and failure for this, I'll just setup a function to showAlertBox with whatever text is necessary (in this case something like StoryLayer Loading...) and then another function hideAlertBox to hide it when the layer successfully loads.

**Comment by Coop56** [comment]
I've pushed up changes with a new notification system, Toastr, that closes this issue.  Once it's deployed to demo that should close this issue if you'd like to check it out @jonpmarino and @reynalddizon.

**Comment by jonpmarino** [comment]
good stuff! ping when its deployed to demo

**Comment by Coop56** [comment]
This one is already on demo - we should be able to close this out now.
