### ISSUE TITLE
Default styles for storylayers

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1371]
- [ ] For points, simple style, circle, with orange fill #f59620, no border and no labels.
- [ ] For lines, simple style with orange stroke #f59620, solid and no labels.
- [ ] For polygons, simple style with solid orange stroke #f59620, solid orange fill #f59620 with 70% transparency, no labels.
- [ ] Apply #f59620 to geoserver default style
- [ ] layers are displayed with varying styles. currently, styles update to the default only when the styling interface is loaded. we want to keep them all uniform pre-composing. 
- [ ] StoryLayer detail page should only show this orange style as a check that these default styles are implemented.

**Comment by davisc** [comment]
<img width="1045" alt="default-style" src="https://cloud.githubusercontent.com/assets/947403/13860024/56d23470-ec54-11e5-9d46-3741fc195efa.png">

@reynalddizon and @jonpmarino this has been deployed to demo.mapstory.org requesting feedback to close this issue.

**Comment by jonpmarino** [comment]
@davisc confirmed on demo. Looks good! We should apply same default to layer playback in explore, if the layer isn't uploaded with its own preferred style in uploader. Can either edit this issue or create a new one for that.

**Comment by reynalddizon** [comment]
does the current uploader recognize the style file (sld)?
