### ISSUE TITLE
Composer CSS

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1372]
- [x] apply the CSS rules to the sidebar elements as depicted on composer 2 mockup
- [x] update the CSS rules for the Styling Interface as depicted on MapStoryOrg composer mockup.

**Comment by Coop56** [comment]
Just sent a commit to demo that should match the CSS rules from the Composer 2 mockup, starting on the styling interface next.

**Comment by Coop56** [comment]
This is done as far as it can be done using CSS rules.  In order to mimic that exact look we'd have to modify the storytools vendor files to modify the HTML template of the edit styles.  I imagine this can be done but I'm not sure if it's worth the time.  That's up to you guys - so just let me know.  @davisc @reynalddizon @jonpmarino - otherwise this issue is completed and closed.

**Comment by davisc** [comment]
@Coop56 Looks good to me. I support calling this task done.

**Comment by jonpmarino** [comment]
I defer to @reynalddizon but agreed from what i see

**Comment by Coop56** [comment]
So is this closed then @reynalddizon?

**Comment by reynalddizon** [comment]
my latest version still has the old font face, Helvetica. I inspected the element and the css rules show "Open Sans" but if you compare the text on the top toolbar (which are Open Sans texts) and the ones in the sidebar, they look different.

**Comment by reynalddizon** [comment]
The styling interface looks fine now.

**Comment by Coop56** [comment]
@reynalddizon It looks like something was using an !important tag and overriding my font.  I pushed up a change to the CSS file that should fix this on demo once automated builds resume.

**Comment by Coop56** [comment]
I tested the fonts locally and they are all showing Open Sans now, this issue should be closed out as soon as demo is back up and @reynalddizon can verify that the font is displaying properly.  @davisc please close it out when you get a moment.
