### ISSUE TITLE
Adding StoryLayers

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1373]
- [x] Add a progress bar to show if a layer is being loaded. (Would be very helpful especially when loading really large datasets)
- [x]  Display an error message if the composer fails to add the layer. (if possible, state the reason why it failed.)

**Comment by Coop56** [comment]
I just pushed up some changes in my latest commit - https://github.com/MapStory/MapLoom/commit/a36a6539e87878b47151ea6b061ad855bcf35247 - this commit creates notifications for adding layers as well.  When you click Use to add a layer, a notification will pop that lets the user the layer is loading.  That notification will remain until the layer either saves or fails and is replaced by a success or failure notification which will fade in a few seconds.

**Comment by jonpmarino** [comment]
confirmed on demo. Nice!
