### ISSUE TITLE
Help Texts and Tooltips

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1374]
- [ ] Display help text/link (small question mark) in each section of the sidebar (and accordions) which links to a wiki page.
- [ ] Display a tooltip for every form element in the sidebar.

_will write the list of items that needs tooltips and help text soon_

**Comment by Coop56** [comment]
@reynalddizon As soon as you have these ready I'll get them implemented.

**Comment by reynalddizon** [comment]
[help text.pptx](https://github.com/MapStory/mapstory/files/224397/help.text.pptx)

@jonpmarino @Coop56 here's the mockup for the help texts/links and tooltips for the composer. Jon, take a look and edit the text in the popups so Jeremiah can implement this when it's ready.

**Comment by reynalddizon** [comment]
<img width="779" alt="screen shot 2016-04-18 at 2 13 06 pm" src="https://cloud.githubusercontent.com/assets/4611843/14614557/b5f4f7e2-056f-11e6-9845-6fd7ecfaf9ce.png">

for some reason the question mark icon didn't appear correctly. it's fa-question-circle

**Comment by reynalddizon** [comment]
[tooltips_JM.pptx](https://github.com/MapStory/mapstory/files/226257/tooltips_JM.pptx)

@Coop56  Here's the mockup with Jon's edits. Lets discuss the details of this after the standup today

**Comment by Coop56** [comment]
@davisc Check out the powerpoint above this comment, slide 10, how would I add those tooltips?  All of that code is generated outside of Composer, in StoryTools I believe?

**Comment by Coop56** [comment]
@jonpmarino @reynalddizon On some of these slides you have words on the bottom of the sidebar - I need to know where each of these are supposed to link to.

**Comment by Coop56** [comment]
@jonpmarino @reynalddizon We also need tooltips written for the new icons at the top of every section of the Composer sidebar.

**Comment by jonpmarino** [comment]
@Coop56 @davisc we can leave off the tooltips for now that can't be implemented easily (storytools specific ones you mentioned). not a top priority.

@Coop56 here's links for the bottom ones:

StoryBoxes Help - http://wiki.mapstory.org/wiki/MapStory_Composer#Configuring_StoryBoxes
StoryLayers - http://wiki.mapstory.org/wiki/MapStory_Composer#Adding_StoryLayers
StoryPins Help - http://wiki.mapstory.org/wiki/MapStory_Composer#Adding_StoryPins
Styling Help - http://wiki.mapstory.org/wiki/MapStory_Composer#Styles
Editing Help - http://wiki.mapstory.org/wiki/Versioned_Editing
History Help - http://wiki.mapstory.org/wiki/Versioned_Editing
Masking Help - http://wiki.mapstory.org/wiki/MapStory_Composer

**Comment by reynalddizon** [comment]
(1) fa-save - Save Draft
(2) fa-publish - Publish MapStory
(3) fa-tags - MapStory Properties
(4) fa-play - Preview MapStory

**Comment by Coop56** [comment]
Tooltips have been pushed - just need to finish up the extra help links now @jonpmarino

**Comment by Coop56** [comment]
Help text has been pushed up now as well.  You should be able to confirm and close this one out @jonpmarino.

**Comment by jonpmarino** [comment]
confirmed and closing.
