### ISSUE TITLE
Trending Tags - Improve API to order by count rather than sorting client side

### ISSUE THREAD

**Issue by travislbrundage** [MapStory/mapstory-meta#1375]
So after some discussion with Simone, our concept of trending tags is not straightforward to implement in the API (though it is of course possible).

"You would have to subclass tags, use it in the Geonode model, write logic to sync the counts on them and modify the API."

For now I've implemented it in the front end. So, I grab all keywords through an api request to /api/keywords, then sort them by count and use the top 8 for our "trending tags". It's probably fine for now, but this solution will get quite expensive over time as users add more tags. Modifying the API is the scalable solution.

**Comment by emilyashley** [comment]
Note: this refers to [here](https://github.com/MapStory/mapstory-geonode/blob/master/mapstory/static/mapstory/js/search.js#L261). It sorts all the tags, whether there are a few, a few hundred, or a few thousand to grab the top 8 for display.
