### ISSUE TITLE
Composer 0.0 StoryPins

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1381]
- [x] Add the StoryBox component on Level 1 sidebar (with a counter)
- [x]  Level 2 StoryBoxes: a working “Add a new storypin” button which calls the “Add a new StoryPin” Level 3 Form.
- [x]  Pin Location button should capture the coordinates of the pin: Lat and Long
- [x]  A working pair of text input boxes for the time frame. An error message/alert should be displayed if the end time occurs before the start time.
- [x]  A working save button to update the Storybox details.
- [x] List down the added StoryPins on Level2-StoryPin
- [x] Once saved, StoryPin should be clickable with a pop-up window
- [x] StoryPin should support media pulled from external links (video, images)
- [ ] Storyteller should be able to set storypin playback behavior to "require user click" or "play automatically during set time range". Play automatically during set time rage should cause the storylayer time control to pause if the media has animation in it (like a video or audio content)
- [x] Eliminate text "drop pin on the map to set pin location". Instead change text on button that says "Save Pin Location" to "Add StoryPin to the Map"
  ![storypinside](https://cloud.githubusercontent.com/assets/2573761/13891577/5955cb92-ed28-11e5-9343-be47ffac95bc.jpg)

**Comment by JWileczek** [comment]
Calling this closed as we are waiting on the pause portion of this.
