### ISSUE TITLE
Composer 0.0 Editing Features

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1382]
- [x]  Added storylayers should appear on the map panel.
- [x] “Add a feature” button should trigger sidebar collapse and launch the editing mode,
- [x] “Edit an existing feature” button should trigger sidebar collapse and display a help text on the map panel.
- [x] “View Layer Metadata” should launch the Layer Metadata modal. Modal should be dismissible.
- [x] Change "Layer Metadata" button to "View StoryLayer details". Hitting button spawns StoryLayer Detail page in new browser tab.
- [x] “View Attribute Table” should launch the Attribute Table modal with simplified search and pagination. 
- [x]  The attribute table should have a Toggle Edit button for editing entries.
- [x] “Delete Layer” button should launch a dialog prompt to confirm deletion.
- [x] View History

**Comment by Coop56** [comment]
@JWileczek is working on a basic implementation of the View History section and from there I'll be styling it to fit with our sidebar.

@davisc and @JWileczek did you guys talk about the metadata field editing?  Last I heard we needed to figure out which fields the user should be able to and should not be able to edit.

**Comment by Coop56** [comment]
@davisc @jonpmarino @reynalddizon This ticket should be completed.  @JWileczek pushed up the code for View History and I just finished off the View StoryLayer Details setup for now.  There may be some additional frontend work I need to do on View History but until this code is on Beta I can't really test it, as local box layers do not have history on them.

**Comment by jonpmarino** [comment]
Re-opening until "View History" is complete

**Comment by Coop56** [comment]
@JWileczek What's the status of View History?  Last time we spoke about it you were working on getting it to display and I was going to take it from them and finish the frontend styling based on @reynalddizon's mockup.  Is this code already live and ready for me somewhere?
