### ISSUE TITLE
Implement "What's Hot" / Leadership Search in Search

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1384]
- [ ] Implement administrative filters in content and user search, as indicated in mockup

**Comment by Coop56** [comment]
@jonpmarino @reynalddizon Where is this mockup?  Can you explain a bit more what you're looking for here?

**Comment by reynalddizon** [comment]
@Coop56 I didn't realize that this issue is already ticketed. I'll close this one and move everything to https://github.com/MapStory/mapstory/issues/1598. there's a mockup there
