### ISSUE TITLE
Apply legend and infobox masking within viewer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1386]
Legend and Infobox masking applied in composer should persist to what a viewer sees on playback. So, the Legend drop-down should so the storylayer alias's created in composer, and clicking on features should so the masked feature names that user has created.

**Comment by davisc** [comment]
http://demo.mapstory.org/story/365 Layer title masked with 'Walmart Stores'

**Comment by davisc** [comment]
<img width="1351" alt="screen shot 2016-04-12 at 7 52 29 pm" src="https://cloud.githubusercontent.com/assets/947403/14479825/2c4e6270-00e8-11e6-862f-dc945c3d34dc.png">

Timeline also displays masked value for Layer Title. Custom style applied to the layer as well.

**Comment by jonpmarino** [comment]
outstanding!
