### ISSUE TITLE
Add search to favorites API

### ISSUE THREAD

**Issue by jj0hns0n** [MapStory/mapstory-meta#1387]
From #1362

**Comment by davisc** [comment]
content_type ids may differ in deployment environments so the favorites api should allow query by type ie layer, map, etc.

**Comment by jj0hns0n** [comment]
@davisc not sure this has been implemented??

**Comment by jonpmarino** [comment]
@jj0hns0n this is done, no?

**Comment by jj0hns0n** [comment]
@simod added this. Will let him confirm and close.

**Comment by simod** [comment]
yup, but can't close

**Comment by jonpmarino** [comment]
thanks guys
