### ISSUE TITLE
Improve guidance on format of time fields

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory-meta#1388]
Current workflow provides no convenient way to find out how time fields need to be specified in the input data - is a string "2001-01-01" OK? What about an integer 2005 ?

**Comment by ChristopherTucker** [comment]
Rob,

We need to get you a solid answer on this.  The best I can say is that our
uploader maps dates in to ISO8601 format.  The old uploader had a variety
of date handling routines that took less than perfectly formatted dates,
and asked the user "did you mean..." type questions.

This of course leaves open a variety of issues, such as, if we only have a
year date (like 32 BC.) what do you do with the month, date, hour, minute
and second fields.

Right now, we are putting the finishing touches for our new uploader...and
by "finishing touches" we mean that which we will build upon over the
coming months.

Chris

On Tue, Mar 15, 2016 at 6:18 PM, rob-metalinkage notifications@github.com
wrote:

> Current workflow provides no convenient way to find out how time fields
> need to be specified in the input data - is a string "2001-01-01" OK? What
> about an integer 2005 ?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/MapStory/mapstory/issues/1388

## 

Chris
703-981-9373

**Comment by rob-metalinkage** [comment]
OK - I'll just try to stay tuned - this will be important as I work up the specs for the temporal behaviour of the gazetteer.

**Comment by glynnis** [comment]
Closing this. If this is still relevant (especially re: Composer redesign), please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.
