### ISSUE TITLE
Explore UI issues

### ISSUE THREAD

**Issue by travislbrundage** [MapStory/mapstory-meta#1391]
- [ ] Long titles overflow on the Explore page. Truncating and showing the full title on rollover is probably the best option.
  Test URL: http://mapstory.org/search/?q=Test&limit=100&offset=0&is_published
  Image:
  <img width="916" alt="screen shot 2015-10-16 at 2 09 21 pm" src="https://cloud.githubusercontent.com/assets/1622331/10699851/6a0aa830-797f-11e5-88dd-e0ae3ae2c882.png">
- [ ] Explore page shows "page 1 of NaN” before loading is complete
  Test URL: http://mapstory.org/search/?limit=100&offset=0&is_published
- [ ] Two different scrolling methods are used for the whole Explore page and the available StoryLayers. Maybe merge into one and consider infinite scrolling? This is a small point.
  Test URL: http://mapstory.org/search/?limit=100&offset=0&is_published

**Comment by jonpmarino** [comment]
Closing due to repeat of #1401
