### ISSUE TITLE
Fix Profile Avatars on Search page

### ISSUE THREAD

**Issue by travislbrundage** [MapStory/mapstory-meta#1393]
The problem with avatars on the search page is because the way the elastic search is indexing the user avatars.

In people's `search_indexes.py`

```
    def prepare_avatar_100(self, obj):
        avatar = obj.avatar_set.first()
        if avatar:
            return avatar.avatar_url(100)
        return ''
```

This is simply grabbing the first avatar the user uploaded, not the avatar that they have set. Since a user can upload multiple avatars, it's not accurate.

There's two solutions possible. First, fix the above code to grab the user's selected avatar. I'm not sure this is possible with the current app.

The other solution is to redesign the avatar app. It would probably be more intuitive to have only one avatar, so don't allow them to upload multiple options, but just replace the old one.

**Comment by travislbrundage** [comment]
Is this still an issue? I'm no longer able to reproduce this issue. I think it has been fixed.

**Comment by jonpmarino** [comment]
Appears fixed on prod. closing for now.
