### ISSUE TITLE
Composer Save Notifications

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1399]
- [x] In StoryBoxes, clicking "Update Map Bounds" results in notification "Your StoryBox Bounds have been saved"
- [x] In StoryPins, clucking "Save StoryPins" results in a notification "Your StoryPins have been saved"
- [x] In "Edit StoryLayer", clicking "Edit an Existing feature" should generate a notification that says "To edit an existing feature, just click on a feature that you want to edit"

**Comment by Coop56** [comment]
@jonpmarino This is done.  Commit is at https://github.com/MapStory/MapLoom/commit/d8f40f41571758088505e51e34e796373f1f410f.
