### ISSUE TITLE
Composer Basemap Bug Fixes

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory-meta#1402]
- [x] Fix layerList bug where 2 baseMaps still show up as layers.
- [x] Fix dropdown menu bug where it does not have the default baseMap automatically selected.

**Comment by jonpmarino** [comment]
Adding a layer seems to add it to the basemap drop down
![0909](https://cloud.githubusercontent.com/assets/2573761/13994336/ae57ff54-f0fa-11e5-83e6-18e6725022cd.jpg)

**Comment by davisc** [comment]
<img width="1146" alt="screen shot 2016-03-29 at 5 24 12 am" src="https://cloud.githubusercontent.com/assets/947403/14105010/8aae7f74-f56e-11e5-9a0c-ca6d25803a58.png">

**Comment by jonpmarino** [comment]
Also need to get OSM back in there based on @milafrerichs work, #1336
