### ISSUE TITLE
Add "Notification Settings" to user profile

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1404]
#1344 is complete. Need to add place in Edit Profile for user to manage notification settings. The checklist of notification options should appear in the "Edit Profile" form at the end after Volunteer Technical Community?.

See demo.mapstory.org/notifications/settings for options.

Here are the notifications a user should be able to set to on or off:
- [ ] StoryLayer Favorited
- [ ] StoryLayer Commented on
- [ ] StoryLayer Flagged
- [ ] StoryLayer Rated
- [ ] MapStory Favorited
- [ ] MapStory Commented on
- [ ] MapStory Flagged
- [ ] MapStory Rated
- [ ] Message received
- [ ] StoryLayer downloaded by another user
- [ ] Your StoryLayer was used in someone else's MapStory
- [ ] Your MapStory was featured on MapStory.org homepage
- [ ] Your Journal Article was commented on
- [ ] Your Password was updated successfully
- [ ] Your StoryLayer was added to a Community Initiative
- [ ] Your MapStory was added to a Community Initiative
- [ ] You were added to an Organization Page

**Comment by jj0hns0n** [comment]
Note the settings are here http://demo.mapstory.org/notifications/settings/
... need to be hooked up in the profile or in the user dropdown menu.

**Comment by jonpmarino** [comment]
Confirmed on demo and beta. closing. looks great! thanks @simod
