### ISSUE TITLE
Composer Font Issues

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory-meta#1406]
For some reason we're still not seeing the right font all the time in Composer.  I've applied the font Open Sans to everything in the Sidebar, which is the same font that is used in the header menu and I've seen it look right a few times, but the majority of the time the font is not correct.  The strange part is that if you inspect the font using Dev Tools it tells you that it's Open Sans, but if you compare it side by side with Open Sans you can see that it's slightly off.

**Comment by reynalddizon** [comment]
The Open Sans font finally decided to show up in the composer.

**Comment by jonpmarino** [comment]
nice of you to join us, Open Sans.
