### ISSUE TITLE
Add UserSnap feedback widget to beta

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1407]
UserSnap is a simple feedback widget that lets test users draw and make comments directly on a website, and log them for the project team. Integration to github and slack lets us build a pipeline from user testing to developer ticketing. This will help us manage the Rapid Feedback Team and other users that begin to test beta in coming weeks.
![grab00](https://cloud.githubusercontent.com/assets/2573761/13968895/b79b6b78-f055-11e5-9162-01423b60233b.jpg)

It can be incorporated into beta.mapstory.org by copy/pasting a snippet of code, as the screenshot indicates:

**Comment by Coop56** [comment]
@jonpmarino I sent in a pull request for this based on @davisc 's feedback.  I think it should be good to go.

**Comment by Coop56** [comment]
Showed this on the meeting today - this issue can be closed.  @davisc @jonpmarino
