### ISSUE TITLE
Allow storyteller to re-arrange Chapter order in composer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1410]
Currently a storyteller can create new chapters sequentially in composer. Once created, chapters should be able to be click and dragged to different spots in the chapter order (i.e. chapter 2 can be moved to sit after chapter 3, making it chapter 4).

**Comment by Coop56** [comment]
@davisc @jonpmarino @reynalddizon This is now done.  You can move chapters around while maintaining all of their content and the Chapter number updates accordingly.  The new order is being saved on both the frontend and backend.

**Comment by jonpmarino** [comment]
score!

**Comment by jonpmarino** [comment]
confirmed on demo. closing.
