### ISSUE TITLE
Map zoom remains at previous level when switching chapters in composer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1412]
When a storyteller switches from one chapter to another, the map zoom remains in the previous zoom location it was set to by the storyteller, rather than defaulting back to a starting saved zoom level for a chapter. Saving a chapter should save a default starting zoom level for that chapter. Switching from chapter to chapter in composer should switch the map view to the default starting zoom level for the chapter. Ideal default zoom level is probably the zoom extent of the largest storylayer in the chapter, or the zoom level of the first storybox in the chapter.

**Comment by JWileczek** [comment]
This should be complete. The map will zoom to the storyLayer with the largest extent if one is available, or world zoom if none is available on chapter switch.

**Comment by jonpmarino** [comment]
Just confirmed on demo. Looks great!
