### ISSUE TITLE
Download request throws error

### ISSUE THREAD

**Issue by rob-metalinkage** [MapStory/mapstory-meta#1417]
Tried to request download of data from
http://mapstory.org/layers/geonode:DenverAnnexations (Am logged in as user "roba")

throws:

"Error!

Permission to download the resource could not be requested to resource owner because of an error."

**Comment by JWileczek** [comment]
I tested this on both my account: jwileczek, and on admin. Experienced no such error. Closing unless someone else can reproduce.

**Comment by rob-metalinkage** [comment]
well - download is not longer offered on this story layer - so cant tell.
Can you post a link to a dataset that does have a working download so I can
check to see if it works.
