### ISSUE TITLE
trigger pause on playback when editing storylayer features 

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1418]

**Comment by JWileczek** [comment]
@reynalddizon @jonpmarino Playback should now pause when you go to edit, add, or switch chapters.

**Comment by reynalddizon** [comment]
@JWileczek does the playback also pause when you click on a feature (get feature info)?

**Comment by JWileczek** [comment]
@reynalddizon currently no but I can make that happen as well if you would like

**Comment by reynalddizon** [comment]
@jonpmarino do we want users to interact with the map (get feature info) while the mapstory is playing?

**Comment by ChristopherTucker** [comment]
I am fine with that.  But, users will quickly realize that the feature that they want info on might just disappear on them unless they hit pause.

Chris
703-981-9373

**Comment by jonpmarino** [comment]
@JWileczek said that was a quick change so I'm fine with it @reynalddizon .

**Comment by JWileczek** [comment]
This should be done if someone could confirm and close.

**Comment by reynalddizon** [comment]
this one's working fine. closing this.
