### ISSUE TITLE
Add before and after "dif" in edit history

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1420]
Maploom edit history had a div icon on edits that showed the before and after of the change. Need to re-incorporate

**Comment by zrouse-Boundless** [comment]
example from maploom
![image](https://cloud.githubusercontent.com/assets/11614809/14182775/8245a43c-f732-11e5-954a-5da138c595c6.png)

**Comment by reynalddizon** [comment]
[view_history.pdf](https://github.com/MapStory/mapstory/files/198054/view_history.pdf)

**Comment by jonpmarino** [comment]
gracias.

**Comment by jonpmarino** [comment]
good stuff. @reynalddizon will edit css on this pop-up to look more like mapstory

**Comment by Coop56** [comment]
Yep this is done other than styling and any bug fixing.  I'll work with @reynalddizon to implement the CSS.

**Comment by jonpmarino** [comment]
looks good!

![dif](https://cloud.githubusercontent.com/assets/2573761/14476840/2e3ebd06-00d8-11e6-9223-0134486db822.jpg)

**Comment by jonpmarino** [comment]
Can this be closed? looks good on demo. @reynalddizon ?

**Comment by Coop56** [comment]
Pretty sure this issue should be closed.  @jonpmarino @reynalddizon

**Comment by jonpmarino** [comment]
confirmed and closing.
