### ISSUE TITLE
replace MapStory header with Rey's composer header

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1428]
- [ ] Leaving composer while in a live mapstory project prompts a modal: "Before you leave composer, make sure you've saved your work as a draft"

<img width="1280" alt="screen shot 2016-04-06 at 4 34 50 pm" src="https://cloud.githubusercontent.com/assets/4611843/14333704/b020115c-fc15-11e5-8e92-871edbec50b2.png">

-->

<img width="1280" alt="header condensed" src="https://cloud.githubusercontent.com/assets/4611843/14646049/0ea3de10-0626-11e6-86db-fca2a797cddc.png">

close-up:
![0](https://cloud.githubusercontent.com/assets/4611843/14646121/5757d0e4-0626-11e6-85af-ad7c48eedb61.png)
![header](https://cloud.githubusercontent.com/assets/4611843/14646122/575ac52e-0626-11e6-8bae-4bc2d006295c.png)

and the navigation menus can be found in the dropdown next to the logo:
![nav_menus](https://cloud.githubusercontent.com/assets/4611843/14646127/5bf276b8-0626-11e6-8e1e-dec10e37a525.png)

**Comment by jonpmarino** [comment]
this is important, since if a user in composer clicks anything in the header (such as quick search) they will be taken out of their mapstory project.

**Comment by jonpmarino** [comment]
can be closed. yeah!
