### ISSUE TITLE
Password re-set not persisting

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1430]
There are 2 ways to reset password: from the Login modal, and from edit profile>reset password. When user resets password, the notification says that password is reset, but logging in again fails.

**Comment by davisc** [comment]
@jonpmarino is this still an issue? I was able successfully reset my password.

**Comment by jonpmarino** [comment]
I have confirmed working for me too. Am closing until/unless another user raises the issue.

**Comment by jonpmarino** [comment]
this is still an issue. @simod reproduced. I did too on new jondoe user account

**Comment by jonpmarino** [comment]
notification of reset is coming to email, but new password doesn't work.
![grabpasswordresetnotice](https://cloud.githubusercontent.com/assets/2573761/14544321/7d7f37da-0266-11e6-8741-a0938d20a277.jpg)

**Comment by simod** [comment]
this works for me on demo but not on beta. and it works in dev mode

**Comment by jonpmarino** [comment]
I tested password change on beta at 6:30pm and it worked. closing unless someone else reports.

**Comment by davisc** [comment]
@jonpmarino can you test this in prod?

**Comment by jonpmarino** [comment]
Just tested with Account AlexanderHamilton. Changed password is persisting.
