### ISSUE TITLE
MapStory continuous playback

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1432]
Add a button on side bar that enables chapters to transition without user click (similar to the 'continuous playback' button we had on storylayers). This will enable a mapstory to play all the through without requiring user click to advance.

**Comment by davisc** [comment]
<img width="1039" alt="screen shot 2016-05-10 at 7 20 18 am" src="https://cloud.githubusercontent.com/assets/947403/15146205/b28f6db4-167f-11e6-9dfa-e2b3b6664cc7.png">
