### ISSUE TITLE
Storylayer panel cosmetic changes

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1433]
![layer tab](https://cloud.githubusercontent.com/assets/4611843/14436518/0e90aa7a-ffeb-11e5-92a5-172f5d4e119e.png)

-remove the style, edit and inbox tabs

**Comment by Coop56** [comment]
The changes for this are all on demo now and working as intended.  This issue can be closed.  @reynalddizon @jonpmarino
