### ISSUE TITLE
Interpolate error when saving StoryPins

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1439]
Attempted to save StoryPin added to map. Received this error
![storypin error](https://cloud.githubusercontent.com/assets/2573761/14444745/92ec939a-0015-11e6-8c36-aa09b592761b.jpg)

**Comment by JWileczek** [comment]
@jonpmarino Can this closed should be fixed.

**Comment by jonpmarino** [comment]
Yup, no longer getting this error.
