### ISSUE TITLE
unselected layer keeps showing up

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#144]
1. go to: http://mapstory.dev.opengeo.org/maps/22/view
   the second layer is showing up as pink tiles
2. unselect the second layer in the layer tree. do not delete it. 
3. press play

i expect the mapstory to play without the second layer appearing. however the second layer continues to appear at each frame.

**Comment by mpriour** [comment]
That is my fault.
I was trying to make layers which were previously out of the current time
range turn on when they are in the current time range, but I need a flag to
not auto enable/disable if the user has actually interacted with the layer
and turned it off.

On Wed, Jan 25, 2012 at 12:58 PM, alyssa wright <
reply@reply.github.com

> wrote:
> 1. go to: http://mapstory.dev.opengeo.org/maps/22/view
>    the second layer is showing up as pink tiles
> 2. unselect the second layer in the layer tree. do not delete it.
> 3. press play
> 
> i expect the mapstory to play without the second layer appearing. however
> the second layer continues to appear at each frame.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/opengeo/mapstory/issues/144

## 

Matt Priour
OpenGeo - http://opengeo.org/
Expert service straight from the developers

**Comment by mpriour** [comment]
closed as duplicate to #293. Keeping higher numbered ticket so that it stays on very near term radar.
