### ISSUE TITLE
New user profiles not appearing in search

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1440]
- [X] Advancing pages doesn't advances storytellers. (can we just do infinite scrolling?)
- [X] search doesn't seem to find any users
- [X] new user profiles don't seem to appear

![slack-imgs com](https://cloud.githubusercontent.com/assets/2573761/14445927/187bfa4c-001f-11e6-9d7a-1720162418fc.jpeg)

On beta, new user profiles created don't populate in the search

**Comment by travislbrundage** [comment]
Blocked by https://github.com/MapStory/mapstory/issues/1361

Curious if this issue even will persist once it is resolved since I do not run into the problem on demo.

**Comment by jonpmarino** [comment]
No longer experiencing this bug on beta. Confirmed with @travislbrundage
