### ISSUE TITLE
After I delete a StoryLayer, it still shows up on sidebar

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1442]
Deleted storylayer from project. Still shows up in the sidebar, although data has been removed.
![grabdelete](https://cloud.githubusercontent.com/assets/2573761/14466595/79591d6e-00a5-11e6-9550-b21f2eafb831.jpg)

**Comment by jonpmarino** [comment]
I think @JWileczek fixed this. Correct?

**Comment by Coop56** [comment]
Yep this can be closed.
