### ISSUE TITLE
StoryLayers showing up in the MapStory explore filter

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1444]
Filter for MapStories. StoryLayers appear.

![grabexplore](https://cloud.githubusercontent.com/assets/2573761/14546308/a96b5f3e-0272-11e6-976b-2e8ec5440e41.jpg)

**Comment by travislbrundage** [comment]
Requires an update from geonode, but fixed on the mapstory-geonode side

**Comment by travislbrundage** [comment]
Closed by [PR#31](https://github.com/MapStory/geonode/pull/31) and [PR#213](https://github.com/MapStory/mapstory-geonode/pull/213)
