### ISSUE TITLE
Change "Delete this StoryLayer" to "Remove this StoryLayer" in composer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1445]
Wherever we say 'delete this storylayer', it would be better to say 'remove this storylayer' in composer. "Delete" makes the user feel like they might actually be deleting a StoryLayer, rather than just removing it from a mapstory project. Low priority.
![grab456](https://cloud.githubusercontent.com/assets/2573761/14468911/09b1f35e-00b0-11e6-8eca-b1353c740d27.jpg)

**Comment by Coop56** [comment]
While I was already changing everything inside the StoryLayers section for Issue #1433 I went ahead and did this at the same time.  This issue can be closed @jonpmarino

**Comment by jonpmarino** [comment]
confirmed and closing!
