### ISSUE TITLE
Masking panel cosmetic changes

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1447]
replace the Customize Info box table with this:

<img width="274" alt="screen shot 2016-04-12 at 3 57 58 pm" src="https://cloud.githubusercontent.com/assets/4611843/14474350/84fb1594-00ca-11e6-80c4-6140540b7a41.png">

**Comment by Coop56** [comment]
This issue is done and can be closed now.  @jonpmarino @reynalddizon
