### ISSUE TITLE
Layer Edit commits list cosmetic changes

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1448]
remove the block buttons and replace the list with this:

<img width="412" alt="screen shot 2016-04-12 at 3 52 55 pm" src="https://cloud.githubusercontent.com/assets/4611843/14474381/b6028618-00ca-11e6-9416-e4b6a22abde4.png">

Border-left: green for adds, yellow for modifications and red for removes.
Name is the author name <a> tag to user's profile.

Icons:
fa-globe for View on Map
fa-user for View Author's Profile
fa-exchange for Show Details/Diff
fa-undo for Revert

**Comment by Coop56** [comment]
This issue is done and can be closed now.  @jonpmarino @reynalddizon
