### ISSUE TITLE
"Create a new map" button broken

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#145]
Creating a map from a selection of layers is no longer functioning.

**Comment by ischneider** [comment]
See this thread for details:
https://groups.google.com/a/opengeo.org/group/dev-mapstory/browse_thread/thread/36b6eb5c7efdac8f/f6d1f73c0f81c707?hl=en#f6d1f73c0f81c707

**Comment by ischneider** [comment]
This is fixed for a single layer, but multiple layers still do not work.

**Comment by mpriour** [comment]
this is invalidated by design changes
