### ISSUE TITLE
Launching a mapstory from storylayer detail page throws server errors

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1450]
verified on demo and beta as of 5:50 EST on tuesday
1. Begin from storylayer detail page. Click "compose mapstory"

![grabcompose](https://cloud.githubusercontent.com/assets/2573761/14476592/aee8ecb2-00d6-11e6-9ea4-7a72d109ab04.jpg)
1. This server error appears:

![grabserver](https://cloud.githubusercontent.com/assets/2573761/14476629/ebdc6e78-00d6-11e6-9f2c-adcfc9f05da5.jpg)
1. Clicking "yes" throws this error:

![graberror](https://cloud.githubusercontent.com/assets/2573761/14476637/f9cba238-00d6-11e6-8e26-4ed6fa79a62b.jpg)

**Comment by davisc** [comment]
@jonpmarino this is because edit mode is not supported. This will be fixed with the issue @Coop56 is working on.

**Comment by jonpmarino** [comment]
Ok. That makes sense for the "edit" button on storylayer detail. Also true for "compose mapstory"? The assumed workflow there is "compose mapstory" from storylayer detail launches composer with that storylayer added to the mapstory project in chapter 1. It looks like it is basically working that way now, except that the StoryLayer title appears in the sidebar, but data does not load. And it throws the errors mentioned above.

**Comment by JWileczek** [comment]
This should be done if someone can confirm and close.

**Comment by jonpmarino** [comment]
seems to have been fixed. closing.
