### ISSUE TITLE
Change "Edit StoryLayer Settings" to "Update StoryLayer Settings"

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1452]
The word "edit" there is confusing for a user if they are wanting to contribute edits. We should try and only use the word "edit" when we are referring to editing a StoryLayer with versioned editing.
![edittodelete](https://cloud.githubusercontent.com/assets/2573761/14497784/ff5e2aba-0165-11e6-8313-33d6c92eb159.jpg)

**Comment by Coop56** [comment]
Just pushed a commit - https://github.com/MapStory/mapstory-geonode/commit/10508553ba1de4267bb99b90bfa891fd65b837d3 that closes this issue.  @jonpmarino

**Comment by jonpmarino** [comment]
thanks @Coop56
