### ISSUE TITLE
Second time you save chapter or save as draft or publish mapstory on a non-admin account it throws a permissions issue

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1453]
this was posted by the RFT. I am experiencing today also. Looks like it occurs after you have saved once;. The second save or publish throws the error.

![nopermissions](https://cloud.githubusercontent.com/assets/2573761/14499640/215e57aa-016d-11e6-8f2c-050681a76107.jpg)

**Comment by davisc** [comment]
@jonpmarino this appears to be fixed based on @JWileczek latest commit. Can you confirm on beta.mapstory.org?

**Comment by jonpmarino** [comment]
Hi guys. Just tested with account "jonbeta". Don't get the red permissions error anymore! But do receive this error when adding layers, saving chapters, saving as draft and publishing:

![graberrorsaturday](https://cloud.githubusercontent.com/assets/2573761/14581754/b04987f8-03c2-11e6-8f45-1f0a58263842.jpg)

**Comment by davisc** [comment]
That's fixed also. Just needs to be pushed.

**Comment by jonpmarino** [comment]
outstanding.

**Comment by jonpmarino** [comment]
Confirmed no longer receiving this error on non-admin accounts. Closing for now. Can re-open if it appears again.
