### ISSUE TITLE
Once resized can't scroll Info Popup

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#146]
1. On the dev server, search for the World Atlas story layer
2. Press "Create new map" for full screen
3. Press play
4. Stop animation
5. Activate "Get Feature Info"
6. Select a feature
7. Pop-up shows (as expected) with attribute info.  There are scrollbars on this pop-up
8. Resize pop-up. 

I expect scrollbars to still be there.  However they are no longer there. 

I'm on Chrome.

**Comment by bartvde** [comment]
Trying to reproduce but I am already getting an error on step 2.

http://mapstory.dev.opengeo.org/maps/new?layer=geonode:WAFinal

b is undefined
http://mapstory.dev.opengeo.org/static/static/script/MapStory.js
Line 477

**Comment by bartvde** [comment]
That error should have been fixed with https://github.com/opengeo/gxp/commit/4462654ba46bed5dfb441cda066a87669f6527ac

Now on to the actual issue.

**Comment by bartvde** [comment]
@awright I cannot reproduce, however this raises a question: do we want the feature info to be HTML or do we want it to be a property grid? Are we making use of any custom HTML templates on the server-side? If not, I would advocate using a property grid instead.

**Comment by awright** [comment]
eventually we'll need to style the feature popups. if we can change to feature grid and still style (which i assume we can?) then your reccomendation makes sense.

**Comment by bartvde** [comment]
No a property grid means it's an Ext property grid, so no HTML styling will apply in that case. They will all look the same, but much better than the current unpolished HTML output.

**Comment by bartvde** [comment]
@awright can we close this ticket, or do we need to perform some action on this item? If so, what action?

**Comment by awright** [comment]
We need to restyle the pop-ups this is for sure.  I am not clear on
your recommendation, but we do want things to look good and also able
to develop more as we move forward.  Something that will grow to allow
for images & video as seen here:

http://virtuefoundation.org/map/

On Wed, Mar 21, 2012 at 5:29 AM, Bart van den Eijnden
reply@reply.github.com
wrote:

**Comment by bartvde** [comment]
Switched to grid view in: https://github.com/opengeo/geonode/commit/96fbf12220f07f4e3fa85fe84003b4f40e45d2a3
