### ISSUE TITLE
Icons Commons modal

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1460]
- [X] Upload icon sets we have
- [X] Support in styling

**Comment by davisc** [comment]
The icons-commons app was already installed so I loaded all of the icons from the repo provided by @reynalddizon which includes 86 collections.

<img width="1308" alt="screen shot 2016-04-14 at 8 25 09 pm" src="https://cloud.githubusercontent.com/assets/947403/14548703/17737b72-027f-11e6-871b-4c66fd5a4850.png">

<img width="1268" alt="screen shot 2016-04-14 at 8 24 51 pm" src="https://cloud.githubusercontent.com/assets/947403/14548706/1d20b15c-027f-11e6-8694-5ad9627ddf48.png">

<img width="1306" alt="screen shot 2016-04-14 at 8 19 35 pm" src="https://cloud.githubusercontent.com/assets/947403/14548708/22c65cec-027f-11e6-8625-6b9687e5a252.png">

**Comment by jonpmarino** [comment]
shown on beta. awesome @davisc and all! (and @ischneider )
