### ISSUE TITLE
Internal Server Error when confirming account

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1462]
> create new account
> 
> > receive Confirmation email
> > 
> > > click link to confirm
> > > 
> > > > Internal Server Error

Reference related #1461

**Comment by jonpmarino** [comment]
Confirming new account today threw this error on demo
![graberrorconfirm](https://cloud.githubusercontent.com/assets/2573761/14570055/45814df0-0310-11e6-9c2a-71606bfe6e29.jpg)

**Comment by garnertb** [comment]
@davisc: given the impact of this we should include it in the test coverage to prevent regressions.

**Comment by jonpmarino** [comment]
new account in beta didn't appear to throw an error on confirming account - http://beta.mapstory.org/storyteller/guestuser/

**Comment by jonpmarino** [comment]
confirm fixed on new accounts as of monday. still have #1430 and #1461 with respect to new accounts.

**Comment by cecilia-donnelly** [comment]
@jonpmarino I signed up for a new account on the live site just now (~10 minutes ago), received a confirmation email, followed the link in the email, clicked "confirm," and got the "Internal Server Error" page.  Maybe the fix hasn't been pushed over to the live site yet?  It was a little disconcerting, so I thought I'd let you know.

(The confirmation worked, btw -- I got the "Welcome to MapStory" email and can log in successfully.)

**Comment by jonpmarino** [comment]
Thanks Cecilia. We've seen this a few other times as well. The account does create successfully as you mention. We will be taking a look at it in our development cycle next week.

**Comment by Coop56** [comment]
@jonpmarino Just to add a datapoint to this - I am also getting an Internal Server Error upon clicking confirm.  This was using Firefox on OSX just now on a brand new test account that I just created.

**Comment by davisc** [comment]
@Coop56 from beta or prod?

**Comment by Coop56** [comment]
@davisc Beta.
