### ISSUE TITLE
StoryLayers created with "Create Layer" don't have Edit functions on detail page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1464]
> Create layer from header drop-down
> 
> > No "edit functions" that would enable user to add features to layer

Not sure if this is geogig related, or just a front-end issue with the detail page?

![grablayercreate](https://cloud.githubusercontent.com/assets/2573761/14564075/eefcfffa-02f2-11e6-8ec3-85c1a9a82088.jpg)

**Comment by Coop56** [comment]
@jonpmarino So I just did some quick research into this.  This block of code is likely the reason that the edit is not showing up on created layers.

```
  {% if GEOGIG_ENABLED and resource.link_set.geogig %}
  <hr style="margin:5px">
  <div style="text-align:right">
    <a title="" href="#" target="blank">
      <a href='{% url "map-edit" %}?layer={{resource.service_typename}}&mode=edit'><span style="font-size:1.3em;color:gainsboro">edit</span></a>
      <!-- <span style="font-size:1.3em;color:gainsboro">edit</span> -->
    </a>
  </div>
  {% endif %}
```

The if section of this code is basically saying only show edit if the layer is geogig enabled.  So my first guess would be that newly created layers using the create wizard are not geogig enabled, although I'm not 100% sure how to tell if they are or not.  @JWileczek @davisc or @garnertb do you guys know if layers created using that wizard are geogig enabled?

**Comment by jonpmarino** [comment]
Thanks @Coop56. Makes sense. Just to confirm, our hope is that created layers would be geogig enabled if possible to do so

**Comment by Coop56** [comment]
@davisc I remember we brought this one up in the meeting and that it wasn't a quick fix - what do we need to do here?
