### ISSUE TITLE
Infinite scrolling for mapstory playback

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1466]
Scrolling to the end of the Chapter info should advance to next chapter. This would enable browsing a mapstory by simply continuously scrolling rather than clicking

**Comment by davisc** [comment]
Currently this concept doesn't apply within mapstory. Map changes are not based on scroll waypoint rather its based on time intervals.

**Comment by glynnis** [comment]
Closing this. If this is still relevant, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.
