### ISSUE TITLE
remove welcome modal and properties modal for edit only view of composer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1468]
Going from StoryLayer detail page to "edit storylayer" should not activate the Welcome Modal or the properties modal.

![grabeditonly](https://cloud.githubusercontent.com/assets/2573761/14570749/de2f91c6-0313-11e6-8908-e6bdbcc648b2.jpg)

![grabeditwelcome](https://cloud.githubusercontent.com/assets/2573761/14570754/e452c906-0313-11e6-89d1-878a9dc8caa4.jpg)

**Comment by Coop56** [comment]
This is done and pushed.  You should no longer see the welcome modal in the edit only mode.

**Comment by Coop56** [comment]
This is confirmed on beta, closing as per @jonpmarino
