### ISSUE TITLE
Redirect "edit" button on storylayer card to edit-only composer view

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1469]
Edit button on storylayer card should direct to edit-only composer view. Same path that is linked tom from the Edit link on StoryLayer detail.
![redirectedit](https://cloud.githubusercontent.com/assets/2573761/14573711/a4d8870a-0324-11e6-8d89-1ed1460463a4.jpg)

**Comment by Coop56** [comment]
I have a pull request - https://github.com/MapStory/mapstory-geonode/pull/199 - that will close out this issue.

**Comment by Coop56** [comment]
This is confirmed on beta - closing per @jonpmarino
