### ISSUE TITLE
infoboxes on features accessible in composer should be able to be clicked on published stories in playback

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1470]
- [ ] infoboxes should pop up on user-click. If the chapter has too many layers for InfoBox pop-up to be rational, perhaps we should have a rule that only a single layer is active for infoboxes?

**Comment by ChristopherTucker** [comment]
The cartodb workflow has he popup ask "which layer did you want info on?" With a list or something.

Chris
703-981-9373

**Comment by davisc** [comment]
That's supported in composer when there is a cluster of adjacent points. I can send a screenshot to make sure it's the desired behavior.

**Comment by davisc** [comment]
This is complete.

**Comment by jonpmarino** [comment]
re-opening just to check for discussion. Can close again when confirmed. the ability to click on features of a layer and see the infobox was a desired capability on published mapstories, not just composer. As Chris mentions in an earlier comment, for chapters with multiple layers, we may need to enable users to select which layer they want to have infoboxes appear for on playback when features are clicked. So, on a published mapstory, a viewer can either scroll over storypins or click on features to see the infobox for a feature.

**Comment by glynnis** [comment]
Closing this. If this is still relevant (especially for upcoming Viewer redesign work), please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.
