### ISSUE TITLE
Move legend in composer from underneath zoom control to adjacent to legend content - same as in playback

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1471]
This is an issue in response to #rapidfeedback usersnap #38

-on playback the legend min/max button is top right. In composer it is placed below the zoom control. We should move it up in composer so its the same location as playback

**Comment by Coop56** [comment]
This is done - I swapped the legend toggle and the full screen toggle positions.  This will close this specific request but I opened a new issue to remind myself to change the way these buttons were setup initially when I have some time - https://github.com/MapStory/mapstory/issues/1566.
