### ISSUE TITLE
Need to re-implement detail pages for new mapstory model

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1473]
Currently published mapstories on beta go to the map directly, rather than detail page. Need to fix.

This is the detail page:

![grabstorydetail](https://cloud.githubusercontent.com/assets/2573761/14612137/b3cf3fc4-0563-11e6-9b93-26b52be9034a.jpg)

Clicking the mapstory search card thumbnail, title or "play" button should go to Detail Page once implemented.

**Comment by travislbrundage** [comment]
Related and embed need to be fixed, everything else should work

**Comment by jonpmarino** [comment]
Confirmed detail page is back, but embed and related need to be fixed. Also a few remaining points to hook mapstory detail back into search cards - #1437
