### ISSUE TITLE
Add 'Save Style' button in styling editing form of composer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1475]
Since we have targeted "save" buttons on other aspects (i.e. "save storypin", "save storybox"), it makes sense to have a "save style" button and the bottom of the styling form. 

![grabsavestyle](https://cloud.githubusercontent.com/assets/2573761/14614265/56ee5f14-056e-11e6-8e43-c02b985c1dd2.jpg)

**Comment by Coop56** [comment]
@jonpmarino What would you like this button to do?  Just save the entire MapStory draft?  Or save only the style?

**Comment by jonpmarino** [comment]
whatever is easiest. It would look like the 'Save StoryBox' and 'Save StoryPin' buttons we have already. As a user, when I create my style, I want to save that style and feel confident I won't lose it if I navigate to another part of composer.

**Comment by davisc** [comment]
@jonpmarino and @Coop56 the concept of _save style_ means something different functionally. Currently in order for the style change to be reflected on the map it must be _saved_ server-side which is different from _saving it to the story config_ . Currently these two actions are preformed implicitly and automatically whenever any style property is modified.

**Comment by jonpmarino** [comment]
Ok. Then it's just a matter of ui-ux so the storyteller has some confidence or awareness that this saving is occurring. Can address in future

**Comment by Coop56** [comment]
For now we could just add a button that calls the Save Draft functionality.  That would allow them to click a save button and see a notification that their MapStory was saved.  Since the style saves every time you make a change anyway - those changes would persist.

**Comment by jonpmarino** [comment]
works for me

**Comment by Coop56** [comment]
@jonpmarino Ok I just pushed these changes up - there's now a Save Style button that will call the save draft functionality.  This will save the entire MapStory and alert the user that their save was successful (or not, if there's an error).

**Comment by jonpmarino** [comment]
Great!

**Comment by jonpmarino** [comment]
confirmed and closing.
