### ISSUE TITLE
Unpublished StoryLayers and MapStories are showing up in explore

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1482]
Any StoryLayer or MapStory that has settings = unpublished should not show up in the general explore

**Comment by Coop56** [comment]
PR sent to fix this - https://github.com/MapStory/mapstory-geonode/pull/207 @jonpmarino @davisc

**Comment by Coop56** [comment]
@jonpmarino This is now fixed and on demo.  Please confirm and close when you have a moment, or let me know if you have any questions.

**Comment by jonpmarino** [comment]
confirmed on demo. closing.
