### ISSUE TITLE
fix hopscotch tour

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1483]
1. Starting at step 7 the user gets stranded on steps with no way back or forward
2. is there a way to add "back" and "next" buttons on every step, and make clicking them enable the desired chages on the composer sidebar? This way for the user taking the tour would just mean clicking "next" or "back" and seeing what happens.

**Comment by Coop56** [comment]
So rather than the current way - which the user follows along by clicking on the desired button and the tour updates itself - you want them to click buttons on the tour itself and have that automatically simulate a click on the desired MapStory button?

**Comment by jonpmarino** [comment]
right now the user gets stuck on Step 7. if we can fix those steps, then its fine as is. if not, we should let users click back/forth on the hopscotch steps. not an immediate priority.

**Comment by Coop56** [comment]
It looks like the 'Use' button is missing it's function to update the tour.  I can fix that quickly now.

**Comment by Coop56** [comment]
Ok I just fixed this - the tour now progresses as intended.  There's still a bug where step 7 doesn't show up in the exact place I want it but it is readable and it is working.  We can ticket that fix for later if you want @jonpmarino.
