### ISSUE TITLE
Updating style should update legend.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1484]
- [ ] When a user creates a new style for a StoryLayer in composer, this should replace the style information that appears in legend.
  ![grablegendstyle](https://cloud.githubusercontent.com/assets/2573761/14717903/9b3d7376-07c1-11e6-877e-3a63b9ba3c36.jpg)
- [ ] Added a "unique" style to a storylayer. the class rules it pulled up were for attributes from a previous layer that I had styled (see Benin, Angola, etc showing up for a West Virginia county boundaries layer)

![stylingstuck](https://cloud.githubusercontent.com/assets/2573761/14718191/2d0b33e6-07c3-11e6-8314-b94853d5b346.jpg)

**Comment by davisc** [comment]
This is fixed.
