### ISSUE TITLE
Your MapStory is published modal.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1485]
When a mapstoryteller succesfully publishes their mapstory from composer, we need a simple modal to pop up that informs them "Congratulations! Your MapStory has been published. Check it out here (hyperlink to mapstory detail page)." This mirrors the link generated on the last step of a successful StoryLayer upload.

**Comment by reynalddizon** [comment]
<img width="680" alt="screen shot 2016-05-11 at 9 06 36 am" src="https://cloud.githubusercontent.com/assets/4611843/15187880/be0e0032-1757-11e6-9655-3e31d19ac700.png">

 that's fa-thumbs-up

**Comment by jonpmarino** [comment]
done and closed. re-open if we need
