### ISSUE TITLE
Zoom issues on mapstory playback

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1488]
http://demo.mapstory.org/story/683

The map zoom at the start of chapters tends to be extremely zoomed out.

**Comment by davisc** [comment]
Looks like the layer bbox is not saved in the config, however, the map bounds are saved and honored. @jonpmarino would like to know the steps you followed. Ah looks like if you navigate back to the main menu, the chapter map zooms out, then if you save the story, the bounds and zoom level you thought you saved are now overwritten in composer.

**Comment by JWileczek** [comment]
@jonpmarino and @davisc This should be fixed with chapter center and zoom being saved based on button from issue #1525. If someone could test this out on a new story to confirm that would be great.
