### ISSUE TITLE
SLD editor not working

### ISSUE THREAD

**Issue by ghost** [MapStory/mapstory-meta#149]
No options to change style when you select the style editor

**Comment by bartvde** [comment]
Is this on mapstory.dev.opengeo.org ? Should be fixed soon, after a new deployment.

**Comment by ghost** [comment]
Yes, it was on the dev site. Thanks for the update Bart. 

G. Everett Lasher
ASU Foundation
Mobile: 814.450.3666 

-----Original message-----
From: Bart van den Eijnden  
<reply+i-3115572-69a5043625541a01175774a46feb9050faebd606-1240394@reply.githu 
b.com>
To: Everett Lasher gel@asu.edu
Sent: Fri, Feb 10, 2012 12:32:18 GMT+00:00
Subject: Re: [mapstory] SLD editor not working (#149)

**Comment by bartvde** [comment]
Should be fixed now. Please reopen if it does not work.
