### ISSUE TITLE
In StoryLayer metadata modal, require a StoryLayer title and data source to publish storylayer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1493]
right now StoryLayer metadata modal does not require any fields. Based on advice from Rapid Feedback Team, we should require title and data source
![grab_feedback](https://cloud.githubusercontent.com/assets/2573761/14785608/a767dd70-0ac9-11e6-9094-ef7d2e538712.jpg)

**Comment by glynnis** [comment]
Closing this. If this is still relevant, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.
