### ISSUE TITLE
all my storylayers (published and unpublished) should show up in mini-explore

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1494]
Right now, the mini-explore inside composer only shows my public storylayers under "My StoryLayers" tab. 

Based on feedback from Rapid Feedback Team, they'd like to see all their storylayer - public or private - to show up there so they could draft mapstories with all their layers. 

When a user "publishes" their final mapstory, then, we should add to the publish modal #1485 text that says "Reminder: any StoryLayers used in this MapStory that were previously private will be set to public once you publish this MapStory."

**Comment by Coop56** [comment]
This is done in this commit - https://github.com/MapStory/MapLoom/commit/cd98a3da1696a6860cbd873f354e88069b60e277
