### ISSUE TITLE
Update text and css for composer welcome modal

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1495]
Need to clean up the text and CSS on this. Suggested text below. @reynalddizon defer to you on design...

![fullsizerender 16](https://cloud.githubusercontent.com/assets/2573761/14786204/d21b29b2-0acb-11e6-9b70-f50f079f3533.jpg)

**Comment by Coop56** [comment]
@jonpmarino  I pushed up the new text, @reynalddizon let me know what you want it to look like design wise.
