### ISSUE TITLE
Hitting play causes content (layers, boxes, pins) not to play back

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1497]
Steps:

> Create and publish mapstory (http://beta.mapstory.org/mapstory/17191)
> 
> Hit play. Time control seems to freeze, and saved content does not play back.

**Comment by davisc** [comment]
This is fixed by https://github.com/MapStory/django-maploom/commit/7916210b635ebc2d5909715dbf336d242c56c6c0
