### ISSUE TITLE
New error: Save failed - Map save failed with following error

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1501]
This error popped up automatically after I opened up mini-explore to add a layer to chapter 1.

![save_failed](https://cloud.githubusercontent.com/assets/2573761/14793651/48261ca8-0aee-11e6-96ef-bf01adcfb4d8.jpg)

**Comment by JWileczek** [comment]
When did this occur? Was it on beta? I so far cannot reproduce this error.

**Comment by jonpmarino** [comment]
@JWileczek haven't seen it yet again today.  If i do I'll add more detail.

**Comment by jonpmarino** [comment]
@JWileczek just experienced again in beta.. I:

Added title in properties and save. Clicked "Chapter Info". Error popped up just as I was going to click "Add StoryLayers"

**Comment by Coop56** [comment]
I've went through the process of creating and saving mapstories on demo in all major browsers and I haven't gotten any errors relating to saving in any of them.  Closing this unless we can reproduce it @jonpmarino if you see this error again please open the Console (right click inspect and go to the console tab) and screen shot any errors you are seeing in there when this happens.

**Comment by jonpmarino** [comment]
sounds good. thanks guys.
