### ISSUE TITLE
Need to add layer notifications on edit-only mode

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1502]

**Comment by Coop56** [comment]
@jonpmarino What notifications do we want here?  Just "Layer Loading..." and "layerName Loaded"?

**Comment by Coop56** [comment]
@reynalddizon @jonpmarino I added this to demo - feel free to try a few layers.  Most of the ones I try load instantly.  If you know of one that takes time to load, you should see a Layer Loading... notification while it loads.  Layer Loaded notifications are definitely working.

**Comment by jonpmarino** [comment]
confirmed and closing for now. Can re-open new issue if we notice new things.
