### ISSUE TITLE
Remove "edit" button now on the cards until we can wire that up properly

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1505]
Edit link on detail page works, so user can assess editing based on the card

**Comment by Coop56** [comment]
I pushed up the changes on this in this commit - https://github.com/MapStory/mapstory-geonode/commit/b53c7d7ee34ddd69b6410a3fce083d5afa470d34

**Comment by Coop56** [comment]
@jonpmarino I just confirmed this on both demo and beta - feel free to close if you see the same.

**Comment by jonpmarino** [comment]
Confirmed and closing
