### ISSUE TITLE
Reposition hopscotch tour steps and create exit X on each step

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1507]
Hopscotch tour steps got misaligned due to CSS changes. User now gets stuck on Step 9. Need to relocate steps. Also should activate the X on each step so a user can leave the tour without having to finish.

**Comment by Coop56** [comment]
Closing the tour out just removes the tour bubbles and the user can start composing as usual.  This is built in Hopscotch functionality that we would have to modify if we need it to take them back to the welcome modal.

**Comment by jonpmarino** [comment]
No worries. Leave the built in functionality. Sounds good.

**Comment by Coop56** [comment]
This is done and live on demo @jonpmarino.

**Comment by jonpmarino** [comment]
confirmed and closing.
