### ISSUE TITLE
Delete button for MapStory cards in profile does not delete the MapStory

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1510]
Steps

> Go to profile
> filter for mapstories
> Delete a mapstory
> the confirmation button pops up, and then user is taken to home page
> If you return to profile, your mapstory is still there

Correct workflow =

> After confirming the delete, the user should be taken back to Profile page, and deleted mapstory should no longer appear.

Delete does seem to be working well for StoryLayers

**Comment by travislbrundage** [comment]
Closed by [PR#31](https://github.com/MapStory/geonode/pull/31) and [PR#213](https://github.com/MapStory/mapstory-geonode/pull/213)
