### ISSUE TITLE
StoryPins don't respect the set beginning and end time

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1511]
Once StoryPins are created in composer, they appear on the map for the duration of the chapter, rather than the beginning/end time set.

In the screenshot, these 3 pins are all set to begin in years after 1636
![grab_pins_showing](https://cloud.githubusercontent.com/assets/2573761/14828702/1eb0ce2c-0bb6-11e6-9d06-1d9f20774b6e.jpg)

**Comment by JWileczek** [comment]
@jonpmarino This is done and testable on demo and beta.
