### ISSUE TITLE
StoryLayer and MapStory detail page reskin

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1518]
to make it look a bit more like the composer 

![mapstory_detail](https://cloud.githubusercontent.com/assets/4611843/14834727/0dc108ac-0bd4-11e6-9b11-2e7e717f3172.png)

![storylayer_detail](https://cloud.githubusercontent.com/assets/4611843/14834728/0dc92e92-0bd4-11e6-9501-e75f830daabd.png)

documentation to follow

**Comment by reynalddizon** [comment]
details page edits:

.page-title {
display: block;
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
font-weight: 600;
margin: 0;
}
change Uploaded By —> Uploaded by:

for buttons:
add btn and btn-block classes and add 

.btn-detailpage {
background-color: #666;
color: #eee;
font-size: 0.8em;
font-weight: 700;
border: 1px solid #666;
border-radius: 4px;
padding: 10px !important;
margin: 10px;
}

for the side-column-header

-remove the h3 tag
-add <div class=“side-column-header”>

.side-column-header {
    display: block;
padding: 5px 15px;
margin: 10px;
background-color: #ddd;
color: #444;
font-size: 0.8em;
border-radius: 4px;
width: 100%;
font-weight: 700;
margin-top: 40px;
}

for the ul on side-column, add <ul class=“side-column-items”>

.side-column-items li {
    color: #555;
    margin: 1px 15px;
    font-size: 0.7em;
    font-weight: 600;
}

.side-column-items li i{
    margin: 5px;
}

-wrap the tags section in an <li> and remove <h3> from Tag text. add <i class=“fa fa-tags”>

for the tabs, add details-tabs class after nav-tabs 

.details-tabs {
    border-bottom: 2px solid #999;
    color: #999;
    font-weight: 600;
}

.details-tabs > li > a, .details-tabs > li > a:hover, .details-tabs > li > a:focus {
    padding: 10px 70px;
    border: 0;
}

.details-tabs > li > a:hover, .details-tabs > li > a:focus {
    color: #666;
}

.details-tabs > li.active > a, .details-tabs > li.active > a:hover, .details-tabs > li.active > a:focus {
    border: 0;
    border-bottom: 4px solid #f59620;
    color: #444;
}

**Comment by Coop56** [comment]
The base pages are done - adding CSS next.

**Comment by Coop56** [comment]
Done and live on demo - example - http://demo.mapstory.org/layers/geonode:crawfish_habitat

**Comment by jonpmarino** [comment]
add back embed, username should link to profile, add "message" storyteller link

**Comment by jonpmarino** [comment]
confirmed embed, username and message are back in. closing.
