### ISSUE TITLE
Remove save as draft/publish and MapStory Properties buttons on sidebar header for edit-only mode

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1519]

**Comment by Coop56** [comment]
This commit removes these from the edit only mode - https://github.com/MapStory/MapLoom/commit/b722c157165b901e44fbdf6799a1f8bd7256e31c - you can test it in a few minutes on demo and close @jonpmarino.

**Comment by jonpmarino** [comment]
rgr

**Comment by Coop56** [comment]
@jonpmarino You can now confirm this on demo and close.

**Comment by jonpmarino** [comment]
confirmed, although it looks like now the hamburger menu collapse button is inactive and the editing tool buttons below got misalinged. Could be my screen/browser.

![grab_spacing](https://cloud.githubusercontent.com/assets/2573761/14860073/01b7e598-0c75-11e6-9aba-e8f270cb4bfa.jpg)

**Comment by Coop56** [comment]
Confirmed on mine as well, looks like some CSS issues now that a few of the buttons are using a tags.  I'll open up a new ticket to fix.

**Comment by Coop56** [comment]
This is done, there is another ticket to fix a CSS issue with the collapsible button.
