### ISSUE TITLE
Exit button in edit-only fails

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1520]

**Comment by Coop56** [comment]
The metadata button isn't working either.

**Comment by Coop56** [comment]
Both are fixed with this commit - https://github.com/MapStory/MapLoom/commit/11e31bb1199d94456b793f536ee3574c985a03c7 - should be able to confirm on demo in 5-10 minutes @jonpmarino

**Comment by jonpmarino** [comment]
rgr.

**Comment by Coop56** [comment]
@jonpmarino You can now confirm this on demo and close.

**Comment by jonpmarino** [comment]
confirmed and closing.
