### ISSUE TITLE
increase height of Chapter Info summary box

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1521]
Right how its about 2 lines. Expanded to a height that fills up the sidebar (maybe 20-25 lines?)

**Comment by Coop56** [comment]
Fixed with this commit - https://github.com/MapStory/MapLoom/commit/6942bb847fa4899ad7f87f041f76ba384df412cc - we can confirm tomorrow when the automated build server gets rebooted @jonpmarino

**Comment by Coop56** [comment]
@jonpmarino You can now confirm this on demo and close.

**Comment by jonpmarino** [comment]
confirmed and closing.
