### ISSUE TITLE
Unique and Choropleth color ramps

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1526]
From colorbrewer2.org

For Unique style:
<img width="106" alt="screen shot 2016-04-28 at 12 51 19 pm" src="https://cloud.githubusercontent.com/assets/4611843/14894270/ca82f370-0d40-11e6-8772-e44568896055.png">
<img width="103" alt="screen shot 2016-04-28 at 12 51 32 pm" src="https://cloud.githubusercontent.com/assets/4611843/14894271/ca85f8cc-0d40-11e6-89c9-aaeea220fedd.png">

For Choropleth style:
<img width="108" alt="screen shot 2016-04-28 at 12 53 35 pm" src="https://cloud.githubusercontent.com/assets/4611843/14894302/e8ed1bf6-0d40-11e6-9c61-753043df95cb.png">
<img width="106" alt="screen shot 2016-04-28 at 12 53 40 pm" src="https://cloud.githubusercontent.com/assets/4611843/14894305/e8eeaf8e-0d40-11e6-9f8f-cb52df5b23ba.png">
<img width="107" alt="screen shot 2016-04-28 at 12 53 51 pm" src="https://cloud.githubusercontent.com/assets/4611843/14894306/e8eedda6-0d40-11e6-935e-73b9e22f797c.png">
<img width="106" alt="screen shot 2016-04-28 at 12 54 08 pm" src="https://cloud.githubusercontent.com/assets/4611843/14894303/e8edec52-0d40-11e6-8248-a2749ca34d15.png">
<img width="101" alt="screen shot 2016-04-28 at 12 54 26 pm" src="https://cloud.githubusercontent.com/assets/4611843/14894301/e8ecb15c-0d40-11e6-9d57-25d192c30bc6.png">
<img width="107" alt="screen shot 2016-04-28 at 12 54 34 pm" src="https://cloud.githubusercontent.com/assets/4611843/14894304/e8ee07be-0d40-11e6-82a7-bc9ec486ccbc.png">
<img width="110" alt="screen shot 2016-04-28 at 12 54 45 pm" src="https://cloud.githubusercontent.com/assets/4611843/14894307/e8f3327a-0d40-11e6-9add-2b7ed78a0cd9.png">

**Comment by davisc** [comment]
@reynalddizon can you provide these as a JS array? colorbrewer has that option under the export tab.

**Comment by reynalddizon** [comment]
@davisc here:

For Unique:
Option 1: ['#8dd3c7','#ffffb3','#bebada','#fb8072','#80b1d3','#fdb462','#b3de69','#fccde5','#d9d9d9']
Option 2: ['#a6cee3','#1f78b4','#b2df8a','#33a02c','#fb9a99','#e31a1c','#fdbf6f','#ff7f00','#cab2d6']
Option 3: ['#fbb4ae','#b3cde3','#ccebc5','#decbe4','#fed9a6','#ffffcc','#e5d8bd','#fddaec','#f2f2f2']

For Choropleth:
Option 1: ['#ffffe5','#f7fcb9','#d9f0a3','#addd8e','#78c679','#41ab5d','#238443','#006837','#004529']
Option 2: ['#ffffcc','#ffeda0','#fed976','#feb24c','#fd8d3c','#fc4e2a','#e31a1c','#bd0026','#800026']
Option 3: ['#f7fbff','#deebf7','#c6dbef','#9ecae1','#6baed6','#4292c6','#2171b5','#08519c','#08306b']
Option 4: ['#ffffff','#f0f0f0','#d9d9d9','#bdbdbd','#969696','#737373','#525252','#252525','#000000']
Option 5: ['#b2182b','#d6604d','#f4a582','#fddbc7','#f7f7f7','#d1e5f0','#92c5de','#4393c3','#2166ac']
Option 6: ['#d53e4f','#f46d43','#fdae61','#fee08b','#ffffbf','#e6f598','#abdda4','#66c2a5','#3288bd']
Option 7: ['#8c510a','#bf812d','#dfc27d','#f6e8c3','#f5f5f5','#c7eae5','#80cdc1','#35978f','#01665e']

**Comment by emilyashley** [comment]
♡ me some color brewer.  

Here's an additional randomized colorblind one for qualitative data (just for good measure) The first three listed aren't as accessible. Luckily, [I want hue](http://tools.medialab.sciences-po.fr/iwanthue/) is pretty great for that, too

["#cf3833", "#02c786", "#b0087f", "#c1e15a", "#0060b9", "#931800", "#4f5700", "#f2456d", "#ff9969"]

**Comment by davisc** [comment]
https://github.com/google/palette.js/tree/master or https://github.com/c0bra/color-scheme-js

**Comment by Coop56** [comment]
This is done and already closed in Jira, closing here.
