### ISSUE TITLE
Profile button on composer header

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1528]
Add the profile button on header. see screenshot
![new_header](https://cloud.githubusercontent.com/assets/4611843/14890332/2da1f08e-0d30-11e6-8165-90c5113009ae.png)

**Comment by Coop56** [comment]
Comment for myself - just add the username and a log out button to this for now.

**Comment by Coop56** [comment]
This has been added with this commit - https://github.com/MapStory/MapLoom/commit/cbde65401d3360dcd1b1a1f938245b3912cf0790 - should be on demo shortly @jonpmarino @reynalddizon

**Comment by Coop56** [comment]
Confirmed it is on demo.
