### ISSUE TITLE
TypeError pop-up when trying to add a chapter

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1529]
Getting this error message immediately after starting a new mapstory and trying to add a chapter (on beta.mapstory.org)
![grab_type_error](https://cloud.githubusercontent.com/assets/2573761/14917878/2bc7e33a-0def-11e6-8d2d-262039b6675c.jpg)

**Comment by JWileczek** [comment]
@Coop56 This is related to the hopscotch tour.

**Comment by Coop56** [comment]
@jonpmarino @JWileczek Were either of you able to replicate this again?  What exactly were you doing when it happened Jon?  I have been unable to replicate it based on your initial comment.

**Comment by jonpmarino** [comment]
I think i did this when the geoserver was rebooting. ignore for now.
