### ISSUE TITLE
Append link should not show unless layer is supported by versioned editing

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1531]
Users should only be able to append to StoryLayers if the layer captures version history of edits. If it does not, we should hide the Append link on the StoryLayer, just as we already do hide the EDIT link.
![append_no_show](https://cloud.githubusercontent.com/assets/2573761/14918491/35ab81c4-0df2-11e6-8eff-35f4b0823d2f.jpg)

**Comment by JWileczek** [comment]
Fixed in this commit: https://github.com/MapStory/mapstory-geonode/commit/e3db846c8ab30bfbbdd0a083849547b9ad354787
