### ISSUE TITLE
0429 CSS

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1532]
- [x] Remove the Switch Coordinates button:
  <img width="242" alt="screen shot 2016-04-29 at 10 18 20 am" src="https://cloud.githubusercontent.com/assets/4611843/14918791/be8eeb38-0df3-11e6-81de-f0e1532c5851.png">

```
<div id="switch-coords-border" class="map-btn-border ng-scope" tooltip-append-to-body="true" tooltip-placement="right" tooltip="Switch Coordinate Display" style="bottom: 42px;">
                <div id="switch-coords" ng-click="mapService.switchMousePosCoordFormat()">
                    <i class="glyphicon glyphicon-map-marker"></i>
                </div>
            </div>
```
- [x] update label rules
  .menu label {
  display: inline-block;
  max-width: 100%;
  margin-bottom: 5px;
  font-family: 'Open Sans', sans-serif !important;
  font-size: 12px;
  font-weight: 700;
  line-height: 20px;
  color: #666;
  }
- [x] remove hr tag in the welcome modal content
- [x] View Table of StoryLayers css updates
  # table-view-window .panel {
  
  height: 100%;
  max-width: 100%;
  overflow: auto;
  background-color: whitesmoke;
  }

.table-striped>thead>tr>th {
border-bottom: 2px solid #ddd;
padding: 10px;
font-size: 0.8em;
text-transform: uppercase;
font-weight: 600;
}

.table-striped>tbody>tr>td, .table-striped>thead>tr>th {
max-width: 200px;
padding: 3px 10px;
overflow: hidden;
text-overflow: ellipsis;
border-left: 1px dotted #ddd;
font-size: 0.7em;
}

.table-striped>tbody>tr>td {
    border-top: 1px solid #ddd;
color: #666;
font-size: 0.8em;
}

.selectedRow > td {
    background-color: #f59620 !important;
color: whitesmoke;
}

**Comment by Coop56** [comment]
These changes have been made and committed - https://github.com/MapStory/MapLoom/commit/f60635aa2079bac7c7b9450d6a0726e649098e1b

**Comment by Coop56** [comment]
The switch coordinates button was removed now as well.
