### ISSUE TITLE
display attribute values in the legend

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1533]
<img width="1280" alt="screen shot 2016-04-29 at 11 08 49 am" src="https://cloud.githubusercontent.com/assets/4611843/14920434/94b1443e-0dfb-11e6-880c-58661e3a9afd.png">

For unique style, the label should display the attribute value text string.

For choropleth and graduated style, the label should display the numerical (integer and double) range (min and max)  per symbology.

For simple, not sure yet. Open to ideas.

**Comment by jonpmarino** [comment]
related to #1484
