### ISSUE TITLE
Keep user on Earth.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1538]
If user scrolls up and down on basemap in composer, they go into outerspace (black map). For users, should define parameters so never zoom beyond map.

**Comment by davisc** [comment]
Some code from storytools which may help

```
 // prevent getting off the earth
 extent[1] = Math.max(-20037508.34, Math.min(extent[1], 20037508.34));
 extent[3] = Math.max(-20037508.34, Math.min(extent[3], 20037508.34));
 getMap().getView().fitExtent(extent, getMap().getSize());
```

**Comment by Coop56** [comment]
Comment for myself - http://gis.stackexchange.com/questions/118383/openlayers-3-max-extent

**Comment by Coop56** [comment]
I've set extents that will solve this.  Unfortunately the way extent is setup - it only ensures the extents stay within the view.  So there's still ugly white space on the sides that I have not seen an answer for anywhere in the OpenLayers documentation.  The user can no longer scroll off into infinity though.
