### ISSUE TITLE
New MapStories seem to be creating a double thumbnail

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1542]
Newly published mapstories in Explore and Profile seem to have 2 thumbnails associated?
![grab_double_thumb](https://cloud.githubusercontent.com/assets/2573761/14945545/8c67b244-0fe1-11e6-9e12-0d1145d63c12.jpg)

**Comment by JWileczek** [comment]
This was fixed in changes from travis' pull request.
