### ISSUE TITLE
Catch GetCapabilities 404 Console Error and Alert User

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory-meta#1547]

**Comment by davisc** [comment]
@JWileczek if more than one layer is loading, is there a way to enrich the failure message to indicate which layer failed to load? May include the title of the layer in the message?

**Comment by JWileczek** [comment]
done in https://github.com/MapStory/MapLoom/commit/ef4ed23845c9d8f148d46ef311723dd099104e59
Loading messages now display the name of the layer when it begins, finishes, and fails loading.
