### ISSUE TITLE
StoryScapes Skin

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1553]
All of these are just updates of the existing classes

.menu {
    width: 20%;
height: 100%;
overflow-y: scroll;
font-family: 'Open Sans', sans-serif !important;
font-size: 1em;
background: #333;
}
# composerTopNav {

```
height: 40px;
```

padding: 3px 5px;
background-color: #162f43;
}

.menu .topText {
    display: block;
padding: 10px;
padding-bottom: 5px;
margin: 0;
font-family: 'Open Sans', sans-serif !important;
font-size: 10px;
font-weight: 700;
line-height: 10px;
color: #ccc;
}

.menu .bottomText {
display: block;
padding: 0 10px 5px;
margin: 0;
font-family: 'Open Sans', sans-serif !important;
font-size: 18px;
font-weight: 700;
line-height: 20px;
color: #ccc;
}
# mapstory-title {

```
padding: 0 0 5px !important;
```

font-size: 1em;
color: #ccc !important
}
# composerIconNav {

```
display: block;
```

height: 40px;
padding: 5px;
background-color: #444;
}
# composerIconNav i {

float: left !important;
width: 16%;
padding: 5px;
font-size: 18px;
color: #ccc;
text-align: center

}
# composerIconNav i:hover {

color: #333;
background: #ddd;
border-radius: 4px;
}

.menuItem {
    display: block;
padding: 6px;
margin: 10px;
font-family: 'Open Sans', sans-serif !important;
background: #555;
border-radius: 0;
}

.menuItem:hover {
background: #777;
}

.menu a h2
margin: 0;
font-family: 'Open Sans', sans-serif !important;
font-size: 10px;
font-weight: normal;
line-height: 16px;
color: #ccc;
}

.menu i {
float: right;
padding-top: 3px;
padding-right: 10px;
padding-bottom: 0;
padding-left: 10px;
font-size: 15px;
color: #ccc
}

.menu i:hover {
color: #eee;
}

.menu a {
display: block;
padding: 6px;
overflow: hidden;
font-family: 'Open Sans', sans-serif !important;
font-size: 12px;
font-weight: 700;
line-height: 20px;
color: #ccc;
text-decoration: none;
outline: 0
}

.menu label {
display: inline-block;
max-width: 100%;
margin-bottom: 5px;
font-family: 'Open Sans', sans-serif !important;
font-size: 12px;
font-weight: 700;
line-height: 20px;
color: #ccc;
}

.modal .modal-header, .loom-dialog.dialog-warning .modal-header {
padding: 15px;
color: #ccc;
text-align: center;
background-color: #162f43;
border-bottom: 0;
border-top-right-radius: 4px;
border-top-left-radius: 4px
}

.loom-dialog.dialog-warning .modal-body, .modal .modal-body, .loom-dialog.dialog-warning .modal-footer {
max-height: 60vh;
padding: 20px 30px;
overflow-y: auto;
background-color: #bbb;
}

.btn-storylayer:hover, .btn-storylayer i:hover {
color: whitesmoke;
background-color: #255074
}

.style-editor-item {
padding: 3px;
margin-bottom: 5px;
background-color: #555;
border: 0 !important;
border-radius: 0;
}

**Comment by davisc** [comment]
This is complete and available here https://github.com/MapStory/django-maploom/tree/storyscapes-v1
