### ISSUE TITLE
Add "zoom to pin" back to StoryPin editor

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1554]
Right now in StoryPin editor we "Add StoryPin to Map" and "Update StoryPin". Neither zooms to the pin location so that user can see where it is before changing location. You have to scrub the time slider to find the pin.

**Comment by JWileczek** [comment]
This is up on demo. Now if you select a storypin from the sidebar menu it will zoom to that time on the timeline so the storypin will show on the map (assuming the storypin is set to show in the map).
