### ISSUE TITLE
replace storypin circle icon (red outline with light red transparency) with newly branded one

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1557]
@reynalddizon will provide icon

**Comment by reynalddizon** [comment]
i saw a nice pin icon that maybe we could use for story pin symbology. it's available on icon commons. (just search for "pin", it's the third one.) then just change the color to mapstory orange #f59620.
<img width="215" alt="screen shot 2016-05-09 at 8 41 47 am" src="https://cloud.githubusercontent.com/assets/4611843/15118680/26c8cb8a-15c2-11e6-9719-d7a02193f1b9.png">

**Comment by Coop56** [comment]
@reynalddizon Can you show me a screenshot of what you mean by the red outline with light red transparent circle icon?

**Comment by jonpmarino** [comment]
this.
![grab_pin_circle](https://cloud.githubusercontent.com/assets/2573761/15198714/2a6c5f04-17a7-11e6-8e12-5317bf014936.jpg)

**Comment by glynnis** [comment]
Closing this. If this is still relevant (especially if it's relevant for the Composer redesign), please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.
