### ISSUE TITLE
Replace MapStory reference in MapLoom Composer Tour StoryScapes Branch

### ISSUE THREAD

**Issue by davisc** [MapStory/mapstory-meta#1559]
- [ ] Change the text `Mapstory` to `Narrative`

**Comment by Coop56** [comment]
I replaced this already to say StoryScape - there shouldn't be any mention of MapStory on the latest branch, but I'll get it changed to Narrative.

**Comment by davisc** [comment]
Ah I see on the rebased branch.

**Comment by Coop56** [comment]
I updated it from StoryScape to Narrative on the tour, in the origin/feature/sc-composer-skinned-rebase branch and pushed the changes if you want to deploy it @davisc.
