### ISSUE TITLE
Invalid resource lookup data provided (mismatched type).

### ISSUE THREAD

**Issue by davisc** [MapStory/mapstory-meta#1560]
The following error is returned when executing a search however hitting a particular api endpoint like `/api/layers` returns successfully.

OS: CentOS release 6.7 (Final)

`
{
error_message: "Invalid resource lookup data provided (mismatched type).",
traceback: "Traceback (most recent call last): File "/var/lib/geonode2/lib/python2.7/site-packages/tastypie/resources.py", line 196, in wrapper response = callback(request, *args, **kwargs) File "/var/lib/geonode2/lib/python2.7/site-packages/tastypie/resources.py", line 436, in dispatch_detail return self.dispatch('detail', request, **kwargs) File "/var/lib/geonode2/lib/python2.7/site-packages/tastypie/resources.py", line 459, in dispatch response = method(request, **kwargs) File "/var/lib/geonode2/lib/python2.7/site-packages/tastypie/resources.py", line 1296, in get_detail obj = self.cached_obj_get(bundle=basic_bundle, **self.remove_api_resource_names(kwargs)) File "/var/lib/geonode2/lib/python2.7/site-packages/tastypie/resources.py", line 1114, in cached_obj_get cached_bundle = self.obj_get(bundle=bundle, **kwargs) File "/var/lib/geonode2/lib/python2.7/site-packages/tastypie/resources.py", line 2073, in obj_get raise NotFound("Invalid resource lookup data provided (mismatched type).") NotFound: Invalid resource lookup data provided (mismatched type). "
}
`

**Comment by ingenieroariel** [comment]
Not sure if this helps: http://stackoverflow.com/questions/11684659/tastypie-notfound-invalid-resource-lookup-data-provided-mismatched-type

**Comment by ingenieroariel** [comment]
Another option related to trailing slashes: https://github.com/django-tastypie/django-tastypie/issues/665

**Comment by davisc** [comment]
Fixed. This error occurs when `HAYSTACK_SEARCH` is not enabled and you attempt to hit search endpoint. When haystack search is disabled, the following pattern  `^(?P<api_name>api)/ ^(?P<resource_name>layers)/search/$ [name='api_get_search']` is not available to urls.py which at request time tries to find the best match to process the request. In our case tastypie used `^(?P<api_name>api)/ ^(?P<resource_name>layers)/(?P<pk>.*?)/$` which results in the error noted above because it expects `/search` to represent an integer value for the primary key - mismatched type.
