### ISSUE TITLE
remove orange accents in storyscapes pages and composer

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1561]
# upload-navbar.nav-tabs > li.active > a, #upload-navbar .nav-tabs > li.active > a:hover, #upload-navbar .nav-tabs > li.active > a:focus {

color: #46443b;
cursor: default;
background-color: #ffffff;
border: 0px;
border-bottom: 4px solid #162f43;
}

a#start-composing:hover {
font-weight: bold;
color: #162f43;
text-decoration: none
}

a#start-tour:hover {
font-weight: bold;
color: #162f43;
text-decoration: none
}

**Comment by Coop56** [comment]
a#start-composing:hover {
font-weight: bold;
color: #162f43;
text-decoration: none
}

a#start-tour:hover {
font-weight: bold;
color: #162f43;
text-decoration: none
}

These two are done and committed to the rebase branch for StoryScapes on MapLoom.  The third one is in mapstory-geonode.  How do we skin that @davisc?
