### ISSUE TITLE
Composer fails when https is enabled

### ISSUE THREAD

**Issue by davisc** [MapStory/mapstory-meta#1563]

**Comment by Coop56** [comment]
Is this on StoryScapes specifically or MapStory?  MapStory doesn't have an SSL certification I don't think?  @davisc

**Comment by Coop56** [comment]
Need more info on this one @davisc and @jonpmarino - when does it fail?  Where?  Is SSL enabled for the domain it fails on?

**Comment by Coop56** [comment]
Closing this issue for now based on our talk Friday.  This fails on MapStory because the entire site fails, with no SSL cert.  It works fine on StoryScapes, which has an SSL cert.
