### ISSUE TITLE
CSS wrapper that forces Storypin images to scale to graceful size

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1567]
We should define a default size for StoryPin images or videos and force them to scale that size once added in composer and on playback, without user having to determine. cc @reynalddizon

**Comment by reynalddizon** [comment]
i know of a solution for image embeds: we just use img-responsive class. it will just inherit the width of the story pin container. I'm not sure about the responsiveness of video iframe tho.

**Comment by JWileczek** [comment]
@reynalddizon I used the img-responsive class and that worked for the image links. For the iframe embeds I am now extracting and changing the width and height of the embed when they add the pin with that content. If you get me width and height values that you think would look best I can easily change them to be that size.

**Comment by reynalddizon** [comment]
The img-responsive class inherits the width of the parent class containing the <img> tag, I think it's called panel. And that parent class has a fixed width (I think it's 180px). So I guess we want to copy that value and for the height, we want the videos the preserve the aspect ratio.

**Comment by JWileczek** [comment]
Changed and should be up on demo
