### ISSUE TITLE
Changing basemap with more than one StoryLayer added to chapter causes top StoryLayer to become invisible

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1573]

**Comment by Coop56** [comment]
@jonpmarino I'm going to need some more info on this one to replicate it.  I just went on production and I added a StoryLayer.  I then changed the basemap several times and the layer never disappeared.

**Comment by jonpmarino** [comment]
Ok. just confirmed. Try adding 2 StoryLayers to a chapter. Then change the basemap. One of the StoryLayers will be set to invisible.

**Comment by Coop56** [comment]
Fixed this with this commit - https://github.com/MapStory/MapLoom/commit/df371c8661be366ea6ef647ab25abe0cfac979cf
