### ISSUE TITLE
Pagination in composer mini-explore

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1578]
No way to advance to more storylayers in mini-explore after reaching the bottom of the first page.

**Comment by Coop56** [comment]
Currently we're limiting the results to 100 layers - so when you get to the bottom of those 100 you don't see any more.  What we'll do here is add a load more button that will call the API again and get the next 100 results.

**Comment by Coop56** [comment]
This commit should solve this - https://github.com/MapStory/MapLoom/commit/35f10436bf2043a168ae814b7e0eec472d7c4e83 - but I need to test it on beta where we have over 100 StoryLayers.  @davisc @jonpmarino
