### ISSUE TITLE
StoryPin: Should respect the start and end date created by storyteller, no matter what the features are in layers

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1579]
Right now StoryPins only show up with the StoryLayer if they correspond with an exact date on the StoryLayer. This prevents a storyteller from adding StoryPins that don't correspond exactly to a StoryLayer data point.

We need a model that lets a storyteller create StoryPins for any beginning and end date they wish, even if don't exactly correspond with a storylayer data point.

**Comment by davisc** [comment]
As an example, I made this change to the viewer playback. Essentially this allows the user to create a story with just pins and have it playback accordingly.
