### ISSUE TITLE
StoryPin: Add option in StoryPin form for "Show Content Automatically"

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1581]
Right now a user has to scroll over to get a StoryPin to pop up. Sometimes users will want their StoryPins to pop up without a user having to scroll on them. This should be an option in composer.

**Comment by davisc** [comment]
Is this on a per pin basis or generally applies to all pins?

**Comment by jonpmarino** [comment]
I would think an ideal implementation would be per pin, and then an option to "Apply to all"

**Comment by JWileczek** [comment]
Added a new property in add storypin to show content automatically during playback. Currently works in composer needs to be added to viewer.

**Comment by Coop56** [comment]
This one is done and working - #1623 is the next piece of this.
