### ISSUE TITLE
StoryPin: Make StoryPins default to "scroll over" in composer so behavior is the same as publish playback

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1582]
Once a MapStory is published, StoryPins default to appear as scroll over. In composer right now they default to pop up on click. We should have the behavior be the same (scroll over) in composer as it is in playback.

**Comment by Coop56** [comment]
@jonpmarino Do you have a live example of the scroll over behavior in viewer?

**Comment by jonpmarino** [comment]
We've used http://roadskillmap.com/ as an example. Think of the blue dots as "storypins" and the pop ups for the features on the map as "infoboxes". roadskill has the opposite of our model. their "storypins" are click and "infoboxes" are scroll over. we want opposite. Storypins are scroll over and infoboxes on features pop up if user clicks a feature.

**Comment by Coop56** [comment]
Just pushed up a change so that the Composer now allows you to scroll over StoryPins to view the information about them.  You should be able to see it shortly on demo @jonpmarino.

**Comment by Coop56** [comment]
I changed all of the event handling from singleclick to the hover, I need to change it back to singleclick and pull out specifically the storypin code and handle that with the hover event.

**Comment by Coop56** [comment]
Done correctly this time.  Single clicks still work on all other features, StoryPins are setup for scroll over.
