### ISSUE TITLE
Quick search on home or header doesn't appear to support a search

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1584]
enter a search request in homepage or header "quick search". Seems to land on Explore with just all "published=true" content showing. Conduct a search in the search bar in Explore page seems to generate a filtered search, though.

**Comment by travislbrundage** [comment]
Should be fixed by this: https://github.com/MapStory/mapstory-geonode/commit/2475053f1a354c9ed56e4b12aa465221fc28b04a

**Comment by jonpmarino** [comment]
Quick search isn't working. Entering a search query returns all results.

**Comment by Coop56** [comment]
This is done and working!  Should be up on demo now.
