### ISSUE TITLE
Go through dev_ops log and determine if tickets are needed

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1585]
Need to go through dev_ops slack channel and make sure all errors are reflected in tickets.

**Comment by davisc** [comment]
ERROR (EXTERNAL IP): Internal Server Error: /initiatives/{{ item.detail_url}}
ERROR (EXTERNAL IP): Internal Server Error: /story/{{ item.id }}
ERROR (EXTERNAL IP): Internal Server Error: /maps/17213

**Comment by Coop56** [comment]
ERROR (EXTERNAL IP): Internal Server Error: /api/owners/
Internal Server Error: /api/owners/

KeyError at /api/owners/
'objects'

Request Method: GET
Request URL: http://mapstory.org/api/owners/?city=london&limit=100&offset=0
Django Version: 1.6.10
Python Executable: /home/mapstory/.virtualenvs/mapstory/bin/python
Python Version: 2.7.6
Python Path: ['/srv/git/mapstory/mapstory-geonode', '/usr/bin', '/home/mapstory/.virtualenvs/mapstory/src/django-mailer', '/home/mapstory/.virtualenvs/mapstory/src/icon-commons', '/srv/git/mapstory/geonode', '/home/mapstory/.virtualenvs/mapstory/src/osgeo-importer', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/plat-x86_64-linux-gnu', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-tk', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-old', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/pymodules/python2.7', '/srv/git/mapstory/mapstory-geonode', '/srv/git/mapstory/mapstory-geonode']
Server time: Fri, 3 Jun 2016 05:51:32 -0500
Installed Applications:
('django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.sites',
'django.contrib.admin',
'django.contrib.sitemaps',
'django.contrib.staticfiles',
'django.contrib.messages',
'django.contrib.humanize',
'django.contrib.gis',
'pagination',
'taggit',
'friendlytagloader',
'geoexplorer',
'leaflet',
'django_extensions',
'autocomplete_light',
'mptt',
'modeltranslation',
'djcelery',
'pinax_theme_bootstrap_account',
'pinax_theme_bootstrap',
'django_forms_bootstrap',
'account',
'avatar',
'dialogos',
'agon_ratings',
'notification',
'announcements',
'actstream',
'user_messages',
'tastypie',
'polymorphic',
'guardian',
'geonode.people',
'geonode.base',
'geonode.layers',
'geonode.maps',
'geonode.proxy',
'geonode.security',
'geonode.social',
'geonode.catalogue',
'geonode.documents',
'geonode.api',
'geonode.groups',
'geonode.services',
'geonode.annotations',
'geonode.geoserver',
'geonode.upload',
'geonode.tasks',
'mapstory',
'django.contrib.webdesign',
'django.contrib.sites',
'geonode.contrib.geogig',
'geonode.contrib.collections',
'geonode.contrib.favorite',
'icon_commons',
'maploom',
'haystack',
'mailer',
'django_slack',
'fluent_comments',
'crispy_forms',
'threadedcomments',
'django_comments',
'djcelery',
'osgeo_importer',
'mapstory.apps.boxes',
'mapstory.apps.flag',
'social_auth',
'provider',
'provider.oauth2')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.locale.LocaleMiddleware',
'pagination.middleware.PaginationMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
 112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/views/decorators/csrf.py" in wrapped_view
 57.         return view_func(*args, **kwargs)
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/tastypie/resources.py" in wrapper
 220.                 return self.error_response(request, data, response_class=http.HttpBadRequest)
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/tastypie/resources.py" in error_response
 1210.             serialized = self.serialize(request, errors, desired_format)
File "/srv/git/mapstory/geonode/geonode/api/api.py" in serialize
 342.         return super(OwnersResource, self).serialize(request, data, format, options)
File "/srv/git/mapstory/geonode/geonode/api/api.py" in serialize
 103.         return super(TypeFilteredResource, self).serialize(request, data, format, options)
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/tastypie/resources.py" in serialize
 364.         return self._meta.serializer.serialize(data, format, options)
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/tastypie/serializers.py" in serialize
 200.         serialized = getattr(self, "to_%s" % desired_format)(bundle, options)
File "/srv/git/mapstory/geonode/geonode/api/api.py" in to_json
 68.         for item in data['objects']:

Exception Type: KeyError at /api/owners/
Exception Value: 'objects'
Request information:
GET:
city = u'london'
limit = u'100'
offset = u'0'

POST: No POST data

FILES: No FILES data

COOKIES:
csrftoken = '11ZlFmDf8ku8MOrjEB7YeIovf4oMWB68'

META:
HTTP_ACCEPT = 'application/json, text/plain, */*'
HTTP_REFERER = 'http://mapstory.org/search/?limit=100&offset=0'
SERVER_PROTOCOL = 'HTTP/1.0'
SERVER_SOFTWARE = 'gunicorn/17.5'
SCRIPT_NAME = u''
HTTP_X_CSRFTOKEN = '11ZlFmDf8ku8MOrjEB7YeIovf4oMWB68'
wsgi.input = <gunicorn.http.body.Body object at 0x7f8ff06ea490>
REQUEST_METHOD = 'GET'
HTTP_HOST = 'mapstory.org'
PATH_INFO = u'/api/owners/'
wsgi.multithread = False
QUERY_STRING = 'city=london&limit=100&offset=0'
HTTP_CONNECTION = 'close'
HTTP_X_REAL_IP = '86.185.212.46'
HTTP_X_SCHEME = 'http'
HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2755.0 Safari/537.36'
wsgi.version = 
HTTP_COOKIE = 'csrftoken=11ZlFmDf8ku8MOrjEB7YeIovf4oMWB68'
RAW_URI = '/api/owners/?city=london&limit=100&offset=0'
REMOTE_ADDR = '127.0.0.1'
wsgi.run_once = False
wsgi.errors = <open file '<stderr>', mode 'w' at 0x7f9004e481e0>
wsgi.multiprocess = True
HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.8'
wsgi.url_scheme = 'http'
gunicorn.socket = <socket._socketobject object at 0x7f8feff49590>
SERVER_NAME = 'mapstory.org'
SERVER_PORT = '80'
wsgi.file_wrapper = ''
CSRF_COOKIE = u'11ZlFmDf8ku8MOrjEB7YeIovf4oMWB68'
HTTP_ACCEPT_ENCODING = 'gzip, deflate, sdch'
REMOTE_PORT = '51062'

Settings:
Using settings module mapstory.settings
CASCADE_WORKSPACE = 'geonode'
MONTH_DAY_FORMAT = 'F j'
DEFAULT_WORKSPACE = 'geonode'
ACCOUNT_USER_DISPLAY = ''
DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': 'mapstory', 'TEST_MIRROR': None, 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'America/Chicago', 'TEST_COLLATION': None, 'TEST_CHARSET': None, 'PORT': '5432', 'HOST': '10.145.57.109', 'USER': 'mapstory', 'TEST_NAME': None, 'PASSWORD': u'********************', 'OPTIONS': {}}, 'datastore': {'ENGINE': 'django.contrib.gis.db.backends.postgis', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': 'mapstory_data', 'TEST_MIRROR': None, 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'America/Chicago', 'TEST_COLLATION': None, 'TEST_CHARSET': None, 'PORT': '5432', 'HOST': '10.145.57.109', 'USER': 'mapstory', 'TEST_NAME': None, 'PASSWORD': u'********************', 'OPTIONS': {}}}
AWS_QUERYSTRING_AUTH = False
CELERY_CREATE_MISSING_QUEUES = True
GEONODE_CONTRIB_APPS = 
CSRF_COOKIE_SECURE = False
CELERY_DEFAULT_QUEUE = 'default'
UPLOADER = {'OPTIONS': {'TIME_ENABLED': True, 'GEOGIG_ENABLED': True}, 'BACKEND': 'geonode.importer'}
LANGUAGE_CODE = 'en'
LICENSES = {'ENABLED': True, 'DETAIL': 'above', 'METADATA': 'verbose'}
MANAGERS = 
DOWNLOAD_FORMATS_METADATA = ['Atom', 'DIF', 'Dublin Core', 'ebRIM', 'FGDC', 'ISO']
BROKER_URL = 'amqp://mapstory:password@localhost/mapstory'
ACCOUNT_ACTIVATION_DAYS = 3
IGNORABLE_404_URLS = 
CELERY_DEFA…

**Comment by Coop56** [comment]
ERROR (EXTERNAL IP): Internal Server Error: /account/confirm_email/9922b1680b34c729117b28473f9dc8bd0449e003cf675f872e6b10f518722a75/
Internal Server Error: /account/confirm_email/9922b1680b34c729117b28473f9dc8bd0449e003cf675f872e6b10f518722a75/

NoReverseMatch at /account/confirm_email/9922b1680b34c729117b28473f9dc8bd0449e003cf675f872e6b10f518722a75/
Reverse for 'auth_login' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

Request Method: POST
Request URL: http://mapstory.org/account/confirm_email/9922b1680b34c729117b28473f9dc8bd0449e003cf675f872e6b10f518722a75/
Django Version: 1.6.10
Python Executable: /home/mapstory/.virtualenvs/mapstory/bin/python
Python Version: 2.7.6
Python Path: ['/srv/git/mapstory/mapstory-geonode', '/usr/bin', '/home/mapstory/.virtualenvs/mapstory/src/django-mailer', '/home/mapstory/.virtualenvs/mapstory/src/icon-commons', '/srv/git/mapstory/geonode', '/home/mapstory/.virtualenvs/mapstory/src/osgeo-importer', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/plat-x86_64-linux-gnu', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-tk', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-old', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/pymodules/python2.7', '/srv/git/mapstory/mapstory-geonode', '/srv/git/mapstory/mapstory-geonode']
Server time: Thu, 2 Jun 2016 12:01:27 -0500
Installed Applications:
('django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.sites',
'django.contrib.admin',
'django.contrib.sitemaps',
'django.contrib.staticfiles',
'django.contrib.messages',
'django.contrib.humanize',
'django.contrib.gis',
'pagination',
'taggit',
'friendlytagloader',
'geoexplorer',
'leaflet',
'django_extensions',
'autocomplete_light',
'mptt',
'modeltranslation',
'djcelery',
'pinax_theme_bootstrap_account',
'pinax_theme_bootstrap',
'django_forms_bootstrap',
'account',
'avatar',
'dialogos',
'agon_ratings',
'notification',
'announcements',
'actstream',
'user_messages',
'tastypie',
'polymorphic',
'guardian',
'geonode.people',
'geonode.base',
'geonode.layers',
'geonode.maps',
'geonode.proxy',
'geonode.security',
'geonode.social',
'geonode.catalogue',
'geonode.documents',
'geonode.api',
'geonode.groups',
'geonode.services',
'geonode.annotations',
'geonode.geoserver',
'geonode.upload',
'geonode.tasks',
'mapstory',
'django.contrib.webdesign',
'django.contrib.sites',
'geonode.contrib.geogig',
'geonode.contrib.collections',
'geonode.contrib.favorite',
'icon_commons',
'maploom',
'haystack',
'mailer',
'django_slack',
'fluent_comments',
'crispy_forms',
'threadedcomments',
'django_comments',
'djcelery',
'osgeo_importer',
'mapstory.apps.boxes',
'mapstory.apps.flag',
'social_auth',
'provider',
'provider.oauth2')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.locale.LocaleMiddleware',
'pagination.middleware.PaginationMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
 112.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/views/generic/base.py" in view
 69.             return self.dispatch(request, *args, **kwargs)
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
 87.         return handler(request, *args, **kwargs)
File "/srv/git/mapstory/mapstory-geonode/mapstory/views.py" in post
 673.         return redirect(redirect_url)
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/shortcuts/__init__.py" in redirect
 78.     return redirect_class(resolve_url(to, *args, **kwargs))
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/shortcuts/__init__.py" in resolve_url
 151.         return urlresolvers.reverse(to, args=args, kwargs=kwargs)
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in reverse
 536.     return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in _reverse_with_prefix
 456.                              (lookup_view_s, args, kwargs, len(patterns), patterns))

Exception Type: NoReverseMatch at /account/confirm_email/9922b1680b34c729117b28473f9dc8bd0449e003cf675f872e6b10f518722a75/
Exception Value: Reverse for 'auth_login' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []
Request information:
GET: No GET data

POST:
csrfmiddlewaretoken = u'FLId6Twj1IlsjVwVyqzRAeqhb5nsFrhr'

FILES: No FILES data

COOKIES:
__utmz = '195813168.1464882090.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
__utmt = '1'
csrftoken = 'FLId6Twj1IlsjVwVyqzRAeqhb5nsFrhr'
__utma = '195813168.1569242957.1464882090.1464882090.1464886779.2'
__utmb = '195813168.5.10.1464886779'
__utmc = '195813168'

META:
CONTENT_LENGTH = '52'
SERVER_NAME = 'mapstory.org'
CONTENT_TYPE = 'application/x-www-form-urlencoded'
HTTP_REFERER = 'http://mapstory.org/account/confirm_email/9922b1680b34c729117b28473f9dc8bd0449e003cf675f872e6b10f518722a75/'
SERVER_PORT = '80'
SERVER_PROTOCOL = 'HTTP/1.0'
SERVER_SOFTWARE = 'gunicorn/17.5'
SCRIPT_NAME = u''
REMOTE_PORT = '45124'
wsgi.input = <gunicorn.http.body.Body object at 0x7f8ff1c0ded0>
REQUEST_METHOD = 'POST'
HTTP_HOST = 'mapstory.org'
PATH_INFO = u'/account/confirm_email/9922b1680b34c729117b28473f9dc8bd0449e003cf675f872e6b10f518722a75/'
HTTP_ORIGIN = 'http://mapstory.org'
wsgi.multithread = False
QUERY_STRING = ''
HTTP_CONNECTION = 'close'
HTTP_CACHE_CONTROL = 'max-age=0'
HTTP_X_REAL_IP = '24.43.166.245'
HTTP_X_SCHEME = 'http'
HTTP_USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36'
wsgi.version = 
HTTP_COOKIE = '__utmt=1; csrftoken=FLId6Twj1IlsjVwVyqzRAeqhb5nsFrhr; __utma=195813168.1569242957.1464882090.1464882090.1464886779.2; __utmb=195813168.5.10.1464886779; __utmc=195813168; __utmz=195813168.1464882090.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
RAW_URI = '/account/confirm_email/9922b1680b34c729117b28473f9dc8bd0449e003cf675f872e6b10f518722a75/'
REMOTE_ADDR = '127.0.0.1'
wsgi.run_once = False
wsgi.errors = <open file '<stderr>', mode 'w' at 0x7f9004e481e0>
wsgi.multiprocess = True
HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.8'
wsgi.url_scheme = 'http'
gunicorn.socket = <socket._socketobject object at 0x7f8fefc0c750>
HTTP_DNT = '1'
HTTP_UPGRADE_INSECURE_REQUESTS = '1'
HTTP_ACCEPT = 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
wsgi.file_wrapper = ''
CSRF_COOKIE = u'FLId6Twj1IlsjVwVyqzRAeqhb5nsFrhr'
HTTP_ACCEPT_ENCODING = 'gzip, deflate'

Settings:
Using settings module mapstory.settings
CASCADE_WORKSPACE = 'geonode'
MONTH_DAY_FORMAT = 'F j'
DEFAULT_WORKSPACE = 'geonode'
ACCOUNT_USER_DISPLAY = ''
DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': 'mapstory', 'TEST_MIRROR': None, 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'America/Chicago', 'TEST_COLLATION': None, 'T…

**Comment by Coop56** [comment]
I've created tickets for all of the errors that I see happening often in the dev_ops chat and stripped them of any private information.  The tickets are all listed below.

https://github.com/MapStory/mapstory/issues/1630
https://github.com/MapStory/mapstory/issues/1631
https://github.com/MapStory/mapstory/issues/1632
