### ISSUE TITLE
 Password reset page it said to email "admin@example.com" for further help

### ISSUE THREAD

**Issue by davisc** [MapStory/mapstory-meta#1594]

**Comment by emilyashley** [comment]
The password reset email is correct on demo. What needs to be done to get the `theme_account_contact_email` in `local_settings.py` changed on production?

**Comment by emilyashley** [comment]
For future reference -
places `theme_account_contact_email` can be defined:
- mapstory-geonode/scripts/provision/host_vars  -   demo.yml & prod.yml as `email_host_user`
- mapstory-geonode/scripts/provision/roles/web/files/local_settings.py.j2
- mapstory-geonode/settings/local_settings.py 
  - (written via /provision/roles/web/tasks `write project local settings`)
- geonode/settings.py

template:
- geonode/templates/account/password_reset.html
