### ISSUE TITLE
Create Embed / Smaller Size of Viewer Page from Large Viewer Page

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory-meta#1597]
- [x] Fix the embedded view so that it points to the new /story/{{resource.id}}/view URL
- [x] Fix the URL given to users so that they can embed stories again with the new /story/ URL structure.
- [x] Setup responsiveness based on the window size where the sidebar goes to 30% of the total real estate on smaller screens.

**Comment by reynalddizon** [comment]
mockup: [embed_view.pdf](https://github.com/MapStory/mapstory/files/294192/embed_view.pdf)

**Comment by Coop56** [comment]
This is done and live on demo @jonpmarino @reynalddizon
