### ISSUE TITLE
Add "What's Hot" lists back to the Explore page

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1598]
Please refer to #1610 for the latest mockup

**Comment by Coop56** [comment]
Recently Added, Top Rated and Most Viewed are all working.  @reynalddizon @jonpmarino @davisc we need to talk about the Editor's Pick section.  Is there currently a mechanism for someone to pick items as Editor's pick and set some sort of variable to true?  If not we're going to need to build that functionality, a dashboard for admins to pick which stories and layers you want showcased and remove ones that you no longer want showcased etc.  That warrants an issue of it's own I think in another sprint.  Thoughts?

Here's the issue that solves three of the four - https://github.com/MapStory/mapstory-geonode/commit/f68c5c215cc9126dd3d93acbe8a189075514c99a

**Comment by jonpmarino** [comment]
@coop56 i'm not very worried about Editors Picks since we can already feature some stuff on home page. Lets create its own issue and table for future, yeah.

**Comment by Coop56** [comment]
I'm closing this one based on the standup conversation - @jonpmarino if you want to create a new backburner issue on Editor's pick please do.
