### ISSUE TITLE
Metadata edit form guide

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1599]
Add a link to a metadata creation guide. Tagging @jonpmarino for reference

**Comment by jonpmarino** [comment]
![learnmoremetadata](https://cloud.githubusercontent.com/assets/2573761/16250845/ba0b89ac-37ee-11e6-8127-83c092b0b45a.jpg)
Just need a link in the layer settings modal as depicted in the screenshot. Link can go to http://wiki.mapstory.org/wiki/MapStory_Uploader#Creating_Quality_Metadata
