### ISSUE TITLE
Detail pages CSS updates

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1607]
Please update this 
a:hover, a:focus, a:active {
color: #333;
text-decoration: underline;
}

Detail pages CSS updates

.page-title{
display: block;
overflow: hidden;
text-overflow: ellipsis;
white-space: nowrap;
font-weight: 600;
margin: 0;
line-height: 1.2em;
}

.btn-detailpage:hover, .btn-detailpage:active {
  background-color: #333;
  color: #eee;
}

add “side-column” next to col-lg-3 class for sidebar, then add this rule:
.side-column a:hover {
    color: #333;
    text-decoration: underline;
}

then update this:

.side-column-items li {
  color: #666;
  margin: 1px 15px;
  font-size: 0.7em;
  font-weight: 600;
}
# embedded_map {

width: 850px;
height: 450px;
padding: 20px 0;
}

.tab-content {
padding: 10px;
color: #444;
font-size: 15px;
font-weight: 300;
}

**Comment by Coop56** [comment]
@reynalddizon This is done - pushing the changes now.
