### ISSUE TITLE
Idea for the future: Add a "View StoryLayer data as a table" button on storylayer detail page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1617]
this will generate a table view similar to the one you can see in edit mode.

Will be helpful in giving users a sense of features before they decide to make edits or appends.

**Comment by glynnis** [comment]
Closing this. I think this will get addressed as we do the Layer Editing redesign work.

If this is still relevant, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.
