### ISSUE TITLE
ERROR (EXTERNAL IP): Internal Server Error: /maps/18652 list index out of range

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory-meta#1631]
ERROR (EXTERNAL IP): Internal Server Error: /maps/18652
ERROR (EXTERNAL IP): Internal Server Error: /maps/18652
Internal Server Error: /maps/18652

IndexError at /maps/18652
list index out of range

Request Method: GET
Request URL: http://mapstory.org/maps/18652
Django Version: 1.6.10
Python Executable: /home/mapstory/.virtualenvs/mapstory/bin/python
Python Version: 2.7.6
Python Path: ['/srv/git/mapstory/mapstory-geonode', '/usr/bin', '/home/mapstory/.virtualenvs/mapstory/src/django-mailer', '/home/mapstory/.virtualenvs/mapstory/src/icon-commons', '/srv/git/mapstory/geonode', '/home/mapstory/.virtualenvs/mapstory/src/osgeo-importer', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/plat-x86_64-linux-gnu', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-tk', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-old', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/pymodules/python2.7', '/srv/git/mapstory/mapstory-geonode', '/srv/git/mapstory/mapstory-geonode']
Server time: Fri, 10 Jun 2016 10:05:55 -0500

Traceback:
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "/srv/git/mapstory/geonode/geonode/maps/views.py" in map_detail
2.         config = map_obj.viewer_json(request.user)
   File "/srv/git/mapstory/geonode/geonode/utils.py" in viewer_json
3.                     str(int(keys[-1]) + 1)] = settings.MAP_BASELAYERS[0]['source']

Exception Type: IndexError at /maps/18652
Exception Value: list index out of range

**Comment by glynnis** [comment]
Closing this. If this is still relevant and can be reproduced, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017. Be sure to follow [the Bug Report guidelines](https://github.com/MapStory/mapstory/wiki/How-to-report-a-bug).
