### ISSUE TITLE
ERROR (EXTERNAL IP): Internal Server Error: /initiatives/{{ item.detail_url}}

### ISSUE THREAD

**Issue by Coop56** [MapStory/mapstory-meta#1632]
ERROR (EXTERNAL IP): Internal Server Error: /initiatives/{{ item.detail_url}}
Internal Server Error: /initiatives/{{ item.detail_url}}

DoesNotExist at /initiatives/{{ item.detail_url}}
GroupProfile matching query does not exist.

Request Method: GET
Request URL: http://t2.mapstory.org/initiatives/%7B%7B%20item.detail_url%7D%7D
Django Version: 1.6.10
Python Executable: /home/mapstory/.virtualenvs/mapstory/bin/python
Python Version: 2.7.6
Python Path: ['/srv/git/mapstory/mapstory-geonode', '/usr/bin', '/home/mapstory/.virtualenvs/mapstory/src/django-mailer', '/home/mapstory/.virtualenvs/mapstory/src/icon-commons', '/srv/git/mapstory/geonode', '/home/mapstory/.virtualenvs/mapstory/src/osgeo-importer', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/plat-x86_64-linux-gnu', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-tk', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-old', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/pymodules/python2.7', '/srv/git/mapstory/mapstory-geonode', '/srv/git/mapstory/mapstory-geonode']
Server time: Fri, 10 Jun 2016 01:19:06 -0500

Traceback:
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "/srv/git/mapstory/mapstory-geonode/mapstory/views.py" in initiative_detail
2.     group = GroupProfile.objects.get(slug=slug)
   File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/db/models/manager.py" in get
3.         return self.get_queryset().get(_args, *_kwargs)
   File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/db/models/query.py" in get
4.                 self.model._meta.object_name)

Exception Type: DoesNotExist at /initiatives/{{ item.detail_url}}
Exception Value: GroupProfile matching query does not exist.

**Comment by glynnis** [comment]
Closing this. If this is still relevant and can be reproduced, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017. Be sure to follow [the Bug Report guidelines](https://github.com/MapStory/mapstory/wiki/How-to-report-a-bug).
