### ISSUE TITLE
Integrate Zendesk help center link

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1636]
StoryScapes will use an open source alternative (likely OSticket.com). Integrating Zendesk into mapstory will help us model this. Zendesk provides an FAQ, community forums, and a user ticket form.

Here is the link: https://mapstory.zendesk.com

Based on existing site, it should be integrated in these ways:

> "Help" link from the profile drop-down on top-right of site
> "Help Center" link from the mapstory.org homepage
> "Help" link in the footer (this should be changed from current 'help.mapstory.org' to just say Help and link to the zendesk link)
> icon next Github icon in the social media links on footer currently links to help.mapstory.org. Should link to Zendesk.
> If we keep the 'Ask for Help' link in importer, it should go here

**Comment by Coop56** [comment]
No longer relevant, closing this issue.
