### ISSUE TITLE
Time info on StoryLayer playback doesn't advance in cumulative mode

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1637]
using this storylayer as a test: https://demo.mapstory.org/layers/geonode:prisons_okktakh

In Instant and Ranged mode, the time information changes as the layer advances. In cumulative mode it remains on the time of the first feature in the layer.

**Comment by glynnis** [comment]
Closing this. If this is still relevant and can be reproduced, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017. Be sure to follow [the Bug Report guidelines](https://github.com/MapStory/mapstory/wiki/How-to-report-a-bug).
