### ISSUE TITLE
Confirmation email upon creating new account generates link with http and https

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1639]
(testing on beta on June 21, 2016)
![activation_email](https://cloud.githubusercontent.com/assets/2573761/16235709/d31b29ac-37a3-11e6-8f7e-dae5f2ece448.jpg)

**Comment by glynnis** [comment]
This is fixed. Closing.

![screen shot 2016-12-16 at 4 38 54 pm](https://cloud.githubusercontent.com/assets/1529366/21280836/2a044032-c3ae-11e6-89ed-2caa54802fdf.png)
