### ISSUE TITLE
Amend text on Get Started section of home

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1643]
(goal is to make this section seem less like a intro/how to, which is what Get Skills is supposed to be)

Replace "MapStory is an open platform for organizing our knowledge about how the world changes over time and space. Click on a link to the right, and learn how you can start contributing observations of your own."

with:

"MapStory is the world's online atlas. Working together, our global community of mapstorytellers is collecting data, making edits, and composing mapstories that help us all better understand our changing world. Click to the right to meet some of them."

**Comment by emilyashley** [comment]
Would this be the same text for both sites?

Note for self, this currently lives [here](https://github.com/MapStory/mapstory-geonode/blob/150323418fdae4eea4dc675ae4fd7de74f3279fd/mapstory/templates/index.html#L157)

**Comment by jonpmarino** [comment]
Outdated. Closing.
