### ISSUE TITLE
Favoriting your own StoryLayer causes the favorites filter in mini-explore to break

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1675]
I have 13 favorites on my profile:

![favorites](https://cloud.githubusercontent.com/assets/2573761/16637291/33e8fc6e-43ac-11e6-968f-a5338f8fb33b.jpg)

But, when I enter composer and click "my favorites" tab in mini-explore, none appear. Also an error is thrown (noted below). 

![grab_favorites_filter](https://cloud.githubusercontent.com/assets/2573761/16637354/949579fc-43ac-11e6-9ef9-be6706a82a6a.jpg)

ERROR (EXTERNAL IP): Internal Server Error: /api/favorites/
Internal Server Error: /api/favorites/

AttributeError at /api/favorites/
'NoneType' object has no attribute 'title'

Request Method: GET
Request URL: http://mapstory.org/api/favorites/?content_type=42&limit=100
Django Version: 1.6.10
Python Executable: /home/mapstory/.virtualenvs/mapstory/bin/python
Python Version: 2.7.6
Python Path: ['/srv/git/mapstory/mapstory-geonode', '/usr/bin', '/home/mapstory/.virtualenvs/mapstory/src/django-mailer', '/home/mapstory/.virtualenvs/mapstory/src/icon-commons', '/srv/git/mapstory/geonode', '/home/mapstory/.virtualenvs/mapstory/src/osgeo-importer', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/plat-x86_64-linux-gnu', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-tk', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-old', '/home/mapstory/.virtualenvs/mapstory/lib/python2.7/lib-dynload', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/pymodules/python2.7', '/srv/git/mapstory/mapstory-geonode', '/srv/git/mapstory/mapstory-geonode']
Server time: Wed, 6 Jul 2016 18:04:12 -0500
Installed Applications:
('django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.sites',
'django.contrib.admin',
'django.contrib.sitemaps',
'django.contrib.staticfiles',
'django.contrib.messages',
'django.contrib.humanize',
'django.contrib.gis',
'pagination',
'taggit',
'friendlytagloader',
'geoexplorer',
'leaflet',
'django_extensions',
'autocomplete_light',
'mptt',
'modeltranslation',
'djcelery',
'pinax_theme_bootstrap_account',
'pinax_theme_bootstrap',
'django_forms_bootstrap',
'account',
'avatar',
'dialogos',
'agon_ratings',
'notification',
'announcements',
'actstream',
'user_messages',
'tastypie',
'polymorphic',
'guardian',
'geonode.people',
'geonode.base',
'geonode.layers',
'geonode.maps',
'geonode.proxy',
'geonode.security',
'geonode.social',
'geonode.catalogue',
'geonode.documents',
'geonode.api',
'geonode.groups',
'geonode.services',
'geonode.annotations',
'geonode.geoserver',
'geonode.upload',
'geonode.tasks',
'mapstory',
'django.contrib.webdesign',
'django.contrib.sites',
'geonode.contrib.geogig',
'geonode.contrib.collections',
'geonode.contrib.favorite',
'icon_commons',
'maploom',
'haystack',
'mailer',
'django_slack',
'fluent_comments',
'crispy_forms',
'threadedcomments',
'django_comments',
'djcelery',
'osgeo_importer',
'mapstory.apps.boxes',
'mapstory.apps.flag',
'social_auth',
'provider',
'provider.oauth2')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
'django.contrib.sessions.middleware.SessionMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.locale.LocaleMiddleware',
'pagination.middleware.PaginationMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware')

Traceback:
File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/tastypie/resources.py" in wrapper
1.                 response = callback(request, _args, *_kwargs)
   File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/tastypie/resources.py" in dispatch_list
2.         return self.dispatch('list', request, **kwargs)
   File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/tastypie/resources.py" in dispatch
3.         response = method(request, **kwargs)
   File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/tastypie/resources.py" in get_list
4.             bundles.append(self.full_dehydrate(bundle, for_list=True))
   File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/tastypie/resources.py" in full_dehydrate
5.             bundle.data[field_name] = field_object.dehydrate(bundle, for_list=for_list)
   File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/tastypie/fields.py" in dehydrate
6.                 raise ApiFieldError("The model '%r' has an empty attribute '%s' and doesn't allow a null value." % (previous_obj, attr))
   File "/home/mapstory/.virtualenvs/mapstory/local/lib/python2.7/site-packages/django/db/models/base.py" in **repr**
7.             u = six.text_type(self)
   File "/srv/git/mapstory/geonode/geonode/contrib/favorite/models.py" in **unicode**
8.         return "Favorite: {}, {}, {}".format(self.content_object.title, self.content_type, self.user)

Exception Type: AttributeError at /api/favorites/
Exception Value: 'NoneType' object has no attribute 'title'
Request information:
GET:
limit = u'100'
content_type = u'42'

POST: No POST data

FILES: No FILES data

COOKIES:
__utmz = '195813168.1467829368.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)'
sessionid = 'kssxhsfwq9r8jwan1mkrocrfi6mgc26s'
csrftoken = 'yeca97teagGzAQntGybzQIVehVUG9qKk'
__utma = '195813168.1861029453.1467829368.1467832311.1467841309.3'
__utmb = '195813168.26.10.1467841309'
__utmc = '195813168'

META:
HTTP_AUTHORIZATION = ''
HTTP_ACCEPT = 'application/json, text/plain, _/_'
HTTP_X_REQUESTED_WITH = 'XMLHttpRequest'
SERVER_PROTOCOL = 'HTTP/1.0'
SERVER_SOFTWARE = 'gunicorn/17.5'
SCRIPT_NAME = u''
REMOTE_PORT = '47366'
wsgi.input = <gunicorn.http.body.Body object at 0x7f188857ab10>
REQUEST_METHOD = 'GET'
HTTP_HOST = 'mapstory.org'
PATH_INFO = u'/api/favorites/'
wsgi.multithread = False
QUERY_STRING = 'content_type=42&limit=100'
HTTP_CONNECTION = 'close'
HTTP_X_REAL_IP = '108.18.32.157'
HTTP_X_SCHEME = 'https'
HTTP_USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36'
wsgi.version = 
HTTP_REFERER = 'https://mapstory.org/maploom/maps/new?tour='
RAW_URI = '/api/favorites/?content_type=42&limit=100'
REMOTE_ADDR = '127.0.0.1'
wsgi.run_once = False
wsgi.errors = <open file '<stderr>', mode 'w' at 0x7f189c8051e0>
wsgi.multiprocess = True
HTTP_ACCEPT_LANGUAGE = 'en-US,en;q=0.8,fr;q=0.6'
wsgi.url_scheme = 'http'
gunicorn.socket = <socket._socketobject object at 0x7f1885f09ec0>
SERVER_NAME = 'mapstory.org'
SERVER_PORT = '80'
wsgi.file_wrapper = ''
CSRF_COOKIE = u'yeca97teagGzAQntGybzQIVehVUG9qKk'
HTTP_ACCEPT_ENCODING = 'gzip, deflate, sdch'
HTTP_COOKIE = 'sessionid=kssxhsfwq9r8jwan1mkrocrfi6mgc26s; __utma=195813168.1861029453.1467829368.1467832311.1467841309.3; __utmb=195813168.26.10.1467841309; __utmc=195813168; __utmz=195813168.1467829368.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); csrftoken=yeca97teagGzAQntGybzQIVehVUG9qKk'

Settings:
Using settings module mapstory.settings
CASCADE_WORKSPACE = 'geonode'
MONTH_DAY_FORMAT = 'F j'
DEFAULT_WORKSPACE = 'geonode'
ACCOUNT_USER_DISPLAY = ''
DATABASES = {'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': 'mapstory', 'TEST_MIRROR': None, 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'America/Chicago', 'TEST_COLLATION': None, 'TEST_CHARSET': None, 'PORT': '5432', 'HOST': '10.145.57.109', 'USER': 'mapstory', 'TEST_NAME': None, 'PASSWORD': u'*******************_', 'OPTIONS': {}}, 'datastore': {'ENGINE': 'django.contrib.gis.db.backends.postgis', 'AUTOCOMMIT': True, 'ATOMIC_REQUESTS': False, 'NAME': 'mapstory_data', 'TEST_MIRROR': None, 'CONN_MAX_AGE': 0, 'TIME_ZONE': 'America/Chicago', 'TEST_COLLATION': None, 'TEST_CHARSET': None, 'PORT': '5432', 'HOST': '10.145.57.109', 'USER': 'mapstory', 'TEST_NAME': None, 'PASSWORD': u'**_*****************', 'OPTIONS': {}}}
AWS_QUERYSTRING_AUTH = False
CELERY_CREATE_MISSING_QUEUES = True
GEONODE_CON…

**Comment by jonpmarino** [comment]
Note, I had one of my own StoryLayers as a favorite. When I deleted it from my favorites and refreshed composer and went to the Favorites filter in mini-explore, it worked. So the issue is favoriting your own layers causes mini-explore to break.

**Comment by glynnis** [comment]
Closing this. If this is still relevant and can be reproduced, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017. 

Be sure to follow [the Bug Report guidelines](https://github.com/MapStory/mapstory/wiki/How-to-report-a-bug).
