### ISSUE TITLE
Date represented in playback is 100 years different than date in data uploaded

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1679]
uploaded data with these dates. Playback on storylayer shows data as 2060 instead of 1960. Here's the data, https://docs.google.com/spreadsheets/d/17Dp_PTIVvXC7fmU53MEKwD0AMjNI0lUT2RTpooMmAJk/edit?usp=sharing. Here's the storylayer: https://mapstory.org/layers/geonode:sitins
2/1/1960
2/8/1960
2/8/1960
2/8/1960
2/9/1960
2/9/1960
2/9/1960
2/10/1960
2/11/1960
2/12/1960
2/12/1960
2/13/1960
2/13/1960
2/13/1960
2/13/1960
2/13/1960
2/13/1960
2/13/1960
2/13/1960
2/13/1960
2/13/1960
2/13/1960
2/13/1960
3/15/1960
3/15/1960
3/15/1960
4/1/1960
4/21/1960
7/25/1960
2/1/1961
5/28/1963

**Comment by glynnis** [comment]
Closing this. If this is still relevant and can be reproduced, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017. 

Be sure to follow [the Bug Report guidelines](https://github.com/MapStory/mapstory/wiki/How-to-report-a-bug).
