### ISSUE TITLE
Reset password requires user to only send email to account associated with username

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1684]
Right now we let users request a link to reset password using ANY email address. But, if a user for some reason has it sent to an email address that IS NOT associated with the account, the email still gets sent and the user feels like everything worked. But in reality they cannot log in with the new password. 

SOLUTION - we need to tell the user "be sure to send the reset link to the email address associated with your account". OR, ideally we would not allow the reactivate email to be sent to an email that is not associated with the account.

**Comment by emilyashley** [comment]
duplicate #1655
