### ISSUE TITLE
Change "layer settings" modal to be 'Metadata'

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1702]

**Comment by emilyashley** [comment]
<img width="636" alt="screen shot 2016-07-20 at 5 50 46 pm" src="https://cloud.githubusercontent.com/assets/15912063/17005887/87c2e3bc-4ea2-11e6-846a-1bbf1c58f87a.png">

Is this what you meant?
Will be merged with the sprints-less branch.
