### ISSUE TITLE
Change "abstract" tab on storylayer detail page and make sure the rest of the metadata fields are exposed there

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1703]
fields are Summary, Data Quality Statement, Data Source and Purpose

**Comment by emilyashley** [comment]
<img width="1314" alt="screen shot 2016-07-20 at 5 54 57 pm" src="https://cloud.githubusercontent.com/assets/15912063/17005956/1f9c5e70-4ea3-11e6-97ce-747d26c853a0.png">

Re-instated metadata tab.
