### ISSUE TITLE
Profiles are not showing storylayers and mapstories created by storytellers

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1710]
gotten this report from a few users. can confirm on my account too. Profiles aren't showing any of our storylayers or mapstories.

I.E. 
https://mapstory.org/storyteller/jonpmarino/
https://mapstory.org/storyteller/cd.boundless/

**Comment by emilyashley** [comment]
I updated this in profile_detail by re-exposing the extrascript block template that wasn't rendering correctly in the html.
