### ISSUE TITLE
"Edit" button is gone from storylayer cards that have community version editing enabled.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1712]
If we aren't going to have an "edit" button the card, then we should remove the "use" button too and just for the user to click on the card and go to the Detail page before deciding to "edit" or "compose" there.

If we are going to have the "use" button on the card, we should also have the "edit" button. It should be all or nothing.

Also, should probably use the word "compose" instead of "use" to keep things consistent.

**Comment by Coop56** [comment]
No longer relevant, there's a view button on layers now that you can click and take you to the detail page and decide what to do from there.  Closing.
