### ISSUE TITLE
Update to Facebook Graph API 2.1?

### ISSUE THREAD

**Issue by drwelby** [MapStory/mapstory-meta#1723]
MapStory uses some Facebook api tools for OAuth login, and is sending me notices that the Graph API needs to be upgraded before the current version expires. I don't know if the Graph API is needed for the OAuth login, but in any case the Facebook API access should be moved to a current developer.

**Comment by Coop56** [comment]
This has been taken care of.  I have the Facebook API access now under a new application and I've updated it to the latest OAuth.
