### ISSUE TITLE
Layer Styling Features II

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1727]
**Legend**
- [ ] update the text color of legend to make it readable.

**Unique**
- [ ] Remove stroke color option (under Stroke panel) for line geometry. This aspect should be controlled by the rules
- [ ] Remove the upper bound of classes
- [ ] If number of classes exceed the number of colors in a palette, rules should interpolate within these colors.

**Choropleth**
- [ ] Fill transparency control is missing
- [ ] Line geometry should be supported
- [ ] Remove the upper bound of classes

**Graduated**
- [ ] Line geometry  should be supported. Graduated should control line's weight.
- [ ] Symbol fill color control is missing
- [ ] Symbol shape control is missing
- [ ] Symbol fill transparency is missing
- [ ] Default range minimum should not start with 0 as this setting messes up the first rule generated.

**Heat map**
- [ ] Hide this on MapStory
- [ ] For point and polygons, add an option for the stroke/border to be transparent/disabled.

**Labels**
- [ ] need to expose the other customization options and values for labels as specified in SLD cookbook. (GeoServer 2.9.x)

For Font settings: 
-- font family
-- font style (normal, italic, oblique)
-- font size
-- font weight (normal, bold)

For text placement:
-- anchor (Left: 0 to 1, Right: 0 to 1)
-- displacement
-- rotation

For text halo:
-- radius
-- halo.

-- [ ] remove the BIUSH buttons in the mockup.

**Comment by glynnis** [comment]
Closing this. Styling issues will be addressed in the composer/editor redesign. I'm planning to take stock of what's there, what's working/what's not, and what needs to be included as I begin design work.

If this is still relevant, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.
