### ISSUE TITLE
Attribute data type for CSV datasets

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1729]
Upon upload, all data columns in a CSV file automatically become string data columns. This is not the ideal situation for datasets that contain integers, long and double columns as string columns can not be detected by Choropleth and Graduated styles

Thoughts? @davisc @JWileczek

**Comment by davisc** [comment]
@reynalddizon there is no way to determine this without scanning all rows for each column to introspectively determine the datatype based on all of the values. This would be a task on upload/import.
