### ISSUE TITLE
Demo Theme cleanup

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1731]
- [x]  active tab indicator in profile page (blue)
- [x]  sign in button (blue)
- [x] Options text hover in Welcome modal in composer (orange)
- [x]  Profile button in composer sidebar (orange)
- [x] Sidebar expand/collapse button hover (orange)
- [x] View storylayer attribute table selected row highlight (orange)
- [x] Remove layer dialog box horizontal divider (brown)
- [x] Visibility and rearrange buttons hover for storylayers list (orange)
- [x] Btn-composer hover class in composer (orange). Ex: Update map bounds in storyboxes, save storypin, set chapter view.
- [x] .menu i:hover (orange). Example: question mark symbols for help
- [ ] Remove chapter modal header (brown)

**Comment by emilyashley** [comment]
Cool cool! Thanks Rey. Updated all of these immediately in the themes except for the Remove Chapter modal header. Looks like it's grey unless it's the only chapter in the story at which point the modal header reflects an error tone. What color would you prefer it?

**Comment by reynalddizon** [comment]
@emilyashley just make it #ddd to be consistent with other popup boxes. thanks!
