### ISSUE TITLE
IconCommons zip upload

### ISSUE THREAD

**Issue by reynalddizon** [MapStory/mapstory-meta#1732]
- [ ] There's a size limit for bulk upload of icons, we want to support massive collections. Ex: i tried uploading the entire emoji svg library, it failed.
- [ ] SVGs need to be put in a folder first before zipping to be uploaded. which is different from uploading zipped shapefiles in layer upload. we need to be consistent

**Comment by Coop56** [comment]
Moved to Jira, closing.
