### ISSUE TITLE
Storylayer URL should use a number, like MapStory URL

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1739]
MapStory URL currently uses the convention https://mapstory.org/story/12345.

StoryLayer URL currently uses https://mapstory.org/layers/geonode/Layer_Name.

We should change the StoryLayer URL so it uses a fixed number as well....i.e. https://mapstory.org/layers/12345.

This would give users a simple and unchanging reference point for StoryLayers...even if the layer name gets changed around at some point, the number will remain the same.

**Comment by emilyashley** [comment]
This question already made it on my radar so I'm :scissors::clipboard: my related notes on the topic:
- Both of these layer url conventions currently render correctly, as well as `storylayer/id`. All produce identical views.
- Changing a storylayer's name via the metadata form doesn't update its `detail_url` property via elastic search, so the < layername > in url persists as the original name in its `detail_url`. 
- I was considering listing a "permalink" in the layer detail share tab using the id url.
- Most of our layer & story links are generated from `detail_url` property which is assigned in it's respective geonode search_indexes.py  (note to @davisc : another case of `get_absolute_url` and a django `reverse`)

**Comment by Coop56** [comment]
I would disagree with making them use numbers.  If we want to get SEO traffic we're going to want the URL to be the layer name so that our data can actually come up in Google searches.

**Comment by ChristopherTucker** [comment]
Jeremiah,

Good point.  But, how will we deal with changing layer names? 

Chris
703-981-9373

**Comment by Coop56** [comment]
I think the best implementation for that would be to allow them to edit their permalink (URL) like Wordpress does.  So if they change the name of the layer they could also change the URL but by default it would remain the same URL as when it was originally uploaded.

https://codex.wordpress.org/Using_Permalinks

**Comment by Coop56** [comment]
Moved to Jira, closing.
