### ISSUE TITLE
error when removing layer (this.timeSpans is null)

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#174]
When I add conflicts twice, and then remove one of them I get:

this.timeSpans is null
http://localhost:8081/script/@/app/static/externals/TimeManager/trunk/lib/OpenLayers/TimeAgent.js
Line 126

**Comment by mpriour** [comment]
fixed in https://github.com/mpriour/TimeManager_OpenLayers-Addin/commit/60bffc51dc00baca1274524ec23ec21ec3805654
