### ISSUE TITLE
Evaluate performance of vs.js timeline component

### ISSUE THREAD

**Issue by davisc** [MapStory/mapstory-meta#1744]
Need to determine the maximum number of  items that can be added to the timeline and how ti affects the loading, playback, and UX of the story and layer viewer. 

I've tested a layer with 18,000 unique time intervals and the performance of the viewer was noticeably degraded. 

http://visjs.org/examples/timeline/other/performance.html

**Comment by jonpmarino** [comment]
Closing. In Jira.
