### ISSUE TITLE
On mapstory.org, clicking Journal on header leads me to error page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1754]
on 12/1/16, 

1. click Journal on header on mapstory.org
2. taken to this error page:

![screen shot 2016-12-01 at 12 36 34 pm](https://cloud.githubusercontent.com/assets/2573761/20809043/686085ba-b7ca-11e6-9c95-e6b01355d64e.jpg)

**Comment by Coop56** [comment]
This has been fixed, closing.
