### ISSUE TITLE
Bug: clicking on a Chapter in django-admin leads to an error page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1757]
to reproduce:

1. Enter django admin
2. go to MapStory Chapters
3. Click on a chapter
![screen shot 2016-12-02 at 7 03 43 pm](https://cloud.githubusercontent.com/assets/2573761/20855384/27bc0cde-b8c2-11e6-9088-5caa36b59762.jpg)

**Comment by glynnis** [comment]
Closing this. If this is still relevant and can be reproduced, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017. Be sure to follow [the Bug Report guidelines](https://github.com/MapStory/mapstory/wiki/How-to-report-a-bug).
