### ISSUE TITLE
Bug: unpublishing a layer in django admin leads to this page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1758]
1. entered django admin (using chrome)
2. went to StoryLayers
3. unclicked a "publish" box for layer MexicoMurdersJoined
4. sent to this page:

[screen shot 2016-12-04 at 4 30 07 pm](https://cloud.githubusercontent.com/assets/2573761/20869751/f5ed4db6-ba3e-11e6-85b5-136efe40e58e.jpg)

**Comment by glynnis** [comment]
Closing this. If this is still relevant and can be reproduced, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017. Be sure to follow [the Bug Report guidelines](https://github.com/MapStory/mapstory/wiki/How-to-report-a-bug).
