### ISSUE TITLE
Fully collapse sidebar into hamburger menu

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#1761]
Currently, the viewer sidebar collapses to the LEFT, and partially shows. The ideal behavior is for the sidebar to fully collapse, and to be accessible by clicking the hamburger menu at top left.
![screen shot 2016-12-12 at 9 44 36 am](https://cloud.githubusercontent.com/assets/2573761/21105473/f05b654c-c04f-11e6-8d32-aaa170d12764.jpg)

**Comment by emilyashley** [comment]
Cool beans, I can take a look at this and update it next time I'm in the viewer code. It had recently been updated to simply scooch to the side as shown because previously it would resize the canvas for the map in an unsmooth manner.

**Comment by jonpmarino** [comment]
@emilyashley sounds good. just logging here for future notice when the time comes for viewer improvements.

**Comment by jonpmarino** [comment]
closing and reproducing in /mapstory rep
