### ISSUE TITLE
start_time should be optional

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#182]
To allow for pixel-based annotations that should show up in the map any time.

**Comment by bartvde** [comment]
would be great to have feedback on this from the user meeting this week, i.e. should this still be done or can it be closed?

cc @cholmes @ischneider @emloux

**Comment by bartvde** [comment]
@ischneider can you clarify on this one whether or not you could have an annotations that miss both a start_time and an end_time?
Or if start_time is not present, there should always be an end_time?

**Comment by bartvde** [comment]
also, if end time is empty now, we use the playback toolbar's range, I assume we can do the same thing for start, but I wonder if we want to allow annotations outside of the playback range (does that make any sense at all?).

Also, we can run into situations where end_time < start_time, and the timeline will show errors in this case. Since the start_time might not be as apparent to the user when omitted, e.g. playback range 2010-2012 and user enters 2009 for end_time and leaves start_time empty.

**Comment by bartvde** [comment]
cc @sshyu

**Comment by bartvde** [comment]
some potential code:

```

index e4ca46e..3d419c3 100644
--- a/src/script/widgets/TimelinePanel.js
+++ b/src/script/widgets/TimelinePanel.js
@@ -764,11 +764,14 @@ gxp.TimelinePanel = Ext.extend(Ext.Panel, {
                 var mapFilterAttr = this.annotationConfig.mapFilterAttr;
                 if (Ext.isBoolean(record.get(mapFilterAttr)) ? record.get(mapFilterAttr) : (record.get(mapFilterAttr) === "true")) {
                     var startTime = parseFloat(record.get(this.annotationConfig.timeAttr));
+                    if (startTime == "" || startTime == null) {
+                        startTime = this.playbackTool.playbackToolbar.control.animationRange[0];
+                    }
                     var endTime = record.get(this.annotationConfig.endTimeAttr);
-                    var ranged = (endTime != startTime);
                     if (endTime == "" || endTime == null) {
                         endTime = this.playbackTool.playbackToolbar.control.animationRange[1];
                     }
+                    var ranged = (endTime != startTime);
                     if (ranged === true) {
                         if (compare <= parseFloat(endTime) && compare >= startTime) {
                             this.displayTooltip(record);
@@ -908,17 +911,18 @@ gxp.TimelinePanel = Ext.extend(Ext.Panel, {
                             end = new Date(this.playbackTool.playbackToolbar.control.animationRange[1]);
                         }
                     }
-                    if(start != null){
-                        events.push({
-                            start: start,
-                            end: end,
-                            icon: this.layerLookup[key].icon,
-                            title: attributes[titleAttr],
-                            durationEvent: durationEvent,
-                            key: key,
-                            fid: features[i].fid
-                        });
-                    }
+                    if (start == null){
+                        start = new Date(this.playbackTool.playbackToolbar.control.animationRange[0]);
+                    } 
+                    events.push({
+                        start: start,
+                        end: end,
+                        icon: this.layerLookup[key].icon,
+                        title: attributes[titleAttr],
+                        durationEvent: durationEvent,
+                        key: key,
+                        fid: features[i].fid
+                    });
                 }
             }
         }
```

**Comment by ischneider** [comment]
> @ischneider can you clarify on this one whether or not you could have an annotations that miss both a start_time and an end_time?
> Or if start_time is not present, there should always be an end_time?

My thought is that without a start and end time, the annotation would always be visible in the map. As for the timeline, this would imply the start and end time of the entire map. I'm not sure how often one would use this in the timeline, but I could see the potential for a map annotation that says something like "DRAFT" or whatever.

**Comment by bartvde** [comment]
I find it a bit too risky to change this behaviour now, so I propose to move this to the next milestone

**Comment by sshyu** [comment]
+1 @bartvde since we are so close to the next deploy.  Can someone also provide some more background as to why the users were asking for this?  (Not sure I understand fully from the description above.)

The result will be better if we can take a little more time to think through and document the scenarios here.

**Comment by ischneider** [comment]
@sshyu I think the background was just part of the initial design so there were no user-specific requests but the idea is to support an annotation that is always there (without having to specify a start/end time though this is a work-around)

**Comment by bartvde** [comment]
moving this out since it wasn't a user request and there have been many user requested tickets this milestone

**Comment by ischneider** [comment]
Closing - old UI
