### ISSUE TITLE
change wrapDateline behavior

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#185]
As discussed with @ahocevar 

True. Then either a base layer that does not show up in the layer
tree, or the use of real base layers (isBaseLayer: true) instead of
using allOverlays: true would be other options. In the latter case,
setting wrapDateLine and map background would be base layer options,
not map options.

**Comment by bartvde** [comment]
@ischneider reported:

In terms of desired functionality, I think Chris is okay with zooming
out beyond the world extent but not seeing multiple worlds. In other
words, having the background appear as per the second map noted above.

**Comment by bartvde** [comment]
@ahocevar :
I think it would make sense to take this as an opportunity to address
several issues we have with base maps in gxp based viewers:
- base map dependent and non adjustable number of zoom levels
- base map dependent and non adjustable wrapDateLine behavior
- zoom levels and wrapDateLine behavior depending on order of base maps in tree

In my opinion, although a bit hackish, the most reliable solution
would be the following:
- gxp.Viewer adds an empty layer with displayInLayerSwitcher set to false
- A new map properties dialog allows to configure the number of zoom
  levels, the dateline wrapping, and the map background color.

**Comment by bartvde** [comment]
@ahocevar came up with an even better suggestion: in OpenLayers when displaying more than one world, automatically switch to wrapDateLine false. This will essentially give the wanted behavior.

**Comment by bartvde** [comment]
The last mentioned suggestion revealed too many issues in OpenLayers. So going back to map properties dialog see:

https://github.com/opengeo/gxp/pull/122

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode-client/commit/6b63d9a50ebd2aa5f09bac795c2a32fba2db3f61

This might still need a Django change to set wrapDateLine to false by default in MapStory.

**Comment by bartvde** [comment]
As Ian reported, the overlays are repeated.

**Comment by ahocevar** [comment]
Is it possible that the overlays have wrapDateLine set to true? Overlays should always have set it to false.

**Comment by bartvde** [comment]
Investigating this one now.

**Comment by bartvde** [comment]
wrapDateLine is false on the overlays

**Comment by bartvde** [comment]
Failing to reproduce the issue.
