### ISSUE TITLE
support for center/zoom keyframes

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#187]
To support more compelling stories, support for annotations that represent keyframes is needed. These 'annotations' would specify a center and/or zoom location for a given instant in time. As playback proceeds, the map should be automatically panned and zoomed to the respective position.

Note this is what Tucker refers to as XYT frames.

**Comment by bartvde** [comment]
Does this needs design before implementing? Do you have ideas on how the workflow would be in relation to the current annotations?

**Comment by ischneider** [comment]
I'd guess it does but I'm sure that some prototyping could be done initially.

In terms of the workflow and an initial design, it seems like there are two tasks:
configuring a keyframe (time, zoom, center or XYZT)
managing new or existing keyframes (add, edit, delete)

Two specific actions are needed to start with: add key frame, manage key frames

When add key frame is pressed, the current XYZT become a new keyframe or override one existing for the same (primary key) time.

When manage key frames is selected, a non-modal window of existing keyframes should appear. The user should be able to select a keyframe and delete it or choose to edit it. Selecting (or alternately double-clicking) a keyframe should pan/zoom both temporally and spatially to the value. Pressing the edit button should, similarly to the add button, update the keyframe with the XYZT.

To identify keyframes from other annotations, one of the other fields could be used. For example, values (using the existing schema) for a keyframe might look like:
{
  title: '**keyframe**'
  description: <Z value>,
  the_geom: <XY point>,
  start_time: <T value>
}

**Comment by cholmes** [comment]
Assigning to Steven, as I think some design would be good at this point. I can think of at least a few edge cases, so we should get good wireframes going.

**Comment by ischneider** [comment]
Closing - covered by story boxes concept
