### ISSUE TITLE
setting of framerate should be supported

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#189]
configuration of framerate should be a supported option. I don't think it makes sense to allow 'dropping' frames, so this should be considered the 'pause between next frame' option.

**Comment by jeffreyameyer** [comment]
Shouldn't each mapstory define the appropriate milestones or steps in the story? Running continuously through a set of evenly spaced timeslices doesn't fit most of history, which follows a more punctuated evolution. Dropping frames (which I haven't seen so far) would be like skipping chapters in a story, no?

**Comment by cholmes** [comment]
Closing this, as I think there's other tickets that reflect this, and we no longer 'drop' frames afaik.
