### ISSUE TITLE
playback speed

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#190]
from an email from tucker, dated 03/05/12

> 1)  When I double the playback speed, it goes double.  When I click it again, sometimes funky stuff happens (like it stalls out) and I don't know what the status is.  Is it 4x instead of 2X?  Is it back to being regular speed?  Am I confusing it?

**Comment by mpriour** [comment]
there were some serious issues here in both the playback toolbar itself and the time manager control. However, they were all resolved before the retreat in Portland.
