### ISSUE TITLE
animation step values 

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#192]
As reported by Ian in an email thread dated 03/01:

On the date/time dialog during upload, the animation units selection sticks when the dialog is closed but the animation step value does not.

**Comment by ischneider** [comment]
To clarify, this is on the options dialog in either a data/map info page and possibly the viewer

**Comment by cholmes** [comment]
This works now. But there's another minor issue I noticed with it just not displaying the animation units properly.
