### ISSUE TITLE
time options endpoint needed

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#194]
to persist time options an endpoint to proxy the settings to geoserver is needed

see #193

**Comment by mpriour** [comment]
is this still valid @ischneider

**Comment by ischneider** [comment]
@mpriour yes, we currently don't have a way to change the start or end date attribute in geoserver or the presentation style after the initial upload

**Comment by cholmes** [comment]
@ischneider - does this get better with new importer stuff? And/or are you going to work on it with the new uploader? Should we schedule to a sooner milestone, or push off?

Also maybe should redo the ticket to talk about the user need to change the date attributes from the UI.

**Comment by ischneider** [comment]
This is supported through the REST API, so we basically just need to add a 'security proxy' view. The UI should be covered by #191

**Comment by cholmes** [comment]
Security proxy view is in django? What are exactly are the configuration options needed?

**Comment by ischneider** [comment]
Security proxy in django makes the REST calls to geoserver on behalf of the user (and verifies permissions).

Config options noted here: https://github.com/MapStory/mapstory/issues/191#issuecomment-19931165

Specifically:
1) choice of presentation (LIST, INTERVAL)
2) if INTERVAL, some interval (7 days, for example)

**Comment by emloux** [comment]
@ischneider Does this still need to be implemented?

**Comment by ischneider** [comment]
Still valid.
