### ISSUE TITLE
background layer selection not persisted in data view

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#196]
if the maintainer of the data selects a different background for the layer view page, the choice should be persisted.

**Comment by bartvde** [comment]
@ischneider I assume you mean the background color of the map? If so, this is a duplicate of #214

Please reopen if I misunderstood.

**Comment by ischneider** [comment]
@bartvde , this is actually for the layer page. There is some work for this already here:

https://github.com/opengeo/geonode/commit/ba94714f0c6e21de905be7bb0c5f7de4df35968f

I quoth cholmes from #417:

```
The other thing that would be good on the 'configuration' tab is the ability to set the base layer for the layer. Like when people look at it on the layer page, the owner should be able to see what base layer they see with it first.
```

**Comment by bartvde** [comment]
@eloux what should be the milestone on this one?

**Comment by emloux** [comment]
@bartvde good question.  I'm thinking we can move this to bentonville along with #417
