### ISSUE TITLE
Notes do not stay in Map View

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#200]
1. opened https://docs.google.com/document/d/1W-DVP7USp0IknH0EDYp8u7KxonPA9qJra0QsImYYd_o/edit
2. create new map
3. press save http://mapstory.dev.opengeo.org/maps/71
4. added new note:
   - title: test
   - start time: december, 2002
   - no end time
   - include in timeline and map
5. press playback 
   - note shows up in timeline and map for dec 2002
   - note disappears after Dec 2002

I expect it to stay in the map view if there is no end date specified.

**Comment by bartvde** [comment]
But this approach would mean they are out of sync wrt timeline display (displayed as a time instant) and map display, does that make sense? So how do you then distinguish between a time instant and a time range with no end?

**Comment by awright** [comment]
ahh, i see what you're saying  let me discuss with rollie.

**Comment by bartvde** [comment]
talked to rollie on IRC.

No end_time means a range up until the end of the range, so it will display as a range in the timeline as well as stay up in the map.

Time instants should be created by specifying end_time = start_time

**Comment by bartvde** [comment]
Implemented with https://github.com/opengeo/gxp/commit/8c8d2aa7d0d5b78441d548ff41c0d33ef69c1ec8

**Comment by awright** [comment]
How do you make an event that's just one date?

On Thu, Mar 15, 2012 at 9:03 AM, Bart van den Eijnden <
reply@reply.github.com

**Comment by bartvde** [comment]
Time instants should be created by specifying end_time = start_time
