### ISSUE TITLE
Edits to Notes Do Not Show up

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#201]
a continuation of #200
1. opened note and changed text to:
   "TESTSADFAJFASL'FJASLJF'ASDFLASJF';ADLAJS'LFDALFJA'LSDFJ'ALFJ'A;SLJDF'LASJDFLASJ'LFA"

(so i could see it better)
1. changed date to 12/13/2002
2. pressed save and then play. 

i expected to see the new annotation at 12/2002.  instead the previous note displayed.  it wasn't until i want back to the info page then to the full view that i could see my changes.

**Comment by bartvde** [comment]
this is probably related to #178

**Comment by bartvde** [comment]
This specific issue should be fixed with https://github.com/opengeo/gxp/commit/4b7f0a1de368b5715c975e4722fd2b45482c0d73
