### ISSUE TITLE
can't save annotations

### ISSUE THREAD

**Issue by cmchen** [MapStory/mapstory-meta#202]
Computer: Windows 7 Pro 64-bit
Browser: Mozilla Firefox 10.0.2

Steps:
- Created a new map at http://mapstory.dev.opengeo.org/maps/new
- Added conflicts layer (following MapStory test script instructions)
- Saved mapstory http://mapstory.dev.opengeo.org/maps/72
- Added new Event note: Title=test1, StartTime=01/01/1950, Include in Timeline = true, Include in Map = true, Position=top right
  (actually, it doesn't matter what annotation type I try, none are successful)
- Press Save button -- Error occurs: "Save Failed - {http://geonode.org/}_map_72_annotations is read-only"

**Comment by ischneider** [comment]
Fixed. Current user was not being passed to create_layer so only admin could save annotations
Still have to update existing annotations layers to adjust owner.

**Comment by ischneider** [comment]
Layer owners updated.
