### ISSUE TITLE
new map with layer should use virtual service for capabilities

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#204]
For example, /maps/new?layer=geonode:african_bees_2009

Instead of resolving the layer via the full capabilities document, the virtual service should be used instead.

**Comment by cholmes** [comment]
+1 - I'm getting 7-10 second load times on new full screen maps, waiting for capabilities to load to get the proper extent to go to. Does appear to just be new maps, already saved maps work fine.

**Comment by mpriour** [comment]
In with this commit:
https://github.com/opengeo/geonode/commit/90b15b333169c6b1853fd44c74bb2a0bbdc39e00
