### ISSUE TITLE
'popout' viewer from data/map page

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#205]
From the data/map landing page, the preview map should have a button to view the map full screen. Ideally, the viewer would just change z-level and size to become full screen and not require a page load. The full viewer needs a button to return to normal. To edit the map, the normal link on the right is used.

**Comment by mpriour** [comment]
implemented with:
https://github.com/opengeo/geonode/commit/d4e4b3995b6b7e12f794fc83fa546f80899d4dac
and
https://github.com/opengeo/mapstory/commit/eb91f780c784b5356dc81a5a01c73808177a8bf2

**Comment by bartvde** [comment]
Tested on dev. Closing.
