### ISSUE TITLE
store map configuration for layers

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#206]
The data page (for example /data/geonode:african_bees_2009) should support customization by the owner. This means persisting:

center/zoom
time options
background

**Comment by mpriour** [comment]
All of these are already supported in the client, you just need a way to save it in the layer data

**Comment by ischneider** [comment]
Ignore commit - read issue number out of wrong window.

**Comment by bartvde** [comment]
post to an non-existing URL and capture the output e.g.

**Comment by bartvde** [comment]
@ischneider easiest way for you to check this is to do app.getState() in Firebug console or something similar. You'll be mostly interested in the map and tools sections of the output. Is this sufficient info for now?

**Comment by bartvde** [comment]
What needs to be done for this on the client-side? Do we need to output a stripped down version of Viewer::getState() ?

**Comment by mpriour** [comment]
No we are actually going to use the full the viewer::getState method output and just store it as a json blob in the database. The client side is going to use the new mapstory.LayerViewer class and it will use the stored viewer config to display the layer properly. The layerViewer playback toolbar will have a camera icon on it that the user will click to save a specific view of the map. That will call the save method and also hit the create thumbnail endpoint.

**Comment by mpriour** [comment]
@ischneider is working on the save layer config endpoint

**Comment by mpriour** [comment]
this has been addressed on both the client server side. however it needs to be implemented in the UI. This is scheduled for inclusion in next round of work.

see #368 for further discussion

**Comment by ischneider** [comment]
Any discussion might be here:
https://groups.google.com/a/opengeo.org/d/topic/dev-mapstory/hhFYXpmzkxs/discussion
