### ISSUE TITLE
Can't see styling condition fields

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#208]
logged in as admin:
1. go to http://mapstory.dev.opengeo.org/data/geonode:US_Stat0
2. select "create new map"
3. select "edit styles"
4. make sure "BMI < 25" is the selected style
5. select edit one of the 5 styles and go to the advanced tab -- 

there is a BETWEEN filter but you can't see any entry in the fields.  

https://skitch.com/alyssawright/8k9dc/styles

**Comment by bartvde** [comment]
My first guess is that this is caused by the whitespace in the XML, but we should fix this on the client-side for sure.

```
                            <ogc:LowerBoundary>
                                <ogc:Literal>


                                29.7


                            </ogc:Literal>
                            </ogc:LowerBoundary>
                            <ogc:UpperBoundary>
                                <ogc:Literal>


                                36.2


                            </ogc:Literal>
```

**Comment by bartvde** [comment]
This should fix it once it makes it into OpenLayers:

https://github.com/openlayers/openlayers/pull/334

**Comment by bartvde** [comment]
This is now fixed in OpenLayers and pulled into MapStory, I've verified that it works okay now. Closing.
