### ISSUE TITLE
Setting Number of zoom levels doesn't work well

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#215]
I played some with setting the number of zoom levels. And it sorta works, but doesn't give good feedback on it being set. I can still 'try' to zoom in further on the slider, but it just doesn't have any affect. Similarly it looks like I should be able to zoom in more by hitting the zoom button, it just appears not to work.

It'd be an improvement if we shortened the zoom slider bar according to how far it was set. I think we do this in GeoExplorer with google terrain for example. Should give visual queues to the user of how far they are allowed to go in, instead of them just feeling like it's not working.

I think it might also be worth expanding the 'number of zoom levels' to a zoom slider where map makers can select the start and end zoom levels, not just the total number of levels. I feel like we want map makers to have control over this - you want users to be able to zoom in and check things out, but going down to zoom level 18 on a map showing country GDP seems a bit silly. This should also save us from generating a lot of tiles that aren't that useful. I think Rollie has some wireframes somewhere on this, a bar with multiple sliders to set the min and max.

**Comment by bartvde** [comment]
Good catch Chris, I needed to trigger a changebaselayer event so that things like the zoom slider and the scale combo get updated.

Wrt setting start and end zoom level, I think we should consider that something for the future for now.

**Comment by bartvde** [comment]
Fixed with https://github.com/opengeo/gxp/commit/211f3ecd70019b2d2f1f85a835291a9262ca4a59

Opened up enhancement ticket here: https://github.com/opengeo/gxp/issues/131

Closing this one.
