### ISSUE TITLE
Keep annotation layers out of user layer lists?

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#216]
If I go to my profile: http://mapstory.dev.opengeo.org/profiles/cholmes/ I see three annotation layers in the list. None of them actually work when I go to them, since I don't think I really added any annotations. 

I want to dig in to more how we store and handle annotations, but will do that in an email. But I feel like we shouldn't be exposing them in the profile? It looks like we don't have them show up in layer search or in the 'add to map' stuff.

**Comment by bartvde** [comment]
I think this would require server-side (Django) changes, not client-side. Reassigning to Ian to get his feedback.

**Comment by ischneider** [comment]
This would require some filtering on the server. I have introduced the concept of a configurable (via django settings) filter into the search results and I suppose this could be extended and used elsewhere.

**Comment by bartvde** [comment]
Annotations don't show up in the profile page anymore, so closing this one.
