### ISSUE TITLE
Controlling style changes and permissions

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#218]
If I go to a layer page and hit 'create new map' I can then just go in to the existing styles and just start changing them however I want. You could really screw up someone else's map that way, not even meaning to. I'd say this is a very serious bug, for when people start to make maps from other people's data. It's more natural to just change a style instead of create a new one from scratch.

Best thing to do I think would be to just gray out the 'edit' button on existing styles, and so that users always have to hit 'duplicate'. To do this right we probably have to test ownership of the style (which I don't think we have a concept of?), but also could just check for ownership / edit permissions on the layer. This still lets admins screw with the styles that others have done on their data, but that seems far less worse then the opposite, having anyone be able to change the owner's styles. And you could argue that's maybe a 'feature', for admins to have some say in how people present their data.

**Comment by bartvde** [comment]
Is there any Django endpoint that the client can hit to find out these permissions @ischneider ?

I don't think we ever should trust only on client-side disabling of tools, additional server-side checks need to be in place to prevent bypassing the client.

**Comment by cholmes** [comment]
Server side checks are definitely ideal, but to do it well we should do it at the geoserver level. Which involves some major overhauls I believe, so that users can own and permission on styles. Afaik right now styles aren't part of the security infrastructure. Though maybe some of the new workspace stuff could be utilized? Doing it right I think you also might want to put style 'cloning' at the geoserver level too? Maybe not.

Alternatively you could have styles just live in django land and have geoserver refer to remote sld's. But the one thing you lose there is when hitting the WMS end point, you wouldn't see the alternate styles.

But server side checks need more thought and work, which I'm not sure is realistic to do by the first mapstory release. Though I guess maybe there is some half way thing that can just happen at the django level and do a bit more. I'm just not sure what it would be right now, or what that really gets you.

**Comment by cholmes** [comment]
This was duplicated in #715. Closing this one as that one is scheduled and has more info.

**Comment by cholmes** [comment]
Relevant info from Ian on #715: The actual communication goes through geonode (a security proxy since we talk to geoserver's REST API) so we could enforce things here as well as on the client without adding anything to geoserver.

The challenge is coming up with the rules for who owns the style, when to copy, implementing a django model to track more complex permissions (if desired), etc.

**Comment by cholmes** [comment]
So I think the thing to do on this is as follows:
- Any user can hit the 'style' button (just like now)
- We do a check on ownership of the layer when popping up the style dialog. 
  - If the logged in user is the layer owner then we have a clickable, non-grayed out 'edit' option (the top edit in the picture below), and they can change edit any of the styles.
  - If the user is not the owner (or not logged in) then the top 'edit' button is grayed out. The bottom panel ideally shows the rules but is not editable. The user can hit 'duplicate' and then they get a style that they can change, and it becomes the default style for that map.

![screen shot 2013-07-20 at 11 52 42 am](https://f.cloud.github.com/assets/407017/830474/a3e05452-f154-11e2-95c6-4e6bee15ff18.png)

Ideally we would then give the user 'ownership' of their style. But I think the short term thing would be that when they come back to their map (they'd be the owner of the map, but not the layer), they have the 'edit' button for the style they created. But for all the other styles in the drop down they can 'duplicate' but not add.

The layer owner then can always edit anyone else's style (though hopefully they won't. And when we get deeper permissioning we make it so they can only edit their own styles).

**Comment by bartvde** [comment]
I don't think this is gonna happen for Appomattox @ischneider what do you think?
Has any work been done on the Django side?

**Comment by zrouse-Boundless** [comment]
We have to also look at the WPS work Justin did

**Comment by davisc** [comment]
This is resolved by using the Geonode style api as a proxy to geoserver as admin.
