### ISSUE TITLE
Generating thumbnail for map goes in to infinite loop

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#219]
Had this happen with two or three maps. Didn't happen with layers, they generated their thumbnails just fine. The animated progress bar just keeps going, for minutes. At least some of the time it's doing this it asks me to login, with the http login (where I do storyteller/tellme) and then with the ext geonode login. But I think I did once get the infinite progress bar without the login prompts. But regardless it for sure should be fixed to not prompt for login, as I'm already fully logged in.

**Comment by ischneider** [comment]
This is most likely resolved. Closing for now
