### ISSUE TITLE
Lower opacity on map controls 

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#22]
Fade out the controls so they don't distract from the map content when the user is not interacting with them (they should increase in opacity when the user hovers.)  See Google Earth for an example

**Comment by mpriour** [comment]
Initial shot at this committed to GXP
https://github.com/opengeo/gxp/commit/1eb62b4cd3e3c6d3ebee30820fe7a0429473b95b

**Comment by scrollie** [comment]
Looks good, but I think the intent is to have all the map controls (including the pan and zoom controls) shift opacity. also, we may want the faded-out controls to be slightly more opaque, lest they seem to disappear entirely.

**Comment by mpriour** [comment]
The map controls shifting opacity is an order of magnitude different from the playback control itself since they are mostly OpenLayers controls and not gxp generated ExtJS components and thus don't have a common container other than the map panel.
I'm soliciting advice from the other js devs on the best place / way to approach this.

**Comment by mpriour** [comment]
Increased opacity level of playback control so that it is nearly fully transparent in faded state.

**Comment by awright** [comment]
We want the time controls visible during animation.  Instead, time controls need "show up" when mouse hovering.  Here is Chris's latest email:

Remember that I would really like to have the time controls NOT on the map.  I think that, like YouTube, having a bar across the bottom on which the time controls lie (along with other things like, sound/mute, full screen, etc.) would be the right aesthetic.

**Comment by mpriour** [comment]
crazy easy, depending on where he WOULD like the time controls. They are a toolbar that can be added to any other toolbar or even added as a new bottom toolbar on the map viewing pane. Icons can be larger, more video like, etc...

**Comment by awright** [comment]
spatial dev is putting together designs for where to put time controls and scale bar.  i don't expect to have those designs finalized before the end of year, so in the interim let's see if we can do a temporary fix.  tucker mentioned having the time controls on the same level of the layers selection and getfeatureinfo tool.  i think it makes sense to move the time controls and scale below the map pane.  https://skitch.com/alyssawright/gc8xm/timeline-and-scale

we do need a "full screen" icon/button on the time controls bar.

**Comment by mpriour** [comment]
Here is a pretty silly looking but functional implementation of that:
https://docs.google.com/a/opengeo.org/drawings/d/1YI_J3d1C-NeR4YiGZrr1f1tonOWJ4bKTGypEkXX_YfY/edit

If you want me to, I can push that change up to the repository and we can fiddle with it to make the buttons big enough for the bar, etc.. Or we can wait until we have better design guidance.

**Comment by awright** [comment]
That looks like a great start.  Could you also remove the MapStory header
when in this full screen mode?

Otherwise, it seems ready to push.

On Wed, Nov 30, 2011 at 12:44 PM, Matt Priour <
reply@reply.github.com

**Comment by mpriour** [comment]
That is not a special full screen mode.
That is just the normal published map mode.

On Wed, Nov 30, 2011 at 5:19 PM, alyssa wright <
reply@reply.github.com

> wrote:
> 
> That looks like a great start.  Could you also remove the MapStory header
> when in this full screen mode?
> 
> Otherwise, it seems ready to push.
> 
> On Wed, Nov 30, 2011 at 12:44 PM, Matt Priour <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Here is a pretty silly looking but functional implementation of that:
> > 
> > https://docs.google.com/a/opengeo.org/drawings/d/1YI_J3d1C-NeR4YiGZrr1f1tonOWJ4bKTGypEkXX_YfY/edit
> > 
> > If you want me to, I can push that change up to the repository and we can
> > fiddle with it to make the buttons big enough for the bar, etc.. Or we
> > can
> > wait until we have better design guidance.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/opengeo/mapstory/issues/22#issuecomment-2965987
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/opengeo/mapstory/issues/22#issuecomment-2968335

## 

Matt Priour
OpenGeo - http://opengeo.org/
Expert service straight from the developers

**Comment by awright** [comment]
I think both are the same, so it's appropriate to remove the header.  If
you want to wait for further design direction, you can push the time
controls and hold off on the header.

On Wed, Nov 30, 2011 at 3:20 PM, Matt Priour <
reply@reply.github.com

**Comment by awright** [comment]
removing all mapcontrols from view is only relevant when we implement the fullscreen view of our map.  in other words, once we start working on the spatialdev design implementation we can make a more relevant ticket.
