### ISSUE TITLE
Links from map pages to the layer pages don't work

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#220]
Each map page references the layers that it uses. In normal geonode these are real links, letting you explore the actual data behind a map. In mapstory these don't actually link, they just say the 'name' of the layer (not even the proper title).

**Comment by awright** [comment]
this is already addressed in the current wireframes,will be implemented as we begin to merge eldarions work with the mapstory branch.

**Comment by bartvde** [comment]
This is fixed already, closing.
