### ISSUE TITLE
Google Earth view doesn't use time

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#223]
Google earth has a great time viewer, that has been made to work with GeoServer, but it's not picking up proper time stuff from the mapstory layers.

I believe this is probably a deep geoserver issue not super easily solved. I think we may use two systems there, the freemarker templates to set time in google earth, and another system for WMS stuff. We should combine these in to one system, so that setting the time field in mapstory / geoserver admin makes it so the time shows up properly in google earth.

**Comment by bartvde** [comment]
GE plugin has been removed, so closing this issue.
