### ISSUE TITLE
Issues with 'refine search'

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#224]
In 'refine search' on http://mapstory.dev.opengeo.org/maps/search there's no way to refine by 'temporal extent', or 'by date added' - they have added before and added after, but no way to set them. There are no keywords to search by. So there's nothing to select.

In refine search on http://mapstory.dev.opengeo.org/maps/search there are options for spatial extent and category, but hitting 'refine' based on them seems to have no effect. For example doing 'category' to environment which tells me there's just one still returns 141 results. The map refining seems similar, even if I'm zoomed in quite far I seem to get everything.

**Comment by ischneider** [comment]
no longer seems relevant. tested on dev with success
