### ISSUE TITLE
Map on map page doesn't zoom well

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#225]
On http://mapstory.dev.opengeo.org/maps/78 and other map pages the credit of who put the data up (in this case 'admin') partially covers the zoom out button, so you can push on it and not go anywhere. You have to move to the top of the icon to hit it successfully. Even a bit more pronounced on http://mapstory.dev.opengeo.org/maps/81 We should leave space for the words across the bottom.

I also wouldn't mind if the map on the map page in particular was quite a bit bigger. It should be about the map, not all the random stuff around it.

**Comment by awright** [comment]
should be addressed in the design updates.
