### ISSUE TITLE
Pink tiles in Info View

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#226]
http://mapstory.dev.opengeo.org/maps/65

Shows up Pink in the small view but plays fine in the large screen view.  I think there's something amiss with the Aviation Timeline layer.

**Comment by bartvde** [comment]
The URL which gives pink tiles is:

http://mapstory.dev.opengeo.org/geoserver/wms?LAYERS=geonode%3AAviation_timeline&FORMAT=image%2Fpng&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&TILED=true&SRS=EPSG%3A900913&BBOX=-9795658.6045978,2145729.6848751,-9061863.1331622,1570198.0745708&WIDTH=600&HEIGHT=-470

and the error message is:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://mapstory.dev.opengeo.org:80/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      illegal bbox, minY: 2145729.6848751 is greater than maxY: 1570198.0745708
</ServiceException></ServiceExceptionReport>
```

**Comment by bartvde** [comment]
See: https://github.com/openlayers/openlayers/commit/84fb15e1d25f34c261250fde9f26640a47c3a6fc#commitcomment-1107603

**Comment by bartvde** [comment]
See: https://github.com/openlayers/openlayers/pull/338

**Comment by bartvde** [comment]
Since the change got reverted, this is working again. Closing.
