### ISSUE TITLE
GetFeatureInfo improvement

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#230]
So I find the new feature grid based Feature Info button used in GeoExplorer vastly superior to the server rendering some html and stacking those up. Could we put that in by default for feature info button?

Doing that may wipe away an issue I'm seeing, of half the pop-up being filled with a big blue space, see https://skitch.com/cholmes/8cba5/mapstory-dev

**Comment by bartvde** [comment]
We switched to property grid view today, but I don't think it's already deployed on the dev server.
