### ISSUE TITLE
Better handling of trying to edit a layer I don't have permission to.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#231]
Right now I can load a map, select a layer, and start editing away, even if I don't have permission to. I only get an error after I try to hit 'save' on the edit I've made, and then I get back a fairly opaque message: '{http://geonode.org/}final is read-only'. See https://skitch.com/cholmes/8mjhf/map-viewer-geonode  

Why does it even let me try to edit if I don't have permission to? Seems like it would be better to just not even have the edit tools appear at all if it's not a layer I can edit.

**Comment by bartvde** [comment]
@cholmes I don't think there is currently a way for the client to find out the permissions, so we can't disable.

**Comment by cholmes** [comment]
Close this, if a user reports this as an issue we can make a new issue.
