### ISSUE TITLE
Issues uploading data with no .prj

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#234]
Shapefiles from GeoCommons don't come with an prj file. The result is that the uploader tells me to look up 'None' on prj2epsg.org 

We should probably handle that a bit better, perhaps suggest to people that they might try 4326 as it's pretty common for data without a prj. Or better yet try to do some check to see if we can figure out if 4326 is a reasonable assumption (like look at some coordinates and see if they're +/- 180

Can get a geocommons file at http://geocommons.com/overlays/210834

**Comment by cholmes** [comment]
The other thing we could do is just require a .prj file. Right now we say it's 'optional', but it's actually not, since we mess up if it's not there.

**Comment by garnertb** [comment]
OBE.  New uploader defaults to 4326 when no projection is found.
