### ISSUE TITLE
'unexpected global name 'cleaned' is not defined' on uploading shapefile 

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#235]
Got this weird error on a couple different datasets: https://skitch.com/cholmes/8cb67/upload-layer-step-2-mapstory-dev

http://nycopendata.socrata.com/api/assets/958A587B-B84F-4E19-914D-808C770C0676 and http://geocommons.com/overlays/210834

One thing was that both had me enter an epsg code manually. Wasn't ever able to get either fully up.

**Comment by ischneider** [comment]
The first succeeds now, I used 2263 FWIW.

The second probably falls under #234

Saying this is resolved.
