### ISSUE TITLE
prompted for unknown credentials

### ISSUE THREAD

**Issue by ghost** [MapStory/mapstory-meta#238]
whenever I try and interact with a mapstory (not in full screen mode) i am prompted for credentials. neither the username and password used to log in works, nor the credentials used to log into the site work.

**Comment by ghost** [comment]
also - only happens on mapstories you "own"

**Comment by bartvde** [comment]
@elasher Is this still an issue, or was this a temporary glitch fixed by @ischneider ?

**Comment by ghost** [comment]
It doesn't seems to be an issue anymore.
