### ISSUE TITLE
Specification of timeline styling, filtering, other end-user customization

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#24]
feature spec and related user experience work for ticket #8

**Comment by awright** [comment]
we currently have a simple implementation, but we should investigate further.  want to answer the question -- what do map authors need from the timeline?  

currently there are no styling options for the timeline.  we want to be able to make the dots different colors or have icons.  

we might want to think about having some way of consolidating things.  for example -- in the mexican murder map we might want to group by city so we don't have 100s of dots.  

sam p, sam s, and rollie probably further ideas.

**Comment by awright** [comment]
see #131

**Comment by ischneider** [comment]
perhaps allowing specification of a filter on what appears in the timeline ( number_of_murders > 100 )

**Comment by awright** [comment]
can't you can already do this under the Layers menu item?

On Wed, Jan 18, 2012 at 1:06 PM, Ian Schneider <
reply@reply.github.com

**Comment by ischneider** [comment]
Yes - i guess I hadn't seen that before. Is the intention that the filter can be saved?

**Comment by awright** [comment]
Yes.  I believe the intention is for the filter to be saved. Does that not
happen?

**Comment by bartvde** [comment]
No the filter is not saved currently.

**Comment by bartvde** [comment]
I just implemented saving and restoring the filter, see e.g.:

https://github.com/opengeo/gxp/commit/29a7d136dc43ae94fcf33654e165ed110eb2fcd5
