### ISSUE TITLE
missing layer list

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#240]
this map is not loading: http://mapstory.dev.opengeo.org/maps/54

i'd like to see what layers are there, but noticed there's no layer list.   until we have the layer list as in the mapstory comps i think we need to keep it in the toolbar.

**Comment by bartvde** [comment]
The map is loading for me @awright once I press play the national parks show up.

The layers can also be seen in the section right of the map (This map uses the following layers), is this not sufficient?

**Comment by awright** [comment]
sounds good to me.
