### ISSUE TITLE
Service Exception/Pink Tiles

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#241]
for this map: http://mapstory.dev.opengeo.org/maps/54

i'm getting one layer, but pink tiles as a base map. 

<?xml version="1.0" encoding="UTF-8"?><ServiceExceptionReport version="1.3.0" xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ogc http://mapstory.dev.opengeo.org:80/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">   <ServiceException code="MissingParameterValue" locator="request">
      Could not determine geoserver request from http request org.geoserver.platform.AdvancedDispatchFilter$AdvancedDispatchHttpRequest@270f3b8e
</ServiceException></ServiceExceptionReport>

**Comment by bartvde** [comment]
cannot reproduce this one currently on the dev server, so closing. Please reopen if I've misunderstood.
