### ISSUE TITLE
Date & Time Options (time range) won't save/update

### ISSUE THREAD

**Issue by cmchen** [MapStory/mapstory-meta#244]
System: Windows 7 Pro 64-bit; Mozilla Firefox 11.0

Steps:
-Create new mapstory (http://mapstory.dev.opengeo.org/maps/new)
-Add a layer
-Go into Date & Time Options window>change the Time Range>click Save
-Playback timeline is still able to play full range (has not updated to reflect new time range), and when you go into the Date & Time Options window again, the changes that were made to the range, have not been saved.

Also, when the original/first layer is removed and a new layer is added, the playback timeline does not automatically update to match the new layer's time range. Nor can the time range be manually changed/saved to match with the new layer.

**Comment by mpriour** [comment]
this was related to the same problem as #351 and has been resolved on the dev server and is waiting for testing and deployment to the production server.
