### ISSUE TITLE
map 96 cant' play

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#250]
http://mapstory.dev.opengeo.org/maps/96/view

not sure if this is a data issue but unclear why it loads with a map of full world info and when hit play only see a little info. 

see image at first load: https://skitch.com/alyssawright/8p9hx/google-chrome
see image after you press play: https://skitch.com/alyssawright/8p9hi/map-viewer-geonode

**Comment by mpriour** [comment]
This has been resolved
