### ISSUE TITLE
Failed to load resource

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#251]
go to http://mapstory.dev.opengeo.org/maps/90/view

http://mapstory.dev.opengeo.org/geoserver/geonode/swineflumerged/wms?request=GetLegendGraphic&format=image%2Fpng&width=20&height=20&layer=swineflumerged&format=image%2Fpng&legend_options=fontAntiAliasing%3Atrue%3BfontSize%3A11%3BfontName%3AArial&SCALE=69885320.73191442

error: Failed to load resource: the server responded with a status of 404 (Not Found)

so the swineflu is no longer is geoserver?  why is the map still in geonode? is this something that would happen alot or because of our development?

**Comment by ischneider** [comment]
Yes, it appears the layer was deleted. Nothing prevents a layer from being deleted (even if in a map) at the moment.
Closing since quite old.
