### ISSUE TITLE
duplicate map from info page doesn't work

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#253]
go to: http://mapstory.dev.opengeo.org/maps/76
press: "duplicate map"
available layers dialog comes up, not a duplicate of the map

https://skitch.com/alyssawright/8qgth/google-chrome

**Comment by bartvde** [comment]
@awright is the duplicate map link still in there? Can't find it anymore.

**Comment by awright** [comment]
@bartvde correct me if i'm wrong, but the "duplicate map" link is no longer available.  the only way to make a copy of a map is to save a copy of it from the edit view.  in other words, this issue is no longer valid.

**Comment by bartvde** [comment]
Right that was my impression as well, closing.
