### ISSUE TITLE
Reloading duplicated map yields original map

### ISSUE THREAD

**Issue by vhamer** [MapStory/mapstory-meta#254]
Visited map 106: http://mapstory.dev.opengeo.org/maps/106/view

Created duplicate (108) map, edited duplicate, and saved.

Found myself here: http://mapstory.dev.opengeo.org/maps/108/view

Hit Command + R.

Page reloaded to the original map (106), not the duplicate (108). 

Have replicated with different maps. 

Seems to be related to the process of duplication. If you do the above, then find yourself on the original map (106) and then search for map 108 and visit it, then Command + R, you arrive at the correct map (108).

**Comment by cholmes** [comment]
Closing. could not reproduce. I don't think we have the 'duplicate this map' functionalitiy.
