### ISSUE TITLE
Layer properties do not save

### ISSUE THREAD

**Issue by vhamer** [MapStory/mapstory-meta#255]
http://mapstory.dev.opengeo.org/maps/107/view

Adjusting the layer properties. Changing Playback Mode from Normal to Cumulative. But state doesn't take. This means I can't change layer-level Playback Mode.

Have tried this while MapStory is playing, and while paused. Have tried to save the properties by saving the whole map after making the change. New property does not seem to take hold.

**Comment by mpriour** [comment]
This is a definite bug. I will address it.

**Comment by mpriour** [comment]
This has been resolved.

**Comment by vhamer** [comment]
Yay for getting notified when tickets are resolved.

If you ever need a user tester, pick me pick me. Would love to help out, as I haven't done any in too long a while.
