### ISSUE TITLE
Pulsing of semi-transparent symbols

### ISSUE THREAD

**Issue by vhamer** [MapStory/mapstory-meta#256]
http://mapstory.dev.opengeo.org/maps/107/view

Second layer (smaller Walmart symbol) is semi-transparent. Over time, it pulses. 

At first we thought this was the normal pulsing effect that occurs due to the symbols in the top Walmart layer being shown over time. However, the small, semi-transparent symbols of the lower layer are pulsing.

Does not seem to be an issue with opaque symbols.

**Comment by mpriour** [comment]
This is a known OpenLayers issue. It was been significantly lessened but might never fully go away.

**Comment by cholmes** [comment]
I think this is much better now, especially on that map. Closing.
