### ISSUE TITLE
copying a map does not copy annotations

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#257]
it would need to create a new annotations layer and it would need to update the JSON blob to reference that

**Comment by bartvde** [comment]
E.g. check: http://mapstory.dev.opengeo.org/maps/107/data?_dc=1333048707323 it has a reference to "local/geonode:_map_76_annotations"

**Comment by bartvde** [comment]
@awright brought this up again July 18 on mapstory-dev

How difficult would this be to implement @ischneider ?

**Comment by ischneider** [comment]
@bartvde this doesn't seem terribly difficult to implement but it might make sense to allow options - when one copies a map, the user is presented options related to the semantics of copying. Someone might want to have a shared annotations layer, for example, so they can have two maps but maintain one set of annotations.

**Comment by cholmes** [comment]
We should revisit this as we're redoing annotations. 

I think it we should start by just defaulting to copying the annotations. Later if we get user requests I think there are two likely options to give people copying - use same annotations (to maintain one set of annotations), and don't copy annotations. I could see some users wanting to make all their own annotations.

That said, with a good editor it should be easy to delete all the existing annotations. That's not so easy right now.

**Comment by ischneider** [comment]
See #710 and #217 for any UI around saving/duplicating

**Comment by bartvde** [comment]
@ischneider any specific reason why this is assigned to me? Is there anything client-side that still needs to be done?

cc @cholmes @emloux

**Comment by ischneider** [comment]
No specific reason. I'll assign to me.

**Comment by ischneider** [comment]
Marking ready for testing. To test, go to a map with annotations, like 208 on dev. Save the map as a copy and verify it has annotations.

**Comment by jonpmarino** [comment]
I can confirm that annotations appear in http://mapstory.dev.opengeo.org/maps/384/ with Chrome and IE

**Comment by ischneider** [comment]
Marking as ready for deploy.
