### ISSUE TITLE
start playback at time 1 not time 0

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#259]
instead of starting the map with the end image, it would be good to see the first frame of the animation.

**Comment by jeffreyameyer** [comment]
I'm not seeing this fix. Ref: http://mapstory.org/maps/170. Map loads with blank base map.

**Comment by mpriour** [comment]
this is fixed. The issue that @jeffme is seeing on this particular map is that the reported playback range is actually just before the actual data occurs and thus you see an empty map. This is the case for several datasets and it might be a good ticket to investigate the best way to handle such situations.

**Comment by mpriour** [comment]
A better title would be to start at time = playback_range[0] not time = undefined
