### ISSUE TITLE
can't download data from mapstory info page

### ISSUE THREAD

**Issue by cmchen** [MapStory/mapstory-meta#261]
System: Windows XP 32-bit; Mozilla Firefox 11.0

Steps:
-Navigate to a mapstory (http://mapstory.dev.opengeo.org/maps/87)
-Under the Download category, select the "Download all layers included in this map" link (http://mapstory.dev.opengeo.org/maps/87/download/)
-Issue -- unable to download desired layer(s): 
Finally, the map contains these layers which will not be downloaded because they are not available directly from this GeoNode:
    /geoserver/wms?layers=geonode:BE_Colonies

However, I can successfully download layers (including the BE_Colonies layer) from the "Available Layers" popup window when I go to create a new mapstory (http://mapstory.dev.opengeo.org/maps/new). Downloads are also successful on storylayer pages (http://mapstory.dev.opengeo.org/data/geonode:FertilityRate_total_Births).

**Comment by cmchen** [comment]
Actually, as of April 2nd, the "Download all layers included in this map" link works now. I can select the layer's link and download from the storylayer page. But when I try to press the "Start downloading this map" button on the http://mapstory.dev.opengeo.org/maps/123/download/ page, I get a server error.

**Comment by cholmes** [comment]
Closing this, I think we don't offer full map download any more. May bring it back at some point, but can make it its own issue.
