### ISSUE TITLE
add html and descriptive text to feature annotations 

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#264]
as with event annotations, feature annotation include the title as well as descriptive text.

**Comment by bartvde** [comment]
Okay, the way we are gonna approach this one is to unify the annotations so that they all use Ext Tips, and not OpenLayers labels.

**Comment by bartvde** [comment]
This has been done with https://github.com/opengeo/gxp/commit/795a8244d82fdf78cb547fa75e2b22024550506f

As a TODO: I still need to create a GeoExt pull request for this. And the positioning of the tip could be better depending on where the feature is in the map, but it's a good start.
