### ISSUE TITLE
overlays should not be repeating

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#265]
this needs to be reimplemented in OpenLayers again. Matt and Andreas were involved initially.

**Comment by cholmes** [comment]
Pull request was at https://github.com/openlayers/openlayers/pull/304

**Comment by cholmes** [comment]
Example of this:
![dateline-wrapping](https://f.cloud.github.com/assets/407017/698251/8ab14290-dd11-11e2-990c-abeb515487de.png)

If we were to wrap the base map then this repeating would be fine. But see #771 - we want to just not have wrapping as an option. So should just get this working right.

**Comment by bartvde** [comment]
This was fixed recently by @ahocevar in OL and pulled in see #771 for the respective discussion.
Closing as duplicate.
