### ISSUE TITLE
annotation moves/doesn't stay center

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#268]
goto: http://mapstory.dev.opengeo.org/maps/117/view
press play
annotation labeled ""third avenue line" doesn't stay in same place on map view

**Comment by bartvde** [comment]
I've seen this as well, not sure yet what is happening here.

**Comment by bartvde** [comment]
Should be fixed with https://github.com/opengeo/gxp/commit/c09fd28304249b790c0e690b40e5a9c2373c859c
