### ISSUE TITLE
Wireframes for Faceted Search

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#27]
related to ticket #13

**Comment by scrollie** [comment]
I still need to do a more thorough write-up on the wiki, but here is what I have thus far: https://img.skitch.com/20111111-r3nx734a1isxif6wwra8qwguqf.png

Note the expanded sorting criteria in the top-center, the refine search criteria in the sidebar, and the three different states of the refine criteria at the bottom. The general idea is that adding criteria will filter the results such that selecting the keyword "fish" will limit the remaining keywords with which to filter to those results that are also tagged "fish". Also, note the implied removal of pagination in favor of "never-ending scroll" of dynamically updated results.

Feedback welcome!
