### ISSUE TITLE
position for events not saving

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#270]
goto: http://mapstory.dev.opengeo.org/maps/117/view
see annotations Lexington Avenue Line and Broadway -Seventh Avenue Line.  Both are events with the same range 1/1/1903-1/1/1904.  One should be on the upper right, one should be on the lower right.  If I save one, the other goes to center.  If I save the other, it resets to center.

**Comment by bartvde** [comment]
the issue is the default value of center that I had introduced

**Comment by bartvde** [comment]
This should be fixed now.
