### ISSUE TITLE
add buffer around event position

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#271]
(not high priority for this release, but would be nice)

the position of the events -- top  left, top right, etc are flush against the edge of the window frame.  it would be good to have a bit of space around the box.

**Comment by bartvde** [comment]
This would require an Ext.override, something like:

```

// showBy does not allow offsets
Ext.override(Ext.ToolTip, {
    showBy: function(el, pos, offsets){
        if(!this.rendered){
            this.render(Ext.getBody());
        }
        this.showAt(this.el.getAlignToXY(el, pos || this.defaultAlign, offsets));
    }   
}); 
```

Also the sign of the offset needs to differ depending on the position, e.g. on the right side the x-offset should be minus, on the left side it should be positive.

**Comment by bartvde** [comment]
Should be fixed with https://github.com/opengeo/gxp/commit/3698a7ccdea9a93f0f1a06129e67fcfda1063501
