### ISSUE TITLE
annotations not showing

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#272]
goto: http://mapstory.dev.opengeo.org/maps/117/view

there are 4 annotation events from 1898 to 1905.  if you press play (with the timeline not expanded) the annotations do not show up on the map view even though they should.  

if you expand the timeline some show up but not all of them. here are the 4 annotations:
1. Brooklyn Bridge tracks
2. Service expands to the Bronx
3. Lexington Avenue Line
4. Broadway-Seventh avenue line

**Comment by bartvde** [comment]
This should be fixed now. I've just verified on the dev server, but please verify as well.
