### ISSUE TITLE
annotation edits on top of annotation positioned in center

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#277]
i have an annotation in the center of a map. when i go to edit the dialog box appears on top.  is there any way to reposition it in this particular use case?

https://skitch.com/alyssawright/8xxr5/annotations-edit

**Comment by bartvde** [comment]
Should be fixed with https://github.com/opengeo/geonode/commit/397696ebb5c8d20bc9632dd3b208aa44d8bca9b6

**Comment by bartvde** [comment]
This does not seem to be a good idea/fix, since the prompt is now getting under the dialog.

**Comment by bartvde** [comment]
Fixed in an alternative way which does not have the side-effect mentioned with:

https://github.com/opengeo/geonode/commit/222e04483600c5bb53f3f9cc100ef3dada26c34f
