### ISSUE TITLE
select annotation > show pop up

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#278]
when a user clicks on an event in the timeline, i believe the pop-up with the information should appear with the option to edit, not as it is now -- the edit dialog box with the option to edit or delete.  i bring this up because there are some events that go by so quickly you can't read them.  a user might want to go back to that event and read the popup, not edit it.  to see this in action go to:

http://mapstory.dev.opengeo.org/maps/117/view

in april 1980 there was a 10 day strike.  you can see the event on the timeline but not on the map. when selected, it opens the edit dialog.

**Comment by bartvde** [comment]
Looking at the design (https://github.com/opengeo/mapstory/wiki/Design) I see you are right.

I'll need to assess how much work this implies though, since this differs from the current GXP workflow.

**Comment by bartvde** [comment]
So is the main issue the Delete button that shows up immediately?

**Comment by awright** [comment]
say for instance that the playback is moving so fast that a user can't see/read the annotation. in that case, a user should be able to pause the play, select the event from the timeline and read the annotation. right now when one select an event the dialog comes up whitened out so a user can't read the info.

**Comment by bartvde** [comment]
okay, so it's mostly the dialog being disabled. I'll look into that.

**Comment by bartvde** [comment]
delete button is now only visible after the edit button has been pressed see: https://github.com/opengeo/geonode/commit/3248124dc657f22f605e27cace73db04e0ee4a18

**Comment by bartvde** [comment]
Readability issue addressed with https://github.com/opengeo/gxp/commit/bac6deeba79496ef36e8293277f1faf0cb0a44e4
