### ISSUE TITLE
missing annotation

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#279]
i added a note but forgot to click "include in timeline or map" so it's not anywhere.  is this expected behavior? seems sort of weird.  i added a note called "graffiti-free" to this map, incase it's somewhere and you can see it but i can't. 

http://mapstory.dev.opengeo.org/maps/117/view

**Comment by bartvde** [comment]
Okay, to overcome this situation I would:
1. change the defaults of include in timeline and include in map to checked
2. add a checkchange listener to make sure always one of them is checked

Does that make sense?

**Comment by bartvde** [comment]
I've implemented the above with https://github.com/opengeo/geonode/commit/a513b13e1147b47685d884758141688dfc497b81

**Comment by awright** [comment]
yes. thank you. is my graffiti annotation gone for good? (just wondering)

**Comment by bartvde** [comment]
it's gone / not accessible, unless we change the database.
