### ISSUE TITLE
playback timeline not compatible with Firefox

### ISSUE THREAD

**Issue by cmchen** [MapStory/mapstory-meta#281]
System: Mozilla Firefox 11.0

The playback timeline is not showing up properly. None of the buttons appear, but I can hover over them and a square button will popup (along with the mouse tool-tip) that I can press and use. 

(No issues in IE 9.)

**Comment by bartvde** [comment]
Fixed with https://github.com/opengeo/mapstory/commit/7577bc33611cfedae14e4ea28d7b06651e6318f2
