### ISSUE TITLE
base maps not loading

### ISSUE THREAD

**Issue by cmchen** [MapStory/mapstory-meta#282]
System: Windows 7 Pro 64-bit
Browser(s): Mozilla Firefox 11.0, Internet Explorer 9

Steps:
-open up the full-screen view page of a mapstory (http://mapstory.dev.opengeo.org/maps/106/view)
-expand the left hand side table of contents/layer window
-switch Base Maps to either bluemarble or Wayne

Issue -- bluemarble and Wayne do not load, only OpenStreetMap layer seems to work. Although, sometimes the Wayne layer works, like here: http://mapstory.dev.opengeo.org/maps/124/view

**Comment by bartvde** [comment]
There seems to be an issue with maps.opengeo.org

**Comment by jeffreyameyer** [comment]
I believe this is related / the same issue, but I've noticed a couple of other dynamics of opening the layer panel in the full screen map view:
http://mapstory.dev.opengeo.org/maps/166/view
1) the basemap layer switches from Wayne to Blue Marble when I open the layer sidepanel, regardless of whether I've changed the basemap myself or not... it happens automatically
2) when I switch the basemap back to wayne, the base map and the shapefile layers are out of alignment
3) the radio buttons do not reflect state when I click them - the base maps change, but there's no filled radio button to reflect that
I have a screen capture video: http://www.screenr.com/O0x8

**Comment by bartvde** [comment]
It's a different issue (actually likely multiple issues) but thanks for the detailed report.

**Comment by bartvde** [comment]
1) is caused when using the new layer manager, by the GeoExt function enforceOneVisible, maybe need to check with @ahocevar Will have a look now to see what I can find.

**Comment by jeffreyameyer** [comment]
Bart - should I be filing tickets for some of these issues against GeoExt or GeoNode? If so, how do we influence prioritization for Mapstory needs?

**Comment by bartvde** [comment]
Hey Jeff, no we will take care of that. If it is a priority for MapStory, we will make sure the underlying issues will get priority as well.

**Comment by bartvde** [comment]
The issue described here is caused by the second layer manager created by: https://github.com/opengeo/geonode/blob/mapstory/src/geonode-client/app/static/script/app/GeoExplorer/PlaybackToolbar.js#L119 (cc @mpriour)

**Comment by bartvde** [comment]
issue 1 and 3 are fixed with https://github.com/opengeo/geonode/commit/128ff59cbc1d7e90d480cd68239e25e17572cdd1

Please note that GeoExplorer/PlaybackToolbar.js depends on the global app, we should fix this in the future.

**Comment by bartvde** [comment]
The alignment issue could be caused by https://github.com/openlayers/openlayers/pull/393

**Comment by bartvde** [comment]
Okay, the show legend button in the composer now hides the layer manager, that is also not the intention. I wonder if the legend button of the playback toolbar should show up at all in the composer?

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/d95c87cee6260b896416408aa2d8873524e447fa
