### ISSUE TITLE
empty pop-up window appears on Add Layer

### ISSUE THREAD

**Issue by cmchen** [MapStory/mapstory-meta#283]
System: Windows 7 Pro 64-bit
Browser: Mozilla Firefox 11.0, Internet Explorer 9

Steps:
-Create a new mapstory (http://mapstory.dev.opengeo.org/maps/new)
-As soon as you get to that page, you are prompted to select a layer. Choose a layer>Add Layers>Done
-Expand left-hand side table of contents/layer window
-Press green "Add layers" button
-Pop-up opens>Choose a layer>Add Layers>Done
-Issue: Empty pop-up window appears

**Comment by bartvde** [comment]
I can reproduce, will look into it tomorrow.

**Comment by bartvde** [comment]
This seems to be caused by the recent Tool.js changes in gxp

**Comment by bartvde** [comment]
Fixed with https://github.com/opengeo/gxp/commit/ce815ca0a0eb410f4470b60997a46d99f621bb0e
