### ISSUE TITLE
Fix date format to work with BCE dates

### ISSUE THREAD

**Issue by mpriour** [MapStory/mapstory-meta#285]
The time slider uses the ExtJS format function (Date::format) and a format string to display the time tooltip. This function throws an error when using dates before 0 AD.
The function which sets the tooltip text is here:
https://github.com/opengeo/gxp/blob/master/src/script/widgets/slider/TimeSlider.js#L271

The default date format string is defined at:
https://github.com/opengeo/gxp/blob/master/src/script/widgets/slider/TimeSlider.js#L24

This format string is further refined depending on your data at:
https://github.com/opengeo/gxp/blob/master/src/script/widgets/PlaybackToolbar.js#L493

Additionally both have the TimeSlider and Playback Toolbar provide a `setTimeFormat` function, which might be useful but right now just sets `this.timeFormat = <Your Format String>`

**Comment by mpriour** [comment]
This can actually be tested without the need for @ischneider 's negative date handling code for the backend by modifying the `gxp.slider.TimeSlider::getThumbText` function to subtract 8e13 from any value before attempting to format the date. This will guarantee that you are working with negative year values.

**Comment by bartvde** [comment]
@mpriour I cannot reproduce, here is my diff:

```

index 520c0d6..7bb3a18 100644
--- a/src/script/widgets/slider/TimeSlider.js
+++ b/src/script/widgets/slider/TimeSlider.js
@@ -270,6 +270,7 @@ gxp.slider.TimeSlider = Ext.extend(Ext.slider.MultiSlider, {

     getThumbText: function(thumb) {
         if(thumb.slider.indexMap[thumb.index] != 'tail') {
+            thumb.value -= 8e13;
             return (new Date(thumb.value).format(thumb.slider.timeFormat));
         }
         else {
@@ -359,4 +360,4 @@ gxp.slider.TimeSlider = Ext.extend(Ext.slider.MultiSlider, {

 });

-Ext.reg('gxp_timeslider', gxp.slider.TimeSlider);
\ No newline at end of file
+Ext.reg('gxp_timeslider', gxp.slider.TimeSlider);
```

On layer geonode:DC I get -573 as the tip value.

**Comment by bartvde** [comment]
Even with Ian's instructions I am unable to set this up successfully locally. So I am unable to look into the issue at this moment.

**Comment by bartvde** [comment]
Finally able to reproduce. The javascript error is generated by the timeline panel, but only after it gets a rangemodified event from the playback toolbar with two invalid dates in it.

**Comment by mpriour** [comment]
Ill be available after 8am (GMT -5) if you want to look at this together.
On Apr 17, 2012 6:35 AM, "Bart van den Eijnden" <
reply@reply.github.com>
wrote:

**Comment by bartvde** [comment]
Hey @mpriour I think I've pinpointed the issue, the regex in OpenLayers.Date.parse is not matching, hence it returns an invalid date.

**Comment by bartvde** [comment]
See: https://github.com/openlayers/openlayers/pull/413

**Comment by bartvde** [comment]
See: https://github.com/opengeo/geonode/commit/d48831b95dd55031e0534ced27c823ed11742e3e

**Comment by bartvde** [comment]
A related issue is that the date & time options window is still complaining about invalid dates
