### ISSUE TITLE
scroll for more results not compatible in IE

### ISSUE THREAD

**Issue by cmchen** [MapStory/mapstory-meta#288]
System: Windows XP Pro 32-bit
Browser: Internet Explorer 8

System: Windows 7 Pro 64-bit
Browser: Internet Explorer 9

Cannot "Scroll down for more results" on map search page (http://mapstory.dev.opengeo.org/maps/search). Therefore, only 10 of 77 mapstories are displayed.

**Comment by ischneider** [comment]
Verified
