### ISSUE TITLE
turn on and off layers in map info page

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#290]
i recognize this wasn't in the original designs, but i think it makes sense to allow for turning off layers in the map info page.  i bring this up because maps.opengeo.org is down and so all maps with this basemap are pink tiles.  for example see:

http://mapstory.dev.opengeo.org/maps/134

can we add this functionality to the legend?  or on the layers tab?  what's your recommendation?

**Comment by bartvde** [comment]
This was done by @mpriour by adding a layer manager from the playback toolbar. Closing.
