### ISSUE TITLE
playback crashed chrome

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#291]
loaded: http://mapstory.dev.opengeo.org/maps/45/view
changed base layer from wayne to OSM
pressed play
noticed that the play button disappeared.  pressed play again. 
playback ended.  press play again.
chrome crashed. 

:(

**Comment by awright** [comment]
reloaded.  changed basemap from wayne to osm
pressed play
play back worked fine.  then chrome crashed. 

see screenshot: https://skitch.com/alyssawright/8x4wx/chome-chrash

**Comment by mpriour** [comment]
Finally fixed this one. There were at least 3 different problems happening, but the one that was really causing it was also the one causing the time slider to jump around unpredictably while dragging it on some maps. That has been made much smoother as a side effect of the fix required for this issue.
