### ISSUE TITLE
unselected layers turn on during playback

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#293]
go to: http://mapstory.dev.opengeo.org/maps/73/view
open legend and deselect nuclear test paths
press play

i would expect the nuclear test paths layer to remain unselected.  however when you press play the layer turns back on.

**Comment by mpriour** [comment]
Duplicate of #144.
@ahocevar provided a snippet which should solve it a while back and I forgot to implement it.

**Comment by mpriour** [comment]
the issue of layers turning on automatically has been solved by:
https://github.com/mpriour/TimeManager_OpenLayers-Addin/commit/b1cdfaac59c418606a77398506c8c01669bf2955

However, the feature of layers going from enabled or visible state to disabled or non-visible state and back automattically depending on if the time manager is ticking within the layer's available time range.

**Comment by bartvde** [comment]
Tested on dev and works fine now. Closing.
