### ISSUE TITLE
upload error

### ISSUE THREAD

**Issue by cmchen** [MapStory/mapstory-meta#298]
Not sure if this is related to/the same as Issue #258...

System: Windows 7 Pro 64-bit
Browser: Mozilla Firefox 11.0

Steps:
-Tried to upload a shapefile (http://mapstory.dev.opengeo.org/data/upload/)
-Got an upload error: duplicate key value violates unique constraint "maps_upload_pkey"

**Comment by jeffreyameyer** [comment]
I've also been unable to upload. Same OS and browser as cmchen. 

Two issues:
1) Upload appears to fail, which is a bummer. : )
2) I'm not told if there was an error or not, which leaves me wondering if it did upload, but maybe I just can't tell...

**Comment by jeffreyameyer** [comment]
Page: http://mapstory.dev.opengeo.org/data/upload/

My uploads fail in this manner:
- Load either individual shapefile files or .zip file
- Click upload
- Pops up: "Please wait" window
- Status bar starts to roll
- Goes away: "Please wait" window
- No visible indication that anything has happened, either good or bad
- No evidence of the uploaded info in any other status areas

Shapefiles were created in QGIS. Zip archives created by WinRAR.

**Comment by jeffreyameyer** [comment]
Here's a screencast of this issue. I've also repro'd it on Win32 and Chrome.

http://screenr.com/5Tx8

Still failing.
OS's tried: Win32, Win64, Ubuntu
Browsers tried: Chrome, Firefox, IE

I've successfully uploaded files to other geonode sites (see: http://worldmap.harvard.edu/maps/1606)

**Comment by jeffreyameyer** [comment]
Still no success here... I keep trying. Any updates? Any suggestions? Help! : )

**Comment by ischneider** [comment]
Hey Jeff, thanks for your video, report and patience - looking into it.

**Comment by ischneider** [comment]
Hey @jeffme, I tried uploading your civil_war_lines shapefile with success. There was one of those fun intermittent bugs blocking your progress. One hint - the date format you have in there will not be detected automatically and you will need to specify it manually during the time step. There are some fixes on the way to make this better but for the moment if date parsing goes bad, there is little in the way of useful feedback.

**Comment by ischneider** [comment]
The original issue has been resolved - primary key in upload model was the same as the importer session but when the session id was reset, this caused collisions.

The second issue was resolved by a restart - related to a known bug in geotools where the EPS database breaks.

Could not duplicate missing warnings unfortunately.
