### ISSUE TITLE
Time controls jump when collapsing sidebar

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#3]
Chris has reported seeing the timeline controls getting jumbled when the map composer sidebar is collapsed, making them unusable.

**Comment by mpriour** [comment]
Fixed with @ahocevar commit on Oct 7, 2011
https://github.com/opengeo/gxp/commit/6b4878ff163a42c55dc6b49427875767eb29f32e

**Comment by dwins** [comment]
cool!
