### ISSUE TITLE
Rollover for Feature Pop-up 

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#303]
UX suggestion:

instead of a click and popup, it would be nice to be able to roll-over a feature and see the info.  would offer smoother access to information.

**Comment by awright** [comment]
a pretty example: http://developmentseed.org/blog/2011/dec/06/design-decisions-mapping-temperature-precipitation-durban/

**Comment by awright** [comment]
info on ow they did it: http://mapbox.com/tilemill/docs/guides/google-charts/

**Comment by bartvde** [comment]
@awright Which popups are you referring to:
1. the ones that come from clicking an event in the timeline
2. the ones that come from clicking an annotation in the map
3. the ones that come from WMS GetFeatureInfo?

**Comment by awright** [comment]
number 3. the ones that come from WMS GetFeatureInfo

On Tue, Apr 10, 2012 at 3:25 AM, Bart van den Eijnden <
reply@reply.github.com

**Comment by bartvde** [comment]
Hover added for GetFeatureInfo with https://github.com/opengeo/geonode/commit/d77ea2daeaa503343d6974c26c8d223a5a3896ed
