### ISSUE TITLE
legend position a couple of pixels off

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#306]
as noted by tucker in 04/08/12, the legend is a couple of pixels above the map border.  should be positioned to be flush with the border:

https://skitch.com/alyssawright/8ta6y/legend

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/891d5377d51b997b0cc1a1fe6f618ef2e0ec95af

**Comment by bartvde** [comment]
Verified on dev, closing.
