### ISSUE TITLE
if legend is too long can't collapse

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#307]
look at the screenshot.  you'll see a pretty long legend.  and it overcovers the legend icon.  the recommendation is to have things collapsed by default.  specifically -- make sure to have all the basemaps collapsed (people don't need to change the basemap too much) the overlays should be expanded to see the list of layers, but all the rules can be collapsed (by default).  i'm open to other suggestions though. 

https://skitch.com/alyssawright/8t2x3/legend

also, could we rename overlay to storylayer?

**Comment by bartvde** [comment]
Looking into this one. I can set the base layer group to be not expanded by default, but this will yield other issues, such as the legend not being wide enough to show the text of the base layers.

I don't see a way currently to not have the legend show by default, it is not a tree node that can be expanded, it's just a box component associated with a tree node. Maybe we can limit its height and have it scroll if too big.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/36f6f4e1c06dc80c0aa4ffb9c73bb1d077374392 and https://github.com/opengeo/geonode/commit/ed665c447afc0f3c6d6539ce69af773ae5c905dc

Basically it's a fixed height now and will not be larger than the available space, we will provide scrollbars if things get too big.

**Comment by bartvde** [comment]
Verified using http://mapstory.dev.opengeo.org/maps/153 Closing.
