### ISSUE TITLE
expand timeline covers timecontrols

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#308]
open: http://mapstory.dev.opengeo.org/maps/117/view
expand timeline: https://skitch.com/alyssawright/8t246/timelinecontrols
covers up the time controls and can't play map story.

**Comment by bartvde** [comment]
This is used to work fine right? Not sure what happened.

**Comment by bartvde** [comment]
Okay, I think I found the issue, but it's not in the timeline, it's in the time/playback controls, when you expand a javascript error is raised in the time manager which causes the weird layout issue:

```
onTimeTick:function(a){var b=a.currentTime

b is undefined
```

**Comment by bartvde** [comment]
Btw, I cannot reproduce this locally unfortunately, I tried to monkey patch GXP with:

https://github.com/opengeo/gxp/commit/1d8476654e57fdb134fed6122df020f51773a98c

but seems like the update procedure for geonode-client is not working anymore? I can't get the change to show up in MapStory.js

**Comment by bartvde** [comment]
Okay I see now why the update does not run:

```
buildjs:
    [mkdir] Created dir: /home/geonode/geonode/src/geonode-client/build/geonode-client/WEB-INF/app/static/script
     [java] Error occurred during initialization of VM
     [java] java.lang.OutOfMemoryError: unable to create new native thread
```

**Comment by awright** [comment]
yes.  this used to work fine. i've seen a lot of oddities with the timeline since the time controls were last updated. matt was saying that they have not been playing well together.

**Comment by bartvde** [comment]
Yeah I think this needs both Matt and me to discuss unfortunately.
I cannot reproduce locally, and the dev server won't update anymore because of out of memory exceptions ...

**Comment by awright** [comment]
I can't seem to reproduce at the moment either.  Will let you know if it
happens again.

On Tue, Apr 10, 2012 at 5:41 AM, Bart van den Eijnden <
reply@reply.github.com

**Comment by bartvde** [comment]
This particular issue was fixed on dev.
