### ISSUE TITLE
timeline doesn't reposition

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#310]
had firefox open with firebug open. 
refreshed: http://mapstory.dev.opengeo.org/maps/117/view
closed out of firebug so could see map. 
timeline stayed on top of map: https://skitch.com/alyssawright/8t237/firebug

(ps.  i've noticed a lot of weirdness with the timeline. things not updating.  this is just one i can reproduce.)

**Comment by bartvde** [comment]
Probably related to #308

**Comment by bartvde** [comment]
This was fixed, works now on dev.
