### ISSUE TITLE
saved annotation doesn't close

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#311]
goto: http://mapstory.dev.opengeo.org/maps/117/view
added a note with a point geometry.
title: test
description: test, test
start time 01/01/1910
pressed save.  dialog didn't close out. 
https://skitch.com/alyssawright/8t256/map-viewer-geonode

**Comment by bartvde** [comment]
It closes for me @awright 

Any specific browser?
Any specific workflow?
Any javascript error in the console?

**Comment by awright** [comment]
i was in safari. and it was for a point note. i will try to reproduce (in a bit...).

**Comment by bartvde** [comment]
cannot reproduce again, please reopen @awright when you have a reproduceable test case.
