### ISSUE TITLE
Profile editing pages need clearer "return" context

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#312]
Data entry pages should help me find my way back to my prior location after editing content. For example, after uploading an avatar, instead of saying "Upload successful," perhaps it should just return me to the profile editing page? Or, at a minimum, there should be a "Back to profile editing" button. As it is right now, the user is left to guess that he or she should hit the back button or click on Profile, etc.

**Comment by cholmes** [comment]
Jeff, could you take this? I've been annoyed by this a few times.

**Comment by jj0hns0n** [comment]
No prob. Will do it now/ today

On Feb 25, 2013, at 12:53, Chris Holmes notifications@github.com wrote:

Jeff, could you take this? I've been annoyed by this a few times.

—
Reply to this email directly or view it on
GitHubhttps://github.com/opengeo/mapstory/issues/312#issuecomment-14074887.

**Comment by jj0hns0n** [comment]
I looked into this a bit and unfortunately those pages are controlled by an external app that we would have to fork and modify. I stopped looking at how to do it better for now, but I may be able to figure something else out. Will report back.

**Comment by ischneider** [comment]
Add 'next' param to form. Made look nicer, too.

**Comment by cholmes** [comment]
Looks good, ready to deploy I believe.

**Comment by cholmes** [comment]
Closing this. I think we could go further, as the profile edit doesn't have a nice way back to the profile page. But the avatar page does now have a return context.
