### ISSUE TITLE
Add data page needs more detailed instructions

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#313]
For example, there's a current warning that says, 
"Uploading of zip files is also supported. The zip file must contain the appropriate shapefiles (.shp,.dbf,.prj) in the top-level directory. "

It might be better to say:

"Uploading of shapefiles is supported. You can upload related shapefiles in a single .zip file or individual files. To upload individual files, enter the .shp file in the "Data" field, and you will be prompted for the other related files."

**Comment by jeffreyameyer** [comment]
Alternately, a feature to add multiple files at once might solve this problem even easier. For example, on geocommons, I can just select all related files at once and add them all with one click.

**Comment by ischneider** [comment]
Drag and drop supports multiple files for recent browsers.

Additional instructions added in the mean time as well as a manual page.

Closing for now, please reopen w/ more details if needed.
