### ISSUE TITLE
time attribute wont accept

### ISSUE THREAD

**Issue by ghost** [MapStory/mapstory-meta#315]
any idea why the time attribute in the following layer won't work?

http://mapstory.dev.opengeo.org/data/geonode:Santorum3

**Comment by bartvde** [comment]
There is no time information in the GeoServer WMS GetCapabilities so this is either a data or a GeoServer issue.

**Comment by bartvde** [comment]
Okay it seems the time columns have the wrong type (String):

START_TIME  String  true    0/0
END_TIME    String  true    0/0

@elasher how was this dataset created? Uploader?

**Comment by ghost** [comment]
yes, uploaded, then chose no time attribute.

the current format i have the time in is:
2010-07-27'T'12:00:00 

but can't figure out where it might be wrong. i believe im following the ISO 8601 format.

**Comment by ischneider** [comment]
closing for now
