### ISSUE TITLE
Should the default basemap have any borders on it?

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#316]
The borders are relative to a fixed point in time & not meaningful in older periods. For example, they distract from depictions of the territorial evolution of the states, such as Kentucky and West Virginia splitting off of Virginia, or the Erie Triangle joining Pennsylvania, etc.

**Comment by awright** [comment]
not sure what you mean here.  could you give an example map and a screenshot?

**Comment by jeffreyameyer** [comment]
Here they are:

With borders: http://flic.kr/p/bxsPxm
Without borders: http://flic.kr/p/bxsPy7
Showing Europe in 843 - Treaty of Verdun, along with 2012 borders - not good / confusing as it shows data from 2 unrelated time periods: http://flic.kr/p/bxsPyW

**Comment by jeffreyameyer** [comment]
Actually, this one is more illustrative - it shows the areas controlled by the Confederate States of America. On the base map, you can see West Virginia, Colorado, and a few other states that weren't around at the time shown in the timeline.

http://www.flickr.com/photos/70442209@N00/7066008247/

**Comment by awright** [comment]
can we add the chalk, graphite baselayers to maps? i believe they don't have any borders.

**Comment by bartvde** [comment]
@awright I just checked, and both chalk and graphite have borders as well.

**Comment by awright** [comment]
re-assigning to sam -- sam, we need a baselayer with no borders.

**Comment by sampepple** [comment]
Great Idea, and we can get something up shortly. I  have thought up about 5 basemaps which will be tailored to specific use cases like what Jeff has outlined above. Expect something by the end of the week. Stay Tuned

**Comment by jeffreyameyer** [comment]
Hi Sam - when you say expect something, is this on mapstory.org or the dev site? I'll keep my eyes open! Thanks, Jeff

**Comment by awright** [comment]
Right now we're making changes to the dev site.  We'll be putting a
schedule for updating the production server shortly.

On Wed, Apr 18, 2012 at 3:56 PM, Jeff Meyer <
reply@reply.github.com

**Comment by jeffreyameyer** [comment]
Excellent - I want to make sure I'm looking at the right place to see changes being made. Thanks!

**Comment by cholmes** [comment]
There is a satellite basemap that does not have borders. I think in time we should strive to get an awesome animating basemap, but for now these are the options we have, and it's lots of work to get new ones.
