### ISSUE TITLE
Is the expanded info pop up in search necessary?

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#321]
It seems that all the information in this pop up is already provided by image tips (the abstract).
The only other user interactions are the "add to favorites" button and the "add to maps in progress" buttons, which could be added to the map thumbnail. The map size in the more detail pop up isn't appreciably bigger.
http://www.dropmocks.com/mBiIZs

**Comment by cholmes** [comment]
Probably not super necessary, but I think most people don't use it, so not sure if we need to change it. Closing this for now.
