### ISSUE TITLE
pressing back one frame hangs browser

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#322]
Viewing this map:
http://mapstory.dev.opengeo.org/maps/162
I advanced several frames, one at a time, then went backwards. If the slider is at the beginning and an additional backwards click is made, everything hangs.

**Comment by mpriour** [comment]
i can't reproduce (I can get it to permanently switch the forward & back directions) but not to hang.

**Comment by mpriour** [comment]
Can't reproduce but testing did reveal another issue (#358)
