### ISSUE TITLE
zoom disappears after first use

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#323]
goto http://mapstory.org/maps/146
zoom in with the openalyers (+) 
the openlayers (+) and (-) disappears

**Comment by bartvde** [comment]
I cannot reproduce in Safari. Which browser? Any specifics to reproduce?

**Comment by bartvde** [comment]
Cannot reproduce in Chrome or Firefox either.

Closing. Please reopen if you have a reproduceable test case @awright
