### ISSUE TITLE
background color doesn't save

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#326]
i have a map with no background. if i change the background from gray to white and then press save, the background reverts back to gray.

**Comment by bartvde** [comment]
This was working the sprint, I need to check if this change https://github.com/opengeo/gxp/commit/5568b9d59b9831819908ce46b68782cb46a0e6e6 broke anything. Nothing else has changed AFAIK

**Comment by awright** [comment]
also, i suggest the default background color is white not gray. nothing looks good on such a dark background.

**Comment by bartvde** [comment]
I believe the default bgcolor is actually set in the CSS of the page somewhere, not in the code.

**Comment by bartvde** [comment]
This was indeed the change that broke things, fixed with: https://github.com/opengeo/gxp/commit/cad7c6b98b2aa44a5ba3e9433e2aefb150caf0a7

I am weary to change the default bgcolor to white (this should be done in the css of the pages anyway), it's not grey currently but a shade of brown, I guess this is to match the design?

**Comment by bartvde** [comment]
Hmm seeing a side-effect now and that is the map properties tool ends up in the wrong toolbar.

@mpriour can you explain why this change (https://github.com/opengeo/gxp/commit/5568b9d59b9831819908ce46b68782cb46a0e6e6) was made?

Maybe there is a different solution.

**Comment by mpriour** [comment]
Yes I don't want the tool button attempting to add itself to a non existent
place. Also I made an coresponding change in the app/GeoExplorer.js code.
You don't want/need most of the initialConfig info saved in the db, as that
is the part that is written in the code and saving that prevents changes in
the code properly reflecting in the app. The 'ptype' should have been
saved. That was an oversight.
On Apr 12, 2012 8:39 AM, "Bart van den Eijnden" <
reply@reply.github.com>
wrote:

**Comment by bartvde** [comment]
@mpriour but currently the tool ends up in the map's toolbar, and not in the main toolbar

**Comment by mpriour** [comment]
It should be going to the location specified by the 'actionTarget' property
in app/GeoExplorer.js
I'm in the Sponosor Day presentation right now. I'll have to look at that
more thoroughly  after this.

On Thu, Apr 12, 2012 at 9:30 AM, Bart van den Eijnden <
reply@reply.github.com

> wrote:
> 
> @mpriour but currently the tool ends up in the map's toolbar, and not in
> the main toolbar
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/opengeo/mapstory/issues/326#issuecomment-5090898

## 

Matt Priour
OpenGeo - http://opengeo.org/
Expert service straight from the developers

**Comment by bartvde** [comment]
actionTarget was not applied, fixed with https://github.com/opengeo/geonode/commit/32b2a1fd88ab193c8ff6d0577582d792fdabb842
