### ISSUE TITLE
clicking avatar on side bar doesnt work

### ISSUE THREAD

**Issue by ghost** [MapStory/mapstory-meta#327]
sends you to: http://www.iana.org/domains/example/

**Comment by bartvde** [comment]
@elasher do you mean on the storyteller page? Or somewhere else?

http://mapstory.dev.opengeo.org/mapstory/storyteller/everettlasher

I just checked now and the avatar is not clickable, which should be okay or not?

**Comment by cholmes** [comment]
Closing, could not reproduce.
