### ISSUE TITLE
Date & Time options window cutting off bottom attributes

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#330]
Sometimes (haven't figured out how to repro yet), the date & time options window will be sized (or content spaced improperly) such that the bottom menu options don't show up & there's no scroll bar to make them available.

http://www.dropmocks.com/mBiJaV
(apologies for the ghetto text...)

**Comment by bartvde** [comment]
Should be fixed with https://github.com/opengeo/gxp/commit/4540d75e5518e5622755be8c58f0ff504bbb9565
