### ISSUE TITLE
clicking on the map and the map title should trigger the same event

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#331]
Page: http://mapstory.dev.opengeo.org/storylayers/search

Current behavior:
- Click on a map, and you get the pop up with more detail, the add to favorite button, and the add to 
- Click on the text, and you go to the map

Untrained expected behavior:
- Click on the map or the text and be taken to the map

**Comment by ischneider** [comment]
Added 'more' button. In testing, will be deployed shortly.
