### ISSUE TITLE
full screen map view as default?

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#332]
I think it'd be much better. I've been using mapstory for a few days and only now noticed the "View this MapStory full screen" link.
It's what users want most. 
View info should be the optional screen, not the default.
Get people engaged in the maps as quickly as possible.

**Comment by cholmes** [comment]
There should now be more options to go to full screen, and you can now email full screen links. So going to close this for now, but it's probably worth revisiting in a redesign.
