### ISSUE TITLE
full screen userid / change password / logout text too high

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#333]
In the full screen map view, the userid / change password / and log out text are so high as to cross out of the top of the browser view pane. They should probably be dropped 10px or whatever looks best.

Also - not clear why change password is here at all. Seems like that could be kept on the settings page. I'm also noticing that github handles logout with a small icon and web tips.

See highlighted red box at: http://www.dropmocks.com/mBiOIj

**Comment by bartvde** [comment]
This has been fixed. Closing.
