### ISSUE TITLE
maximize use of web view pane for map

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#334]
and minimize screen real estate dedicated to anything else. My belief is that the map should be as close to as big as the browser screen as possible. 

Current view: http://www.dropmocks.com/mBiIrk
Expanded view: http://www.dropmocks.com/mBiILf
(again apologies for crude gimp'ing)

more map... it's kind of like more cowbell...

**Comment by cholmes** [comment]
This should be much  better in #full screen view in the next release. The 'view' one is also a bit bigger. Can do more in this direction, but I think we've got good progress in this next release.

**Comment by cholmes** [comment]
deployed on prod
