### ISSUE TITLE
Search page drop down disabled topics aren't distinct enough

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#339]
OS: Win64, browsers: Firefox, Opera

On: http://mapstory.org/mapstories/search

I originally thought I was having problems selecting Relevance or Popularity, which are both disabled="true".

The gray of these colors is dark enough to be confused with black, creating a frustrating user experience...

http://www.screenr.com/2rh8

**Comment by bartvde** [comment]
Relevance and Popularity work now so are not disabled anymore, so I assume this is not an issue anymore. Closing. Please reopen if I misinterpreted.
