### ISSUE TITLE
Wireframes for alternate themes

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#34]
#18 tracks the implementation

**Comment by scrollie** [comment]
Do these alternate themes apply only to user profiles and vanity pages (groups, portals, whatever) or elsewhere as well?

**Comment by dwins** [comment]
As I understand it a user should be able to enter the site through a given portal and have that theming "stick" for the session (not necessarily an actual webapp session.)  But it would be really good for @awright to confirm.

**Comment by awright** [comment]
yes. my understand is that the theme would stick to the entire session.

**Comment by scrollie** [comment]
What is the problem that this is trying to solve? Where does this use case originate?

**Comment by awright** [comment]
no longer relevant. might revisit at a later date.
