### ISSUE TITLE
add ajax login to composer

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#341]
Should we add ajax login to the composer as well (the redirect currently annoys me a bit)? Any thoughts @ischneider ?

**Comment by ischneider** [comment]
Yes, I suppose it is time to override this template, too. I'll take this one one, @bartvde

**Comment by ischneider** [comment]
@bartvde can you test? deployed to dev

**Comment by bartvde** [comment]
Works like a charm @ischneider
