### ISSUE TITLE
migration of annotations

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#344]
Annotations/timelines did not migrate over.  Am more than happy to reinput this data if easier. 

Right, it seems the underlying tables/featuretypes were not migrated to production.

<?xml version="1.0" encoding="UTF-8"?>
<ows:ExceptionReport version="1.0.0"
  xsi:schemaLocation="http://www.opengis.net/ows http://mapstory.org:80/geoserver/schemas/ows/1.0.0/owsExceptionReport.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ows="http://www.opengis.net/ows">
  <ows:Exception exceptionCode="NoApplicableCode">
    ows:ExceptionTextCould not find type: {http://geonode.org/}_map_117_annotations/ows:ExceptionText
  /ows:Exception
/ows:ExceptionReport

**Comment by rmarianski** [comment]
Annotation for map 117 came over. I didn't copy any others over though because it was much easier to just copy this one over. Are there any other annotations for maps that are important to have?

**Comment by awright** [comment]
Thank you! There's one for killer bees that Matt worked on. Can you check with him for the number?

**Comment by rmarianski** [comment]
Looks like this has some other underlyilng problems if we don't systematically migrate all the annotations over. Ticket for follow up here: #363

**Comment by rmarianski** [comment]
For now I'll try to migrate all annotations that don't exist from the dev server

**Comment by rmarianski** [comment]
I've migrated all the annotations from the dev server over to production. I also migrated map 148 (the bees map with the annotations).

The following maps still don't have annotations on production. They either don't have an annotations layer on dev or they don't have a corresponding map object on dev.
http://mapstory.dev.opengeo.org/maps/10
http://mapstory.dev.opengeo.org/maps/14
http://mapstory.dev.opengeo.org/maps/172
http://mapstory.dev.opengeo.org/maps/106
http://mapstory.dev.opengeo.org/maps/107

**Comment by awright** [comment]
I have a bad internet connection at the moment.  Can you confirm that map
117 has annotations?

It should be a subway map with both items on the timeline and animated
pop-ups.

Thank you.

On Thu, Apr 26, 2012 at 8:38 PM, Robert Marianski <
reply@reply.github.com

**Comment by rmarianski** [comment]
I see both items in the timeline below and animated popups when viewing production.
http://mapstory.org/maps/117/view
