### ISSUE TITLE
Layer view page has an edit map button

### ISSUE THREAD

**Issue by iwillig** [MapStory/mapstory-meta#346]
Currently the layer page on mapstory has an edit map button on the time controls. This link leads the url to an 404 page.

For example, http://mapstory.org/data/geonode:civil_war_battles_timeenabled has the edit map button but as you can see this is an layer page.

**Comment by mpriour** [comment]
to be addressed this week with a new GeoNodeViewer subclass that is specific to the layer info / preview page

**Comment by mpriour** [comment]
this was addressed in https://github.com/opengeo/mapstory/commit/11a6b39c262ea2fa78c2ea0d96c05d9f5625314b
