### ISSUE TITLE
thumbnail and abstract g+ link

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#347]
email from chris 04/16:

I tried facebook too. The main disappointment there was how little
info showed up in the post. Would be much better to have a thumbnail,
title and blurb. See https://skitch.com/cholmes/816qa/2-chris-holmes
G+ did better, but it'd be good to figure out how to remove the
boilerplate about who uploaded and 'abstract' text, so it just puts
the blurb right in the feed.

(ian, reassign if appropriate.)

**Comment by ischneider** [comment]
For the G+ link, this appears to describe: https://developers.google.com/+/plugins/+1button/?hl=en#plus-snippet

**Comment by cholmes** [comment]
#501 handles the facebook part of this. So this can just be about google plus, getting it so the result of a g+ share is better. See like https://plus.google.com/u/0/105927010353605742300/posts/YhJHtjyTPQg - first text there should just be the actual abstract.

**Comment by jj0hns0n** [comment]
Now that we are using sharethis, this is handled by the open graph tags. Needed to add in the description which should help it work better on FB too.
![Share on Google ](https://f.cloud.github.com/assets/506078/326637/6339ec80-9b3f-11e2-9648-c66c4e9ca937.png)
![Google ](https://f.cloud.github.com/assets/506078/326638/63395b30-9b3f-11e2-86ff-54c1614436f9.png)

**Comment by cholmes** [comment]
Assigning to me for testing.

**Comment by cholmes** [comment]
Description is working a bit different now, but I think that's probably g+, not us.
