### ISSUE TITLE
put full name for "about this storyteller" 

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#348]
as suggested by cholmes on 04/16

The 'about the storyteller' is just the username, while the full name
is used on the 'by this story teller' links. See
https://skitch.com/cholmes/8uyfb/mapstory-united-states-post-offices
would be good to use full name for both.

**Comment by ischneider** [comment]
also see #612 and #623

**Comment by cholmes** [comment]
Confirmed on prod.
