### ISSUE TITLE
mailto link should work

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#349]
email from cholmes (04/16)

And right now it's a half-assed thing where it's a mailto link that is blank - like I can click on the email link but then it doesn't actually prepopulate my email. If we truly want that to be a link then it should work right. 

(even better would be to hook up the private messaging stuff and just
give a way to message through the system.)

https://skitch.com/cholmes/8uyfw/mapstory-pgudipudi

**Comment by bartvde** [comment]
There is no e-mail address anymore on the storyteller page so closing this one.
