### ISSUE TITLE
changing range does not work anymore

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#351]
To reproduce:
1. open up maps/new and add a time-enabled layer.
2. open up the time properties dialog
3. change the start time
4. you'll see a javascript error pasted below

```
this.timeManager.currentTime is undefined
http://localhost:8081/script/@/app/static/externals/gxp/src/script/widgets/slider/TimeSlider.js
Line 194
```

**Comment by mpriour** [comment]
thanks for the report. set as high priority fix.

**Comment by mpriour** [comment]
Was previously fixed but got reverted somehow. Fixed again in:
https://github.com/mpriour/TimeManager_OpenLayers-Addin/commit/77832925e2bc042da1d0a0790546d842adbca001

**Comment by bartvde** [comment]
Confirmed this is working now.
