### ISSUE TITLE
No available layers when creating a new story

### ISSUE THREAD

**Issue by ghost** [MapStory/mapstory-meta#352]
the add layers option doesn't seem to go to the correct server.

**Comment by bartvde** [comment]
@elasher Is this on production? Was it a glitch or is it still happening?

**Comment by ghost** [comment]
This is on production and is still happening. I don't know what the url to the wms is.

http://www.dropmocks.com/mBiQYU

**Comment by ghost** [comment]
And switching to My GeoServer WMS doesn't have anything either

**Comment by ghost** [comment]
@bartvde part of this issue has been resolved. when clicking create a new mapstory on the landing page, this is fine, but when creating a new story from a storylayer page, this is still a problem.

**Comment by ghost** [comment]
this appears to be an issue again

**Comment by ischneider** [comment]
get capabilities document hosed again - fixed @elasher
