### ISSUE TITLE
Styled Layer Descriptor

### ISSUE THREAD

**Issue by ghost** [MapStory/mapstory-meta#356]
is there a way to extract this information if you created a style on the site?

**Comment by jeffreyameyer** [comment]
Right now, this seems like one of the biggest areas of opportunity for making vector data even more portable, in addition to figuring out a standard for temporal tagging.  +1 for style portability, to inlcude line, fill, labelling, etc.

**Comment by ischneider** [comment]
SLD download is supported in the layer page (download tab) for authenticated users.
