### ISSUE TITLE
Wireframes for annotations

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#36]
Important workflows include:
- Editing annotations by interacting with the map  (see #10)
- Editing annotations by interacting with the timeline (see #11)

**Comment by scrollie** [comment]
How's this for wireframes? https://github.com/opengeo/mapstory/wiki/Design#wiki-notes

Note, there is also an animated wireframe here (requires Flash): http://projects.opengeo.org/common/design/mapstory-notes-animation-20111031.swf
