### ISSUE TITLE
Can't access Layer Properties

### ISSUE THREAD

**Issue by ghost** [MapStory/mapstory-meta#360]
http://www.dropmocks.com/mBieQn

**Comment by bartvde** [comment]
I can reproduce this one. Will look into it.

**Comment by bartvde** [comment]
The error I am getting is:

app.tools['playback-tool'] is undefined
http://localhost:8081/script/@/app/static/script/app/GeoExplorer/TimeLayerPanel.js
Line 30

but I am also not getting the playback toolbar anymore in the application, which could be the root cause. Need to check with @mpriour

**Comment by bartvde** [comment]
This should have been fixed with 4559d3f9e8c4a7992bc1c2288fab8c8762b1cee8

**Comment by bartvde** [comment]
Works fine on dev now, closing.
