### ISSUE TITLE
unable to upload shapefiles to mapstory after downloading them from mapstory

### ISSUE THREAD

**Issue by jeffreyameyer** [MapStory/mapstory-meta#364]
In an attempt to figure out why I'm unable to upload shapefiles of any sort, I've put together a recording of the following workflow:
- download a shapefile from a mapstory storylayer
- attempt to upload that same shapefile
- no luck

site: http://mapstory.dev.opengeo.org/
browser: firefox latest
os: win7 ultimate x64

http://www.screenr.com/ItC8

**Comment by jeffreyameyer** [comment]
Also - Ian, thanks for the follow up on: https://github.com/opengeo/mapstory/issues/298. I was still having problems, so I figured they were related to a separate root cause, hence this ticket.

**Comment by ghost** [comment]
it appears that you can't upload anything right now...

"Error in upload step : Could not save the layer Buildings, there was an upload error: ('Server error', 500, 'Error updating context:null')"

**Comment by jeffreyameyer** [comment]
Ha! Well, with a layer like "Buildings," I'm intrigued to see what you're working on! My guess is that these are unrelated, as I've been having this problem for a while now. I have yet to successfully upload any shapefiles.... Hope all's well in AZ!

**Comment by cholmes** [comment]
So I just tried to reproduce this. I think the issue is that zip uploads don't work. Selecting the individual files from a mapstory shapefile export worked fine for me. So should maybe readjust the title to failure to upload zipped shapefiles.

**Comment by ischneider** [comment]
Yes, the extra file in the zip causes errors.

**Comment by ischneider** [comment]
Now handles the following better:
- no valid files uploaded (like a zip with non-spatial/unrecognized files)
- valid files w/ superfluous non-spatial files (as per this issue)
- attempt to upload more than one vector file in a zip

**Comment by ischneider** [comment]
Still an issue with extra file :(

**Comment by ischneider** [comment]
Now, should be fixed.

**Comment by ischneider** [comment]
Fixed in multiple places, closing for now.
