### ISSUE TITLE
cannot create new map using single layer

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#365]
Go to a layer page. 
Press 'Create a Story using this StoryLayer' link in upper right.
For example: http://mapstory.dev.opengeo.org/maps/new?layer=geonode:Market_Capitalization
console logs message

The problem is that the client is using the virtual service endpoint. This no longer provides the geonode prefix. Removing the prefix from the query parameter does not work either as the request to the virtual service endpoint fails.

**Comment by mpriour** [comment]
This seems to be fixed. I fixed this behavior in the client side code and it also seems to be fixed in python as well.
Are there any current cases in which this doesn't work
