### ISSUE TITLE
annotations dialog date chooser not helpful

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#367]
A date chooser is probably not the best user interface here - from my experience, this is most useful when booking flights, etc. Most people will probably want to copy/paste timestamps.

Ideally, date and time would be a single field.

Another nice enhancement would be the addition of a 'current map date' button that obtains the value from the time control

**Comment by mpriour** [comment]
The date chooser can be suppressed and copy current map date used instead.

Alternatively, the date chooser could be initialized to start at the current map time, rather than today's date

**Comment by bartvde** [comment]
Yeah hiding the trigger is easy. However if you ask me it's not doing any harm being there, it's an easy way to look up what date format to use for a user IMHO.

**Comment by bartvde** [comment]
I can't really see a clean way to get to the current map date from the feature editor ...

**Comment by cholmes** [comment]
@sshyu - not sure if you've thought about this yet, but would be great if you had thoughts / mockups on a better way for people to enter / select the date.

**Comment by cholmes** [comment]
#717 is related. Will leave them both open, as this is asking for a bit more.
