### ISSUE TITLE
Add "take thumbnail snapshot" tool to map & layer info pages

### ISSUE THREAD

**Issue by mpriour** [MapStory/mapstory-meta#368]
Both the map info & layer info pages should provide the user with a UI element either in the actual playback toolbar or in the horizontal actions list under the map to save the current map / layer state and take a thumbnail of it at the same time.

**Comment by ischneider** [comment]
Any discussion might be here:
https://groups.google.com/a/opengeo.org/d/topic/dev-mapstory/hhFYXpmzkxs/discussion

**Comment by cholmes** [comment]
I think we have ability to take a thumbnail now? Closing this, reopen if this is about something else, like just adding an extra ui element to take the thumbnail.
