### ISSUE TITLE
Logged out on Layer Pages

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#369]
StoryLayer: http://mapstory.dev.opengeo.org/data/geonode:irene_11_pts_interval
1. Logged in as admin https://skitch.com/alyssawright/8h479/login-home
2. Went to layer info page and was logged out https://skitch.com/alyssawright/8h46b/login-layer-page
3. Went to full screen still logged out
4. Went to "search" was then logged in.

**Comment by awright** [comment]
Logged in when added a new story layer, http://mapstory.dev.opengeo.org/data/geonode:mexmurder_w_rank

**Comment by awright** [comment]
Closed and reloaded the original map (http://mapstory.dev.opengeo.org/data/geonode:irene_11_pts_interval) and was logged in.  Some caching thing on my browser?

**Comment by ischneider** [comment]
@awright I cannot duplicate. We're you at a hotel or other location that may have had a proxy in place?

**Comment by awright** [comment]
just my apartment. will report if i see again.

**Comment by bartvde** [comment]
I also cannot reproduce this one. Closing.
