### ISSUE TITLE
Awkward transition exiting from full screen

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#370]
Full screen looks good, but I think we can do some small things to improve it greatly.  Let's go through the layout this early week. 

https://skitch.com/alyssawright/8h46c/full-screen

**Comment by awright** [comment]
Take for instance this workflow:
1. From layer info page, go to full screen mode
2. There is no back button, only the minimize screen.
3. Can't find where to edit -- but then see the "create a map" button on the bottom
4. Select create a map, and am redirected to the editor.
5. Click back expecting to go to full screen mode, but am redirected to the layer info page.

**Comment by cholmes** [comment]
Closing this, as most of these are fixed or worked around. Back now goes back with the full screen hash, there's an 'edit' button on map pages.
