### ISSUE TITLE
No playback for mexmurder_w_rank

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#371]
1. Openlayer layer info page: http://mapstory.dev.opengeo.org/data/geonode:mexmurder_w_rank
2. Press play, time controls advanced but no animation.
3. Though it maybe it was a styling issue, so went to editor
4. Styling fine in editor https://skitch.com/alyssawright/8h463/mexmurder-w-rank

**Comment by mpriour** [comment]
Actually this is a styling issue. The style specifies several scale dependent symbol rules. However, there is no symbol set for the default scale of the preview window. Putting in a extra set of symbols for the any scale larger than the ones already defined will fix this.

**Comment by cholmes** [comment]
Closing, as it sounds like just a styling issue, and this layer is gone.
