### ISSUE TITLE
Playback stalls for Pashtun Area Tribal Maps

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#372]
1. Loaded http://mapstory.dev.opengeo.org/data/geonode:AFPK_Merge_FY
2. Pressed play
3. Animation moved smoothly and then stopped on June 1998 for about 10/20 seconds
4. Unexpected, but thought it might be the data, so let it loop.  
5. Animation stalled again in November 2003

If there's some buffering going on, we need to give feedback to the user.

**Comment by mpriour** [comment]
I can't even get this layer preview map page to load.
I get a "server error occured...." page
Maybe @ischneider can shed some light on this

**Comment by ischneider** [comment]
This was related to the hitcount application I pulled in though I'm not sure how this particular state was reached. Looking into how to prevent it...

After resolving the hitcount issue, playback appeared to work. @mpriour , @awright can you verify and close?

**Comment by bartvde** [comment]
works fine for me on dev, closing.
