### ISSUE TITLE
Can't create new map from full screen mode on layer page

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#373]
Using the Pashtun Area Tribal Maps map again. 
1. On layer info page, press play
2. During playback, went to full screen mode
3. There is no "create a map button" https://skitch.com/alyssawright/8h49q/create-a-map

**Comment by mpriour** [comment]
There is not supposed to be.
The image attached to #370 shows a create map button. However you should not see that in full screen mode. It should really be full screen. The mapstory header should be displayed and under that the map.
The image attached here shows what I would expect.

**Comment by bartvde** [comment]
So what is the resolution on this ticket? Mark as WONTFIX?

**Comment by awright** [comment]
I'm assigning it to a new milestone.

**Comment by awright** [comment]
actually bart -- i can't seem to do that on my phone. can you assign it to 'the future' milestone. thank you.

**Comment by bartvde** [comment]
sure done

**Comment by awright** [comment]
thank you!

**Comment by cholmes** [comment]
I think it would be good to let users create a new map from full screen mode. 

Doing the 'edit' button the same as on a map full screen makes sense to me. And make it so all have that edit link (the little pen icon), as it just makes a new map for them. So like that edit link should do the same as clicking on 'Create a Story using this StoryLayer' on the small map layer page.

**Comment by ischneider** [comment]
Closing - will be using new platform
