### ISSUE TITLE
Can't edit styles from layer tree

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#374]
http://mapstory.dev.opengeo.org/data/geonode:AFPK_Merge_FY
1. On layer info page,selected "create a map"
2. Expanded legend. 
3. Right clicked on layer, and https://skitch.com/alyssawright/8h493/edit-styles
4. I selected the layer properties option and edited styles from there https://skitch.com/alyssawright/8h5yy/editing-styles

**Comment by mpriour** [comment]
You shouldn't be able to edit styles for that layer AT ALL.
We actually need to look into why / how you were able to do it from the layer properties.
Maybe Admin is given special rights and can basically edit anyone's styles. However, no other user than Everett should be able to edit any styles for that layer.

**Comment by bartvde** [comment]
Right so the issue here is that editing styles should not be allowed in this case from the layer properties dialog as well.

**Comment by bartvde** [comment]
It seems the styler plugin is not enabled because of the matching of layer name after a describe layer request, one of the layer names is without the prefix, so it does not match.

**Comment by bartvde** [comment]
The last mentioned issue only appears when using a URL like: http://localhost:8000/maps/new?layer=geonode:cheng_haokin

**Comment by bartvde** [comment]
I'd argue this should be fixed on the GeoServer side, but I've sent an e-mail to mapstory-dev to put this up for discussion.

**Comment by bartvde** [comment]
@jdeolive just confirmed that this should be fixed on the GeoServer side.

**Comment by ischneider** [comment]
Just waiting for changes in geoserver - https://github.com/geoserver/geoserver/pull/12

**Comment by ischneider** [comment]
Fixed
