### ISSUE TITLE
Can't see symbol preview

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#376]
https://skitch.com/alyssawright/8h5yh/symbol-preview

**Comment by mpriour** [comment]
I'm only seeing this on some maps. Will need to investigate it more. Maybe @bartvde might have some insight as to why this would happen.

**Comment by bartvde** [comment]
IIRC there was a change in OpenLayers causing this. So I think we should update openlayers.

See also:

https://github.com/openlayers/openlayers/commit/120cc0680daad4617d815e70ae207d988085343f

**Comment by bartvde** [comment]
Right this is fixed.
