### ISSUE TITLE
No legend or full screen mode for static layers

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#377]
see: http://mapstory.dev.opengeo.org/data/geonode:Santorum3

we haven't accounted for the use case of static layers.  since all info is on the time controls and there are no time controls on static layers.  see https://skitch.com/alyssawright/8h5ny/no-controls

**Comment by bartvde** [comment]
finished this right now. Toolbar will show, but time-related functions will be disabled. Seems like the cleanest and easiest way to do this currently without changing too much.

**Comment by bartvde** [comment]
Verified on dev environment, works now. Closing.

**Comment by bartvde** [comment]
Reverted this change see #381 for the discussion.

**Comment by cholmes** [comment]
Would be good to get this working, so static layers don't look totally broken.

**Comment by ischneider** [comment]
Closing - old UI
