### ISSUE TITLE
Favorites and MapStories in Progress don't show in search results

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#379]
[Walmart & Target Test](http://mapstory.dev.opengeo.org/maps/138) is a favorite map and did not show up in a search for "Walmart & Target Test"

[bc map with annotations](http://mapstory.dev.opengeo.org/maps/187) is a map in progress and did not show up in a search for "bc map with annotations"

**Comment by ischneider** [comment]
I cannot duplicate the first though it is possible it showed up lower in the results based upon the sorting (the word 'test' will match many others).

Maps in progress do not show up in search results.
