### ISSUE TITLE
Wireframe for hand digitization

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#38]
Elsewhere this is know as general layer creation and editing - user-defined schema and a ui for feature editing, creation, deletion.  See #19

**Comment by awright** [comment]
closed and addressed in an email by rollie:

I've been working through some ideas (alongside Matt and Andreas) and have some (very) rough animations to show some of them. They are different approaches to the same problem and, while not mutually exclusive, these draft animations don't make any effort to show how they could be made compatible.

Editing and authoring via the table (https://hoth.openplans.org/opengeo/design/GeoNode/MapStory/mapstory-authoring-20111215.swf) demonstrates non-persistent drawing tools that allow a user to draw features onto the map and then provides a lightly-structured means of adding attributes to those features.

Editing and authoring via a pop-up (https://hoth.openplans.org/opengeo/design/GeoNode/MapStory/mapstory-authoring-20111216.swf) demonstrates persistent drawing tools that allow a user to draw features onto the map and then provides structured, in-context pop-ups for adding attributes to those features.

In either of the above cases, the start time should default to the time of the currently shown frame, if applicable.

Structured guidance when creating a new mapstory is assumed by both of the above animations in the form of a dialog (though it could be in the side panel, as Alyssa alludes to below) that prompts the user to add existing layers, upload data, or draw a new layer when first creating a mapstory. Selecting the option to add an existing layer could open the Layers pane and begin the 'Available layers' workflow; selecting the option to upload a layer could expand the Layers pane and begin the uploading workflow; selecting the option to create a new layer could create a new layer (inheriting the metadata for the map as specified in the new map dialog?), then expand the drawing tools (and, if appropriate, the table). Not pictured is an idea to expand the Add Layers button (from the Layers pane) into a drop-down that includes the same three options listed above.

Andreas and I also discussed some specific ways we could handle drawing lines that I will paste here for posterity:
"I think it makes more sense to let the user draw the line. Then it can be split, and each "sub-line" can be assigned a different time span."
"Or with snapping we don't even pay special attention to the case of a line that has segments with different time spans. You just draw a segment, assign it a time span. You still have the "draw line" tool active, snap to the vertex of the previous line you want to connect to, and can continue. So I guess my favorite workflow would be a simple line drawing tool with snapping enabled."

As always, feedback is encouraged.

—R
