### ISSUE TITLE
Not sure how to minimize "more" info in search results

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#380]
1. Searched for BC Date Test2
2. Clicked on the "More" arrow
3. Abstract information expanded below.  
4. Clicked up the upward arrow, expecting the more information to minimize.  Nothing happens. 

https://skitch.com/alyssawright/8h5dh/minimize-more

**Comment by ischneider** [comment]
Added an X button as per the original wireframes, page 5.
