### ISSUE TITLE
Cant edit static maps

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#381]
http://mapstory.dev.opengeo.org/maps/184

No way to access map composer from maps that don't have time animation.

**Comment by bartvde** [comment]
@awright what about the link in the top right of the page "View this MapStory fullscreen" that brings me to the composer.

**Comment by bartvde** [comment]
looking into this one

**Comment by bartvde** [comment]
This was done wrt #377 the Edit this Map button will be enabled as well.

**Comment by bartvde** [comment]
Okay I do see one issue with the approach I have taken and that is when adding a time-enabled layer to a static map a javascript error will occur:

TypeError: this.range is null
http://localhost:8081/script/@/app/static/externals/TimeManager/trunk/lib/OpenLayers/Control/TimeManager.js
Line 503

but maybe setRange should deal with the situation where there is no oldRange?

@mpriour any thoughts on this?

**Comment by bartvde** [comment]
hmm after patching the above the next error occurs so I am not sure if this was such a good idea to have the playback toolbar be in the application but being disabled ....

TypeError: thumb.slider.indexMap is null
http://localhost:8081/script/@/app/static/externals/gxp/src/script/widgets/slider/TimeSlider.js
Line 279

**Comment by bartvde** [comment]
After fixing the thumb issue I get a weird tooltip on the time slider saying Tuesday Feb 03 -251540 for conflicts, so I think my general conclusion is that this is not a good idea, and I am gonna revert the fix for static maps.

**Comment by bartvde** [comment]
Okay reverted.

**Comment by cholmes** [comment]
Closing this, as it overlaps enough with #377 Though this issue has more info as to why things are messed up for that.
