### ISSUE TITLE
points not appearing in timeline

### ISSUE THREAD

**Issue by cmchen** [MapStory/mapstory-meta#382]
System: Windows 7 Pro 64 bit
Browser: Mozilla Firefox 12.0

Steps:
-Create a new map from a storylayer (http://mapstory.dev.opengeo.org/maps/new?layer=geonode:exams)
-Expand SIMILE timeline
-Under the Layers dropdown, press the checkbox to select/turn-on the layer 
-Under the Label dropdown, select an attribute to display
-Issue: Expected to see points appear in the timeline area, but it is empty still. Firebug says, "this.layerLookup[c]  is undefined"

**Comment by bartvde** [comment]
I am now getting different behavior (no timeline at all), it seems the layer is not time-enabled anymore since the playback tool also does not show up. Any idea what changed on the layer @cmchen ?

**Comment by cmchen** [comment]
System: Windows 7 Pro 64 bit
Browser: Firefox 13.0.1

I'm not sure what happened to the "exams" layer, but I am also no longer able to play it. I seem to be seeing this issue (no playback timeline appears) with multiple other layers as well...typically in older layers and not in recently created ones. Actually, I am able to play the map on the preview page (http://mapstory.dev.opengeo.org/maps/5 or http://mapstory.dev.opengeo.org/maps/34) but when I move to the full screen page, the timeline does not appear (http://mapstory.dev.opengeo.org/maps/5/view or http://mapstory.dev.opengeo.org/maps/34/view). Similarly, the storylayer page for the "exams" layer (http://mapstory.dev.opengeo.org/data/geonode:exams) is also able to playback successfully, but can't in the new map page (http://mapstory.dev.opengeo.org/maps/new?layer=geonode:exams).

**Comment by bartvde** [comment]
I am now able to reproduce your initial issue (though I don't get the layerLookup error, but the timeline is empty) locally and will look into it. I can see the hitCount query go off and return features, but the features itself are not being retrieved.

**Comment by bartvde** [comment]
Somehow the BBOX strategy refuses to get data.

**Comment by bartvde** [comment]
Okay this should have been fixed with https://github.com/opengeo/gxp/commit/3c221ffc55ffecb95c6d48f2b98d4f852bd8a59c but it's not yet on the dev server for testing.

**Comment by bartvde** [comment]
Hmm still an issue on dev environment, will have another look now.

**Comment by bartvde** [comment]
Okay see the issue now http://mapstory.dev.opengeo.org/maps/time_info.json?&_dc=1343130606708&layer=exams returns {}

**Comment by bartvde** [comment]
Whereas http://mapstory.dev.opengeo.org/maps/time_info.json?&_dc=1343130606708&layer=geonode:exams works fine

**Comment by bartvde** [comment]
depends on #392

**Comment by bartvde** [comment]
tested on dev and working fine now, closing.
