### ISSUE TITLE
long loading time for ming dynasty map

### ISSUE THREAD

**Issue by rmarianski** [MapStory/mapstory-meta#383]
http://mapstory.dev.opengeo.org/maps/10

I had originally thought that the map just didn't load, but it looks like it is just taking a really long time for it to do so. I'm using firefox. Other maps load much faster for me.

**Comment by bartvde** [comment]
This map does not make use of lazy loading and hence is slow (GetCapabilities takes long). Not sure yet why though.

**Comment by bartvde** [comment]
Okay, resaving the map fixes the issue, in this case the GetCapabilities JSON blob is stored in the map config and it's fast again.

**Comment by rmarianski** [comment]
Confirmed that this is fast now. Thanks!
