### ISSUE TITLE
embed map improvements

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#384]
The embedded map link was broken. I added a template override that just uses the view template, though this needs refinement.

The embedded map should:
- [x] show the playback controls, the timeline and legend. 
- [x] have no editing tools, login link, etc
- [x] have a link to the map info page and mapstory
- [x] not display the fullscreen action
- [x] legend font color match normal view
- [x] rounded corners

The embed template is here (extracted from geonode on purpose):
https://github.com/opengeo/mapstory/blob/master/templates/maps/embed.html

**Comment by bartvde** [comment]
getting rid of the toolbar I did with some css in the viewer:

#msmap .x-panel-tbar {
    display: none;
}

Now looking into how to get the timeline in there.
Also we need to get rid of the expand button in the playback toolbar.

**Comment by bartvde** [comment]
To show the timeline we can do this with a portalready listener:

```
var config = Ext.apply({{config}}, {
        listeners: {
            'portalready': function() {
               Ext.getCmp('timeline-container').show();
               app.portal.doLayout();
           }
        }
    });
    app = new mapstory.Viewer(config);
```

it should pop up automatically if there are annotations.

**Comment by bartvde** [comment]
Hmm now how to get rid of that toggle-size button without changing the code ....

**Comment by bartvde** [comment]
Okay this kind-of works but needs changes for @iwillig's code since it will try to toggle the size even if there is no toggleSize button. Ivan, should we protect your code with if (this.playbackActions['togglesize']) { or do you have other suggestions on how to handle this more gracefully. We could alternatively also protect all your methods to check if the toggle button exists ...

```
var config = Ext.apply({{config}}, {
        listeners: {
            'portalready': function() {
                app.tools['playback-tool'].outputConfig.playbackActions = [
                    "play","slider","loop","fastforward","prev","next",
                    {xtype: "tbspacer"},"legend",{xtype:"tbfill"},
                    "settings",{xtype: "tbspacer"}
               ];
               Ext.getCmp('timeline-container').show();
               app.portal.doLayout();
           }
        }
    });
    app = new mapstory.Viewer(config);
```

**Comment by iwillig** [comment]
I think your first suggestion will work, however I would really like to come up with a better solution for how we use this mapstory view. As now I think this same code is used in 5 places, but there is no way of telling from within the code how these methods should be run. 

Not sure if that makes sense, but this related the conversation we had the other day. 

Find me on IRC today?

**Comment by ischneider** [comment]
Ready for testing on dev. Thanks @iwillig and @bartvde

**Comment by iwillig** [comment]
Did we push this to dev yet? Because if so its still broken.

**Comment by iwillig** [comment]
Cool.

**Comment by iwillig** [comment]
Nice, it looking better. Just noticed that the legend font colors have to be fixed.

**Comment by iwillig** [comment]
Can we close this ticket?
