### ISSUE TITLE
first WMS request does not have TIME parameter

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#390]
as reported by @ischneider July 16

I've set up the following layer to be cached in GWC. Not sure what
changed to make this work now (before I was getting grid set error
messages in the http header responses) but caching appears to be
working.

http://mapstory.dev.opengeo.org/data/geonode:BE_Colonies?tests=2

There appear to be other issues (perhaps you can verify Matt?):
1) regression - upon load, a request is made without a TIME parameter
- this causes pink tiles in GWC. I thought that this had been resolved
  earlier.

**Comment by mpriour** [comment]
This had not been resolved earlier, but can be easily resolved (I think)
I'll make the appropriate change

**Comment by mpriour** [comment]
see https://github.com/opengeo/gxp/commit/b28b0546a29d82be747d66dd4739bbeef76cacb1

**Comment by bartvde** [comment]
@mpriour I just updated the gxp dependency and updated the dev server but I am still seeing pink tiles on http://mapstory.dev.opengeo.org/data/geonode:BE_Colonies?tests=2

**Comment by mpriour** [comment]
i updated the wrong branch and other stupid git mistakes.
the correct fixes are in the correct place now but the issue is still there.

**Comment by bartvde** [comment]
This works fine now, closing.
