### ISSUE TITLE
Wayne baselayer requests go off on startup

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#391]
as reported by @ischneider July 16th

I've set up the following layer to be cached in GWC. Not sure what
changed to make this work now (before I was getting grid set error
messages in the http header responses) but caching appears to be
working.

http://mapstory.dev.opengeo.org/data/geonode:BE_Colonies?tests=2

There appear to be other issues (perhaps you can verify Matt?):

2) only on load, additional requests are being made to 'wayne' despite
the base layer being openstreetmap ???

This appears to be caused by enforceOneVisible in the GeoExt layer tree code.

**Comment by cholmes** [comment]
This is still firing off extra requests, they also go to the mapquest tiles for the satellite layer.

**Comment by bartvde** [comment]
yeah I don't think there is an easy fix for this one unfortunately, talked about it with @ahocevar way back IIRC

**Comment by cholmes** [comment]
Hrm. If no easy fix I think I'll just close, as I don't think it's a big deal - they seem to load at the end anyways, so don't even make things feel slower. I'll hold some hope for ol3 :)

**Comment by bartvde** [comment]
For reference this was the GeoExt thread: http://www.geoext.org/pipermail/dev/2012-April/001125.html
