### ISSUE TITLE
Timeline integrated with map composer

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#4]
High-level ticket for all timeline functionality

**Comment by bartvde** [comment]
What is done is:
- syncing up with playback tools (bi-directional)
- dynamic time attribute
- picking a title attribute

What still needs to be done is:
- filtering based on comparison filter
- \+ and - tools along vertical slider
- play button
- optimizations for data fetching
- how to deal with potential data overload (currently just using maxfeatures)

**Comment by bartvde** [comment]
I think this particular ticket can be closed, since the timeline has been integrated. Will open up tickets for the stuff still remaining if their tickets are missing.

**Comment by dwins** [comment]
sounds good to me, thanks bart
