### ISSUE TITLE
storyteller A should be able to edit annotations of storyteller B

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#400]
@ischneider is this just a matter of changing permissions server-side when creating the annotations layer? Or is there some other way to do this already? 

From the script Google doc by Nitin I read one more thing: having other storytellers edit the annotations of a map they did not create. I think this requires some server-side permissions, no client-side changes, but need to check with Ian.

**Comment by ischneider** [comment]
@bartvde this does require permission changes on the server-side.

I haven't read the document yet, but I think the workflow needs to be more involved than changing permissions upon creation - a more explicit way of granting permission.

**Comment by cholmes** [comment]
I agree with Ian. Closing this for now, can reopen something in a more thought out permissioning, of actually letting someone in to collaborate. Making it so any storyteller can edit another's permissions seems bad. I think we should now / soon be able to duplicate (through 'save as') a map and have the annotations duplicated. So they can extend to their own. But we need to think through more fully the way you give someone explicit permission.
