### ISSUE TITLE
evaluate when annotations are shown

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#401]
In MapStory they are only shown when they cross the centre time, but in timemap they are shown in the map when they are visible in the timeline's range. From Nitin:

*I like how the elements in timemap appear when they appear in the
timeline, and disappear when they are gone. Check out this map:
http://timemap.googlecode.com/svn/tags/2.0.1/examples/kenya.html

... this would change the was mapstories are displayed, but I think it
is much better for the person viewing the mapstory.
However, for accuracy, we should still have a vertical line in the
middle for the "present", and the element (point/line/polygon) should
change color, shape and/or texture when it enters the timeline as a
future event, hits the line as a current event, and crosses the line
as a previous event. So, for example, when it enters the timeline, it
might be a semi-transparent square, when it hits the line, it pops up
as fully opaque pushpin, and when it crosses, it goes to
semi-transparent triangle. As always, there can be defaults and the
option to customize.
... but come to think of it, this might be annoying many times, as the
user might want a sudden and brief change, such as a boundary change
or roads... but for events, I think that it would be better if they
appear and immediately disappear. Perhaps the default should be, as it
is right now, where the only things that are showed are what cross the
line, and there is an option to have things appear when before and
after they hit the line.

**Comment by cholmes** [comment]
@sshyu - this has some more user input on annotations.
