### ISSUE TITLE
constrain timeline to range of the map

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#406]
suggestion made by Steven

**Comment by bartvde** [comment]
see: http://www.simile-widgets.org/wiki/Timeline_ThemeClass#timeline_start

**Comment by bartvde** [comment]
However this seems to lead to some side issues, such as starting up with the center date and not the left/min date of the playback toolbar.

**Comment by ischneider** [comment]
Closing - based on old skin
