### ISSUE TITLE
Refine display of "current" time during animation

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#41]
We should choose an appropriate level of detail for reporting the time when looking at temporal data - data with year accuracy currently reports the time with second precision.

**Comment by mpriour** [comment]
Current Time Display should also
-  be displayed in the time slider's built-in tooltip
-  be on top of, not below the time slider

**Comment by mpriour** [comment]
Now using the time slider tooltip as the only time display component.
https://github.com/opengeo/gxp/commit/3af4a255175d31c309f3a370b0e08c76f7ed02f6

Time display format is autoformatted based on the time resolution
https://github.com/opengeo/gxp/commit/5bdecb91a62239804230995aa4f6a4482e74e99e
