### ISSUE TITLE
IE issues

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#412]
There are a number of obvious CSS problems on IE8 in the map/layer page:
-playback tools have no backround
-popout button causes javascript error
-when one leaves the page a javascript error occurs.

fullscreen viewer:
-legend swatches too far left
-legend tree moves around when moused over
-playback controls are barely visible

**Comment by cholmes** [comment]
Not sure of the state of these, but moving off to future to do dedicated IE testing then. In the meantime we'll wait for user feedback.

**Comment by ischneider** [comment]
We currently see around 4% of our traffic from IE8 so we might consider warning them as we do for versions less than 8. Either way, low priority for sure.

**Comment by ischneider** [comment]
Closing as IE8 EOL was April 8, 2014
