### ISSUE TITLE
legend labels in popup legend have poor contrast

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#414]
The labels referred to are generated by geoserver (GetLegendGraphic), not the client-side layer labels.

**Comment by ischneider** [comment]
Looks like this should be relatively easy by controlling the fontColor vender parameter (looks like we're already sending some parameters):

http://docs.geoserver.org/latest/en/user/services/wms/get_legend_graphic/legendgraphic.html#controlling-legend-appearance-with-legend-options

**Comment by ischneider** [comment]
Specifics:
gxp.plugins.LayerManager needs to allow options to be passed through to it - there is already a todo noting this need

**Comment by bartvde** [comment]
Okay I see what you mean, so specifically in the maps/XX endpoint

**Comment by bartvde** [comment]
I think we should be able to specify:

```
        loader: {
            baseAttrs: {
                    baseParams: {
                        legend_options: "xxx"
                    }
            }
        }
```

this currently does not work in GXP, will work on a patch

**Comment by bartvde** [comment]
See: https://github.com/opengeo/gxp/pull/156 for the GXP pull request

**Comment by bartvde** [comment]
Fixed with https://github.com/opengeo/geonode/commit/ed7006ab503225fe9adb44a672e0eeb2feabcede
