### ISSUE TITLE
update old layer sources

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#415]
it is possible that there are layer sources that are using the full capabilities document. these should be updated to use virtual services. if a map is not loading, this issue has a high probability of being the cause

**Comment by ischneider** [comment]
Making this high priority as a number of older maps are broken/extremely-slow by this

**Comment by cholmes** [comment]
Closing this, as I think all are using new virtual services, and there's a new migration to fix up some stragglers in #647
