### ISSUE TITLE
time dimension should be configurable after upload

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#417]
currently this is only possible via geoserver admin interface. an endpoint to do this via gsconfig is needed and a UI to drive it should be on the layer info page.

**Comment by cholmes** [comment]
This should probably go in the same place as the ability to 'add' a raster, in #757 

Perhaps a 'configuration' tab that shows up in the storylayer if someone is the owner, where they can set such things.

**Comment by cholmes** [comment]
The other thing that would be good on the 'configuration' tab is the ability to set the base layer for the layer. Like when people look at it on the layer page, the owner should be able to see what base layer they see with it first.

**Comment by ischneider** [comment]
As for the base layer comment above, reopening #196 to capture this.

**Comment by ischneider** [comment]
Closing as new UI contains this concept - will eventually reticket as part of new work
