### ISSUE TITLE
allow filtering by user in layer dialog when creating new map

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#419]
At minimum, add a filter that shows only the current users layers perhaps even as a default. Ideally, any/all users.

This addresses a concern related to #418 , from Steven:

Just a thought at this point, but when a user creates a map, we could show them a list of layers they've uploaded first by default instead of a list of all public layers (which is what it looks like it shows now).  I know part of the point is to be collaborative, though, so this wouldn't help that aspect.

**Comment by cholmes** [comment]
This would be a nice little improvement to the new map search actually. Perhaps just an extra checkbox that says 'limit to only my layers'. Would be nice if it only shows up if a user actually has layers, as some users will just make maps.
