### ISSUE TITLE
Feature grid in composer

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#42]
Integrate GXP feature grid into GeoNode map composer

**Comment by bartvde** [comment]
dwins: is this supposed to be done in mapstory branch of geonode-client? Are there any wireframes that I should use?

**Comment by bartvde** [comment]
I do see it in the new wireframes, however it's not clear if the grid contains the same data as the timeline.

**Comment by bartvde** [comment]
Can anybody confirm which features need to be shown in the grid?

**Comment by bartvde** [comment]
Confirmed to show the same features as in the timeline, but with all the attributes.

**Comment by bartvde** [comment]
initial feature grid implementation is in with https://github.com/opengeo/geonode-client/commit/e82b5d8d5c81d67b4ffc336f794a6409eb4c19e1

(only for annotations at this point, but that's the main focus now probably anyway)
