### ISSUE TITLE
minor changes to comments in map/layer pages

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#420]
From Steven:
- When map has no comments, add space below "No Comments. Be the first!" (15px should be good)
- For Consistency: "Post a Comment" should be in title case (uppercase "C")

To improve readability (can mock below up if doable):
- Remove dash between username and comment post time
- Make comment post time a lighter color
- Add borders between top-level comments (but not within threads)

Reply to comment overlay:
- Reduce space between "Reply to Comment" and "Comment:"
- Rename "Comment:" label to "Reply:"
- Include the comment they're replying to at the top (limit height and allow for internal scroll if comment is very long), below the overlay header and the reply field
- Move "x" so it lines up with right of the comment box 
- Make right padding match left padding.
- Make submit button same as the submit button under "Post a Comment" on map page

**Comment by ischneider** [comment]
Completed the first 5 with b787385d0bf602a2bb5dc21e60160893252cf779

**Comment by cholmes** [comment]
This might be a good one for @drwelby

**Comment by drwelby** [comment]
Addressed most of the last 6 in #940. I can't include the previous comment without rewriting Dialogos which is part of GeoNode, or sneaking it in with some jQuery. I don't see unequal right/left padding, so that might already have been fixed.

**Comment by ischneider** [comment]
Sneaking it in with jQuery seems the easiest bet. You could find the closest `.comment` and grab the content from the child div.

Deployed to dev. Ready for testing.

**Comment by drwelby** [comment]
I have it working with jQuery - the form has a hidden field with the parent comment ID, which happens to have a CSS id of '.comment-ID' so you can grab what you need.

**Comment by drwelby** [comment]
Merged in #941 .

**Comment by emloux** [comment]
Looking good on Dev.
