### ISSUE TITLE
ajaxify comments in maps/layer pages

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#421]
should be clear - current approach is rendering in template. deletion works okay this way, but adding a comment requires page reload

_UX_

To also include:
- showing confirmation message when user adds a comment
- showing confirmation message when user deletes a comment

**Comment by cholmes** [comment]
Closing, I think this is improved now.

**Comment by ischneider** [comment]
This actually hasn't changed. When a user posts a comment, the whole page reloads and it's not clear the comment was posted as the reload makes the page scroll to the top.

**Comment by cholmes** [comment]
Ah, my bad. Reopening.
