### ISSUE TITLE
revisit popup legend design in info pages

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#425]
From Steven:
- Consistency: change “Storylayers” to “StoryLayers”
- Add a close button ( this addresses the oft reported 'legend won't close' bug - #307 )
- Items under subheaders - make regular font weight (not bold).  Subheaders (“StoryLayers”, “Base Layers”) should remain bold.
- Change text color to white.
- Base Map: change it to a dropdown; show the legend (if any) associated with the selected base layer below the dropdown
- Mockup (note: also shows other changes in addition to those listed above) : https://docs.google.com/a/opengeo.org/document/d/1Bluxv_Zn0N3c48gc8Y5whae9Bo2MZlnSKX_NMoD-ylI/edit

From Ian:
overflow on the legend may still be needed (in addition to the close button) but we should style the scrollbars. see maps/153 on dev server for example.

**Comment by cholmes** [comment]
That mockup is behind opengeo permissions. It's also up at https://github.com/MapStory/mapstory-roadmap/blob/master/items/legend.md

**Comment by jonpmarino** [comment]
Is there a way to have the legend window show the MapStory title as well? Currently in embed or full screen playback there is no way for viewer to know what the MapStory is about. Rather than take up more screen real estate, locating the MapStory title somewhere in legend seems to make the most sense

**Comment by jonpmarino** [comment]
Also need legend to re-size, so it only extends as large as the content there is to fill it. Currently the legend is defaulted to fill the whole MapStory viewer height, and is often covered by annotations
