### ISSUE TITLE
Labels do not show up when a story is played

### ISSUE THREAD

**Issue by satmaram** [MapStory/mapstory-meta#427]
During styling a mapstory, when any label values are selected in the 'Label Features' tab, those labels do not get displayed properly when the mapstory is played. Only a few label values show up.

**Comment by cholmes** [comment]
This has some options, explained in http://forum.mapstory.org/question/8/how-do-i-get-all-my-labels-to-show-up-on-the-mapstory/ And will make individual tickets for more improvements.

**Comment by cholmes** [comment]
![screen shot 2013-07-09 at 5 45 00 pm](https://f.cloud.github.com/assets/407017/771320/ed562886-e8e0-11e2-80c6-bc56fd1bc8d2.png)
