### ISSUE TITLE
possible 'favorite' duplicate key error

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#432]
The Favorite model declares uniqueness based on user, content_type, and object_id (so a given Layer or Map can only appear once in a user's favorites). The view code does not handle this well and adding the same Layer or Map twice will results in a IntegrityError

**Comment by cholmes** [comment]
Testing favorites and seemed to work ok. But one thing is that there's no feedback as to whether I've hit 'favorite' or not. It should ideally be shown depressed if I've already favorited it. Want me to submit a new bug for that? I am not
