### ISSUE TITLE
audit stored config that points to non-virtual services

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#433]
Some older maps/layers client config may be pointing to the full capabilities document still. These should be updated to point to the virtual WMS service URL. This applies to all installs but is critical for the production site.

**Comment by cholmes** [comment]
Closing this, assuming/hoping it works now, and that we would have hit a real bug if it was an issue. Especially since we've got over 1000 layers now so any client using that caps doc would be super slow.
