### ISSUE TITLE
cannot use d or backspace in annotations

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#435]
I suspect this is caused by:

https://github.com/opengeo/gxp/blob/master/src/script/widgets/FeatureEditPopup.js#L381

**Comment by bartvde** [comment]
My suspected cause was wrong ...

**Comment by bartvde** [comment]
Not totally wrong it seems, since modify control even has this as deleteCodes if I comment the line mentioned above:

this.modifyControl.deleteCodes: Array[2]
0: 46
1: 68

**Comment by bartvde** [comment]
So the issue here is that in FeatureEditPopup we are stopping the event [1]. I believe this was done to prevent the backspace for going back to the previous page in the browser when done outside of a field in the popup.

[1] https://github.com/opengeo/gxp/blob/master/src/script/widgets/FeatureEditPopup.js#L377

**Comment by bartvde** [comment]
Before we stop the event, we could check the type of evt.target, can't think of a better solution right now, but maybe @mpriour has a better idea:

```
!(evt.target instanceof HTMLInputElement || evt.target instanceof HTMLTextAreaElement)
```

**Comment by mpriour** [comment]
Wouldn't prevent default be sufficient to not navigate back?

**Comment by bartvde** [comment]
That's a good one, you could be right, let me test it out. I am not sure how old this part of GXP is.

**Comment by bartvde** [comment]
Tested it, but this also prevents using one the delete keys in the popup:

```
                    if (this.feature && OpenLayers.Util.indexOf(this.deleteCodes, evt.keyCode) != -1) {
                        OpenLayers.Event.preventDefault(evt);
                    }   
```

**Comment by bartvde** [comment]
Okay this is pretty recent:

https://github.com/opengeo/gxp/commit/f675772bd44b47f1640c0528ff6ca2f6ea2e5fe6

1 month old, that's why I had not experienced it myself.

**Comment by bartvde** [comment]
@tschaub has reverted this in GXP

https://github.com/opengeo/geonode/commit/273f39cf6d8efd151750120f187231ebc6e36f3b pulls this in
