### ISSUE TITLE
annotations showing up at the wrong time

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#437]
Reported by Nitin: some annotations I added are popping up at random times. They seem to be popping up in 1998, when they should be popping up in 1942.

http://mapstory.dev.opengeo.org/maps/208/view

**Comment by bartvde** [comment]
I cannot reproduce, they pop up in 1942 for me in Chrome.

**Comment by cholmes** [comment]
For me they pop up in both 1942 and 1997. I just hit 'play' on the exact view and they run. I'm on Chrome too, on a mac. Bart, could you see if they also pop up in 1997 for you.

**Comment by bartvde** [comment]
Thanks for the extra info @cholmes I see this now as well.

**Comment by bartvde** [comment]
The biggest hurdle is getting the mapstory local, but I see now there is a trivial bug in the annotations functionality, too much Math.abs in the logic, will work on a fix

**Comment by bartvde** [comment]
https://github.com/opengeo/gxp/commit/acfee3df8c106b215bc20f4a6ebe47faa38eae97 should hopefully fix this, haven't tested in real life situation though, will test when this makes it to dev environment

**Comment by bartvde** [comment]
Pulled in with https://github.com/opengeo/geonode/commit/e520b514a9c943db5bbd5dbd5b6382e3b5217774

**Comment by bartvde** [comment]
@ischneider how can we get this tested on dev? The old update procedure I have does not work anymore.

**Comment by bartvde** [comment]
Put this on mapstory.dev.opengeo.org and works fine for me now.

@cholmes can you verify?

**Comment by cholmes** [comment]
Looks to be working. I tried it 3 times. I weirdly thought one of those times it popped up, but then couldn't see it again, so I think it's good. Will tell others to test.

**Comment by bartvde** [comment]
Okay there is an additional issue, and that is that when panning the map, the popups get visible again. This is because the popups have some code to hide and show when they pass the boundaries of the map. Will work on an addtional fix.

**Comment by bartvde** [comment]
See: https://github.com/opengeo/gxp/commit/26a5d2b7f253d9b23bf79eb0572049975caa5f40 but need to test this out on dev

**Comment by bartvde** [comment]
pulled in with https://github.com/opengeo/geonode/commit/26a94530424f53f59d955d355893bbc09d47a804 and tested on the dev environment.

Closing for now, please reopen if necessary.
