### ISSUE TITLE
Testing of Select time attribute

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#44]
#1

Testing of Geonode UI, uploader client and uploader to allow users to select a default time attribute.  In addition to any internal tests, we might encourage the class at ASU to test the updated demo site post the October 28th demo update.

**Comment by ischneider** [comment]
Work in progress - and probably will be for a while. Trying to ensure importer tests are complete as well as integration tests from geonode side of things.

**Comment by awright** [comment]
Also note that the ASU students should be starting to test the dev server in the next week (or so).  Just sent a follow-up email to the ASU team
