### ISSUE TITLE
not all annotations show up in timeline

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#440]
This map has 4 annotations, but only 3 show up in the timeline. 4 show up in the map.

http://mapstory.dev.opengeo.org/maps/208/view

**Comment by bartvde** [comment]
Actually the issue is different, one of the 4 has in_timeline false, so will not show up. But this also means it cannot be edited at all.

**Comment by bartvde** [comment]
http://mapstory.dev.opengeo.org/geoserver/wfs?service=WFS&request=GetFeature&typename=geonode:_map_208_annotations

**Comment by adunetz** [comment]
No longer relevant.  Should be closed out.
