### ISSUE TITLE
filter users from search if profile is incomplete

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#447]
users should not appear unless they have:
picture, full name, blurb

additionally, the profile and storyteller page should show a message (to the user only) noting the profile is incomplete

add message about 'incompleteness' to profile form, too

**Comment by cholmes** [comment]
I'm going to bump this back out of ready for testing, due to issue #309 - basically no user will be able to get to being able to show up in search since it always says they need an avatar, even if one has already been uploaded.

**Comment by cholmes** [comment]
This appears to be working great in my limited testing. Thanks! Marked for production.

**Comment by cholmes** [comment]
Hey Ian, so this doesn't seem to be working right on production. New users it does notify that they haven't filled out all their information. But existing users don't get the message. And they show up in the search. It does look like new incomplete users don't show up in the search though.

**Comment by cholmes** [comment]
Closing this. It's not working perfectly, see the comment above. And it looks like if users have everything but the picture they show up. But this is definitely an improvement, and we can make new tickets for related issues.

**Comment by ischneider** [comment]
All users have been 'audited' on production now.

There is a bug in the search results that doesn't check for the user's avatar via gravatar, only uploaded images.

I created this to track the bug: #675
