### ISSUE TITLE
Add Terms of Service link on footer

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#451]
There is now a terms of service - http://wiki.mapstory.org/index.php?title=Terms_of_Service

Could we add a link to the footer, just to the right of 'license' called Terms of Service, that links there?

**Comment by jj0hns0n** [comment]
Should we just include the terms in the site itself? Rather than linking to an external page. Seems like bad UX, and that site doesnt currently answer.

**Comment by jj0hns0n** [comment]
Sent a PR for adding the simple link. Makes much more sense to me to use flatpages and include this kind of thing directly in the site itself (also license). I sent a separate PR for the flatpages app, and if we go this route, we need to add some fixtures for pages like this.
