### ISSUE TITLE
make time slider aggressive

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#452]
this will only make sense once we have pre buffering in place, but to make the time slider aggressive we should listen to change instead of changecomplete

**Comment by bartvde** [comment]
this does seem to lead to quite a bit of flickering

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/3f9b87d9df83c049e348bbed437a06f8964be82d pulled in with: https://github.com/opengeo/geonode/commit/1e4a0a92aefa9e36da2a47cd88c42b910d962446

**Comment by bartvde** [comment]
deployed on dev ready for testing @cholmes

**Comment by cholmes** [comment]
Awesome work Bart! Getting really close to the ideal. I am seeing a lot
more flickering now, even on normal playback. Try like
http://mapstory.dev.opengeo.org/maps/188

This seems similar to the flicker issues we just had that Andreas helped
with - just keeping the existing tiles up until all the tiles for the next
step are loaded.

**Comment by bartvde** [comment]
Hmm how did this issue come back, will investigate

**Comment by bartvde** [comment]
Hmm the css is still in place, not getting what broke this, it's not the pre-buffer code since I disabled it and still had the issue

**Comment by cholmes** [comment]
Hmmm...  I'm pretty sure it was working fine a day or two ago, and I think
you're the only one with the ability to push changes this week. Maybe the
mapquest fix introduced something?

**Comment by bartvde** [comment]
no those were just url changes and can't be the cause of this

**Comment by bartvde** [comment]
okay this is the culprit: 1e4a0a92aefa9e36da2a47cd88c42b910d962446

**Comment by cholmes** [comment]
I got a 404 when I clicked on the link. But that's ok, just let me know when you push to dev and I'll test.

**Comment by bartvde** [comment]
oh right it's because it's a commit in the geocode project and not the mapstory project ... duh

**Comment by bartvde** [comment]
okay what happens is that the change event on the slider is fired when playing (so on every tick), I guess we'll just need a flag on the slider to put it in silent mode when playing, so it will ignore any changes.

**Comment by bartvde** [comment]
Fixed with https://github.com/opengeo/gxp/commit/543ebd8082928d9a0a116ff88a3e86ad331cae46 pulled in with https://github.com/opengeo/geonode/commit/da41f34c73aaae3d84e8fe9c2dabd9ae21c82e41

deployed to dev

This will mean playback is smooth again, but dragging the slider will still result in a bit of flickering.

**Comment by cholmes** [comment]
Sweet, much better. And the flicker when dragging doesn't feel too bad in
initial tests. I think a new bug was introduced though, which is made
pretty clear since I was just demonstrating the same type of movement on
the screencast I made on #524  See http://www.screenr.com/8Kc7  Basically
the clicking on the timeline will make the mouse jump to where it's at, but
on the next playback step it'll jump back to where it was.

**Comment by bartvde** [comment]
@cholmes good point, will look into the new issue. It's probably because the slider is now silent when playing, so it will not react to clicks.

**Comment by bartvde** [comment]
this also occurs in the composer, so it is not related at all to the aggressive slider, @cholmes I am gonna move this into a separate ticket

**Comment by cholmes** [comment]
Removed ready for testing label - this is no longer working (deployed?) on dev.

**Comment by cholmes** [comment]
Working well now, thanks Bart.

**Comment by cholmes** [comment]
Looks great on production
