### ISSUE TITLE
Cooler theme for mapstory ext editor

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#454]
Hopefully the ext.js accessibility theme can be adapted.

**Comment by cholmes** [comment]
Looking good. There's at least one little tweak needed on the small map page. Am testing for more.

![color-off](https://f.cloud.github.com/assets/407017/232574/561fe03c-8739-11e2-9efd-1f414d4b39b3.png)

**Comment by iwillig** [comment]
Good catch Chris, 

That looks like its happening because we are not including the ext access theme on the

**Comment by cholmes** [comment]
Ok, got a few more small tweaks. Two are shown here:
![Viewer](https://f.cloud.github.com/assets/407017/249223/c3c3b3ec-8b27-11e2-8214-8abb1e66d7ff.png)

First is the 'arial' and '10', would it be possible to make those bigger? In all the other places where the user is selecting an option it's a bigger font. Would be good to make those consistent.

Second is the side scroll bar at the bottom. It only pops up if you hit 'label features', and then go to another tab and back. Like only when it starts out expanded. The first expansion goes fine. Seems like it's just some internal container that is off. If you drag the bottom to be wider then the slider still remains, at the same distance away from being complete.

Another issue is this:

![Viewer-1](https://f.cloud.github.com/assets/407017/249495/db5b176e-8b2e-11e2-9d1e-5da990914aa6.png)

If you're in a note and you adjust the time I think it does white text on white background. So you're flying blind with how to complete it properly. I _believe_ normally it just has that error but you can see the text while you're correcting it.

One more - 
![hanging text](https://f.cloud.github.com/assets/407017/249525/a78d7930-8b2f-11e2-9466-f290cb16dac8.png)

The background for a long tooltip doesn't extend. I think a cool improvement would be to wrap the tooltip text if possible, as this long one gets cut off.

Ok, let me know if you can't reproduce any of these and I can make a screencast. I'll keep digging, but in general great job, these ones are all super obscure.

**Comment by cholmes** [comment]
Also am getting similar tooltips to the one in my first comment (on the map page) on the search pages. Like when you mouse over on a user or layer or map, it's too hard to read what it says.

**Comment by iwillig** [comment]
Fixed some of the minor issues in this pull request. 

https://github.com/opengeo/mapstory/pull/583

Chris, can you please me check and create a new ticket for the remaining tickets. 

Thanks.

**Comment by cholmes** [comment]
? I'm not sure what 'can you please me check' means. You want me to figure
out which of those you fixed and create new issues for the comments that
weren't fixed? Are your fixes on the dev server?

**Comment by iwillig** [comment]
Chris, 
Can you check http://mapstory.dev.opengeo.org/

Also, can you please open new issues for different issues? A lot of the small css issues you bring up are not related to the style change. It would be a lot easier to keep track of them if they were in different tickets. 

Thanks.

**Comment by iwillig** [comment]
Also, please remember to clear your browser cache. 

Thanks

**Comment by cholmes** [comment]
Great work Ivan. Everything related to theming that I can find seems to be fixed. There are two more issues, but you're right, they're on mapstory.org. So I'll file as separate issues. They're pretty minor, so we probably won't work on them for a bit, but will get them in.

**Comment by iwillig** [comment]
Cool, 

Do you think I should close this issue?

**Comment by cholmes** [comment]
So showed this to Tucker, and he liked it a lot, except for the 'blue', he wants it to be brown. Like matching the mapstory brown at the top. So we don't get to deploy this yet. Ivan, I'm fine if we just sit on this for a bit. I pushed back some and said there's probably a few different blues in there, and it'd take quite a bit of tweaking. So would be good to at least figure out how many 'blues' there may be that would have to change to different forms of brown.

So yeah, I'm super happy with it, and we can leave it on dev. And good that we learned how to do it. But unless changing to brown is super easy I think we should wait till we have a designer, and then you can just help them implement Ivan.

**Comment by iwillig** [comment]
It seems like replacing these colors would help. 

   replace #8db2e3 with #454238;
   replace #99bbe8 with #454238;
   replace #6fa0df with #454238;
   replace #3399bb with #454238;

**Comment by iwillig** [comment]
Chris, 

One of the biggest issues with changing the color of the theme is the need to generated a new set of images for the theme. 
For example the follow image would have to be updated. 

![clear-trigger](https://f.cloud.github.com/assets/38427/335068/0f0b02ac-9c84-11e2-8f0f-d7ad895b2c6f.gif)

**Comment by cholmes** [comment]
This went out to prod, so closing. SHould make a new issue for the brown stuff.
