### ISSUE TITLE
Ability for admin to sort the orders of videos in How To page.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#455]
From Tucker:

Admin Console Features:
b)  Can we sort the order on which videos show up on the How To page?  

So he or Liz can choose which order to present the videos in, looks like they have no control now.

**Comment by ischneider** [comment]
@jj0hns0n I have a model change in the works related to the vanity page links. let me know when you begin

**Comment by jj0hns0n** [comment]
@ischneider should this now get closed? I will make sure it works on the Reflections page too.

**Comment by ischneider** [comment]
Not yet, all I did was add the model change (to be compatible with the vanity-pages) branch. The views need trivial adjustments to their queryset.

**Comment by jj0hns0n** [comment]
@ischneider Im assuming this is the order field in here? Doesnt look like we do any enforcement to make sure they are unique, but that shouldnt be a big deal. I will go ahead and implement this in the view/template for both pages.

**Comment by cholmes** [comment]
At some point we should figure out a more elegant way to handle this. But this is good enough for now.

**Comment by cholmes** [comment]
Verified on mapstory.org
