### ISSUE TITLE
Auto-generate TOC of hyperlinks to the videos on the How To page.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#456]
From Liz:
1)On how to page -- perhaps have hyper links to the videos on the left side so you don't have to scroll down so much.  Think about how this gets expanded out in the future.  Would also like to eventually see written documentation combined with video -- but for now - would be nice to have the video name and then a jump to the link at the bottom. 

---

So I think we just need to auto-generate a table of contents of hyperlinks. Have it show up on the left side of the page.

**Comment by jj0hns0n** [comment]
added in #532

**Comment by cholmes** [comment]
tested, this looks good, ready for production.

**Comment by cholmes** [comment]
Verified on prod, closing issue.
