### ISSUE TITLE
Create 'reflections' page with same capabilities as 'how to' page.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#457]
From Tucker
c)  Can we create a "Reflections" page that is exactly like the "How To" page, with the same admin capabilities?

This is just an page that the admins can select the content for. Will be a number of videos I think, just like the how to. Should also be sure we also generate the table of contents of hyperlinks requested there in https://github.com/opengeo/mapstory/issues/456

**Comment by cholmes** [comment]
This should include a link to the page from the top banner header. Just to the right of howto and blog (when blog is there). To the left of profile / admin.

**Comment by cholmes** [comment]
And some placeholder text to populate it with initially. Though just give them admin ability to change this:

This is a place to share the story behind your MapStory with the world. Reflections help teach and inspire other MapStorytellers by giving them, for example, ideas of how to formulate a research question, where to find data, what challenges they might encounter with data, approaches to presenting their story, surprise takeaways that might come from the work, and more. To have your Reflection posted here, simply film and upload it to YouTube and email us at info@mapstory with a link to the video, a link to the StoryLayers or MapStories it refers to, your contact information, and a 50 word description of the Reflection. We review these regularly and pull new ones into the platform all the time. We'll alert you if yours is selected to be featured here.

**Comment by jj0hns0n** [comment]
Im back on this stuff this week, and what I did was set it up so block like
this can be edited from the admin. Going to coordinate with @ischneider on
that this week and will report back.

**Comment by jj0hns0n** [comment]
@ischneider this got pulled and can be closed?

**Comment by ischneider** [comment]
I think we're missing a link from any page to this.

As for the placeholder text, either a fixture or just adding that when we deploy?

**Comment by jj0hns0n** [comment]
Thought I set it up to show up somewhere, but doesnt look like I did.

+1 on using fixtures for this stuff and then editing in the admin. I will
add a fixture for it when I get the rest of the flatpages/flatblocks stuff
done today.

**Comment by cholmes** [comment]
Taking away from 'ready for testing', as this needs a link. Just do it to the right of the 'blog' link up top, on the header so it's on every page.

**Comment by cholmes** [comment]
Looks good.

**Comment by cholmes** [comment]
Verified on prod, closing issue.
