### ISSUE TITLE
timeline should start expanded if there are annotations in the map

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#458]
To work on this, do the following:
- create a new map using the maps/new endpoint. 
- add a time-enabled layer such as conflicts. 
- save the map.
- from the Notes menu, choose add note -> point
- add a title description and start date + end date, then press save

This will have created a feature in the newly created annotation layer (e.g. _map_56_annotations) where 56 is the map's id.

Now use http://localhost:8000/maps/56/view

You'll see a XHR WFS request go off for the annotations layer already. Based on whether or not we get anything back we can expand the timeline automatically.

It is the feature manager called annotations_manager which is doing the WFS request.

This is all controlled by GeoExplorer.plugins.Notes

The GXP timeline panel (gxp/src/script/widgets/TimelinePanel.js) has a reference to the featureManager. The expanding could be added to the query listener here:

https://github.com/opengeo/gxp/blob/master/src/script/widgets/TimelinePanel.js#L686

where you should do a check if features.length is at least 1 before expanding.

**Comment by bartvde** [comment]
please note we are using the mapstory branch of gxp

**Comment by iwillig** [comment]
Yeah I can look at this later in the week. Whats the time frame for when we must have this fixed?

**Comment by cholmes** [comment]
We've got quite a few small issues we're working through, and we'll make progress on them, so it's ok if this isn't fixed immediately. But should be at the top of your queue. Can prioritize it over the accessibility stuff if you're hitting roadblocks with it. Not sure what else is on your plate.

**Comment by bartvde** [comment]
@iwillig this one is not as trivial as I had expected, so if you're okay with it, I'll take it over.
Let me know if you need a new issue, and I can assign a simpler one.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/fd01739e27117aaab2644a8b67a2016a8fd16cc9 and which was pulled in with https://github.com/opengeo/geonode/commit/1382430d8a6494dc4e11d33c4237dbe63a1f362e

**Comment by bartvde** [comment]
this is ready for testing on dev @cholmes

**Comment by bartvde** [comment]
on production, closing
