### ISSUE TITLE
Implement 'announcements' in mapstory

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#459]
Just do this on dev for now, so Tucker and all can try it out to see if it meets their needs.

This can send email messages, right? Be sure that's configured, so we can test it. 

And also want to be able to put a message on the site that doesn't go out on email.

**Comment by ischneider** [comment]
We still don't have email on this, but announcements are integrated.

To have email work, need to make a decision (discussion link):

https://groups.google.com/a/opengeo.org/d/topic/dev-mapstory/aagJKxLumm8/discussion

**Comment by cholmes** [comment]
This is on production now, so I'm going to close it. Will open another ticket for emailing with announcements.
