### ISSUE TITLE
UI for filtering timeline

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#46]
The timeline control is currently undemoable with many of the layers on the demo server due to loading too many features.  Some workflow/ui work is needed to help guide users in not trying to load too many features and provide feedback when the control needs to be disabled due to the quantity of data that would be visualized.

**Comment by scrollie** [comment]
It's hard to come up with a UI solution to a technical limitation, but perhaps the easiest way is to make the error itself more helpful. The copywriting here may not be perfect, but what about attaching actions to the error message like so: https://img.skitch.com/20111107-cb7jphie3sdbjhf9gfe5kbxief.png

What other options are worth considering? I've heard tell of clustering or rendering the timeline on the server as options...
