### ISSUE TITLE
Add pinterest and linkedin to share tab

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#460]
Put in links in the 'share' tab on layers and mapstories to share to linkedin and pinterest social networks. Linkedin now has http://developer.linkedin.com/plugins/share-plugin-generator Pinterest has one at the bottom of http://pinterest.com/about/goodies/

**Comment by cholmes** [comment]
I'd go ahead and add twitter in there too.

**Comment by jj0hns0n** [comment]
@cholmes Should we just use something like sharethis to make this whole process much easier? I tested it out locally and it works perfectly from what I can tell. I think we can/should switch to something like this in mainline geonode too.

**Comment by cholmes** [comment]
Can you push it to dev? Let me check it out there.

**Comment by jj0hns0n** [comment]
In my issue-460 branch and screenshots below. The other advantage of doing it this way is that Sharethis has what looks to be a nice platform to track this stuff. 

![MapStory _ Test Map](https://f.cloud.github.com/assets/506078/178268/92cb05ae-7bb1-11e2-81bc-cb5d93f6b51b.png)
![MapStory _ NIC_0 5s_200y](https://f.cloud.github.com/assets/506078/178269/92fd69b8-7bb1-11e2-9d7d-113b218adafa.png)

**Comment by ischneider** [comment]
Haven't looked into this too much, but we probably need to do something like this:
http://stackoverflow.com/questions/689295/how-to-show-particular-image-as-thumbnail-while-implementing-share-on-facebook

**Comment by cholmes** [comment]
Yeah, we'll need to do that on most every service. I think we have tickets
for wordpress and twitter. I'll add them soon for facebook and g+

**Comment by cholmes** [comment]
Sent this to tucker/marino for feedback on how it looks and which services to use.

**Comment by cholmes** [comment]
They said it's good.

**Comment by cholmes** [comment]
confirmed on prod.
