### ISSUE TITLE
Media ribbon and hyperlinks on storyteller pages

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#461]
Just like we have on the organization page, Tucker wants each storyteller to be able to add links, and media in a media ribbon. Assigning to you Ian, as this should hopefully be easy to do after doing the media ribbon on organization pages. Feel free to reassign to Jeff if your plate gets full, after you get the org media ribbon going.

**Comment by cholmes** [comment]
Should do https://github.com/opengeo/mapstory/issues/462 first - that's the issue for just media ribbon in organization pages. There's a few places Tucker wants to be able to put media ribbons and links, so can take some time to make sure it's done generically.

**Comment by cholmes** [comment]
Where is this? I don't see where I can edit my media ribbon and links for my story teller page.

**Comment by ischneider** [comment]
Was waiting for feedback on the individual components.

**Comment by cholmes** [comment]
Ah, ok. Will comment on the other issue.

**Comment by cholmes** [comment]
Pushing this back a bit, to do after we get organization stuff all nailed.

**Comment by cholmes** [comment]
Be sure to include #582 in this.

**Comment by cholmes** [comment]
Media ribbon should go above the activity feed. Links and networks should go just under the 'by this storyteller' box.

**Comment by cholmes** [comment]
Links section should have the top section of it be 'networks', like on meetup, with the logos of the networks (fb/twitter/linkedin, etc). And below that should be all their other links.

**Comment by jj0hns0n** [comment]
reassigned this to @ischneider after talking to him. He is going to extracting this functionality from organizations and adding it here and the same in #582 ... @ischneider let me know if you need/want help with this.

**Comment by cholmes** [comment]
So this now seems to work, except it has lead to weirdness with the user profile pages, it has this on it now:

![screen shot 2013-06-03 at 9 13 44 pm](https://f.cloud.github.com/assets/407017/603129/29a44622-ccb4-11e2-9fc4-67f69fd8a193.png)

Instead this should be the same style as the organization pages, displaying the links or the media ribbon, with an 'edit' button to take you to the page that edits them.

**Comment by cholmes** [comment]
Marking this ready for deploy. It would be good to get a real UI refresh, as these were on dev for awhile before I noticed how to actually update them. And the updating components could use a bit of polish. They're definitely good enough for the administrator, but we should have a higher level of usability for users. #742 should cover the additional UI refresh though, this work is good enough for now.

**Comment by cholmes** [comment]
Removing 'ready for deploy', as I didn't fully test before, and there's at least one problem. It still doesn't do #597 And I think I should do more testing on it. Also could be nice to rethink the way in to edit these, as it's a bit obscure right now.
