### ISSUE TITLE
Media ribbon and hyperlinks on resource pages

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#463]
Depends on https://github.com/opengeo/mapstory/issues/462

Should use the same ribbon and links structure there to enable customization of the 'resources' pages, like http://mapstory.org/mapstory/resource/religious-and-ethnic-groups

These can be just under the control of admin users.

**Comment by jj0hns0n** [comment]
Reassigning to @ischneider as he is going to migrate this stuff over from the organizations (vanity-pages) code and abstract it out so its reusable. Ian, let me know what help you need from.

@cholmes Ian and I are in agreement that all of this functionality needs to be thought through a bit more before we roll it to production. Lets discuss ASAP.

**Comment by cholmes** [comment]
This went out with the spring improvements deployment, so marking as closed.

**Comment by cholmes** [comment]
This didn't go out with spring improvements, reopening.
