### ISSUE TITLE
Checkbox for terms of service on signup

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#464]
On http://mapstory.org/account/signup/ - Instead of the 'I am Human' checkbox let's make it 'I agree to the terms of service', where terms of service is a hyperlink to http://wiki.mapstory.org/index.php?title=Terms_of_Service

**Comment by ischneider** [comment]
6a784ef

**Comment by cholmes** [comment]
Looks good, ready for the site.

**Comment by cholmes** [comment]
thanks
