### ISSUE TITLE
Notifications settings don't 'stick'

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#468]
If I set notifications to 'immediately' or 'once a day' or even 'never' the button goes down while I'm on the page. But if I hit 'reload' then it just reverts to a non-pressed down state. It probably should always have one pressed down, whatever we choose for the default.

And even when I don't get feedback on the button being pressed I don't think that any notification even takes place if it's on 'immediately'. So it's not really working. Testing more on production, but some on dev too.

**Comment by ischneider** [comment]
Deployed to dev, @cholmes 

Didn't mean to close - github helping me.

**Comment by cholmes** [comment]
Confirmed working on dev. Go ahead and deploy to production. Keep it at 'never' for default for now.

**Comment by cholmes** [comment]
This seems to have just reverted, only on production. Now working exactly as I described above. Not sure what happened. It's using what settings people had, but not able to change them.

**Comment by ischneider** [comment]
A URL routing error that broke the admin reporting link (#644) also resulted in breakage here. Fixed on production again.

**Comment by cholmes** [comment]
confirmed working on production.
