### ISSUE TITLE
Add User Voice widget

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#469]
We should add in a 'support and feedback' widget provided by User Voice, see http://www.uservoice.com/widget/ MapStory has an account. I can send the login info so we can install it.

**Comment by jj0hns0n** [comment]
@cholmes can you send me the credentials in a mail please. Im going to setup my own account to test and we can just switch them when I have mapstory's set.

**Comment by jj0hns0n** [comment]
Sent a PR for this #485 ... must switch the credentials before deploying (I setup a geonode account), and not sure if this rightly goes in page_layout.html or in theme_base.html, but put it in the latter for now.

**Comment by cholmes** [comment]
This is on dev site now. I tested and it works great. Punting to tucker and marino for feedback.

**Comment by cholmes** [comment]
This still needs switching of credentials before deploying to prod.

**Comment by cholmes** [comment]
From tucker: there probably needs to be some basic guidance text on the uservoice popup that says "Please provide feedback on the MapStory platform.  Comments on StoryLayers and MapStories should be done through threaded comments."  Or something like that.

**Comment by cholmes** [comment]
Feedback from jon marino: Awesome! Looks great…exciting to see.

3 questions:
1. Is it possible to customize the word 'Feedback', or is that standard? Not sure we'd want to change it, but just curious. There might be something better that reflects the space more as a place to post/find ideas for MapStories to work on….rather than just tech support. Even 'Ideas' perhaps.
2. Is it possible to have the 'Give Feedback' form be default, rather than 'Contact Support'? Want to front this as a place for folks to share ideas, and as tech support secondarily.
3. Is it possible to have multiple forums on the left side that comments can be assigned to? On the account we currently have we've created 4 'forums' for: 1) data source ideas 2) StoryLayer/MapStory suggestions for the community 3) StoryLayer/MapStory requests for help from users and 4) UI/UX improvement suggestions for developers. Not sure this is the right breakdown, but some different forums might be nice.

Its also possible that UserVoice might not be the right solution for the message board functions I'm suggesting. Just trying to solve for the many people I speak with who say "somebody should really do a MapStory on X" or "I'd love some help putting together a StoryLayer on Y" or "You should check out this data source". Want the community to be the receiver of all that, not just us. You get the point.

**Comment by jj0hns0n** [comment]
Looks like almost all of this can be customized in the UserVoice site itself. @jonpmarino do you need help walking through that process and setting things up. I can do a screenshare with you to look.

@cholmes I dont actually see this on the dev site, am I somehow missing something?

**Comment by jonpmarino** [comment]
@jj0hns0n would it require edits to the html/css to customize? If so, we need to upgrade to the $95 per month plan, which is a bit dear. I also don't see it on dev anymore...

**Comment by cholmes** [comment]
Hrm, it does seem to have left dev. Not sure what happened. I distinctly
remember it being there at some point.

**Comment by jj0hns0n** [comment]
They probably downgraded our account. I saw something in the header about
it, but kinda ingored it.

@jonpmarino I dont think we need to modify the html and css directly, I
think we can do most if not all of what we need just by changing the
default options. I dont know if we have to pay for them or not. Maybe we
can just do a screenshare and phone call and look at it together? Send an
invite and I can do that.

**Comment by jonpmarino** [comment]
@jj0hns0n our account was deactivated - expiration of free upgrade I believe. I just reactivated. Might involve taking some action to get it back on dev. Jeff, once its back up in dev I can do my best to modify default options. Will reach out tomorrow if I get stuck. Any times during the day better for you?

**Comment by jj0hns0n** [comment]
It didnt just automatically show back up on dev. I cant push to dev myself,
but I can check in and see whats going on and see if I can fix it without
updating the code.

**Comment by jonpmarino** [comment]
Ok. My apologies! Think I missed then notification on that somehow...

**Comment by jj0hns0n** [comment]
@ischneider ... let me know if I can help debug what happened on dev. Maybe
we can schedule a session early next week to go over all my PRs (more
coming today) and get them onto dev so we can test.

**Comment by ischneider** [comment]
this is on dev with the account pointing to mapstory.uservoice.com or whatever that account is referred to as

**Comment by cholmes** [comment]
This looks to be on dev, so closing.
