### ISSUE TITLE
Implement 'flag' tab

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#470]
Right now when you hit the 'flag' under maps or layers it says 'not yet implemented'. We should implement it.

Workflow from Tucker:

'It is only implemented on the YouTube map page, under the map.  ideal workflow, I think, is a mailform that requires being logged in, so we know who is reporting it.  (Does this sound right?) The mail would go to several people (e.g., me, Jon, etc.) so that it can be acted upon.  We would then have to log in to the admin console and somehow make the data non-public until we can figure things out.'

So, we want it in Maps and Layer pages. If not logged in it should just pop up to say 'please log in, only registered users can report abuse'. If logged in then it should pop up a form that lets people report something wrong. When they hit submit it should ideally email admins. If that's hard that's ok. But it'd be good for admins to easily just look at messages that are about abuse, and then easily take action to make the data non-public.

**Comment by ischneider** [comment]
While I agree we should start with something, does it make sense to add a model to track this? Instead of just shooting out emails, this would allow us to:
- track what's been flagged and by who
- not send multiple emails if something gets flagged many times during some period of time
- a new admin to access flagged stuff without playing email
- when an email is sent, a link to the flagged model detail or admin view is included

**Comment by jj0hns0n** [comment]
Mail is certainly not what I would use here either. And of course there is
a pluggable for this already https://github.com/pinax/django-flag ... why
dont we use this and hook in email as needed?

**Comment by ischneider** [comment]
django-flag looks good to me.

**Comment by jj0hns0n** [comment]
Just doing it this way now. We can discuss later.

**Comment by cholmes** [comment]
Doing mail later sounds fine.

**Comment by jj0hns0n** [comment]
Sent a PR for this. #529 @ischneider this uses the django messages framework which can be used to hook up to the mailer. Lets discuss this when you are back in action.

**Comment by cholmes** [comment]
Looks to be working well. One thing though, could we get the text box to fill the space?

![MapStory _ ames test again](https://f.cloud.github.com/assets/407017/222064/c4edf1c2-85b1-11e2-8117-941845ddccd7.png)

**Comment by cholmes** [comment]
@jj0hns0n - any thoughts on the above comment? Making the text box bigger?

**Comment by jj0hns0n** [comment]
Fixed with https://github.com/opengeo/mapstory/pull/621

**Comment by ischneider** [comment]
Fixed with CSS (along with metadata fields in info tab) in 8ab2dda8c2910e62195ec3f6b99e6688e6e2fd17

**Comment by cholmes** [comment]
Looks good, marking ready for deploy.

**Comment by cholmes** [comment]
verified on prod.
