### ISSUE TITLE
Make 'Arial' the default style

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#472]
When a user goes to the style editor the default right now is Sans Serif. This should change to be Arial. Have it listed first, so that if the user doesn't change anything it is the default.

**Comment by iwillig** [comment]
This commit should fix close this issue, 

https://github.com/opengeo/gxp/commit/eced0bf694024da4c55ce2a42308cd33791c8387
I need to ask Bart if this is the correct way of doing this.

**Comment by iwillig** [comment]
This commit should fix it,
https://github.com/opengeo/mapstory/commit/c3dc21ab72d356f4ada51add67b380674b33c56f

**Comment by cholmes** [comment]
Looks good in all my testing.
