### ISSUE TITLE
Implement OAuth Consumer in MapStory

### ISSUE THREAD

**Issue by jj0hns0n** [MapStory/mapstory-meta#474]
Implement oAuth in MapStory

**Comment by jj0hns0n** [comment]
This is implemented and pulled onto master, can take up specific issues in other tickets like #607 

Warper guys have been testing on their end. We can file a separate issue for oAuth provider there.

**Comment by jonpmarino** [comment]
Is it possible to extend Oauth to wiki and Wordpress blog as well? Want users to be able to easily add content, making us editors not originators. Here's some documentation on Wordpress O-Auth options. http://wordpress.org/extend/plugins/keyring/

**Comment by jonpmarino** [comment]
What's timeline for having o-auth enabled in MediaWiki? Starting to get some folks I want to empower to work in the wiki. Just giving them current log-in and pw for now but would love to signal a timeline to O-Auth on that.

**Comment by ischneider** [comment]
We're kinda stalled on this at the moment due to resourcing.

**Comment by jonpmarino** [comment]
Gotcha.

**Comment by ischneider** [comment]
Closing as this is implemented.

**Comment by jonpmarino** [comment]
@ischneider AWESOME!
