### ISSUE TITLE
Adjustments to base layers

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#479]
So our base layers have some names that aren't that intuitive. We've got 'wayne', based on Sam's middle name. And 'bluemarble', which no one outside of GIS land knows. So we should update the names of them. Talked to Tucker on this, and his preference is:

Naked Earth
Satellite Imagery
OpenStreetMap
No Background

So wayne should be renamed 'Naked Earth'. And 'bluemarble' to Satellite Imagery. Other two can stay the same.

Also, if it's easy to do, which I believe it should be, could we switch satellite to the mapquest open tiles? Like the one on http://suite.opengeo.org/geoexplorer/composer/#maps/847 I think there's a gxp thing for it. If it's not easy just stick with the same blue marble we're using now.

**Comment by iwillig** [comment]
Closing ticket as this is now fixed in master. However this fix only effects new maps, not existing maps. Opening a new ticket for a migration script that will update all of the existing maps.

**Comment by cholmes** [comment]
Hey, if this is going to require a migration could we also change the satellite layer to mapquest? I had been assuming these changes would be easy to do. But I'd prefer the mapquest one to our blue marble. Should hopefully be an easy change as it's already in gxp. Keep the same name, just use the mapquest satellite layer.

**Comment by iwillig** [comment]
Hey Cholmes, 

I have created a new issue for the migration script, 

https://github.com/opengeo/mapstory/issues/493

Moving your comments there.

**Comment by cholmes** [comment]
Verified this on dev site, looks good. Just put the 'production' label on as I don't see it on mapstory.org yet. Reopening and  will assign to Ian in line with ticket workflow on dev list.
