### ISSUE TITLE
map in map page tweaks

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#481]
In the map page viewer, we need to do two things (feel free to break this up in to two tickets)

1) Include the timeline in full screen mode. This should be expanded if there are annotations. So should use same code as https://github.com/opengeo/mapstory/issues/458

2) Remove the edit button from the small map view. Only have it in the full screen. Ideally only have it in full screen if a user is logged in. But a user should go to full screen, and from there to edit mode.

**Comment by bartvde** [comment]
https://github.com/opengeo/geonode/commit/5415d0369d5df1ceb055f7c5af0f5cca45165b20 addresses item 2

**Comment by bartvde** [comment]
A small tweak on item 2: https://github.com/opengeo/geonode/commit/84e3ef49415774a18a7dc1124d4b77e79f9c786a

**Comment by bartvde** [comment]
One thing I noticed is that the resize is not working properly anymore, the map is not updated until you zoom in. Needs investigation as well.

**Comment by bartvde** [comment]
The last report seems related to having the tile manager, need to investigate more

**Comment by bartvde** [comment]
@ahocevar has addressed the issue with https://github.com/openlayers/openlayers/pull/863 I'll test it out now and review

**Comment by bartvde** [comment]
The first part of the issue is a lot less trivial than I thought it would be, but I'll continue to work on it.

**Comment by cholmes** [comment]
Cool. I tested part 2 and it works great. If someone has good github issue skills please break it out in to its own issue with the comments/code.

**Comment by cholmes** [comment]
Marking this as production, though just for part 2. But I think that's the best way so @ischneider knows there's something ready here to deploy.

**Comment by bartvde** [comment]
new issue created #506

**Comment by bartvde** [comment]
@ischneider this one is on production right? So we can close?

**Comment by cholmes** [comment]
I see it on production, so I'll close it. Thanks for this Bart.
