### ISSUE TITLE
Create a migration script to update base layer names

### ISSUE THREAD

**Issue by iwillig** [MapStory/mapstory-meta#493]
Because of the way we store the base layer names, we need a script that can update all of the existing map configure objects with the new base layer names.

This address the original goals in #497

**Comment by iwillig** [comment]
Leaving this open until the we merge the pull request into master

**Comment by iwillig** [comment]
From Chris, 

Hey, if this is going to require a migration could we also change the satellite layer to mapquest? I had been assuming these changes would be easy to do. But I'd prefer the mapquest one to our blue marble. Should hopefully be an easy change as it's already in gxp. Keep the same name, just use the mapquest satellite layer.

**Comment by cholmes** [comment]
You want me to make a separate issue for doing the satellite layer? Since it's a bit orthogonal to the script deployment. Or you can feel free to make it.

**Comment by cholmes** [comment]
I think this got all done properly, on production too. Reopen if for some reason it wasn't.

**Comment by ischneider** [comment]
There are 468 still on production. Reopening.

**Comment by ischneider** [comment]
Ran on dev - seems pretty straightforward.

**Comment by cholmes** [comment]
Looks good on dev

**Comment by cholmes** [comment]
confirmed on prod
