### ISSUE TITLE
minor profile page UI changes

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#496]
change 'Remove selected' to 'Delete selected'

remove/hide/disable 'Change permissions' button (can cause errors and is confusing given coarse grained permissions in use)

remove/hide/disable 'Edit button' and/or fix response from mapstory metadata view to redirect to layer page (currently GET request errors out)

**Comment by ischneider** [comment]
A longer discussion of other improvements here:
https://groups.google.com/a/opengeo.org/d/topic/dev-mapstory/3f02PvYyu94/discussion

**Comment by ischneider** [comment]
Also by https://github.com/opengeo/geonode/commit/eb35109214850cbc7a02686081e40949ddc91220

**Comment by cholmes** [comment]
Looks good. Found no issues. Tagged for production.

**Comment by cholmes** [comment]
This looks to be working well on mapstory.org
