### ISSUE TITLE
Add search to the add layer dialog

### ISSUE THREAD

**Issue by iwillig** [MapStory/mapstory-meta#499]
Chris mentioned that this is a new requirement. We need to some or all of the functionality in the search storylayer page to the add layer dialog. This includes the ability to search for a layer, the ability to narrow the search list by filters.

Updates from Ian (03-13-2013):
- Do not load anything until user searches for a term or presses enter key (see below)
- allow user to press enter key

Right now the search storylayer page allows users to filter results based on
- What
  - Section
  - Keyword
- Where 
- When
- Who

**Comment by iwillig** [comment]
It seems like the best way to do this would be to build a new subclass of this existing class, 

https://github.com/opengeo/gxp/blob/master/src/script/plugins/AddLayers.js

That includes these new functions

**Comment by ischneider** [comment]
Where and When: it would be cool if we could use the existing extent of the map, both spatial and temporally, as filters. For example, a toggle button that adds/updates/removes the extent filter for each dimension, respectively.

For section/topics, we'll need an endpoint to obtain these to populate a drop-down/whatever. There is already an author endpoint for auto-completion.

**Comment by ischneider** [comment]
Also see #419

**Comment by cholmes** [comment]
Feel free to start with no filters, just get 'search' going. Then add in better display of results, with thumbnails and abstracts. Then can investigate filtering. Agree with Ian that spatial/temporal extent of current view would be ideal.

**Comment by iwillig** [comment]
https://github.com/opengeo/geonode/pull/11

**Comment by iwillig** [comment]
from Chris,

Cool. Will you just kill that 'view available layers from <search>' thing? Both the text and the drop down. I know it's for like adding remote WMS servers, but I'm not really convinced those will work well with time. Let's just keep it mapstory, and later we can figure out a better workflow for adding other WMS layers.

And for adding thumbnails, could you also improve the formatting of the results? I'd say start with the results expanded (the + thing, though leave it so people can hit the '-' and get smaller results. And get rid of the 'id' thing, I can't see anyone caring about the ID name, and we should have titles for all. 

And also the results now have a bunch of essential 'blank' stuff: 

(apologies if that doesn't work, and let me know if it doesn't, I'm trying a new workflow for screenshots).

Abstract is good and should be required.

Provided by seems like it should maybe be a link to the storyteller? Or perhaps a fliter? I'd say just kill it for now. Along with metadata links. And leave keywords in, but I'd say only display them if there are actually keywords. Hrm, a little testing leaves me thinking they aren't actually working right now. Though I could be wrong. So yeah, make sure keywords work.

So title, a small thumbnail, and keywords for now should be the next step. And anything else you can think of to make the results look and feel a bit better.

**Comment by bartvde** [comment]
okay tested out the patch, will look at the code in more detail in the PR.

I would move the Search button next to the search field instead of underneath.

There is something with the layout, try scrolling down the grid, you can't reach the bottom of the scrollbar.

Also, when you search for American, I get 2 results. When I remove the search filter and press Search again, I am not getting the same amount of layers which I saw initially, I am guessing the limit parameter is getting sent and it should not?

If I use the Find Layers option of the Add Layers menu option, I get a JS error. I am guessing we should simply hide that option?

**Comment by bartvde** [comment]
Looked at the PR, nice work @iwillig not bad at all, put some minor comments in the PR code.

**Comment by iwillig** [comment]
Hey Bart, 

I can reproduce the scrolling issue you mentioned, so I am going to look into that right now. Thanks for catching this.  That I get for having to few layers ;).

**Comment by iwillig** [comment]
Right now when a user is using the new search interface, the query limits the search results to 10 layers. We should fix this.

**Comment by cholmes** [comment]
Verified on prod.
