### ISSUE TITLE
Make map animation configurable

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#5]
Users should be able to control details of the animation like framerate, step size, time range, loop or don't, etc.  This involves both offering those options in the UI and making them "stick" with server-side storage.

**Comment by mpriour** [comment]
At least for the Demo Ready milestone the loop & framerate will only be set via the playback toolbar control. The framerate is nominally 1 fps but can be increased to 2 fps using the Fast Forward button.

Would be good to have a 2X icon from @scrollie or someone else to give some better user feedback as requested by Tucker.
