### ISSUE TITLE
Add Twitter 'card' functionality to Share/embed Twitter feature

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#500]
We need to apply for a 'twitter card' that adds some additional HTML code to the Twitter embed (which our guys are working on now, right?)

See: https://dev.twitter.com/docs/cards. This spells out the coding work and app process pretty clearly.

There are 3 options for how it would appear to "Tweet" a story layer
1. Summary
- would actually work pretty well for us. It would have a StoryLayer appear like a news article…title, author, lead sentence, and thumbnail of photo
1. Photo

-this is what MapBox did…the map essentially appears as a static photo that can be clicked, taking user to original map on MapBox platform. Could still be interesting for us.
1. Player

-the most ideal…used for Videos. This would have a StoryLayer/MapStory be able to play in someone's actual twitter feed. Hardest develop effort, it appears.

you have to demonstrate it and apply…seems pretty straight forward, but need developers to do this.

**Comment by cholmes** [comment]
Assigning to myself for testing.

**Comment by cholmes** [comment]
@ischneider  I just confirmed this worked. See https://twitter.com/chucker42/status/340938019286700032

Could you push in the next release? And then I will need to register the card so it shows up on production.

**Comment by ischneider** [comment]
I attempted to push to production last night but I must have missed a commit as it actually broke stuff. Looking into what happened.

**Comment by cholmes** [comment]
Jon, can you confirm if/when this works. Changes are deployed to production, but want to be sure we take it all the way through with registration on twitter, so they actually work. I signed up mapstory.org with your contact info.

**Comment by jonpmarino** [comment]
Awesome! Will do.

**Comment by cholmes** [comment]
confirmed working on prod.
