### ISSUE TITLE
Enhance Facebook share/embed feature

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#501]
Facebook 'share' function should result in content being 'Recommended', not 'Liked'. Also, thumbnail image for the 'recommend' should be the StoryLayer itself. Currently it varies, and oftentimes uses the profile picture of the StoryTeller.

**Comment by cholmes** [comment]
I think we need to investigate the opengraph facebook stuff as well.

**Comment by cholmes** [comment]
Yeah, I'd say make sure the thumbnail is always the map/layer, and that it always displays the title and abstract, for what people see in facebook when it shows up in feeds there.

**Comment by jj0hns0n** [comment]
With the switch to sharethis and @ischneider's work in https://github.com/opengeo/mapstory/commit/f386ef221e9c3c09013c60b117db7c0adcf6068c this should be good to go. Attached some screenshots to show how it looks.
![Facebook](https://f.cloud.github.com/assets/506078/326581/cab467e4-9b3c-11e2-994d-e65f7a0b789c.png)
![Facebook-1](https://f.cloud.github.com/assets/506078/326582/caccf80e-9b3c-11e2-8942-c36bc6ec8fd6.png)

**Comment by jonpmarino** [comment]
Awesome!!!

**Comment by jj0hns0n** [comment]
@cholmes We can add as many more opengraph tags as we need to do what we want to do. See the ones Ian added here https://github.com/opengeo/mapstory/commit/f386ef221e9c3c09013c60b117db7c0adcf6068c#L0L-1 and there are many more things we could do for sure. Lets discuss.

**Comment by jj0hns0n** [comment]
Fixed up the opengraph meta tags to add the abstract. Looks even a bit better now (Abstract: is gone)

**Comment by cholmes** [comment]
Assigning to myself to do testing.

**Comment by cholmes** [comment]
This is already deployed on prod, tested.
