### ISSUE TITLE
Unable to remove layer from map composer page

### ISSUE THREAD

**Issue by iwillig** [MapStory/mapstory-meta#502]
When on attempts to remove an layer from the map composer page, GeoExplorer throws and exception. 

TypeError: this.destroy is not a function
http://localhost:8888/script/@/app/static/externals/openlayers/lib/OpenLayers/Dimension/Model.js
Line 121

**Comment by cholmes** [comment]
I can't reproduce on mapstory dev site. Have you confirmed it there, or is it a problem with your set up? Or let me know the steps to reproduce, I just tried a new mapstory, added a few layers and then hit 'remove layer' and didn't get this.

**Comment by bartvde** [comment]
okay, the code looks dodgy though, since there is no destroy method on that class, so let's remove it anyway to be sure

**Comment by bartvde** [comment]
see: https://github.com/opengeo/openlayers/commit/c39944b1298d14cc1194f8bfa84056d8c387ee84

**Comment by bartvde** [comment]
pulled in with: https://github.com/opengeo/geonode/commit/9664acdabfc64708509658bda2d778bc6d012bb1

**Comment by iwillig** [comment]
Fixed
