### ISSUE TITLE
error in intial thumb generation

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#503]
Currently, thumbnail generation automagically occurs for newly created maps/layers on the info page when the owner visits. A (very hacky) listener is attached to the map object and when totally loaded, the thumb is rendered. Apparently the load event is broken now... Related info:

Traceback (most recent call last):

  File "/var/www/mapstory/wsgi/geonode/lib/python2.6/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, _callback_args, *_callback_kwargs)

  File "/var/www/mapstory/wsgi/geonode/src/GeoNodePy/geonode/maps/views.py", line 858, in layer_thumbnail
    return _handleThumbNail(req, get_object_or_404(Layer, typename=layername))

  File "/var/www/mapstory/wsgi/geonode/src/GeoNodePy/geonode/maps/views.py", line 874, in _handleThumbNail
    thumb = obj.set_thumbnail(spec)

  File "/var/www/mapstory/wsgi/geonode/src/GeoNodePy/geonode/maps/models.py", line 596, in set_thumbnail
    thumb.generate_thumbnail()

  File "/var/www/mapstory/wsgi/geonode/src/GeoNodePy/geonode/maps/models.py", line 1942, in generate_thumbnail
    raise Exception('Empty thumb content')

Exception: Empty thumb content

<WSGIRequest
path:---REDACTED---,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'STYLES': [u''], u' height: 800%': [u''], u' top: -2856%': [u''], u' top: 0%': [u'', u''], u'FORMAT': [u'image/png'], u'"><div id': [u'"OpenLayers_Map_6_OpenLayers_Container" style="position: absolute', u'"OpenLayers_Layer_4" style="position: absolute'], u' width: 100px': [u''], u' z-index: 335': [u''], u' left: 0%': [u'', u''], u' z-index: 749': [u''], u' top: 0px': [u''], u' width: 800%': [u''], u' width: 606%': [u''], u'TRANSPARENT': [u'TRUE'], u' z-index: 325': [u''], u'LAYERS': [u'Homicides11_clip'], u'REQUEST': [u'GetMap'], u'HEIGHT': [u'450"></div></div><div id="OpenLayers_Layer_OSM_20" style="position: absolute'], u'SRS': [u'EPSG:900913'], u'VERSION': [u'1.1.1'], u' width: 100%': [u'', u'', u''], u'" src': [u'"http://mapstory.org:80/geoserver/geonode/Homicides11_clip/wms?SERVICE=WMS'], u'" dir': [u'"ltr" class="olLayerDiv"></div><div id="OpenLayers_Layer_WMS_26" style="position: absolute', u'"ltr" class="olLayerDiv olLayerGrid"><div id="OpenLayers_Layer_WMS_26_bb" class="olBackBuffer" style="position: absolute', u'"ltr" class="olLayerDiv olLayerGrid"></div></div></div>'], u' left: -4018%': [u''], u'amp': [u'', u'', u'', u'', u'', u'', u'', u'', u'', u'', u'', u''], u' opacity: 1': [u''], u' height: 100px': [u''], u' height: 100%': [u'', u'', u''], u' position: absolute': [u''], u'WIDTH': [u'606'], u' left: 0px': [u''], u'height:450': [u''], u'"><img class': [u'"olTileImage" style="visibility: inherit'], u' z-index: 350': [u''], u'TILED': [u'false'], u'TIME': [u'2011-01-01T00:00:00.000Z'], u'<div style': [u'"width:606'], u' height: 450%': [u''], u'BBOX': [u'-8970623.2694952,4432588.5072163,-8229489.8433452,4982935.1107929']}>,

**Comment by cholmes** [comment]
This now works fine. Though it made me find a couple other issues, will report them in separate tickets. Would it be hard to generate thumbnails for existing blank ones? Actually a potentially easier thing to do might just be to filter search to not display the results if there is no thumbnail, so owners could then generate the thumbnails.

**Comment by ischneider** [comment]
Thumb generation currently requires the client so we cannot generate them without someone viewing the layer/map. Once the 'spec' has been created, they can be (re-)generated server-side.

We could consider a lack of thumbnail part of the 'incomplete metadata' criteria and filter from search.

The biggest challenge to automatically generating thumbs is the time dimension - this pretty much requires a human to decide 'when' and where the thumbnail should be...

**Comment by cholmes** [comment]
Ok. Let's push this to production then. And I'll make another ticket on considering lack of thumbnail part of 'incomplete metadata'.
