### ISSUE TITLE
Implement oembed for MapStory sharing on wordpress

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#504]
First step to be able to share mapstory on wordpress.com is to implement oembed, see  http://codex.wordpress.org/Embeds

**Comment by jj0hns0n** [comment]
It looks like the real issue here is that by default Wordpress rejects iFrames, you have to install a plugin to allow iframes. I was able to do a normal embed with a hosted wordpress with the plugin installed. I dont think whitelisting will solve that, but I will keep investigating.

**Comment by cholmes** [comment]
Talk to Jon Marino on this. He has a thread from the automattic guys on
what's needed on our end to get white listed on we.com

**Comment by jj0hns0n** [comment]
Working on this again today, was sidetracked yesterday.

**Comment by jj0hns0n** [comment]
@cholmes Im back on this today and again, struggling with all of the existing django libraries that do this and loathe to start over/from scratch. Will just focus on this until I get it right and report back.

**Comment by jj0hns0n** [comment]
Django side implemented http://mapstory.dev.opengeo.org/oembed/?url=http%3A%2F%2Fmapstory.dev.opengeo.org%2Fmaps%2F73 ... working on wordpress side now.

**Comment by jj0hns0n** [comment]
See #590 for implementation. The following are still required
- Fix Embed template to only show the viewer
- Make a wordpress plugin with the small snippet to add support for this. Figure out how to distribute this
- Ask wordpress.com to whitelist this site
- Look into using embedly etc
- Decide whether we need oembed consumer support in other pages?

**Comment by cholmes** [comment]
Cool, tried it out and works decently. It seems pretty big though? Can we make the default embed a bit smaller? On my screen it takes up more than my screen height.

I think we'll also need some instructions on the page for people to share it on wordpress.

Did you do it for maps and layers? I think those are the only two types of pages we need it on.

**Comment by jj0hns0n** [comment]
I think we can work on the scaling a bit, I left it alone once it worked
and didnt really work on the scaling.

In order to do this nicely on wordpress, we need to package up that little
bit of code above and make a plugin out of it and distribute it. You would
have to install it into your wordpress install in order to use it.

Its Only for maps right now. Can make it for layers I suppose. We dont have
a layer embed page though.

**Comment by cholmes** [comment]
Assigning to myself, so I am sure to test it.

**Comment by cholmes** [comment]
Hey @ischneider  could you work with @jonpmarino on this? 

The Django side is deployed to production, see http://mapstory.org/oembed/

Can pair with Jon on the mapstory blog - can change the php there to set what we want. But it's not clear what all we need to do to enable it. We did super basic testing, but probably missed something obvious - it didn't work.

Then need to document how to do this for others. I think above Jeff suggested making a really simple wordpress plugin.

**Comment by jonpmarino** [comment]
Yes. Once we prove it on our blog we can apply for white-listing on wordpress. Have a note out to their platform services director.

@ischneider let me know when we can screenshare and try to do this.

**Comment by ischneider** [comment]
We have verified oembed works, still need to workout whitelisting and what plugins/widgets support this best.

Closing for now.
