### ISSUE TITLE
fullscreen mapviewer should have timeline

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#506]
See also #481

1) Include the timeline in full screen mode. This should be expanded if there are annotations. So should use same code as #481

**Comment by bartvde** [comment]
to get the annotations in the timeline, we need the notes plugin in the application, since this will setup the layer on the feature manager

**Comment by bartvde** [comment]
It might make sense for an easier configuration of the timeline, instead of having all these intertwined dependencies (feature manager, feature editor, notes plugin etc.).

**Comment by bartvde** [comment]
see: 

https://github.com/opengeo/geonode/commit/ef2e5ac0697a53147fc077a76a174fa6e2ba2cec

and:

https://github.com/opengeo/mapstory/commit/8234f31dd467016aeb169e2eb7a1dd274f5f9917

**Comment by bartvde** [comment]
this is ready for testing on dev @cholmes

**Comment by cholmes** [comment]
It works, but it also seems to have introduced the small icons for notes and editing features. And they show up on every page, even the small map pane. Would it be possible to get rid of those? Tucker wants it so we only have the nicer more mapstory-ish icons, like even on the edit page. That's too much right now, but we shouldn't introduce the small blue ones on every page. 

![MapStory _ US Population Density from 1790](https://f.cloud.github.com/assets/407017/145512/4d0a6c6e-7466-11e2-995c-a3bde9168ff5.png)

**Comment by bartvde** [comment]
Okay, I think this is a deploy issue, maybe my changes to the mapstory templates were not deployed I'll need to ask @ischneider how to get those on dev

**Comment by ischneider** [comment]
@bartvde we are using the integration branch on dev ATM so any changes from master need to be merged/cherry-picked in. I went ahead and did this already.

**Comment by ischneider** [comment]
@bartvde I get an error when I tried to make the viewer go 'back to smaller size':

TypeError: this.btnEdit is undefined

**Comment by bartvde** [comment]
confirmed with @ischneider on IRC that this is on the layer page e.g. http://localhost:8000/data/geonode:conflicts

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/57cb8d0796d34d999a6ba40bd8c1188b474f36d4 for the fix

**Comment by bartvde** [comment]
fix is on dev, ready for testing

**Comment by cholmes** [comment]
Looks great. Thanks Bart.

**Comment by bartvde** [comment]
closing since this is on production
