### ISSUE TITLE
when expanding timeline, basemap disappears

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#507]
currently when the timeline is expanded, the base map disappears, and only reappears after a zoom action

**Comment by bartvde** [comment]
only occurs when using the tile manager

**Comment by bartvde** [comment]
somehow the layer div is loosing all its tile children

**Comment by ischneider** [comment]
Not sure if it's related but changing the base layer also seems to show the same bug.

**Comment by bartvde** [comment]
See https://github.com/openlayers/openlayers/pull/874 by @ahocevar

**Comment by bartvde** [comment]
fixed by: https://github.com/opengeo/geonode/commit/544fb94e3096b06f5ed5060f0b1571ed62261a34

**Comment by bartvde** [comment]
this is ready for testing on dev @cholmes

**Comment by bartvde** [comment]
Hmm if I add a layer to a new map, and then switch to OSM, still no tiles.
If I don't add a layer, and then switch to OSM, the tiles load.

**Comment by bartvde** [comment]
When changing the base layer, drawTilesFromQueue is not called in the tile mgr code cc @ahocevar

**Comment by bartvde** [comment]
If I change the code in TileMgr to also listen for property visibility all works as expected:

```
    changeLayer: function(evt) {
        if (evt.property === 'visibility' || evt.property === 'params') {
            this.updateTimeout(evt.object, 0);
        }   
    },      
```

**Comment by ahocevar** [comment]
Ok, this sounds like it can easily be fixed by adding a listener for
addlayer in TileManager that does the same as the changelayer listener.

Let me know if you want me to prepare a pull request, or if you want to do
it. I could do it on Monday.

Andreas.

**Comment by ahocevar** [comment]
Ok, this sounds like it can easily be fixed by adding a listener for
addlayer in TileManager that does the same as the changelayer listener.

Let me know if you want me to prepare a pull request, or if you want to do
it. I could do it on Monday.

Andreas.

**Comment by ahocevar** [comment]
ah good, that is the right fix. Not addlayer.

**Comment by ahocevar** [comment]
ah good, that is the right fix. Not addlayer.

**Comment by bartvde** [comment]
I'll create the PR for OL @ahocevar thanks for the feedback

**Comment by bartvde** [comment]
I can reproduce it in GeoExplorer, but creating an OL testcase is non-trivial, but will try a bit more

**Comment by bartvde** [comment]
See: https://github.com/openlayers/openlayers/pull/876 without a testcase for now unfortunately

**Comment by bartvde** [comment]
In with https://github.com/opengeo/geonode/commit/b225f89fe50f9886dc60d13412db0a15c904f38b
