### ISSUE TITLE
New animation steps don't appear to load all at once in small map / full screen mode.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#511]
So I think with the new caching code there was a bit that got lost. I believe Matt deployed a version at one point that only showed the next animation step once all tiles in view had been loaded. Right now on full screen mode on layers with lots of data it looks like various parts of the map are animating at different times. So I think that maybe some queueing step is not working, it seems to display tiles as it gets them instead of waiting till the full time sequence is loaded.

This only happens when not in the map composer. When on a map page, and most apparent when on a map page in full screen mode. See like http://mapstory.dev.opengeo.org/maps/223 and put it in full screen. The same http://mapstory.dev.opengeo.org/maps/223/view works fine. So I guess the code didn't quite get all even.

**Comment by bartvde** [comment]
I think this is because in the composer it's singletile, and not tiled right?

**Comment by bartvde** [comment]
@ahocevar do you have a good idea how to achieve this behaviour without switching to singleTile?

**Comment by bartvde** [comment]
I guess simply switching to singleTile and the GWC mosaicking is also an option for the viewer

**Comment by cholmes** [comment]
Ah, you're right, I didn't realize the composer was single tile.

I'd prefer not to switch to GWC mosaicking, and I'm 90% sure Matt had a way to queue all the tiles in a given frame before displaying them. Having it done on the client side will ensure better caching, especially once we get cdn's like cloudfront in place, because all clients will ask for the same tiles.

**Comment by ahocevar** [comment]
This could easily be done with a layer loadstart listener, a layer loadend listener, and an !important css that overrides the  opacity to 0 on loadstart, and to layer.opacity on loadend.

**Comment by bartvde** [comment]
@cholmes what Matt had wasn't compatible anymore with the latest OL tilemanager, but I'll try @ahocevar's suggestion right now

**Comment by bartvde** [comment]
I've deployed @ahocevar's suggestion to dev but it is (still) causing flickering, even with removeBackBufferDelay set to 2500 see: https://github.com/opengeo/geonode/commit/d9f14c609c74079e46c7054c525612ff66334376

@ahocevar any more ideas? TIA.

**Comment by cholmes** [comment]
Yeah, flicker is still pretty bad.

**Comment by ahocevar** [comment]
`removeBackBufferDelay` should not even be needed. I successfully modified the OpenLayers fullScreen.html example to do what you need. This diff should help you get there:

```
diff --git a/examples/fullScreen.html b/examples/fullScreen.html
index f5df04a..814c67d 100644
--- a/examples/fullScreen.html
+++ b/examples/fullScreen.html
@@ -23,6 +23,13 @@
                 background-color: white;
                 padding: 0 0.5em 0.5em 0.5em;
             }
+
+            .fade-all .olTileImage {
+                display: none !important;
+            }
+            .fade-all .olBackBuffer .olTileImage {
+                display: inherit !important;
+            }
         </style>
         <script src="../lib/OpenLayers.js"></script>
     </head>
diff --git a/examples/fullScreen.js b/examples/fullScreen.js
index 754cabf..2bfe3fb 100644
--- a/examples/fullScreen.js
+++ b/examples/fullScreen.js
@@ -8,6 +8,14 @@ var map = new OpenLayers.Map({
     div: "map",
     layers: [
         new OpenLayers.Layer.XYZ("OSM (with buffer)", urls, {
+            eventListeners: {
+                loadstart: function(e) {
+                    OpenLayers.Element.addClass(e.object.div, 'fade-all');
+                },
+                loadend: function(e) {
+                    OpenLayers.Element.removeClass(e.object.div, 'fade-all');
+                }
+            },
             transitionEffect: "resize", buffer: 2, sphericalMercator: true,
             attribution: "Data CC-By-SA by <a href='http://openstreetmap.org/'>OpenStreetMap</a>"
         }),
```

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/f89a5cf1c3856be618fa141df82d0c0cbea0ff92 it's now on dev, but the behaviour on fullscreen playback on e.g. http://mapstory.dev.opengeo.org/maps/223 is not what is expected, unless I did something wrong here @ahocevar

**Comment by cholmes** [comment]
Looks like the tiles are coming in all at once, but going away one by one.
I'd guess there just needs to be something to keep the old tiles until the
new ones are displayed, instead of turning them blank when the new one
comes in.

**Comment by bartvde** [comment]
thanks to @ahocevar that has now been fixed, ready for testing on dev @cholmes

**Comment by cholmes** [comment]
Great job on this guys. I think it got totally pushed to production, so am closing this. And I just managed to figure out the gwc bug on production, so things are working _great_ there now.
