### ISSUE TITLE
cannot add same layer twice

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#512]
Not sure if this is needed for any reason but it used to work. In the past, this has been used for styling tricks.

To test, go to /maps/new, add a layer from search dialog. Then try again.

**Comment by bartvde** [comment]
I think this was introduced when we went to search API for addlayers, will fix

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/6e144c20d5cb5208bb74dcfaa2e703840c5bf775 for the fix

I do see other strange things (adding both conflicts and exams has the second layer "disabled" / grayed out in the layer manager), not sure why this is, but it's unrelated to this change AFAICT

**Comment by bartvde** [comment]
this is ready for testing on dev @ischneider
