### ISSUE TITLE
No visual feedback when changing topic

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#513]
In the info tab if I change the 'topic' it's totally unclear if I did. The publishing status nicely updates, so ideally this one would as well. If i do a page refresh then the newly selected topic changes, so it is working. But after changing it I get no feedback that the change was successful.

**Comment by cholmes** [comment]
Sorry, forgot to specify 'map' or 'layer' page. Both appear to be not working.

**Comment by ischneider** [comment]
Update the 'current' topic text on success.

**Comment by cholmes** [comment]
Looks great, though it seems to miss one corner case. If there is no topic already set then when you set one the 'this has not yet been tagged' fades away, but the current topic does not pop up. See http://www.screenr.com/ywq7 From there on a reload though everything works great, and any map with an existing topic works great.

**Comment by cholmes** [comment]
(tested the above on both maps and layers, they are the same).

**Comment by cholmes** [comment]
This is deployed on dev, ticketed the corner case that doesn't work.

**Comment by cholmes** [comment]
by dev I meant prod
