### ISSUE TITLE
Unable to set mapstory to anything other than private

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#514]
This appears to be a regression. I don't know that I've fully got all the cases, but hopefully looking at the code may help. It's a bit hard to test some of the corner cases.

If I make a new mapstory I can't set it to anything other than 'only visible to me'. If I take an existing mapstory that is already public I can't seem to set it to 'anyone with a link can view'. I can however seem to set it to 'only visible to me'. But then I can't set it to anything else. But that one I could only test once, since I don't have many existing mapstories that are public.

Layers seem to be working fine though, once all information is filled out. There are some small tweaks that would make some better user interaction, but I'll come back to those later, there are bigger priorities now.

**Comment by ischneider** [comment]
To prevent cheats, a map requires it's layers to be metadata complete as well. There was no feedback regarding this, so I added it.

The rules about this need more discussing - for example, what if I've made a map with someone else's layer that has been turned private or was just 'linkable'

**Comment by cholmes** [comment]
Tested, looks to be working well. I agree there's some deeper things to discuss, but let's get this deployed and iterate.

**Comment by cholmes** [comment]
verified on dev.
