### ISSUE TITLE
Consider thumbnails to be required metadata to show up in search.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#515]
Right now there are a number of maps and layers that don't have thumbnails. It'd be good to have them not show up in search. Easiest way is probably to just consider them to be required metadata, along with the other metadata. Then people will have to make a thumbnail to go public. Which makes sense, it's something we do use as valuable metadata.

**Comment by cholmes** [comment]
Is this deployed to dev? I don't see it working. If I go to http://mapstory.dev.opengeo.org/search I see a number of non-thumbnailed maps. See:
![MapStory _ Search](https://f.cloud.github.com/assets/407017/221868/91ea1f72-85ab-11e2-9feb-bec35c7bb2e7.png)

Going to remove ready for testing label. Let me know if we're just not communication properly. But the result of this should be that no black X images appear in search. Or is some script / migration thing needed to get it all working right?

**Comment by ischneider** [comment]
Executing an 'audit' is required to hide things. Unless we actually populate some metadata, everything will be hidden. To be sure the way it works now (only for _new_ layers) is:
1) initially a layer is private
2) until meta data (including thumbnail) is complete, it cannot be marked public
3) only public layers appear in search

The same issue exists on production.

**Comment by cholmes** [comment]
Cool. Seems to be working, at least with a bit of testing.

**Comment by cholmes** [comment]
Verified on dev
