### ISSUE TITLE
user driven thumbnail generation doesn't work

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#516]
On dev on maps and stories whenever I push the 'generate thumbnail' button it seems to hang with some loading type bar of 'generating thumbnail' and not do anything. On one occasion I thought after I killed the loading thing by reloading I thought it updated. So I thought it was maybe not just giving feedback that it was successful. But I couldn't reproduce the successful generation, even after letting it hang for 4 minutes.

**Comment by cholmes** [comment]
Working well. One little tweak it'd be nice to have if it's not hard. After successfully generating the thumbnail it shows in the little pop-up the new thumbnail. But on the info page itself it's the old thumbnail, until you hit 'reload' or revisit the page. If it's not too much work it'd be good to force the reload on the image, so people know that the thumbnail was updating. Though if it's a bitch don't worry about it.

**Comment by cholmes** [comment]
Perfect.

**Comment by ischneider** [comment]
on production and verified
