### ISSUE TITLE
Keyword upgrades

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#518]
A longer term issue (not current priority), but wanted to add to queue:

Can we make 2 changes to keywords? 

1) Can they appear in alphabetical order in the drop-down? Currently they seem to show up by most recently added, or some other algorithm.

2) Can we add a text-fill search box for keywords, like the one we have for StoryTeller search? Ideally this would auto-fill. In the meta-data portion of creating/uploading content, perhaps the keyword box could gain auto-fill powers? Or maybe a drop down (like the topic tag box) but that has an option for "add new"? Want to try and make it simple for the same keyword ideas to group together so we can use them as aggregator tools for similar live topics (like a hash tag).

**Comment by ischneider** [comment]
sorted keywords pushed to dev. did not do auto-fill but instead added scrolling to constrain height in page.

**Comment by cholmes** [comment]
Closing this, as the are on prod. Can revisit auto complete in another ticket.
