### ISSUE TITLE
Place pages

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#519]
Propose creating a 'place page' that uses basic design of the Organization Page. In the "Search" schema, we would add a search text box under "Where" for users to search place pages, like they would a StoryTeller or Organization Page.

Unlike organization pages, Place pages would be open and policed by the community via common standards. The 'About' content for the place page could just pull from Wikipedia pages. If no Wikipedia page exists for the page, the page would simply say so....inviting the user to go create that Wikipedia page.

Place pages would probably have to sit at the URL mapstory.org/place/NAME or something to avoid crowding out potential Organization Page URLs.

The result would be the ability for content to emerge around a place by the name we use for it, in addition to the geo-coordinates allowed for by the Bounding Box. These pages would become go-to commons for residents of places.

Would also have to add an option to assign content to a Place page in the upload metadata.

**Comment by jj0hns0n** [comment]
@cholmes Whats the priority on this one?

**Comment by jonpmarino** [comment]
Irrelevant based on new redesign
