### ISSUE TITLE
ExpatError in time_info.json endpoint

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#52]
Bart is seeing an intermittent error in the time_info.json endpoint for detecting the time attribute on temporal layers.  This is blocking timeline development.

**Comment by bartvde** [comment]
This was fixed by applying Ian's patch for httpclient.

**Comment by dwins** [comment]
fixed in dev, not on the demo

**Comment by bartvde** [comment]
Has this been fixed on demo as well in the mean time?

**Comment by mpriour** [comment]
This appears to be fixed in geonode commit https://github.com/opengeo/geonode/commit/a031c5a30c8dc2b2ff26ca5fc990c74d7de2b8ee
Manual tests locally on developer machines and on the dev server could not reproduce the error after this change was applied

**Comment by bartvde** [comment]
@matt this is a different issue. The expat issue appeared when running multiple simultaneous requests on time_info and was fixed by applying a patch to httpclient.

**Comment by mpriour** [comment]
Closed either way though, right?

On Thu, Dec 22, 2011 at 4:33 AM, Bart van den Eijnden <
reply@reply.github.com

> wrote:
> 
> @matt this is a different issue. The expat issue appeared when running
> multiple simultaneous requests on time_info and was fixed by applying a
> patch to httpclient.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/opengeo/mapstory/issues/52#issuecomment-3247616

## 

Matt Priour
OpenGeo - http://opengeo.org/
Expert service straight from the developers

**Comment by bartvde** [comment]
Sure assuming this fix made it to the demo server (that's why dwins originally reopened it).
