### ISSUE TITLE
Play back seems to slow down

### ISSUE THREAD

**Issue by iwillig** [MapStory/mapstory-meta#521]
While playing a map, it seems like the time between each frame slows down. This is only on some maps. Below is a map that highlights the issue.

http://mapstory.dev.opengeo.org/maps/87

One Firefox and Chrome on Linux (Debian).

**Comment by ischneider** [comment]
Confirmed. Labelling as High for now.

**Comment by iwillig** [comment]
Closing this as I think is no longer an issue.
