### ISSUE TITLE
Add space for video on 'sign up' page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#522]
Would like to add space for a video to exist in the white space on http://mapstory.org/account/signup/.

The video will be a 2 minute 'welcome to the community' video that emphasized the fact that MapStory is a work in progress...new functionality coming all the time.

**Comment by cholmes** [comment]
@jonpmarino - do you have a video ready to go for this? It shouldn't be hard to do, but I'd prefer to do it when we can slot a video in.

**Comment by cholmes** [comment]
Duplicate of #646 as that seems to be the same. So closing.
