### ISSUE TITLE
Amend automatic email language when new user signs up

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#523]
Want to change text of email users receive when they decide to create a MapStory account.

Will add a clear set of action steps they should take now that they are member of community (i.e. 1. complete profile 2. search for content 3. check out how-tos, reflections and resource pages 4. add ideas on Feedback 5. get involved....see wiki.) Also will embed welcome video into the email itself.

**Comment by cholmes** [comment]
I think #568 covers this now.
