### ISSUE TITLE
better click then drag on time control

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#524]
Right now if you grab the time control cursor when it's at its current spot you can slide it back and forth. And you can also click on any point in the timeline and the cursor will jump right there, which is also great.  But the one thing you can't seem to do is 'both'. I want to click on a point on the time control, and then move the slider back and forth. Right now if I click on a point that's not where the cursor is it will update to that point, but not then let me slide it to another point. So I have to click exactly right to get the slide-y behavior. Let me know if this isn't clear and I can make a video.

**Comment by bartvde** [comment]
I wonder if we can control this, or that this is default Ext behaviour

**Comment by bartvde** [comment]
I think the issue is that after the click, the mouse needs to go up, otherwise you cannot start a drag. I see no way in Ext to control this, unless hacking their code which doesn't seem trivial and might not even work at all.

How important is this @cholmes ?

**Comment by cholmes** [comment]
Pretty important, imho. Let me think about if there's other ways the interaction could work. But do think on if there's other ways to approach it, or if you can think of a different interaction. Maybe others don't use it the same way I want to, I can ask more people. But on maps that are fairly fast moving it becomes really hard to move the slider to its right place. Try like http://mapstory.dev.opengeo.org/maps/151 and put it on double speed, and try to move the slider to the point you want. 

Also youtube works that way, try http://www.youtube.com/watch?v=JYTyluv4Gws or any video. And I think that's the slider experience we want to mimic, it's certainly what I'm used to.

**Comment by bartvde** [comment]
Will this become less of an issue once the slider is aggressive, or not?

**Comment by cholmes** [comment]
I'm happy for you to focus on the more aggressive sliding first, just keep this in the back of your mind. My suspicion is that it may seem worse when that's there, not better. But happy to try it out, and that would be great to have the aggressive slider, and it could make this less of an issue. So far I'm the only one to notice this in particular, and I do think it'll make things feel better. But with a larger effort entailed I'll work to get more evidence from people that it would make things feel better.

**Comment by cholmes** [comment]
Ok Bart, I made a screencast to try to illustrate the problem, just to make sure we're on the same page. http://www.screenr.com/cAc7

**Comment by bartvde** [comment]
thanks @cholmes confirmed that it's the same issue I thought it was, maybe my explanation of it wasn't great ;-)

**Comment by cholmes** [comment]
Yeah, I thought it was, but good to make sure we're totally on the same
page.

**Comment by cholmes** [comment]
Putting this on the long term list, since it sounds like it'll require a ground up rewrite of the time slider, to not use ext.js

**Comment by ischneider** [comment]
Closing - related to old UI
