### ISSUE TITLE
video annotation playback gets covered up while timeline continues.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#525]
So the biggest problem is that the video starts to play, but the timeline continues, and covers up the actual video. So I just get the audio playing, but can't see the video. 

The behavior I believe should be to pause the timeline until the video finishes. And if the user hits 'play' again or closes the video then the timeline should also start playing again. Is that possible?

**Comment by bartvde** [comment]
I can see the following issue:

if you move the timeline such that your youtube annotation is visible, and you start play on the playback toolbar, the video will not play (it will play if it is invisible before you start playing)

**Comment by bartvde** [comment]
this is because playVideo will only be called in the show listener

**Comment by bartvde** [comment]
also, calling stop on the playback control does not always have an effect

**Comment by bartvde** [comment]
So the tick function is getting called even though _stopped is true

**Comment by bartvde** [comment]
okay so doing it in the next cycle (window.setTimeout with 0) works for stopping the control

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/252732e6c02b63c5ef2b5d86684665ff3bf15737 pulled in with: https://github.com/opengeo/geonode/commit/57f899a5b424f57a09d8ef87b5190c59606d28f4
