### ISSUE TITLE
404's with trailing /

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#526]
If I go to http://mapstory.dev.opengeo.org/maps/236/ I get a 404. If I go to http://mapstory.dev.opengeo.org/maps/236 things work fine. Could we make it so the / just gets to the map?

**Comment by jj0hns0n** [comment]
Fixed in https://github.com/opengeo/geonode/pull/12

**Comment by cholmes** [comment]
Removed 'production site' label - this isn't even 'ready for testing' as far as I can tell, I don't see it on dev. http://mapstory.dev.opengeo.org/maps/236/ still gives me a 404. Once it's deployed on dev put a 'ready for testing' label, and when I confim it we'll put on a production site label.

**Comment by jj0hns0n** [comment]
I think I added that label in error. Im pretty anal about all issues having
labels in my own projects and thought this one was the most appropriate.
Maybe we can just add a general label for "bugs" or other generic issues?

**Comment by cholmes** [comment]
Sure, add any labels you like. production site and ready for testing are just reserved for deployment states instead of classification. Definitely am happy for all issues to have labels.

**Comment by cholmes** [comment]
I guess we could also add some label prefix for the 'state' ones or something.

**Comment by cholmes** [comment]
Looks good, let's get 'er on production.

**Comment by cholmes** [comment]
Grrr... didn't mean to hit 'close'. Reopening, needs to be deployed afaik.

**Comment by cholmes** [comment]
This may have broken #557 so should check that before deploying.

**Comment by cholmes** [comment]
Verified on prod. THough found it only works for map pages, not layer pages. May make a ticket for that, but it's less important.
