### ISSUE TITLE
pre buffering of tiles

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#527]
It would be good to start pre-loading tiles for more responsive user playback. Ideal would be youtube style visual feedback of how far the map has loaded, to set people's expectations as to when it will play fast, and when they'll need to wait. 

After that's one it'd be great to have #452 in place, with aggressive time sliding on already loaded tiles.

**Comment by bartvde** [comment]
Currently I was only pre buffering until the tilemanager's DOM cache was full. Do you think it makes sense to pre buffer even further, i.e. the whole mapstory, so that the browser cache will come into play?

**Comment by cholmes** [comment]
I think just prebuffering till the dom cache is full is probably ok, at least to start and see how it goes. But it'd be good if the prebuffering continued once the user hits 'play', so it stays buffered. But youtube I feel like recently changed to not fully prebuffer the whole video, you now have to get it going to continue buffering. 

I think a very important aspect though is the visual feedback on the time slider as to where the buffer is. I mean, don't need it right at the start, but I think it'll help users understand what's going on, that pausing some to wait for the buffer will help in smoother playback. And that the buffering stops at a certain point.

So yeah, if it's easier to just do the DOM start there. I think the full pre buffer may make sense later, but keep the code simpler to start.

**Comment by bartvde** [comment]
For the code it doesn't make any difference, it's just the length the loop. 

So if full pre-buffer makes sense, it might be easier as well, since I don't have to move the buffer when play starts.

**Comment by cholmes** [comment]
From the view here I think full pre-buffer makes sense. There may be some un-anticipated reason that it won't once implemented. But yeah, if it feels like it might be easier then start with full pre-buffer.

**Comment by bartvde** [comment]
See: https://github.com/opengeo/openlayers/commit/fbc7065964266a6d69898cf6ee7d57495c52101b and https://github.com/opengeo/gxp/commit/9e9a781302ba685b00841779b187af63ad6a23a7

Pulled in with: https://github.com/opengeo/geonode/commit/b7d1bc5497768429609b8760143ffe41f5af5d0a

I am not really happy with the architecture of my changes, but it works, and I can revisit later if I get a better feeling for the architecture of the code.

Prebuffering only added to the viewer, not the composer, where speed is less of an issue.

**Comment by bartvde** [comment]
also a change in the mapstory project needed for a css addition: https://github.com/opengeo/mapstory/commit/fa062b851730229e83581620d27e7a0d99dcf959

**Comment by bartvde** [comment]
deployed on dev ready for testing @cholmes

**Comment by bartvde** [comment]
I've noticed the prebuffering is really slow on dev @cholmes, as compared to my local machine. Not sure what is going on, I'd expect GWC to handle everything and it to be fast.

Also ofcourse this change is gonna increase the load on the server, since even if somebody doesn't use the play button, all the tiles will be retrieved.

**Comment by cholmes** [comment]
I don't find it super slow on dev. GWC may not have yet cached some of the
ones you're looking at perhaps?

I hear you on the load, will think on it. We could consider starting the
pre fetching only when a use hits 'play', I think some video sites work
that way now. But let's see how it goes like this. One good idea may be to
make the option easily configurable. Like so we could just hit a button on
the django admin to select the pre fetch we want to do 1) pre-fetch on load
2) pre-fetch on use hitting play and 3) don't pre-fetch. This would let us
dial it down if we started to get too much load on the server.

**Comment by cholmes** [comment]
Looks good. I'd say it's even ready to deploy in current state, where prebuffer=true is a secret way for people to get prebuffering.

**Comment by cholmes** [comment]
Verified on prod. Still need more work so it's generally usable.

**Comment by glynnis** [comment]
Closing this. If this is still relevant, please create a new issue at https://github.com/MapStory/mapstory/issues, where the team will be working from in 2017.
