### ISSUE TITLE
Update mapquest imagery layer to new tile scheme.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#528]
Mapquest seems to have updated their satellite layer to not work with our existing code. Andreas updated gxp, let's push this to production as fast as we can.

**Comment by bartvde** [comment]
pulled in with https://github.com/opengeo/geonode/commit/ff99a95f9566eb280e8d19242bda806e3e767c83 and https://github.com/opengeo/geonode/commit/9fa653e4b6d8f102dc1f3affa5bdc273163cbedf

**Comment by cholmes** [comment]
Thanks Bart.

**Comment by ischneider** [comment]
Now it's actually deployed.

**Comment by bartvde** [comment]
thanks @ischneider what timezone are you in ;-) ?
