### ISSUE TITLE
playback stalls if there is only 1 value

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#530]
This happens with the US drones dataset.

Original report by @cholmes on mapstory-dev

Does going to http://mapstory.org/maps/471 and hitting 'play' crash anyone else's browser? I tried with chrome, ff and safari.

Bart, could you look in to it if you can reproduce?

The root layer doesn't load for me at all, just getting a 'loading map' thing - http://mapstory.org/data/geonode:DronesOverUS

If I try to make a new layer from it, in the composer, I get similar behavior to the mapstory. It loads, but doesn't playback.

**Comment by bartvde** [comment]
it will create an endless loop in this case

**Comment by bartvde** [comment]
now to find the best way to handle this more gracefully in the code, I think the play button should be disabled in this case

**Comment by bartvde** [comment]
maybe we should not even show the playback toolbar in this particular case

**Comment by bartvde** [comment]
I went for the last option, since that makes the most sense to me, GXP change is here: https://github.com/opengeo/gxp/commit/bab0b765c12d50e6bd9ffbd98085be2f29469995

**Comment by bartvde** [comment]
pulled in with https://github.com/opengeo/geonode/commit/2d12ee71e55e1101c82d6f93729296e6e70cdb30

**Comment by bartvde** [comment]
this is ready for testing on dev @cholmes you might need to upload the drones layer here if it's not there already, I've only done that locally

**Comment by bartvde** [comment]
@ischneider should this case be caught by the uploader as well?

**Comment by cholmes** [comment]
Everett just tested on dev, he had reported a very similar issue on prod, and uploaded the same dataset to dev and it worked, I assume since this fix was deployed. It does actually playback so I think this fixed something a bit more. See http://mapstory.dev.opengeo.org/data/geonode:panplateid_Project vs http://mapstory.org/data/geonode:panplateid_Project

But the fix does seem to have worked, so let's get this deployed to prod.

**Comment by bartvde** [comment]
This does not seem related to me @cholmes for this dataset the start and end date differ, are you sure it's the same?

**Comment by cholmes** [comment]
No, not sure at all. But the crash is exactly the same on prod as my reported issue (drones). And if he puts it on dev it works fine.

**Comment by bartvde** [comment]
I am quite sure this fix killed @ischneider's map http://mapstory.dev.opengeo.org/maps/200 since it's got a single value, but it's actually a range:

"values": ["2012-01-01T00:00:00.000Z/2012-08-01T00:00:00.000Z/P1D"]

**Comment by bartvde** [comment]
So I am gonna revert this change as well.

**Comment by bartvde** [comment]
Hmm and it doesn't even fix @ischneider's map ..... confused.

**Comment by bartvde** [comment]
okay with this reverted http://mapstory.dev.opengeo.org/data/geonode:panplateid_Project still works so this was not related
