### ISSUE TITLE
Better steps when dragging the slider

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#534]
Check the screencast, probably easiest way to explain: http://www.screenr.com/ZKc7

Basically right now when dragging our slider will look like it can go to far more time 'steps' than it actually can. It'll drag and report back different dates. But then will snap to the actual step more slowly. I think it'd be better to snap more, to not drag between and give date updates, unless there is a real date there. There may be another way to approach this, but basically right now it often feels like it's not working quite right, even though it is.

**Comment by bartvde** [comment]
I am curious to hear if the fix for #536 will make this less of an issue @cholmes

**Comment by cholmes** [comment]
It does make things a decent bit better, since it gives a visual feedback when you're on a step. Let me leave it open for a bit, to think on if it's the ideal now or not.

**Comment by cholmes** [comment]
Yeah, I'd say it's good enough for now. Could be better somehow, but I'll just close this.
