### ISSUE TITLE
'Additional playback options' not persisting

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#535]
In the 'display' properties for a layer on mapstory we have an checkbox for 'playback options', with a drop down for normal, ranged and cumulative. Let's  you change the type of playback for one layer to be different than the map as a whole.

Right now it doesn't seem to work at all. When you close it the changes don't persist at all. I'd imagine it should update right away, and stay persisted. I made a bad screencast where I thought it was working on dev. But in the middle of it realized I was just doing different things, and it doesn't seem to work on dev or prod. See http://www.screenr.com/BXc7

**Comment by bartvde** [comment]
looking at this one now

**Comment by bartvde** [comment]
@cholmes some properties had been renamed probably during the redesign, but not all of the code was updated to reflect this.

I think I've fixed this with: https://github.com/opengeo/geonode/commit/429310232f7bcb8cedab3bf3093d746388624460 but please test on dev since you know this functionality much better than me.

**Comment by cholmes** [comment]
Hrm, initial testing isn't yielding many positive results. It seems maybe a
slight bit better? But for the most part it seems like if I change the
settings and close the window they don't get saved. Can make another video
for you. But I think it's pretty easy to replicate, just change the drop
down or turn on/off and then close and it usually goes back to the last
state. I can't figure out the things that _do_ make it stick, though
sometimes it does seem to.

**Comment by cholmes** [comment]
Though I also may have not cleared my cache properly, will try to.

**Comment by bartvde** [comment]
when I tested on a new map, the option persisted on-the-fly, and also after saving the map

**Comment by cholmes** [comment]
Ok, let me do some more testing. Haven't tried fully saving map yet. What
map did you test on?

**Comment by bartvde** [comment]
I just created a new map locally and added the google flu trends layer

**Comment by bartvde** [comment]
If I change it to cumulative, it will stay on cumulative. The checkbox will not be checked again, is that what you expect?

The checkbox is only used to bind the combobox to the layer before changing the value. But I agree this is not the best UI experience.

**Comment by cholmes** [comment]
Just made a screencast, see http://www.screenr.com/68F7

Though those changes seem to have somehow totally screwed up my mapstory.
http://mapstory.dev.opengeo.org/maps/188 doesn't seem to play in small
view. And in big it looks like it's trying to do cumulative.

**Comment by cholmes** [comment]
I think the ideal would be if the checkbox is off then the grayed out thing
would report the overall state of the map. Like if the overall map is set
to cumulative then if the checkbox is off for the layer it reports
cumulative. Or same for normal and ranged. So it communicates that it's
getting its value from the map.

If its checked than it should stay at what's been selected in the drop down.

**Comment by bartvde** [comment]
it seems to be related to having 2 layers, I only tested with 1 layer, will have another look

**Comment by cholmes** [comment]
Yeah, the only time to ever use this option is if you have two layers. You
want the map to be one way, and one or more of the layers to be the other
way.

That said I am getting similar problems with a single layer :(

**Comment by bartvde** [comment]
I can't reproduce on a single layer on dev. I added bugsites, set it to cumulative. Close the dialog, open it again, and it's still cumulative, but the checkbox is unchecked.

If I pick ranged, it's still range, but the checkbox is also still checked.

**Comment by bartvde** [comment]
Okay but if I put it to normal, it stays on ranged (the previous choice). So maybe it's got to do with the value chosen.

**Comment by cholmes** [comment]
Yeah, or it may be that the first change works better? And the second and
beyond has trouble? I'll try to play more in a bit, but I never managed to
get deterministic behavior of when it _would_ change.

**Comment by bartvde** [comment]
I am hoping that this improves things: https://github.com/opengeo/geonode/commit/55928f6d70110b45ec03c1b2a28d5a8706d9ff44

Haven't tested with more than 1 layer though, deployed to dev as well @cholmes

**Comment by cholmes** [comment]
Um, it's like maybe a little better? But after a few changes I can still
get it 'stuck' in normal...

**Comment by bartvde** [comment]
does it depend on the mode setting of the map/toolbar at all @cholmes i.e. do you change that, or you don't touch that setting at all.
Also, did you use 1 layer or more?

**Comment by cholmes** [comment]
Just used one layer. And do you mean the playback setting of the map? Or
any settings of the map?

I don't set it at all. But the disturbing thing is that it looks like it
gets set when I set the layer playback option. Like if I change the layer
playback to 'cumulative' then the map's time control switches to cumulative
mode. Are they like somehow writing to the same variable or something?

**Comment by bartvde** [comment]
yeah the playback mode of the map, which can be set through the playback toolbar's options panel

I think they are connected, looking at the code:

```
        switch(mode) {
            case 'cumulative':
                if(this.playbackToolbar.playbackMode == 'track') {
                    this.playbackToolbar.setPlaybackMode('cumulative');
                }
                break;
            case 'range':
                if(this.playbackToolbar.playbackMode != 'ranged') {
                    this.playbackToolbar.setPlaybackMode('ranged');
                }
                break;
        }
```

but I don't know much about the history of this.

**Comment by cholmes** [comment]
Hey, so it sounds like there's a lot of things that we should maybe
rethink, about the various playback modes. But we're aiming for this ames
map, where we only do need to make _one_ change, one layer from cumulative
to normal. And I think we can pull that off with what we have now.

There is one slight problem though, which it seems like in the non-edit
view the time slider doesn't show up if the map isn't all cumulative. So I
think if we could fix _that_ problem then we should just push this fix and
let Nitin make the proper map. And then we can investigate the deeper
problems later.

See http://mapstory.dev.opengeo.org/maps/255 vs
http://mapstory.dev.opengeo.org/maps/254 for the two maps. Same layers,
first is cumulative for all layers. Second is cumulative for all except the
city limits. Which is the one we to be working right. But it does work
totally fine if you go to http://mapstory.dev.opengeo.org/maps/254/view

**Comment by bartvde** [comment]
Okay so the question is why doesn't the playback toolbar show up on: http://mapstory.dev.opengeo.org/maps/254 will investigate

**Comment by bartvde** [comment]
I wish we had a utility to copy a mapstory and deploy it locally ;-)

**Comment by cholmes** [comment]
I _believe_ @mweisman is working on that? Or at least the first steps to it? We have him for a bit of time, so I think that should be the goal.

**Comment by bartvde** [comment]
I just created a map locally with 2 times the google flu layer, and made the top one range and the bottom one cumulative. But after loading the saved map, things are not okay. Top one is set to normal, bottom one is set to ranged. I am also not sure how time agents for the same layer are taken apart since they use the layer's name AFAICT.

**Comment by bartvde** [comment]
When the timeManager's agents are getting restored, they are both associated with the same layer WMS_71 which is not okay, one of them should be associated with WMS_75 but not yet sure what is causing this

**Comment by bartvde** [comment]
Okay I am going to take a step back here and start with two different layers

**Comment by bartvde** [comment]
I am having a lot of trouble understanding this code (GeoExplorer.TimeLayerPanel)

**Comment by bartvde** [comment]
So it seems that after splitManagerAgents is getting called, we can get into a situation where the combo's agent is correct, but this._agent is wrong (for the wrong layer).

**Comment by bartvde** [comment]
I've successfully tested the two distinct layers case with this fix: https://github.com/opengeo/geonode/commit/1ca4414ceca30839dde48e897a44ab28a640f5bb

**Comment by bartvde** [comment]
The cause of  http://mapstory.dev.opengeo.org/maps/254 not working seems to be that the time agents are getting created without a dimension manager, but not sure what the actual root cause is yet.

**Comment by cholmes** [comment]
Hey Bart, the saving of playback is working _much_ better, haven't hit any bugs with it yet. But got the same non-playing small map when I saved it out - http://mapstory.dev.opengeo.org/maps/259  Will try to do more testing on the other cases, but will be traveling today so not sure if I'll get the time.

**Comment by bartvde** [comment]
thanks @cholmes yeah I am expecting that to be the same issue as http://mapstory.dev.opengeo.org/maps/254 but haven't tackled that one as yet unfortunately

**Comment by cholmes** [comment]
No worries. And yeah, I'm sure it's the same issue, very similar set up. It
was just the first time I'd replicated it, so thought I'd mention it in the
thread.

**Comment by bartvde** [comment]
Yeah I wish I was able to replicate it locally with the layers that I have setup.

**Comment by bartvde** [comment]
Good news I finally reproduced locally.

**Comment by cholmes** [comment]
Awesome, yeah, I was just about to try to get you instructions on how to,
as I think I have a decent idea of the unique things that result in it.
Thanks Bart, you've been doing truly awesome work on mapstory this last
little bit.

**Comment by bartvde** [comment]
The issue seems to be that in this case the agents are constructed before the control itself has been created, see also: https://github.com/opengeo/gxp/blob/master/src/script/widgets/PlaybackToolbar.js#L379

but it's kind of a chicken-egg problem. Not sure how to deal with this.

**Comment by bartvde** [comment]
Maybe we need to let the control create the agents based on config instead? But I wonder how this ever worked.

**Comment by cholmes** [comment]
I think it may not have ever worked. I remember seeing some similarly
static maps but wasn't sure of the cause.

**Comment by bartvde** [comment]
This feels like getting into the weeds, I can get the playback toolbar to show up properly, but I can't get it to play as yet

**Comment by bartvde** [comment]
I made some changes in OL and GXP to hopefully address all of this, the mapstory now plays locally, but I really need someone with more experience in MapStory to test this out, especially if I did not break anything. Deployed to dev just now @cholmes.

https://github.com/opengeo/openlayers/commit/e7281966bd7334bfe70c798b41f6adde0562119f
https://github.com/opengeo/gxp/commit/64034bd2794ca56e4671cb9d86d0db20e9b6f1d2

Pulled in with: https://github.com/opengeo/geonode/commit/259a4315dc5141a3e33b8163f6ac084387bf7aaf

**Comment by bartvde** [comment]
I thought this would fix @ischneider's map as well http://mapstory.dev.opengeo.org/maps/200 but it does not unfortunately

**Comment by cholmes** [comment]
Hey, so the dev server is down now, so can't get great testing. But in my limited testing I think things are pretty messed up. The time slider isn't showing up at all in some other maps. Like was looking at maps like http://mapstory.dev.opengeo.org/maps/258 and the slider doesn't load. It just has one layer. Some other one layers maps were like that. I think I tried some with two layers, but with out a mixed playback. So I think maybe you fixed mixed playback, but it broke the others? http://mapstory.dev.opengeo.org/maps/258/view also doesn't load the slider. I also made a new map and saved it out, with mixed normal and cumulative playback. And it messed up too, no time slider: http://mapstory.dev.opengeo.org/maps/260

My internet connection was maybe not great, so there could be other things going on. But yeah, looks like the change introduced some unanticipated consequences.

**Comment by cholmes** [comment]
I think I get a javascript error of 'Uncaught TypeError: Cannot read property 'length' of null ' on http://mapstory.dev.opengeo.org/maps/252

**Comment by bartvde** [comment]
@cholmes are you sure that those maps played before this change? Just trying to pin things down.
Update: yeah it seems my change broke something, looking into it now.

**Comment by bartvde** [comment]
The issue is that in buildAgents in the DimensionManager control layers is null somehow:

```
        //categorize layers and separate into arrays for use in subclasses
        for(var i = 0, len = layers.length; i < len; i++) {
```

I am gonna revert my changes and look for a more robust solution.

**Comment by bartvde** [comment]
Reverted and deployed this map works again: http://mapstory.dev.opengeo.org/maps/258

**Comment by cholmes** [comment]
Cool. And yeah, I was quite sure that things worked before the change. Let
me know if I can be of help testing, I have the morning free.

**Comment by bartvde** [comment]
Looked at this again today, but haven't found solutions without issues unfortunately.

If I create a new map locally and add Conflicts as well as Wallmart distribution centers, I get the playback toolbar. But it does not actually play. Is this to be expected?

**Comment by cholmes** [comment]
I think it should? I'm not sure about conflicts, it may not be time
enabled. I mean, if you have a non time one I think the whole thing should
play. But I'm not sure that I've actually seen that before.

**Comment by cholmes** [comment]
Sorry, in the comment before I meant to say that yes, the playback toolbar should play. If there is time enabled data in any combination of normal or cumulative then the playback should work in both small map and map editor. I don't know if things actually truly worked before. But the old killer bee demo was the one to show both, and it no longer seems to work anywhere.

I'm going to remove ready for testing label, as it seems like there's more to do here. I'm fine if you want to take longer and rewrite things. Fine to consider dropping 'ranged' too, or at least to not make it a mixed option.

**Comment by bartvde** [comment]
Okay looking at this one again today

**Comment by bartvde** [comment]
Investigating http://mapstory.dev.opengeo.org/maps/259/ first, it seems that the Dimension agent has no currentValue and has not yet been associated with a dimensionManager as yet, this is happening in calculateLayerInRange

If you run http://mapstory.dev.opengeo.org/maps/259/view/ instead this.currentValue is set as well as this.dimensionManager

**Comment by bartvde** [comment]
Interesting this is actually caused by the prebuffer code. Since using prebuffer=false the playback toolbar shows in the viewer.

**Comment by bartvde** [comment]
So there are cases where the control config contains agents, and there are cases where it does not contain them. These cases differ in the way they should be handled, hence complicating the solution here.

**Comment by bartvde** [comment]
If they are not supplied in the config, they get created in the setMap function of OpenLayers.Control.DimensionManager with a call to buildAgents

**Comment by bartvde** [comment]
Likely it's better to move the prebuffering code from the agent to the control.

**Comment by bartvde** [comment]
This it turning out to be a tough issue again.

**Comment by bartvde** [comment]
okay so it's actually the calculateInRange function on the clone that is causing this

**Comment by bartvde** [comment]
I'm hopeful that this change fixes the issue here but it needs testing for sure: https://github.com/opengeo/openlayers/commit/ed51e6b22c20a9523fa15f89661a51e8a8590c6b pulled in with 341aaa9618a473dc06dc11668bcec8b9f0ea5ab7

**Comment by bartvde** [comment]
Forgot one change: https://github.com/opengeo/gxp/commit/7cec9082d4611273698335fe8a7fe99af9f54f03 pulled in with https://github.com/opengeo/geonode/commit/9de01e23b4a04479db2d6a3817b4d5d6509c33a6

**Comment by bartvde** [comment]
Okay this one now works: http://mapstory.dev.opengeo.org/maps/259/?prebuffer=true but the progress bar is acting weird, probably because the progress value is not reliable when using multiple agents. Need to work on that as well.

**Comment by bartvde** [comment]
Looking now at changing the strategy for calculating the progress, since there are a lot of flaws currently.

**Comment by bartvde** [comment]
changed the progress bar here: https://github.com/opengeo/openlayers/commit/16665f39d84c611455e97b61c20732cf0aa38d31 pulled in with: https://github.com/opengeo/geonode/commit/e2a30d81a0f1aa045387aed4cf4d5d6dd0dafe15

Please note that the progress bar currently registers the portion of the tiles that have come in already, so it's not related to the portion of time that has been prebuffered (like Youtube). Maybe I should change that later on, what are your thoughts on this @cholmes ?

**Comment by bartvde** [comment]
AFAICT the issues from this ticket have been resolved, and can be tested by adding ?prebuffer=true on the above maps

deployed to dev as well

**Comment by cholmes** [comment]
Portion of tiles is fine, no need to do time.

**Comment by cholmes** [comment]
Great, will try to test later today. Thanks Bart!

**Comment by cholmes** [comment]
Verified on prod
