### ISSUE TITLE
Flicker when at the end of a scrub movement

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#536]
Ok, first off let me say that the results of the real time scrubbing are exceeding my expectations. I realized this today when I paused the animations and just moved back and forth. See http://www.screenr.com/Ckc7

Playing with it more I found some flickering. See http://www.screenr.com/nkc7 If you move the slider fast then it does perfect animated scrubbing, it's awesome. If you move more slowly it flickers. 

Realized that the flickering doesn't happen if you move past the end of the timeline. It maybe misses some event that is causing the flicker? If we can get rid of that flicker it'll be _huge_. See http://www.screenr.com/Fkc7 for example and some explanation.

**Comment by bartvde** [comment]
buffering the change event with a larger value causes less flicker, but also less updating, but that's probably only masking the root cause

**Comment by bartvde** [comment]
fixed in OL dimNG branch with https://github.com/opengeo/openlayers/commit/84741629ab86f9b10e49ef90cae6d916e3442c0b and pulled in with https://github.com/opengeo/geonode/commit/45b7553240b348882a4123f863ca52c60102050b thanks again @ahocevar for the pointer to what caused this issue

**Comment by bartvde** [comment]
ready for testing on dev @cholmes

**Comment by cholmes** [comment]
Totally f'n' awesome. You're my heroes. This is huge.

**Comment by cholmes** [comment]
Removed 'ready for testing' label as scrubbing / aggressive time slider is not currently working on dev.

**Comment by cholmes** [comment]
On production.
