### ISSUE TITLE
click in timeslider when playing does not work anymore

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#537]
This came up in #452 but is not directly related.

**Comment by bartvde** [comment]
Actually it is related to the last change, the _silent change, but leaving it as a separate ticket anyway.

**Comment by bartvde** [comment]
So clicking in the slider triggers a change and changecomplete event, but there is not really a way to distinguish these events from the ones that are fired when the toolbar is playing. Need to find a way though.

**Comment by bartvde** [comment]
Fixed in gxp with: https://github.com/opengeo/gxp/commit/e7bb80f707935f5b381f77667878bda126a936f7 and pulled in by https://github.com/opengeo/geonode/commit/68f55404f3262ccff56a26006bf6c662464eecb4

**Comment by bartvde** [comment]
deployed on dev @cholmes so ready for testing

**Comment by cholmes** [comment]
I don't know that I understood the original problem. But I think this does work now.

**Comment by bartvde** [comment]
This actually broke dragging the slider (and the aggressive dragging) ....

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/58bf271e9a62ac2579e308f39fa48418022fda68 and https://github.com/opengeo/geonode/commit/4540c3c8872d7e6f355edfb0a09d8b396176dfde

When testing, I found that this change was not needed anymore to get the click to work, so I removed it altogether would be good to get some testing on it, will deploy to dev in 5 min

**Comment by cholmes** [comment]
Verified to work on prod
