### ISSUE TITLE
download produces invalid ZIP file

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#538]
Cannot download this dataset:

http://mapstory.dev.opengeo.org/data/geonode:Comb_Renew

zip file is invalid.

@ischneider @iwillig any ideas?

**Comment by iwillig** [comment]
Strange Bart, 

When I download that zip file it seems to be working for me.

**Comment by bartvde** [comment]
works for me now as well @iwillig maybe the disk space issues?

**Comment by iwillig** [comment]
Yeah i think that was the error. Should we close this ticket?

**Comment by bartvde** [comment]
yeah feel free to close it.

**Comment by ischneider** [comment]
Closing.
