### ISSUE TITLE
Colorado temperatures map is broken

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#540]
http://mapstory.dev.opengeo.org/maps/200

This is caused by the prebuffer code, it is too simplistic and doesn't deal with all possible structures of time in the model.
cc @ischneider

**Comment by bartvde** [comment]
So does it mean a model can have a distinct set of values (an array of values), as well as a range + resolution?

**Comment by bartvde** [comment]
Yeah so the tricky part here is finding the right place for this prebuffer code ...

**Comment by bartvde** [comment]
okay tested out a fix on dev, will clean up a bit and then commit this fix

**Comment by bartvde** [comment]
see: https://github.com/opengeo/openlayers/commit/f4b2ba8a28c3f46fec5d589812d6d7c404c50998 pulled in with: https://github.com/opengeo/geonode/commit/dc79e6729ef3b2be5fee06ceaee58c7a822166c1 and deployed to dev

**Comment by ischneider** [comment]
Looked good to me. So is buffering not possible for range+resolution at the moment?

**Comment by bartvde** [comment]
it is, I added it today

**Comment by cholmes** [comment]
Removed label, this is not working for me on dev.

**Comment by bartvde** [comment]
What is not working @cholmes ? It plays for me on dev in Chrome.

**Comment by cholmes** [comment]
Ah, this was just about the actual playback, not an attempt to fix the underlying tile issue (making a single tile layer for heatmaps, etc). Yeah, playback works just fine. Due to #557 I can't actually check if setting single tile for the layer works.

**Comment by bartvde** [comment]
okay, right, no work on singleTile has been done as yet see: #541

**Comment by cholmes** [comment]
Closing this, as it's now fine on dev, and not a problem on prod.
