### ISSUE TITLE
make sure that we can force singleTile for certain layers

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#541]
such as @ischneider's map: http://mapstory.dev.opengeo.org/maps/200

**Comment by bartvde** [comment]
Since all layers are single tile in the composer, we need a way to distinguish user action from the default setting

**Comment by bartvde** [comment]
okay talked to @ahocevar about this. It would require some changes to GXP, but also to the saved map config (tiled should be removed everywhere).

GXP changes:

ok, so you need to change the way https://github.com/opengeo/gxp/blob/master/src/script/plugins/WMSSource.js#L865 is handled, and migrate the mapstory database.

if ('singleTile' in options) {config.tiled = !options.singleTile} above L862.

and remove the else statement here:

https://github.com/opengeo/gxp/blob/master/src/script/plugins/WMSSource.js#L521

**Comment by bartvde** [comment]
okay let me start on an implementation which I can test with new maps

**Comment by jonpmarino** [comment]
@davisc not sure if this is still relevant or should be pushed forward.
