### ISSUE TITLE
ability to turn-off prebuffering with a url parameter

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#542]

**Comment by bartvde** [comment]
see: https://github.com/opengeo/openlayers/commit/f01a19a10e19061e6cc7da983ad4b42085d1a147 pulled in with https://github.com/opengeo/geonode/commit/3b3354c5efe278beca6d4d1b214f49c0920b718b

@ischneider this is ready for testing, use ?prebuffer=false to turn it off

**Comment by ischneider** [comment]
This needs to be done at the settings level for the moment - there is far too much noise in the log files if anything is going wrong and it makes the dev server nearly unusable while buffering.

**Comment by cholmes** [comment]
Closing, url works, we now default to off.
