### ISSUE TITLE
User should not be allowed to hit play until layers are fully loaded (composer and playback

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#543]
I have another concern and that is while it pretty much works like
youtube, we have nowhere near the bandwidth as youtube and I worry
about excessive requests. Would it be possible to trigger buffering
only when the user presses play? Like first buffer 3 seconds worth of
tiles and then start actual playback.

reported by @ischneider

**Comment by bartvde** [comment]
extra remark by @cholmes 

Oh wait, actually, one thing would be good. If the admin sets it to say like 20 frames, it'd be really good if pre-buffering could kick in again, just when the user hits play. So instead of just playing forward through the buffer without pulling any more tiles in it'd be really good if it was pulling in more tiles. This is what basically happens now if the user hits play before the buffer is complete. So it'd be good to have the admin option of number of frames just be a 'pause' until the user hits play, and to then automatically pull in the rest of the tiles, keep on buffering till the end.

**Comment by jonpmarino** [comment]
@bartvde is pre-buffering deployed? It doesn't seem to be on Prod

**Comment by ischneider** [comment]
We disabled it as there were problems with the current approach - like too many requests.

**Comment by bartvde** [comment]
I think it makes sense to move this out of the current milestone

**Comment by jonpmarino** [comment]
need to revisit based on new playback.
