### ISSUE TITLE
Add language select radio button for homepage

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#544]
geonode dev site has the ability to change the language that text appears in on the site (radio button on the footer). Can MapStory have this as well?

**Comment by cholmes** [comment]
Well, we'd first need translations of all the assets. Since we're built on geonode there's quite a bit we can leverage from them. But there are definitely some mapstory specific ones. We'd also need to confirm we're set up for internationalization on all the necessary strings. Once we get i18n in place we could look in to using something like transifex.

**Comment by ischneider** [comment]
There are 2 parts - static assets (buttons, labels, etc.) and dynamic content. The latter can be broken into 'mapstory' content (we create it - like topic/categories) and 'user' content - abstract, attribute names/values etc.

Static assets are possible via transifex. Dynamic content is a _much_ bigger issue, especially user-provided content.

**Comment by jonpmarino** [comment]
Makes sense...especially as language and location is a huge issue in itself. Presume that's wrapped up in deeper philosophical/representation issues...tied up with longitudinal gazateer, etc.

 If its doable, I think allowing for multi-language viewing of static content would be a big win for now....helping us shop around what we have to a global audience as we're building support, investment, blah blah blah.

**Comment by cholmes** [comment]
Well even the static content will be incomplete without some decent investment. To shop around I'd say just make one or two wireframes and say that all the core technology is internationalized. 

Don't get me wrong, I think it'll be super important. Indeed we'd hopefully be able to make communities around translating it. But I think we've got a lot more fundamental issues to tackle first.

**Comment by jonpmarino** [comment]
Agreed.

**Comment by ischneider** [comment]
Closing - based on old skin and platform

**Comment by jonpmarino** [comment]
We need to inherit this functionality somehow. It seems to be in GeoNode?

**Comment by jwood106** [comment]
Just reviewed the story and its comments after Jon assigned it to me.  This is going to be a lot of work, and do not think ISTE2015 (July 1) target is do-able.  Whether we target ISTE2015 or not, maybe we discuss this afternoon in Standup parking lot targetting a specific area of app where we can demonstrate that we are underway in this work?

**Comment by jonpmarino** [comment]
Desired behavior is demonstrated here, http://demo.geonode.org/. Clearly we have multiple language issues inside MapStory - i.e. translation in data itself, translation in front end interface, translation of user generated storypins, etc. The first win is just to get the interface language to be easily toggled so non-English users can browse the site in their own language. Deeper multilingual issues in the data structure will have to come later.
