### ISSUE TITLE
Add twitter, facebook, and pinterest buttons to all mapstory pages

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#545]
similar to what is at blog.mapstory.org.

**Comment by cholmes** [comment]
Talked with Tucker on this. Easiest is to use the same 'sharethis' implementation. On the options he wanted the button bar, and put it on the left side of the screen. That will put it on all mapstory pages, including the homepage. We can investigate later adding more specific stuff to the home page.

**Comment by jj0hns0n** [comment]
Got it, easy enough to do. @cholmes @jonpmarino I need to get you guys access to the sharethis site so you can see the metrics and also add more sites if you like.

**Comment by jonpmarino** [comment]
Cool.

**Comment by jj0hns0n** [comment]
I finally figured out how to add a sidebar so its there on every page https://github.com/opengeo/mapstory/pull/622. We can customize it as necessary or move it somewhere else. This still works on the layer and map pages. See the screenshots attached. 
![MapStory _ NIC_0 5s_200y](https://f.cloud.github.com/assets/506078/306159/06344166-9671-11e2-84af-f99fd2cbf17e.png)
![MapStory _ Welcome ](https://f.cloud.github.com/assets/506078/306160/06451e0a-9671-11e2-8fe7-70fc48c54654.png)

**Comment by jj0hns0n** [comment]
Also, note in the screenshots above that when testing locally you _must_ use 127.0.0.1 ... this doesnt work on localhost for some reason.

**Comment by ischneider** [comment]
Should we remove the "Share" tabs then?

**Comment by jj0hns0n** [comment]
Works for me, probably don't need both. But let's ask @cholmes
@jpmarino and tucker

**Comment by ischneider** [comment]
sharethis hash messes with back button in browser

http://support.sharethis.com/customer/portal/questions/700642-hash-tag-causing-problems-with-the-back-button

**Comment by cholmes** [comment]
Confirmed on prod.

**Comment by jonpmarino** [comment]
Cool!

**Comment by jonpmarino** [comment]
Just tried to share http://mapstory.org/maps/594/ with FB option. The auto-generated URL still pointed to hugedomains.com. FYI.
