### ISSUE TITLE
Make it easier to delete a StoryLayer

### ISSUE THREAD

**Issue by bmmpxf** [MapStory/mapstory-meta#546]
Currently it is hard to find the link to delete a StoryLayer. You can’t do it from the StoryLayer view page as far as I can see. You have to click on your own Profile and then select the layer to delete. This is not obvious.

There is plenty of room on the right bar to put a small box where you can delete the StoryLayer. Or perhaps at the bottom of the Info tab.

**Comment by ischneider** [comment]
Closing - based on old skin
