### ISSUE TITLE
Multiple profile links are confusing

### ISSUE THREAD

**Issue by bmmpxf** [MapStory/mapstory-meta#547]
It’s feels odd how clicking on “Welcome [username]” takes you to a different place than clicking on Profile”. I would expect that to be the same target. Also, looks to me like you can see your Profile more easily from the “Welcome [username]” page than from the Profile page.

Can these two pages be combined? It's unclear why they are split into two different pages. Alternately, make a clearer distinction between them.

http://mapstory.org/mapstory/storyteller/[username]
http://mapstory.org/profiles/[username]

**Comment by ischneider** [comment]
Closing - based on old skin
