### ISSUE TITLE
"Best Guess" should be a top level “Type” not a “Date Format”

### ISSUE THREAD

**Issue by bmmpxf** [MapStory/mapstory-meta#548]
When uploading StoryLayers, the "Best Guess" should be a top level “Type” not a “Date Format”. It should be a wildcard where you can select any attribute and enter in a custom format string as you please.

This is because you may not know offhand whether your attribute in question is Text or Year Number. I know we'd like to think that we all know our data intimately, but we can't assume that. What if you don't know? Being able to access the Best Guess algorithm would make things easier in this case.

![bestguesshere](https://f.cloud.github.com/assets/506694/219421/16fafae8-852e-11e2-9efc-137140f1bd86.png)

**Comment by ischneider** [comment]
The above commit actually refs #549 :(
