### ISSUE TITLE
User should be able to select time attribute first instead of format first

### ISSUE THREAD

**Issue by bmmpxf** [MapStory/mapstory-meta#549]
Just like with issue #548, when setting the time attribute, the first options are Text and Date Format. If I select Text, I can then select a list of Text attributes, and if I select Date Format, I get another disjoint list of attributes.

This feels the wrong way around. As I user, I just want to select my attribute. I may or may not know the format, but I don't want to have to select it first. Instead, I would want a full list of all attributes (maybe with certain invalid ones greyed out). MapStory is capable of determining what format the attribute is and directing accordingly.

**Comment by emloux** [comment]
@ischneider This would be a nice enhancement to include in the work on the new uploader.

**Comment by ischneider** [comment]
This is more of a UI issue, but I agree, it's frustrating for me, too.

**Comment by ischneider** [comment]
see @6cc43801fa74caff6bf7096a0705ddd48ac21aa8

**Comment by ischneider** [comment]
Ready for testing. I just flattened the list of attributes adding the 'type' to the list. I attempted right justification of the type in the drop-down but doing this will require a bit more effort as white space is collapsed.
