### ISSUE TITLE
Dates interpreted as "days past 1900-01-01"

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#55]
Sam Smith reports some oddness in loading data through the importer - GeoNode seems to treat strings of the form "YYYY" (no month, day, etc.) as a count of days past 1900 instead of interpreting them as years.

**Comment by ischneider** [comment]
This one appears to be operator error - the same data uploaded locally using the correct field works. The other field contains invalid date objects that are interpreted as specified.
