### ISSUE TITLE
Make upload buttons easier to find

### ISSUE THREAD

**Issue by bmmpxf** [MapStory/mapstory-meta#551]
The Upload buttons (for StoryLayers and MapStories) are hard to locate. First, they don't appear to be on any page other than the main mapstory.org. Not on the Profile pages, and not on any pages where you're looking at existing content. A user is likely to want to see a StoryLayer and be able to click to Upload directly from that place. Or maybe not, but the user shouldn't have to go back to the main page to find the upload button.

Once on the main page, though, the upload buttons are hard to see. They are kind of buried in the middle of the page, in between a bunch of other buttons and and graphics.

I would prefer if the upload option were a bit more global, perhaps as part of the toolbar. Or failing that, an option on more of the pages that users are likely to spend the most time on.

**Comment by emloux** [comment]
GeoNode 2.0 does this nicely, lets take a look at how they do things

**Comment by ischneider** [comment]
Closing - based on old skin
