### ISSUE TITLE
Allow user to set the year when data doesn't contain it

### ISSUE THREAD

**Issue by bmmpxf** [MapStory/mapstory-meta#552]
Picture a data set that includes months, days, hours, but no year. In such a case, MapStory won't flinch during upload, but will set the year to be 1970 upon playback. This is arbitrary. It would be nice if MapStory could notice this and say "year not specified, please enter the year here:"

**Comment by emloux** [comment]
This needs more thought.

**Comment by ischneider** [comment]
At least a warning that this format is invalid. Adding additional functionality seems of less ROI.
