### ISSUE TITLE
Topic doesn't show when you select one

### ISSUE THREAD

**Issue by bmmpxf** [MapStory/mapstory-meta#554]
No default Topic is given at first on a StoryLayer, so on the Info tab it says “No topics selected”. When I select a topic, the “No topics selected” note goes away, but it also doesn’t actually say what topic I selected anywhere, or at least not where I would expect it.

![notopics](https://f.cloud.github.com/assets/506694/219480/e11a3048-8531-11e2-9633-9e08611c8c48.png)

The topic does eventually show up when I navigate away and then back to the page.

**Comment by emloux** [comment]
This should be working better now.
