### ISSUE TITLE
Use a hash URL for full screen mode

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#555]
On our map page we have a nice full screen mode, which is where we want most to end up instead of the /view (edit) page. But there's no way to refer to that. We should put in the anchor style reference of it, so I can refer to http://mapstory.org/maps/146#full and get the full screen.

It should additionally automatically make that url when in full screen, so that when a user copies that url to give to someone it refers to what state they're in.

Also be sure to update the 'View this MapStory fullscreen' link in the upper right hand corner to go to the #full url instead of the /view one, so that people naturally go there.

**Comment by iwillig** [comment]
It looks like that is not an amazing solution for this in Ext.js 3. 

http://stackoverflow.com/questions/298503/how-can-you-check-for-a-hash-in-a-url-using-javascript

I am going to do some research to see what the best solution for us will be.

**Comment by iwillig** [comment]
http://badassjs.com/post/840846392/location-hash-is-dead-long-live-html5-pushstate

**Comment by iwillig** [comment]
https://developer.mozilla.org/en-US/docs/DOM/window.location

**Comment by cholmes** [comment]
Cool, just skimmed one of those. But approach doesn't matter and I don't care about a hash. Just want a way to refer to the full screen state, and for that to reflect the user action. Perhaps @bartvde can sound in on approach.

**Comment by bartvde** [comment]
We can do this with plain JS, when fullscreen mode is chosen we add the hash with window.location.hash = 'full' and then when loading the map view page we check if window.location.hash equals full and then call the function to change to the full screen state.

**Comment by iwillig** [comment]
https://github.com/opengeo/geonode/pull/17

**Comment by iwillig** [comment]
Current issue on the live site, I think the timeout is set to low and the legend is in the incorrect position. 

Fix should be simple, just change this argument. https://github.com/opengeo/geonode/blob/mapstory/src/geonode-client/app/static/script/app/GeoExplorer/PlaybackToolbar.js#L57

**Comment by cholmes** [comment]
Hrm, ok, I guess the bare minimum on this works, as I can go to http://mapstory.dev.opengeo.org/maps/139#full and I get a full screen view. But there's a bunch of little issues. I'll make a ticket for each one.

**Comment by iwillig** [comment]
A lot of the issues you brought up on IRC should be fixed in this Pull Request

https://github.com/opengeo/geonode/pull/18

Thanks.

**Comment by cholmes** [comment]
Cool. Sorry I didnt get to making issues for them yet. I will wait to see
this on dev, and then report any remaining issues. Thanks Ivan.

**Comment by iwillig** [comment]
Ready for testing.

**Comment by cholmes** [comment]
Looks great Ivan. Ready for deployment.

**Comment by iwillig** [comment]
cool.

**Comment by iwillig** [comment]
Hey Chris I think that this is done. can we go ahead and close it ?

**Comment by cholmes** [comment]
Yeah, go for it.
