### ISSUE TITLE
map editing broken on dev

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#557]
THis is just on mapstory.dev.opengeo.org. But the map edit mode doesn't work any more. See like http://mapstory.dev.opengeo.org/maps/236/view/  It's some uncaught typeerror.

**Comment by bartvde** [comment]
did something change that a / gets appended automatically @ischneider ?
I think this is causing this breakage since map data is returning a 404 with the extra / in the url:

http://mapstory.dev.opengeo.org/maps/236/data/?_dc=1362500114232

**Comment by cholmes** [comment]
Yeah, looks like that's the way they fixed
https://github.com/opengeo/mapstory/issues/526

I just wanted trailing urls to work. Could do it so it redirects the other
way.

**Comment by ischneider** [comment]
The trailing slash can be added to the data URL, too. Django middleware takes care of redirecting from the non-slashed to the slashed.

**Comment by ischneider** [comment]
Crap - commit message for wrong repo. Fixed with opengeo/geonode@eaa74023

**Comment by cholmes** [comment]
Closing, since this was never a problem on production. Thanks Ian.
