### ISSUE TITLE
Legend in full screen tweaks

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#558]
A couple tweaks to make to the legend in full screen mode (from the map pages, not in map editor mode).
- Start with the legend displayed in full screen mode. So whenever anyone goes to full screen mode have it turned on, on the right.
- Give some way for users to easily 'close' the legend. Right now it's not open, so users click the 'legend' button to open it, and then naturally hit it again to close it. If it starts open they won't know that some random button closes it. So would be good to put some sort of 'close' action, I guess one of those 'x' things on the window makes the most sense. Bonus points if you can get a little animation on close going to the legend button, to hint to people how to open it again.
- There's a bug when switching between small screen and full screen on the map page. If you expand the legend on the small screen and then expand out the legend stays in the middle of the page, instead of going to the right, out of the way.

**Comment by cholmes** [comment]
Checked on dev, and the last tweak seems to be working well. Don't see the other two working yet though. I can break up in to separate issues if you'd like.

**Comment by iwillig** [comment]
Hey Chris, this PR addresses the last issue. 

https://github.com/opengeo/geonode/pull/18

Lets chat about the second issue because I fear fixing might be more work then its worth.

**Comment by cholmes** [comment]
Hey, trying it out with everything working I'm ok to not do the second issue. The legend doesn't take up a ton of space, and the fact that it's icon is the only orange icon I think gives enough of a hint to users. So yeah, if it's easy then go for it, but if it seems like a bitch it's not important to me. Great work on this Ivan. Marking for deployment.

**Comment by iwillig** [comment]
Would you like me to make the second issue into its own ticket so we can revisit at a later point?

**Comment by cholmes** [comment]
Naw, just let it go. If client or users complain then we'll add it. We've got bigger fish to fry though. Marked ready for deploy.

**Comment by iwillig** [comment]
Should we close this issue?

**Comment by iwillig** [comment]
Also I think that we can close this ticket.

**Comment by cholmes** [comment]
Yup, good work. All working on production.
