### ISSUE TITLE
Icon consolidation in map editor

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#559]
So right now on the map editor page we have two rows of icons to do actions. The normal gxp ones along the top, and some time ones on the bottom. We can get rid of a number of the ones at the top. And then we should move the remaining ones to the bottom icon bar.

I think the ones we need are 'map properties', 'save map', 'get feature info', 'notes' and 'edit'. 

Edit we can probably do as a drop down for create and modify, like in http://suite.opengeo.org/geoexplorer/composer/

We'll try to get someone to design some nicer and more integrate icons. But start with just using the same icons up top, or just use text (info, save, edit, etc)

**Comment by iwillig** [comment]
Hey Chris, 

Are you think that we should move the icons from the top bar to the playback bar? And do you think we should drop the top tool bar completely?

**Comment by cholmes** [comment]
Yes and yes. That's what Tucker wants, all the relevant icons from the top moved to the playback, and then drop the top bar completely.

**Comment by cholmes** [comment]
@bartvde - could you add review of this to the top of your queue?

**Comment by bartvde** [comment]
will do @cholmes

**Comment by bartvde** [comment]
I actually reviewed this before already @cholmes 

@iwillig what's the status of the rework of my review?

**Comment by iwillig** [comment]
The biggest concern that we both had was the duplication of code in the mapstory tool bar compared to geo explorer.  I am of two minds about this. On one hand I think by combining these two similar widgets makes the application. It also seems like gxp has a long life span ahead of it. So maybe this duplication is okay. 

What do you think bart?

**Comment by iwillig** [comment]
@bartvde ^

**Comment by bartvde** [comment]
is this IRC ;-) ?

**Comment by bartvde** [comment]
yeah maybe just go ahead and merge @iwillig

**Comment by iwillig** [comment]
:)

**Comment by cholmes** [comment]
confirmed on prod
