### ISSUE TITLE
404's with trailing / on org pages.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#560]
Similar to #526 - http://mapstory.dev.opengeo.org/mapstory-foundation/ gets a nasty 404.

**Comment by cholmes** [comment]
Is this deployed? I'm still getting a 404 at http://mapstory.dev.opengeo.org/mapstory-foundation/

**Comment by ischneider** [comment]
D'oh. Branch confusion. Deployed correctly.

**Comment by cholmes** [comment]
Perfect.
