### ISSUE TITLE
hitcount tracking broken

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#564]
The original code counts a 'hit' as 3 ticks in the playback bar. This is broken for all maps/layers due to some change but also does not consider layers with 2 or less ticks (like a single timestamped raster from the warper)

as an intermediate step, enabling hit count on a successful map load will suffice

**Comment by cholmes** [comment]
Looks good. Thanks for the fix. Confirmed on prod. Takes a little while to increase the 'view', but I assume that's some caching going on.
