### ISSUE TITLE
Add "Search" button to search tools

### ISSUE THREAD

**Issue by bmmpxf** [MapStory/mapstory-meta#565]
Type in a word or phrase in the search box and then click...nothing? There’s nothing to click. (The spyglass isn’t a link, even though I expected it to be.) In order to perform a search, the user needs to press enter. Keyboard shortcuts are great, but it seems like an oversight to not have a box called “Search”. It's not like we're expecting users to navigate this site without a mouse.

Note that this is the case in both the Quick Search box and the main search box.

![quicksearch](https://f.cloud.github.com/assets/506694/229604/1719ffc0-86a4-11e2-9b5a-98e232706c9a.png)

![mainsearch](https://f.cloud.github.com/assets/506694/229605/1b5f69ee-86a4-11e2-88ed-4690dea6edba.png)

**Comment by cholmes** [comment]
Looking on the web (twitter, change.org, meetup) one does the same for their quick search. 

I'd say easiest thing to do here is just make it so clicking on the magnifying glass sends off a search.

**Comment by ischneider** [comment]
Closing - based on old skin
