### ISSUE TITLE
Add 'donate' button to sign-up page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#567]
Add the 'donate' button located on http://mapstory.org/mapstory/donate to the 'sign up' page

**Comment by cholmes** [comment]
Hey Jeff, I figure you'll the sign up page some with the social login stuff.

**Comment by jj0hns0n** [comment]
@cholmes got it, no prob.

**Comment by jj0hns0n** [comment]
https://github.com/opengeo/mapstory/pull/600

**Comment by cholmes** [comment]
Moving this to 'early spring' milestone, as it looks like it's done. But it looks like registration on mapstory dev server is closed right now, so I can't see it.

**Comment by ischneider** [comment]
I disabled registration while we have the 1st level auth wall down (for testing social stuff)

**Comment by cholmes** [comment]
Donate button looks good, marked ready for deploy.

**Comment by cholmes** [comment]
Verified on prod
