### ISSUE TITLE
Build out account activation email

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#568]
**Specs**
- Text is in comments below.  Note the plain text version has some slight differences.
- E-mail details:
  - From: `MapStory <hello@mapstory.org>`
  - To: `{{first name}} {{last name}} <{{user email}}>`
  - Subject: "Welcome to the MapStory community, `{{first name}}`!"
- HTML e-mail: target width is 600px, but it should still work and be viewable at widths smaller and larger than that.
- Should work in the following e-mail clients at a minimum: Gmail, Hotmail, Yahoo! Mail, Outlook, Apple Mail (app on OS X), iCloud.com.  Check in mobile phones/tablets (iOS and Android) as well.
- Messages should be multipart MIME so that plain text e-mail clients can fall back to the plain text version.
- Text
  - Font: Arial, Helvetica, sans-serif
  - Header and link color: #f46817 (also same color for orange bar at top)
  - Header: 22px bold.
  - Subheaders: 18px, font weight normal.
  - Text: #4e4e4e, 14px, line height 20px.  8px space between paragraphs.
  - Note: in paragraph under "Share What You Know", the words "add", "build", and "curate" should be bold (per mockup) in the HTML version.
- Background color: #f2f2f2
- May find this helpful: [Campaign Monitor Guide to CSS Support in E-mail Clients](http://www.campaignmonitor.com/css/)

**Logo image**
![568-logo-v2](https://f.cloud.github.com/assets/2131145/1009702/0823b178-0b3d-11e3-867d-abdbbf25632f.gif)

**Mockup**
![568-welcome-email](https://f.cloud.github.com/assets/2131145/1009681/973f00ca-0b3c-11e3-8587-b7e21d9d6599.png)

---

Were missing an opportunity to engage users with our activation email. this should have more directions, how-to information, embedded welcome video. If this isn't possible, we need to create an automatic 'welcome' email that arrives in a new users inbox at some interval after they activate...like 24 hours.

**Comment by cholmes** [comment]
I don't believe any of this should be too hard technically. @jj0hns0n you have thoughts? Could we do embedded video in the sign up email? @jonpmarino - could you do a draft of the text and info to send out?

**Comment by jj0hns0n** [comment]
I will take this one on. Sounds like we just need an HTML mail and that we want to be able to embed video links. That shouldnt be difficult, but I will look into it.

**Comment by jonpmarino** [comment]
Cool! Right now I'm imagining something like I just forwarded you, Jeff...from UserVoice. It could either come in the text of the 'activate your account' email, or (probably more ideal) as an automatic follow up 'welcome' email sent to account holder's email. I will draft text.

**Comment by jj0hns0n** [comment]
@cholmes whats the priority on this one? Put it in "Early Spring Improvements" ?

**Comment by cholmes** [comment]
Put it in social and tweaks just now. Would be good to get soon.

**Comment by jonpmarino** [comment]
Jeff, working on this now (4/8) and will get to you on 4/9. sorry for delay!

**Comment by cholmes** [comment]
@jonpmarino - can you put the desired email up somewhere, and link to it from here? Like dropbox or whatever.

**Comment by jonpmarino** [comment]
sure. doing it now.

**Comment by jonpmarino** [comment]
https://www.dropbox.com/s/0agw20c3ubgeb2x/MapStory%20welcome%20email.docx. Feel free to take a final cut yourself...also there are a few places where hyperlinks to referenced content would be helpful!

**Comment by cholmes** [comment]
Hey @iwillig , could you look in to this? Maybe @ischneider has some insight. If it's a pain we can push it off, since Jeff is MIA, but would be good to get in soon.

**Comment by ischneider** [comment]
This is probably easiest to implement via polling the User model daily and checking if the registration date was within the 'send' period. The alternative would be to hook into signals for User's but we don't have a high-quality delayed email queue solution.

Django _does_ support this:
https://docs.djangoproject.com/en/dev/topics/email/#sending-alternative-content-types

**Comment by cholmes** [comment]
@jonpmarino - do you imagine this going out as the activation email? Or sent just after they confirm?

If it should go out as an activation email could you put in where exactly they 'confirm'? Right now we have:

chris, activate your account on MapStory:

http://mapstory.org/account/confirm_email/ec24b8af117c907ddc6fd78d4d5a9e664524b852b1f2db2994907e68bed06d43/

So we need to make sure they click on that link to get registered.

@ischneider - if it's part of the account activation email do we need the polling?

**Comment by jonpmarino** [comment]
It would be money if it came after they activated...like auto 24 hours or something. Not sure if that's possible. 

I like the short quick activation followed by a longer welcome note later.

**Comment by cholmes** [comment]
Cool, that works. And actually will work better with social login stuff
where we don't make people confirm.

**Comment by emloux** [comment]
@jonpmarino It's been a while, do you want to make any updates/improvements to this?

**Comment by jonpmarino** [comment]
Send you shortly.

On Tue, Jul 2, 2013 at 4:42 PM, emloux notifications@github.com wrote:

> @jonpmarino https://github.com/jonpmarino It's been a while, do you
> want to make any updates/improvements to this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MapStory/mapstory/issues/568#issuecomment-20374604
> .

## 

Jonathan Parnell Marino

@jonpmarino
www.mapstory.org
(815) 222 9088

**Comment by drwelby** [comment]
@jonpmarino Do you have a preferred logo for the email? Actually, is there a repository of all the logos and other graphic assets?

**Comment by jonpmarino** [comment]
@sshyu could use your design savvy here, working with @drwelby.  Below is updated text for welcome email as well as a mock-up design. Its based on an example from Peers.org I just sent you. I'm imagining a background map image with white text box on top and the content below...

UPDATED TEXT:

Welcome to the MapStory community!

Hi, `{{first name}}`!

By creating an account, you've joined a community of global citizens working together to organize data and tell stories about how our world has changed, is changing, and might change over time. We come from different places and have different interests, but we are connected by our belief that knowledge is meant to be shared and can always be improved!

Here's how you can get started: 

Learn

MapStorytelling involves using open data, maps and your own reflection to illuminate change in place over time. Its something anyone can learn, and your peers are adding more resources all the time to help you along.

Learn the [basics](http://wiki.mapstory.org/index.php?title=How_To).

Share What You Know

There's three ways to share on MapStory. Just remember A, B, C. First, you can **add** new spatially and temporally enabled datasets, which we call StoryLayers. Second, you can **build** MapStories using StoryLayers and other narrative elements that you would like. Finally, you can **curate** content that appears on MapStory to improve its quality and accuracy.

Start [sharing on MapStory](http://mapstory.org).

Build the Community

MapStory is a nonprofit open educational resource. We rely on users like you to launch new initiatives, develop new tools and raise funds to keep the project going. So, get involved and build the future of MapStory that you want to see!

Get involved with the [community](wiki.mapstory.org).

Thanks for joining us, and happy MapStorytelling!
The MapStory Team

---

DESIGN CONCEPT - solid orange border, logo at the top, social media buttons placed somewhere:

![introemaildesign](https://f.cloud.github.com/assets/2573761/1003453/f0c521a6-0a8d-11e3-85b1-311cd708d1e3.jpg)

**Comment by sshyu** [comment]
Plain text version:

```
Welcome to the MapStory community!

Hi, {{first name}}!

By creating an account, you've joined a community of global citizens working together to organize data and tell stories about how our world has changed, is changing, and might change over time. We come from different places and have different interests, but we are connected by our belief that knowledge is meant to be shared and can always be improved!

Here's how you can get started:

Learn

MapStorytelling involves using open data, maps and your own reflection to illuminate change in place over time. It's something anyone can learn, and your peers are adding more resources all the time to help you along.

Learn the basics:
http://wiki.mapstory.org/index.php?title=How_To

------------------

Share What You Know 

There's three ways to share on MapStory. Just remember A, B, C. First, you can add new spatially and temporally enabled datasets, which we call StoryLayers. Second, you can build MapStories using StoryLayers and other narrative elements that you would like. Finally, you can curate content that appears on MapStory to improve its quality and accuracy.

Start sharing on MapStory:
http://mapstory.org/

------------------

Build the Community

MapStory is a nonprofit open educational resource. We rely on users like you to launch new initiatives, develop new tools and raise funds to keep the project going. So, get involved and build the future of MapStory that you want to see!

Get involved with the community:
http://wiki.mapstory.org

------------------


Thanks for joining us, and happy MapStorytelling!
The MapStory Team

```

**Comment by drwelby** [comment]
The emails are run through the template engine so we have access to the user account details, in case you want to greet the user by name. They'll also use the link management in #888.

**Comment by sshyu** [comment]
@emloux, @drwelby - this is now ready for development.  Ticket has been updated with specs and details.  

Let me know if you have any questions!  I'm discussing testing options with Jon--I think there may be services out there we can use to simulate the e-mail in different clients (given the e-mail's code), but need to do some more research.

**Comment by drwelby** [comment]
@jonpmarino  I have the text updated, can you send me access to the graphic assets? My email address is in my GitHub profile.

**Comment by sshyu** [comment]
@drwelby, the gif for the logo is attached/embedded in the main ticket.  The rest would ideally be done with CSS, though if you need images, please let me know.

**Comment by jonpmarino** [comment]
Lets make the from email account hello@mapstory.org. We've created that account for this purpose.

**Comment by ischneider** [comment]
This has been deployed to dev. There might be an issue with the computation of who to send this to - the idea was anyone who registered in the past day but I just got one :)

For the HTML email, it looks like we need the absolute URL - I'll do this part.

I'll look at the sender email, too.

**Comment by jonpmarino** [comment]
@ischneider @sshyu @drwelby so we think this went out to everyone registered on Dev, then? Not production?

**Comment by jonpmarino** [comment]
@sshyu lets make sure the most up-to-date text is what is used as well.

**Comment by ischneider** [comment]
@jonpmarino It seems like everyone on dev (not production) received a copy. There was a small content mix up so this is fixed and the sender is adjusted as well. I also changed dev to use the mapstory email account (we were just using an opengeo gmail account dating back some time).

**Comment by jonpmarino** [comment]
@ischneider all good!

**Comment by ischneider** [comment]
Looks like gmail does not honor anything in the head - this includes the style element. I've pushed a commit to contend w/ formatting in gmail. This also works fine in Thunderbird and Yahoo from my testing. If anyone uses outlook or other clients, let me know and I can fire off tests.

Dealing w/ HTML email is _not_ trivial w/ respect to client compatibility it seems.

**Comment by sshyu** [comment]
@ischneider, @drwelby: HTML emails are definitely a challenge.  You may find this guide helpful--it tells you what CSS is supported by which clients.
http://www.campaignmonitor.com/css/

For testing, it may be worth looking into MailChimp's inbox inspector--it looks like it'll run your email against a large number of clients for you to look at.  Not sure what the pricing is though.

http://kb.mailchimp.com/article/how-do-i-use-the-inbox-inspector#email-clients

**Comment by jonpmarino** [comment]
@ischneider @drwelby @sshyu, we can move with what Ian set me today (plus fixes he and I discussed) that at least has logo and links if this is going to be too big of a lift for now. Don't want to get too bogged down in this. Just wanted something up. Core issues on platform itself are certainly higher priority.

**Comment by ischneider** [comment]
Thanks @sshyu, I saw the CSS site you noted. The biggest problem it seems was using a style element. I inlined most styles (a:visited of course is not possible so whatever the user agent style is, you'll get that) and added some explicit margins for paragraphs.
@jonpmarino you should have just received a bunch of emails :) Let me know how they look.

**Comment by drwelby** [comment]
Strange thing - that html email template _is_ from Mailchimp.
https://github.com/mailchimp/Email-Blueprints

**Comment by drwelby** [comment]
I guess it would help if they were more explicit that they preprocess their
templates to inline all the CSS. Sheesh.

**Comment by sshyu** [comment]
Thanks @ischneider and @drwelby.  The email is looking great from the sample Jon sent me.  Just a couple small tweaks that I see offhand:
- subheaders should be 18px, _not_ bold.  They should also have 30px space above them and 5px below (between the subheader and paragraph).
- extra line break below "Get involved with the community" (at the end of the email).

**Comment by ischneider** [comment]
One last update to cover @sshyu recent comments and @jonpmarino request for an ! in the subject - ready for testing again.

@drwelby FWIW, if we do more along these lines, let's take a look at https://github.com/davidjamesmoss/django-inline-css-tag for inlining css

**Comment by emloux** [comment]
Marking Ready for Deploy
