### ISSUE TITLE
Hyperlink MapStory Foundation on homepage footer to Wiki about

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#570]
Where it says MapStory Foundation at the botton of the homepage, link this to http://wiki.mapstory.org/index.php?title=The_MapStory_Foundation.

**Comment by cholmes** [comment]
Could you knock this out Jeff?

**Comment by jj0hns0n** [comment]
@cholmes yup, no prob.

**Comment by jj0hns0n** [comment]
https://github.com/opengeo/mapstory/pull/595

**Comment by cholmes** [comment]
Looks good.

**Comment by cholmes** [comment]
Though reopening, as it's not deployed to production yet. Marked as 'ready to deploy'.

**Comment by cholmes** [comment]
Verified on prod
