### ISSUE TITLE
Label updates revert and don't save

### ISSUE THREAD

**Issue by nittyjee** [MapStory/mapstory-meta#572]
*When I change things in styling, I often have to do it again and again for it to save. I change the opacity or the labeling feature, click "save", and I go back, and it's back to where it was. I have to do it over and over and it's hit or miss really.
*Even when I do add labels and get everything right and it's saved and not reverting, it's hit or miss whether it shows up on the mapstory.

Happened with the following:
http://mapstory.org/maps/531/view
http://mapstory.org/maps/532/view

**Comment by ischneider** [comment]
Closing - will be using new platform
