### ISSUE TITLE
Changing order of storylayers changes start time for whole mapstory

### ISSUE THREAD

**Issue by nittyjee** [MapStory/mapstory-meta#573]
*When I change the order of storylayers, with one ranging 1629-2000 and the other ranging 1783-2000, it changes when the whole mapstory starts. This was unfortunate, because I got the labels working, and they show up nicely when I have the shorter storylayer on top of the longer one (otherwise the features of the longer one overlap on top of the labels). When they are underneath, it's really distracting, and I had to remove them all.
- in the end, I made two mapstories - I took advantage of it, because it would be good to have a mapstory of just 1783-2000. Of course, it's still an error, and I would prefer it not be there.
- however, again, the labels are not showing up (see: https://github.com/opengeo/mapstory/issues/572)

Happened with the following:
http://mapstory.org/maps/531/view
http://mapstory.org/maps/532/view

**Comment by ischneider** [comment]
closing due to rewrite
