### ISSUE TITLE
Storylayer uploads fine, but shows error

### ISSUE THREAD

**Issue by nittyjee** [MapStory/mapstory-meta#574]
*Luckily I was able to at least upload everything okay. But for the states/territories storylayer I got an error at the end that said "There is already a layer with the name geonode_xxx", with "xxx" being the name of the file. I searched for and found my storylayer and it turned out that everything was fine, and it was uploaded, but I certainly didn't do it twice. I have some intuition from similar errors before, but someone else would just think that it didn't work at the very last second (and both layers took 1-2 hrs to upload and ingest).

Happened with the following storylayer
http://mapstory.org/data/geonode:US_HistStateTerr

**Comment by ischneider** [comment]
Closing - old
