### ISSUE TITLE
Getting "500 internal service error" on MapStories this morning...

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#578]

**Comment by iwillig** [comment]
Hey jonpmarino, 

Can you check to see if you are still getting these errors. Often this type of issue will be resolved by Ian or our system admin. 

Thanks.

**Comment by jonpmarino** [comment]
Looks like its good to go now!

On Sun, Mar 17, 2013 at 11:41 AM, Ivan Willig notifications@github.comwrote:

> Hey jonpmarino,
> 
> Can you check to see if you are still getting these errors. Often this
> type of issue will be resolved by Ian or our system admin.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/opengeo/mapstory/issues/578#issuecomment-15024698
> .

## 

Jonathan Parnell Marino

@jonpmarino
www.mapstory.org
(815) 222 9088

**Comment by ischneider** [comment]
As interest and load continue to grow, the frequency of errors will unfortunately, too. Closing for now.
