### ISSUE TITLE
GEOSERVER_BASE_URL used for internal communications

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#579]
See https://github.com/GeoNode/geonode/issues/809

**Comment by ischneider** [comment]
I put this on dev and from my minimal testing, it seems to work well so far.
I created a new map from a layer, added an annotation (failed due to monitor bbox bug, another story), did some styling, etc.

**Comment by cholmes** [comment]
Closing this, as I assume it got deployed to prod.

**Comment by ischneider** [comment]
It hasn't yet but I'd say it's ready for production after being tested for almost 2 months :)

I'll pull it in now.
