### ISSUE TITLE
bulk annotation upload/download service via CSV

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#580]
Need to be able to upload annotations (text, video, images) in bulk by CSV.

**Comment by ischneider** [comment]
Service implemented and deployed to dev. Awaiting GUI in #874 to test.

Example of download: http://mapstory.dev.opengeo.org/maps/208/annotations?csv
Ensure your spreadsheet viewer uses only commas for separator chars when importing.
