### ISSUE TITLE
screen relative annotations layout issue

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#581]
see here, first few time steps:
http://mapstory.org/maps/475

![Workspace 1_018](https://f.cloud.github.com/assets/794512/256501/8bcef2a8-8c2b-11e2-8197-673bea8b21da.png)

**Comment by bartvde** [comment]
@ischneider is this map on dev as well by any chance?

**Comment by bartvde** [comment]
@ischneider I don't have the issue in Safari on OSX, any specific browser?

**Comment by ischneider** [comment]
It was on firefox (most likely) but I cannot reproduce so closing.
