### ISSUE TITLE
Add networks on user pages

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#582]
On both org and user pages we should have functionality to add social network type links. Meetup does a nice job of this, see:

![Your Meetup Group profile - MapStorytelling Alexandria VA - Meetup](https://f.cloud.github.com/assets/407017/259108/52cee41a-8cb5-11e2-88a3-96f5914afbe7.png)

**Comment by ischneider** [comment]
We have the concept of Link already attached to the extended Contact profile model. It would probably be easiest implemented by sniffing the link URL to resolve the appropriate icon like is done for videos in the vanity-pages work present on integration

https://github.com/opengeo/mapstory/blob/integration/models.py#L212

**Comment by cholmes** [comment]
Ah, that could be cool, great idea.

**Comment by jj0hns0n** [comment]
This should just work with https://github.com/opengeo/mapstory/commit/6bf9474f645512bf619687402aa5a15114caf085

**Comment by ischneider** [comment]
Still requires a user interface for managing links. Handling this.

**Comment by jj0hns0n** [comment]
Should be handled in the current UI right? Just add a link that matches the
regex and it displays with the right logo. What else are we missing?

**Comment by ischneider** [comment]
The current UI is on the vanity-pages branch and only works for orgs

**Comment by jj0hns0n** [comment]
Ah, yeah, I see what you are saying. Lemme know if you need help with that,
its still on my list here

**Comment by jj0hns0n** [comment]
@ischneider you plan to take care of implementing this since you reassigned the issue?
