### ISSUE TITLE
Icon is wrong with #full

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#584]
When you go to http://mapstory.dev.opengeo.org/maps/110/#full the first icon is the 'expand', which doesn't make much sense as you're already in the expanded out mode. It should be the collapse icon.

![Google Chrome](https://f.cloud.github.com/assets/407017/271069/8a8ddbf8-8fdb-11e2-9d74-5a98ba9ce14d.png)

**Comment by iwillig** [comment]
Yes, I am aware of this issue. The fix is not as easy as it looks. Working on that today.

**Comment by iwillig** [comment]
Fixed in https://github.com/opengeo/geonode/pull/18

**Comment by cholmes** [comment]
Perfect.

**Comment by iwillig** [comment]
Hey Chris, 

Ready for testing.

**Comment by cholmes** [comment]
Cool. I had thought I already put this one as 'ready to deploy'. But looks great, and just put the label on.

**Comment by iwillig** [comment]
Fixed on production.
