### ISSUE TITLE
Timeline on full screen maps on map page is gone.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#585]
I think the new changes left out the timeline that expands out with all the annotations. The one with the weird little button that takes up the bottom of the screen (which should get better soon with #556 ). It should be minimized on maps that don't have annotations, and maximized on maps that do (like http://mapstory.dev.opengeo.org/maps/117/#full ). This I believe was already implemented with #458 so should be a matter of just getting the timeline back.

**Comment by iwillig** [comment]
Oh yeah, You are correct. 

Will add that back today.

**Comment by iwillig** [comment]
I noticed another issue where the old code rendered the edit button in the Playback tool bar. Do we still want to have the edit tool bar?

I can add back.

**Comment by cholmes** [comment]
Ah, nice catch. Yeah, please, with your #586 fix, he edit button is the
only way in to the editor. So definitely important to be there.

**Comment by iwillig** [comment]
Addressed in PR 
https://github.com/opengeo/geonode/pull/20

**Comment by iwillig** [comment]
I think this is fixed on dev, are we able to close this ticket?

**Comment by iwillig** [comment]
I think that this is fixed but will wait to close it until chris confirms.

**Comment by cholmes** [comment]
Yup, working on production.
