### ISSUE TITLE
View this mapstory full screen should link to new #full page

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#586]
On the map page the link to 'view this mapstory full screen' should go to http://mapstory.dev.opengeo.org/maps/117/#full instead of http://mapstory.dev.opengeo.org/maps/117/view.

@iwillig if you can knock this out that's great, it's the final piece for #555 But I realize it's a bit more in django land, so feel free to reassign to @jj0hns0n if it's easier for him to do.

**Comment by iwillig** [comment]
Oh, I have already fixed this, but just did not push it as it just be easier to wait until the pull request is merged into geonode:mapstory.

**Comment by iwillig** [comment]
Fix in this commit https://github.com/opengeo/mapstory/commit/906469f683a784f196fff1815ef5d44c203896b5

**Comment by cholmes** [comment]
Oh cool, that's great. Slap on ready for testing label when it's up on dev, I just tried and don't think I saw it (though my internet is weird atm).

**Comment by iwillig** [comment]
Pushed to master, but since Bart is doing work on dev this morning I am going to hold off on updating the server for a while.

https://github.com/opengeo/mapstory/commit/906469f683a784f196fff1815ef5d44c203896b5

**Comment by iwillig** [comment]
Hey Chris, 

This is ready for testing.

**Comment by cholmes** [comment]
Oh yeah, I had saw it was working, forgot to update this issue. Thanks!

**Comment by iwillig** [comment]
Should we close this?

**Comment by iwillig** [comment]
Closing as I believe this is on the production machine.
