### ISSUE TITLE
remove progress bar when zoom in / out or skip ahead

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#587]
Could we do one thing to set their expectations a bit more though? If they zoom in or skip ahead where the progress bar has gone then just remove the progress bar? So they have the expectation that pre buffering is no longer working? I _think_ that'd be better than the way it works now, where you're not sure if it half loaded or something.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/e4ebfd2adff6a873eb9eba49979424f31ae7d2a7 this is only for the zoom action though

**Comment by bartvde** [comment]
on click we now just cancel pre buffering see: https://github.com/opengeo/geonode/commit/f59f75edddfec8e2708f6e4a89b6cec2df5617a0

**Comment by bartvde** [comment]
this is now ready for testing on dev @cholmes 

so if you zoom in or out, or click in the time slider, prebuffering is cancelled and the progress bar is hidden

**Comment by cholmes** [comment]
Looks great. A couple little improvements that could be made (though if they're a pain let's just deploy where it's at now).

Shown on http://www.screenr.com/BQb7 - 
- clicking ahead of the loading bar gets rid of it, communicating to the user it's no longer loading, which is great. But if you drag ahead then it doesn't get rid of it. Actually the ideal would be to not let you drag ahead of where it's loaded. But could also just remove the loading bar if you release past where it is.
- When you zoom in while it's buffering it nicely gets rid of the loading bar. But if it's already totally loaded then the loading (loaded) bar stays there. Would be good to get rid of it on any zoom, to communicate to the user they're in an area where there is not prebuffering.

**Comment by bartvde** [comment]
okay pulled in some tweaks with: https://github.com/opengeo/geonode/commit/1ad15b02a133d53a9bb9eec555a937397f8f757c

Both issues are addressed, however when dragging I do not yet check if the drag goes outside of the prebuffered area, it just always cancels. Btw, the same restrictions applies to click. I think we can address this later and I'll ticket it in a separate ticket.

**Comment by cholmes** [comment]
Verified on rpd
