### ISSUE TITLE
Styler scroll bar weirdness

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#588]
In the 'label' section of the styler the scroll bars are off. You can even get two scroll bars going at the bottom. See 

![Viewer](https://f.cloud.github.com/assets/407017/276019/8a25be30-90a1-11e2-8d00-50781d75b492.png)

Basically if you expand the window width wise and then shrink it back you'll get the extra scroll bar. And the other scroll bar is always present, even if you expand out. So probably just some misalignment in the container.

**Comment by iwillig** [comment]
Yeah look into this and it seems like its something that the access theme broke. Will try to fix this week.

**Comment by ischneider** [comment]
Closing - based on old skin
