### ISSUE TITLE
tooltip text on long ones hangs too far

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#589]
Tooltips that are long hang off, with no background to even read against. And they go on too long, off the screen. Should figure out a better solution for giving long hints to people, or at least make things more readable.

![hanging text](https://f.cloud.github.com/assets/407017/249525/a78d7930-8b2f-11e2-9466-f290cb16dac8.png)

**Comment by ischneider** [comment]
Closing - will be using new platform
