### ISSUE TITLE
layer no worky

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#591]
http://mapstory.dev.opengeo.org/data/geonode:SlateGunDeaths

It works fine when added to a map.

On the layer page, I get a JS error:

TypeError: element is null
[Break On This Error]   

if (!element._eventCacheID) {

**Comment by ischneider** [comment]
Actually, the map:
http://mapstory.dev.opengeo.org/maps/265/

Also has a problem on it's info page:
RangeError: invalid date

return date.toISOString();

**Comment by bartvde** [comment]
ah have seen this error as well and have been discussing with @iwillig for me it sometimes just disappears. If I remove the tile manager, I did not get the issue. Needs further looking into, but could be very tricky.

**Comment by bartvde** [comment]
@cholmes putting this in the near future milestone please change it if you don't agree

**Comment by bartvde** [comment]
@ahocevar pointed out that the template is a bit weird, since it uses a ready listener to set the extent (very inefficient), and passed in center: [null, null] and zoom: null into the config.

We need to fix this up first.

**Comment by bartvde** [comment]
@ischneider the layer's maxExtent is nowhere in the model right, so this workaround seems necessary ?

**Comment by bartvde** [comment]
@ischneider wrt the range error on http://mapstory.dev.opengeo.org/maps/265/, I cannot reproduce, not even with prebuffer true. Can you still reproduce that one?

**Comment by bartvde** [comment]
but yikes what's up with the playback speed on: http://mapstory.dev.opengeo.org/maps/265/ ?

**Comment by bartvde** [comment]
@ischneider @cholmes what is the purpose of animation step = 1 ? Is this causing the playback to be so fast?

**Comment by bartvde** [comment]
see https://github.com/openlayers/openlayers/pull/920 by @ahocevar

**Comment by bartvde** [comment]
First issue was fixed @ischneider and deployed to dev
