### ISSUE TITLE
Admin control over prebuffering

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#592]
An admin should be able to turn on and off prebuffering on the site. This can be at a global level, for all layers. They should be able to set a number of frames to buffer. The number of frames should be total number of frames. So like if there are 5 layers and the admin sets the number of frames to 10 then the client would actually prebuffer 50 total frames. So the admin is really setting the number of 'steps' for the playback. The total number of scenes, not the number of individual layer frames.

Bart, assigning to you for now, but feel free to reassign when it gets to the server part. But I'm guessing there'd be a similar url thing to prebuffer=true/false for numframes=X that we could play with in the URL. And then figure out with Ian/Jeff how to implement it on the server side.

**Comment by bartvde** [comment]
@ischneider do you need anything else besides a url parameter? Something you can configure in the template?

**Comment by bartvde** [comment]
@cholmes what should the progress bar do in this case? Should it should go to a 100%? Or should it go to (configured max / real number of steps) \* 100?

**Comment by cholmes** [comment]
Well my ideal is my comment in #543  If we have that implemented then this one should definitely just go to configured max / real \* 100. Then when they hit play it continues going to 100.

Before that is implemented.... hmmm... I guess to the same?

**Comment by bartvde** [comment]
url param called maxframes pulled in with: https://github.com/opengeo/geonode/commit/d348594e1f0d9d5bd5382e3adad37be4ff7f9bad

**Comment by cholmes** [comment]
Tested on the url param and it works well. Taking the ready for testing label off and reassigning to @ischneider as the full ticket is to let the admin control it. Ian, if Jeff could handle this feel free to reassign.

**Comment by ischneider** [comment]
The URL is useful for testing as the one can provide the value. It is very annoying to make the server provide the value via the URL. Would it be possible to get the value from the template (as @bartvde asked earlier)?

**Comment by bartvde** [comment]
do you want to remove the url param or keep both, if so which one should override the other?

**Comment by ischneider** [comment]
I think it's fine to keep both. I'd say that the template generated one should override.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/6cad9c5876cbc4303cfe0e5be1a7a67dca3ef368 and https://github.com/opengeo/gxp/commit/6cad9c5876cbc4303cfe0e5be1a7a67dca3ef368 pulled in with https://github.com/opengeo/geonode/commit/149838f07424bf473aea33dac31ad113e9e2f8b3

**Comment by bartvde** [comment]
@ischneider an example of configuration in the template is (templates/maps/mapinfo.html):

```
    var config = Ext.apply({{config}}, {
        portalConfig : {
            renderTo: 'embedded_map'
        },
        prebuffer: true,
        maxframes: 10
    });
    app = new mapstory.Viewer(config);
```

I assume you can turn this into variables (I have no clue how this works)

**Comment by cholmes** [comment]
I'm taking this off 'ready for testing' until there's an admin control that I can edit and have things change.
