### ISSUE TITLE
hitting 'enter' on new search in map composer should run the search

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#593]
On the new search from  #499 one really good thing to have would be if the user hits 'enter' after putting in some text it should run the search. That's what I do every time, and then think for a second it's broken, until I try the 'search' button. We should make it so that hitting enter runs the search.

**Comment by ischneider** [comment]
hmm, added w/ opengeo/geonode@6ce453d8

**Comment by iwillig** [comment]
Should we close this?

**Comment by iwillig** [comment]
It looks like some thing broke in this search dialog. When you visit the map composer page now, the add layer dialog is not empty.

![broken-search-field](https://f.cloud.github.com/assets/38427/353185/6c8c602a-a07a-11e2-9825-fb997a330d6c.png)

Not sure what changed.

**Comment by ischneider** [comment]
The dialog is empty on purpose. The goal is to _not_ load all layers.

**Comment by iwillig** [comment]
Okay, but I think that we could show at least a limited number of layers. When I see this widget right now I think that the site is broken. 

Thoughts on how we can balance this?

**Comment by iwillig** [comment]
Also, this ticket seems like its been fixed. Should we go ahead and close it?

**Comment by ischneider** [comment]
Without display a listing, we should probably put a label/message up noting one must enter a search term.

Ticketed as #639

**Comment by iwillig** [comment]
Cool
