### ISSUE TITLE
prebuffer not working on full screen

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#594]
Just had Nitin do some testing and he pointed out that pre-buffer isn't working in full screen. Though this may just be because the prebuffer=true doesn't work with the full hash thing. It makes it as http://mapstory.dev.opengeo.org/maps/99/?prebuffer=true#full if you say prebuffer on the small one and then hit 'full'. And if you go to http://mapstory.dev.opengeo.org/maps/99/#full?prebuffer=true then it ignores the full and goes to the small map view.

**Comment by bartvde** [comment]
okay in full screen mode an OpenLayers event zoomend is triggered, causing prebuffer to stop

**Comment by bartvde** [comment]
Hmm if there are no annotations we'll get 2 zoomends in fullscreen without the user doing anything, if we have an annotation we'll get even 3.

**Comment by bartvde** [comment]
Btw, this url is wrong: http://mapstory.dev.opengeo.org/maps/99/#full?prebuffer=true 

prebuffer is a url param and not part of the hash. The hash check that @iwillig did was for the exact #full and not an indexOf, so this will not trigger fullscreen mode. We could relax the check to check for indexOf though.

But the other one should work.

**Comment by bartvde** [comment]
fixed with https://github.com/opengeo/geonode/commit/db78a3b7d35fc306ebb1f14e11b7db6246d19405 except for a corner case where the timeline opens up automatically, since this still causes a zoomend event and cancels prebuffer.

**Comment by bartvde** [comment]
https://github.com/opengeo/geonode/commit/3efe1a6afb9f1ac7532e9ca3fe2e88669fbc9f06 deals with the corner case as well

**Comment by cholmes** [comment]
Looks good. Marking ready for deploy. One small improvement would be to restart the buffering when you go to full screen from small screen. I can ticket that in it's own issue, curious if it'll be easy or not. Right now it works if you go straight to full screen, but if you are at small and click the button then it stops, I assume because it does some sort of zoom event.

**Comment by cholmes** [comment]
Confirmed on prod. Though there's a corner case that's not handled.
