### ISSUE TITLE
Resize images on media ribbon

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#597]
See http://mapstory.dev.opengeo.org/mapstory-foundation/ particularly Tucker and Marino's pictures. Instead of cutting things off if they are too long could we resize them to fit the proper length?

**Comment by cholmes** [comment]
Ok, the vertical ones look great now. But the opengeo one looks weird, and it was fine before:
![MapStory _ MapStory Foundation](https://f.cloud.github.com/assets/407017/294540/2ceb0336-93f5-11e2-9c61-46c387db84da.png)

Can we have it so it doesn't smoosh it? I believe it was ok before, so maybe don't resize on vertical? And/or scale it down all the way, don't smoosh it.

**Comment by jj0hns0n** [comment]
@ischneider Im a little confused as to what to do here without a bunch of client side work to figure out what the size is and scale it that way. We can do it that way, but we should chat about it first. I did try just disabling the max-width 100% in the debugger and I end up with this.
![MapStory _ Code for San Diego](https://f.cloud.github.com/assets/506078/325274/4c0ba498-9b05-11e2-8e46-c6b1d5eabed8.png)

**Comment by ischneider** [comment]
working on js fix for this

**Comment by cholmes** [comment]
This looks good on dev, marked as 'ready for deploy'
