### ISSUE TITLE
Minimize header on organization pages

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#598]
If it's not too difficult we should have less of a header on the organization pages. Inspiration is http://www.meetup.com/mapstory/

So just the mapstory logo and 'login', and get rid of all the other text and stuff.

**Comment by jj0hns0n** [comment]
Implemented in https://github.com/opengeo/mapstory/commit/7f29a1bc22c3709c14bd279b1d14d3ce57e02fe3

Moved the quick search bar to the left of the Donate link and gave the header a bit of extra padding so the register button still shows. Pulled to dev and marked ready-for-testing. @cholmes can you take a look.
![MapStory _ Code for San Diego-2](https://f.cloud.github.com/assets/506078/335521/d3f72e28-9c8f-11e2-8578-e36b875e1954.png)

**Comment by jj0hns0n** [comment]
Another screenshot from the dev server. Check it out here http://mapstory.dev.opengeo.org/mapstory-foundation/
![MapStory _ MapStory Foundation](https://f.cloud.github.com/assets/506078/335541/154d7a30-9c90-11e2-8fd1-77de293b4db9.png)

**Comment by cholmes** [comment]
Looks good.

**Comment by cholmes** [comment]
This went out, closing.
