### ISSUE TITLE
Tell users recommended banner size on org page

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#599]
When users hit 'edit' on the banner it should recommend they use a 960 px wide banner. In time we may want to try to enforce this a bit, but for now let's just make a recommendation.

**Comment by jj0hns0n** [comment]
Added in https://github.com/opengeo/mapstory/commit/6c31b4ad8914925e72a3cf23ae46288ffb1843fb ... This panel still needs a little UI/UX love though.

**Comment by cholmes** [comment]
Tested, looks good, ready for deployment.
