### ISSUE TITLE
Have 'read more' on org pages

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#601]
4)  Also to save screen real estate, perhaps we could limit the number of characters of text that are displayed by default, and have a "Read more..." that expands the text downward, and then minimize.  Same thing for the link list.  Is this possible?

---

I'd say make it based on number of 'lines'. Start with maybe 12 lines? And if they click read more it does some javascript to show the rest.

**Comment by jj0hns0n** [comment]
Initial commit of this here https://github.com/jj0hns0n/mapstory/commit/caba7c1764be1cd46773d2653a5412be112b98b7 ... basic customization in place. @cholmes we should look at this together on dev so we can tweak it to your liking

**Comment by cholmes** [comment]
@iwillig - can you take a look at this? Let's talk about it. There's something there, but it doesn't do line breaks properly.

**Comment by cholmes** [comment]
http://stackoverflow.com/questions/10591972/django-jquery-expander-plugin-not-working-with-linebreaks

**Comment by ischneider** [comment]
I saw the email in my client but missed that @iwillig had been assigned. Deployed a fix for this.

**Comment by cholmes** [comment]
Looks perfect. Thanks Ian.
