### ISSUE TITLE
Add 'network' links to organization pages

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#603]
See #582 

Be sure to do that for organization pages. I guess easiest may be the approach Ian recommends, to just sniff the links in the 'links & resources' section and generate nice icons from them. I'm also more than ok with having it filled out separately, it could be nice for users to know they put it in one place, and to have that a bit validated.

See like http://www.meetup.com/Geo-DC/members/13701646/

Would definitely be good to have it as a bit separated off. A 'networks' section that just has those links, have it at the top.

**Comment by jj0hns0n** [comment]
Initial work to add FB and Twitter here https://github.com/opengeo/mapstory/commit/6bf9474f645512bf619687402aa5a15114caf085 ... note that this currently does _not_ put them separated off, but in line in the ordering specified. @ischneider I cant immediately think of a good way to separate them off without making changes to the model. Let me know if you have any ideas. What other networks do we care about? Screenshot attached. 
![MapStory _ Code for San Diego-1](https://f.cloud.github.com/assets/506078/325518/af777b18-9b0c-11e2-9715-797fa829f4fb.png)

**Comment by cholmes** [comment]
This is too incomplete to consider done. They need to at least be separated out in the presentation, and ideally separated in the editor, explicit places where people can just put in their twitter id, their linkedin profile, facebook page, etc.

Meetup is the good example, display shown at http://www.meetup.com/Geo-DC/members/13701646/ and login and fill out the profile to see how to make it a nice area of its own.

**Comment by cholmes** [comment]
I think it's ok if the editing does not break them out in to separate things, as our link sniffing seems to be good. But I think we should put a line in the link editing area that says something like 'to fill out the 'networks' section of your page just enter a link to your presence on twitter, facebook, google+, linkedin or tumblr and it will show up.'

I think that is a good list.

And then for display just put it at the top of the 'links and resources' section, with icons stacked horizontally, and perhaps a line or something before the rest of the links.
