### ISSUE TITLE
Ability for user to login with facebook or google.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#607]
I don't think we actually have this as an issue. Will make other smaller issues referring to the one version I saw. Would be good to get that back on dev.

**Comment by jj0hns0n** [comment]
I considered this all together with https://github.com/opengeo/mapstory/issues/474

**Comment by cholmes** [comment]
Cool, can just refer the various issues to there then. Just want a record of what we do for milestone logs and the like.

**Comment by jj0hns0n** [comment]
Copying @cholmes workflow comments from #608 to here.

"They should all let users login with their account. All should work the same, even if they're on the register page and they've logged in before or vice versa. First time should create a user account. Second time should just login to that user account. And ideally if it's the same email as an existing account it should login to that account. (like if I sign up with cholmes@opengeo.org and login with my cholmes@opengeo.org google account I should login to the same mapstory account)."

**Comment by drwelby** [comment]
As a note, it's keyed to the login account's email. So if you have an exisitng MapStory account with a GMail address and you later use "Log In With Google" to sing in with that GMail address, you'll be logged in to your original account. If you're signing in for the first time using Google, a new account will be created.

**Comment by emloux** [comment]
Marking ready for deploy
