### ISSUE TITLE
All login/register pages should have option to sign in with google/fb

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#608]
First implementation just let users login at the 'login' popup. There's also  http://mapstory.dev.opengeo.org/accounts/login/ and http://mapstory.dev.opengeo.org/account/signup/

They should all let users login with their account. All should work the same, even if they're on the register page and they've logged in before or vice versa. First time should create a user account. Second time should just login to that user account. And ideally if it's the same email as an existing account it should login to that account. (like if I sign up with cholmes@opengeo.org and login with my cholmes@opengeo.org google account I should login to the same mapstory account).

**Comment by jj0hns0n** [comment]
https://github.com/opengeo/mapstory/pull/625

@cholmes lets take up workflow issues to #607 not sure what you are asking for is possible, but lets discuss there.

**Comment by cholmes** [comment]
Looks good.

**Comment by emloux** [comment]
Marking ready for deploy
