### ISSUE TITLE
Some download links for time-enabled layers are broken

### ISSUE THREAD

**Issue by mbertrand** [MapStory/mapstory-meta#61]
Download links for time-enabled layers don't work correctly for some formats: KML (empty data), GML3 (geoserver exception), zipped shapefiles (missing some time information).

GML 3.3.1 exception:
java.lang.RuntimeException: Failed to
      get property:
      {http://www.opengis.net/gml}featureMembers Failed to
      get property:
      {http://www.opengis.net/gml}featureMembers
      net.opengis.wfs20.impl.FeatureCollectionTypeImpl
      cannot be cast to net.opengis.wfs.FeatureCollectionType

**Comment by cholmes** [comment]
I'm going to close this, as gml 3.3.1 'works' now, or at least it doesn't give the runtime error. And zipped shapefiles work. KML still has problems, but I'll put it in its own issues.
