### ISSUE TITLE
Use properly branded google and fb login buttons

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#610]
In all places that we let people login with fb or google we should use their proper buttons, so it feels like a recognized thing to people.

I think the default for google is fine - https://developers.google.com/+/web/signin/#try_it And for facebook I found https://developers.facebook.com/docs/reference/plugins/login/ though that looks 'social'. Lots of sites seem to use a different one. Meetup actually does a nice 'login with facebook' on the login page and 'signup with facebook' on the sign up page. Both with properly branded buttons.

**Comment by jj0hns0n** [comment]
Used a standard set. You can see the images here https://github.com/opengeo/mapstory/pull/624/files

**Comment by cholmes** [comment]
Looks good.
