### ISSUE TITLE
Grab picture and full name for user profile if someone registers with fb or google

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#611]
If someone registers with fb or google we should automatically populate their user profile with their 'full name' and picture form fb or google, so they don't have to fill that out.

Would be great if we gave them the option (not required) to fill out their blurb, letting them know they won't show up in user search until they do.

**Comment by ischneider** [comment]
Implementation notes:

For the profile info, we of course have the User model but the profile model in use is actually mapstory.models.ContactDetail (for the other information)

As for the avatar, we could (pick one):
1) download the image and serve it ourselves through existing avatar
2) alter 'our' avatar fork and add a URL field
3) add a URL field to our profile model and a method that checks the field URL then avatar

**Comment by jj0hns0n** [comment]
Full Name and email are already grabbed and stored by the django-social-auth pipeline. If we need to do anything custom like grabbing other variables from their profile (tagline etc) we can do that.

Im going to go with 1) as a first pass here. Took me a while to find a good article on how to use the pipleline functionality in django-social-auth, but I got it now, just need to update the avatar retrieved.

@cholmes this same pipeline functionality lets us jump in the middle of the external login session and force them to provide their email or anything else in the process. Lets discuss what we want to do after I get the avatars taken care of.

**Comment by jj0hns0n** [comment]
Here is the article fwiw http://tryolabs.com/Blog/2012/02/13/get-user-data-using-django-social-auth/

**Comment by cholmes** [comment]
So this is grabbing the email and picture. But the user profile is not actually aware that those things have been grabbed. So the user is told to fill out their name and blurb. And when they go to edit their details the name and email are empty. We should be populating the spots the user can edit. So we seem to grab it, but not all the way to where the user can update it. 

Taking 'ready for testing' off, as this needs more work.

**Comment by cholmes** [comment]
Another note on this is that the thing that tells users that they need to fill out their profile should also be updated. May easily be the same thing as my above request, but want to be explicit. When a user logins in with facebook or google the only thing they should need to fill out is the 'blurb' and then they should be a fully searchable user.

**Comment by drwelby** [comment]
Seems to be working fine as of https://github.com/drwelby/mapstory/commit/33e82d8d51de490136a96df56e06b0a9cbf26d4f (not yet on dev)

We may need to make the part about filling the blurb out to be searchable to be more explicit, but maybe we move that to new issue?

**Comment by ischneider** [comment]
Is there a way to redirect the user to their profile page? It will show them that things are incomplete. It seems like the setting SOCIAL_AUTH_NEW_USER_REDIRECT_URL might work?

**Comment by drwelby** [comment]
Yeah, I think I can make that work - make a /profile url that grabs the user from the request and redirects to their profile page.

**Comment by ischneider** [comment]
Ah, right - we can't do a dynamic URL there. We could also do a 'welcome' page as somewhat mentioned in #646.

The account app that handles 'normal' registration has a place for this, too, it seems:
ACCOUNT_SIGNUP_REDIRECT_URL

**Comment by drwelby** [comment]
The redirect works fine, but now I think we can just redirect straight to /profiles/edit/ which handles the user anyway.

What's the language here? "Until your profile is complete you will not be a searchable user"?

**Comment by ischneider** [comment]
Nice to hear stuff works like it should ;) Forgot that profiles/edit deals with that.

It should show something on the form related to what fields are incomplete.

**Comment by jonpmarino** [comment]
With social log-in, will new users receive the 'welcome' email like we've talked about with #568?

**Comment by drwelby** [comment]
Yeah, if the welcome email is triggered by adding a new user (whether through signals or polling), then the user signing up with a social account will get an email.

The profile form does say what fields are incomplete, I'm just not 100% sure what the language is for the sentence that tells them why they should complete their profile. It seems to have something to do with being searchable.

**Comment by ischneider** [comment]
Agree with what @drwelby said and as noted in #568 - we can run a daily process that checks for registrations over 1 day in age but less than 2 and send an email to them. This is not implemented yet, but can be.

@drwelby, the template tag that renders the message is `profile_incomplete`. The template it uses is templates/mapstory/_profile_incomplete.html

We don't have any specific copy for this language. @jonpmarino ?

**Comment by jonpmarino** [comment]
@ischneider there is some draft copy in #568 for this. Can we do a test send to @ChristopherTucker and I and we'll do one quick edit scrub and finalize?

**Comment by emloux** [comment]
@drwelby @ischneider Did we send a test welcome email to Jon/Tucker yet?

**Comment by drwelby** [comment]
Here's a first draft of the text and email versions of the email. The html version still needs a logo, not sure which to use and where those assets are stored.

https://rawgithub.com/drwelby/mapstory/userwelcome/templates/mapstory/welcome_message.txt
https://rawgithub.com/drwelby/mapstory/userwelcome/templates/mapstory/welcome_message.html

If those look good the code is ready to deploy to dev, and someone will need to add the management command to cron.

**Comment by jonpmarino** [comment]
@drwelby thanks for moving on this. Exciting stuff! I have some updated text for this. Also, I'm wondering what ability we have to do rich html styling? Ideally I'd like to something like this - the blue boxes on the bottom are social media links (FB, Twitter). I need your email and I can add you to our design assets folder -

![abc12345](https://f.cloud.github.com/assets/2573761/941461/cfcbea48-0146-11e3-85d5-662ff7ad965b.jpg)

**Comment by emloux** [comment]
@drwelby sorry, scrumdo seems to have wiped out all our github labels.  Is this one ready for testing?

**Comment by drwelby** [comment]
yes

**Comment by emloux** [comment]
Looks good, ready for deploy
