### ISSUE TITLE
Display full name in upper right if available instead of user name.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#612]
With the new fb/goog login some of the generated user names can look a bit weird. Would be better if we just used people's full names if we have them. I'm thinking mostly in the upper right corner where we always say 'welcome <username>'. If there is no full name then obviously fall back on the username.

**Comment by cholmes** [comment]
Ian notes: Jeff, I have a template_tag (mapstory_tags.user_name) for this (show username only iff first and last don't exist) and we should add (or move) the same logic to the profile (ContactDetail model) object so we can access this all over.

**Comment by jj0hns0n** [comment]
Initial work submitted as #623 need to discuss a bit with @ischneider

**Comment by cholmes** [comment]
Looks good, ready to deploy.

**Comment by cholmes** [comment]
verified on prod.
