### ISSUE TITLE
Text box on org pages is too small

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#614]
Could we get this to be bigger? I tested on chrome and safari.

![MapStory _ MapStory Foundation-1](https://f.cloud.github.com/assets/407017/294551/066498ec-93f7-11e2-963f-0db548e881cf.png)

**Comment by jj0hns0n** [comment]
Changed it to be size 600x200 and fixed up a few things in the process. Will let @cholmes know when its ready for testing.

**Comment by cholmes** [comment]
Looks good on dev.
