### ISSUE TITLE
Org page edit links improvements

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#615]
A couple improvements to be done on the edit links page, off of organizations. See:

![Uploading MapStory _ MapStory Foundation-2.png . . .]()

First, could we change the name of 'edit' to 'update'? As the user is already in edit mode. Mentioned this in a comment on #462 but this ticket can just track it.

Second, the alignment on the values on the right is all weird. Could have more space so they don't keep indenting on one another?

**Comment by jj0hns0n** [comment]
@cholmes can you repost that graphic please.

**Comment by cholmes** [comment]
Trying again with the picture:

![MapStory _ MapStory Foundation-2](https://f.cloud.github.com/assets/407017/410237/c04d8aa6-ab68-11e2-91a9-6f2c2b8fdf85.png)

**Comment by cholmes** [comment]
@iwillig - can you take a look at this one?

**Comment by iwillig** [comment]
Yes of course.

**Comment by iwillig** [comment]
Whats the url for this page.

**Comment by cholmes** [comment]
http://mapstory.dev.opengeo.org/mapstory-foundation/links

Actually the weird indents look less bad than they used to. But still would
be good to improve. To get to the 'edit' button just select one of the
items. We could also name it 'save' if update is too long. I just think if
the button says 'edit' you'd think it takes you to edit mode. In this
you're already in edit mode, so I think it'd be 'save' or 'update'.

**Comment by adunetz** [comment]
Assigned to Chris and Ready for Testing.

**Comment by cholmes** [comment]
Not confirmed on dev. I guess it still needs to be pushed.

**Comment by cholmes** [comment]
I'm removing 'ready for testing' label until this actually appears on dev. Things should not be marked ready for testing unless they are actually deployed.

**Comment by cholmes** [comment]
@ischneider - can you try to dig up this commit and get it on dev to test? It's like one line, not sure where it went.

**Comment by ischneider** [comment]
was hanging out in vanity-pages branch and just not merged. deployed to dev

**Comment by cholmes** [comment]
Looks good on dev.
