### ISSUE TITLE
date/time tooltip display on time slider not always correct

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#616]
reported by @cholmes on the dev list:

And looks like our code does get the time span proper. Like http://mapstory.dev.opengeo.org/maps/151/ if you switch the playback mode displays month and year. So we have some code that works just right with the display, something just is wrong at first.

On Thu, Mar 21, 2013 at 6:33 PM, Chris Holmes cholmes@opengeo.org wrote:
So just realized that on a map playback if you just adjust the playback mode (any adjustment, even changing to one thing and then back), then it goes back to just using the year. See like http://www.screenr.com/Rcb7 

And I just tested on the small map and it worked the same. So yeah, more weirdness. But looks like we have somewhere in there the right thing.

On Thu, Mar 21, 2013 at 3:32 PM, Chris Holmes cholmes@opengeo.org wrote:
Something definitely changed.

See attached, and http://mapstory.org/maps/170

http://mapstory.org/maps/170 and http://mapstory.org/data/geonode:uscntypopcopy_Project also used to just have year. I have videos of both. I don't have any videos showing it without it working properly.

**Comment by cholmes** [comment]
Tucker asked about this in meeting 5/22, as one of very few issues. So it's important.

**Comment by bartvde** [comment]
Putting some more info from the e-mail thread in this ticket:

```
@bartvde: From the code I can see this depends on whether or not it's interval. If it's interval, it will guess a time format, otherwise it will use the predefined long format with hours, minutes, seconds.
Nothing has changed on this recently AFAICT.
```

```
@ischneider: This one is tricky but it embarrassed me the other day as I was
showing an anthropologist/geography professor from CU the post offices
map (which she thought was super cool)

At the moment, in `list` mode, geoserver returns full precision ISO
timestamps. In interval mode, it returns an interval (with the
appropriate resolution). So for the latter, the client can make some
calculation about precision. While we could work around it on the
client, a more appropriate fix would be to support specification of
the precision in geoserver and adjusting the caps doc - the spec
allows reduced precision ISO timestamps.

One reason we might still want to have support on the client is the
mixed use case - we have intervals and lists of varying resolutions.
```

```
@bartvde: For the client solution - would this be a setting in the playback toolbar's settings dialog or something else?
```

```
@ischneider: My thought would be in the general playback settings for a map/layer.
```

```
@cholmes: So just realized that on a map playback if you just adjust the playback mode (any adjustment, even changing to one thing and then back), then it goes back to just using the year. See like http://www.screenr.com/Rcb7 

And I just tested on the small map and it worked the same. So yeah, more weirdness. But looks like we have somewhere in there the right thing.
```

```
@ischneider: There are two (useful) approaches to advertising dimensions in
geoserver (chosen in the geoserver layer dimensions tab or in
mapstory, when the user uploads):
list and interval

List is often most useful for random events - earthquakes, etc.
Interval is for events that have been regularly collected - yearly
census data, daily temps, etc.

With list, the WMS caps doc dimension/extent response is all of the
specific timestamps (With full precision).
With interval, the WMS response is just a range specifier. I think
it's like start/end + interval

Not sure what the intention of use exact list values is but my guess
is that often it makes sense to view list data as an interval. For
example, if you have hundreds of random list events, playback might
take forever. In this case, I chose interval because that was the
resolution of the data - 1 day. With, the earthquake dataset I
uploaded, there are like 100,000 events randomly scattered across
time. By using a 1 day interval, playback is not only a bit more
exciting, it actually ends...

The layer/map has bugs related to recent changes. Interval playback
used to work well.

Interval is often the 'right' way to go depending upon your data.
There is also a very noticeable performance difference and user
experience difference for large datasets (instead of returning
hundreds of list values, a single start/end/interval is returned.)

Perhaps a useful feature is to allow a vendor parameter to allow
returning list values as interval. There might be a case for both and
this way, the client can decide.

Hopefully this clears some things up.
```

**Comment by bartvde** [comment]
so the question I have now is whether or not to do some automatic guess based on the values or to make this configurable (or both, ideally I think based on the value list below it can be guessed that this should be days resolution):

```
2003-01-01T00:00:00.000Z,2004-01-01T00:00:00.000Z,2005-01-01T00:00:00.000Z,2006-01-01T00:00:00.000Z,2007-01-01T00:00:00.000Z,2008-01-01T00:00:00.000Z,2009-01-01T00:00:00.000Z,2010-01-01T00:00:00.000Z
```

**Comment by bartvde** [comment]
But basically this data should be served with interval.

**Comment by bartvde** [comment]
Okay I have a client-side fix for this, but since it's hard to see the implications of this for all possible scenarios, it will need some real testing.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/52aa623aaf8b3a5cfa061aa87991639a5644805c btw this is only for the tooltip issue, not the actual playback issues here

pulled in with https://github.com/opengeo/geonode/commit/2c7fb27c1c5bcb590d035b50bc0dd36f8b0c2a3f

**Comment by bartvde** [comment]
The tooltip issue fix is ready for testing on dev, I'll start looking into the playback issue now

**Comment by bartvde** [comment]
Wrt playback, playback seems to stall for a while if an error is received from the server, it doesn't seem to have to do with aggressive mode.

**Comment by bartvde** [comment]
Hmm seems playback issues on my side were caused by memory issues in Chrome, restarting Chrome fixed the playback for me. Wondering if anyone else still sees playback issues on this map.

**Comment by cholmes** [comment]
Testing the tooltip, I tried ming dynasty and it worked great, so
definitely an improvement. Tested
http://mapstory.dev.opengeo.org/maps/135/http://mapstory.dev.opengeo.org/maps/135/#
and
it was less good, it still says 8:00pm on all the steps. Will test more.

**Comment by bartvde** [comment]
@cholmes the map you referenced does not look like equal interval data to me so that's probably why this code path is not matched. Maybe I should only check for equal units and not equal amount. That should be an easy fix.

```
"1962-01-01T00:00:00.000Z", "1965-01-01T00:00:00.000Z", "1969-01-01T00:00:00.000Z", "1970-01-01T00:00:00.000Z", "1971-01-01T00:00:00.000Z", "1972-01-01T00:00:00.000Z", "1976-01-01T00:00:00.000Z", "1977-01-01T00:00:00.000Z"
```

**Comment by bartvde** [comment]
see https://github.com/opengeo/gxp/commit/3b41af913ab6530c275afa8e3c229349010637b9 pulled in with https://github.com/opengeo/geonode/commit/ebb561381bfcf6fcdefb8fda974f9d5e8687d0b8

**Comment by bartvde** [comment]
no that's not it, it needs more looking into

**Comment by cholmes** [comment]
Tested another 10 layers. Most worked perfect.
http://mapstory.dev.opengeo.org/maps/156/ though errs the other way - all
values say 2009, while it is probably a day interval.

Irene did work well though, it displayed the hours, and the hours are
relevant.

**Comment by bartvde** [comment]
will look into the examples that you sent me, thanks for testing!

**Comment by cholmes** [comment]
No problem. Another similar one to the wildfire one is
http://mapstory.dev.opengeo.org/data/geonode:timestamp2

Though http://mapstory.dev.opengeo.org/data/geonode:Titanic_Path1 works, so
it could be a data error.

**Comment by bartvde** [comment]
Wrt map 135: the intervals are not similar, I had 6 months and 2.1 years e.g. in the first 3 values. So maybe I should only collect the lowest possible value instead of what I do now.

**Comment by bartvde** [comment]
okay this approach seems to work much better, will work on a patch based on this workflow

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/1c3a94a639d2b1e9866656aa87a40a663a9f339c for the new approach pulled in with https://github.com/opengeo/geonode/commit/dd035ef3119cd470f5edd6f03f9ed79a5ad9b6d8

**Comment by bartvde** [comment]
this is ready for testing again on dev @cholmes all the maps you pointed me at work okay AFAICT

**Comment by cholmes** [comment]
Did a bunch of testing. Seems to be working great, with one exception, which is http://mapstory.dev.opengeo.org/maps/265/

But that's it's own special issue ( #670 ), so I'm just going to mark this as ready for deploy.

@ischneider - if it's possible to deploy just this that could be a win, as it's high on Tucker's list. But if it's a pain can just wait till next release. I have tested 25 or so maps with it, I don't think it introduces any issues.

**Comment by bartvde** [comment]
right this is an interval map, so it doesn't follow this code path, will debug to find out more about it though

**Comment by bartvde** [comment]
The interval is one day (14T00:00:00.000Z/2013-03-18T00:00:00.000Z/P1D) however the code seems to forget about the unit, interval is just 1, no units, which means it will use seconds precision in this case. Will need to find out more about the real cause.

**Comment by bartvde** [comment]
Okay I think I have fixed this one too with https://github.com/opengeo/gxp/commit/1708ffdc8610e7bc1d6b31b3839032cdb1ea8a55 pulled in with https://github.com/opengeo/geonode/commit/9b09fb4631590358dd39a022b9f7a07ae54acf1c also deployed on dev @cholmes

**Comment by ischneider** [comment]
[edited comment due to messy format]
The slate map looks good. Shall I push to production then @cholmes?

**Comment by cholmes** [comment]
Yeah, that'd be great Ian.

**Comment by ischneider** [comment]
@bartvde does this commit ( opengeo/geonode@25737879ab02e0e0ba14750a466e69774e0ecb22 ) represent what I needed to get from you?

I computed this from the most recent submodule commits that you made.

```
git log --oneline origin/mapstory-production..origin/mapstory -- src/geonode-client/
```

**Comment by bartvde** [comment]
@ischneider I get a 404 on that link

**Comment by ischneider** [comment]
@bartvde updated link - sorry about that

**Comment by bartvde** [comment]
@ischneider only the gxp update is the necessary for this one

**Comment by ischneider** [comment]
@bartvde I went ahead and deployed both - let me know if that's a problem

**Comment by cholmes** [comment]
Working on prod, so closing.
