### ISSUE TITLE
prebuffering should check for errors

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#618]
Not sure if it's possible and still need to investigate the cause but on dev the error log is filled with hundreds of huge stack traces starting with:

2013-03-22 19:34:47,051 ERROR [geoserver.ows] -
org.geoserver.platform.ServiceException: No such style: Poverty_8962862c

Ideally, we'd abort on errors.

**Comment by cholmes** [comment]
Makes sense. Since we're getting lots of problems with too many errors in our logs I'm putting this at high priority.

**Comment by bartvde** [comment]
So cancel prebuffering on error?

**Comment by cholmes** [comment]
Maybe on like 5 or 10 errors? Or how about if you get 10 tile errors in a row. Like it could just be one bad frame or something. Just want to prevent the case where there's tons of errors and it just keeps pounding.

**Comment by ischneider** [comment]
Agree, some metric like X in a row seems most appropriate.

**Comment by bartvde** [comment]
okay fix pulled in with https://github.com/opengeo/geonode/commit/2634266c7a2f7487362b1736fb9f95812986d099 I took X=5 for now.

**Comment by cholmes** [comment]
This is tough to test, will try to set it up so I can soon. But I think it's fine to deploy, it doesn't seem to mess up anything else.

**Comment by cholmes** [comment]
Didn't get to testing, but I think this is deployed, so closing.
