### ISSUE TITLE
Unable to add Annotations to mapstories

### ISSUE THREAD

**Issue by sravaniv** [MapStory/mapstory-meta#619]
Getting an error message when trying to add annotations to mapstories created. Attached is a screenshot of the error message.
![Annotations_Error](https://f.cloud.github.com/assets/2584276/299525/3e0f47d8-957d-11e2-93f2-1ba9e5f2b685.JPG)

**Comment by ischneider** [comment]
This appears related to the bbox feature of the monitor.

**Comment by sravaniv** [comment]
The error seems to have been fixed. Able to save the annotations but they are not being displayed when the story is played.

**Comment by ischneider** [comment]
Forgot to note that it should be possible now - thanks for replying with your success.

To enable the notes, ensure the 'Show Notes' option is selected as in this image:

![Workspace 1_021](https://f.cloud.github.com/assets/794512/304816/11b2274e-9647-11e2-8fdd-bb1cda63c05c.png)

If there are other perceived bugs related to annotations, please open another ticket - closing this for now.

Resolved by disabling bbox capturing in monitoring extension - upstream fix awaiting in geoserver/geoserver@d3f41543
