### ISSUE TITLE
Problem uploading a shapefile with same name as existing layer

### ISSUE THREAD

**Issue by mbertrand** [MapStory/mapstory-meta#63]
When a shapefile is uploaded that has the same name as an existing layer, the time data for the existing layer is overwritten but not the actual layer or metadata.  Instead a new layer should be created with a number appended to the name, as in standard geonode.

**Comment by cholmes** [comment]
Just tested this, and it seemed to be fixed, doing same as geonode. See http://mapstory.dev.opengeo.org/data/geonode:world_series_winner_final and http://mapstory.dev.opengeo.org/data/geonode:world_series_winner_final0
