### ISSUE TITLE
Add "Beta" to homepage

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#630]
Here is a good example of this in practice:

http://emlo.bodleian.ox.ac.uk/

Notice it links back to text that signal issues the user is likely to experience at this stage. We could have a link back to Wiki Roadmap with a section for "current major issues/challenges".

**Comment by cholmes** [comment]
@jonpmarino - this is easy for us to do, but we need the actual images to put on. We don't really have graphic designers that can do this right now. It shouldn't be hard, and I think Tucker said he could get it. He may just make them himself? But basically get us the assets, and we can update the site.

**Comment by jonpmarino** [comment]
Ok. We can get a graphic. J-peg?

**Comment by jonpmarino** [comment]
Ok, I imagine something as simple as this, using same font as other header links.
![beta image](https://f.cloud.github.com/assets/2573761/422125/5e22b7b0-ad1c-11e2-87c5-7beca2e79c14.jpg)

**Comment by ischneider** [comment]
@jonpmarino, that should be relatively easy. You mentioned a link to a wiki page, too?

**Comment by jonpmarino** [comment]
No, don't think that's necessary...

On Wed, Apr 24, 2013 at 4:53 PM, Ian Schneider notifications@github.comwrote:

> @jonpmarino https://github.com/jonpmarino, that should be relatively
> easy. You mentioned a link to a wiki page, too?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/opengeo/mapstory/issues/630#issuecomment-16963936
> .

## 

Jonathan Parnell Marino

@jonpmarino
www.mapstory.org
(815) 222 9088

**Comment by ischneider** [comment]
Like this?

![Workspace 1_025](https://f.cloud.github.com/assets/794512/422303/a87bf014-ad22-11e2-9015-c73677e7ae20.png)

**Comment by jonpmarino** [comment]
Good enough for me!!!

**Comment by jonpmarino** [comment]
looks good on Dev, Ian. cool to push to production when you can.

**Comment by cholmes** [comment]
Verified on prod.
