### ISSUE TITLE
importer time transforms configured multiple times

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#634]
This appears to happen after a failure in the time step and an attempted retry.

**Comment by cholmes** [comment]
Closing, as this got deployed, though I haven't be able to test.

**Comment by ischneider** [comment]
Reopening as there is evidence this still occurs sometimes.

**Comment by cholmes** [comment]
Cool, removed 'ready for testing' label and put in a future milestone so we track it.

**Comment by ischneider** [comment]
The issue pops up with lat/lon transforms, too.

Both occur when resuming an import.
