### ISSUE TITLE
Sign up on front page should be a real linke

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#637]
We have a sign up button on the home page, but it doesn't do anything
![MapStory _ Welcome ](https://f.cloud.github.com/assets/407017/381244/850e3676-a5db-11e2-9c37-8e8049c83116.png)

Should hook it up as a link to http://mapstory.org/account/signup/

**Comment by iwillig** [comment]
K that should be easy to fix.

**Comment by iwillig** [comment]
Okay fixed this is ready for development.

**Comment by iwillig** [comment]
On dev.

**Comment by cholmes** [comment]
Looks great. Ready for deploy

**Comment by cholmes** [comment]
confirmed on prod.
