### ISSUE TITLE
Longer sections on homepage

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#638]
From Tucker:

'2)  Can we rework the vertical sliders on Thinkers and Thoughts, and on the sections, so that 4 or so of each show on default display?'

It looks like the sections are about 3.5 showing up now, and the thinkers and thoughts 3. Could we extend those to be longer by default.

Ivan, assigning to you, let me know if you can't handle it easily.

**Comment by iwillig** [comment]
Okay, 
Should be not that hard.

**Comment by iwillig** [comment]
In a PR ready for development.

**Comment by iwillig** [comment]
Oh dev, might need to hard refresh.

**Comment by cholmes** [comment]
Sizing looks great. 

It's an existing bug, but on the 'sections' the human settlement and science and technology ones have the same maps in them. @ischneider - do you know how those are set? Are they just configured to be the same on dev? Just want to be sure we're not introducing any bug here, and I've never looked closely at the sections until now.

**Comment by ischneider** [comment]
I think I just ran a script that randomly populated some of the sections. They can be configured in the admin interface or in the layer/map page.

**Comment by cholmes** [comment]
Ok, I guess this then probably didn't introduce a bug then. Will mark as ready to deploy, let's just be sure to check on mapstory.org that the sections aren't messed up before closing.

**Comment by cholmes** [comment]
confirmed on prod.
