### ISSUE TITLE
Timebar problems with multiple time layers on one map 

### ISSUE THREAD

**Issue by mbertrand** [MapStory/mapstory-meta#64]
Attempting to add a second time-enabled layer on a map causes a javascript error - 

if same layer: in TimeManager.js:
range is not defined
if(oldIntervalsLen!=this.intervals.len...vents.triggerEvent('rangemodified')}} 

if different layer: in OpenLayers.js:
str.match is not a function
return str;};}})(),parse:function(str)...t);}}}else{date=new Date("invalid");} 

Second layer appears in the map but not in the layer tree.  Adding it again will add it to the layer tree.  The time bar stops working after a second different layer is added.

**Comment by bartvde** [comment]
I cannot reproduce this anymore with the current code base, so closing.
