### ISSUE TITLE
upload sessions not handled well

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#642]
browsers keeping page cache for history and bug in deleting upon completion - cause of many errors

**Comment by cholmes** [comment]
I'm happy to test on this, but can you give me a workflow that used to not work? Also happy to just spend some time uploading a few things.

**Comment by ischneider** [comment]
Once an upload is complete, pressing the back button or returning to any of the 'steps' of the upload should result in a page that says something like 'you have no upload in progress'. I tested with both firefox and chromium so I'd guess it's resolved but feel free.

**Comment by cholmes** [comment]
I didn't get a chance to test, but this got deployed, so closing.
