### ISSUE TITLE
Add date added/edited in Admin console.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#643]
From Tucker: '3)  Add date added/edited to the map and layer screens on Admin console. This lets you see the most recent of everything.'

**Comment by iwillig** [comment]
I have a couple of questions about this ticket. 

First, it seems like some of the core geonode data types are missing the required data fields. 

There is one field of the Layer object that seems close to the what we need. The Layer object is very closely tied to the an iso standard and there for is missing an date added field and a last modified field. The closet thing that we have on the layer object is 

https://github.com/opengeo/geonode/blob/mapstory/src/GeoNodePy/geonode/maps/models.py#L740

Which is not the same thing as what was request.

For the map object we actually have a last modified time stamp but not a created date, 

https://github.com/opengeo/geonode/blob/mapstory/src/GeoNodePy/geonode/maps/models.py#L1331

I am going to open a PR that does the min, without any database migrations, but I am going to check in with Ian about taking this further.

**Comment by iwillig** [comment]
https://github.com/opengeo/geonode/pull/26

**Comment by cholmes** [comment]
@ischneider - looks like only 'layers' got deployed, but not 'maps', on production. On dev they are both there...

**Comment by ischneider** [comment]
D'oh - a raft of changes never actually got deployed in my rush to get out for vacay... Done.
