### ISSUE TITLE
Download Admin tables as .csv

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#644]
Would be great if there's some easy way in django to enable this. If not then we can figure out which tables are most important.

**Comment by cholmes** [comment]
Looks like there's some stuff out there: https://docs.djangoproject.com/en/dev/howto/outputting-csv/ and http://djangosnippets.org/snippets/2369/

**Comment by ischneider** [comment]
I had mentioned 'reporting' functionality earlier. The problem with just the specific tables is that often one needs more complete 'views' on the data. The app I tested was not too helpful and seemed incomplete and partially broken.

It looks like that generic action in the snippets would be a start but we'd most likely need to tweak certain views and mask or process field values to be of much use.

If there are specific 'reports' of interest, let's identify those and see if the generic action output will fit the requirements.

**Comment by cholmes** [comment]
I will talk to Tucker about what he wants to see.

**Comment by ischneider** [comment]
With a small amount of additional work, https://github.com/opengeo/mapstory/tree/iss-644-csv-export will support generic reports as well as model specific reports of a fixed nature (i.e. the query input and formatting are fixed) selected items. To query everything (like without requiring the user to make a selection), it will require some hacking to this approach or a more involved one.

ref: http://stackoverflow.com/questions/4500924/django-admin-action-without-selecting-objects

**Comment by cholmes** [comment]
@jonpmarino says they really just care about the users and their emails. 

Assigning to Ivan. Can just do the user table or a more generic one, up to you.

**Comment by iwillig** [comment]
Ian or Chris

What  tasks do you think are left on this issue? Should we define some reports that our admin can generate.

**Comment by cholmes** [comment]
@iwillig - We just need one report. Which is the users, and be sure to include their email. 

So baseline is being able to go to http://mapstory.dev.opengeo.org/admin/auth/user/ and have a button there that says 'download as csv'.

I guess if that's a pain there could be a 'reports' section, that just has the user one, letting people download as csv.

**Comment by ischneider** [comment]
@iwillig, you can add the action to the User ModelAdmin or go with it as is on the entire site. Model specific actions might make more sense to support trimming off irrelevant information. See my comment above to support exporting all objects without requiring a selection.

Ping me w/ any questions.

**Comment by iwillig** [comment]
Hey Ian, 

Do you think its important that we allow users to export users without an selection?

**Comment by ischneider** [comment]
I believe that is the functionality they want.

**Comment by ischneider** [comment]
This is deployed to dev. The reports are here:
http://mapstory.dev.opengeo.org/admin/reports/

This page should be protected but it's not a serious issue as the reports themselves are limited.

As I had already done the user activity report, I just slotted that in, too.

**Comment by adunetz** [comment]
Assigned to Cholmes to verify.

**Comment by cholmes** [comment]
Hrm, not working for me. 

![attributeerror at _admin_reports_generate-user-report](https://f.cloud.github.com/assets/407017/562381/84f8ff7c-c4a8-11e2-87cc-5c64823ea08e.png)

I just clicked on 'User Details CSV Report' and got that.

The activity report seems to be working well though, and is super cool.

**Comment by ischneider** [comment]
Sorry about that @cholmes. Fixed.

**Comment by cholmes** [comment]
Looks great. Thanks!

**Comment by cholmes** [comment]
@ischneider Checking this on prod, it works great if you know to go directly to http://mapstory.org/admin/reports/

But if you click on 'reports' on the admin screen (the one at the very top) it takes you to mapstory.org, not to http://mapstory.org/admin/reports/ On dev it still does the right thing, just not on production.

**Comment by cholmes** [comment]
Moving to annotation milestone, so we can close out raster milestone.

**Comment by cholmes** [comment]
Confirmed working on production.
