### ISSUE TITLE
Add 'welcome' video to register page.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#646]
Need to get the video from washington college. @jonpmarino - can you help with letting us know here when the video is ready?

**Comment by jonpmarino** [comment]
Sure. Haven't seen final product yet, so this is provisional based on seeing that!

**Comment by cholmes** [comment]
@jonpmarino - this has been scheduled as high priority, but we don't have the video. Any progress on it?

**Comment by jonpmarino** [comment]
Ok. We have a version done but to be honest, its quite low quality. Have you done work on this? If not, I would suggest holding off and instead prioritizing the 'welcome' email that auto-sends to new sign-ups after they verify account reg. I think that will actually have a higher impact on orienting new users to what they're getting into :)

**Comment by jonpmarino** [comment]
The other thing we could do is just put Tucker's original 'welcome' video there, too, which is still a pretty good welcome.

**Comment by ChristopherTucker** [comment]
I think my old video is out of date

**Comment by cholmes** [comment]
Have not done any work on this. Will move it off to medium term.
