### ISSUE TITLE
Add ability to re-style old MapStories

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#647]

**Comment by ischneider** [comment]
Can you provide more details on this Jon or a specific map where you are seeing the issue?

**Comment by jonpmarino** [comment]
Ian, thanks for response. This was an issue some of the ASU students requested I follow up on. I'll get more intel and an example from them.

**Comment by jonpmarino** [comment]
Ok, here's the screenshots showing the editing styles are disabled for some stories.

![diffstoryss2](https://f.cloud.github.com/assets/2573761/404182/f6e83388-a93b-11e2-9415-4dc904e185c3.png)
![diffstoryss1](https://f.cloud.github.com/assets/2573761/404183/fb6be33c-a93b-11e2-9a74-a7be0500aa87.png)
![screenshot2](https://f.cloud.github.com/assets/2573761/404184/fe957064-a93b-11e2-9034-44ec07c99245.png)
![screenshot1](https://f.cloud.github.com/assets/2573761/404186/02449b7c-a93c-11e2-925e-64cc3f5cae0e.png)

**Comment by cholmes** [comment]
Hmmm... http://mapstory.org/maps/64/view/ works, as does http://mapstory.org/maps/159/view/

http://mapstory.org/maps/427/view/ doesn't And the ones above don't either. For ease of reference those are http://mapstory.org/maps/587/view/ and http://mapstory.org/maps/467/view/ Also http://mapstory.org/maps/218/view/ does not work.

@bartvde - can you look in to this? If you can't reproduce easily then we can wait for @ischneider to finish Michael's migration tool.

**Comment by bartvde** [comment]
Are these maps on dev as well? That would make it easier to debug.

## 

Bart van den Eijnden
OpenGeo - http://opengeo.org
Expert service straight from the developers.

**Comment by ischneider** [comment]
I'll attempt a migration on this map - found another few things that need to be adjusted first.

**Comment by bartvde** [comment]
@ischneider is this because of the prefix issue again? It looks like this map is not referencing the layer through the right endpoint / url:

http://mapstory.org/geoserver/wms?LAYERS=az_50yr_avg_precip&SERVICE=WMS&VERSION=1.1.1&REQUEST=DescribeLayer

returns in DescribeLayer with the geonode prefix:

```
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE WMS_DescribeLayerResponse SYSTEM "http://mapstory.org:80/geoserver/schemas/wms/1.1.1/WMS_DescribeLayerResponse.dtd">
<WMS_DescribeLayerResponse version="1.1.1"><LayerDescription name="geonode:az_50yr_avg_precip" wfs="http://mapstory.org:80/geoserver/wfs/WfsDispatcher?" owsURL="http://mapstory.org:80/geoserver/wfs/WfsDispatcher?" owsType="WFS"><Query typeName="geonode:az_50yr_avg_precip"/></LayerDescription></WMS_DescribeLayerResponse>
```

It should be using:

http://mapstory.org/geoserver/geonode/az_50yr_avg_precip/wms?LAYERS=az_50yr_avg_precip&SERVICE=WMS&VERSION=1.1.1&REQUEST=DescribeLayer

so these maps should be migrated somehow to the new url structures for virtual services.

**Comment by bartvde** [comment]
yeah so the map config should be migrated:

```
"local": {"title": "My GeoServer WMS", "url": "/geoserver/wms"
```

**Comment by cholmes** [comment]
I tried to migrate one of these by hand in the admin, but it said I needed a real URL (even though the existing one is not valid), and a group (the existing one is blank). So maplayers can't really be administered by hand. If we want to let people administer by hand we should also probably make them searchable. Or better yet link to a map's maplayers from it's maps admin page.

**Comment by cholmes** [comment]
Who marked this as high priority? Removing that label.

@jonpmarino - we need to make a migration script and will try to get to that soon. But there is a decent work around, which is to just tell users to make a new mapstory with the same story layer. Their style should be there, if not the default then as a drop down from the styler dialog.

**Comment by ischneider** [comment]
Can confirm that a migration fixes this.

**Comment by bartvde** [comment]
thank god for that ;-)

**Comment by ischneider** [comment]
There are 159 of these and I found the issue is more complex and needs more testing. My initial thought was that just the ows_url field in the MapLayer model needs changing, but it seems the id in the source_params also needs updating or other things break.

**Comment by ischneider** [comment]
Migration complete, let the testing begin!

107 maps scattered in the range of 4-285... I'd guess a sample size of 10-20 :palm_tree:

**Comment by cholmes** [comment]
Hrm, I don't actually know any ones on dev that weren't working. I tested map 4 and I can style it. So if that was one not working then we're good. 

Will mark as ready for deploy. If there are ones that you know were bad on dev then I can test and confirm on those.

**Comment by ischneider** [comment]
Found an issue - those maps with custom styles most likely contain broken references that render the styler partly broken again.
