### ISSUE TITLE
Share This email function generates links to hugedomains.com.

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#649]
Tried to send a MapStory with the Share This email function. With 2 different tests the MapStory link sent me to hugedomains.com. Screenshots below.
![test](https://f.cloud.github.com/assets/2573761/405966/2cc46a4c-aa33-11e2-8e76-2029416660ca.jpg)
![test1](https://f.cloud.github.com/assets/2573761/405967/32b55e84-aa33-11e2-8d97-6146c37a2c4c.jpg)

**Comment by ischneider** [comment]
The site-wide shareme stuff seems to work. Looking into what's up on the layer/map sharing.

**Comment by ischneider** [comment]
GrinSide for _only_ $1,195 - sign me up!

**Comment by ischneider** [comment]
Confirmed this is fixed. Reopen if anything else shows up wrong.
