### ISSUE TITLE
Add 'edit' link if logged in and owner of a map/layer

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#652]
Ivan - this is the one we keep mentioning. If a user is both logged in and the owner of a map then we should have an 'edit this map' link from the map page. So that they don't have to go through 'expand' and 'edit' to get there. But don't want to expose it to everyone, just the owner. Should be right below the 'view this map in full screen'

**Comment by cholmes** [comment]
Is this deployed? Happy to test when it is.

**Comment by ischneider** [comment]
Deployed to dev - just verified.

**Comment by adunetz** [comment]
Ready to test label added, assigned to Cholmes to verify.

**Comment by cholmes** [comment]
Looks great, ready for deploy.
