### ISSUE TITLE
Start search results expanded

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#654]
Right now it's a bunch of narrow lines when we get the search results. Would be much cooler to have the images and abstracts there to browse through. Hopefully can just start with the little ext expander in the 'out' state, and let people collapse it.

**Comment by iwillig** [comment]
So I took a similar but a little different approach. Right now the way the search widget works it to allow the user to select if the "meta" data is shown. This meta info is the thumb nail, the abstract and the rantings.  Then we attach the change event and redo the search if the use toggles this input.

**Comment by cholmes** [comment]
Yeah, looks great, better than what I was hoping for. There's a small language tweak I'd like, but will make a new ticket for it.
