### ISSUE TITLE
'read more' in abstract of search results on the map

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#655]
In the map composer the 'abstract' field now is sometimes quite long. Would be better if it just displayed 4 or 5 lines and then said 'read more', which users could expand out.

**Comment by iwillig** [comment]
Added in these lines, 

https://github.com/opengeo/mapstory/blob/newMapSearch/media/script/map-search.js#L75-L77

**Comment by cholmes** [comment]
Looks great.
