### ISSUE TITLE
Paging on search results

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#656]
Would be great if we could have a paging mechanism for the search results in the map composer page. I guess could also do the infinite scrolling like the main search, that'd probably be ideal, but not essential. With pagination though we'd be able to start with some results, since we wouldn't be returning everything.

**Comment by iwillig** [comment]
Addressed in newSearchMap, 

https://github.com/opengeo/mapstory/tree/newMapSearch

**Comment by cholmes** [comment]
Tested on dev, looks good. Could we try increasing the number of results per page to 20? Main issue to me is that with just 5 when you de-expand them the screen looks a bit empty. 20 may be too many to scroll through when it's expanded, but let's try it.

Long term we might try some auto-filling of the space, but that'll probably get tricky with paging. And I think somewhere above 5 and less than 30 will get us well enough along.

**Comment by cholmes** [comment]
I'm removing 'ready for testing' label, put it back when you tweak it, and I can mark for deployment.

**Comment by cholmes** [comment]
Looks like this is now 10 results. Let's adjust it to 25.

**Comment by ischneider** [comment]
Next and prev buttons remain active if result set is 0 in size - like search for something non-existent

**Comment by cholmes** [comment]
Nice catch Ian, confirmed the same problem. Though the 25 results looks good. 

@iwillig - you want a new ticket for Ian's comment? Or just do it here?

**Comment by iwillig** [comment]
This seem to me like a new feature request, please open a new ticket thanks.

**Comment by cholmes** [comment]
Sure - #777

**Comment by cholmes** [comment]
Marking this one ready for deploy. Nice work Ivan.
