### ISSUE TITLE
Have search in map composer start with results

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#658]
The 'search' on map composer can be intimidating if one doesn't know what to search for, as it's just an empty line.

With #656 in place we should be able to start with something displayed, as it won't overwhelm the client.

Would be ideal to start with the most popular, once #657 is in place.

**Comment by iwillig** [comment]
Bottom of page has an example something that could work for the  UI. 

https://6e4a55e8-a-14a40982-s-sites.googlegroups.com/a/opengeo.org/ui/geonode/version-2/map-composer-and-geonode-integration/Map%20View%20Edit.png?attachauth=ANoY7cqkV7Y9obojvcWS7N-cjdYvhf78KEkdHkqz0UWUOzIa6Dxh9wsAD9AIiUFse_cPMKdgRJlff1UYYmnJ5D7pzepRItAXP33Z4Fif0xFYXh7B_c786eJ-qiXJRAAccgLGjXTNNhIp3bepZoyh1xLkDomLk0gk2FT3E2Dphc7eBT9LgcIE6d921KSSnIaLE49mgtuOH9blLmkuS6Xo89GTaBuLOz1GWQ_NW5ZdncOG7NyX8gMuWwsZdhXVgrKJX14w63V1StLknVgdWFYltZCZiEnFoxH0nQ%3D%3D&attredirects=0

**Comment by iwillig** [comment]
Addressed in 

https://github.com/opengeo/mapstory/tree/newMapSearch

**Comment by cholmes** [comment]
Looks great, marking ready for deploy.
