### ISSUE TITLE
Refactor annotations to be in the django model

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#659]
Annotations should be handled in django, not in geoserver. Then we'll have more flexibility to change the model, as well as an easier time handling uploads ( as in #580 )

**Comment by bartvde** [comment]
going to look at this one today, @iwillig is there a specific reason why the javascript code is in the mapstory project and not in the geonode/mapstory branch where the rest of the js code resides? Personally, I'd like to keep this code closer to GXP if possible.

**Comment by ischneider** [comment]
Marking ready for deploy. The base functionality is here. Create new tickets for other issues, please.

**Comment by jonpmarino** [comment]
@ischneider did we acquire builk upload as referenced in #580 when we did this? Looks like we have bulk delete but not bulk upload.

**Comment by ischneider** [comment]
#580 covers the backend service, #874 covers the UI - both are almost ready.
