### ISSUE TITLE
Time too specific when editing annotations

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#66]
When editing annotations, if you enter an imprecise value for the date the editor appears to fill in the gaps with the current time.  Here the time was entered as just "1390" but echoed back as "11/21/1390" (added on 11/21/2011)
https://skitch.com/alyssawright/gk8db/map-viewer-geonode

**Comment by bartvde** [comment]
Hmm apparently this is how Javascript handles dates:

Date.parseDate("1931", "Y")

yields:

Date {Tue Jan 06 1931 00:00:00 GMT+0100 (AMT)}

Need to see if there is way around this.

**Comment by bartvde** [comment]
I should have said how Ext handles it.

Plain javascript yields:

new Date("1931")

Date {Thu Jan 01 1931 01:00:00 GMT+0100 (AMT)}

**Comment by bartvde** [comment]
c     ISO 8601 date
        Notes:                                                                    Examples:
        1) If unspecified, the month / day defaults to the current month / day,   1991 or
           the time defaults to midnight, while the timezone defaults to the      1992-10 or
           browser's timezone. If a time is specified, it must include both hours 1993-09-20 or
           and minutes. The "T" delimiter, seconds, milliseconds and timezone     1994-08-19T16:20+01:00 or
           are optional.

**Comment by bartvde** [comment]
dwins, just to confirm, when specifying 1930 you want it to be 01-01-1930?

**Comment by dwins** [comment]
Well, technically "1930" corresponds to a time range, [1930-01-01T00:00:00, 1931-01-01T00:00:00).  In the absence of good interval support on the server though, using the start of the interval seems like the way to go.  Btw, this ticket is from Alyssa's and my notes from the November demo, so she might have other thoughts on the issue. @awright ?

**Comment by bartvde** [comment]
Fixed with https://github.com/opengeo/gxp/commit/8f43392cc0f3e58910d3656a9c1eb303479092c7

Please reopen if something else was needed.
