### ISSUE TITLE
Better pictures, videos and links in annotations.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#662]
After #661 we should improve the handling of pictures, videos and links.

We made a start on this, but it requires hacking in the description. They should just be nice fields to easily edit.

**Comment by bartvde** [comment]
I guess this work depends on the new wireframes?

**Comment by bartvde** [comment]
@emloux @ischneider any guidance on whether or not this should be moved out of the current milestone or not?

**Comment by emloux** [comment]
@bartvde I think this may require some more investigation/research, I'm going to move it out of the current milestone.
