### ISSUE TITLE
Allow users to limit search to current viewport map and map extent

### ISSUE THREAD

**Issue by iwillig** [MapStory/mapstory-meta#666]
Makes sense since the search api already supports this. 

Two new options then 
1. Allow users to limit layers via the current map's viewport. 
2. Allow users to limit layers via the map's static map extent.

**Comment by iwillig** [comment]
While I was working on this feature I noticed that we have an interaction issue. When the user limits the search results to the current extent a lot of results are of course removed. The user now needs the ability to adjust the map. 

In order to support this we need to attach an event listen to the OpenLayer.map pan event.

**Comment by ischneider** [comment]
The search bbox query param is being provided in web mercator meters, it must be latlon degrees. Time based search looks pretty cool, though.

**Comment by cholmes** [comment]
Tested on dev, working pretty well.

@iwillig - it looks like you added the stuff to listen to the openlayers pan? I can get moving to update the results. But it seems to need to 'change' the result list. Like expand or minimize the results. Could we have the update on pan fire to actually change the list ordering more? Like whenever you move have the list update if things have changed?

**Comment by cholmes** [comment]
Still curious about my last comment, if it'd be possible to continually update when moving. But it's definitely ready for deployment.
