### ISSUE TITLE
Add "Skills" section to MapStory profile create

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#668]
Want to add a new portion to individual StoryTeller's profiles for "MapStorytelling Skills". Functionally this would operate the same as adding "Topics" to MapStories, except we need folks to be able to select multiple....essentially a set list of check boxes. Perhaps with ability to "add a new skill" like keywords.

Then, I want people to be able to "Search for" MapStorytellers by skills they express in addition to current "Sort by" search options.

The goal is is 2-fold: 1) for others to more easily find peers that have skills and might be able to help them and 2) to get a clear understanding of the things people need to know to tell MapStories in the first place.

If this is technically possible, we can quickly create a first draft of skills...
![profile](https://f.cloud.github.com/assets/2573761/432923/92542f12-aeb3-11e2-9a9a-9e837cf31961.jpg)

**Comment by emloux** [comment]
@jonpmarino can you provide a first draft of skills?
