### ISSUE TITLE
Annotation editor offers to edit id property

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#67]
On the demo site you can type in a new id for features in the annotation layer (maybe a configuration issue...)  It shouldn't be editable, and probably shouldn't even be displayed.

**Comment by bartvde** [comment]
Hmm, I don't have this in my local copy. Any chance the layer is exposing the primary key field as a WFS attribute (GeoServer option)?

**Comment by bartvde** [comment]
Yeah this is a GeoServer issue, compare:

http://mapstory.dev.opengeo.org/geoserver/wfs/WfsDispatcher?service=WFS&request=DescribeFeatureType&typename=geonode:annotations

with:

http://mapstory.demo.opengeo.org/geoserver/wfs/WfsDispatcher?service=WFS&request=DescribeFeatureType&typename=geonode:annotations

**Comment by bartvde** [comment]
Not anymore an issue, so closing.
