### ISSUE TITLE
Option to limit map composer search to current time

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#672]
Would be great to have search results on the map naturally limit to the current 'time' displayed on the map. Best would be to have a checkbox that is 'on' by default (though if there are no layers at all on the map may be best to not start it on, so results actually show up), that can easily be turned off.

Would be good to get any layer that has a time that spans the current time. And for that to also work right with 'range' and 'cumulative'.

**Comment by ischneider** [comment]
How about instead of the current time using the overall extent of the entire map?

Using only the current time, one might miss data that overlaps significantly with the overall extent.

**Comment by iwillig** [comment]
Sure, either one works for me. Which do we think is best?

**Comment by cholmes** [comment]
Tried this on dev. The checkbox seemed to always be greyed out for me.

Also could we put the three checkbox options on their own lines? And perhaps put the text to the right of the checkbox? They are a bit confusing now as to which text goes with which checkbox.

**Comment by iwillig** [comment]
Chris, you need to add a layer that has some time information to the map first. The map does not have a current range before a layer is added. 

Also, please note that some layers don't have a time information on dev.

**Comment by cholmes** [comment]
I tried a bunch of different ones, making sure the map was fully saved and had a timeline. Will try some more.

**Comment by cholmes** [comment]
If you can give me a link to a map working on dev that would be great.

**Comment by cholmes** [comment]
Ah, got one to work. But it was only when I created a new map from an existing layer. And it _only_ showed up the first time. If I closed the search and then did 'add layer' then the new search box didn't have the option.

**Comment by iwillig** [comment]
Yeah this is an issue... it worked on my local machine. We need a better way of telling if a map is a time enabled.

**Comment by cholmes** [comment]
But yeah, I've not gotten an existing map that I want to add more to to work. Like http://mapstory.dev.opengeo.org/maps/295/view/ With admin password, I hit the green add button, and it's greyed out.

**Comment by cholmes** [comment]
Ok, cool. Can treat this with a bit lower priority than the others, since I think it'd be ok to cut this and revisit later. Since like you say it could use more of a gui element. If we can get it working this week that's great, but don't want to hold up the release on it.

**Comment by iwillig** [comment]
Can you explain this? 

"But yeah, I've not gotten an existing map that I want to add more to to work. Like http://mapstory.dev.opengeo.org/maps/295/view/ With admin password, I hit the green add button, and it's greyed out."

I am not sure I follow what you mean. What do you mean "to to work". 

Thanks.

**Comment by cholmes** [comment]
Sorry for not being clear. to work = to not have the 'limit search to current time range' to not be greyed out. Everything but that functions fine. I can try some more maps, but have tried like 5 existing maps that all have time, where the button to limit search on time range is grayed out.

**Comment by iwillig** [comment]
Okay got... its fine I get that its broken and am looking into it.  

Thanks.

**Comment by iwillig** [comment]
I think i figured it out... one second.

**Comment by iwillig** [comment]
Okay... I think i have fixed it on dev. please check. 

Thanks for catching this issue.

**Comment by cholmes** [comment]
Looks great, is working in most cases. Definitely will be nice to get some better UI on it, but marking ready for prod.
