### ISSUE TITLE
Update instructions to reflect raster support

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#676]
http://mapstory.org/data/upload/ should have information about the support of tifs, etc.

**Comment by ischneider** [comment]
What exists currently is on dev. Take a look at the manual content linked to via the upload page.

**Comment by adunetz** [comment]
assigned to Cholmes to verify.

**Comment by cholmes** [comment]
Looks great.

I'd say we are ready for the 'raster' release.
