### ISSUE TITLE
Change 'reflections' to 'storyboards'

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#677]
Lots of feedback that what people are more interested in in this section is not MapStorytellers reflections on what they did in particular, but on the idea of 'storyboards' in which MapStorytellers talk through the basic structure of their story and how they told it. No technical changes needed. Just change link and page title to "Storyboards".

**Comment by cholmes** [comment]
So this should change 3 places

In the url http://mapstory.org/mapstory/reflections/ (reflections to storyboards)
In the header on all mapstory pages
In the title/text on the page at http://mapstory.org/mapstory/reflections/

**Comment by emloux** [comment]
Closing this as we decided to do away with 'refllections' during the user meeting last week.
