### ISSUE TITLE
Improve interactions for adding to map from search

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#683]
Interaction on the links in search seems a bit off. I think a more intuitive thing would be clicking on the layer name or the thumbnail would add the layer to the map. Ideally it'd have a little dialog that fades away that says 'added <layername> to map'. But it's fine with out if that's hard. And then instead of 'add to map' I'd have that be a 'less' / 'more' thing. If it's expanded it says 'less', which minimizes, and if minimized it says 'more' which expands it.

**Comment by cholmes** [comment]
@iwillig - I'm testing your new stuff on dev, most stuff looks great. Looks like this one isn't there though? Did you forget to push it? Or do you need more info?

**Comment by iwillig** [comment]
I am still thinking about the best way to improve this.... So no I have not done it. More info would be great.

**Comment by cholmes** [comment]
So I think it can be pretty simple:
![screen shot 2013-06-25 at 4 10 53 pm](https://f.cloud.github.com/assets/407017/705279/672caf90-ddd3-11e2-8ab0-88c04fb46131.png)

The layer name (Yemen Livelihood Zones in the above) should do the action that 'add to map' does right now. When I click on it I expect it to 'add', where right now it minimizes the thumbnail, which is the last thing I expect. You could put a little text that says (add) after the layer name to make it more obvious.

The place where it says 'add to map' should be the action that minimizes/maximizes. And the text should say 'less' (when expanded) and 'more' (when minimized). 

I think those two things will make it more natural for people.

**Comment by cholmes** [comment]
Oh, and one more thing. Could we do a 'zoom to layer extent' call on the newly added layer, right after it's added?

**Comment by ischneider** [comment]
Zooming is useful. The listing changes look nice to me but one improvement maybe? Tooltip over the layer name to note "Add this storylayer to the mapstory" or such.

**Comment by cholmes** [comment]
+1 on a tooltip over layer name. Other than that it works great.

Wondering if we should also take some action with clicking on the image, as I often try to do that. Will think on it, and make another ticket if need be.

**Comment by cholmes** [comment]
Looks great.
