### ISSUE TITLE
Add "Step 9" to Tutorial in manual

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#684]
Want to add this to tutorial in manual:

Step 9: Share Your Work

Now that your MapStory is published, make sure to share your work and your experience!

-Share your MapStory on Twitter or Facebook with #mapstory
-Create a Storyboard video and upload it to the MapStory You Tube account, and link to it in your MapStory's abstract
-Create a How-To guide that walks others through how you built this MapStory, upload it to the MapStory Wiki, and link to it in your MapStory's abstract
-Write a blog post about your experience and send it to blog@mapstory.org.

**Comment by emloux** [comment]
This should also be addressed with #728

**Comment by drwelby** [comment]
added in https://github.com/drwelby/mapstory/commit/f099fb17e30b171277c09007ef5349af83696af0

**Comment by emloux** [comment]
@drwelby Just spoke to Jon and determined that this does not actually need to be implemented.  Closing this ticket.
