### ISSUE TITLE
Add button to edit profile form asking new users to join Volunteer Technical Community

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#686]
Add an option to "join Volunteer Technical Community" on user edit profile page. On profile, then, under Interests or Expertise or something, it will simply show that that member is a "VTC Member".

Check out video on Get Involved to learn more

**Comment by cholmes** [comment]
Do we think signup is the best time to ask that? I'd guess people would first want to try the site and figure out the potential, before signing up for a list, etc.

**Comment by cholmes** [comment]
(though I do admit that putting it here is probably easiest from an implementation perspective)
