### ISSUE TITLE
Thin panel / button for timeline

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#687]
Now that we have the 'timeline' button the long panel with the expand button doesn't need to be nearly so big, since it's no longer the only way to get at the timeline. Ideal would be to eliminate the panel at the bottom when the timeline is not expanded. If that's a pain with ext then a perfectly good outcome would be to use a panel and button that's super thin. http://suite.opengeo.org/geoexplorer/composer/ is a great example of this, on its side panel. Can just reuse theirs.

**Comment by ischneider** [comment]
The super thin button was (almost) universally missed by everyone unfamiliar with ext (or the composer) so we stopped using it (for the side). A possibility might be to use a 'normal' button located in the tools that expands the timeline.

**Comment by cholmes** [comment]
Yeah, exactly. Ivan already implemented a 'normal' button (just text that
says 'timeline'), which is why we put a ticket for this.

**Comment by cholmes** [comment]
@bartvde - could you tackle this one? Let me know if you need more info on it. There are a few other little button reworking issues I will have you check out too.

**Comment by bartvde** [comment]
@cholmes so bring back collapseMode: 'mini' for the timeline panel? Or also for the left panel in the composer?

**Comment by cholmes** [comment]
Yeah, I think so. Make sure it still stays hooked up to the 'timeline'
button though, as that's how most everyone will be using it I think.

**Comment by bartvde** [comment]
@cholmes talking to @iwillig it seems the new Timeline button is only there in the composer, so I assume that the collapseMode: 'mini' should only be done in the composer. Is this a right assumption?

**Comment by bartvde** [comment]
see https://github.com/opengeo/geonode/commit/d29a4168a18d5d53480781396accc7563dce5ce1

**Comment by bartvde** [comment]
deployed to dev

**Comment by cholmes** [comment]
Yeah, just for the composer. Sorry for not being clear on that.

**Comment by cholmes** [comment]
Looks pretty good. Though it looks like the old panel and button is still there when you expand out (when it's not expanded it looks great). See: 
![screen shot 2013-05-30 at 11 20 13 am](https://f.cloud.github.com/assets/407017/585708/a5a25a1e-c93c-11e2-8d5b-4d266c44b97d.png)

Can you make sure it goes away there too?

**Comment by cholmes** [comment]
@bartvde - Would you be able to move the timeline button to the time playback toolbar? Like to the right of the 'settings' button?

I guess the button should not show up on the small map page, but should be there when it goes to 'full'.

If that's doable I can make a ticket for it.

**Comment by bartvde** [comment]
get rid of header see: https://github.com/opengeo/geonode/commit/52bee5d905ea2d532745fd2414c1606a24769d0e

**Comment by bartvde** [comment]
@cholmes do you mean the button saying "Layers" ?

"Would you be able to move the timeline button to the time playback toolbar?"

**Comment by cholmes** [comment]
No, the button saying 'timeline'. It's what pops up the timeline. Right now it's only in the map composer view. Would like it in the map page full screen view.

**Comment by bartvde** [comment]
Since @iwillig did this code, would it make more sense to have him weigh in on it?
I see that the button is not set up as a normal gxp.plugins.Tool so it's not so easy to change its actionTarget unfortunately.

**Comment by bartvde** [comment]
@cholmes but doesn't the timeline pop out automatically if there are annotations in a map?

**Comment by cholmes** [comment]
Sure makes sense for @iwillig to weigh in.

@bartvde - it does, but it seems to me that there should still be a way to control it, that's in line with how it's controlled in the composer. I mean, you could make the same argument for the legend - it always pops out, but we still have a button to close it and open it back up.

**Comment by bartvde** [comment]
okay then the easiest way is to just add a new button (it duplicates a small bit of code), will do that then

**Comment by cholmes** [comment]
SOunds good. It should probably just be on the full screen mode.

I guess a cool alternative could be to pop it out as a moveable window on the small mode. So like it doesn't overrun the map, pops out below over the text. Though would need an 'x' to close it in addition to the button. But easier option would be just not include the timeline button there, which would be fine.

**Comment by iwillig** [comment]
Could you just assign this ticket to me and I will correct the issue with the button not being a gxp.Tool? I am at a training for most of the day but this should be an easy fix. 

Thanks.

**Comment by bartvde** [comment]
@iwillig yeah I am working on it already and close to a fix (but not the gxp.plugins.Tool fix)

**Comment by iwillig** [comment]
Okay, 

Sorry about this. I think I did not make this button a gxp.Tool because I ran into an issue with gxp that i did not understand. 

I had hoped that I could come around and fix it. 

Thanks and sorry for leaving this wart in the code base.

**Comment by bartvde** [comment]
np, don't worry

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/ea1515b6272f95cfa5f19d712bf2b637b3694a07

**Comment by bartvde** [comment]
okay this is done but I can't deploy to dev because of a heap space error

**Comment by cholmes** [comment]
Looks great.

**Comment by cholmes** [comment]
Oh, and the new 'timeline' button in full screen mode is great too. But now full screen mode needs the same  adjustment for the thin panel. I'll make a new ticket though, since this ticket is getting overloaded with lots of little requests.

**Comment by cholmes** [comment]
confirmed
