### ISSUE TITLE
Problem with uploading story layer

### ISSUE THREAD

**Issue by satmaram** [MapStory/mapstory-meta#688]
![upload](https://f.cloud.github.com/assets/2531531/498105/b33e6cf8-bc0d-11e2-935b-b0894a1ad7d0.png)

![upload2](https://f.cloud.github.com/assets/2531531/498114/ebeb85fe-bc0d-11e2-967a-9729cdbd1f60.png)

Doesn't show the attributes for selecting time fields

**Comment by ischneider** [comment]
Also see #689

**Comment by ischneider** [comment]
I cannot duplicate this behavior. Can you try again to verify? If you can duplicate, please provide the exact steps to duplicate, if possible.

**Comment by ischneider** [comment]
This is a chrome bug. For now, use firefox if possible. Prioritizing for rapid fix.

**Comment by ischneider** [comment]
To be fair, this was a developer bug that only appeared on chrome :)

**Comment by cholmes** [comment]
Did you fix this Ian? Did you deploy it? Putting at raster milestone to track it.

**Comment by adunetz** [comment]
Ready to deploy
