### ISSUE TITLE
Allow adjusting time scale on timeline control

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#69]
When there are too many features to display, the timeline control asks the user to adjust the scale by using the slider at the left. https://skitch.com/alyssawright/gk8r8/map-viewer-geonode

But this doesn't appear to have any effect on the demo site.

**Comment by bartvde** [comment]
I've verified that this still works locally, what might help is to show to number of features compared to the limit in the help text?

**Comment by bartvde** [comment]
Added the help text info in https://github.com/opengeo/gxp/commit/6033751f7973b8a0868433c7e3aa97a664b62bd6
