### ISSUE TITLE
map/layer publishing workflow UX improvements

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#693]
A few issues here:
- [ ] more up-front information about what is required and why
- [ ] better feedback for missing metadata fields
- [ ] better feedback for missing topic
- [ ] better feedback for missing thumbnail

**Comment by emloux** [comment]
@jonpmarino I'm going to create a separate ticket for the above proposed metadata fixes.

**Comment by jonpmarino** [comment]
Great!

**Comment by ischneider** [comment]
Removed the large comment that was moved over to #887

**Comment by ischneider** [comment]
Changing to Cedar Creek - need to discuss details.
