### ISSUE TITLE
replacing of invalid xml characters results in many poor layer names

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#696]
The current approach to making layer names XML safe replaces a numerical prefix with a single underscore resulting in particularly bad names.

So 1990_2000something would become __2000something.

To fix, perhaps just prepend an '_' if the name begins with a numeral.

**Comment by cholmes** [comment]
Did you deploy this Ian? If not, and you won't by monday, then just put to a later milestone.

**Comment by adunetz** [comment]
Assigned to Ian.  Ready to deploy.
