### ISSUE TITLE
Problem with Embedding YouTube video 

### ISSUE THREAD

**Issue by BetsyEmmons** [MapStory/mapstory-meta#697]
YouTube video will not play after being added to MapStory. 
![screen shot 2013-05-28 at 3 02 49 pm](https://f.cloud.github.com/assets/4552719/574744/6fd5fa2a-c7d0-11e2-9812-73f6275ab2e9.png)
![screen shot 2013-05-28 at 3 13 04 pm](https://f.cloud.github.com/assets/4552719/574745/6fd9899c-c7d0-11e2-86e0-4a5317512e81.png)
![screen shot 2013-05-28 at 3 09 38 pm](https://f.cloud.github.com/assets/4552719/574746/6fdb6adc-c7d0-11e2-9532-a32b9893c405.png)
![screen shot 2013-05-28 at 3 07 14 pm](https://f.cloud.github.com/assets/4552719/574748/6fdae1ca-c7d0-11e2-8a6a-7a6fe8143392.png)
![screen shot 2013-05-28 at 3 11 13 pm](https://f.cloud.github.com/assets/4552719/574747/6fd9379e-c7d0-11e2-87b5-e8470972939b.png)

**Comment by cholmes** [comment]
Thanks for the error report Betsy! I'm sorry it isn't working well, or really at all, at the moment. We are right now refactoring how annotations work, with having the media stuff work better (and be easier to use) in mind. See #662 So we should have something for you to test out in the dev server in 2-4 weeks.

**Comment by bartvde** [comment]
I can reproduce the error but don't know as yet what could be the cause

**Comment by bartvde** [comment]
okay I see the issue now I guess, this youtube url does not have a v parameter, the ones I tested with has, so the iframe src is not correct:

```
<iframe id="player_40" type="text/html" width="250" height="250" src="http://www.youtube.com/embed/undefined?enablejsapi=1&amp;origin=http://mapstory.dev.opengeo.org" frameborder="0"></iframe>
```

**Comment by bartvde** [comment]
Made a fix in the annotations-reworked branch: https://github.com/bartvde/gxp/commit/a7a287e68359360ceed7e5e769aeb0f80489280a

**Comment by bartvde** [comment]
so the fix should make  the video show up correctly, but it doesn't automatically play as yet (however there is another ticket for this already IIRC).

**Comment by emloux** [comment]
Hey @bartvde- embedding youtube videos doesn't work on chrome or firefox.

**Comment by bartvde** [comment]
can you tell me exactly what you tried? last time I tried embed worked but video did not play automatically

**Comment by emloux** [comment]
Sorry @bartvde I think it might have to do with a specific storylayer, I just got this to work.

**Comment by jonpmarino** [comment]
We got it to work too. See http://mapstory.dev.opengeo.org/maps/336/. But, see the image below. If I scroll down, the video annotation travels off the map with my screen.

![youtubevideo](https://f.cloud.github.com/assets/2573761/920787/d1513296-fee5-11e2-8f41-91f9b74a4fb5.jpg)

**Comment by bartvde** [comment]
@jonpmarino okay I can reproduce in Chrome but not in Safari, will look into it

**Comment by bartvde** [comment]
https://github.com/opengeo/gxp/commit/8b9adac1e68ee2e4dc2f44096c45da5e7fe172bd should fix it pulled in with: https://github.com/opengeo/geonode/commit/a1739282de56db34b138d17da4af9f819522abf1 (you might need to clear browser cache, at least for me this was needed)

**Comment by emloux** [comment]
Looks good, Marking Ready for Deploy
