### ISSUE TITLE
Can't style layers in map composer 

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#70]
You can see the issue on this map on the demo site: http://mapstory.demo.opengeo.org/maps/18/view

Here's a screenshot of what we were seeing at the 11/21 demo, an empty dialog instead of the styling tools. https://skitch.com/alyssawright/gk8rs/map-viewer-geonode

**Comment by bartvde** [comment]
talked to @ahocevar about this, this is a GeoWebCache layer, you cannot style it. In the current code base the style tool does not enable at all for this layer, so that's the expected behaviour.
