### ISSUE TITLE
add client-side sniffing of zip files

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#700]
We encourage (and require for raster mosaic, ATM.) zip file upload - we should add as much validation on the client as possible to prevent painful failed uploads.

Validation can include:
- [x] scanning for subdirectories (not well supported ATM)
- [x] scanning for file types and showing the appropriate message
- [x] scanning for multiple 'main' files (also not well supported)
- [ ] scanning mosaic names
- [ ] checking for csv headers

Ideally, the client would use importer services for this (e.g. is this list of files supported?) but for now, the checks can occur on the client.

This should degrade gracefully for clients that don't support the relevant APIs.

**Comment by ischneider** [comment]
The code lives here but is merged into integration:
https://github.com/opengeo/mapstory/tree/iss-700-client-side-zip

This is deployed to dev and ready to test - on a modern browser, the sniffing should occur as soon as a file is selected or dropped.

The checked functionality (in the initial report) is implemented.

**Comment by cholmes** [comment]
Awesome work Ian, this is _huge_ for usability.

I tried the first three and they all worked. I think the messages could potentially be a bit improved, will think on it.

Can you report in that little window what is scanned? Like it could be nice to say the names of the files that are problematic, or perhaps even list them out if the user clicks. That could make the messages even more informative. Like 'This file contains dams.shp and rivers.shp. Please upload only one file type at a time'.

**Comment by cholmes** [comment]
So it is possible to list the problematic files? I will attempt to come up
with some improved messages, but need to know if I can use the filenames in
the message.

**Comment by cholmes** [comment]
Looking at the source code I think it'd be a bit of a pain to get all the specific messages I'd like (things like 'we found roads.shp and rivers.shp - right now we only support uploading one at a time'). But I think this could be enhanced a lot by just having a 'list files in zip' line below the message that just lists what the zip sniffer found. I think many people won't know exactly what is in their zip, so this could show them. They should click on the 'list files in zip' to expand it out (maybe with like a + sign next to it), and then can just see what the files are.

As for messages, just a few tweaks:

'Please upload only one type of file at a time' -> 'Your zip appears to have more than one relevant geospatial format. MapStory currently supports upload of one StoryLayer at a time, so please break it up in to separate zip files'

'Please do not include any directories' -> 'MapStory does not currently support directories in zip files. Please place all relevant geospatial files at the top level of your zip archive and remove all directories'

'The zip file does not appear to contain any recognized files' -> 'MapStory could not recognize any currently supported file formats in your zip file. Please convert your data to one of formats listed above.'

At some later point we can work towards more custom error messages using the file names they uploaded.

**Comment by ischneider** [comment]
Deployed to dev. Added message rewording and the listing (recognized files in bold).

**Comment by cholmes** [comment]
Looks good. Marking ready for deploy. We should get tickets for the two little issues in the task list not completed though.

**Comment by ischneider** [comment]
Need to filter __MACOSX/ directories as these are ignored in geoserver but cause the client to complain about duplicate shapefiles.

**Comment by ischneider** [comment]
Deployed __MACOSX fix to dev

**Comment by cholmes** [comment]
@ischneider I just tried this on production and it didn't seem to work. I'm pretty sure the two zips I tried I had tested on dev and had client side warnings. But on prod they didn't complain till after upload.

**Comment by ischneider** [comment]
Thanks for testing - the branch wasn't merged. Deployed to production.

**Comment by cholmes** [comment]
confirmed on prod. Thanks Ian.
