### ISSUE TITLE
Raster Upload EPSG Code

### ISSUE THREAD

**Issue by SeanEmerson** [MapStory/mapstory-meta#701]
I was uploading a raster image and encountered this screen.  Unsure what an EPSG code is.  
![mapstory_issue](https://f.cloud.github.com/assets/4571377/585354/16f95228-c936-11e2-9206-6dfdbae76970.jpg)

**Comment by cholmes** [comment]
Did you try going to http://prj2epsg.org/search and copying and pasting
that text box in? That should hopefully give you a number to enter there.

**Comment by SeanEmerson** [comment]
I just uploaded them on the regular site without issue, thanks.

**Comment by cholmes** [comment]
So you didn't get that dialog at all? Interesting.

**Comment by SeanEmerson** [comment]
Yes, I got that screen three separate times on the dev site but I encountered no issues when I tried uploading on the normal one. 

----- Original Message -----

**Comment by cholmes** [comment]
Hrmm... Thanks Sean, that's helpful.

@ischneider - obviously it's better that production is working better. But
hopefully there's not some change that will get pushed? Seems unlikely,
maybe dev doesn't have as full of an epsg database.
