### ISSUE TITLE
Kill save/cancel in time settings.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#702]
In our time settings we have these superfluous 'save' and 'cancel' buttons. See:

![screen shot 2013-05-30 at 11 26 43 am](https://f.cloud.github.com/assets/407017/585751/7cffd6b2-c93d-11e2-9f36-44730bc60df7.png)

I say superfluous because changing the settings on that updates the map instantly. Save does nothing. And cancel is even worse, it doesn't revert. The one other place I think we have save/cancel is styling, but that appears to revert properly. So easiest thing is to just remove the save/cancel from the time settings.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/688022eea94c1fa8e2ea0f8c33a47363959c270f pulled in with https://github.com/opengeo/geonode/commit/a313cecc6803ed64f06648a7a9649c48d6a84f28

**Comment by cholmes** [comment]
Hey, I think this lead to some sizing error, as there's now a scrollbar on all of them that feels entirely unnecessary and is taking up space:

![screen shot 2013-06-07 at 10 31 53 am](https://f.cloud.github.com/assets/407017/624212/2b11c822-cf7f-11e2-9a70-bcc45f0861e9.png)

Could you get rid of it?

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/2152306963de6029f7d7ef31f872e93796753321 pulled in with https://github.com/opengeo/geonode/commit/39d96f6337618fbaf26481948da5ba410a98c65a

**Comment by bartvde** [comment]
deployed to dev

**Comment by cholmes** [comment]
ready for deployment.

**Comment by cholmes** [comment]
confirmed on prod
