### ISSUE TITLE
Remove 'map properties' button from top panel and remove top panel.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#703]
Ivan now has this stuff in the 'save map' dialog, and he meant to remove it from the top, but it popped back in. Getting rid of this should let us remove the top panel.

See 
![screen shot 2013-05-30 at 12 08 27 pm](https://f.cloud.github.com/assets/407017/586029/600a8754-c943-11e2-85e2-83bf1f187d39.png)

The lone button right above the zoom control

**Comment by cholmes** [comment]
Hrm, it actually doesn't seem to show up in all maps. http://mapstory.dev.opengeo.org/maps/159/view/ doesn't have it. http://mapstory.dev.opengeo.org/maps/239/view/ does. http://mapstory.dev.opengeo.org/maps/133/view/ does. Guess it needs some debugging to figure out why it shows up. If I have time I will try to help out.

**Comment by bartvde** [comment]
okay so the tool has been saved into some of the maps so basically we would need to remove them in the map JSON to get rid of them.

```
{"wrapDateLine": false, "ptype": "gxp_mapproperties", "backgroundColor": "#454238", "numZoomLevels": 22}
```

@ischneider / @iwillig another migration task / script ?

Alternatively I could hide the toolbar with css, but I'd rather remove the tool from the map JSON.

**Comment by ischneider** [comment]
I can confirm that removing a tool of ptype="gxp_mapproperties" appears to resolve the top button issue. Will test on dev shortly.

**Comment by ischneider** [comment]
This has been run on dev. There were 59 maps affected. The few I tested appeared to have worked.

**Comment by cholmes** [comment]
Looks great, thanks Ian.

**Comment by cholmes** [comment]
Looks good on prod, though I'm not sure if I tested the right maps to confirm the migration
