### ISSUE TITLE
Remove 'number of zoom levels' from the properties / save map dialog

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#704]
The 'number of zoom levels' property only works in the map composer mode, and doesn't do anything from what I can tell in the main map pages. I don't think it works very well either, and that most people don't need to use it. It only makes some sense for full screen maps, for maps at higher scales you would want the zoom levels around the default. So I think it needs more work if users really want it. May make sense to think about for xyt frame stuff. But for now let's just remove it. It's in the 'save map' dialog and in the 'map properties'. The latter should go away with #703 

![screen shot 2013-05-30 at 12 12 13 pm](https://f.cloud.github.com/assets/407017/586060/0e3f6ea2-c944-11e2-9b28-4545e63538fb.png)

**Comment by bartvde** [comment]
done https://github.com/opengeo/geonode/commit/02b60d902815f70432277faf10c03452ad67499a

**Comment by cholmes** [comment]
Thanks, looks great.

**Comment by cholmes** [comment]
confirmed on prod
