### ISSUE TITLE
hit count error on map 136

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#705]
http://mapstory.dev.opengeo.org/maps/136/ gives me django errors: 

get() returned more than one HitCount -- it returned 2! Lookup parameters were {'object_pk': 136, 'content_type': <ContentType: map>}

![screen shot 2013-05-30 at 3 12 44 pm](https://f.cloud.github.com/assets/407017/587057/006b1b28-c95d-11e2-8a26-ed03579cbd60.png)

Haven't seen it anywhere else, but hopefully it's an easy fix

**Comment by ischneider** [comment]
Not sure how this duplicate entry got there but I've seen it before one time. I deleted the superfluous entry. Closing for now.
