### ISSUE TITLE
Change 'edit existing feature' icon and tooltip

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#707]
Rogue has done something Tucker likes, and I agree it makes decent sense. They don't have a specific 'getfeatureinfo' button separate from the 'modify existing feature'. In our current set ups those return more or less the same thing, though modify also gives you an 'edit' button. (I think the one other difference is getfeatureinfo will get info on all the features on all layers at that spot, modify just the active layer). 

Ivan got rid of the get feature info in the new buttons. I had wanted it back. But I think a better route is to just rebrand it. Put the 'info' icon on it, and have the tooltip say 'select feature'.

**Comment by bartvde** [comment]
@cholmes not sure I'm understanding what needs to be done here. Also since the edit existing feature function is currently not working. So you just want to change its icon and tooltip?

**Comment by cholmes** [comment]
Yeah, we probably should fix #706 first. I made that one when I was working to describe this one. Though I guess could switch this when that one is in progress.

But yeah, it comes down to changing icon and tooltip. Icon should change to the old getfeatureinfo blue circle around the 'i'. And tooltip to 'select feature'. See like http://geoserver.rogue.lmnsolutions.com/maps/38/view Their 'i' button, is actually a modify feature. Could also use their 'i', but it's probably too big. We'll get better icons from Tucker.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/fd6fa3eba2634b3be84b5b587c21da8fd8163d7c

**Comment by bartvde** [comment]
deployed to dev

**Comment by cholmes** [comment]
Looks good, though it doesn't seem to give any indication that it's 'down' - like you're in select mode. But let's wait till #706

**Comment by cholmes** [comment]
@bartvde - could you look in to the 'down' indication? On production hitting the info button (or the modify feature button for that matter) turns to orange when it's 'active'. Like when using the screen will yield that action. On dev right now there's no indication that it's active. If you hit it once and then do something on the screen it will work, but it's quite confusing as to whether it will work. Can we just give some indication that it will work?

Would be really good to get this before the release on tuesday.

**Comment by bartvde** [comment]
looking at this now

**Comment by bartvde** [comment]
@cholmes it seems select feature is also sometimes disabled, so it doesn't even show orange on hover, but this is separate to what you are seeing right? Your remark is about the pressed state?

**Comment by cholmes** [comment]
Yeah, my remark is about the pressed state.

It's disabled when you don't have a layer selected, or are you seeing it
disabled more than that?

**Comment by bartvde** [comment]
yeah it's because of some css in temporal_controls.css

**Comment by bartvde** [comment]
should be fixed with https://github.com/MapStory/mapstory/commit/5b6a48d6094c0ac65b45447530c2d03b948c861b

**Comment by bartvde** [comment]
@ischneider since dev server is on integration, I'm not sure how to deploy this to dev, any chance you could deploy this small change to dev? TIA.

**Comment by ischneider** [comment]
@bartvde integration exists just to let long-lived feature branches get to testing. I'll merge master in and deploy.

**Comment by ischneider** [comment]
Deployed - had a little struggle with an imaginary problem.

**Comment by cholmes** [comment]
Looks good.

**Comment by cholmes** [comment]
Confirmed on prod.
