### ISSUE TITLE
StoryLayer Page sharing problems 

### ISSUE THREAD

**Issue by SeanEmerson** [MapStory/mapstory-meta#708]
When I tweeted a StoryLayer, the link in the tweet does not work, only leads to this page 
![not found](https://f.cloud.github.com/assets/4571377/587334/8581bf32-c963-11e2-988d-927f6803e773.jpg)

**Comment by cholmes** [comment]
What storylayer page did you share it from? And which share button did you use?

**Comment by ischneider** [comment]
Confirmed - a fix to this that was attached to twitter card functionality never got pulled to production. Will address.

**Comment by ischneider** [comment]
Resolved and deployed to production.

**Comment by ischneider** [comment]
@SeanEmerson can you verify this is fixed?

**Comment by SeanEmerson** [comment]
It is fixed I tweeted a StoryLayer and the link worked-thanks!
