### ISSUE TITLE
Playback controls not responsive

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#71]
The playback controls on the demo site seem kinda flaky wrt. pausing, looping, etc.   Here's Alyssa's report:

> once you stop timeline can't restart it. 
> 
> (if press continuos playback, you can restart it.)
> 
> can't stop the animation once continuos playback is turned on.  i expect that even if continuous playback is on, one can still stop the animation at any frame.

**Comment by mpriour** [comment]
Some of this has been addressed already, other parts of it will be addressed in #112
