### ISSUE TITLE
Few labels showing up

### ISSUE THREAD

**Issue by BetsyEmmons** [MapStory/mapstory-meta#711]
I added labels to a MapStory but most are not showing up. Chicago, Philadelphia, and Washington always appear, but others do not have a label. Each point has location data that should be labeled. 

http://mapstory.org/maps/711/ 

I know labels are being worked on, but I just wanted to let you know!

Thanks!!

**Comment by cholmes** [comment]
We actually have some label options that should help this, I'll try them and write them up, and hopefully we can add to the docs. Have had this question from another person as well.

**Comment by emloux** [comment]
@BetsyEmmons Can you send this to http://forum.mapstory.org/questions/?

**Comment by cholmes** [comment]
Closing this, it ended up as a number of different tickets: #794 #795 #796
