### ISSUE TITLE
Anyone can change the default SLD of a layer

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#715]
I'm surprised no users have reported this yet, but I guess it's not yet a common workflow to make a mapstory from someone else's layer. 

But if I create a new mapstory from a storylayer I can chance the default style and it changes it for all time. On the layer, and on any other mapstory that uses the default style.

I can use 'duplicate style' to make my own, but that's not the default.

The long term improvement would be to have a security model around styles, to say who has permission to change them.

A short term improvement would probably be to make more duplicates of the default style automatically. Like if a user copies a map or makes a new mapstory from a layer then when they edit the style it creates a duplicate one.

**Comment by cholmes** [comment]
Finally got a user hit this. I'm actually surprised it wasn't discovered earlier. Assigning to myself, since I can do some thinking about the duplicate behavior.

**Comment by ischneider** [comment]
The actual communication goes through geonode (a security proxy since we talk to geoserver's REST API) so we could enforce things here as well as on the client without adding anything to geoserver. 

The challenge is coming up with the rules for who owns the style, when to copy, implementing a django model to track more complex permissions (if desired), etc.

**Comment by cholmes** [comment]
Ah cool, didn't realize we could do stuff through GeoNode. That's great.

I do want to see if we can do some nice stuff on the client side. Like just duplicating more. Though I guess a shorter term fix would be for the server to just say 'you're trying to edit someone else's style, please hit 'duplicate' to create your own'.

But yeah, I'll put some brainpower in to the rules.

**Comment by cholmes** [comment]
See #218 for some more info / thoughts on this.

**Comment by cholmes** [comment]
Duplicate of #218, closing
