### ISSUE TITLE
Thumbnail creation error

### ISSUE THREAD

**Issue by SeanEmerson** [MapStory/mapstory-meta#716]
I encountered this error when creating thumbnail for a StoryLayer on the regular site.

![500_error](https://f.cloud.github.com/assets/4571377/601645/4d1f75ce-cc85-11e2-8953-feec75900944.jpg)

**Comment by ischneider** [comment]
@SeanEmerson, please include the URL you are using in future reports. In this case, I received an automated email but this doesn't always happen.

The specific error is related to an invalid bufferedimage type - cannot duplicate regularly but it's possible it's related to transparency or black/white.

**Comment by ischneider** [comment]
The relevant stack trace portion:

> java.lang.IllegalArgumentException: Unknown image type 0
>        at java.awt.image.BufferedImage.<init>(BufferedImage.java:507)
>        at org.xhtmlrenderer.util.ImageUtil.createCompatibleBufferedImage(ImageUtil.java:108)
>        at org.xhtmlrenderer.util.ImageUtil.convertToBufferedImage(ImageUtil.java:245)
>        at org.xhtmlrenderer.util.ImageUtil$AbstractFastScaler.getScaledInstance(ImageUtil.java:300)
>        at org.xhtmlrenderer.util.ImageUtil.getScaledInstance(ImageUtil.java:173)
>        at org.xhtmlrenderer.util.ImageUtil.getScaledInstance(ImageUtil.java:203)
>        at org.xhtmlrenderer.swing.ImageResourceLoader.get(ImageResourceLoader.java:151)
>        at org.geoserver.printng.PrintUserAgentCallback$1.get(PrintUserAgentCallback.java:84)

**Comment by SeanEmerson** [comment]
I refreshed the page after the error and it created the thumbnail without issue.  I'll include the URL in the future, thanks.

**Comment by ischneider** [comment]
Closing for now. Please reopen if needed.

**Comment by ischneider** [comment]
Opening this as I've seen this error again. This appears related to scaling an image though the error is spurious and while I was able to duplicate once, I could not again (to find what format of image response causes the issue)

One solution might be to ensure that the image has an imageType != 0 at PrintUserAgentCallback.java:84
