### ISSUE TITLE
Don't default to current date when selecting annotation date.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#717]
When you create a new annotation and select a date it defaults to todays date. It would be much better since mapstory is about history to default to the date that the map is at at that moment.

**Comment by ischneider** [comment]
This has bugged me for a while... +eleventy-five

**Comment by cholmes** [comment]
Would be great if it would also use the same amount of significant time. Like if it's 1901 then it just sets it to 1901. If it's Sept 14, 1999 then it sets it to that, etc.

**Comment by bartvde** [comment]
this was done with https://github.com/bartvde/gxp/commit/008dbf43ab50d6a2bfc4dc5262cd4dc81fe94b8d and https://github.com/opengeo/geonode/commit/5b79ac91fabddff46f87a737d78cc4958853792d#L0R95 not yet deployed on dev

**Comment by cholmes** [comment]
Awesome! A great improvement.
