### ISSUE TITLE
Remove twitter as a login option or force email

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#718]
We want to always get a user's email address, but twitter doesn't provide this, see https://dev.twitter.com/discussions/4019

So we should either remove twitter as a login option (easy way), or else make a special screen for twitter login that pops up and doesn't let a user complete their mapstory account until they put it in and successfully activate.

**Comment by drwelby** [comment]
Easy way is covered here: https://github.com/drwelby/mapstory/commit/23cbcb5669d5a444b01ae22a38efcdacd5f02862

If wanted we can deploy this to dev next week in DC.

**Comment by emloux** [comment]
Is this on dev @drwelby?

**Comment by drwelby** [comment]
I think so but it the social login doesn't show up in the front end yet so
you can't test it anyway.

**Comment by ischneider** [comment]
In order to test locally, you must change ENABLE_SOCIAL_LOGIN to True. This is enabled on dev. Not sure if Jeff ever figured out the provider pipeline but IIRC, it's supposed to allow for redirecting to support special cases like this.

@drwelby will follow up in email

**Comment by drwelby** [comment]
I've looked some more at this and #611 and here's a few considerations:

In the Social Auth module you can leave the process to get user input, such as an email address. I'm not sure how it works when you have to go through the whole email validation part. But it at least seems possible.

We could also just set the email address field to list of fields that are flagged as incomplete to the user. The catch here is that the email address would not be validated. There's no validation on this field once you're a user.

Or we just drop Twitter.

**Comment by ischneider** [comment]
I'd consider it a low priority, but if we 'leave' the process for twitter, we could leverage the account app to complete the registration.

For the moment, dropping Twitter seems appropriate to me given the additional effort.

**Comment by emloux** [comment]
Ready for deploy
