### ISSUE TITLE
Regression of formatting on user editing page

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#720]
I think this may be due to #461 But we used to have the page to edit your user profile be ordered and with appropriate sized text boxes. This is still the case on production. On dev though it looks like a dump of the model. See images below:

![screen shot 2013-06-03 at 9 48 16 pm](https://f.cloud.github.com/assets/407017/603204/27e23484-ccb9-11e2-9ee1-3e62560ce369.png)

The above is on mapstory.org, the below on dev:

![screen shot 2013-06-03 at 9 51 35 pm](https://f.cloud.github.com/assets/407017/603209/573af770-ccb9-11e2-8eef-a05aa1ae5015.png)

**Comment by ischneider** [comment]
Deployed fix to dev

**Comment by ischneider** [comment]
D'oh - sorry @drwelby, @cholmes  didn't notice the assignment

**Comment by cholmes** [comment]
No worries, there's a number of issues for @drwelby and he's not on contract yet, so happy for you to do it, especially for things that don't take you much time.

**Comment by cholmes** [comment]
Looks good @ischneider 

I'll close this. There's some more little work to do here, thanks for fixing this up though, takes us to same state as production.
