### ISSUE TITLE
Support Validation for Uploaded SLD

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#721]
A user is trying to upload an SLD and then adjust the opacity online, but he gets a number of failures when trying to edit it. 

![style-saving error](https://f.cloud.github.com/assets/407017/605239/86c63480-cd10-11e2-8dcd-34244f688ae6.png)

**Comment by cholmes** [comment]
I will try to reproduce, on prod and then on dev.

**Comment by cholmes** [comment]
Reproduced on dev. Well not exactly this user's error above, but the one he was having before. Go to http://mapstory.dev.opengeo.org/maps/new?layer=geonode:NYCaggregate and try to change the opacity of one of the styles.

**Comment by bartvde** [comment]
The client is just doing a simple PUT of an xml string to a Django resource (a bridge to GeoServer REST I presume), which responds with an internal server error (500), so I don't think this is client-side @cholmes 

@ischneider any ideas?

**Comment by adunetz** [comment]
Moved to Appomattox milestone.

**Comment by ischneider** [comment]
This is specific to the SLD. Unclear how it got this way (either the original SLD was off or the client messes things up), but there are filters that look like:

``` xml
<ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
    <ogc:And>          
        <ogc:PropertyIsEqualTo>
            <ogc:PropertyName/>
            <ogc:Literal>YES</ogc:Literal>
        </ogc:PropertyIsEqualTo>
        <ogc:PropertyIsEqualTo>
            <ogc:PropertyName/>
            <ogc:Literal>1</ogc:Literal>
        </ogc:PropertyIsEqualTo>
    </ogc:And>         
</ogc:Filter>
```

And the parser barfs out expecting a child element on the empty `PropertyName` elements.

**Comment by bartvde** [comment]
Is there a way to get the validation error back the client?

**Comment by ischneider** [comment]
First, we'd have to fix the parser to catch some actual error :) Then the question of whether the user would even want to know about the details has to be asked...

For uploaded SLDs, we should perhaps try to trigger rendering (or something that produces an error once exercised) to let the user know of an issue.

**Comment by jonpmarino** [comment]
@davisc not sure if this should be closed and moved or still worth having around.
