### ISSUE TITLE
Have watchdog communicate to django when geoserver is down

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#723]
When the watchdog detects geoserver is down, we could add an announcement that there is a problem and remove it upon restart.

**Comment by ischneider** [comment]
We also are detecting slow service in the watchdog so this could also trigger a warning.

**Comment by cholmes** [comment]
This sounds like a _really_ great improvement. +1

**Comment by cholmes** [comment]
Is this a big thing Ian? Or relatively easy? Can anyone other than you handle it?

**Comment by ischneider** [comment]
Relatively easy, deploying to dev for testing shortly

**Comment by ischneider** [comment]
Just deployed this to dev. Geoserver is not really down or having problems, just triggered the announcement.

**Comment by cholmes** [comment]
Could you change wording here? 'It' makes more sense when you are looking at a map directly:

Mapping Service Experiencing Heavy Traffic
Displaying maps, editing MapStories and uploading StoryLayers may not work properly, but should resume shortly. If this problem persists please let the administrators know.

**Comment by cholmes** [comment]
too hard to test on prod, just going to close, believing that it's ready.
