### ISSUE TITLE
client should handle geoserver downtime better

### ISSUE THREAD

**Issue by SeanEmerson** [MapStory/mapstory-meta#724]
The other interns and I have gotten this error several times today, here's the link to the page I was trying to access when I got it: 

http://mapstory.org/maps/725/

![transaction_error](https://f.cloud.github.com/assets/4571377/607118/e93e79da-cd3b-11e2-8314-4ab60dbebbcb.jpg)

**Comment by ischneider** [comment]
This was due to a number of geoserver-down events. See #723, too.

Changing title to capture true issue - ideally we would let the user know there are problems communicating w/ geoserver (in addition to the feature noted in #723 placing a static warning label on the page)

**Comment by cholmes** [comment]
I think simplest thing would just be a more informative generic message:

'The mapping server did not respond properly. It is likely temporarily down, but should be up soon. If this problem persists please let the administrators know'

**Comment by cholmes** [comment]
I guess we should try to report an error if we get anything more informative than the current error message. But that one is all I've ever seen, so it should at least let the user know what's going on. Or at least what most likely is going on. In time perhaps we can have more informative error messages, but let's just get a bit better for this ticket.

**Comment by bartvde** [comment]
The Details button should show the raw (Django) error.
I'll change the text to what @cholmes suggested

**Comment by bartvde** [comment]
Changed with https://github.com/opengeo/geonode/commit/de601a461047c8041de279b6eef1687af84f5924

**Comment by cholmes** [comment]
Commit looks good. Seems silly to do a real test since I don't have a local dev environment, so it'd be taking down the dev tomcat.

**Comment by cholmes** [comment]
Ah, actually just got it.
![screen shot 2013-06-07 at 7 44 57 am](https://f.cloud.github.com/assets/407017/623484/cef26f18-cf67-11e2-8449-25f28ae8bd29.png)

Could you change UT:Details to just Details?

**Comment by bartvde** [comment]
sure, yeah I needed to restart Tomcat to do the jsbuild :-(

**Comment by bartvde** [comment]
changed text for details button: https://github.com/opengeo/geonode/commit/162e2d2e1e184a29a16eabab004c149ba3ee98d4

Ideally this should be added to the Django dictionaries though I guess, but it also depends whether or not we ever expect a MapStory site to be in non-English.

**Comment by cholmes** [comment]
Need to take things down to confirm on production. So just closing, can reopen if I see it later and it didn't get deployed.
