### ISSUE TITLE
Split MapStory components across machines

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#725]
Afaik MapStory right now is all hosted on one box. In anticipation of future scalability improvements for a cluster of GeoServers it would be good to split it across different VM's. I think a DB server, a java (GeoServer+GWC) server and a Django (geonode/mapstory, etc) server makes sense. The java ones will likely be the ones that need to scale, and are most in need of an HA set up.

We can probably get away with a small vm for the django portion. Perhaps a bit bigger for the DB server, and the biggest should be the java server. Ideally we keep a good record of cpu usage (ok to pay a bit more on amazon for this if needed) so we can get the sizing between the three servers right. And eventually we hopefully have each tier auto scaling.

**Comment by ischneider** [comment]
Moving to Appomattox

**Comment by davisc** [comment]
This is complete. We now have a multi-server setup.
