### ISSUE TITLE
Install AskBot as a community help tool

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#726]
After trying OSQA we should now try out AskBot - https://askbot.com/

We should install it and replace user voice. Hopefully #725 should make this easier - would be great to use the same database server. The django front end could probably go on the django tier. Or it could probably live in its own micro instance.

**Comment by cholmes** [comment]
@jonpmarino - what do you want the name of the osqa thing to be? help.mapstory.org ? exchange.mapstory.org?

**Comment by jonpmarino** [comment]
Forum.mapstory.org perhaps?

Still envisioning a help page that lives on mapstory.org where we can describe the full architecture of support we have...manual, how to, etc. So don't want to confuse. Also hoping osqa gets used for more than pure technical support. So forum seems appropriate. 

Open to thoughts, though.

**Comment by cholmes** [comment]
Opened #728 to discuss what to do about help page mess.

**Comment by evanccnyc** [comment]
Should we just create a new amazon instance for this?

**Comment by cholmes** [comment]
Either way, was hoping to have you make the call on doing a new one or doing on our existing stuff. It would be good to get backups going, so I was thinking it could be good to do #725 and then have this share its database server and so backups would just happen from there. And then the django piece could go in its own ami, or on the front django tier. I've got no strong preference. Though keep it to a micro to start if we do its own ami. Maybe @ischneider has some thoughts.

**Comment by evanccnyc** [comment]
After looking at the documentation on this its easier to set this up as mysql and not postgres.  Thus probably will require a different backup setup.

**Comment by cholmes** [comment]
Interesting. The bitnami thing I used to trial on amazon used postgresql. And it looks like there's a guide on doing it with postgresql at http://wiki.osqa.net/display/docs/ubuntu+12.04%2C+django+1.3%2C+mod_wsgi%2C+virtual_env%2C+postgresql

But yeah, if it's easier for you with mysql and setting up backups with it that way then that's fine. I just thought backups may be easier with it all on one database, and would maybe save us a bit on costs with shared resources.

Looks like we can use south to migrate in the future if there's a good reason to. I'd say just put it in its own 'micro' instance under the mapstory aws account. And we can vertically scale if it starts getting overworked. 

And would be very good to have the openid / google/fb signon stuff enabled.

**Comment by evanccnyc** [comment]
Yeah we are going to have to redesign the infrastructure anyway for multiple servers (moving everything into vpc) so postgres isnt going to work in the short term.

Long term after the move it might work.

**Comment by cholmes** [comment]
Ok. That move to multiple servers is overall higher priority than this. But yeah, if we could do something quick on a micro and migrate to the new set up after it's solid then that'd be great.

**Comment by evanccnyc** [comment]
Okay setting this software up is making me wary of it. I am already (a 
few steps in) having to manually edit different parts of it to get it to 
even go through the install process. Is there any other options out 
there or do we want to use this one?

  -Evan

On 6/11/13 12:11 PM, Chris Holmes wrote:

> Ok. That move to multiple servers is overall higher priority than 
> this. But yeah, if we could do something quick on a micro and migrate 
> to the new set up after it's solid then that'd be great.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MapStory/mapstory/issues/726#issuecomment-19272256.

## 

Evan Carter
Senior Systems Administrator
OpenGeo | www.opengeo.org
Email: ecarter@opengeo.org
Phone/Fax: 917.388.9090

**Comment by cholmes** [comment]
Haven't done a super full evaluation. But this stuff is more done by saas, not open source. http://help.openstreetmap.org uses it, so we figured it must be decent.

**Comment by evanccnyc** [comment]
Okay...I'll continue on manually editing the source files to try and get 
it to work.

  -Evan

On 6/11/13 1:45 PM, Chris Holmes wrote:

> Haven't done a super full evaluation. But this stuff is more done by 
> saas, not open source. http://help.openstreetmap.org uses it, so we 
> figured it must be decent.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MapStory/mapstory/issues/726#issuecomment-19279837.

## 

Evan Carter
Senior Systems Administrator
OpenGeo | www.opengeo.org
Email: ecarter@opengeo.org
Phone/Fax: 917.388.9090

**Comment by cholmes** [comment]
Cool. Spend no more than another hour on it, if can't get it going by then call it and we can research other options.

**Comment by ischneider** [comment]
@evanccopengeo let me know if you'd like any assistance

**Comment by evanccnyc** [comment]
I got it installed but the admin interface seems busted and cant seem to 
find an easy solution for it. I also checked when they last released 
this software, it was in 2011. So is there any other options out there?

  -Evan

On 6/11/13 1:47 PM, Chris Holmes wrote:

> Cool. Spend no more than another hour on it, if can't get it going by 
> then call it and we can research other options.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MapStory/mapstory/issues/726#issuecomment-19279988.

## 

Evan Carter
Senior Systems Administrator
OpenGeo | www.opengeo.org
Email: ecarter@opengeo.org
Phone/Fax: 917.388.9090

**Comment by jonpmarino** [comment]
Were looking at alternatives...

On Tue, Jun 11, 2013 at 3:26 PM, evanccopengeo notifications@github.comwrote:

> I got it installed but the admin interface seems busted and cant seem to
> find an easy solution for it. I also checked when they last released
> this software, it was in 2011. So is there any other options out there?
> 
> -Evan
> 
> On 6/11/13 1:47 PM, Chris Holmes wrote:
> 
> > Cool. Spend no more than another hour on it, if can't get it going by
> > then call it and we can research other options.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MapStory/mapstory/issues/726#issuecomment-19279988.
> 
> ## 
> 
> Evan Carter
> Senior Systems Administrator
> OpenGeo | www.opengeo.org
> Email: ecarter@opengeo.org
> Phone/Fax: 917.388.9090
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/MapStory/mapstory/issues/726#issuecomment-19286289
> .

## 

Jonathan Parnell Marino

@jonpmarino
www.mapstory.org
(815) 222 9088

**Comment by cholmes** [comment]
There's a bunch listed at http://meta.stackoverflow.com/questions/2267/stack-overflow-clones

Looks like askbot may be a fork of osqa. Evan, if http://askbot.org/doc/install.html is easy to do give that a whirl. If not then we'll find an option that meets our needs and is hopefully easier to install.

Thanks for investigating / trying @evanccopengeo , sorry for not vetting it more, the openstreetmap use of it seemed like a good enough endorsement.

**Comment by evanccnyc** [comment]
Ill check out askbot. It looks better documented already.

  -Evan

On 6/11/13 3:33 PM, Chris Holmes wrote:

> There's a bunch listed at 
> http://meta.stackoverflow.com/questions/2267/stack-overflow-clones
> 
> Looks like askbot may be a fork of osqa. Evan, if 
> http://askbot.org/doc/install.html is easy to do give that a whirl. If 
> not then we'll find an option that meets our needs and is hopefully 
> easier to install.
> 
> Thanks for investigating / trying @evanccopengeo 
> https://github.com/evanccopengeo , sorry for not vetting it more, 
> the openstreetmap use of it seemed like a good enough endorsement.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/MapStory/mapstory/issues/726#issuecomment-19286738.

## 

Evan Carter
Senior Systems Administrator
OpenGeo | www.opengeo.org
Email: ecarter@opengeo.org
Phone/Fax: 917.388.9090

**Comment by jonpmarino** [comment]
Shapado looks good as well...

On Tue, Jun 11, 2013 at 3:39 PM, evanccopengeo notifications@github.comwrote:

> Ill check out askbot. It looks better documented already.
> 
> -Evan
> 
> On 6/11/13 3:33 PM, Chris Holmes wrote:
> 
> > There's a bunch listed at
> > http://meta.stackoverflow.com/questions/2267/stack-overflow-clones
> > 
> > Looks like askbot may be a fork of osqa. Evan, if
> > http://askbot.org/doc/install.html is easy to do give that a whirl. If
> > not then we'll find an option that meets our needs and is hopefully
> > easier to install.
> > 
> > Thanks for investigating / trying @evanccopengeo
> > https://github.com/evanccopengeo , sorry for not vetting it more,
> > the openstreetmap use of it seemed like a good enough endorsement.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/MapStory/mapstory/issues/726#issuecomment-19286738.
> 
> ## 
> 
> Evan Carter
> Senior Systems Administrator
> OpenGeo | www.opengeo.org
> Email: ecarter@opengeo.org
> Phone/Fax: 917.388.9090
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/MapStory/mapstory/issues/726#issuecomment-19287066
> .

## 

Jonathan Parnell Marino

@jonpmarino
www.mapstory.org
(815) 222 9088

**Comment by cholmes** [comment]
Let's try askbot first, it'll have a more familiar admin interface.

**Comment by cholmes** [comment]
And also has more potential to integrate with activity feeds on mapstory at some point.

**Comment by ischneider** [comment]
We just need oauth integration for this now. Don't think we want to encourage folks to start using it until then.
Moving to Appomattox.

**Comment by emloux** [comment]
@ischneider and @evanccopengeo is there a site I can check out for this?

**Comment by cholmes** [comment]
I think it's fine for people to start using before we have oauth integration. It's a small group of people, and we'll just tell them to get new accounts to be active on there once we get mapstory login integration.
