### ISSUE TITLE
Same login for MapStory.org and help.mapstory.org

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#727]
After #726 is done we need to have ways in to the system from MapStory.

---

![image](https://f.cloud.github.com/assets/2131145/1175556/ffa9169e-215a-11e3-8d72-1b2cfabfea11.png)

Note: page contents should be centered in browser window

**Text**
See comments below...

**Logo**
![727-logo](https://f.cloud.github.com/assets/2131145/1175548/e0a9704a-215a-11e3-8446-6304de90502c.gif)

**Button Details**
`primary` is the main one and matches the darker red button on MapStory.org. `secondary` is the lighter, grey one.  Take what details you need from the code below.

```
  button { padding: 8px 12px; border: none; border-radius: 3px; }
  button.primary { background: #9E2F1E; color: #fff; margin-right: 15px; }
  button.primary:hover { background: #842e1a;  }

  button.secondary { background: #e1e1e1; color: #4e4e4e; }
  button.secondary:hover { background: #d1d1d1; }
```

**Comment by cholmes** [comment]
Users should be able to login to mapstory.org and not have to login again on help.mapstory.org Probably some oauth or openid thing. Any way to achieve this is fine.

**Comment by jonpmarino** [comment]
@drwelby does this look doable?

**Comment by ischneider** [comment]
@drwelby I attempted adding a oauth provider to askbot but it wasn't working as advertised.

Another approach might be to write an authentication backend that uses the ajax endpoints on production.
https://docs.djangoproject.com/en/1.4/topics/auth/#writing-an-authentication-backend

Either way, it's probably worth mucking around w/ a VM as my attempts on the live site were breaking it.

**Comment by drwelby** [comment]
I finally have this working in my test VM. It's a little ugly, though. @sshyu can you mock up something a little nicer?
![screen shot 2013-09-19 at 10 25 10 am](https://f.cloud.github.com/assets/152875/1174492/5dbe3eca-2148-11e3-838a-66f68945c1ee.png)

**Comment by sshyu** [comment]
Sure @drwelby - can I get a bit more info on this?  e.g., when does the user see this?  What happens when the user clicks "Cancel" or "Authorize"?

**Comment by drwelby** [comment]
Flow is like this:

1) In Askbot, user clicks "Login with MapStory" icon.
2) If user isn't currently logged in to MapStory, they're first taken to the MapStory login page to log in.
3) They see the authorization page shown above.
4) If they click "Authorize", they are logged into Askbot and redirected to the main Askbot page. 
5) If they click "Cancel", they are just redirected to the main Askbot page.

**Comment by sshyu** [comment]
Thanks @drwelby.  In this particular case, it's AskBot asking to access the user's MapStory account data to authenticate, right?  

(Want to clarify the wording so the user knows what's going on.)

**Comment by drwelby** [comment]
Correct, it will access the user's MapStory account to authenticate, as well as grab the user's name, username, email address, and other details needed to create the Askbot account.

**Comment by sshyu** [comment]
Cool, thanks!

**Comment by sshyu** [comment]
@drwelby: I updated the main ticket body above with a mockup and some details.  Let me know if you have any questions.  As for text:

> help.mapstory.org (powered by AskBot) would like to access the following information:
> - your MapStory user profile (including username and email address)

**Comment by drwelby** [comment]
Is that button styling already in our css? I can access the Bootstrap .btn and .btn-primary but .btn-primary is blue. Are we planning to update bootstrap_custom.css with these colors at some point?

**Comment by sshyu** [comment]
@drwelby - it is, though as an anchor not a button element.  (Though my styling might be slightly different, please use what's already on the site for consistency.)  The Cancel one is NOT on the site already as far as I know.  

Example is on the mapstory homepage (the lighter one at left -- "Search Storylayers"):
![image](https://f.cloud.github.com/assets/2131145/1176445/a7318210-216b-11e3-84d1-60109f517c54.png)

**Comment by drwelby** [comment]
Here's what I've got - I just put the button css in a style tag for now.
![screen shot 2013-09-19 at 2 53 23 pm](https://f.cloud.github.com/assets/152875/1176577/07c07b0c-216e-11e3-9117-9cb036f33615.png)

**Comment by sshyu** [comment]
Looks good @drwelby!  A couple things: can we make the background of the page content area (where the logo, text, buttons are) white?  And, could just be the screenshot/my monitor, but the text next to the bullet looks smaller than the text above it--the text size, color, etc. should match the "help.mapstory.org" line.

**Comment by drwelby** [comment]
Good eye - the site css had LI smaller than P. I got ride of all of the default css and just styled everything. H2 is 22px, body text is 15px. 
![screen shot 2013-09-19 at 3 39 53 pm](https://f.cloud.github.com/assets/152875/1176911/19beeb30-2174-11e3-9dd9-e416af571b00.png)

**Comment by sshyu** [comment]
Thanks!  Looks much better now.  Since the body text is a little bigger, can we bump the h2 to 26px maybe?  Think we're set after that :)

**Comment by jonpmarino** [comment]
@sshyu @drwelby nice!

**Comment by drwelby** [comment]
This is also ready for testing (technically it's already deployed)

**Comment by emloux** [comment]
Verified, closing
