### ISSUE TITLE
help/manual/howto consolidation and workflow

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#728]
Opening a new ticket for this, to start just to get your thoughts Jon. 

We'd like to get the help stuff better organized, and in a position where you and a vetted user community can improve it.

Curious on the way you see forward. What are the assets we have, and what should be the assets? I would image most everything linking to one page that goes out to different things. 

Right now I count at least:
- Howto - videos, most prominent link
- Help - text, kind of an overview, not that prominent, but linked
- Manual - text, most detailed. I think it is only linked to from specific places in the site?

I'd like it so you and your team can help with the manual. Likely using github against our repo directly (probably just you with direct rights). It's important that it maintain its links, so that other places in the site don't break.

**Comment by cholmes** [comment]
Thoughts from awhile ago from @bmmpxf

Hi all. I've been looking at the current state of the informational content on the MapStory site (docs, help, videos, etc.) and wanted to offer some suggestions. I'm sending this to the list after a discussion with Ian.

There appear to be four different pages that show relevant content (please let me know if I've missed one):

/about
- Accessible on the top toolbar
- Goes to the MapStory wiki

/how-to
- Accessible on the top toolbar
- Goes to a page with videos

/help
- Accessible from a very small link in the footer
- Goes to basic boilerplate information about MapStory

/manual
- Not directly linked from anywhere
- Goes to a page containing various topics regarding using MapStory

With all this in mind, my suggestions are:
- Build out the /manual page to include a full MapStory reference as well as tutorial
- Add /manual link to main toolbar
- Remove the /help page and copy any still-relevant content into /manual
- Rename /how-to to /videos (more explicit, less confusion with other pages)
- Add a new page: /faq containing, well, an FAQ (short answers + links to specific areas in the /manual)

I think this will help better organize the help content available on the MapStory site, and better guide users to the information they need.

**Comment by jonpmarino** [comment]
Ok. Really glad were moving on this. 

Under the current UI, here's my first thoughts on how this should work. In the medium term I think we need a home page redesign (and I have thoughts on that...basically want feel of change.org homepage) but know that is a later priority...and we do what we can now.

-general design principle is that we need a single home-base page for How To and everything needs to be linked together.

-I think its equally as important to have links to relevant "Help" info embedded at every step of the user experience as well...

Actions:
-Agreed we should remove "Help" in footer and rope any content there that isn't already in Manual to Manual.
-We should eliminate "About" in the header. We link to the MapStory Foundation in the footer anyway, so no need.
-We should eliminate Reflections/Storyboards as a header item. Will reference in how to...

THEN, we should use How-To as our homebase.

In How To, we need to amend page so we can have text, videos and links. Not just videos.

How-To will then have the following components:

-intro text
-Reference and link to Manual as a comprehensive repository of documentation with most detail if you want to read more.
-Reference and link to Wiki as a user-generated place to share documentation. We pull the best-of-the-best from users to display at mapstory.org
-Reference and link to forum.mapstory.org as a collaborative Q/A spot
-Reference and link to Storyboards as a place to get project type ideas and a sense of the storytelling process in general.
-Stream of videos and corresponding links to PDF tutorials (probably hosted on Scribd)...organized around the 4 A-B-C-D categories of what you can do with MapStory..."Adding StoryLayers, "Building MapStories", "Curating the Commons" and "Discovering Content".

Analogs to look at:
HistoryPin - http://www.historypin.com/how-to/
Change.org - http://www.change.org/guides

Just a first attempt...focused on easy doable do's under the current design.

**Comment by cholmes** [comment]
Marking this high priority, as it keeps slipping, and it'd be really good to sort out the community stuff. We're starting to spend too much time helping people when we need to 'teach people to fish' - let others build up more documentation, etc.

**Comment by emloux** [comment]
I think the work we've done with help.mapstory.org and the submenus on the homepage should cover this.
