### ISSUE TITLE
empty trailing rows in CSV may cause improper reading

### ISSUE THREAD

**Issue by BetsyEmmons** [MapStory/mapstory-meta#731]
MapStory isn't detecting latitude and longitude attributes within .csv file. Here's my spreadsheet:
![screen shot 2013-06-05 at 11 00 51 am](https://f.cloud.github.com/assets/4552719/612658/11d4a9e0-cdf1-11e2-9114-c6cbc05f7bf3.png)

Here's how I uploaded it:
![screen shot 2013-06-05 at 11 01 10 am](https://f.cloud.github.com/assets/4552719/612669/42f21468-cdf1-11e2-8986-81300c363f01.png)

This is the message I received:
![screen shot 2013-06-05 at 11 01 17 am](https://f.cloud.github.com/assets/4552719/612670/522ed664-cdf1-11e2-8c4e-b28db0d438fd.png)

Any help is appreciated! Thanks! Also, I was working on the development site.

**Comment by cholmes** [comment]
Could you try renaming to 'latitude' and 'longitude' and see if it works any better?

**Comment by BetsyEmmons** [comment]
Had that originally, changed it to lat and long. neither worked.

**Comment by ischneider** [comment]
In this case, the 6223nd entry is being read incorrectly as it contains a semi-colon. @BetsyEmmons, I would check the other data as well before trying again.

Until this is fixed, the message should note that it's possible the data is not being read correctly.

Updated title to reflect the true nature of the issue.

**Comment by cholmes** [comment]
Bumping this to a future milestone. Would be nice to auto detect such issues, but in the meantime hopefully people will google and find answers and we'll improve documentation and help generally.

**Comment by ischneider** [comment]
Updated again - upon further investigation, this was actually caused by empty rows at the end.

**Comment by BetsyEmmons** [comment]
thank you!

**Comment by ischneider** [comment]
see opengeo/geoserver-exts#13
