### ISSUE TITLE
upload view should inform user about geoserver being down

### ISSUE THREAD

**Issue by SeanEmerson** [MapStory/mapstory-meta#732]
Got this trying to upload shapefile on regular site

http://mapstory.org/data/upload/

![upload_error](https://f.cloud.github.com/assets/4571377/612886/16f7aefe-cdf6-11e2-9cba-560b005aa139.jpg)

**Comment by ischneider** [comment]
Changing the title to reflect the actual problem.

The best I can tell, geoserver was down during this upload. @SeanEmerson can you try again?

The uploader api and view should detect a 5xx status response and note that geoserver is having downtime.

**Comment by emloux** [comment]
@ischneider Is this deployed to production?

**Comment by ischneider** [comment]
Yes.

**Comment by emloux** [comment]
Ok, I'll close this ticket.
