### ISSUE TITLE
map/layer pages shouldn't fail when geoserver is down

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#733]
geoserver resources should be resolved in the view to allow better error trapping and reporting instead of a complete failure to render.

without this, #723 won't work on these pages

**Comment by ischneider** [comment]
Bumped up to Appomattox as geoserver will likely be down for some time during the upgrade process.

**Comment by ischneider** [comment]
Deployed to dev and ready for testing. Let's schedule a time to take geoserver down and see what things look like.

**Comment by emloux** [comment]
@ischneider- Will this be deployed in Appomattox?
