### ISSUE TITLE
fix class of uploader error

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#734]
Not sure how this happens, but the stack trace is:

> java.lang.ClassCastException: sun.proxy.$Proxy13 cannot be cast to org.geoserver.catalog.impl.LayerInfoImpl
>        at org.opengeo.data.importer.rest.ItemResource.handlePut(ItemResource.java:122)

It may be related to performing the same PUT twice.

**Comment by garnertb** [comment]
OBE.
