### ISSUE TITLE
Allow multiple StoryTellers to be 'authors' of the same StoryLayer or MapStory

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#735]
Each mapstory is owned by an individual owner. We should investigate enabling users to "add" other users to their mapstory as a co-author. MapStories would still show up in search and profile pages only for the single storyteller assigned, but when viewing the MapStory the viewer would see other storytellers assigned to the mapstory as co-authors. Similar to the way they see 'related mapstories'

**Comment by Coop56** [comment]
Moved to Jira, closing.
