### ISSUE TITLE
Integrate warper.mapstory.org and mapstory.org logins

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#737]
We want people to be able to login to mapstory and not make them sign up for accounts and login to the warper as well.
#736 is the ticket on oauth, but that may not be the only way to go for this.

**Comment by cholmes** [comment]
From Andrew Johnson (in turn from his developer):

I think the cleanest way to integrate warper with mapstory would be to have mapstory handle all the user data, and then tweak warper to login based on a cookie provided by mapstory. It would be a custom solution, but would require less development time than trying to get OAuth working or upgrading rails. Hopefully in the future Tim Waters will bump the project up to a more recent rails version making integration with third party sites easier.

**Comment by emloux** [comment]
Related to #787

**Comment by jonpmarino** [comment]
Completed!

**Comment by ischneider** [comment]
This _was_ completed but needs to be re-completed.

**Comment by jonpmarino** [comment]
Closing. Covered in Jira.
