### ISSUE TITLE
Intra-platform messaging

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#738]
**Entry Points**
- [ ] MapStory header: where it says "Welcome {{first_name last_name}}" in the header:
  - Reword: remove "welcome"
  - Add a message icon: this links to the user's inbox
  - When the user has messages, add a number to the left of the icon.  Clicking the number also takes the user to the inbox.  Make number bold.
  - Example with no messages and with messages: `Johnny Smith  {{icon}}`; `Johnny Smith  {{icon}} 2`
- [ ] MapStory and StoryLayer page: in the "About this StoryTeller" section, add a link to message this storyteller. below "Read more about this Storyteller".  Link takes user to a new message with the "To" field pre-populated with the StoryTeller.
  - Read more link: reword to "Read more >"
  - Message link: "{{icon}} Message"
  - Move links so they are underneath the blurb (to save space)
- [ ] StoryTeller Profile Page: add link below the profile photo: "{{icon}} Message"
- Icon: we can use icon-envelope from the [Bootstrap glyphicons](http://getbootstrap.com/2.3.2/base-css.html#icons).  Use the white one when on dark background.

**UI Details for Messaging**
- Use buttons for compose, reply, and delete (see below)
- Forms should match existing forms on MapStory (make sure labels are aligned to the left and/or top of fields)
- If not sure on something, just ask @sshyu

**Inbox**
![image](https://f.cloud.github.com/assets/2131145/1306949/ae292de6-31b7-11e3-96f1-46e92b52d022.png)

**Message View**
![image](https://f.cloud.github.com/assets/2131145/1306946/a4f33fdc-31b7-11e3-8ceb-ef7ed0d43846.png)

---

Enable users to send private messages to one another.

See https://github.com/MapStory/mapstory-roadmap/blob/master/items/messaging.md for more information, this should likely flesh out in to more issues when it gets scheduled.

**Comment by drwelby** [comment]
I have this implemented locally with https://github.com/arneb/django-messages and it should work for us - the next question is where is this going to be implemented in the UI? Will there be little "Send this user a message" links in the user profile? In their data/maps? @sshyu do you have any plans for this yet?

**Comment by jonpmarino** [comment]
@drwelby cool! @sshyu we can touch upon this tomorrow as part of https://github.com/MapStory/mapstory-roadmap/blob/master/items/storytellers.md

**Comment by emloux** [comment]
Moving to Cedar Creek

**Comment by sshyu** [comment]
@drwelby - where can we look at what the instance you've setup of django-messages?

I have a list of points where we need to integrate this into MapStory (profile pages, navigation, user profile page, etc.) but need to take a look to start figuring out details.

**Comment by sshyu** [comment]
Per MapStory meeting today, @drwelby will send screenshots of the messaging system to me.  I'll review and communicate further UI details.

**Comment by jonpmarino** [comment]
thanks @drwelby and @sshyu !

**Comment by drwelby** [comment]
There's some screenshots here: https://code.google.com/p/django-messages/wiki/Screenshots

It's really bare-bones, so it probably won't help much...

**Comment by jonpmarino** [comment]
@drwelby these look good I think!

**Comment by sshyu** [comment]
@ischneider, @drwelby: I've added a couple mockups to the ticket to show how the messages UI should look so that it matches the MapStory site.  In the interest of saving hours, I've done the two main views--I think it should be easy to extrapolate how the others should look based on these.  If you have any questions, just let me know.   When you have this up on MapStory, let me know, and I will review and writeup more detailed feedback.

Related note: from the screenshots, I obviously can't get an idea of how the interactions work (e.g., what happens when deleting, sending, etc.).  I'll have feedback on that when I can try it out on MapStory.

**Comment by drwelby** [comment]
@sshyu Here's a rough start, needs lots of minor tweaks.
![screen shot 2013-10-12 at 10 08 31 am](https://f.cloud.github.com/assets/152875/1320405/c8e221ea-3358-11e3-876c-3513b4f97c20.png)

@ischneider I'm using the simplesearch author endpoint for the autocomplete and it's working nice but it's probably going to require that we upgrade Bootstrap and jQuery.

**Comment by sshyu** [comment]
Thanks @drwelby -- great start!  Do you need me to provide any specific feedback at this point?  

For quick reference, some specs:
- Message table header: text `#666`, border color `#888`
- Message table body: border color `#ccc`
- Page subheader (e.g., 'Inbox'): `#333`

The page header (e.g., 'Messages') is normally `#F46817` which is the same as the link color, so this can be confusing.  @jonpmarino - are you open to changing this color so that these headers don't look like links to users?

**Comment by jonpmarino** [comment]
@sshyu yes, that makes sense. Your call!

**Comment by sshyu** [comment]
Cool @jonpmarino 

@drwelby - can you try making page headers on MapStory `#d24d27` instead of the current color?  (Only the ones that are orange--headers that are other colors should remain unchanged.)  That color is used for a header on the main page, and it should match the rest of the site as well.

**Comment by drwelby** [comment]
To follow up on the upgrades: The version of Bootstrap that we're using doesn't do AJAX autocomplete. The newest version of Bootstrap dropped autocomplete in favor of Twitter's typeahead.js, but that requires a newer version of jQuery. Then upgrading jQuery breaks the old version of Bootstrap or at least requires a compatibility layer. There might be a happy medium in upgrading to an older version of Bootstrap or we might be able to work something out with jQuery UI.

There's also the problem that the recipients need to be usernames, but we also have display names, so we would need to figure out how to handle them in the least confusing way possible. We have a search endpoint for usernames but it would have to handle display names too.

Or we could drop the 'send message' button, and limit the sending of messages to clicking a 'send this user a message' button on their profile, or replying to a received message.  That would eliminate the jQuery/Bootstrap upgrades and the changes to the search api.

**Comment by sshyu** [comment]
Thanks for the update @drwelby.  It's standard to be able to send a message to a recipient you specify (as opposed to having to find their profile and click a link in there)--we should keep that functionality.

@drwelby, @ischneider - what's our best option for handling the autocomplete given the above?  I understand it's challenging to upgrade given the set up we have.  Are there other plugins that may work?  

Re: endpoint: is it a big lift to have the endpoint also send over the display name?  AFAIK, the autocomplete/tokenizer plugins can usually handle this.

**Comment by ischneider** [comment]
I think I have a solution that will not involve updating. Almost there.

**Comment by ischneider** [comment]
@sshyu:

OK, I've managed to get this working with the fullname. I added the username in brackets since it's possible John Smith shows up a few times ;) This can taken out easily.

Next step to finish this off, @drwelby?

**Comment by sshyu** [comment]
@ischneider - awesome, thanks!  Having the user name to disambiguate is great.

**Comment by drwelby** [comment]
@ischneider I'm at the dairy making some repairs but I have my laptop so I'll push all the templates and css up to my 'messages' branch. They still need a little more CSS work but you can tie in your autocompleter.

The Django-messages app will need to be monkeypatched - it uses the old deprecated Django Messages framework.

**Comment by ischneider** [comment]
@drwelby thanks for the update. no worries/rush, the milk must get out :wrench:

I'm unclear on the django-messages issue. I have django-messages==0.4.4 installed and I'm not seeing any reference to the old django.contrib.messages ?

**Comment by drwelby** [comment]
I have 0.4.4 and I'm seeing in views.py:

request.user.message_set.create(message=_(u"Message successfully sent."))

instead of

messages.success(request, _(u'Message successfully sent.'))

**Comment by ischneider** [comment]
Gotcha. Since 0.4.4 was released 4 years ago, maybe time to hang with master ;)

I'll give this a shot and see what happens. Thanks for your efforts on this @drwelby

**Comment by ischneider** [comment]
deployed to dev

**Comment by jonpmarino** [comment]
@ischneider nice! looks to work. Do we need designs from @sshyu on where messages sit on a Storyteller profile page and where we put the "message this storyteller" button on MapStory and StoryLayer pages?

**Comment by sshyu** [comment]
@jonpmarino, @ischneider - those entry points to the messaging functionality are documented in the first part of the ticket above.  The styling should match the other links/buttons on those pages, but if you need specifics, just let me know, and I can add them.

**Comment by jonpmarino** [comment]
@sshyu great! looks good.

**Comment by ischneider** [comment]
@sshyu sorry, I missed those details on the entry points - should have actually read the ticket (and I'm late to this game)...

Anyway, a few notes about those:

> Move links so they are underneath the blurb (to save space)

I tried this but with longer blurbs it looks kinda funny (edit blurb in dev tools to make longer).

> Icon: we can use icon-envelope from the Bootstrap glyphicons. Use the white one when on dark background.

I colorized these a while ago so we have them in orange, too. Should we use these over the default?

Deployed more work to dev.

**Comment by jonpmarino** [comment]
@ischneider @sshyu looking great! What do you think about messages living on user's profile pages? Or at least a link on their profile page to their messages?

**Comment by sshyu** [comment]
@ischneider - thanks for all your work on this!  Link positioning: sounds good.  Icons: I think they're OK as-is for now--we have a lot of orange on the site already, so having a different color for the icon actually helps the link stand out.

@jonpmarino - I think it's best to keep them centralized in one place, unless there's a strong use case for having them elsewhere.  We could add a link on the profile page, but there's already a link at the top of every page, so I don't think we need to add an additional link.

**Comment by jonpmarino** [comment]
@sshyu Agreed...also better for keeping it simple!

Then, I still think it would be nice to have a simple link, just as a reminder to users that the message function is there. And, it makes the profile a comprehensive place where all their actions can be taken.

Like - 
![grab00](https://f.cloud.github.com/assets/2573761/1352209/eabfc46e-3733-11e3-893a-3decbe31c6a0.jpg)

@ischneider question - on that profile...we have "notify me via email" with settings for 'never, once a day, and immediately'. What is this notification of? Do you know? And is it activated at all at this point? Just curious.

**Comment by DanielJDufour** [comment]
@ischneider @bartvde 
On a Storyteller page, I left-click "Message" under the Storyteller's picture.  It opens the window shown in the screenshot below, but the "To:" field is not filled in.  At the very least, the "To:" field should be filled in by the name of the person I'm messaging.  Users will be very confused if they don't see this.  Thanks and here's the screenshot:
![image](https://f.cloud.github.com/assets/4313463/1376993/79e6c210-3a9e-11e3-8227-4f006e713f35.png)

**Comment by ischneider** [comment]
Link added to profile page.

@DanielJDufour an typo on my part prevented auto-complete and filling in the field from the 'Message' link

Both deployed to dev

**Comment by DanielJDufour** [comment]
Footer should be at the bottom of the page:
![image](https://f.cloud.github.com/assets/4313463/1377697/0193f9f8-3aae-11e3-8c0c-57fbc965af1b.png)

**Comment by DanielJDufour** [comment]
Reply also needs to auto-populate "To:" field with whom you are replying to.
![image](https://f.cloud.github.com/assets/4313463/1377723/b0a6ae7c-3aae-11e3-92d3-5a54fa1801e5.png)

**Comment by drwelby** [comment]
@ischneider supposedly you can autopopulate the TO: field by adding it to the end of the url and the urlconf will pass it to the view, like /compose/username/

**Comment by ischneider** [comment]
@drwelby thanks! missed that.

@DanielJDufour updates pushed to dev

@sshyu I cleaned up the templates+css a bunch partly to support the request of filling up the empty space, partly to fix some duplicate html element id's and make things a bit simpler/DRY. Mind a double check on any layout issues?

**Comment by sshyu** [comment]
Thanks @ischneider for all the updates.  This is looking great!

A few other updates to what's there now to make it even easier to use:
- Navigation: make bottom padding of the `li` containing the "Send Message" button 10px (currently it's 5).
- Inbox
  - make padding of header cells match the padding of cells in the table body
  - change the table **header** border to `#888`
  - for the table **body**, change the borders to `#ccc`
  - delete icon: add a tool tip (using `title` attribute if we don't have a tooltip plugin already in use): "Delete message"
- Compose
  - Make the padding on the "to" and "subject" fields 4px (to match the textarea)
  - Add 10px space between "message" field label and the textarea on the right
  - Minor, but the "Send" button appears to have a border and text shadow that the other buttons don't have
- Message view
  - "Delete" button changes text color when hovering.  To be consistent with the other buttons, leave the text color the same.  
  - Delete button: change background color to `#ddd` and text to `#333`

**Comment by jonpmarino** [comment]
@drwelby @ischneider @sshyu - 2 changes to current messaging presence in user email inbox:
1. change from line from storyteller@mapstory.org to MapStory messages-noreply@mapstory.org
2. the subject line format should be: Jonathan Marino sent you a message: _subject content_

we want to get the MapStory username in there

**Comment by jonpmarino** [comment]
@ischneider I have messages-noreply@mapstory.org created on our gmail company page btw if needed

**Comment by ischneider** [comment]
@jonpmarino few comments:

> change from line from storyteller@mapstory.org to MapStory messages-noreply@mapstory.org

This can be done but it will change the from sender for other emailing, too. Let me know and I can change it.

> the subject line format should be: Jonathan Marino sent you a message: subject content

This will most likely not be able to happen this go around due to the way the messages app works.

**Comment by jonpmarino** [comment]
@ischneider ok, on 1. what other emailing cases might there be...what they are affects whether or not we should change.

on 2, i assume the difficult part is pulling the username. Could we change the subject convention to just say "You have a new message on MapStory"?

**Comment by ischneider** [comment]
For 1, I'm not too sure exactly which emails use this setting but the invite might be the only other one.

For 2, the way the app we're using is designed, it doesn't really provide a way to customize the subject in any way. So while it would be possible to work around this, it will take more effort. Getting the username is actually the easy part :)

**Comment by jonpmarino** [comment]
@ischneider got it.

For 1, ok - if the invite is the only other one we'd like to change it...maybe just noreply@mapstory.org? do you need me to create that account with gmail or do you maintain it from your end?

For 2, ok. we tried :)

**Comment by jonpmarino** [comment]
Can we change the spec so that "MapStory" shows up as from instead of norepy in inboxes? See image.
![test9](https://f.cloud.github.com/assets/2573761/1422522/c570ac4c-3ffc-11e3-8b96-596698f85c69.jpg)
