### ISSUE TITLE
Drag-n-drop filename matching too loose

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#74]
If you include a .shp.xml in the batch of files dragged and dropped into the upload page then that seems to be preferred over the actual .shp file.  Dragging in just the .shp afterward does not fix it, you have to refresh the page to clear out the form fields.

**Comment by dwins** [comment]
I think this one might already be fixed?

**Comment by ischneider** [comment]
I don't think yet - depending upon the order selected in the file chooser, one might get lucky. I've verified a fix and will commit shortly.
