### ISSUE TITLE
Trying to upload a CSV

### ISSUE THREAD

**Issue by SeanEmerson** [MapStory/mapstory-meta#740]
Got this error a few times while trying to upload csv files

http://mapstory.org/data/upload/

![csv_error](https://f.cloud.github.com/assets/4571377/619503/89ba0340-cecf-11e2-885c-bf45a6ebafee.jpg)

**Comment by cholmes** [comment]
Are they different csv files, or all the same csv file multiple times?

**Comment by SeanEmerson** [comment]
same multiple times, I got this file from a website and this was the name it gave the file, I'll make it shorter and see if it works

**Comment by ischneider** [comment]
Closing. Real cause is: #741
