### ISSUE TITLE
long file names cause failure on upload

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#741]
Due to an arbitrary, but reasonable, database column size limit of 64. The client should, at a minimum (and immediate step) detect this.

**Comment by ischneider** [comment]
Deployed to dev.

**Comment by cholmes** [comment]
Looks great, ready for prod. Loving all the client side checks, instant feedback is _so_ good.

**Comment by cholmes** [comment]
confirmed on prod
