### ISSUE TITLE
background color not applied to map view (only in composer)

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#744]
as reported by @cholmes 

http://mapstory.dev.opengeo.org/maps/239/view/ vs http://mapstory.dev.opengeo.org/maps/239/

The second one does not have the correct background colour on the map (set base map to none to see).

**Comment by bartvde** [comment]
maybe it's just a question of adding a hidden version of the mapstory toolbar in the viewer

**Comment by bartvde** [comment]
but it seems on saved maps background color is still controlled by the old gxp_mapproperties tool which has been saved into map config

@iwillig is this correct? No migration has been done to change this to the state of your new ms-toolbar tool?

**Comment by cholmes** [comment]
Even if there's not a migration done then shouldn't a new map save the tools properly and be able to change the background color? Because that's not happening.

**Comment by bartvde** [comment]
I can't even save a new map now see #743 but I agree that with a new map this should work okay. If that's enough, I can probably go for the solution I outlined before (an invisible mapstory toolbar in the viewer).

**Comment by cholmes** [comment]
Yeah, I had trouble saving a new map for a second too, but then it worked.

But yeah, with a new map it doesn't work. Works fine in the map composer mode (/view), but not in the smaller map page (full or small). It just seems to not pick it up.

**Comment by bartvde** [comment]
When I can save a map again, I can look into this. But it's really broken for me all the time unfortunately.

**Comment by iwillig** [comment]
Was this always broken? I feel like we would have noticed not being able to save maps before today.

**Comment by cholmes** [comment]
Bart, I get an error when I try to save it, but then it was actually saved.
And then I can go back and save it again without the error. So check to see
if a map actually got created with your error.

Will report the bug though.

**Comment by bartvde** [comment]
@cholmes ah right, did not check that. Indeed it shows up in the search results

**Comment by cholmes** [comment]
Yeah. It is only saving new maps, not existing ones. So I could see it not
being noticed for a few days, but not much longer than that.

**Comment by bartvde** [comment]
okay I'm close to fixing this, will continue early next week on this

**Comment by bartvde** [comment]
@iwillig I see now that the mapstory toolbar tool uses addOutput instead of addActions, so there is no way to suppress its output, I'll see if I can quickly rewrite it / restructure it to become a normal gxp tool.

**Comment by bartvde** [comment]
instead, I'll take the easy way out now, and add a boolean to suppress the output conditionally

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/4085b0fb8e22f3a3e9d4f1ad2d5ca8b8ad2c7cca

**Comment by bartvde** [comment]
deployed to dev

**Comment by cholmes** [comment]
Confirmed, thanks.

**Comment by cholmes** [comment]
Looks good on prod
