### ISSUE TITLE
Full screen mode timeline should have thin panel

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#745]
Lots of great improvements in #687 But missed the combination of full screen mode, time line button, and thin panel. The full screen mode of the map page still has a thicker panel. Since the timeline button is now there we can change that to a thin panel, getting more map real estate.

**Comment by bartvde** [comment]
this should be an easy one to fix, will do it now

**Comment by bartvde** [comment]
see https://github.com/opengeo/geonode/commit/0fea615ea504d308e81d13f34b8bfbaaf59fa22a

**Comment by cholmes** [comment]
Looks great. But just noticed a related bug.
![screen shot 2013-06-07 at 7 50 25 am](https://f.cloud.github.com/assets/407017/623495/9257e398-cf68-11e2-9385-fda24a2d953c.png)

The timeline button goes black on mouse over and makes it very hard to see. Can you turn it orange instead of black? Then it's in line with the other buttons, and on most maps will be much more visible.

**Comment by bartvde** [comment]
sure I can change the text color easily

**Comment by bartvde** [comment]
see https://github.com/opengeo/geonode/commit/a14c7c9d5a565e4ac11f2ec2ee69894cc6d133b9

**Comment by cholmes** [comment]
Looks good on production
