### ISSUE TITLE
Have full screen mode cover orange bar

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#746]
Could we have the full screen mode go up higher? Like to the top of the orange bar on:
![mapstory-orange-bar](https://f.cloud.github.com/assets/407017/623702/ea9f0402-cf70-11e2-94c2-be11a9d76149.png)

We want to eventually slim down the top bar even more. But I'm hoping this could be a quick fix. No one needs the buttons that pop up on that bar in full screen mode, and it'd be great to get more map. Can we have the map just extend a bit higher and go over the all the orange?

**Comment by bartvde** [comment]
Implemented with https://github.com/opengeo/geonode/commit/a13426d08cc1285649642a8f655bd31492bcd243 will deploy later today

**Comment by cholmes** [comment]
Awesome. Let me know when dev is updated, I'll give it a whirl.

**Comment by bartvde** [comment]
deployed to dev

**Comment by cholmes** [comment]
Nice job. I may have some further tweaks, but will make another issue.

**Comment by jonpmarino** [comment]
Looks awesome!

On Mon, Jun 10, 2013 at 9:23 AM, Chris Holmes notifications@github.comwrote:

> Nice job. I may have some further tweaks, but will make another issue.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MapStory/mapstory/issues/746#issuecomment-19197997
> .

## 

Jonathan Parnell Marino

@jonpmarino
www.mapstory.org
(815) 222 9088

**Comment by cholmes** [comment]
confirmed on prod
