### ISSUE TITLE
Login is covered up in full screen mode

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#747]
When you hit 'login' in full screen mode you can only see 'username' field, and not the 'password' field:

![screen shot 2013-06-07 at 8 52 56 am](https://f.cloud.github.com/assets/407017/623726/d3417c76-cf71-11e2-8dc7-05508bc97fd7.png)

It should go above the map. Hopefully it's just a simple z-value thing, to have the login pop-up as far front as possible.

**Comment by bartvde** [comment]
I see this in the code by @iwillig 

```
    // prevent the thumb nail images from showing through in full
    // screen mode
    this.portal.el.setStyle({'z-index' : 1000});
```

1000 is the same value as the login form. I can change this to 999 but not sure if this would interfere with the thumbnail images.

How can I get the thumb nail images to show?

**Comment by bartvde** [comment]
okay I'm gonna change the value to 999

**Comment by bartvde** [comment]
deployed to dev

**Comment by cholmes** [comment]
Looks great, thanks.

**Comment by cholmes** [comment]
works on prod
