### ISSUE TITLE
Migrate GeoTools time extensions to 9.x

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#751]
We have some time functionality that was made for MapStory, and it hasn't been ported to GeoTools 9.x, needed for GeoServer 2.3.x. We need to upgrade to GeoServer 2.3.x to get the new importer for better mapstory uploading.

**Comment by ischneider** [comment]
Initial work completed. Basic testing seems to work.

https://github.com/ischneider/geotools/tree/postgis-xdate-udt-9.x

**Comment by adunetz** [comment]
Moved to Appomattox

**Comment by ischneider** [comment]
Completed - any specific related problems should probably get their own issue.
