### ISSUE TITLE
Use geoserver-geonode-ext as external from upstream

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#752]
MapStory's security module was custom coded against GeoServer 2.2.x. It needs to be updated to 2.3.x so we can upgrade GeoServer and get the new importer.

The original ticket was to update the mapstory-specific integration but that approach no longer is viable as noted below. Instead, use the upstream version as an external.

**Comment by ischneider** [comment]
The 2.2.x integration no longer works and will be abandoned. Instead we'll be pulling in our fork of geoserver-geonode-ext. Mostly this issue involves the build though a few changes were needed in the fork.

**Comment by adunetz** [comment]
Moved to Appomattox

**Comment by ischneider** [comment]
Partly blocked by GeoNode/geoserver-geonode-ext#8

**Comment by ischneider** [comment]
Present in the gs23 branch:
https://github.com/opengeo/geonode/tree/gs-23
