### ISSUE TITLE
MapStory running with GeoServer 2.3.x

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#753]
To get at new functionality for both scalability and uploader we need to have MapStory run on GeoServer 2.3.x. This depends on #752 and #751 

Once we get it up on dev we need to do lots of testing to be sure that there were no regressions in 2.3.x

**Comment by ischneider** [comment]
Besides some potential config migration issues, the big show stopper is a caps doc regression for WMS virtual services. We currently are making requests like this:

> http://localhost:8000/geoserver/geonode/British_Empire_Colonies0/wms?SERVICE=WMS&REQUEST=GetCapabilities&TILED=true&VERSION=1.1.1

This request will succeed if the user is not authenticated but will fail otherwise. Interestingly, the request works if 1.3.0 is specified or the version is omitted (implying a 1.3.0 response).

This appears to have been around for a while [1] and I can verify this on a fresh vanilla 2.3.2 install as well as 2.3.x. I'll dig in a little more and as I haven't found a JIRA issue, will create one.

While it would be possible to use 1.3, this might introduce other issues. @bartvde would we also have to migrate any stored config?

[1] http://osgeo-org.1560.x6.nabble.com/GetCapabilities-1-1-1-error-td5054416.html

**Comment by bartvde** [comment]
yeah I think the reason we use 1.1.1 in GXP is because the SLD WMS requests are not hooked up for WMS 1.3 in GeoServer

**Comment by ischneider** [comment]
For reference:

http://jira.codehaus.org/browse/GEOS-5844

**Comment by ischneider** [comment]
PR for 2.3.x: https://github.com/geoserver/geoserver/pull/248

Will begin work on deploying to dev next.

**Comment by adunetz** [comment]
Moved to Appomattox

**Comment by ischneider** [comment]
Deployed to dev. Have tested a number of things - only found one potential issue so far:

Initial call to /geoserver/wfs/WfsDispatcher can take a very long time (10-20 seconds) but subsequent calls are quick, hundreds of ms

Have not moved gwc data over so there may be some misses encountered

**Comment by jdeolive** [comment]
Out of curiosity how is this endpoint being exposed? It is a relic of the
1.7.x (pre dispatcher) days and has been deprecated for quite some time.

On Fri, Jul 5, 2013 at 2:20 PM, Ian Schneider notifications@github.comwrote:

> Deployed to dev. Have tested a number of things - only found one potential
> issue so far:
> 
> Initial call to /geoserver/wfs/WfsDispatcher can take a very long time
> (10-20 seconds) but subsequent calls are quick, hundreds of ms
> 
> Have not moved gwc data over so there may be some misses encountered
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MapStory/mapstory/issues/753#issuecomment-20537261
> .

## 

Justin Deoliveira
OpenGeo - http://opengeo.org
Enterprise support for open source geospatial.

**Comment by bartvde** [comment]
WMS DescribeLayer response:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE WMS_DescribeLayerResponse SYSTEM "http://mapstory.dev.opengeo.org:80/geoserver/schemas/wms/1.1.1/WMS_DescribeLayerResponse.dtd">
<WMS_DescribeLayerResponse version="1.1.1">
  <LayerDescription name="geonode:_map_157_annotations" wfs="http://mapstory.dev.opengeo.org:80/geoserver/wfs/WfsDispatcher?" owsURL="http://mapstory.dev.opengeo.org:80/geoserver/wfs/WfsDispatcher?" owsType="WFS">
    <Query typeName="geonode:_map_157_annotations"/>
  </LayerDescription>
</WMS_DescribeLayerResponse>

## 

Bart van den Eijnden
OpenGeo - http://opengeo.org
Expert service straight from the developers.

**Comment by jdeolive** [comment]
Right, i remember that. I could have swore there was a patch that changed
that recently but perhaps not. Good to know.

On Mon, Jul 8, 2013 at 8:23 AM, Bart van den Eijnden <
notifications@github.com> wrote:

> WMS DescribeLayer response:
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <!DOCTYPE WMS_DescribeLayerResponse SYSTEM "
> http://mapstory.dev.opengeo.org:80/geoserver/schemas/wms/1.1.1/WMS_DescribeLayerResponse.dtd">
> 
> <WMS_DescribeLayerResponse version="1.1.1">
> <LayerDescription name="geonode:_map_157_annotations" wfs="
> http://mapstory.dev.opengeo.org:80/geoserver/wfs/WfsDispatcher?" owsURL="
> http://mapstory.dev.opengeo.org:80/geoserver/wfs/WfsDispatcher?"
> owsType="WFS">
> <Query typeName="geonode:_map_157_annotations"/>
> </LayerDescription>
> </WMS_DescribeLayerResponse>
> 
> ## 
> 
> Bart van den Eijnden
> OpenGeo - http://opengeo.org
> Expert service straight from the developers.
> 
> On Jul 8, 2013, at 4:08 PM, Justin Deoliveira notifications@github.com
> wrote:
> 
> > Out of curiosity how is this endpoint being exposed? It is a relic of
> > the
> > 1.7.x (pre dispatcher) days and has been deprecated for quite some time.
> > 
> > On Fri, Jul 5, 2013 at 2:20 PM, Ian Schneider notifications@github.comwrote:
> > 
> > > Deployed to dev. Have tested a number of things - only found one
> > > potential
> > > issue so far:
> > > 
> > > Initial call to /geoserver/wfs/WfsDispatcher can take a very long time
> > > (10-20 seconds) but subsequent calls are quick, hundreds of ms
> > > 
> > > Have not moved gwc data over so there may be some misses encountered
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/MapStory/mapstory/issues/753#issuecomment-20537261>
> > > .
> > 
> > ## 
> > 
> > Justin Deoliveira
> > OpenGeo - http://opengeo.org
> > Enterprise support for open source geospatial.
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MapStory/mapstory/issues/753#issuecomment-20608690
> .

## 

Justin Deoliveira
OpenGeo - http://opengeo.org
Enterprise support for open source geospatial.

**Comment by ischneider** [comment]
Jira: https://jira.codehaus.org/browse/GEOS-5564

Here's a commit:
https://github.com/jdeolive/geoserver/commit/a0b46717d2c770301d338ea8840d44b24e9908ef

I couldn't find that commit or the GEOS ref in any of the geoserver branches - perhaps it never got merged?

**Comment by ischneider** [comment]
@jdeolive I cherry-picked your commit onto 2.3.x and it applied cleanly providing the correct response.

**Comment by cholmes** [comment]
Have been using this quite a lot, and have hit no problems. 

Marking ready for deploy, and if we hit any new individual issues we can make new tickets for them.

**Comment by emloux** [comment]
Moving to Bentonville

**Comment by ischneider** [comment]
Finally deployed to production. Closing. Report 2.3 related regressions separately.
