### ISSUE TITLE
Ability to 'add' raster to an existing raster storylayer

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#757]
The new uploader of #756 should include the ability to upload a raster and have it added to an existing storylayer image mosiac. This will enable integration with the warper and just a general increase in usability. Need to figure out the ways to present that workflow, involving @sshyu may be a good idea.

**Comment by jonpmarino** [comment]
@ischneider  FYI, when were ready for testing on this I have some new raster images just received that I'd like to add to http://mapstory.org/data/geonode:EV_Aerial_1971__ProjectRaste0

**Comment by ischneider** [comment]
OK. FYI, I don't have any short-term ETA for this - it will be some time still.

**Comment by jonpmarino** [comment]
ALL good.
