### ISSUE TITLE
clean up buildkit config

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#758]
Ran into this today with @iwillig 

Currently in buildkit there are 2 entries: MapStory.js and GeoExplorer.js.
This means you cannot really use a @requires to an OpenLayers resource in GeoExplorer.js

Ideally we would merge them into one file so we can overcome this.

Workaround for now is to add dependencies to the include section of MapStory.js, just like eg TileManager.js

**Comment by ischneider** [comment]
Closing, obsoleted by Phase V effort
