### ISSUE TITLE
Changing End Date on StoryLayer

### ISSUE THREAD

**Issue by DanielJDufour** [MapStory/mapstory-meta#759]
I want to tell a mapstory (http://mapstory.dev.opengeo.org/maps/288/) using two story layers, however the data for one storylayer disappears after 2005 (http://mapstory.dev.opengeo.org/data/geonode:Parks_in_Istanbul).  I would like it to continue to appear up until the present.  This storylayer includes data with start dates up until 2006, but has end dates as 9999 (i.e. infinity).  When I change the end date to 2013, I cannot save this change.
![screenshot of changing end_date issue - daniel dufour](https://f.cloud.github.com/assets/4313463/655072/d64dbb12-d509-11e2-9147-af8c5988013e.png)

**Comment by bartvde** [comment]
@emloux @cholmes any reason why this is not in the current milestone?
I've moved it to Appomatox let me know if this is not okay.

**Comment by bartvde** [comment]
@DanielJDufour when you say: "When I change the end date to 2013, I cannot save this change." is this in the "Date & Time Options" dialog, or when you import the data? cc @ischneider 

So if I am understanding you correctly, you want the story to play up until further than the limit of one of the storylayers (2005)? And the one story layer that has no data for that period, would simply display transparent / empty in that case?

**Comment by DanielJDufour** [comment]
If you're going to work on a Saturday, the least I can do is respond! 
Since 1 month ago, I deleted the old StoryLayer, did a workaround and uploaded a new story layer (with the same name).  The hyperlink refers to the new version.  If I remember correctly there were two original issues, I felt forced to enter an end-date for the parks because the system would not assume that a park continues to exist in perpetuity when there is no end-date.  The second issue is that I tried another workaround in which I wrote the end-date as 9999 for parks that still exist today.  I was hoping that I could set the temporal bounds to the layer without changing the underlying data.  Within the Date & Time Options, I tried to change the End: to 2013, but it wouldn't save.  I was hoping then next year in 2014, I could change this again without having to change the end-date for every feature in my dataset.  The workaround I finally did was manually enter 2013 as the end-date in my csv for all the existing parks.  But this doesn't distinguish between Parks that will end in 2013 and those that currently exist in 2013, but will probably continue to exist.

Re: your first question: This is in the "Date & Tie Options" dialog
Re: your second question: No quite.  Although I think would like the MapStory to play up until further than the limit of one of the storylayers, that wasn't my concern here.  Essentially, I want it to be that in the case that there is no end-date for some features, the story should play up until the present.  It's more of an intuitive thing, than a coding thing.  I'd like playback to assume that if something doesn't have an end-date then it still exists.

Let me know what's possible.  I think a lot of this confusion (on my part) was because I was new to the platform at the time and my first intuitive thoughts did not perfectly line up with the underlying technology.

Sorry for the long message, I did not have time to write a shorter one

**Comment by bartvde** [comment]
Hey Daniel would you mean reposting this on http://help.mapstory.org/questions/

Once things get clear wrt what needs to be done to the software, we'll create github issues.

TIA.

**Comment by ischneider** [comment]
I opened a new ticket to capture the specific case of allowing a missing end date: #827

Daniel has created discussion here: http://help.mapstory.org/question/106/what-happens-if-i-dont-specify-an-end-date/

Reopening this ticket to address the UI/UX surrounding the modification of the end date - it appears to work correctly but one must explicitly save the map after adjusting the date.

**Comment by bartvde** [comment]
looking the last mentioned issue by @ischneider now

**Comment by bartvde** [comment]
@ischneider I cannot reproduce. I created: http://mapstory.dev.opengeo.org/maps/355/ and if I change the end date from 2005 to 2003 the playback end date instantly changes on the slider. What am I doing wrong?

**Comment by bartvde** [comment]
or do you mean the change is not persisted until you save the map @ischneider?
Do you want it to save automatically? We used to have a Save button on the dialog but @cholmes wanted it removed because it did not seem to do anything.

**Comment by ischneider** [comment]
It makes sense to either save immediately or add back a save button that actually does something. As is, the behavior is confusing.

**Comment by bartvde** [comment]
agreed

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/79b325dbae25a5777b6a75b673993203fcf7aa0f pulled in with https://github.com/opengeo/geonode/commit/e45d5b035eae6bda5fa6126b0a2537b0268fef86

**Comment by bartvde** [comment]
deployed on dev

**Comment by DanielJDufour** [comment]
I tested the UI/UX changes to the Date & Time Options Pop-Up.  I changed the End Date, and then clicked Save, and then nothing happened.  Here's the url: http://mapstory.dev.opengeo.org/maps/367/view/.  And here's the screenshot:
![enduiux](https://f.cloud.github.com/assets/4313463/919617/3869ccfe-fecd-11e2-84c7-e534c52321c8.png)

**Comment by bartvde** [comment]
you mean you did not notice that anything happened ;-) ?

It uses an Ajax request to save, you want feedback that the save finished successfully?

**Comment by DanielJDufour** [comment]
Actually both (maybe).  The end-date on the time slider doesn't change and there's no save confirmation (like the window closing after pressing save).  My best guess for why this is happening is that the end-date on the time slider seems to be automatically calculated based on the latest start-date and not the latest end-date....

**Comment by bartvde** [comment]
If I change the end date on your map to 2010, the slider gets updated and the Ajax request goes off correctly

**Comment by DanielJDufour** [comment]
Okay, you're correct.  I was confused.  It appears that my issue is really with the way playback works.  (I'll create another issue for this).

**Comment by bartvde** [comment]
Closing the dialog automatically on save has been implemented with: https://github.com/opengeo/geonode/commit/2ab907a6d12b9e493f6e5e7382dbf81632cdab9f

**Comment by emloux** [comment]
Marking ready for deploy- separate ticket open for Daniel's playback issue.
