### ISSUE TITLE
potential regression in viewer

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#761]
No migrations have been done at this point, but it seems different.

http://mapstory.dev.opengeo.org/maps/112/view/

A large number of console errors and the timeline pops over the controls.

**Comment by bartvde** [comment]
Apparently there is an annotation without content and the code is not prepared for this.

**Comment by bartvde** [comment]
Fixed in GXP and tested on dev: https://github.com/opengeo/gxp/commit/270848e9c03f83c1554aea9b40516f17e510b7fa

**Comment by bartvde** [comment]
Pulled in with: https://github.com/opengeo/geonode/commit/2c994795e269292e8085148d9c272f8d8638d4e2

**Comment by ischneider** [comment]
This did fix things. One of the layers was marked as private, so this was causing permission errors. Thanks Bart. Closing.
