### ISSUE TITLE
gml download links don't appear to work in chrome or safari

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#764]
The server call actually works, but something about how it calls makes it so it doesn't show up anywhere. In firefox it opens in a new tab and displays it. In chrome and safari it just says waiting and doesn't do much. If you right click and open in new tab then it displays it fine.

I think the idea would be if it popped up the dialog to save it to disk. Not sure if this is in our control easily though. But since it's under 'download' I think the expectation would be to save the file, not to view some huge xml thing in your browser (which can easily take up tons of memory).

**Comment by ischneider** [comment]
This is actually in our control. For example (and note the file name change):

http://mapstory.dev.opengeo.org/geoserver/wfs?typename=geonode%3Aworld_series_winner_final&outputFormat=gml2&version=1.0.0&request=GetFeature&service=WFS&CONTENT-DISPOSITION=attachment&FILENAME=blah.xml

**Comment by cholmes** [comment]
Ah cool. Thought I remembered some option like that in geoserver at some point, but my memory was vague. So we just have to update the django code to call that properly? Assigning to an earlier milestone then, since it sounds like a pretty quick fix.

**Comment by cholmes** [comment]
Would be good to do for json too, I had similar things on firefox.

**Comment by ischneider** [comment]
Changed the links to add the headers - very easy fix. Deployed to dev.

**Comment by cholmes** [comment]
Looks good. Could you make two small little tweaks to it? 
- Call it GML 2.1.2 instead of 2.0 (since that's what it is, and is then consistent with the 3.1.1 naming of the other one)
- Have the GML 3.1.1 call use version 1.1.0 of WFS, not 1.0.0

http://mapstory.dev.opengeo.org/geoserver/wfs?typename=geonode%3ASoccer&outputFormat=text%2Fxml%3B+subtype%3Dgml%2F3.1.1&version=1.1.0&CONTENT-DISPOSITION=attachment&service=WFS&request=GetFeature&FILENAME=Soccer.xml

instead of

http://mapstory.dev.opengeo.org/geoserver/wfs?typename=geonode%3ASoccer&outputFormat=text%2Fxml%3B+subtype%3Dgml%2F3.1.1&version=1.0.0&CONTENT-DISPOSITION=attachment&service=WFS&request=GetFeature&FILENAME=Soccer.xml

This is admittedly pretty obscure, but if you use 1.0.0 then the schema for the request comes back as GML 2.1.2, so it probably wouldn't actually validate in a good xml parser. If you use 1.1.0 in the initial request then the describe feature type call in the schema also calls 1.1 and gets the 3.1.1 schema.

Ideally the iso19139 metadata link also gets updated similarly.

**Comment by ischneider** [comment]
Updated on dev. Should show up in ISO metadata, too.

**Comment by cholmes** [comment]
Hrm, I think iso metadata may not be working now. http://mapstory.dev.opengeo.org/mapstory/metadata/225 doesn't seem to have any download links any more.

The 2.1.2 and 1.1.0 stuff looks good though.

**Comment by ischneider** [comment]
Sorry, deployed fix to that.

**Comment by cholmes** [comment]
looks good on prod
