### ISSUE TITLE
clean up download formats

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#766]
We've got a bunch of download things that don't work, don't work well, or don't seem to work.

GML doesn't appear to work in chrome or safari - #764  

I think geojson suffers similarly in chrome.

PNG, JPG and PDF all only return the first time image. Returning just a slice of time probably just doesn't make sense. An animated gif does, or some UI to select a time slice. But doesn't seem to make sense in bulk download.

KML / view in google earth suffer similarly or don't work, because of the time component, see #765 

We should either fix these, or at least remove them as options. Should have 4 formats that all work instead of 10 half broken ones.

**Comment by ischneider** [comment]
This was easy, just added a filter to remove the 'bad' formats. Deployed to dev.

Don't think this should be closed yet, though as especially KML fixes make sense.

**Comment by cholmes** [comment]
Looks good. I think we can close this, KML has its own issue so we can just track it there. Everything else is good now.

**Comment by cholmes** [comment]
confirmed on prod
