### ISSUE TITLE
new icons for buttons

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#770]
So we've got new buttons, clearing out lots of space, but many of them could use nicer icons:

![screen shot 2013-06-24 at 3 15 38 pm](https://f.cloud.github.com/assets/407017/697551/87b52cb4-dd02-11e2-8f83-ef2726bc0342.png)

Top of the list are 'timeline' and 'save map', as they are just text right now.

After that it'd be great to get 'select feature' (the blue i), 'create new feature' (the pencil with a green plus) and 'notes' (may still need text, but the icon could be updated) to be in the style of the other icons on the toolbar. Right now they come from the gxp stuff, in the style of the 'silk' library, from 'geosilk' - http://projects.opengeo.org/geosilk Which does not really match the rest of our aesthetic. 

They are also a bit small, so would be good to get ones that are the same size as the time slider icons.

**Comment by jonpmarino** [comment]
Will have new buttons from Rebecca (designer) soon. Got mock ups for Save, Timeline and Notes but she didn't include Select Feature and Create New Feature so I sent back to her. Pinging her now to hurry up.

**Comment by ischneider** [comment]
Changing milestone to Appomattox

**Comment by jonpmarino** [comment]
Will have icons from Rebecca in a few hours, FYI

**Comment by emloux** [comment]
@jonpmarino Do you have the new icons from Rebecca yet?

**Comment by jonpmarino** [comment]
Yes. Had forwarded it last week. Sorry if it fell through cracks. Emily,
I'll send assets to you now over email.

On Mon, Jul 1, 2013 at 11:31 AM, emloux notifications@github.com wrote:

> @jonpmarino https://github.com/jonpmarino Do you have the new icons
> from Rebecca yet?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MapStory/mapstory/issues/770#issuecomment-20289381
> .

## 

Jonathan Parnell Marino

@jonpmarino
www.mapstory.org
(815) 222 9088

**Comment by bartvde** [comment]
Implemented with https://github.com/opengeo/geonode/commit/524fd3388833021b89cf6fe300aebb6c382cda29 and https://github.com/MapStory/mapstory/commit/4ee7f1ab5276a7eee5dc746e2bca38ac2dfc3e9d

Not deployed to dev as yet

**Comment by ischneider** [comment]
deployed to dev

**Comment by jonpmarino** [comment]
look great I think!

**Comment by bartvde** [comment]
this still needs some work in the annotations rewrite branch, since that one still shows up as a text button, putting a note here as a reminder

**Comment by cholmes** [comment]
I'm going to mark ready for deployment. It's an improvement even without the annotation button.

**Comment by bartvde** [comment]
btw the annotations work has been updated as well to use the new icon
