### ISSUE TITLE
Remove dateline wrapping

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#771]
Right now we have a 'dateline wrapping' option. It was in map properties, is now in 'save map'. Tucker has expressed that he doesn't want any dateline wrapping. Right now we default to 'false' for that value. But because of #265 it seems like it's set to wrapping, since the map does wrap, the basemap just doesn't.

So we should get #265 working, and then remove dateline wrapping as an option. Just take it away as a map property. 

I guess this may take some migration, but my guess is it's very few maps that have dateline wrapping to true.

More discussion at: 
https://groups.google.com/a/opengeo.org/forum/#!topic/dev-mapstory/N0N0IJbVnUo

Note that if this is a big bitch to implement we can just wait for ol3, which seems to do better with this stuff (in that dateline wrapping seems to work well all the time, doesn't need a goofy setting - I think it's ok if we default to true if it all just works right)

**Comment by bartvde** [comment]
IIRC we need to set wrapDateLine to true otherwise we can't zoom out far enough on a lot of maps, i.e. we can't even see the whole world.
So the only option I see is fixing the wrapDateLine on overlays in OL2.

**Comment by bartvde** [comment]
@ahocevar do you still remember the change in OL2 that restricted the map zooming out too far if wrapDateLine is false?

**Comment by ahocevar** [comment]
@bartvde That was openlayers/openlayers@0b39d32031836af30078a5e21448f1f916c18523

**Comment by bartvde** [comment]
okay I think I have a plan for this now, let's put wrapDateLine to true by default and override the adjustZoom function to just return the zoom. The only potential issue is there if we have vector features that span the dateline, and I don't think there is a very high chance of this in MapStory.

**Comment by cholmes** [comment]
Not sure I understand. With this will we be able to zoom all the way out?

Note that Tucker does have a preference for _no_ dateline wrapping. Though if this is easier then let's just do it, and can revisit later.

**Comment by bartvde** [comment]
It will mean we will be able to see the complete world. But not more than 1 world, so we won't have the issue with the repeating overlays.

**Comment by cholmes** [comment]
Ah, ok, cool.

**Comment by bartvde** [comment]
Hmm I have to take that back, I do get more than world in this case (with both base map and overlay repeating), looking further into solutions.

**Comment by bartvde** [comment]
Okay, I think the only way to deal with this is fix it in OL so that the overlays are not repreating when wrapDateLine is set to false, but non-trivial.

**Comment by bartvde** [comment]
Actually @ahocevar's original patch still works okay with a little adaption, except for the transitions when zooming which are ill-positioned

https://github.com/ahocevar/openlayers/commit/e52c97f7413b57663e51ae67af358a3083c9c40c

but also still have to look up the reason why this was reverted.

Maybe best to leave this one for now.

**Comment by bartvde** [comment]
Discussed this with @ahocevar on IRC and opened up a new OL2 issue with an example for him to reproduce: https://github.com/openlayers/openlayers/issues/1036

**Comment by bartvde** [comment]
@ahocevar's work was pulled in with https://github.com/opengeo/openlayers/commit/e4a63cf8a478ac1b60e4f4f330f834b007bf655a and https://github.com/opengeo/geonode/commit/521c746db68391e4866ff1497f5683758f6a81a1

**Comment by bartvde** [comment]
implemented with: https://github.com/opengeo/geonode/commit/e786c232f90fd127c47a874fa4f37bc7761578fc

**Comment by cholmes** [comment]
Is this pushed to dev? And what exactly does the fix do?

**Comment by bartvde** [comment]
not deployed as yet

it removes the wrapDateLine checkbox from the saveMap dialog and makes all maps use wrapDateLine false (since overlays are not repeating anymore)

**Comment by ischneider** [comment]
Deployed to dev. From what I saw in this map, the wrapping still occurs but in the editor, it does not

http://mapstory.dev.opengeo.org/maps/337
http://mapstory.dev.opengeo.org/maps/337/view

I think the idea is that when zoomed past world extent, there will be no wrapping of the overlay.

**Comment by cholmes** [comment]
Agreed, editor looks great.

But in the display we've got 2 copies of the world. Which is better than the infinite that was there previously, but let's get to one.

![screen shot 2013-07-19 at 5 32 33 pm](https://f.cloud.github.com/assets/407017/828690/ebbe0f52-f0ba-11e2-82a8-fedc1e7e6e3f.png)

**Comment by bartvde** [comment]
This is weird, no clue as yet as to why this is happening in the viewer, but will investigate a bit more.

**Comment by bartvde** [comment]
Ah ofcourse, the composer is singleTile and the viewer is not, but how come the tiled layer is not listening to wrapDateLine cc @ahocevar 

My best guess would be that the layer has a maxExtent defined:

```
maxExtent: OpenLayers.Bounds.OpenLayers.Class.initialize
bottom: -7542451.543252016
centerLonLat: null
left: -20037508.33998887
right: 20037508.34001113
top: 17926781.199337915
```

**Comment by ahocevar** [comment]
The right bound of the maxExtent exceeds the Web Mercator world bounds. This is why you get another world. The right bound should be 20037508.34.

**Comment by bartvde** [comment]
Hmm wondering how it got to be that value, GetCapabilities or some other cause. Thanks for the quick feedback @ahocevar

**Comment by bartvde** [comment]
The search API gives back bbox in WGS84:

```
"bbox": {"minx": -180.0, "miny": -55.919724000099997, "maxx": 180.0, "maxy": 83.113876000000005}, "owsUrl": "http://mapstory.dev.opengeo.org/geoserver/geonode/FSCategorized/wms", "relevance": 13, "title": "Failed States Index (2007-2013)", "storeType": "featureType", "_display_type": "StoryLayer"
```

**Comment by ahocevar** [comment]
So there must be a quite inaccurate formula to transform to web mercator from these WGS84 bounds.

**Comment by bartvde** [comment]
right, checking for the place where this happens right now

**Comment by bartvde** [comment]
Ah GetCapabilities is into play and not the bbox from the search result:

it seems GeoServer is somehow the culprit here:

```
<BoundingBox SRS="EPSG:4326" minx="-179.99999999989993" miny="-55.91972400006239" maxx="180.00000000010013" maxy="83.11387599997758"/>
```

http://mapstory.dev.opengeo.org/geoserver/geonode/FSCategorized/wms?SERVICE=WMS&REQUEST=GetCapabilities&TILED=true&VERSION=1.1.1

**Comment by ahocevar** [comment]
It's not necessarily GeoServer. There might be something that sets the WGS84 bounds in GeoServer using the REST API.

**Comment by bartvde** [comment]
Okay right, but outside of control of the client (maybe the uploader indeed).

**Comment by bartvde** [comment]
@ischneider would love to hear your feedback on where this could be caused. TIA.

**Comment by ischneider** [comment]
The data itself contains the ever so slightly invalid values:

```
select ST_XMax(the_geom) from "FSCategorized" where ST_XMax(the_geom) > 180;
```

## st_xmax     

 180.0000000001
 180.0000000001
 180.0000000001
 180.0000000001
 180.0000000001
 180.0000000001
 180.0000000001
 180.0000000001
 180.0000000001
 180.0000000001
 180.0000000001
 180.0000000001
 180.0000000001
 180.0000000001
(14 rows)

And the bbox is dutifully reported as calculated:

```
select ST_Extent(the_geom) from "FSCategorized";                               
```

## st_extent                                

 BOX(-179.9999999999 -55.9197240000624,180.0000000001 83.1138759999776)
(1 row)

As for the discrepancy between the search response and the caps doc, my guess is that the search code is getting/creating a clipped envelope for it's index.

As for how to prevent/deal-with this, it seems like:
1. Ideally, we'd stem these issues ahead of time with some sanity checking tool (I've seen much larger erroneous values that look like overflow/logic errors)
2. During upload, we'd check again and warn about invalid values and/or clip them
3. The client could defend against invalid bounds and clip them

**Comment by bartvde** [comment]
@ischneider I implemented 3. with: https://github.com/opengeo/gxp/commit/3e87e24e3408e9bb8a33df51eeb62129dc5c6cc8

but cannot really be pulled in until the annotations work has been merged in.

**Comment by bartvde** [comment]
verified the fix on dev on: http://mapstory.dev.opengeo.org/maps/337/

**Comment by emloux** [comment]
Marking Ready for Deploy
