### ISSUE TITLE
playback bug

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#772]
http://mapstory.org/maps/471/

On firefox, browser becomes unresponsive and I had to kill. Chrome notes:
Uncaught RangeError: Maximum call stack size exceeded

**Comment by emloux** [comment]
Map 471 isn't working for me on chrome either.

**Comment by bartvde** [comment]
can we get this map on dev?

**Comment by ischneider** [comment]
Assigning to me so I remember to get it over :)

**Comment by ischneider** [comment]
Closing - old UI
