### ISSUE TITLE
Creating a new map from a layer should not pop up search results

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#775]
I believe this is a regression from the old search. 

If you go to http://mapstory.dev.opengeo.org/maps/new?layer=geonode:GRanD_dams_v1_1

(by hitting 'create new map from this story layer' on a story layer page) then you have already selected your map, and likely don't want to search. We used to not start with the search popped up, only did that on totally empty maps. So could we make it so the new map composer search does not pop up if you're on a map newly created from a layer?

**Comment by iwillig** [comment]
Actually, I am not sure what is best here. I feel there are valid reasons to show the add layers dialog when you are creating a map thats been pre-populated with an layer.

**Comment by cholmes** [comment]
Unless it's a bitch to change I'd prefer to stick with the behavior that matches the current site. And at some later point we can have a designer make a more informed call.

But yeah, it's not essential, so should be lower priority than other stuff.

**Comment by cholmes** [comment]
confirmed working on dev, ready for prod.
