### ISSUE TITLE
Show total number of results to page through

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#776]
One thing I miss in the new map search is context for how many results my search may be returning. On the main page it gives you an idea (as it's loading more). It's probably more relevant here, as you'll want to know just how many results you have to page for.

Would be great if right next to the 'previous' / 'next' buttons it could say 'displaying X of Y results'. Where Y is the total number of results that the search returned. I guess X would never be more than 25 (with our current paging stuff), but would be less on the last page.

**Comment by iwillig** [comment]
This is new work and I not sure I will be able to get it to. Chris, can you prioritize this issue.

**Comment by cholmes** [comment]
Lower priority. Can do it after the next push to production, if you've got time at the end of the week.

**Comment by cholmes** [comment]
Looks good, ready to deploy.
