### ISSUE TITLE
Change 'sharethis' default langauge so it includes mention of @MapStory

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#778]
Current sharethis default language in the Tweet does not include @MapStory handle. Would like to change it so it does.

**Comment by cholmes** [comment]
So I'm pretty sure this should be easy. There's a 'twitter:creator' tag which we're not using. I think we can just set it to a static '@mapstory' in that field. And then a 'by MapStory @mapstory' should show up in all tweets, below the other info.

https://dev.twitter.com/docs/cards/validation/validator

**Comment by cholmes** [comment]
Hey Ian, assigning this to you as I figure it'll take you about 2 minutes to knock out. Or if you don't feel like doing it we can reassign to Marc.

**Comment by ischneider** [comment]
I went ahead and added this and deployed to dev. I have no idea how to test this.

**Comment by cholmes** [comment]
I just tested, works great. 

For future reference you just go to https://dev.twitter.com/docs/cards/validation/validator and hit 'validate and apply' and then post in a map, like: http://mapstory.dev.opengeo.org/maps/183/

**Comment by cholmes** [comment]
squeezing in to antietam, it's great to push out.

**Comment by cholmes** [comment]
Hrm, actually @jonpmarino - could you check it out and see if we want to run with it?

https://twitter.com/chucker42/status/349882247203127298

vs

https://twitter.com/chucker42/status/349643948555378688

First is the new one on dev, second is the current on prod

Both do have MapStory with the logo that goes to the mapstory handle, at the top.

The second also says 'By MapStory @MapStory' That's what the easy way gets us. Happy to do it if you want. In the long term I think it'd make sense to grab the user's twitter handle (once we have #582) and put that there, so the mapstory appears with a 'by' attached to their twitter, not mapstories.

**Comment by jonpmarino** [comment]
Looks good to push to me! Agreed about the future change once #582 is working.

**Comment by cholmes** [comment]
confirmed on prod
