### ISSUE TITLE
Make the map zoom to the layer extent when a layer is added

### ISSUE THREAD

**Issue by iwillig** [MapStory/mapstory-meta#780]
The current behavior is wrong. 

When a user adds a layer to a map the map should zoom to the extent of that map. 

Created from a comment in ticket #683

**Comment by cholmes** [comment]
Thanks for making the ticket Ivan, meant to and then forgot.

**Comment by iwillig** [comment]
No worries

**Comment by cholmes** [comment]
Works great, thanks Ivan.

**Comment by cholmes** [comment]
working on mapstory.org
