### ISSUE TITLE
edit layer style is read-only on demo

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#781]
Reported by @ischneider 

Hey Bart,

I was just running this on production and stumbled into a version of this not covered by the migration script:

http://mapstory.demo.opengeo.org/maps/17

One can bring up the style dialog but it looks like just an image and no clickable rules. The edit buttons are all disabled.

A similar map on dev: http://mapstory.dev.opengeo.org/maps/158/view/ doesn't show this behavior.

Looking at the config, the working map has cached capabilities. This reminds me that we don't want to do this any longer: https://github.com/MapStory/mapstory/issues/416

Any hints appreciated.

**Comment by bartvde** [comment]
this is caused by the layer config referencing a styles (in params.STYLES) that doesn't exist in the SLD, I think we should fallback to the default style in this case.

**Comment by bartvde** [comment]
See: https://github.com/opengeo/gxp/commit/d10ba7e95965d49109faa5b4454365fca64fdcd9

**Comment by bartvde** [comment]
pulled in with https://github.com/opengeo/geonode/commit/9aa08debc4c464dabeeff1cf5c03032954b04425

**Comment by emloux** [comment]
@bartvde is this deployed on dev?

**Comment by bartvde** [comment]
i did not deploy it maybe @ischneider did

also note the issue was only with a map on demo not dev

**Comment by emloux** [comment]
@ischneider can you deploy the fix for this on demo?

**Comment by ischneider** [comment]
Not yet ready to deploy due to wanting some more testing in dev related to some GXP issues that got in the mix.

**Comment by ischneider** [comment]
Confirmed this is resolved.
