### ISSUE TITLE
StoryLayer Grayed out on MapStory Edit Screen

### ISSUE THREAD

**Issue by DanielJDufour** [MapStory/mapstory-meta#782]
StoryLayers sometimes gray out on the left hand panel under Overlays on the MapStory edit screen.  It is unclear to me why this is happening, especially when I know that these storylayers are functional because I've tested them in other mapstories before.  In this particular example, the Districts of Yemen are grayed out.
![storylayer grayed out](https://f.cloud.github.com/assets/4313463/711242/99e5afac-de8e-11e2-8c14-a12607f76201.png)
.

**Comment by ischneider** [comment]
closing due to change in platform
