### ISSUE TITLE
Change "About" to "Wiki" on homepage?

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#784]
I think this is better, as no one knows the Wiki exists currently. Now that we can link to MapStory Foundation page in footer that seems to suffice for "About".

**Comment by emloux** [comment]
@jonpmarino Do you want to preserve the content of the about page anywhere or have you moved relevant information to the wiki?

**Comment by jonpmarino** [comment]
@emloux about just goes directly to Wiki. Wouldn't be any changing of content, just changing header link so people know what it is. When we started, Wiki was just a landing page for 'about text', so this made sense. But now were positioning it as a community space to host lots of content, so users need to know its there. 

In the future we have MapStory Foundation link to an 'about the Foundation' page, which I think is helpful as a more traditional 'about' for what folks would be looking for

**Comment by drwelby** [comment]
Changed in https://github.com/drwelby/mapstory/commit/5c747a652703befa92ab8ff7c50169be992fc371

Not sure how to proceed from here...

**Comment by jonpmarino** [comment]
This is another one that is a question for the community infrastructure
pow-wow next week. I would table until then.

On Wed, Jul 10, 2013 at 5:03 PM, Marc Pfister notifications@github.comwrote:

> Changed in drwelby@5c747a6https://github.com/drwelby/mapstory/commit/5c747a652703befa92ab8ff7c50169be992fc371
> 
> Not sure how to proceed from here...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MapStory/mapstory/issues/784#issuecomment-20773066
> .

## 

Jonathan Parnell Marino

@jonpmarino
www.mapstory.org
(815) 222 9088

**Comment by cholmes** [comment]
@drwelby - let's roll this change back, given all recent discussion. We'll call it 'about' again, and in #804 we'll have some sub-headers for 'about' too.

Closing ticket, let's make sure it doesn't get pushed.
