### ISSUE TITLE
logging in from logout page causes logout

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#786]
because the return context takes the user back to the logout page :(

in this case, a redirect to 'home' would work.

**Comment by drwelby** [comment]
Is this fixed? The logout button seems to redirect to / which would take care of the problem.

**Comment by ischneider** [comment]
This only seems to occur when on the 'admin' site page - it takes you to 'logout' and from there a login attempt via the popup ajax thingy reloads the page (which then logs you out).

Given the infrequency of this happening (maybe it's only me), I'm closing this for now. Reopen if needed.

Punt :football:

**Comment by drwelby** [comment]
The ajax thingy does the reload, so we can always test to see if the page location is /logout, and then have it load / instead. But I think a punt works for now.
