### ISSUE TITLE
Provide cookie to integrate with warper

### ISSUE THREAD

**Issue by DavidJLee** [MapStory/mapstory-meta#787]
Upon successful login a cookie should be set to the mapstory.org domain (this will allow warper.mapstory.org access to the cookie). If the user logs out, the cookie should be destroyed.

At a minimum this cookie should contain JSON serialized data of the following hash:

{ :id => <unique user id>,
:username => <display username>
}

This cookie should be signed and encrypted so that it can not be spoofed.

I'm currently not sure how to create a signed and encrypted cookie that is interoperable between rails and django. Will look into options.

**Comment by ischneider** [comment]
@DavidJLee any updates on how to best interoperate? I found a variety of approaches for this but as I now nothing of rails, defer to your preference.

**Comment by DavidJLee** [comment]
Sorry for the delay, have been really swamped of late.

Thinking about this more we could just sign the cookie to ensure it's valid and not really care about encryption. That should simplify the implementation assuming it's ok to expose the user's unique id and username (presumably this is already exposed somewhere?)

If just signing, the string would need to be HMAC signed. In ruby that would look something like this:
OpenSSL::HMAC.hexdigest(OpenSSL::Digest::Digest.new('sha1'), key, data)

I presume very similar in python (http://docs.python.org/2/library/hmac.html)

**Comment by ischneider** [comment]
Thanks for getting back to me @DavidJLee.

I can verify python and ruby arrive at the same hexdigest using sha1 and the same key/data.

So you're thinking the cookie would look like:
username:hash

Do you see any problems setting it only for warper.mapstory.org?

**Comment by ischneider** [comment]
I've figured out pretty much everything needed to do this and could cherry-pick to production pretty quickly for testing. Just let me know when you'll have some time @DavidJLee

**Comment by jonpmarino** [comment]
@ischneider any word from @DavidJLee on the cookie piece?

**Comment by ischneider** [comment]
@DavidJLee I deployed the cookie to production. Sorry, though I had that worked out earlier...

The cookie key is `msid`. The value is `username:sha-1`. This gist verifies the hash: https://gist.github.com/byu/99642

I'll email the value of `SYMETRIC KEY`

**Comment by DavidJLee** [comment]
Thanks Ian, 

I was able to successfully decode the key in production this morning so we should be all set. This issue can be closed.

**Comment by ischneider** [comment]
keeping this open as a reminder for phase V
