### ISSUE TITLE
Create workflow and document a way to Add to Manual

### ISSUE THREAD

**Issue by emloux** [MapStory/mapstory-meta#789]
This ticket will take care of creating a workflow and documenting a process for updating the Manual.

**Comment by ischneider** [comment]
At the moment, the best approach is to edit the manual pieces here:
https://github.com/MapStory/mapstory/tree/master/manual

Github should create a branch for the edits and then a pull request should be created. Devs will review the pull request, verify things work correctly and merge.

**Comment by jonpmarino** [comment]
@ischneider this seems a good approach! I'd say we call this one done.

**Comment by emloux** [comment]
closing
