### ISSUE TITLE
Add Following to Info Page

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#79]
Comments was developed in Pinax (by Eldarion) for the ANZSM project. This needs to be brought into the MapStory project for display on the Info Page. Other social features include Comments and Following (ala Twitter)

**Comment by awright** [comment]
Issue #77

**Comment by awright** [comment]
Issue: #78

**Comment by bartvde** [comment]
@awright has this all been done? I see comments, and G+ and Facebook in the current site.

Can we close this one?

**Comment by awright** [comment]
yes, complete. closing.
