### ISSUE TITLE
Add 'space around' and 'conflict resolution' to Styling options

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#794]
See http://forum.mapstory.org/question/8/how-do-i-get-all-my-labels-to-show-up-on-the-mapstory/

Conflict resolution should be a checkbox defaulting to 'true'. Turning it off should make it so all labels appear, which is what people sometimes want. Space around should help to show more in a less blunt way I think. Can add both under 'label options'.

See http://docs.geoserver.org/latest/en/user/styling/sld-reference/labeling.html#conflictresolution and http://docs.geoserver.org/latest/en/user/styling/sld-reference/labeling.html#overlapping-and-separating-labels-spacearound

**Comment by bartvde** [comment]
See: https://github.com/opengeo/gxp/pull/196

pulled in with https://github.com/opengeo/geonode/commit/636baa737e80dfb54826aa5c81f012ab01e9de60

(not deployed as yet on dev)

**Comment by cholmes** [comment]
Just starting to test Bart. Looking good for the most part. One thing though, I can't seem to set conflict resolution to 'true'.

I think it'd be good to default to 'true', and let people uncheck it if they want.

**Comment by bartvde** [comment]
@cholmes do you mean the checkbox doesn't work? Or that it does not get into the SLD output?

**Comment by bartvde** [comment]
ah I see now what you mean, it doesn't stick

**Comment by bartvde** [comment]
This should be fixed with https://github.com/opengeo/gxp/commit/00091fa7fb757b7524c5ff4e298d160dd3e97510 still needs to be pulled in and deployed to dev, will do this when I finish the other TextSymbolizer issues as well

**Comment by cholmes** [comment]
Can you make it so the 'space around' option is below the 'conflict resolution' checkbox? And have it only show up when 'conflict resolution' is checked to true, as I don't believe it does anything unless conflict resolution is on.

**Comment by bartvde** [comment]
Done with https://github.com/opengeo/gxp/commit/b5dca04cf846311fcef56b02a08ed271cc1ab73f

**Comment by cholmes** [comment]
Though it starts with -3, I can't seem to set spaceAround to a negative value in that field. Like if I change it to a positive I can't seem to add back in a negative sign.

**Comment by bartvde** [comment]
yeah I think all fields default to allowNegative false will change that for this field

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/ba62cff961a4cc5d8efbbb4ba9da4847734e4787

**Comment by bartvde** [comment]
last change also deployed on dev, negative values should be possible now

**Comment by cholmes** [comment]
Works great.

There's one more little error I see. If you hit 'save' when conflict resolution is off and then come back to it the 'space around' field is there. If you click conflict resolution on then off then it will disappear. It should ideally never appear when conflict resolution is not checked. I think it gets thrown off when it's reading it in fresh or something.

**Comment by bartvde** [comment]
Good testing, will fix

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/58faa42b625d31df655bd9c90cb2f844da2e8284

**Comment by emloux** [comment]
Looking Good
