### ISSUE TITLE
Defaults to display more labels

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#795]
Several users have complained about their labels not showing up. A couple defaults I think could help. Could we make it so when people add a new label we put some default values?
- maxDisplacement = 40
- Autowrap = 40

(feel free to tweak those, just want something in there)

If we do #794 then would be good to also do the overlap one to -3, so more appear.

Also would be great to do 'followline' to true if it's a line. I guess can just default to it regardless, others will just ignore.

**Comment by bartvde** [comment]
see https://github.com/opengeo/geonode/commit/d6075188a8f2a1717595131ad7f08a66b49e535b

**Comment by cholmes** [comment]
On second thought and real testing could we default followline to false? Turning it on can make it seem like there's very few labels.

Also could we default grouping to 'true'?

**Comment by bartvde** [comment]
sure

**Comment by bartvde** [comment]
defaults changed with https://github.com/opengeo/geonode/commit/4cafa2682319aef9eb72575bcd07391ef287b043

**Comment by bartvde** [comment]
https://github.com/opengeo/geonode/commit/ce35bdf898cf80a069c466b47cc39a200ac50f6c

**Comment by cholmes** [comment]
Could you also default 'goodness of fit' to 0.2? Just on polygons.

**Comment by bartvde** [comment]
Hmm default values currently cannot be geometryType dependent, is this really important?

**Comment by cholmes** [comment]
Hrm, it's pretty important. Very few labels show up by default with polygons if it's not set to this. I think it's actually the setting that makes the most difference to polygons.

Could you see what happens if you set it for all the geometryTypes to 0.2? Like just display it to be set on polygons, but set it to default to 0.2 for all? I think there's a chance it may not do anything for the others, so may not matter. But I'm not sure if I'm reading the docs right: http://docs.geoserver.org/latest/en/user/styling/sld-reference/labeling.html#goodnessoffit

**Comment by cholmes** [comment]
Oh, and can you adjust the defaults a bit? After experimenting a bit I think all the options I had lead to too many labels. Set 'conflict resolution' to true by default, with '0' for the value, not -3.

**Comment by cholmes** [comment]
Oh, and one more default. Can you put a default white halo of size 1 when people make a new label? Makes for much nicer default.

**Comment by bartvde** [comment]
Okay let's start with a value of 0.2 for goodness of fit and see if it doesn't interfere for other geometry types.

New defaults with:

https://github.com/opengeo/geonode/commit/8fffa9a3633d605a6144b30dbd6d4d8f30eb1a44

**Comment by bartvde** [comment]
btw not yet deployed since I created some git mess on the dev server cc @ischneider

**Comment by cholmes** [comment]
Hey, the goodness of fit looks great.

But the halo I think regressed, it doesn't seem to default to 1 any more.

**Comment by bartvde** [comment]
@cholmes how did you test this? I just clicked the Halo fieldset on dev and get the defaults (white and 1 pixel).

**Comment by emloux** [comment]
Marking ready for deploy
