### ISSUE TITLE
Add 'polygon alignment' and 'goodness of fit'

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#796]
Related to #794 - would be great to have these as options under 'label options'.

Would be really great if they only showed up for polygons, as they are only relevant to polygons.

**Comment by bartvde** [comment]
I see we are missing some more (new) vendor options, does it might sense to add all of them?

**Comment by cholmes** [comment]
If we do #797 I think it could make sense to add all of them. I picked these two and the two in #794 as I think they do the most for us. I think our interface is already a bit too cluttered, people don't even try the options now. But if we just display the relevant stuff then we could add more options with less clutter.

**Comment by bartvde** [comment]
right, I'm working on both of these already

**Comment by bartvde** [comment]
See: https://github.com/opengeo/gxp/pull/196

pulled in with https://github.com/opengeo/geonode/commit/636baa737e80dfb54826aa5c81f012ab01e9de60

(not deployed as yet on dev)

**Comment by cholmes** [comment]
So the drop down on the polygon alignment works a bit weird right now. If you select one of the options and then go to another field or hit save and then come back the other options won't drop down. You can like delete them and then manage to get the other options, but it's tricky. It'd be good if the drop down always showed all the options, it doesn't seem to if one is selected.

Also could we have it default to 'manual' instead of blank? And never offer the blank option? If that's a pain don't worry about it, there are a number of fields that are like this in the style editor (where we offer both blank and an option that is the default so ends up doing the same thing). So at some point they should all be fixed, but that time is not now. But if you're in this code and it's easy to fix that'd be great.

**Comment by bartvde** [comment]
the polygonAlign combo should be fixed with https://github.com/opengeo/gxp/commit/0a506f347c59cf0f10e6e14eb432c2376f16e283

**Comment by emloux** [comment]
Looks good, ready for deploy
