### ISSUE TITLE
Only display geometry relevant label options 

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#797]
Related to #796 - would be a cleaner interface if we only displayed the label options that are relevant to the geometry type being styled.

See http://docs.geoserver.org/latest/en/user/styling/sld-reference/labeling.html for the options. 

We do this for 'basic' tab, but not on the style one. The following lists what each is relevant to (may miss some, but this list will get us much better):

Anchor point: point only

Displacement (X-direction): point only

Displacement (Y-direction): point only

Perpendicular offset: line only

Priority: point, line polygon (I think, should test to be sure)

Auto wrap: point, line, polygon

Follow line: line only

Maximum displacement: point, line, polygon

Repeat: line only

Force left to right: line only

And then there are some we can add:

rotation: point only

grouping: all

repeat: line only

maxAngleDelta: line only (and only if followline is selected)

goodness of fit: polygon only

polygon align: polygon only

conflict resolution: all

**Comment by bartvde** [comment]
This would need to be dealt with in GXP, so will work on a PR there and reference it here.

**Comment by bartvde** [comment]
See: https://github.com/opengeo/gxp/pull/196

pulled in with https://github.com/opengeo/geonode/commit/636baa737e80dfb54826aa5c81f012ab01e9de60

(not deployed as yet on dev)

**Comment by bartvde** [comment]
Had forgotten one detail: https://github.com/opengeo/gxp/commit/3e5533f0cca81c146e3cf11aa4fa02fe82aa6def pulled in with https://github.com/opengeo/geonode/commit/9d6140b600b8dfafb04dee4774ff3f8f5c1fb2ec

**Comment by cholmes** [comment]
Hey, forgot to be explicit on the LabelAllGroup (Label all segments in line group) option. That should only be in the 'line' section. And similar to your maxangle delta thing, it should only show up if grouping is set to true (just in lines, not in others)

**Comment by cholmes** [comment]
And could 'grouping' be a checkbox, instead of a drop down that says 'yes / no' ?

**Comment by bartvde** [comment]
Wrt grouping, in GeoServer it's yes/no unfortunately and not true/false
I can do it, but it will require a bit of code to handle this special case.

**Comment by bartvde** [comment]
I did wonder myself why this isn't a boolean in GeoServer as well ...

**Comment by cholmes** [comment]
Just asked on the geoserver list. A bit of code to handle it would be great, keep it consistent.

**Comment by cholmes** [comment]
Hey, so one thing is that now 'label positioning' is still a checkbox for polygons, but there's nothing in it. Thinking about it though, could put the 'polygon alignment' option under labeling positioning instead of label options, for polygons. Would make sense there to me, it's about the position.

**Comment by bartvde** [comment]
labelAllGroup only for lines and only if grouping is yes done with https://github.com/opengeo/gxp/commit/b568d47ef2cf7032aad8bdd0b04d32602e776261

**Comment by bartvde** [comment]
Made it a checkbox and done the translation to yes/no with https://github.com/opengeo/gxp/commit/f334dfffa89d90f806392041b41cc57e7a6fd7a1

**Comment by bartvde** [comment]
Moved polygonAlign into a different fieldset with https://github.com/opengeo/gxp/commit/2ca685de8c0c4b480f8ac904e833d3cc0a3fd3c8

**Comment by bartvde** [comment]
@emloux wasn't this finished in the last release already?

**Comment by emloux** [comment]
Good question, I don't know how this one snuck into bentonville. Closing.
