### ISSUE TITLE
Not all settings 'stick' properly in label style editing tab after saving

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#798]
A minor thing, but while you're in the code would be good to fix. If you adjust the graphic, label positioning, priority or label options they update the style properly, but when you come back to them after saving they are unchecked.

If you check them again your settings when they expand will be correct. But it'd be better if after a save they started expanded, to indicate something in there was set. The halo does this properly, the rest don't.

**Comment by bartvde** [comment]
See: https://github.com/opengeo/gxp/pull/196

pulled in with https://github.com/opengeo/geonode/commit/636baa737e80dfb54826aa5c81f012ab01e9de60

(not deployed as yet on dev)

**Comment by cholmes** [comment]
Looks good on dev.
