### ISSUE TITLE
Timeline styling, filtering, other end-user customization

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#8]
User-configurable details on what to put in the timeline and how to display it.  This currently needs more specification

**Comment by awright** [comment]
specification required by david #24

**Comment by bartvde** [comment]
Picking the label is done, and also the filtering as specified here: https://img.skitch.com/20111006-r9xqitjafcy7b5tk1k7h8f3fcb.png was implemented today in GXP.

**Comment by bartvde** [comment]
Not sure if anything still needs to be done for this, so closing. Please create a more specific issue if things are missing.
