### ISSUE TITLE
Maps created by 'create map from this story layer' don't cache

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#800]
It looks like maps that are created from a starting url like http://mapstory.dev.opengeo.org/maps/new?layer=geonode:roads don't get their caching set properly. They seem to save not using the virtual service or the prefix, which leads to GWC not recognizing them as a tile layer. We could fix that in geoserver, but it'd probably be better to save all our maps the same way.

Original report:

I uploaded a new data set: 

http://mapstory.dev.opengeo.org/data/geonode:finalindex0

And if I play back on the data page I get great caching.

If I make a map from it I don't get any. See http://mapstory.dev.opengeo.org/maps/302/

Complaints about not being a tile layer. I tried a couple things (default vs non-default style, etc). But came across a real difference.

The data page, which does cache, uses the virtual service end point: http://t3.mapstory.dev.opengeo.org/geoserver/geonode/finalindex0/wms?SERVICE=WMS&LAYERS=finalindex0&FORMAT=image%2Fpng&TRANSPARENT=TRUE&VERSION=1.1.1&REQUEST=GetMap&STYLES=&TILED=true&SRS=EPSG%3A900913&TIME=2002-01-01T00%3A00%3A00.000Z&BBOX=-15028131.255,5009377.085,-12523442.7125,7514065.6275&WIDTH=256&HEIGHT=256

The map page, which doesn't, does not use the virtual service end point:

http://t4.mapstory.dev.opengeo.org/geoserver/wms?LAYERS=finalindex0&FORMAT=image%2Fpng&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&TILED=true&SRS=EPSG%3A900913&TIME=1996-01-01T00%3A00%3A00.000Z&BBOX=-15028131.255,5009377.085,-12523442.7125,7514065.6275&WIDTH=256&HEIGHT=256

If you change it to the virtual service it does cache. Note it even works properly if you use the properly qualified name. For some reason we say finalindex0, not geonode:finalindex0. Like: http://t4.mapstory.dev.opengeo.org/geoserver/wms?LAYERS=geonode:finalindex0&FORMAT=image%2Fpng&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&TILED=true&SRS=EPSG%3A900913&TIME=1996-01-01T00%3A00%3A00.000Z&BBOX=-15028131.255,5009377.085,-12523442.7125,7514065.6275&WIDTH=256&HEIGHT=256

That does seem to cache properly. 

This seems to be a new thing, with newly created maps. Older maps seem to use the virtual service end point. (I'm still digging in to other problems, they're not all working perfectly).

**Comment by bartvde** [comment]
Looking into this issue now

**Comment by bartvde** [comment]
okay will make a change to use the virtual service endpoint here, would be great if you could actually test it out @cholmes

**Comment by bartvde** [comment]
see https://github.com/opengeo/geonode/commit/a322ece768285e7e53bcb73c5736fe3f6833b2b9

**Comment by bartvde** [comment]
AFAICT this is not caused by not using the virtual service endpoint.

I just created http://mapstory.dev.opengeo.org/maps/317/ with the fix deployed but the same issue is still there.

geowebcache-cache-result:MISS
geowebcache-miss-reason:not a tile layer

So are you saying @cholmes that we should be using the geonode prefix for GWC to cache? Then IMHO this should really be fixed in GWC since GeoServer was changed not to use the prefix anymore for virtual services in the GetCapabilities response.

@ischneider any thoughts?

**Comment by cholmes** [comment]
Looking at map 317 it looks like it's not calling the virtual service end point. For me it's calling http://mapstory.dev.opengeo.org/geoserver/wms?LAYERS=roads&FORMAT=image%2Fpng&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&TILED=true&SRS=EPSG%3A900913&TIME=1926-01-01T00%3A00%3A00.000Z&BBOX=-10439463.573623,5165920.1189063,-10429679.634004,5175704.0585254&WIDTH=256&HEIGHT=256

**Comment by cholmes** [comment]
And @bartvde I was saying one or the other. Using a virtual service without the prefix is fine. And not using a virtual service but using the prefix properly is also fine. But not doing either leads to not caching.

**Comment by bartvde** [comment]
Ah I had missed that, the source url is correct though, will have to look further

**Comment by bartvde** [comment]
Hmm I just tried locally and there the image url is okay

http://127.0.0.1:8000/geoserver/geonode/googleflutrends/wms?LAYERS=googleflutrends&FORMAT=image%2Fpng&TRANSPARENT=TRUE&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&TILED=true&SRS=EPSG%3A900913&TIME=2012-06-16T22%3A00%3A00.000Z&BBOX=-10018754.17,0,0,10018754.17&WIDTH=256&HEIGHT=256

**Comment by bartvde** [comment]
Okay I think I see what might be going on:

```
                            if (url.charAt(0) === '/' && url.indexOf('geoserver') !== -1) {
                                url = this.localGeoServerBaseUrl + 'wms';
                            }
```

**Comment by bartvde** [comment]
Okay should be fixed with https://github.com/opengeo/geonode/commit/ec7b197623bb0aad992342ce8c35679f1146a349

Also deployed on dev.

This map has the correct url:

http://mapstory.dev.opengeo.org/maps/319/

**Comment by bartvde** [comment]
geowebcache-cache-result:HIT w00t

**Comment by cholmes** [comment]
Awesome work Bart. Looks great.
