### ISSUE TITLE
remove help link at bottom of page

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#802]
Get rid of the small footer 'help' link. Content will be merged in to wiki.

**Comment by drwelby** [comment]
pull into master in https://github.com/MapStory/mapstory/pull/812

**Comment by cholmes** [comment]
Looks good.

**Comment by jonpmarino** [comment]
With new feedback button on Home going to the pop-up form, (which looks awesome!) we no longer have any way for user to click directly to help.mapstory.org. Lets reinstate the help link at button of page and have it link to help.mapstory.org.

**Comment by ischneider** [comment]
Good idea for SEO, reopening.

**Comment by ischneider** [comment]
This has been added back. Marking ready for deploy.

**Comment by emloux** [comment]
verified on prod
