### ISSUE TITLE
add feedback/support askbot widget

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#803]
To go right under the 'donate' button, using the askbot widget.

**Comment by ischneider** [comment]
There is a 'recent activity' widget there that I will remove since it's half-baked and most likely confusing.

**Comment by ischneider** [comment]
Deployed to dev.

**Comment by cholmes** [comment]
Looking good. Could we make two small css tweaks? See:

![screen shot 2013-07-19 at 12 47 36 pm](https://f.cloud.github.com/assets/407017/826970/1004d710-f093-11e2-91b6-b8ef33e633f9.png)

The 'search or ask your question' line is a bit cut off.

And the scroll bar on the right is only for a few pixels. Would be better if the box were just a bit bigger, so you didn't have to scroll to see the bottom of the ask question button.

 First is more important than the second

**Comment by ischneider** [comment]
Removed the seemingly erroneous 'search or ask your question' text (it seems it was supposed to be a tooltip), added margin beneath, fixed height to reduce scrollbar

deployed to dev

**Comment by emloux** [comment]
@ischneider Looks great on dev. Marking ready for deploy.
