### ISSUE TITLE
Create sub links on 'about'

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#804]
On orange header below the top links it is just blank under 'about'. We should add three links 'mapstory', 'community', 'foundation'. These should go to wiki pages.

**Comment by cholmes** [comment]
Also where does 'about' go to? Still wiki top level?

**Comment by jonpmarino** [comment]
I thought about still went on header...with sections, search, how to, about and blog.

here are links for:

Foundation -

http://wiki.mapstory.org/index.php?title=The_MapStory_Foundation

Community -

http://wiki.mapstory.org/index.php?title=Community

**Comment by cholmes** [comment]
Note we just switched 'about' to 'wiki', in #784 . We need to roll that back. And 'about' top line should still go to wiki.

**Comment by jonpmarino** [comment]
Needed to add for MapStory.org

http://wiki.mapstory.org/index.php?title=MapStory.org

**Comment by cholmes** [comment]
Cool. So top about goes to http://wiki.mapstory.org

Sub links below that, in this order:

 'MapStory.org' to 
http://wiki.mapstory.org/index.php?title=MapStory.org

'Foundation' to http://wiki.mapstory.org/index.php?title=The_MapStory_Foundation

'Community' to  http://wiki.mapstory.org/index.php?title=Community

**Comment by cholmes** [comment]
@drwelby I think this is ready to go. Would be great if you could knock it out.

**Comment by drwelby** [comment]
Ready for dev.

**Comment by ischneider** [comment]
Deployed

**Comment by jonpmarino** [comment]
Ian. Awesome! A few thoughts -
- "Sections" stays orange no matter what...even if I'm hovering over 'How-To' or others
- Can we not have the sub-topics be centered under their handing rather left justified? It would seem to make more sense for 'get started, get engaged, get skills' to show up UNDER How-To rather than to the left, no?
- under 'About' can have it say "MapStory.org" "The Community" and "The Foundation"

**Comment by drwelby** [comment]
The current UX is a little confusing - we're using the same color for the
active tab and the hover state, and two of the tabs act like links since
they don't open up as tabs.

I agree on having the sub-links centered but wanted to get other design
decisions finalized before messing with that.

**Comment by emloux** [comment]
@drwelby I think we are just going to go forward and implement the changes as stated in the ticket. I want to make sure these content changes get taken care of before we start having a broader UX discussion.

**Comment by drwelby** [comment]
Ready for dev with content changes, holding off on fixing the UX.

**Comment by ischneider** [comment]
Deployed to dev.

**Comment by jonpmarino** [comment]
Looks good!
