### ISSUE TITLE
add email notifications to askbot

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#805]
At the very least people should be notified when someone else replied to their issue.

Would be ideal to be able to get 'the firehose', choose to get emails on everything, or at least digests.

**Comment by ischneider** [comment]
As noted, notifications are on, but the defaults for some settings are daily or weekly.

**Comment by cholmes** [comment]
Yeah, this is great. Closing as it's deployed already. We can figure out default settings.
