### ISSUE TITLE
Flickering Animation 

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#81]
See: http://mapstory.demo.opengeo.org/maps/7

When playing the unemployment map above, the animation turns on and then off in a flickering fashion.  The expected behavior would be a smooth transition.

**Comment by mpriour** [comment]
This reveals a fundamental issue with WMS based animation. The server response to fully displayed image time is longer than the 2 seconds per frame minimum animation speed allowed by the default GeoExplorer viewer.

There are at least 3 fixes:
1. Pre-buffer the animation. Request the next 3 or 4 frames on initial playback and then keep at least 1 or 2 frames ahead during playback. This would smooth the transitions. It would also mean that the initial playback would/could involve a slight waiting time. However, that waiting for the initial buffering is common when watching videos or other animations on the web, so it might be an acceptable trade-off.
2. Wait longer for each frame and provide a waiting indicator while waiting. This would mean that the 1st time through, some animations could be quite slow, but would not be choppy, flickering, or skipping ahead. The animation should be smooth the next time through. You see this on most animated radar maps on the web. It may take 3-4 seconds for each radar snapshot to load, but then the animation loops and runs smoothly after that.
3. Server-side caching -- Create caches or sub-caches that are keyed to style and time request parameters. The very first view of this map by the very first viewer of the data might be choppy, but after that the animation would be fairly smooth for all other subsequent users, provided that the data does not change and the cache can be reliable used.

**Comment by mpriour** [comment]
While the above issues are still performance concerns in the longer term (esp. the server side caching); the flickering issue was fixed in gxp commit https://github.com/opengeo/gxp/commit/ebc16e3c445cab11c6718420b3b67100e21e235d
