### ISSUE TITLE
Clicking on 'download sld' on layer page should actually download

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#813]
See http://forum.mapstory.org/question/52/how-do-i-download-an-sld/

The last couple steps show a 'save as' workflow. The reason it does that is because if you just click on 'download sld' nothing really happens. I think it's because the mime type is set wrong or something like that. If you right click and hit 'save as' then it will work just fine. But we should make it so clicking 'save' downloads properly.

**Comment by ischneider** [comment]
Ready for testing on dev.

**Comment by emloux** [comment]
verified on prod
