### ISSUE TITLE
quick search should select relevance sorting

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#814]
This is when searching for text via the search field on the upper right of most pages

**Comment by ischneider** [comment]
Deployed to dev. To test, enter something like 'NYC Subway' in the search field in the upper right. The top results should all contain that fragment in their title and the sorting dropdown should be 'Relevance'.

Verified by me but if someone else wants to look...

**Comment by emloux** [comment]
Looks great @ischneider! Working perfectly for me.
