### ISSUE TITLE
"How To" submenu buttons

### ISSUE THREAD

**Issue by ChristopherTucker** [MapStory/mapstory-meta#816]
When hovering over "How To" the following 3 buttons should show up in orange:  1) "Get Started", 2) "Get Engaged", 3)  "Get Skillz".

How to

http://wiki.mapstory.org/index.php?title=How_To

Get Started

http://wiki.mapstory.org/index.php?title=How_To#Get_Started

Get Engaged

http://wiki.mapstory.org/index.php?title=How_To#Get_Engaged

Get Skillz

http://wiki.mapstory.org/index.php?title=How_To#Get_Skillz

**Comment by drwelby** [comment]
Covered in https://github.com/MapStory/mapstory/issues/804, waiting to go into dev

**Comment by ischneider** [comment]
Deployed to dev

**Comment by emloux** [comment]
Looks good, one minor spelling detail though, I think we wanted the last menu option to say "Get Skillz" instead of Get Skills.  We're still using this spelling right @jonpmarino?

**Comment by jonpmarino** [comment]
@emloux for sure!!! got to have a little spice :)

**Comment by jonpmarino** [comment]
@ischneider @emloux Also, the links are wrong for how to. They go to wiki links with How to (notice t in to is not capitalized). They should go to the links above, which has a capital T in To. This is important, as it points to a different wiki page currently.

**Comment by drwelby** [comment]
Ready for dev with latest changes

**Comment by jonpmarino** [comment]
It looks like it points to wrong How To link. See exact links above. The T in How To needs to be capitalized in the URL or else it will point to the wrong wiki page.

**Comment by drwelby** [comment]
It's not on dev yet. Let me get rid of those tags.

**Comment by jonpmarino** [comment]
Cool. Sorry about that Marc!

**Comment by ischneider** [comment]
Deployed to dev. Sorry for the delay.

**Comment by jonpmarino** [comment]
@ischneider @drwelby @emloux  noticed one more small thing. On Dev, it looks like clicking How-To directly still directs to the old link with small "to", http://wiki.mapstory.org/index.php?title=How_to. Should direct to http://wiki.mapstory.org/index.php?title=How_To. Otherwise, looks good to go!

**Comment by drwelby** [comment]
Sorry, missed it in the main nav. It's fixed and ready to deploy to dev.

**Comment by jonpmarino** [comment]
@drwelby thanks!

**Comment by ischneider** [comment]
Deployed to dev.

**Comment by emloux** [comment]
Verified on prod.
