### ISSUE TITLE
Give some visual feedback when adding a favorite.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#817]
Favorites are now used by organization pages to set the layers and users. So they're actually used now. But there is no visual feedback. Would be good to show something when clicking. 

This is tested on both the layer/map pages, and through the search interface.

**Comment by ischneider** [comment]
@drwelby the favorites listing on the left _should_ be reloading but it probably makes sense to give some fading effect to the new bookmark. This will most likely require returning the id of the new favorite (if one is created, as it checks for dups) and including the ids in the favorites HTML. Ping me for more details.

**Comment by ischneider** [comment]
Ready for testing.
As @cholmes noted, this is for the search page as well as the layer/map page (under the 'add' tab).

**Comment by emloux** [comment]
Verified
