### ISSUE TITLE
Label values don't 'stick'

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#818]
Like #798 the 'label value' drop down no longer sticks. Pretty sure this is a regression with all the great new changes. It still is there, but it doesn't display that it's there. Like the column you're using as your label value.

**Comment by bartvde** [comment]
i am quite sure it's always been like this but i'll look into it anyway 2morrow

**Comment by bartvde** [comment]
it seems this happens because the label can be an expression, e.g.: 

`↵                            ${STATE}↵`

at least that's what I am seeing.

**Comment by bartvde** [comment]
Although in the XML it is a plain PropertyName:

```
 <ogc:PropertyName xmlns:ogc="http://www.opengis.net/ogc">STATE</ogc:PropertyName>
```

**Comment by bartvde** [comment]
Ah I see what happens there is a lot of whitespace around it:

```
<sld:Label>
                            <ogc:PropertyName xmlns:ogc="http://www.opengis.net/ogc">STATE</ogc:PropertyName>
                        </sld:Label>
```

**Comment by bartvde** [comment]
Though when it is saved by the client there is no whitespace:

```
<sld:Label><ogc:PropertyName xmlns:ogc="http://www.opengis.net/ogc">DATE</ogc:PropertyName></sld:Label>
```

but I guess because of formatting we get the whitespace:

```
                        <sld:Label>
                            <ogc:PropertyName>DATE</ogc:PropertyName>
                        </sld:Label>
```

**Comment by bartvde** [comment]
see: https://github.com/openlayers/openlayers/pull/1048

**Comment by bartvde** [comment]
since this requires upgrading to the latest OL, it now depends on: #748

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/1dc8e80ba70102366e8559e385b9f3487ab7ce62

**Comment by bartvde** [comment]
seems this got deployed on dev already

**Comment by emloux** [comment]
Looks good, ready for deploy
