### ISSUE TITLE
enable crons on help.mapstory.org

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#820]
There are 3 cron jobs to support sending emails:
- send_unanswered_question_reminders - reminder emails about unanswered questions. It probably makes sense to send these weekly.
- send_accept_answer_reminders - reminding users to accept answers. Probably weekly
- send_alerts - any non immediate email. Should run daily.

**Comment by ischneider** [comment]
Configured. Emails set to go out weekly for reminders and daily mail setup to run at 20:00 UTC.

Note to self: check logs + verify

**Comment by emloux** [comment]
I received an email update yesterday.  @ischneider I think we can close this as implemented unless you need to leave it open.

**Comment by ischneider** [comment]
I'll close for now. There should be weekly reminders that go out Monday - I have a reminder set to check on Monday ;)
