### ISSUE TITLE
Put announcement about help.mapstory.org on main site.

### ISSUE THREAD

**Issue by cholmes** [MapStory/mapstory-meta#822]
As soon as possible we should put an announcement on the main site about help.mapstory.org

I wrote a message for this, but it needed a fix to put url's in it. So we should probably just hotfix it on production so we can have this up before we do all the site changes.

Priority for this goes down if it doesn't get done before we do all the site changes. But right now there's no way for a normal user to figure out that help exists.

**Comment by ischneider** [comment]
Deployed hotfix and announcement to production. Closing this. Reopen as needed for any tweaks.
