### ISSUE TITLE
annotations do not show up in viewer

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#824]
Thanks for these improvements, it's coming along nicely.

Looks like we got Betsy successfully making a map with it, see http://mapstory.dev.opengeo.org/maps/340/view/

But it appears that the annotations don't show up in the map pages full screen mode: http://mapstory.dev.opengeo.org/maps/340/#full

**Comment by bartvde** [comment]
currently the annotations store is managed by ms-notes-manager but this tool is not in the viewer (also the viewer had outdated annotations config)

**Comment by bartvde** [comment]
the functionality that automatically expanded the timeline in the viewer where there are annotations needs to be restored as well

**Comment by bartvde** [comment]
original implementation was here: https://github.com/opengeo/gxp/commit/fd01739e27117aaab2644a8b67a2016a8fd16cc9

**Comment by bartvde** [comment]
actually this still works fine (to my own surprise)

**Comment by bartvde** [comment]
should be done with: https://github.com/opengeo/geonode/commit/77342bc41ec2340bb37f46db4036bc7ba9757b90

**Comment by bartvde** [comment]
deployed on dev but not working on the provided map, will investigate more

**Comment by bartvde** [comment]
ah it was merely a browser cache issue, working now AFAICT

**Comment by cholmes** [comment]
Looks great.
