### ISSUE TITLE
allow for missing end date

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#827]
See http://help.mapstory.org/question/106/what-happens-if-i-dont-specify-an-end-date/

**Comment by bartvde** [comment]
@ischneider for my understanding, does this influence both the uploader and the playback, or just the playback?

**Comment by ischneider** [comment]
I was unclear, @bartvde 

This issue is related to the importer and potentially geoserver - the former should allow a blank during ingest, the latter should behave correctly when a blank is present.
