### ISSUE TITLE
Divide flag tool text boxes into 3 sections with updated prompts

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#829]
@emloux @sshyu @ChristopherTucker Updated specification for Flag Tool changes based on intern and team discussion. Also refer to #830 (need admin tool to control who gets notifications) and #783 (flag notifications should be able to contain hyperlinks...

Right now we have one big text box under flag with a general prompt for "flag content that is inappropriate, broken or otherwise". Break this single text box into 3 boxes. Each box should have same functionality - text, with ability to hyperlink, and a 'flag' button at the bottom.

Box 1 should read "See something that is broken? Flag it."

Box 2 should read "See something that is inaccurate? Flag it."

Box 3 should read "See something that seems inappropriate or illegal? Flag it."

Each prompt text should have an orange question mark icon at the end that will link to a page on the wiki with more information about what is meant by these fields.

Here are the links:

For broken - http://wiki.mapstory.org/index.php?title=Curation_Guide#Flagging_Content_as_Broken

For inaccurate - http://wiki.mapstory.org/index.php?title=Curation_Guide#Flagging_Content_as_Inaccurate

For inappropriate - http://wiki.mapstory.org/index.php?title=Curation_Guide#Flagging_Content_as_Inappropriate

**Comment by ischneider** [comment]
See https://github.com/MapStory/mapstory/issues/830#issuecomment-22658823 for the design.

**Comment by ischneider** [comment]
deployed to dev. @jonpmarino is this what you were thinking?

marking ready for testing. scrumdo - I'll beat you up if you change this :hankey:

**Comment by jonpmarino** [comment]
Do we still have it so that only registered users can flag? In dev it looks like I can use the tool even if I'm not logged in

**Comment by ischneider** [comment]
Only registered users can flag. If you attempt to flag anonymously, it will redirect to login and then there will be an error :warning:

If we want to keep flagging to registered users, then we should hide that tab. Please create a new issue if this is the case.

**Comment by emloux** [comment]
Ready for deploy
