### ISSUE TITLE
Editing with Time 

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#83]
Expand the editing capabilities as completed in ticket #82 to include the ability to create vectors by time slice, and vice versa.  IN other words, a user should be able to add/edit start and end dates when adding or modifying features.

**Comment by bartvde** [comment]
@awright Are you referring to annotations here? Since this is what annotations can already do, they have start_time and end_time fields. Please clarify or close.

**Comment by awright** [comment]
I think annotations covers this requirement. Let's close it out.
