### ISSUE TITLE
Create tool on 'admin' for administrators to manage Flag Tool notification recipients

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#830]
We need a tool on admin that enables administrators to see and control who receives 'flag error' tool notifications...and to extend that power to users who have that designation.

**Comment by ischneider** [comment]
Just a potential implementation note:

We're currently listening to the content_flagged signal and sending email to all 'staff' users. we could modify the code to send to all user's in a 'moderator' group.

This would fit nicely with the concept of enabling moderator permissions for adjusting comments, etc. though the latter would still require more effort.

**Comment by jonpmarino** [comment]
Creating a moderator group sounds like a wonderful solution. In long-run strategy we'll have to disaggregate what a 'staff' is/does and what some editors will be able to do. Pushing flag into a moderator group is a great first step towards that.

**Comment by ChristopherTucker** [comment]
should have ability to create more than one moderator group.  right?

**Comment by ischneider** [comment]
In django parlance, staff means the user can access the admin area. If the user is not a superuser, specific permissions must be given out to allow access to specific models.

We can create any number of groups and assign permissions to the group that are inherited by group members - this part is 'simple'. We then must implement specific checks for those permissions to have any effect - this is harder.

@ChristopherTucker what are you envisioning one moderator group do differently than another?

**Comment by jonpmarino** [comment]
Here's what I want/envision...

Right now we have one big text box under flag with a general prompt for "flag content that is inappropriate, broken or otherwise". I'd like to see this broken into 3 boxes..."flag broken content", "flag inappropriate content", and "flag inaccurate content". Each prompt has links to a wiki page about what we mean by these terms. Inappropriate means anything that is legally troubling (DMCA, etc. or folks think is obscene, whatever). These flag notifications then can be directed to appropriate moderator groups... developers moderator group (broken), policy oriented group (inappropriate) and a content accuracy moderator group(s) (inaccurate). All notifications go to the staff group.

**Comment by ChristopherTucker** [comment]
I agree with jon.

**Comment by ChristopherTucker** [comment]
To answer @ianschneider, there may be a need (ultimately, but not now) to have different tiers of editors with special privileges.  i am not sure whether this is different from a moderator group.

**Comment by ischneider** [comment]
Cool, makes sense.

**Comment by ischneider** [comment]
Starting to revisit this:

Having different categories of flags and groups is a good idea. @jonpmarino, when you mention 3 boxes, are these radio buttons or separate text areas? It would probably be clearer to do the former.

It's probably useful to also support something beyond just notifications in the admin interface. This would be a view on 'open' (unresolved) flags by the viewer's group membership.

The flag module we're using also supports some workflow via a 'status' label (broken, inappropriate, incorrect). My thought is when a flag is created, it has one of the 3 categories. When resolved, a new status label is used (rejected, invalid, etc.) as needed. Unfortunately, a flag can only hold one 'status' so if we wanted to track resolved flags by the original status, some additional work would be needed.

**Comment by jonpmarino** [comment]
Great. Glad this is moving. As we get more content its imperative we have the ability to responsibly monitor content! 

I love the idea of a status workflow for folks to be able to monitor. Your workflow makes sense...issue is marked as either "broken content, inappropriate content, or inaccurate content" upon report. When addressed, it gets marked "resolved".

Here's what I'm envisioning for the user interface. I want users to be able to click one of the three options (broken, inaccurate, inapporpriate), to be able to add some more contextual info, and to be able to visit the Curation Guide (which will live on wiki) to learn more about expectations around content.

![test9912](https://f.cloud.github.com/assets/2573761/964300/d0c957a2-0513-11e3-9647-530b4980591a.jpg)

**Comment by ischneider** [comment]
@jonpmarino I have something to show on the admin front. Not complete, but ready to take a look at. We should do a screenshare. Perhaps tomorrow?

**Comment by jonpmarino** [comment]
you da man! name your time...

On Thu, Sep 5, 2013 at 5:30 PM, Ian Schneider notifications@github.comwrote:

> @jonpmarino https://github.com/jonpmarino I have something to show on
> the admin front. Not complete, but ready to take a look at. We should do a
> screenshare. Perhaps tomorrow?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MapStory/mapstory/issues/830#issuecomment-23903237
> .

## 

Jonathan Parnell Marino
(815) 222 9088

**Comment by ischneider** [comment]
Did a refresh from what we discussed on Friday. Still might need some tweaks to what permissions are needed for content moderators.

**Comment by emloux** [comment]
Marking Ready for Deploy
