### ISSUE TITLE
Project Page

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#838]
@emloux Based on idea that emerged during Dev Conference...would like to create a 'project page' that is identical to Organization Page design but does not receive a simple customized URL...so, mapstory.org/project/randomstring. This is to maintain the desirability of going for an Organization Page with a custom URL directly at mapstory.org/orgname

**Comment by ChristopherTucker** [comment]
Jon, are you sure that we want to let them have a project name after the random string?  I think that is to be avoided.

Chris
703-981-9373

**Comment by jonpmarino** [comment]
Yes, right. URL slug convention needs to be determined...the more random the better. Amended ticket above.

**Comment by jonpmarino** [comment]
Addressed by Initiative and Org pages embodied in redesign
