### ISSUE TITLE
Specification to include Rubber Sheeting

### ISSUE THREAD

**Issue by awright** [MapStory/mapstory-meta#84]
Feature spec and estimate for including rubber sheeting capabilities (as seen in WorldMap).  This would let people upload maps and scan from them.  Cholmes originally recommended this, and Chris Tucker has asked us for where this feature falls in our development roadmap. I have suggested we provide him with a work plan at the beginning of the new year but that we don't recommend including this new feature in our February beta launch.

**Comment by awright** [comment]
this is something to address in geonode in general. it's not clear (to dwins) how time would be applied in these maps.  if specifying a date range in the upload process, we'll need to animate in a different way than current data.

**Comment by cholmes** [comment]
Closing this, as we're going to have warper.mapstory.org and get a workflow for people to go through that. Probably will want a specification at some point in the future, but let's just do that when it comes.
