### ISSUE TITLE
investigate gwc cache not being emptied on style changes

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#840]
We've ( @cholmes and I) noticed this on several layers. Both via geoserver interface and modification in GXP.

What we've seen is that during playback, previously cached tiles (by time) are not getting cleared when the style is changed.

**Comment by bartvde** [comment]
@ischneider is it feasible to put this in the current milestone or not?

Reading the description, it seems you have verified that it wasn't browser cache causing this but actual server-side cache?

**Comment by ischneider** [comment]
serendipity: https://github.com/geoserver/geoserver/pull/337
