### ISSUE TITLE
annotations: set id on insert

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#844]
if you create a new annotation, save it, then edit and save again, a duplicate annotation is created. This is because the id is not present in the second POST. Of course you don't have an id since I wasn't returning them ;) As per my other email, returning ids on creation is implemented now.

**Comment by bartvde** [comment]
the fix was simple but took me a while to figure it out, see: https://github.com/opengeo/geonode/commit/c0c77a377e7b4ce1f94957cc10f89bda4415c47a

**Comment by bartvde** [comment]
cc @ischneider since he reported this one

**Comment by ischneider** [comment]
Looks good, @bartvde 

Deployed to dev. Marking ready for deploy.

**Comment by ischneider** [comment]
This still occurs when a geometry is present. To duplicate, create a new annotation and before saving, add a geometry. Then edit again.

**Comment by bartvde** [comment]
I can't reproduce locally @ischneider this is what I do:
1. create new annotation
2. add geometry
3. save
4. edit title
5. save again

I see no duplicates.

**Comment by bartvde** [comment]
ah sorry I do see them after reloading the map

**Comment by bartvde** [comment]
ah okay I see the issue in the code, the state will be set to UPDATE in this specific case, the code should only do this is if it wasn't INSERT already IMHO lemme verify the fix

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/9526bd358762b1ba21ccaebee1dc076e5750f24d pulled in with https://github.com/opengeo/geonode/commit/d14fee0806257294bc05d6f17d239b4274e00e48

@ischneider can you test again (btw your testing is very thorough and helpful, I can learn from that), not yet deployed to dev btw. TIA.

**Comment by ischneider** [comment]
Sorry, should have mentioned the reload :poop:

Looks like this fix handles it.

**Comment by emloux** [comment]
Marking ready for deploy
