### ISSUE TITLE
ability to provide empty dates for annotations

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#845]
Leaving a blank start or end date seems to work when editing but on reloading the page, the value appears as 12/31/1969 (I verified it's not transmitted in the JSON)

**Comment by bartvde** [comment]
I can confirm this issue exists

**Comment by bartvde** [comment]
somehow setValue in gxp extended date field gets called with 0

**Comment by bartvde** [comment]
in the Ext record start_time and end_time has values of 0, not sure why this is as yet

**Comment by bartvde** [comment]
okay because it is an integer field, the empty string gets changed into 0

**Comment by bartvde** [comment]
ah there is a magic setting I did not know about:

```
    /**
     * @cfg {Boolean} useNull
     * <p>(Optional) Use when converting received data into a Number type (either int or float). If the value cannot be parsed,
     * null will be used if useNull is true, otherwise the value will be 0. Defaults to <tt>false</tt>
     */
    useNull: false
```

**Comment by bartvde** [comment]
should be fixed with: https://github.com/opengeo/geonode/commit/949e803e79f0e61b31c0dc8de66e6c59125b2f7d

cc @ischneider since he reported this

**Comment by ischneider** [comment]
Verified this works. Deployed to dev and marking ready.
