### ISSUE TITLE
geometries not dealt with in annotations playback

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#846]
geometries do not appear in the map unless the editor is brought up and then do not appear to be controlled by time

**Comment by bartvde** [comment]
the editor has a grid and featurestore which controls the layer, I assume this is okay.

But what's missing is for the geometries to show up in playback, right @ischneider ?

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/ab4e13ca3ce513c9b07b442e5eacaa50366fbcae not yet pulled in

Also one issue: if a record / feature is selected in the row editor, the geometry will stay selected even after closing the annotations editor, will fix this at the application level

gxp change also needs to be pulled in

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/650b28f48ff93592d7580ee2b94f3c63e95a5d16

**Comment by bartvde** [comment]
btw this should also fix point 4. raised by @ischneider 

4) it might be confusing to show all annotations when the editor is up though this is a bigger topic. either way, when the editor is hidden, all annotations should be hidden and only those visible at the current time should be visible.

**Comment by ischneider** [comment]
Nice work @bartvde 
Verified and deployed to dev, marking ready.
