### ISSUE TITLE
appearance should take precedence over geometry

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#847]
For annotations with a geometry:
- the default location is next to the geometry (current behavior)
- if the user selects another location for the annotation, then the annotation appears in the selected location
- one of the options in the "Annotation Location" dropdown is "Next to `{name of geometry}`" -- this represents the default option.

Note: as @bartvde mentions below, when the annotation is positioned near its associated geometry, the position is the centroid of the geometry.  So may need to update the label of the "Next to ..." option.  TBD

---

if a geometry is present AND the user chooses an appearance, it seems like the latter should take priority. right now it seems like the annotation appears on the first vertex(?) of the line or polygon

**Comment by bartvde** [comment]
@ischneider in this case, should the geometry still be shown on playback?

**Comment by bartvde** [comment]
this is a potential diff:

```

diff --git a/src/script/widgets/TimelinePanel.js b/src/script/widgets/TimelinePanel.js
index 6d80f31..0fd4e37 100644
--- a/src/script/widgets/TimelinePanel.js
+++ b/src/script/widgets/TimelinePanel.js
@@ -640,7 +640,7 @@ gxp.TimelinePanel = Ext.extend(Ext.Panel, {
             scope: this
         };
         if (!this.tooltips[fid]) {
-            if (!hasGeometry) {
+            if (!Ext.isEmpty(record.get('appearance'))) {
                 this.tooltips[fid] = new Ext.Tip({
                     cls: 'gxp-annotations-tip',
                     maxWidth: 500,
@@ -648,7 +648,7 @@ gxp.TimelinePanel = Ext.extend(Ext.Panel, {
                     title: record.get("title"),
                     html: this.buildHTML(record)
                 });
-            } else {
+            } else if (hasGeometry) {
                 this.tooltips[fid] = new GeoExt.FeatureTip({
                     map: this.viewer.mapPanel.map,
                     location: record.getFeature(),
@@ -665,11 +665,11 @@ gxp.TimelinePanel = Ext.extend(Ext.Panel, {
         }
         var tooltip = this.tooltips[fid];
         tooltip._inTimeRange = true;
-        if (!hasGeometry) {
+        if (!Ext.isEmpty(record.get('appearance'))) {
             // http://www.sencha.com/forum/showthread.php?101593-OPEN-1054-Tooltip-anchoring-problem
             tooltip.showBy(this.viewer.mapPanel.body, record.get("appearance"), [10, 10]);
             tooltip.showBy(this.viewer.mapPanel.body, record.get("appearance"), [10, 10]);
-        } else {
+        } else if (hasGeometry) {
             this.annotationsLayer.addFeatures([record.getFeature()]);
             if (!tooltip.isVisible()) {
                 tooltip.show();

```

But also there is currently no way to clear the appearance once it has been set.

**Comment by ischneider** [comment]
My thought is the geometry would still be shown but the appearance would place the actual label. 

Not critical functionality but it might be useful.

**Comment by bartvde** [comment]
waiting for feedback from @sshyu before implementing this one

**Comment by sshyu** [comment]
@bartvde -- added some initial notes in the ticket (though have not had time to think through all details yet).  Do you have any questions based on what I have there so far?

**Comment by bartvde** [comment]
in the Google doc you mean right? That seems like good feedback, I can work on that.

Btw, it's not really "next to a feature's geometry" but on its centroid (or what OpenLayers calculates as the centroid)

**Comment by sshyu** [comment]
I added some notes there but also more in this ticket (in the main summary at the top).

Re: positioning of annotation -- ah ok.  So if I had a large polygon (say a square), the annotation would be placed in the center of that square?  To be more specific: the lower left-hand corner of the box would be positioned at the center of the square?  Trying to see if there's a better/more accurate label we could use.

**Comment by bartvde** [comment]
@sshyu is it really important that the option reads "next to {name of geometry}" ? I assume with {name of geometry} you mean point/line/polygon? Or is a general "next to geometry" also okay (much easier)?

**Comment by bartvde** [comment]
@sshyu currently the topleft corner of the box will be at the centroid (but this can easily be changed)

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/d1e66e9ffcf911ff511dffd5f5324bb279f930a7 pulled in with https://github.com/opengeo/geonode/commit/2a0a1278d5d57b2f7378b6e36b28faee225bed46

**Comment by bartvde** [comment]
deployed on dev

**Comment by sshyu** [comment]
@bartvde thanks!  "Next to geometry" is OK.

Couple updates
- "Next to geometry" should only appear as an option if the annotation has a geometry.
- When it appears as an option, it should be the first option in the list.

**Comment by bartvde** [comment]
At least the first one is likely non-trivial but I'll see what I can do

**Comment by bartvde** [comment]
looking into this now

**Comment by bartvde** [comment]
the editor combobox is reused between rows

**Comment by bartvde** [comment]
been looking into this for a while now but no success as yet unfortunately

**Comment by emloux** [comment]
Looks good, ready for deploy

**Comment by sshyu** [comment]
@bartvde - following up from our earlier discussion, if the user specifies "Next to geometry" and the annotation does _not_ have a geometry, can we default it to the upper right-hand corner?  (Same default when they don't specify a location for the annotation.)

**Comment by bartvde** [comment]
@sshyu this should be implemented, are you seeing something else?

**Comment by sshyu** [comment]
@bartvde - didn't have a chance to test it yesterday, but I see this now.  Thanks!
