### ISSUE TITLE
today button should be now and use the current playback date

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#848]
i can't recall if you noted this before with the 'today' button in the time chooser but it would be nice to make that 'now' and have it take the current time from the dimension control. I know it does this for a new annotation (and this makes a huge difference) but for editing an existing value, it would be nice.

**Comment by emloux** [comment]
@bartvde Can this be addressed in Bentonville, or a future milestone?

**Comment by bartvde** [comment]
let's aim for Bentonville we can always move it out if it doesn't make it in the end

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/959565842e588d06e3629feccbdb59128e67bb87 pulled in and used with: https://github.com/opengeo/geonode/commit/78ce0ad84c15c892c5bc5e8f53cf86a37ea79396

**Comment by bartvde** [comment]
this is now ready for testing @ischneider

**Comment by ischneider** [comment]
Looked good to me, @bartvde. Marking for testing.

**Comment by DanielJDufour** [comment]
When I press the now button, the date entered into the annotation and the date appearing right above the playback bar do not agree:
![image](https://f.cloud.github.com/assets/4313463/1017020/7a5448d2-0c07-11e3-846b-7b4ee40a360e.png)
Time zone problem??

**Comment by bartvde** [comment]
Seems to be a timezone problem indeed, looking into it now

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/a8e49f6a4b16ce9115216fe76c55268e9005c943

**Comment by bartvde** [comment]
@DanielJDufour deployed the fix on dev can you test? For me it solves the issue. Btw the currently selected date in the picker had the same issue.

**Comment by DanielJDufour** [comment]
Pressing "now button" works now. Thanks

**Comment by emloux** [comment]
Ready for Deploy
