### ISSUE TITLE
Protect someone from clicking insert when an insert is in progress

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#850]
Clicking insert multiple time results in bad state. Probably best to disable/do-nothing when editing a record.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/8e748ac5303323d4d07746166b91235bcd7e2139

**Comment by bartvde** [comment]
deployed on dev

**Comment by emloux** [comment]
@bartvde looks good, however the pop up message appears below the insert dialog.  Any way we could get the error message to display over top of the dialog?

**Comment by bartvde** [comment]
ah right good point how could I have missed that will fix

**Comment by bartvde** [comment]
the row editor gets z-index 11000 and the message box is somewhere in the 9000s

**Comment by bartvde** [comment]
okay I had missed this since for me the messagebox was being displayed outside of the grid editor ;-)

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/b1e33be1fd97608175a2af0f3d1103bf5ecec703

**Comment by emloux** [comment]
Looks good, Marking Ready for deploy
