### ISSUE TITLE
Geometry disappears when creating new annotation

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#851]
While adding a polygon, it is visible until the final vertex (double-click) and then it disappears until save is pressed

**Comment by bartvde** [comment]
okay this was introduced when I added the check for not changing the state to UPDATE when it's INSERT

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/44c126502b39b5c75d317cb34b31ff493cb37851 pulled in with https://github.com/opengeo/geonode/commit/e2b231a1083a618e42cde8acb23e9561c95b30c6

**Comment by bartvde** [comment]
deployed on dev

**Comment by emloux** [comment]
Ready for deploy
