### ISSUE TITLE
Bad state in annotation editor after adding a geometry

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#852]
After adding one geometry, bad state results and an error occurs:
TypeError: control is undefined
var map = this.map || control.map;

It looks like this happens because a control is not passed in to the constuctor in handleAddGeometry() ??
this.drawControl.handler = new handler();

**Comment by bartvde** [comment]
thanks @ischneider your suggested fix was very close: https://github.com/opengeo/gxp/commit/95be5bf804763db42181fa95bc6e380e48a0ae67 pulled in with https://github.com/opengeo/geonode/commit/b30195128bb19a3df594161fd4ed36656b2e3ee7

**Comment by bartvde** [comment]
deployed on dev

**Comment by emloux** [comment]
Ready for Deploy
