### ISSUE TITLE
Add a prompt for deleting an annotation

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#853]
Add prompt for deleting:
are you sure? 
[ ] don't ask again
ok | cancel

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/1210d6eaec882f14049860f14137c7506f973765

I did make a small change to the UI, there is a checkbox in the toolbar which controls whether or not the prompt should appear (this was easier than what @ischneider suggested), the value of the toolbar is not persisted (cookie) currently.

**Comment by bartvde** [comment]
deployed on dev

**Comment by emloux** [comment]
Looks good, marking ready for deploy
