### ISSUE TITLE
Support multiple / batch delete in annotations editor

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#854]
Would it be easy to add a 'check box' column and support multi delete? I can batch delete via the DB API but others can't ;)

**Comment by bartvde** [comment]
it is also already multiple select (with shift and ctrl buttons) but the delete code doesn't currently handle this, will add this

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/a3b805442a95b43d2291a79a913815c82efee757 and https://github.com/opengeo/geonode/commit/461800b7ceb5b183b4974149d8a9e7d9c2fbd34a

**Comment by bartvde** [comment]
deployed to dev

**Comment by emloux** [comment]
@bartvde this is working with ctrl shift, but there are no checkboxes displaying.

**Comment by bartvde** [comment]
checkboxes is not the way Ext handles this by default. It uses shortcuts like on any operating system, I thought this was fine and did not put effort into adding checkboxes to do exactly the same?

**Comment by emloux** [comment]
@bartvde, makes sense marking ready for deploy.
