### ISSUE TITLE
Issue with height of annotions dialog when there are many annotations

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#855]
There is some oddness in the dialog here - it gets 'stuck' at the bottom of the page:
http://mapstory.dev.opengeo.org/maps/208/view/

Probably should configure a maximum row count ;)

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/be47a853d2340e280bc88bf0669b7458f5a0a9ba

**Comment by bartvde** [comment]
deployed to dev and tested

**Comment by emloux** [comment]
Looking good, ready for deploy
