### ISSUE TITLE
annotations should be kept in sync in composer

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#862]
currently, when people add annotations in the composer, they don't show up in the timeline immediately and are not available for playback until the page is reloaded

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/6c7f63340f5a1c5c0c4bb20daee508316de92ecc pulled in with https://github.com/opengeo/geonode/commit/8ac7eb96259d8bb2e91832efc3ae42e095df661c

**Comment by bartvde** [comment]
deployed on dev - ready for testing

**Comment by ischneider** [comment]
@bartvde looks good to me, marking ready for deploy. Feel free to change status if something else comes up.
