### ISSUE TITLE
issue with dragging windows in the composer

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#863]

**Comment by bartvde** [comment]
See: https://github.com/openlayers/openlayers/blob/master/notes/2.13.md#map-property-fallthrough-defaults-to-false

**Comment by sshyu** [comment]
@bartvde - yes, this issue seems to happen primarily when the window is over the map or playback toolbar.  I've only done a little testing, but the issue does not seem to occur over the other areas of the page.

**Comment by bartvde** [comment]
see: https://github.com/geoext/geoext/pull/79 pulled in with https://github.com/opengeo/geonode/commit/e9e60acee58a51d07e6459ce2c611cd43d1ba9c7

**Comment by bartvde** [comment]
deployed on dev - ready for testing

**Comment by sshyu** [comment]
Thanks @bartvde.  From initial testing on dev, this is working much better now!  Haven't been able to reproduce the issue.

**Comment by ischneider** [comment]
Also verified a huge improvement, thanks @bartvde 

Marking ready for deploy

**Comment by bartvde** [comment]
thank @ahocevar instead he identified the cause ;-)
