### ISSUE TITLE
annotations should not cover the playback toolbar

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#864]

**Comment by bartvde** [comment]
okay this is because defaultAlign on Ext.Tip is a value we don't provide in the combo, will fix

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/6ef6a4cc8d409ec352ffe00159a8bfef9fa7223f pulled in with: https://github.com/opengeo/geonode/commit/7a8e619f4b5a0cc6df202c5e9e7ff0f1c47025cb also changed default align to be one that we support by default in the combo

**Comment by bartvde** [comment]
let me know if the default value does not make any sense @sshyu @ischneider it's now align the bottom left of the tip with the bottom left of the map (bl-bl) so it should not cover the playback toolbar anymore.

deployed on dev

**Comment by sshyu** [comment]
Thanks @bartvde!  The location of these depends on the content and design/layout, but a lot of them seem to have them on the right (from some quick research).  So can we default to the upper right hand corner?

**Comment by bartvde** [comment]
sure that's an easy change

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/79496f0587f4e98db3b932ca2d201489aa50aa95

**Comment by emloux** [comment]
Looks good, ready to deploy
