### ISSUE TITLE
Logging in from editor view does not work

### ISSUE THREAD

**Issue by sshyu** [MapStory/mapstory-meta#865]
**Steps to reproduce**
- Go to a map's editor view when not logged in.  Use a map that you have permissions to edit or login using an admin account.  [Example](http://mapstory.dev.opengeo.org/maps/360/view/)
- Enter username and password; sign in
- Notice the following bugs:
  - the site shows that you're logged in, but (if you have permissions to edit the map), it does not show you those additional options (like the annotations button).
  - the header shows "Signed in or signed in" (A) on the right instead of indicating that you're signed in (B).  
  - the header is also taller than it should be.
  - the header does not show the name of the map.

(A)
![image](https://f.cloud.github.com/assets/2131145/916811/466d16fc-fe97-11e2-98f2-ad260dd034f5.png)

(B) 
![image](https://f.cloud.github.com/assets/2131145/916823/a94c6728-fe97-11e2-9e4c-5865ae6bb3d6.png)

**Expected behavior**
- After you sign in, you see:
  - the header appears properly (see B, above)
  - if you have permissions to edit the map, you can access the controls to edit the map

**UI bugs**
- The "username" and "password" fields are the same color as the background color and are not readable
- "Sign In" button should appear equal to the buttons for the alternate sign in options.  Make the font larger and increase the padding to match.  Colors TBD.
- "Forgot your password?" should not be next to the other sign in options.  Move to the right, below the "Sign In" button.  Make the font smaller (12pt).

![image](https://f.cloud.github.com/assets/2131145/916728/b387f93e-fe95-11e2-98d3-84625fbbb82b.png)

**Comment by bartvde** [comment]
the first issue is for me (the annotations button does not show in this case), what other buttons are you missing @sshyu ?

**Comment by bartvde** [comment]
@ischneider any chance the login function can call setAuthorizedRoles with the new roles on the composer instance?

**Comment by sshyu** [comment]
@bartvde, I think that's the only button.  I'm not familiar with all the functionality yet, so I'm not sure if everything else works/saves properly after you login in this scenario.  I did some initial/basic testing, and it seems like it is so far.

**Comment by ischneider** [comment]
> @ischneider any chance the login function can call setAuthorizedRoles with the new roles on the composer instance?

@bartvde I'll take a look and see

**Comment by ischneider** [comment]
This stuff would all be much easier to address if we redirect to the login page with a return context of the map.

The problem with this of course is that we allow people to start to create a map without being logged in so they'd lose their work. I can address a few of these issues withs some CSS, but there are more problematic ones that IMHO offer small returns for their cost - like dealing with the login/logout button state and 'welcome' and the permissions stuff.

My personal preference would be that if someone arrives at the editor and is not logged in, we immediately let them know they will not be able to save their changes unless they are logged in (and provide the link to the login page with redirect context page to 'new map')

**Comment by sshyu** [comment]
@ischneider - that makes sense.  So is the below doable:
- user who is not logged in goes to editor view in browser (either a new map or an existing map)
- user does _not_ see the editor view; instead the user is redirected to login page with message: "Please login to use the editor."
- after user logs in, user is directed to the new map editor or the editor with the existing map loaded (same as whatever they requested originally)

**Comment by ischneider** [comment]
@sshyu what you mention is quite doable and makes sense since we're really promoting the 'info' page viewer (like `maps/<id>` versus `maps/<id>/view`)

Along those lines, perhaps we do the standard security check we're using on other pages and bounce the user if they don't have permissions to edit?

**Comment by sshyu** [comment]
If the user requests `maps/<id>/view` and they are not logged in, we can redirect them to `maps/<id>/view` after they login right?  (The idea is to take them to whatever URL they put in originally, since we can't know their intent.)

As far as the standard security check: sounds like that should work.  Is there a way I can try that out?  (Not sure if there are some variations on it--want to make sure I get the standard one :))

**Comment by ischneider** [comment]
> If the user requests maps/<id>/view and they are not logged in, we can redirect them to maps/<id>/view after they login right? (The idea is to take them to whatever URL they put in originally, since we can't know their intent.)

Correct. The builtin django view annotation does this in one small line of code ;)

> As far as the standard security check: sounds like that should work. Is there a way I can try that out? (Not sure if there are some variations on it--want to make sure I get the standard one :))

Log out and then visit, for example: http://mapstory.dev.opengeo.org/maps/314/

[Granted our existing not-permitted/401 page sucks and has never been updated from the 'stock' geonode page]

**Comment by sshyu** [comment]
Sounds good.  Any chance we can make some updates to the page that shows up when you're not logged in?  The important part (the message about not being able to access it because you're not logged in) is one of the least prominent items on the page.  Would also be good to work in a link to the login directly.

If there's an easy way for me to make some of those changes, I'm happy to do them too.

**Comment by ischneider** [comment]
Deployed to dev - the 'map editor' views all require login.
