### ISSUE TITLE
when creating annotations on maps/new, the timeline does not bind to the annotations store

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#866]
Save a new map, then add an annotation, it does not show up in the timeline

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/306f2473075c130e2d953291552951627ec56065 pulled in with: https://github.com/opengeo/geonode/commit/b13062d2e0e5a3a61d0f539df41017cf185c3fb9

**Comment by emloux** [comment]
Marking Ready for Deploy

**Comment by emloux** [comment]
Verified on Prod
