### ISSUE TITLE
Add link to wiki explaining star rating tool

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#867]
@emloux Small win. Want to create an orange 'question mark' after the 5th star in 'Rate this MapStory'. See image. Scroll over text would read "Learn more". Question mark should link to

http://wiki.mapstory.org/index.php?title=Curation_Guide#Ratings

![grab1](https://f.cloud.github.com/assets/2573761/918642/3bc2eec2-feb8-11e2-9a4b-c8f0ffc96953.jpg)

**Comment by ischneider** [comment]
Just a thought that we might want to have all the outbound wiki (or any?) links tracked somewhere to help verify their existence. I could see doing this in a model which would allow admin interface management (only for existing links) or in some kind of 'link dictionary' in python since it will take template changes to actually use a 'named' link.

**Comment by jonpmarino** [comment]
Makes sense for sure

**Comment by ischneider** [comment]
See #888

**Comment by ischneider** [comment]
Deployed to dev. Marking ready for testing.

**Comment by jonpmarino** [comment]
Nice! Someday let's have that cute little Learn More guy all over the place! :)

**Comment by jonpmarino** [comment]
@ischneider curious how the cumulative rating for a layer is defined? Some kind of average of individual ratings, I assume?

**Comment by ischneider** [comment]
Thanks! The html template code is easy enough:

`{% wiki_help_link 'curation_guide_ratings' classes='pull-right' %}`

:cake:

**Comment by ischneider** [comment]
Yes, the overall rating is the average.

**Comment by jonpmarino** [comment]
Cool. A thought I have for future is to be able to 'weight' some users' rating ability...essentially giving their rating more power for editorial purposes. No action now, but could pose an interesting dilemma.

**Comment by ischneider** [comment]
We'd probably have to do some major surgery to the module we're using to support a weighted rating. OTOH, the 'popularity' sort in search uses a weighted (views \* average rating) for ordering.

**Comment by jonpmarino** [comment]
Nice. All good for now I'd say.

**Comment by emloux** [comment]
Looks good, marking ready for deploy
