### ISSUE TITLE
Change text on 'complete your profile' notifications

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#869]
@emloux @ischneider Want to make small text changes to the notification for users to complete their profile.

![grab123](https://f.cloud.github.com/assets/2573761/921086/3b0582c6-feed-11e2-82ed-ea3e220f8a85.jpg)

Change from:

"Your profile is incomplete. Please ensure the following fields are complete: X, Y, Z"

To:

"Take a second to complete your profile! Currently you're still missing: X, Y Z"

**Comment by ischneider** [comment]
Deployed change to dev and ready for testing.

**Comment by jonpmarino** [comment]
Looks good on dev!

**Comment by emloux** [comment]
Verified on Prod
