### ISSUE TITLE
labeling priority field does not persist/save

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#870]
This came up here and I can reproduce: 

http://help.mapstory.org/question/168/why-is-label-priority-not-saving/

**Comment by bartvde** [comment]
see: https://github.com/openlayers/openlayers/pull/1073

**Comment by bartvde** [comment]
merged in dimNGfresh and pulled into mapstory with: https://github.com/opengeo/geonode/commit/ef124b3a5e43c533ccfb20e7a86ce4c6330d6b9d

**Comment by bartvde** [comment]
deployed on dev just now

**Comment by emloux** [comment]
Ready for Deploy
