### ISSUE TITLE
don't leave unfinished insert in place when closing dialog

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#872]
See: http://help.mapstory.org/question/169/why-am-i-getting-another-insert-in-progress-error/?answer=177#post-id-177

When somebody pressed Insert and then closes the dialog, it will be in an incorrect state.

**Comment by bartvde** [comment]
should be fixed with: https://github.com/opengeo/geonode/commit/03030489d5a6be8d318f459960c136c348106591

**Comment by emloux** [comment]
Looks good, Marking ready for deploy

**Comment by emloux** [comment]
verified on prod. closing
