### ISSUE TITLE
pressing Cancel can delete another annotation

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#873]
to reproduce: open up the annotations mgr on a new map. Press insert, create a new one and save. Then press insert again and press cancel. The previously created annotation will be deleted from the grid, not the one in progress.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/674d18d7a03f7cdbe4f5bcdb0f97507cc6421466

**Comment by bartvde** [comment]
this was reported as well by @ischneider

**Comment by emloux** [comment]
Looks good, marking ready for deploy

**Comment by emloux** [comment]
Verified on Prod
