### ISSUE TITLE
add bulk upload of Storypins

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#874]
cc @ischneider

**Comment by bartvde** [comment]
see also #580 for the backend work which was done I believe

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/1bc1247c3abb2d78a9680729555b908ebfbd69e1

buttons hidden until content-type of response on upload gets changed to text/html

**Comment by jonpmarino** [comment]
@ischneider can we amend the error message for this to say "We're sorry but a servor error has occurred. Administrators have been notified and will look into it as soon as possible. Visit help (hyperlink to help.mapstory.org) for more support."

In general, for any error messages on the platform I'm trying to avoid leaving people without an action to take. Now that we have help.mapstory.org we can just send people there.

![bulkuploaderror](https://f.cloud.github.com/assets/2573761/927603/138a8884-ffa3-11e2-901c-783aa8cab1d3.jpg)

**Comment by ischneider** [comment]
@jonpmarino I created #875 to reflect this as the message is for all 500 errors (unhandled server error)

Related to CSV specifically, I'm about to deploy some better error handling ;) - caveat: there will be blood, er bugs

**Comment by ischneider** [comment]
@bartvde the prompt for opening/saving the download shows some interesting URL encoded names and the file appears to actually save with a random name. The content-disposition header provides a nicer name (as you can see from the headers or visiting the download link directly).

Not sure if this is a blocker but it is a bit confusing/unfriendly.

**Comment by bartvde** [comment]
the weird url is because it uses: http://en.wikipedia.org/wiki/Data_URI_scheme

Data URIs do not carry a filename as a normal linked file would. When saving, a default filename for the specified MIME type is generally used.

**Comment by jonpmarino** [comment]
@ischneider could we sqeeze in a link to the Manual documentation for using media in annotations inside the new annotations uploader box? It seems the documentation is still relevant and would give us a quick fix for helping users know how to add video and image for time being - http://mapstory.org/mapstory/manual/#using-media-in-annotations. If its intensive, we can hold off as a hot fix for next Bentonville

**Comment by jonpmarino** [comment]
Here is screenshot of where text could go. Text can just be 'Learn more'. Hyperlink 'more' to direct to http://mapstory.org/mapstory/manual/#using-media-in-annotations

![test123](https://f.cloud.github.com/assets/2573761/933563/15669d62-0059-11e3-8dd0-7637127c9506.jpg)

**Comment by bartvde** [comment]
@jonpmarino I added this in: https://github.com/opengeo/geonode/commit/f3c9addb900f7ce4141677fbfeeffc7932f6aeca

**Comment by emloux** [comment]
closing

**Comment by jonpmarino** [comment]
We need to add some directions to users on how their bulk-upload CSV must be formatted. I suggest adding a section to Manual on 'bulk upload' and providing a link in the upload dialogue box as specified below....similar to what we did with 'adding media to annotations'. We could title this link simply, "Learn more"

![test12311](https://f.cloud.github.com/assets/2573761/948751/0774ce68-036f-11e3-90df-7cfc8a31274d.jpg)

**Comment by ischneider** [comment]
deployed to dev

**Comment by emloux** [comment]
Verified on dev.

**Comment by jonpmarino** [comment]
@ischneider can we change the link here to http://wiki.mapstory.org/wiki/How_To#How_to_Annotate_Stories. Want to be able to add more descriptive text and link to a downloadable test data set. Thanks!

**Comment by ischneider** [comment]
deployed to dev

**Comment by zrouse-Boundless** [comment]
This should use existing uploader
