### ISSUE TITLE
constrain annotations window so it cannot go astray

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#876]
http://help.mapstory.org/question/195/lost-annotations-window/?answer=196#post-id-196

**Comment by ischneider** [comment]
@bartvde you probably already know this, but adding `constrain:true` to the window init properties seems to handle this. This has annoyed me as well :+1:

**Comment by bartvde** [comment]
right I know ;-)
I never move the window out, but I'm too experienced with Ext maybe .... I've learned my lesson in the past

**Comment by bartvde** [comment]
fixed with https://github.com/opengeo/geonode/commit/9ed900957c17ceb083737ca77d2ab3dc08ae1afa

**Comment by emloux** [comment]
Marking Ready for Deploy
