### ISSUE TITLE
in embed timeline cannot be collapsed

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#878]
reported here: http://help.mapstory.org/question/207/timeline-issues-in-embed/

e.g.: http://mapstory.dev.opengeo.org/maps/340/embed

**Comment by bartvde** [comment]
in here there is the timeline button: http://127.0.0.1:8000/maps/130/#full

**Comment by bartvde** [comment]
so embed should get the timeline button as well

**Comment by bartvde** [comment]
fixed with: https://github.com/opengeo/geonode/commit/211100c53225926bd15348da8493b13cb7fecb78

**Comment by DanielJDufour** [comment]
In embed I cannot (or I can't figure out how to) collapse the timeline:
![image](https://f.cloud.github.com/assets/4313463/1017093/c7c86ac0-0c08-11e3-813a-f301c5c7a37b.png)
From: http://mapstory.dev.opengeo.org/maps/288/

**Comment by bartvde** [comment]
@DanielJDufour doesn't pressing the Timeline button work for you? It should toggle (collapse/expand).

**Comment by DanielJDufour** [comment]
Okay. It's working now.  I'm not sure why it wasn't working before, but if I run into the problem again, I'll let you know.

**Comment by emloux** [comment]
Ready for Deploy
