### ISSUE TITLE
Change default screen new user sent to after activation to "Create Profile"

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#881]
Currently when a new user creates an account the workflow is this: 
1. sign-up
2. receive activation email
3. Activate account
4. Taken to mapstory.org homepage

This results in few people taking immediate action to complete their profile.

A simple change we can make is to send the user directly to their complete profile page, such as http://mapstory.org/profiles/edit/ after they've activated their account for the first time.

This is a small client-side fix.

**Comment by ischneider** [comment]
Deployed to dev.

**Comment by jonpmarino** [comment]
Ian, just tested. It looks like you get sent to profile page directly after creating username/password and agreeing to terms. Would it be better to send them to 'create profile' after clicking activation email? Do we want them creating profiles before they've validated their account via the email?

**Comment by ischneider** [comment]
Thanks for testing that @jonpmarino . I was using a short-cut to test this, so I missed this unintended behavior. Back to the drawing board :)

**Comment by ischneider** [comment]
@jonpmarino, there was a missing setting on dev. This appears to be corrected now. Can you try again?

**Comment by jonpmarino** [comment]
@ischneider looks like it works now!

**Comment by ischneider** [comment]
Thanks for testing again, @jonpmarino. Marking ready for deploy.
