### ISSUE TITLE
Add internal links to doc resources to improve user experience

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#882]
We can achieve much higher user satisfaction if we do a better job of linking to How-To and Help across the platform. I don't want this to delve into design specifics which we know will change. But a few simple links to help new users feel less frustrated for the next few weeks will go a long way...especially now that we have Help, How To and Manual straightened out.

Here are priority areas:
- [x] see #867
- [x] In http://mapstory.org/data/upload/, add a link to help.mapstory.org under "report issues at help if you're experiencing problems, and add a link to How-To under "add go to How-To for tutorials on loading StoryLayers successfully"
- [ ] In the edit MapStory viewer, add links to Help, How-To and Manual in bottom right (see screenshot)

![12345](https://f.cloud.github.com/assets/2573761/965642/a0f7e45a-052f-11e3-85ab-e1fd7582b0a8.jpg)

**Comment by ischneider** [comment]
@jonpmarino added the links to the upload page.

@bartvde I looked at implementing the links in the viewer but couldn't find a good way quickly.

**Comment by bartvde** [comment]
@ischneider I'll handle this part of the ticket

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/0182919409f8eb9fa3dad534fc2a5c3e9d37709c

**Comment by ischneider** [comment]
@bartvde this doesn't work so well when creating a new map - the links end up in the middle with other tools pushed to the right

**Comment by bartvde** [comment]
good call @ischneider had not tested that will fix

**Comment by bartvde** [comment]
this is because the playback toolbar is only outputted once the first time-enabled layer gets added

**Comment by bartvde** [comment]
@ischneider should be fixed with: https://github.com/opengeo/geonode/commit/53af92fc49ab2cce82968cc243925878772eaa89

**Comment by jonpmarino** [comment]
@bartvde could we have these links open up to a new window rather than take the user away from their MapStory composer?

**Comment by bartvde** [comment]
sure that's an easy change will do

**Comment by emloux** [comment]
closing

**Comment by bartvde** [comment]
@emloux why was this closed? The last request by @jonpmarino has not yet been handled.
