### ISSUE TITLE
why not have 'full screen' be truly full screen?

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#883]
A user can always minimize the map to see the header and other information....in full screen mode I suggest we remove the banner altogether.

This is an example of this in practice - http://roadskillmap.com, http://demographics.coopercenter.org/DotMap/index.html

**Comment by jonpmarino** [comment]
@ChristopherTucker @sshyu @ischneider what do you think of this? Seems a simple way to make full screen pop a little more. User can always minimize back to view with abstract, StoryTeller info, and header.

**Comment by sshyu** [comment]
I think updating the full screen view on these lines would be an improvement!

**Comment by ischneider** [comment]
Makes sense to me. @bartvde, assigning to you.

**Comment by jonpmarino** [comment]
@ischneider @bartvde would it be possible to add a minimize X button to the header in full screen, so the header is defaulted ON but can be clearly/easily minimized. This would be ideal solution.

**Comment by bartvde** [comment]
Will commit something for this soon

**Comment by sshyu** [comment]
@bartvde - please hold off a moment.  Jon and I were just wrapping up some discussions we had on this (just now), which may impact your work.  Wasn't aware work was happening on this yet, otherwise would have said something sooner.

**Comment by bartvde** [comment]
okay was basically done, so hope things don't change too much ;-)

**Comment by bartvde** [comment]
the question I had though if this should only show up when somebody visits a link that is already fullscreen, or also when somebody switches to fullscreen? I assumed the first.

**Comment by bartvde** [comment]
Putting my patch here for further reference, won't commit anything now:

```

diff --git a/src/geonode-client/app/static/script/app/GeonodeViewer.js b/src/geonode-client/app/static/script/app/GeonodeViewer.js
index d65075d..cbd43d4 100644
--- a/src/geonode-client/app/static/script/app/GeonodeViewer.js
+++ b/src/geonode-client/app/static/script/app/GeonodeViewer.js
@@ -160,6 +160,16 @@ var GeonodeViewer = Ext.extend(gxp.Viewer, {

             if (this.embed !== true) {
                 this.toggleMapSizeViaUrl();
+                if (this.fullScreen && !this.embed) {
+                    var close = Ext.DomHelper.append(Ext.get('header'), {tag: "button", cls: "close", html: "x"});
+                    Ext.get(close).on('click', function() {
+                        Ext.get('header').setVisibilityMode(Ext.Element.DISPLAY);
+                        Ext.get('header').hide();
+                        Ext.get('top-crossbar').setVisibilityMode(Ext.Element.DISPLAY);
+                        Ext.get('top-crossbar').hide();
+                        this.expandMap();
+                    }, this);
+                }
             }

             if (this.embed === true) {
```

**Comment by sshyu** [comment]
@bartvde, thanks for waiting.  So after discussing this issue @jonpmarino, it turns out the desired/best solution to what we're trying to do here will be part of #898.  In #898, we'll add the ability for the user to view more information about the MapStory (similar to the "i" button on YouTube) -- and as part of that work, we can make the header a lot smaller in full screen view.

So for this ticket, nothing needs to be done.  Sorry for the mixup, Bart.

**Comment by bartvde** [comment]
so we can close this @sshyu ?

**Comment by sshyu** [comment]
@bartvde: yes, we can close this now.
