### ISSUE TITLE
manage annotations window should be above annotations

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#884]
http://help.mapstory.org/question/227/how-can-i-stop-my-annotations-from-covering-my-manage-annotations-window/

**Comment by bartvde** [comment]
fixed with: https://github.com/opengeo/geonode/commit/f5f920d826491c34b2e8723731cfdfcf8c7e333c

**Comment by bartvde** [comment]
make sure the row editor is still visible: https://github.com/opengeo/geonode/commit/af416273e472c5bcbb483da06c21e0a2210be58d

**Comment by bartvde** [comment]
more issues: all fields in the editor are also below now

**Comment by bartvde** [comment]
so this needs more work

**Comment by bartvde** [comment]
maybe we should go back and revisit this change: https://github.com/opengeo/geonode/commit/c8beb86a695e0868248d95acc3fb44229d26ad43#src/geonode-client/app/static/theme/app/geoexplorer.css

**Comment by bartvde** [comment]
changed the approach: https://github.com/opengeo/geonode/commit/eb1205b77a1dfba1f6d3fdf8c9758a0b293a2fd0

**Comment by emloux** [comment]
Marking Ready for Deploy
