### ISSUE TITLE
better max height handling for annotations

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#885]
http://help.mapstory.org/question/229/how-do-i-prevent-my-annotation-from-expanding-outside-the-viewing-window/

**Comment by bartvde** [comment]
maybe add a body cls but needs more work:

```
bodyCssClass: "gxp-annotations-body",
```

```
.gxp-annotations-body {
    max-height: 200px;
    overflow-y: scroll;
}
```

**Comment by bartvde** [comment]
gxp change: https://github.com/opengeo/gxp/commit/ed53ed0b15a5c9cd5f680659352b7384409ab9bc pulled in with: https://github.com/opengeo/geonode/commit/5f182c25ff8114f8885aa6b96b6adfe281236bc5 and template change
see: https://github.com/MapStory/mapstory/commit/fe2158b8e21dd1d8244a6ecdc6306f5b5f9b087c

**Comment by bartvde** [comment]
@ischneider how do I deploy the template changes on dev?

**Comment by ischneider** [comment]
@bartvde the `integration` branch is being used for deployment so just merge whatever (master or a branch) in there. I just did this so you're all set.

**Comment by bartvde** [comment]
this needs a bit more work, also youtube videos are 250 by 250 pixels by default which should also differ for the mode probably

**Comment by bartvde** [comment]
it's hard to find the perfect solution for all situations

**Comment by bartvde** [comment]
see: https://github.com/MapStory/mapstory/commit/ab7814f1fdf6afd7280f45bdb235e9136ec41674 and https://github.com/opengeo/geonode/commit/5567405b1725b04d7b43f2e25a2b3ee7d0c33566
