### ISSUE TITLE
Embedded View - Update Settings, Timeline UI

### ISSUE THREAD

**Issue by sshyu** [MapStory/mapstory-meta#886]
Prerequisite: #577 

**In analysis, _not_ ready for dev**

For the embedded view of MapStories:
- show a smaller and simplified settings dialog
  - must fit within an embedded view as small as TBD px by TBD px.
- add gear icon back - user accesses the settings dialog using this
- the dialog will have the following options:
  - time range (start time, end time)
  - playback mode
  - loop animation
  - reverse animation
- remove the little bar/button used to open the timeline
- add an icon to toggle the timeline on the toolbar
- reduce the space that the timeline takes up (based on height)
  - to discuss: allow user to disable timeline button
  - button is disabled (details TBD) if the map doesn't have any timeline data

For all MapStory views (per discussion with Jon):
- default is for animations to _not_ loop
  - this is standard behavior across the web
  - this will save server and client resources (esp. important on mobile and laptops)
  - for cumulative maps, this will allow users to see and explore the completed map
- remove the loop animation button (can be controlled via settings dialog)

**Comment by jonpmarino** [comment]
Based on feedback from a session with Fund for Peace....Embed should acquire similar functionality to YouTube, as evidenced here at top right (the 'i' information button) - http://friendsofthearc.org/. This would give us the ability to provide a viewer with the MapStory title, abstract, and perhaps StoryTeller and datasources. They are concerned with having some way in viewer to always link back to the original data source.

**Comment by sshyu** [comment]
The enhancement that @jonpmarino describes in his above comment is covered in #898
