### ISSUE TITLE
StoryLayer Metadata UI Tweaks

### ISSUE THREAD

**Issue by emloux** [MapStory/mapstory-meta#887]
As mentioned by @jonpmarino in #693 

@drwelby @ischneider @sshyu @emloux @ChristopherTucker The interns and I propose the following changes to StoryLayer metadata for the short term...all should be straightforward html UI fixes. I'm not sure where were restricted with ISO 8601 standards, though. So feel free to rebuff on those grounds. This probably breaks into multiple issues, and encompasses #563.

Make the default view of a StoryLayer set to the 'info' tab clicked on. Currently default shows abstract only. Idea is to give the viewer immediate knowledge of additional context available and to draw the eye to other interactivity that can be done with Style, Share, etc. See image:
test1

Change 'Supplemental Information' to 'Data Source'. Change prompt text to read: "Indicate where you got your data. Include hyperlinks to the original data source if available."

Change prompt text under "Data Quality Statement" to read: "Discuss what your data includes beyond what appears in your StoryLayer or MapStory, limitations of the data, methods you employed for processing it, licensing and terms of use, and the names of columns in your attribute table"

An orange 'question mark' should be added at the end of each metadata field's prompt text that hyperlinks to the wiki where we'll explain more about what we are looking for. Here are the hyperlinks for each:

Title - http://wiki.mapstory.org/index.php?title=Curation_Guide#Title
Keywords - http://wiki.mapstory.org/index.php?title=Curation_Guide#Keywords
Abstract - http://wiki.mapstory.org/index.php?title=Curation_Guide#Abstract
Purpose - http://wiki.mapstory.org/index.php?title=Curation_Guide#Purpose
Data Source - http://wiki.mapstory.org/index.php?title=Curation_Guide#Data_Source
Data Quality Statement - http://wiki.mapstory.org/index.php?title=Curation_Guide#Data_Quality_Statement
Topics - http://wiki.mapstory.org/index.php?title=Curation_Guide#Topics

Add rich text editor functionality to text boxes so user can easily add bold, italics, bullets, hyperlinks, etc....

**Comment by ischneider** [comment]
The main issue with allowing markup is that iso-19139 does not allow for embedded HTML in many fields. We _could_ strip these while generating the XML but often this is a lossy operation.

**Comment by jonpmarino** [comment]
Makes sense. The only field we'd really be interested in having this in is the proposed new "Author's Notes" field, which isn't part of the iso-19139 framework. Perhaps we could limit it to that? This is actually better anyway.

**Comment by ChristopherTucker** [comment]
More important I think is to have brief explanatory text in grey in each field that tells the user what kind of stuff each field is for.  There are enough flexible fields inside iso19139 to allow us to say something like "Think of this field as Author's Notes that explain the purpose that you or the author had in mind when generating this StoryLayer.  This can include HTML hyperlinks to additional online resources that aid your explanation." 

We need these for each.  I wrote them up 2-3 years ago when we discussed metadata editor originally.  Would have to dig them up.

**Comment by jonpmarino** [comment]
Agreed. We have this prompt text proposed above for each:

-Change 'Supplemental Information' to 'Data Source'. Create gray prompt text to read: "Indicate where you got your data. Include hyperlinks to the original data source if available."

-Create gray prompt text for "Data Quality Statement" to read: "Discuss what your data includes beyond what appears in your StoryLayer or MapStory, limitations of the data, licensing and terms of use, and the names of columns in your attribute table."

-Create a new text field should be added below Data Quality Statement entitled "StoryTeller Notes". The gray prompt text should read "Add any additional information you'd like to share with the viewer about this data and the process you undertook to develop it".

**Comment by drwelby** [comment]
I've covered the UI changes in https://github.com/MapStory/mapstory/pull/905

Adding the "StoryTeller Notes" should probably be moved to a new ticket - we need to decide how this differs from "Abstract" and how to fit it in with the existing metadata format and data model.

**Comment by jonpmarino** [comment]
@drwelby sounds good. I'll create the new ticket now. The way we saw it is that Abstract provides a more universal/objective description of the content...StoryTeller Notes provides a separate place for a StoryTeller to provide commentary on more subjective topics they want to discuss...i.e. what challenges did they encounter when producing this MapStory? What unique methods did they employ? Who else do they especially want to acknowledge that supported the work? We've found that users want to share this information and for now we've put them in blog.mapstory.org. See this as an example - http://blog.mapstory.org/2013/07/12/ranking-peacekeeping-operations-can-we-do-it/. I want to keep as much of this on the platform as I can, and think the StoryTeller notes space can accomplish it for us. Blog should be more about feature updates, events, etc...not this content rich/relevant stuff which should be with the content on MapStory.org.

**Comment by jonpmarino** [comment]
@ischneider can we also increase the size of the abstract text box so its bigger than 2 lines? Perhaps 8-10?

**Comment by ischneider** [comment]
Adjusted to 8 rows. Note that all fields _should_ be adjustable - just drag the little draggy thing.

![workspace 1_032](https://f.cloud.github.com/assets/794512/1097145/f64b1f2e-170b-11e3-9159-1b21f55594d0.png)

**Comment by jonpmarino** [comment]
right on! should have known. that's awesome. still think default size change is smart. thanx

**Comment by ischneider** [comment]
To be clear, I did adjust it to 8 rows :smile:

**Comment by jonpmarino** [comment]
confirmed. looks good.

**Comment by emloux** [comment]
marking ready for deploy
