### ISSUE TITLE
create means for managing and refering to outbound wiki and other links

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#888]
We don't want to have these scattered all over the templates or codebase. It would be nice to have them in one place and refer to them in shorthand. This would support changing them and verification via a tool.

For example, in the templates:

`{% ext_url "wiki" "Curation_Guide_Title" %}` would render `http://wiki.mapstory.org/index.php?title=Curation_Guide#Title`

`{% ext_link "wiki" "Curation_Guide#Title" "See the curation guide"  %}` would render an actual html link with the provided text in the 3rd arg.

As for managing the links, starting with a simple dict structure of category (e.g. "wiki"), an optional prefix (e.g. "http://wiki.mapstory.org/index.php?title="), and a dict of named links (e.g. "Curation_Guide_Title") and their associated URL path fragment (to be appended to the prefix) or absolute URL.

**Comment by drwelby** [comment]
+1 on this.

**Comment by ischneider** [comment]
@drwelby can you revisit previous work with wiki links and use the new template tags?

**Comment by ischneider** [comment]
@drwelby forgot to note I implemented this in ad5a285

**Comment by drwelby** [comment]
Changed out all the current links in https://github.com/MapStory/mapstory/commit/ede895a2759015d2eec27212b8d6d7007fde216c
