### ISSUE TITLE
annotation start/end date get local timezone offset

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#889]
It looks like the formatted date in the annotations editor is getting a timezone applied to it.

As reported here: http://help.mapstory.org/question/232/why-does-upload-change-my-annotation-dates/

The response from the service is 725846400 and this corresponds to UTC 1993-01-01.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/7b030d3c4fd1a2e2a0f47fa3beba467c66625abb pulled in with: https://github.com/opengeo/geonode/commit/42a1dcbdc03114110926c9b6bb1e45a81b1e5834

**Comment by bartvde** [comment]
this seems to be causing side effects for me. E.g. I create an annotation with June 3rd but end up with June 2nd

**Comment by bartvde** [comment]
Hopefully this fixes the side effects: https://github.com/opengeo/geonode/commit/2b0c28cfa31fda7e31deab712aebdfeaf4bf9941
