### ISSUE TITLE
Saving maps while logged out does not error

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#89]
It doesn't work, but it doesn't tell the user about that.

**Comment by bartvde** [comment]
dwins: don't you get an Ext based login prompt after trying to save when logged out.

**Comment by bartvde** [comment]
I just tried this again, and this is the behavior I get: start up maps/new when logged out. Save the map. The form appears. Press Save. The requests returns a 401, the client comes back with a login prompt and after putting in the credentials the save is performed fine. So I don't really see an issue here with the current code-base.

Please reopen if I am misinterpreting anything here.
