### ISSUE TITLE
better 401 (unauthorized) page

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#891]
As discussed in #865

**Comment by ischneider** [comment]
@sshyu I took what existed in geonode and did a few small changes.

You could make changes here, though they'd be hard to 'test':
https://github.com/MapStory/mapstory/blob/master/templates/401.html

to test: http://mapstory.dev.opengeo.org/maps/314/

**Comment by emloux** [comment]
Marking Ready for Deploy

**Comment by emloux** [comment]
Verified on Prod
