### ISSUE TITLE
Add 'info' screen to MapStory embed and full-screen viewer

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#898]
Follow-up to #577

**In progress, NOT ready for dev yet**

**UX**
- [ ] Show map title in upper left-hand corner of embed.  
- [ ] Show info button 
- [ ] Clicking info button shows the below information, overlaid above the map.
  - Close button (closes info view)
  - StoryTeller details: name/organization, ...
  - First TBD words of the abstract, then truncated by an ellipsis
  - The data sources (extracted from ...?)
- [ ] Full screen view: make header smaller; include info button there as well

---

Currently a viewer in embed or full-screen mode has no way of seeing the title, StoryTeller, abstract or...most importantly...data sources for a MapStory without clicking back into MapStory itself.

As MapStories are increasingly shared around the web, it will be vital that we more easily provide this high-priority information to viewers.

As a solution, we suggest implementing something similar to the YouTube "i" button. See embedded YouTube video here for example, http://friendsofthearc.org/. This icon allows a viewer to see basic information immediately.

For us, we would want to try and locate the following information here:

-MapStory title
-StoryTeller name
-Data Sources

Data Sources is the most complex aspect here. Each MapStory is based on StoryLayers. Each StoryLayer has a place in the metadata for "Data Sources". We would want to pull the text from these data sources into this info viewer.

Again, the final product would be similar to the cited song in the video here - http://friendsofthearc.org/.

The alternative to creating an automatic workflow for this, which would seem quite complex, would be to simply require the MapStory author to complete this information somehow manually when publishing their MapStory as "public so anyone can view"

**Comment by sshyu** [comment]
@jonpmarino - another related enhancement: it seems like a MapStory could also have sources aside from the StoryLayers--e.g., the annotations may be supported via other sources.  Longer-term, maybe a MapStory should also be able to note those sources as well?

**Comment by jonpmarino** [comment]
@sshyu yes good point! We also need an "additional sources" text box in the MapStory metadata. Currently we have nothing for that...only the layers its based on. I will ticket.
