### ISSUE TITLE
Create annotations layer

### ISSUE THREAD

**Issue by dwins** [MapStory/mapstory-meta#9]
Let users make a new blank layer for use in GeoNode maps.  See opengeo/gxp#86

**Comment by bartvde** [comment]
Not sure if opengeo/gxp#86 is related for this ticket, but this info is: https://github.com/opengeo/mapstory/wiki/NotesLayers

**Comment by bartvde** [comment]
See also: https://groups.google.com/a/opengeo.org/group/dev-mapstory/browse_thread/thread/7f2c5f35594a386e?hl=en# for more info

**Comment by bartvde** [comment]
Started on this today, but waiting for the create layer endpoint to be finished.

**Comment by bartvde** [comment]
This part of annotations is working.
