### ISSUE TITLE
Create ability for admin to update/edit homepage essays

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#901]

**Comment by ischneider** [comment]
Deployed to dev. See the `admin` interface for access. I copied all the existing essays over. Note that images must be hosted elsewhere except that we're already hosting the existing images on production.

The `preview` button in the top left lets you see what the page will look like without having to save.

To prevent an essay from appearing, deselect the 'public' option. The front page essay list is cached for 60 seconds though this can be changed. Even if an essay is not public, it can be visited - this might be useful for previewing.

If needed, an admin group could be setup to allow staff (non superuser) access to the essays.

Markup is in textile. Reference:
http://redcloth.org/hobix.com/textile/

**Comment by emloux** [comment]
Looks good! Ready for Deploy
