### ISSUE TITLE
Add "Learn More" link to annotation bulk upload box

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#903]
Need to create a simple "Learn More" link at the bottom left of the bulk annotation upload box. For now this will link to a blog post that describes annotations and links to templates. Link forthcoming.

![bulk1](https://f.cloud.github.com/assets/2573761/1053272/974379c8-10ed-11e3-8fd2-b34feed7ae04.jpg)

**Comment by emloux** [comment]
@jonpmarino I think this might already be on dev.

**Comment by emloux** [comment]
Closing as this is a duplicate ticket

**Comment by ischneider** [comment]
This was originally reported here: https://github.com/MapStory/mapstory/issues/874#issuecomment-22507384
