### ISSUE TITLE
Amend and add to metadata fields for MapStorytelling

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#906]
Related to #887 

This ticket proposes 3 adjustments to the metadata requirements in the MapStory composer only...

-Add prompt text to the abstract field, as well as help link to more information, as is proposed for StoryLayer metadata fields in #887. 

Prompt text should read, "What is this MapStory about? What geography does it cover? What time period does it cover? Who are the actors involved in the story? What StoryLayers and other data are utilized? What point does the story seek to make?

-Change the MapStory "abstract" box to be titled "About" and change that text box to the same functionality of the org page about text - http://mapstory.org/mapstory-foundation/ - a jump, links....no need for images....wysiwyg editing would be great though for hyperlink, bold, etc.

-expand the size of the current Abstract text box so the person typing can see more than 2 lines...perhaps 8.

**Comment by drwelby** [comment]
Could this be covered by the comment system, with the author's comments getting distinctive presentation?

**Comment by jonpmarino** [comment]
@drwelby that could be a pretty ingenius idea. the concept is right...with the StoryTeller essentially reflecting on/commenting on their own work. Can we add the ability to upload images and have those rich text abilities in comments (bold, italic, hyperlink, bullets)?

**Comment by drwelby** [comment]
That sort of content smells more like a blog post, so it seems like there should be something existing that we could use to have a Narrative for storylayers and/or storymaps. It would be independent of the GeoNode stuff, so it would be separate from the metadata and anything GIS-related.

**Comment by jonpmarino** [comment]
@drwelby totally agree. I amended the ticket above. Upon reflection I realize this is really only directed at MapStories. StoryLayers don't need this additional info.

In the long run, our advanced MapStorytelling efforts will take care of alot of this. But for now (seeing as those changes may be awhile off) I do see merit in simply adding another text field below abstract in the MapStory metadata. See screenshot above.

As proposed, the MapStoryteller would essentially have 2 options...1. to complete an abstract designed to be purely 'descriptive' and brief like any journal abstract. A second text box for 'Contextual Information' would allow the MapStoryteller to add any links, personal reflections or acknowledgements that may not be appropriate for an abstract. Links could be to an external blog post, for example. Currently folks are putting this type of content in the abstract, which really doesn't make sense.

**Comment by ischneider** [comment]
@drwelby not sure shoe-horning some existing app in will be as easy as doing something our own on the django side. Basically just a content-type model to represent the content and any other attributes we want to hang on it (like modified_date) including a version (we could eventually allow versioned editing). By using a content-type, it could be attached to anything (including the profile). The biggest piece would be to have proper support for the editor and such. Perhaps this would help out in that respect: https://github.com/pydanny/django-wysiwyg

For the non-editor (determined by the same permissions as the layer/map), they just see a read-only view of the content and modified_date. For the editor, they get the nice wysiwig editor. The django form just extracts the content and sticks that into the content-type object updating the date. We layer some version control on later (just allow going back to N versions)

**Comment by drwelby** [comment]
@ischneider  Agreed - I need to look to see if it's easier to build something from scratch or shoehorn something and spend time customizing it. Content-types would be the obvious way to go, but after you add validation and wysiwig and image uploads and so on it seems like you've just written your own blogging platform. Knowing the exact feature  set would help in the decision - @jonpmarino?

**Comment by ischneider** [comment]
I don't think we want to get into the image management game. If we can support embedding external images, that should be enough to start with.

As for validation and wysiwig, not implying we develop those - just reuse them. Agreed understanding the desired features will help w/ component selection and/or development.

**Comment by jonpmarino** [comment]
@drwelby @ischneider i'm hesitant to drown you guys in too much work on this, especially if were going to be building some new advanced MapStorytelling features soon. 

In StoryLayer metadata, if we implement the other changes referenced in #887 we can definitely leave Abstract as-is. Its at the StoryLayer level that were concerned about ISO metadata anyway.

In MapStory, for time being I'm just interested in MapStorytellers doing a bit more description about the MapStory than were getting now with basic abstract.

Perhaps a very simple solution...

Could we just change the MapStory "abstract" box to be titled "About" and change that text box to the same functionality of the org page about text - http://mapstory.org/mapstory-foundation/ - a jump, links....no need for images....wysiwyg editing would be great though for hyperlink, bold, etc.
