### ISSUE TITLE
Enable playback to begin at "last frame"

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#909]
@ischneider, I'm interested in enabling a StoryTeller to set playback settings that would have the mapstory begin at "last frame" rather than the beginning. This would mean that the 'first look' by the viewer would be of the MapStory data in its final form. Hitting 'play' would bring the viewer back to the beginning of the content.

Does this sound possible?

I am looking to achieve essentially what is being done with these maps of buildings in cities color coded by year build, http://mobile.theverge.com/2013/9/2/4683912/interactive-map-plots-out-nearly-10-million-netherlands-buildings-by.

If data in our Local mapstories could show up by default at the "end", we'd basically accomplish what these are doing, plus give the viewer the ability to "play" their progression over time!

**Comment by jonpmarino** [comment]
@ischneider  another thought on this that is probably a separate issue, can the 'generate thumbnail' generate a thumbnail visual based on data in the final frame? this would give the viewer a full picture of what the data in the MapStory displays. At what point does the current thumbnail generator pull the data from? Is it random? Set to a default?

**Comment by ischneider** [comment]
> @ischneider another thought on this that is probably a separate issue, can the 'generate thumbnail' generate a thumbnail visual based on data in the final frame? this would give the viewer a full picture of what the data in the MapStory displays. At what point does the current thumbnail generator pull the data from? Is it random? Set to a default?

@jonpmarino, when the user presses the generate thumbnail button, whatever is in the current view is shown. This allows the user to figure out what looks best for the layer/map in question.

**Comment by ischneider** [comment]
Assigning to @bartvde for estimation.

**Comment by jonpmarino** [comment]
@ischneider @bartvde regarding thumbnail question. that's great! just tested creating different thumbnails based on different zoom levels and points in the data and it works well. Could we just make a small change to the prompt text, then, so that the user understands how they can use the thumbnail. I think alot of folks have created poor thumbnails because they weren't aware of this.

Change from "Generate a thumbnail for this MapStory"

to...

"Generate a thumbnail that will represent this MapStory when others search for it. To do so, first position your MapStory above at the zoom level and time sequence you would like, then click "Set thumbnail" below."

Issue of setting playback to start at 'final frame' is still a separate issue I'm interested in

**Comment by ischneider** [comment]
Opening #911 to reflect wording changes noted above
