### ISSUE TITLE
better thumbnail language

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#911]
From #909:

> Could we just make a small change to the prompt text, then, so that the user understands how they can use the thumbnail. I think alot of folks have created poor thumbnails because they weren't aware of this.
> 
> Change from "Generate a thumbnail for this MapStory"
> 
> to...
> 
> "Generate a thumbnail that will represent this MapStory when others search for it. To do so, first position your MapStory above at the zoom level and time sequence you would like, then click "Set thumbnail" below."

**Comment by ischneider** [comment]
The handling of this is currently different in layers and maps so I will include unifying the two as part of this.

**Comment by ischneider** [comment]
Deployed to dev and ready for review.

**Comment by jonpmarino** [comment]
reviewed. looks good.

**Comment by emloux** [comment]
Marking ready for Deploy
