### ISSUE TITLE
make annotation popups non floating again

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#912]
see: http://help.mapstory.org/question/283/why-is-my-annotations-placed-relative-to-top-of-visible-screen/?answer=306#post-id-306

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/825fede1b499a38d572f9126ba466f0e8437c389 pulled in with: https://github.com/opengeo/geonode/commit/b5f5fe6e6f4c8e3ced1f353da3b091d863ac7cb0

**Comment by bartvde** [comment]
this was not the complete solution to the problem.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/eb80181e86cb476f3fa28c289baf80868b79c126 pulled in with: https://github.com/opengeo/geonode/commit/1833c7d8500f036da765ac9912d9e2417e048f48

**Comment by emloux** [comment]
Marking Ready for Deploy

**Comment by emloux** [comment]
Verified on Prod
