### ISSUE TITLE
issue with resizing annotations window

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#914]
see: http://help.mapstory.org/question/267/how-can-i-resize-my-manage-annotations-window/

There is a maxHeight of 200 set on the grid, hence this issue.

**Comment by bartvde** [comment]
I am having trouble getting this to work like they want it to work

**Comment by bartvde** [comment]
okay this should work:

```
outputConfig: {width: 800, layout: 'fit', height: 200, constrain: true, closeAction: 'hide'},
```

and on the grid itself:

```
        autoWidth: true,
        autoHeight: true,
```

just a shame it took me so long to find out ;-)

**Comment by bartvde** [comment]
but still issues with scrollbars in this case ...

**Comment by bartvde** [comment]
something in gxp.Tool.addOutput is messing things up, since working with a straight Ext.Window with layout: 'fit' works okay.

**Comment by bartvde** [comment]
fixed with: https://github.com/opengeo/geonode/commit/3dd8e5f80f7e3332d45b68fe2357c45a1fdc73c0 please note that I decided to go around gxp.plugins.Tool.addOutput since the extra container in between is messing things up here

**Comment by emloux** [comment]
Marking Ready for Deploy

**Comment by emloux** [comment]
verified on prod
