### ISSUE TITLE
youtube video should stop if popup hides

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#917]
as reported here: http://help.mapstory.org/question/256/video-in-annotation-keeps-playing-after-annotation-disappears/

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/5278b9b598314b76b5a20d335ec22ba2dbf940b1 pulled in with: https://github.com/opengeo/geonode/commit/6532f379a4aca01ed3e20d7fbe7912e5c59b9af6

**Comment by emloux** [comment]
Ready for Deploy
