### ISSUE TITLE
Resize legend to fit  content

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#918]
For discussion...

Currently our legend box remains the same size no matter how much content is inside it. How difficult would it be to resize that legend based on content?

With current annotation placements, our legend is usually covered by annotations, like the example below. These leaves alot of wasted white space.

![tableofcontents](https://f.cloud.github.com/assets/2573761/1089219/023eb736-1640-11e3-86ea-50a10a9ed68d.jpg)

**Comment by drwelby** [comment]
The legend is in an Ext / GXP panel so @bartvde would be the one to ask.

**Comment by bartvde** [comment]
@jonpmarino how would the legend resizing to its content solve the issue with annotations? cc @sshyu

**Comment by jonpmarino** [comment]
@bartvde @sshyu this isn't a high priority, so shelve in favor of other items if need be. The idea was to have legend size-to-fit content...biased towards bottom right. So in the example above, the legend would only take up half of the screen height and wouldn't be hidden behind a top-right annotation. So far users seem to prefer the top right annotation most.

**Comment by bartvde** [comment]
thanks for the clarification @jonpmarino together with shifting the default position to bottom-right it makes sense

**Comment by bartvde** [comment]
done with: https://github.com/boundlessgeo/geonode/commit/edc2d194773d27f6c2babe3b8de63a9687e73105

**Comment by jonpmarino** [comment]
@bartvde sweet!

**Comment by bartvde** [comment]
deployed on dev for testing

**Comment by jonpmarino** [comment]
@bartvde testing and works beautifully. thanks!

**Comment by sshyu** [comment]
Thanks @bartvde!  Did some quick testing and looks good so far.  The only case that doesn't work so well is when the legend is too large to fit--it gets cutoff, and you can't see the rest.  I'm not sure how we handled this before this change.  Is it easy to make it scroll if this happens?

See http://mapstory.dev.opengeo.org/maps/360/ for an example.

**Comment by jonpmarino** [comment]
also, question. as I look at content on Dev it looks like we have some default that puts (c)openstreetmap in maps that use OSM layers as a watermark. I don't see this on Prod. Is that right? If so, what do you think about moving that to Prod?

Also, stylistically, that watermark gets covered by the date tooltip when you hit play...could be nice to move that watermark to the top left, maybe next to the zoom buttons or something.

See this example...bottom left in map.
http://mapstory.dev.opengeo.org/maps/407/#full

cc'ing @sshyu here for reference.

**Comment by jonpmarino** [comment]
@sshyu good catch! Can we set a media_query function that resizes legend to this height limit if it goes above?

**Comment by bartvde** [comment]
I'll look into the issues reported

@jonpmarino as part of the MapBox base layers I realized we did not show attribution, so I've corrected this. This will be part of the upcoming release.

**Comment by bartvde** [comment]
scroll issue with long legends addressed with: https://github.com/boundlessgeo/geonode/commit/9ec1d4211ec012443e3efe47c6e70071f6558bd2

**Comment by bartvde** [comment]
hmm still needs a few tweaks (e.g. when opening up the legend in full screen mode)

**Comment by bartvde** [comment]
some more tweaking done with: https://github.com/boundlessgeo/geonode/commit/8899289c6fd4df02653f4bfdbfce638255b490ce

**Comment by bartvde** [comment]
moved attribution to top left with: https://github.com/boundlessgeo/geonode/commit/abcc1103e036373e2552223afcd345e16ec882bc

**Comment by bartvde** [comment]
ready for testing again

**Comment by jonpmarino** [comment]
@bartvde on embed that attribution still shows up bottom left - http://jonpmarino.tumblr.com/

**Comment by bartvde** [comment]
@jonpmarino I think this is because I haven't updated the templates as yet on dev

**Comment by jonpmarino** [comment]
@bartvde cool. actually for me currently it looks like its top-left on Safari but not Chrome

**Comment by bartvde** [comment]
@jonpmarino if I look here it works for me: http://mapstory.dev.opengeo.org/maps/426/embed (maybe some forceful browser cache involved in Chrome)

**Comment by jonpmarino** [comment]
@bartvde cool! 

Question - do you think it'd be better to have the "watch in MapStory" button link back to the info page rather than the view page? The info page has the abstract and info about the storyteller and what not...probably the first thing we want to show them...

so, for example,

this - http://mapstory.dev.opengeo.org/maps/426/

not this - http://mapstory.dev.opengeo.org/maps/426/view/

**Comment by bartvde** [comment]
@jonpmarino I think that would make sense, it's an easy change so let me know

**Comment by jonpmarino** [comment]
@bartvde lets do it!

**Comment by bartvde** [comment]
done see: https://github.com/boundlessgeo/geonode/commit/ec417b29dd75ee4b279202240af3141b07a29c92

**Comment by DanielJDufour** [comment]
@ischneider 
Legend gets pretty big with all the new base maps, which conflicts with legends set to the top-right corner, so let's do this:
- start out with the Base Maps section of the legend minimized
- if you click to expand the base maps or storylayers in the legend, the legend section should move up (to fit the now expanded base maps section) and if in conflict with the annotations, the legend should cover annotations (change z-indexes).

**Comment by ischneider** [comment]
@bartvde is this doable?

**Comment by bartvde** [comment]
I got everything implemented except for the z-index of legend versus annotations, not sure why (maybe because it's a floating panel) but running out of time so I just did the other ones for now see https://github.com/boundlessgeo/geonode/commit/b2095f162f5079aa0fb9680be979054e10bf5daa

**Comment by bartvde** [comment]
deployed on dev

**Comment by DanielJDufour** [comment]
If you have time left, the legend should also resize horizontally to fit contents.  Or have text wrap.  There's a weird side scrolling thing when you expand the base maps section if "Humanitarian OpenStreetMap" (the longest worded basemap) is longer than your longest text under StoryLayers.  This is because the legend width is too small and doesn't adjust.
