### ISSUE TITLE
when creating an annotation, timezone should always be UTC

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#919]
If I create an annotation with my computer in MDT, with time 11:00 I get the value of 

new Date(1339174800*1000)
Fri Jun 08 2012 11:00:00 GMT-0600 (MDT)

however the 11:00 should be UTC instead.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/6018c42ae9fc45fd48c4be307cc90081b7612010 pulled in with: https://github.com/opengeo/geonode/commit/a74b13e4a7aae411b6f00a28adfff030f140f661

**Comment by bartvde** [comment]
needed an additional change: https://github.com/opengeo/gxp/commit/363382373e99231a19c1ca0db3fdeb082f182cac pulled in with: https://github.com/opengeo/geonode/commit/d34db1c2cdd3f7b41dd18bd7cce0942974f1155f

**Comment by emloux** [comment]
Verified on Prod
