### ISSUE TITLE
annotations download function is missing some separators

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#920]
this was reported here by Daniel and I've also seen this myself:

http://help.mapstory.org/question/328/why-is-tr-tr-in-my-in_timeline-column-on-download/?answer=331#post-id-331

So appearance values show up in the in_timeline field since empty values (in_map and in_timeline) don't seem to get the separator (,).

**Comment by ischneider** [comment]
deployed to dev, ready for testing

**Comment by emloux** [comment]
Verified on Prod
