### ISSUE TITLE
Set sizing defaults for Gear box in embed so it can be minimized

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#921]
A current quick fix to allow for basic embedding. Currently a user is unable to close the Gear box once it is opened in embed views of a standard size:

![test111](https://f.cloud.github.com/assets/2573761/1110841/13429238-199b-11e3-9c51-b59238cd989f.jpg)

We need to resize this default so that the box can be closed.

More extensive fixes to embed are forthcoming to #577 #898 #886, but this is a change hopefully we can make for now.

**Comment by bartvde** [comment]
see: https://github.com/opengeo/gxp/commit/7cacf0c8277fcc6701cd5a91b9d84cafa472a500 pulled in with: https://github.com/opengeo/geonode/commit/0e7e11925502ef83d9f60f9ef7bd436079732808

**Comment by bartvde** [comment]
this is ready for testing on dev

**Comment by emloux** [comment]
Marking ready for Deploy
