### ISSUE TITLE
annotations date format in CSV download cannot be re-uploaded

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#923]
The output would look like `y-m-dTh:m:s` but upon upload, parsing fails.

See: http://help.mapstory.org/question/245/why-do-i-get-unable-to-read-as-date-error-when-bulk-uploading-annotations/

**Comment by ischneider** [comment]
deployed to dev and ready for testing

**Comment by DanielJDufour** [comment]
Download and re-upload works fine now, except for two things: (1) when I enter only years for the start and end times in the manage annotations window, it seems to randomly select hours (I noticed this looking at the downloaded csv, but I'm guessing this is probably done before download.) and (2) my in_timeline correctly downloads as all false, but after re-upload all the timeline checkboxes are checked-off.  Maybe Timeline column is reading the in_map column by accident or there's some other bug. Here's a screenshot:
![checkofftimeline](https://f.cloud.github.com/assets/4313463/1117670/a64e335a-1a51-11e3-9f90-7f63d328e4e5.png)

**Comment by ischneider** [comment]
Thanks Daniel. I fixed the 2nd bug you mentioned. The 1st bug I cannot duplicate. I do see that some of the start or end times have an hour in them (like when I click on the row to edit) but I can't make the random appearance happen.

@bartvde see this: opengeo/geonode@33fe01b9fec40933d0e8359942c98f0c2e11c4ca - sorry about the whitespace changes, my editors were making me :)

**Comment by bartvde** [comment]
thanks @ischneider change looks good (I should have tested that change more thoroughly last night)

**Comment by emloux** [comment]
Verified, closing
