### ISSUE TITLE
daylight saving time issues

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#925]
see Daniel's last comment here:

http://help.mapstory.org/question/339/why-are-my-annotations-and-map-appear-to-be-on-different-dates/?comment=351#comment-351

this is a daylight saving time difference (1hr)

**Comment by bartvde** [comment]
see https://github.com/opengeo/gxp/commit/80738fbaaa4cbfa271442d347589f2c8131cfb4b pulled in with: https://github.com/opengeo/geonode/commit/1b9776d352cd22395d73b5dad08ef33a77b76585

**Comment by emloux** [comment]
Verified on prod.
