### ISSUE TITLE
Search page refresh

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#928]
#927 #742

-my favorites and MapStories in Progress shouldn't show up in search....but in Profile.

-use check-box filters under Type and Section. Allow multiple items to be checked simultaneously rather than one at a time.

-create a smart-populate text box, like we have with StoryTellers, for Keywords

**Comment by ischneider** [comment]
Closing as much of this should be addressed by changes in GeoNode. Please open new issue if needed.
