### ISSUE TITLE
change download so that filename of the server is used

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#929]
see also: http://help.mapstory.org/question/246/why-are-the-downloaded-annotations-not-formatted-as-a-csv/

**Comment by bartvde** [comment]
see: https://github.com/opengeo/geonode/commit/340b49ce7fb7df8da7467b6bc35967a26be14693 and https://github.com/opengeo/geonode/commit/d829392aac40f863f3e6ebbc5ff56560e9136c67

**Comment by emloux** [comment]
Marking Ready for Deploy

**Comment by emloux** [comment]
Verified, closing
