### ISSUE TITLE
add mapbox base maps

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#933]
see: http://help.mapstory.org/question/368/can-we-use-additional-basemaps/

**Comment by bartvde** [comment]
@DanielJDufour can you clarify which mapbox base maps you want to see? You can check out what we have available here: http://suite.opengeo.org/geoexplorer/composer/

Use Add layers and choose the mapbox source.

**Comment by bartvde** [comment]
to add:

```

bart-van-den-eijndens-macbook-pro:mapstory bartvde$ git diff settings.py
diff --git a/settings.py b/settings.py
index 3c7496d..cb901d1 100644
--- a/settings.py
+++ b/settings.py
@@ -215,7 +215,15 @@ MAP_BASELAYERS = [
         'group': 'background',
         'args': ['Satellite Imagery']
     },
-
+    {
+        'source': {
+            'ptype': 'gxp_mapboxsource',
+            'hidden': True
+        },
+        'name': 'geography-class',
+        'title': 'MapBox Geography Class',
+        'group': 'background'
+    }
 ]

 # use new uploader
```

**Comment by bartvde** [comment]
currently we don't have the attribution control, we need to fix this, also for MapQuest

**Comment by DanielJDufour** [comment]
I responded to your recent inquiries here: http://help.mapstory.org/question/368/can-we-use-additional-basemaps/

**Comment by bartvde** [comment]
https://github.com/MapStory/mapstory/commit/071705197a0c77509b89d48bc1b6b6ac7ceac563 adds the 4 mentioned MapBox base maps.

**Comment by bartvde** [comment]
HOT OSM added with https://github.com/MapStory/mapstory/commit/67e144eead8dfc31f05512c91a03a8ac142e356d btw not sure about the attribution

**Comment by bartvde** [comment]
@ischneider I've merged this into integration but unsure how to actually "deploy" on dev (I've pulled the latest from integration), what are the extra steps needed?

**Comment by ischneider** [comment]
@bartvde This only applies for new maps since the other stuff is stored in the client. This will require a migration. I'll look into it, but I think we already have one.

**Comment by bartvde** [comment]
good point @ischneider

**Comment by ischneider** [comment]
@bartvde I worked out a migration pretty easily. old maps should have all the baselayers, too.

This config change is on dev, now.

**Comment by jonpmarino** [comment]
badass.

**Comment by emloux** [comment]
Marking ready for deploy

**Comment by ischneider** [comment]
@bartvde for older maps, any saved base layer info seems to have been wiped out (on dev). I've saved the old config for those so I can fix it but want to make sure it's preserved on production. How is the selected base layer stored? (Didn't have time to dig for it)

**Comment by bartvde** [comment]
@ischneider it should just be visibility: true on the respective base layer
