### ISSUE TITLE
Incorporate a # of contributors counter to versioned editing GUI

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#934]
Once we have versioned editing piloted, we should incorporate a # counter for the number of users who have contributed to a StoryLayer open for versioning, similar to what Zooniverse uses for its crowdsourcing projects,

https://www.zooniverse.org/project/oldweather

**Comment by garnertb** [comment]
We currently show the number of contributors on the story layer detail page. Are you thinking it should also be shown in the actual editor?  If the the screen shot below works for now, I think we should close this.

![screen shot 2015-06-19 at 8 39 32 am](https://cloud.githubusercontent.com/assets/1141646/8253514/cecf8bfc-165e-11e5-98e5-4169388b01e8.png)

**Comment by jonpmarino** [comment]
@garnertb that's fine. But review @reynalddizon mockup for StoryLayer viewer page. He has a slightly different look for how this would be represented. May need mods but is something to start with

**Comment by garnertb** [comment]
@reynalddizon, can you add the screenshot of the geogit section in you're mockup to this issue?

**Comment by jonpmarino** [comment]
![storylayer](https://cloud.githubusercontent.com/assets/2573761/8253776/dd767560-1660-11e5-93a2-fc9056b843d6.jpg)

**Comment by garnertb** [comment]
Where's the contributors section?

**Comment by jonpmarino** [comment]
He's got that "edits" tab. presumably you could put "total commits" and "total contributers" there

**Comment by ChristopherTucker** [comment]
That is a MapStory, not a story layer

Chris
703-981-9373

**Comment by jonpmarino** [comment]
no, its the layer mockup. very similar to mapstory mockup though. Major different is storylayer has edit tab and will have different metadata fields. here is the mapstory mockup.

![mapstory](https://cloud.githubusercontent.com/assets/2573761/8254057/3cd42b18-1663-11e5-981c-f028a8086798.jpg)

**Comment by ChristopherTucker** [comment]
Maybe "edit history" tab?

Chris
703-981-9373

**Comment by reynalddizon** [comment]
Yeah Jon's right. That first screenshot is the layer mockup. I just used the same stock image for the frame on the left. This issue is related to Issue #1042.
