### ISSUE TITLE
Hide days and hours in annotations if MapStory is about years

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#937]
If the MapStory has one StoryLayer whose start-date and end-date fields are years, then the manage annotations window should only allow the user to select years and not months, days, hours, etc. We could still default the hours to 12:00 when only a year is chosen in order to make sure the annotation discretely matches with the features, but just hide all this.

Furthermore, obviously if a user then adds a StoryLayer with more precise time (e.g. days and not just years), then the annotation date-time selection should change to allow the user to select a more precise time.

**Comment by bartvde** [comment]
See also: http://help.mapstory.org/question/372/can-we-hide-days-and-hours-if-mapstory-is-about-years/?answer=373#post-id-373

**Comment by bartvde** [comment]
after looking into this there is no way with Ext to deal with different "precisions" in the date picker (so only show months or only show years). We should be able to leave out the time part though if it's not relevant.

**Comment by bartvde** [comment]
see: https://github.com/boundlessgeo/geonode/commit/3767f234738efb8746d4d796394e07f3b2807ccc

**Comment by bartvde** [comment]
deployed on dev
