### ISSUE TITLE
Open Help | How-To | Manual Links in New Tab

### ISSUE THREAD

**Issue by DanielJDufour** [MapStory/mapstory-meta#946]
When you are editing a MapStory, the links on the right side of the playback bar that look like "Help | How-To | Manual" should open in a new browser tab when left-clicked.  It would be frustrating for users, to have to go back and reload the webpage of their MapStory.

**Comment by ischneider** [comment]
@bartvde, @emloux this one seems like an easy target given the usability issues it presents. Can this be slotted in?

**Comment by bartvde** [comment]
sure I think there was even an existing ticket for this already

**Comment by emloux** [comment]
@ischneider I agree with Bart, this should be doable.

**Comment by jonpmarino** [comment]
thanks all!

**Comment by bartvde** [comment]
Done with: https://github.com/boundlessgeo/geonode/commit/c982026683cd1c4a05bcbdd5fbdb5ddb8d2053eb

Not yet deployed

**Comment by bartvde** [comment]
deployed on dev

**Comment by emloux** [comment]
Looks good, marking ready for deploy
