### ISSUE TITLE
Change "Abstract" for MapStories to "Description" and add prompt language

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#947]
This is a quick/small triage change. The purpose of this change is to indicate to StoryTellers that they should provide more description/narrative about their MapStory than 'abstract' connotes. We use 'abstract' for StoryLayers, which is right on. The abstract talks about the data. But for MapStories we want to see more narration and reflection than just an 'abstract'.

So, 2 quick changes, and a 3rd that would be slightly more work:
1. Change "Abstract" to "Despcription" for MapStory metadata
2. Add a subtitle to Description that says the following:

"Describe your MapStory in any way you find effective. A good description might answer some of the following questions: What is the purpose of this MapStory? Why did you decide to create it? What methods did you employ in creating it? What conclusions should a viewer take from it? What limits might it have that a viewer should keep in mind?"
1. Add the orange "question mark" symbol that links to this in the wiki: http://wiki.mapstory.org/wiki/Curation_Guide#Description

**Comment by ischneider** [comment]
As I noted in another conversation w/ Jon, adding textile markup processing to the field is done but we need to migrate any links to textile formatting or else they just show up as. While possible, the only logical text for the link I can generate is the link itself.

**Comment by ischneider** [comment]
I ran the textile conversion on dev. I suppose a note about textile formatting would help people?

**Comment by jonpmarino** [comment]
@ischneider is this done on dev to test?

**Comment by ischneider** [comment]
Yes, sorry. Here's an example of where the conversion went slightly astray: http://mapstory.dev.opengeo.org/maps/73/

**Comment by jonpmarino** [comment]
argh. yup

**Comment by DanielJDufour** [comment]
When you are in the composer view and open up the save box, abstract is still displayed.  It should say description:
![image](https://f.cloud.github.com/assets/4313463/1376495/ad10cd24-3a95-11e3-9afa-2159d2e9d026.png)

**Comment by ischneider** [comment]
@bartvde reassigning to you for this label text rename

**Comment by bartvde** [comment]
see: https://github.com/boundlessgeo/geonode/commit/69fd560d48347164abbb147794f1da7ca42d2134

@ischneider I did not dare to change the Django text string for Abstract, since I'm not sure where else it is used, so I just did an override, let me know if you see it differently.

**Comment by bartvde** [comment]
deployed on dev
