### ISSUE TITLE
Videos on media ribbons don't align properly

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#949]
For example, see - http://mapstory.org/mapstory/resource/students/

**Comment by ischneider** [comment]
deployed to dev

**Comment by jonpmarino** [comment]
@ischneider cool! using this as a test - http://mapstory.dev.opengeo.org/mapstory/resource/educators/ - videos seems to align well now, but i can't get more than one at a time to appear in the ribbon.

**Comment by ischneider** [comment]
That issue has been there a while apparently as I discovered it during testing. Looking at it now.

**Comment by ischneider** [comment]
Deployed this fix to dev.

**Comment by jonpmarino** [comment]
Money! it works, http://mapstory.dev.opengeo.org/mapstory/resource/educators/
