### ISSUE TITLE
Expanded search 'preview' cannot be minimized

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#950]
When you expand a StoryTeller preview in search, there is a minimize X. But for StoryLayers and MapStories there is no way to minimize them once they are expanded:

![grab9](https://f.cloud.github.com/assets/2573761/1363658/9b20edaa-382f-11e3-9c23-3421852d2046.jpg)

**Comment by jonpmarino** [comment]
Also, we should change "Abstract" in this expanded preview to "Description" for MapStories, so that it matches the change we made in MapStory metadata

**Comment by ischneider** [comment]
Can we just change both to 'Description'? It would be much easier.

**Comment by jonpmarino** [comment]
ABSOLUTELY.

**Comment by ischneider** [comment]
The minimize part is done (the icon was just hiding the 'X') and on dev.

**Comment by jonpmarino** [comment]
Nice!

**Comment by emloux** [comment]
Marking ready for deploy
