### ISSUE TITLE
In MapStory search, put "favorites" and "MapStories in progress" after the "Narrow by" fields...

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#951]

**Comment by ischneider** [comment]
Would it also make sense to add the favorites to the profile page?

**Comment by jonpmarino** [comment]
@ischneider yeah, i think so...if its not a heavy lift...

**Comment by jonpmarino** [comment]
@ischneider, see #951 and #927 as well...we could flip favorites/in progress in Search so they go below "Narrow By" and we could have 'favorites' sit on the profile...

**Comment by ischneider** [comment]
deployed to dev
