### ISSUE TITLE
Create a tooltip scroll-over for "notify me" options in 'edit profile'

### ISSUE THREAD

**Issue by jonpmarino** [MapStory/mapstory-meta#953]
Current we have a feature in 'edit profile' for 'notify me by email - never, immediately, once-a-day'. We don't explain what this means, though? What is being emailed? A scroll-over tooltip on these options should describe these buttons.

**Comment by ischneider** [comment]
Right now, the email notifications include:
- comment on user's layer/map or comment reply
- rating of other user on user's layer/map
- other user adding user's layer to their map

It will unfortunately take a bit more work to adjust this setting for messaging as that application automatically queues the email.

Any preferred language? Seems like a tooltip might be a bit small for this...

**Comment by jonpmarino** [comment]
@ischneider cool. Yeah, rather than a tooltip lets just add some text below the option buttons to explain.

"Your email digest will tell you when others comment on and rate your StoryLayers and MapStories, and when others use your StoryLayers to make a new MapStory"

**Comment by ischneider** [comment]
deployed to dev

**Comment by jonpmarino** [comment]
@ischneider  awesome! One small thing....change "rating" to "rate".

Also, we have never, immediately, and once-a-day. Is it difficult to add a weekly option? My sense is it would be a bit of work, in which case leave it for now. But if its a quick move, that might be a nice thing to do. Its coming to have a 'weekly digest' option I think.

**Comment by jonpmarino** [comment]
@ischneider still need change rating to rate

**Comment by ischneider** [comment]
Fixed the wording and deployed to dev.

I created #954 to track the weekly option.
