### ISSUE TITLE
add weekly option for email of activity

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#954]
From @jonpmarino 

> Also, we have never, immediately, and once-a-day. Is it difficult to add a weekly option? My sense is it would be a bit of work, in which case leave it for now. But if its a quick move, that might be a nice thing to do. Its coming to have a 'weekly digest' option I think.

**Comment by jonpmarino** [comment]
We need to re-evaluate the definitions of email notification going to user email address in light of redesign and versioned editing....
