### ISSUE TITLE
verify and/or fix time enabled upload

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#971]
depends on #961 and #962

**Comment by ischneider** [comment]
Mostly fixed with: GeoNode/geonode#1676

Need to investigate progress polling and async `run` step in geonode

**Comment by ischneider** [comment]
Also awaiting https://github.com/geoserver/geoserver/pull/777 to address text/number->date transformations

**Comment by ischneider** [comment]
This has evolved into a larger effort within the GeoNode community about fixing the uploader.

**Comment by garnertb** [comment]
According to my tests the uploader is now working fine for time enabled uploads.  Closing.
