### ISSUE TITLE
news item model

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#974]
For front-page news item content
- [ ] admin management
- [ ] fields
  - title
  - date
  - content
  - publish date

Questions:
~~Q: Any need for delayed publishing?~~ Yes
~~Q: Preferred format for content (markdown, textile, etc.)~~ sticking w/ textile

Assumptions:
- No uploaded content associated w/ item, links only

**Comment by ischneider** [comment]
Close when complete

**Comment by reynalddizon** [comment]
1. Delayed publishing -- Yes.
2. ~~We should add Textile editor for the diary content.~~ @ischneider added this to #975

**Comment by ischneider** [comment]
Added delayed publishing and a few admin improvements with mapstory/mapstory-geonode@d782b601043bb11ec9298791bd2450af06b6107f

> We should add Textile editor for the diary content.

@reynalddizon when requesting features, pay attention to which issue you are using and don't just throw in unreleated features. I did add the request for the textile editor to the diary issue: #975

**Comment by ischneider** [comment]
Initial work complete, open new issue for follow ups.
