### ISSUE TITLE
reactivate hopscotch tour and welcome modal in Composer

### ISSUE THREAD

**Issue by ischneider** [MapStory/mapstory-meta#982]

**Comment by ischneider** [comment]
initial work completed

**Comment by Coop56** [comment]
@davisc Do you know where the old initial work that was completed is?

**Comment by davisc** [comment]
@Coop56 https://github.com/MapStory/mapstory-geonode/blob/7e91d3d21bf39418417e270a273a881cc9e64672/mapstory/static/mapstory/js/editor_tour.js

**Comment by Coop56** [comment]
Thanks @davisc I'm working on this now.

**Comment by Coop56** [comment]
@jonpmarino @reynalddizon @davisc I just pushed my latest changes which include a fully functional 26 step tour that closes out this issue.

**Comment by jonpmarino** [comment]
@Coop56 @davisc @reynalddizon I do not see the tour in demo.  Could be a browser issue. Can someone else confirm?
