### ISSUE TITLE
don't clear previous tile until new tile is in

### ISSUE THREAD

**Issue by bartvde** [MapStory/mapstory-meta#994]
hey @ischneider not sure if you noticed this already but on playback with ol3 the tiles are cleared before the new ones are loaded, so this leads to a kind of flash in the playback

I'm guessing we'll need to address this somehow as well?

**Comment by ischneider** [comment]
It would be great if it was possible - never got around to looking at the approach.

**Comment by bartvde** [comment]
This is where the tiles get cleared: https://github.com/openlayers/ol3/blob/master/src/ol/renderer/canvas/canvastilelayerrenderer.js#L363:L368

**Comment by ischneider** [comment]
So without some core changes, we're stuck?

**Comment by bartvde** [comment]
right this needs core ol3 changes, I've opened up a ticket there for discussion

**Comment by bartvde** [comment]
@ischneider this does seem to be a can of worms on the ol3 side, so I am going to experiment with 2 separate layers anyway and see if I can use them in a LayerGroup

**Comment by bartvde** [comment]
The second layer in the layer group is the top-most layer

**Comment by bartvde** [comment]
So we would call updateParams on the first (bottom-most) layer in the layer group, and when the result is in we would move it to the second position again, and hiding the first layer.

**Comment by bartvde** [comment]
fixed with https://github.com/MapStory/story-tools/pull/10
